### ISSUE TITLE
Add Telemetry and Metrics

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#1]
Start building some telemetry into the system.

Actual requirements need to be determined.

**Comment by menski** [comment]
kafka metrics: https://kafka.apache.org/documentation/#monitoring

**Comment by meyerdan** [comment]
@menski I have now pushed the following branches:

* [1-metrics in zeebe](https://github.com/zeebe-io/zeebe/tree/1-metrics)
* [mertics in transport](https://github.com/zeebe-io/zb-transport)
* [mertics in logstreams](https://github.com/zeebe-io/zb-logstreams/tree/metrics)
* [mertics in util](https://github.com/zeebe-io/zb-util/tree/metrics)

With this, you get the following metrics:

* transport: bytes written / read
* fs log storage: bytes written / read
* stream processors: events processed / skipped
* actors: invocation count

Architecture is as follows:

* broker maintains counters in a memory mapped file
* the file can be mapped by the prometheus exporter

**Comment by menski** [comment]
thanks :heart:
