### ISSUE TITLE
Investigate if it is necessary to use a full fence in ChannelConsumerCondition#signal

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1000]
Currently we use an `getAndSet` in ChannelConsumerCondition#signal, which will end in a full fence.
We should validate if this is really necessary.

Be aware that if we do not use a fence here and for example the dispatcher uses a put ordered that it can happen that we signal an subscriber but he does not see it yet.

**Comment by menski** [comment]
It's okay for now. If we end up having problems on that level we should reinvestigate.
