### ISSUE TITLE
Rewrite the Zeebe Model API

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1007]
AT:
* fork the Camunda BPMN model API
* build a transformer for the model into the executable model for the Zeebe broker (this is part of the broker NOT the model API)
* improve fluent builder of the BPMN model API (more like the current Zeebe model builder) --> separate issue
* take the YAML workflow parsing from the Zeebe model API (use the BPMN model builder to create the workflow)

Motivation:
* the current Zeebe model Api is hard to extend (e.g. new BPMN symbols)
* Camunda Model API supports all BPMN symbols 
* it has a dependency to runtime models (e.g. Scala dependency for parsing conditions)

**Comment by ThorbenLindhauer** [comment]
Course of action:

- [x] Bring new model api into repository
- [ ] Add Zeebe attributes
- [ ] Expose Zeebe attributes in fluent builders
- [ ] Build/refactor model validator in model API
- [ ] Build model transformer in broker
- [ ] Use model transformer in broker
- [ ] Remove old model API
- [ ] Remove Camunda attributes => separate issue if it takes significantly longer than one hour

**Comment by ThorbenLindhauer** [comment]
Ideas for a validator/transformer:

* Build a walker that visits all elements in a BPMN model in top-down fashion
* Validators and transformers are visitor interfaces that are invoked by the walker
* Validators/transformers can be implemented for a type of element (e.g. service task, subprocess, flow node, ..)
* When an element is visisted, handlers are invoked according top-down to the element's type hiearchy (i.e. for a service task, a flow node handler is invoked first, and then service task handler)
* Transform context for any stuff we want to hand over between transformers

**Comment by ThorbenLindhauer** [comment]
Changes/degradations we accept for the time being:

* Inconsistencies in fluent API. This is no a mix of pure fluent style and lambdas.
* Model validation: No line numbers for validation errors. Didn't see an immediately obvious solution. Should be a separate ticket.
