### ISSUE TITLE
A message can be published idempotent

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1012]
AT:
* a message can be published with an id to ensure that the message is published only once (idempotent)
* when a message is published with the same id, name and correlation-key then it is rejected

Context:
* is some case it is important that a message is published/correlated only once (e.g. for a message start event)
* in order to make the publication easier (i.e. no need to store which message is successfully published), Zeebe take care of this
* a generic publisher for Kafka can use the Kafka's message position as id

**Comment by berndruecker** [comment]
Please make sure that this is also considered when starting new workflow instances via mesage: https://github.com/zeebe-io/zeebe/issues/1022
