### ISSUE TITLE
Correlate a message to a message start event

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1022]
AT:
* a message can be correlated to a message start event
* the correlation of a message start event has only a name but no correlation-key (no data to extract the key from)
* when a workflow is deployed which has a message start event then it opens a subscription on each partition
* if the workflow has a previous version then the message subscriptions of the previous version are removed 

Context:
* the subscriptionmust be opened on every partition because a message can be published on every partition based on the given correlation-key

**Comment by berndruecker** [comment]
Please make sure not to forget idempotent start in this case (https://github.com/zeebe-io/zeebe/issues/455)
