### ISSUE TITLE
Replace ReceivedEventsCollector in Gossip module with some more stable 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1023]
In the past we had a few times problems in the gossip test suite, which most of them are caused by the `ReceivedEventsCollector`.

Examples:

 * the ReceivedEventsCollector is registered as transport input listener, which means he can see the events before gossip has consumed it by itself. That causes some race conditions see for example https://github.com/zeebe-io/zeebe/issues/975
 * if a bug causes that gossip does not consume an event (did this on purpose) the test can be still green since ReceivedEventsCollector is used to check if custom event is received by the gossip node. The ReceivedEventsCollector will create an custom event from the received response even if the real gossip implementation does not consume the response at all.

**Comment by menski** [comment]
We will replace the gossip module
