### ISSUE TITLE
zb-parent/zb-bom 0.11.0 broken - zb-build-tools can not be found

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#1027]
After updating to the zb-parent 0.11.0 in spring-zeebe the build fails, because it tries to get zb-build-tools with the project-version of my project (0.3.0-SNAPSHOT) instead of the 0.11.0 released version.

I suppose there is something broken with the maven parent/bom structure.

--In spring-zeebe I added the dependency to zb-build-tools 0.11.0 manually, this works. You can remove the dependency to verify the problem--

Correction: does not work, I have to go back to zb-parent 0.10 to fix this

**Comment by jangalinski** [comment]
Well, spring-zeebe and camel-zeebe are zeebe extensions, so I thought this would be a good idea ... regarding common build tools, checkstyle, sonatype releases ... and it workd so far, it just broke after you merged all zeebe libs in the zeebe repo.

If you do not require zeebe parent, then please give me an alternative I can use (camunda-release?) and accept that I might not have build in style checks in my builds ...

**Comment by menski** [comment]
The issue you are facing is that as far as I know it is not possible to not specify the version of a plugin dependency. So I'm currently not sure how to solve this for you. 
https://github.com/zeebe-io/zeebe/blob/6129aaad443204816e12265fff2299a71aa1a9c6/parent/pom.xml#L212-L216

Also please be aware that with the latest release we also now have automatic code formatting based on google java format.
https://github.com/zeebe-io/zeebe/blob/6129aaad443204816e12265fff2299a71aa1a9c6/parent/pom.xml#L425-L428

As alternative you can use the camunda release parent as we also do in the bom.
https://github.com/zeebe-io/zeebe/blob/6129aaad443204816e12265fff2299a71aa1a9c6/bom/pom.xml#L12-L18

**Comment by jangalinski** [comment]
I guess you could separate bom and parent like this

```
                     camunda-release
                                   |
                             parent
                       /     <<uses>>   \
                   bom         <-         root
                                              /    \
                                        broker    client                                      
```

**Comment by jangalinski** [comment]
Ok, I will drop the zb-parent dependency
