### ISSUE TITLE
Stream processing: Handle staged records immediately for batching effects

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1036]
In workflow instance stream processing, we often generate a sequences of events, where one command generates n events (e.g. CREATE instance leads to CREATED -> START_EVENT_OCCURRED -> SEQUENCE_FLOW_TAKEN -> ..). 

Currently, we generate the first event, wait for it to appear on the log, then generate the second event, etc. A potential performance optimiziation would be to handle every published event immediately and then "commit" them in a batch to the log. That way we would do multiple steps in a workflow instance at once, by which we may be able to reduce overhead of accessing the workflow definition and workflow instance index state. 

The implementation should be data-driven, i.e. only introduce this added complexity if there is a useful performance gain.

**Comment by Zelldon** [comment]
superseded by https://github.com/zeebe-io/zeebe/issues/4255
