### ISSUE TITLE
Stream processing: Merge StreamProcessor and EventProcessor

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1048]
No need to distinguish on this level of abstraction. The stream processor can do all those things that the event processor does.

I will rename a couple of things from *event* to *record* along the way.

**Comment by ThorbenLindhauer** [comment]
Will postpone that to when we remove topic subscriptions. The distinction into the two interfaces is currently useful in `TopicSubscriptionManagementProcessor` and maintaining that class is not worth the benefit of the change.

**Comment by Zelldon** [comment]
@ThorbenLindhauer  since we removed the topic subscriptions with #1560 we could give this another try, right?
