### ISSUE TITLE
LongRingBuffer head & tail are not thread safe

### ISSUE THREAD

**Issue by max-neverov** [zeebe-io/zeebe#1067]
Both head and tail fields are volatile: 

https://github.com/zeebe-io/zeebe/blob/1b9b2e4555075137f34a80d0142a6cbf0ef1ddee/util/src/main/java/io/zeebe/util/collection/LongRingBuffer.java#L28

but operations like `head++` or `tail++` won't work correctly. 
I'd suggest to replace them with AtomicLong.

**Comment by Zelldon** [comment]
Thanks for opening this issue.

Be aware that this data structure should only being used in a one producer to one consumer fashion.

**Comment by max-neverov** [comment]
I see. 
I'm closing the issue than.
