### ISSUE TITLE
Find the best naming for broker-client

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1099]
* module name and Java package names
* see comment on https://github.com/zeebe-io/zeebe/pull/1090 for some ideas

**Comment by Zelldon** [comment]
Why not simply client or gateway ?

**Comment by npepinpe** [comment]
So broker-client is the client between gateway and broker, correct? And the user facing client will be the one connecting to the gateway. So what's wrong with broker-client? It's pretty descriptive. We could keep `io.zeebe.broker` as a package, and split it into `io.zeebe.broker.server` and `io.zeebe.broker.client`?

**Comment by menski** [comment]
We will merge the broker client to the gateway module, see #1137
