### ISSUE TITLE
Any idea for Timer Event solution 

### ISSUE THREAD

**Issue by deanwong** [zeebe-io/zeebe#1101]
I have watched the demo of your fantastic new workflow product from youtube. I'm a fan of BPMN and activiti (from jbpm3), and  my team still work on it. But when I saw zeebe I have to say it will be the next -generation workflow engine.
I found you have the planning to support more BPMN events. In my experience,  the timer (including timer delay) is not a easy part. The timer implementation in activiti is to use polling query to check jobs from database every 10s. If we have more than 100 million timers that will be a nightmare. Do you have any blueprint or idea for the time things?

**Comment by meyerdan** [comment]
Hi Dean,

thank you for your interest in Zeebe.

While the timer event is not implemented yet, we have plans to do so in the near future. The implementation will be along the following lines:

- Internally, Zeebe does stream processing and manages state in RocksDB. RocksDB is a sorted key/value store.
- Timers will be managed in RocksDB in a way that they are sorted by deadline by using a key with the layout [deadline,flownodeId].
- There is a stream processor per partition responsible to move forward all workflow instances inside that partition.
- This stream processor knows the deadline of the timer which will fire next (has the earliers dedaline), lets call this `nextDeadline`. When `nextDeadline` is reached, it will process this timer and process any other timers which may fire at the same time or immediately after by iterating through the keys in RocksDB. When all timers have been processed, it sets the `nextDeadline` to the timestamp of the timer which is next to fire.
- When a timer event in entered or cancelled, it's deadline is added or removed from RocksDB and the stream processor's nextDeadline is adjusted if necessary.

This way no polling is necessary.

Does that make sense to you?

**Comment by deanwong** [comment]
Hi Daniel

It's really helpful.
Do you have more detail plan for this feature? or event a scratch project?

**Comment by meyerdan** [comment]
Hi Dean,

Our current plan is to approach this during the 4th quarter of 2018. We have some base work to do regarding BPMN Support which we are currently working on, see the corresponding [milestone](https://github.com/zeebe-io/zeebe/milestone/10) and in parellel we are also working on supporting [message events and message correlation](https://github.com/zeebe-io/zeebe/milestone/9).

(As always, our plans could change based on requirements of some early adopters we are working with and based on how fast we can make progress.)

Hope it helps
