### ISSUE TITLE
WF instance stream processor may not create message subscription

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1102]
`CatchEventEnteringProcessor` extends `FlowElementEventProcessor`. There can be situations where we submit two "async continuations": 1) Fetch workflow 2) Fetch partitions for topic. The stream processor controller is not built such that it can handle more than one async future. After completion of the first future, it would concurrently continue with the next processing phase (execute side effects).

This will go away if we can get rid of the async concept in stream processing.

**Comment by menski** [comment]
async fetching of workflows and topics is removed with #1220  and #1235
