### ISSUE TITLE
Rename network.client configuration section

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1117]
In the TOML configuration file a section network.client exists.
https://github.com/zeebe-io/zeebe/blob/85ba7748dd6e5df545741fa33d20e42024c586a1/dist/src/main/config/zeebe.cfg.toml#L95

As this API is not anymore the public client API but rather the API used by the gateway to communicate with the broker cluster it should be renamed. And the documentation should be updated.

**Comment by jsam** [comment]
related #1099 ?

**Comment by menski** [comment]
Yeah we should probably find a new name before adjusting the setting name

**Comment by menski** [comment]
In the team meeting we decided to call this section `network.gateway` it will configure the gateway request endpoint on broker side. The embedded gateway configuration should be identical with the standalone gateway configuration and either embedded in the broker configuration under an own section, i.e. `gateway` or `embeddedGateway`, or be a separate file in the configuration folder.

**Comment by menski** [comment]
closed in favor of #1524
