### ISSUE TITLE
Bootstrap default topic and restart broker can break broker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1123]
The following test:

```java

  @Test
  @Ignore
  public void shouldReturnCreatedPartitionsAfterRestartDoNotWaitForSetup() {
    // given
    brokerRule.restartBroker();

    // when
    // have to do this multiple times as the stream processor for answering the request may not be
    // available yet
    apiRule.waitForTopic(DEFAULT_TOPIC, EXPECTED_TOTAL_PARTITIONS);

    // then
    assertResponse(apiRule.requestPartitions(), EXPECTED_TOTAL_PARTITIONS, DEFAULT_TOPIC);
  }
```

Can end in a endless loop of the following log statements:
```java

14:46:02.312 [io.zeebe.broker.clustering.base.bootstrap.BootstrapDefaultTopicsService] [0.0.0.0:51015-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
```

After zeebe is a static system we can check if the problem is still there. If Zeebe is a static system we will create only the partitions on bootstrap instead of the default topic like in this test.

The test is green if we wait for the default topic before restarting.

**Comment by npepinpe** [comment]
Maybe related to #1080 ? That also caused it to end in an endless NPE loop (although killing the broker and restarting would fix it, since it's a race condition).

**Comment by Zelldon** [comment]
Ah ok yeah could be. Thanks
