### ISSUE TITLE
Run JMH only on master and develop

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1143]
Since we building the jmh on every build (requires https://github.com/zeebe-io/zeebe/issues/1141) , we get fast feedback if we break the jmh sources. 
To improve the branch build execution time, we can skip the jmh execution on branches (since jmh will not fail anyway). We should run them on master and develop.

**Comment by menski** [comment]
I would run them on every develop/master push. This is easier to implement in the Jenkinsfile, allows developers to easy opt-in to run JMH on their develop branch and also shows the performance impact of every merged PRs on develop.

@Zelldon is that okay for you?

**Comment by Zelldon** [comment]
Yeah I think should be fine. 

> also shows the performance impact of every merged PRs on develop.

makes sense.

Thanks :)

**Comment by menski** [comment]
Skipping a parallel stage in Jenkins pipeline triggers a blue ocean bug which will not show any log output of the not skipped stage during the run. :woman_facepalming: 

https://issues.jenkins-ci.org/browse/JENKINS-48879

**Comment by Zelldon** [comment]
Awesome :see_no_evil: :laughing:

**Comment by Zelldon** [comment]
But normal jenkins output work right? Since we have no parallel builds (jmh and tests) then it should not a problem or? (besides the fact that blue ocean not work)

**Comment by menski** [comment]
Yes normal output works and is only the test log, but with parallel module builds :tada:
