### ISSUE TITLE
Need of undeclared properties

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1147]
I would like to know what are the necessity of the undeclared properties. 

Currently I'm not really sure if we need this and why. Furthermore It is a bit weird for me, that I can send any other Event to an API an this will result in no deserialization error (if no of the properties is required).

See for example the following test which checks this https://github.com/zeebe-io/zeebe/blob/develop/broker-core/src/test/java/io/zeebe/broker/transport/clientapi/ClientApiMessageHandlerTest.java#L374 .
This test only fails if the corresponding record for this request has an required property, for example the topic name.

The following line https://github.com/zeebe-io/zeebe/blob/develop/msgpack-value/src/main/java/io/zeebe/msgpack/value/ObjectValue.java#L112 makes it possible that undeclared properties are added.

**Comment by Zelldon** [comment]
Ok I assume this is for backwards compatibility, but anyway would assume if I send a complete different record that I get an error :sweat_smile:

**Comment by menski** [comment]
Our broker client uses Jackson for msgpack which will add additional attributes to the msgpack object. Jackson adds these attributes for type safety during deserialisation. Before this was also something we had to be aware from other msgpack implementations. Nowadays we could think about configuring the client to not do it is this is now full under our control. But as you said backwards compatibility is another reason.

**Comment by menski** [comment]
> if I send a complete different record that I get an error

Isn't this the case when an attribute doesn't have a default value?

**Comment by menski** [comment]
I hope the question why undeclared properties are need is answered. If not feel free to reopen. As we support default entries and cannot assume a specific serialization we will not change this behavior at the moment.
