### ISSUE TITLE
Add "duplicateFilter" on deployment

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1159]
Add some duplicate filtering like in Camunda BPM (e.g. https://docs.camunda.org/manual/7.9/user-guide/spring-framework-integration/deployment/) to allow for services to auto-deploy their owned processes at startup. Currently this leads to multiple versions being deployed or requires a manual deployment step.

**Comment by berndruecker** [comment]
Should probably get easier with the current RocksDB refactoring? Would be an awesome feature to get

**Comment by jwulf** [comment]
At the moment this is implemented in the Node.js client library - `deployWorkflow(filename, { redeploy: false })` will not deploy the workflow if it is already on the broker. This uses the `listWorkflows` gRPC method and compares based on the process id, so it doesn't compare the XML - only the presence or absence of a workflow with the process id.

In the current snapshot we have removed `listWorkflows` during the atomix refactoring so this client-side convenience will no longer work.

It is useful for programming clients that bootstrap the broker with the workflows, and it would be good to have this built-in to the broker.

**Comment by menski** [comment]
REST API docs for camunda deploy command https://docs.camunda.org/manual/7.11/reference/rest/deployment/post-deployment/

**Comment by MiguelPires** [comment]
For documentation purposes, I'll note down some decisions (and their reasoning) that were made about this feature:
* The filtering will check the deployed resources against their latest version and not against every version - this is more efficient and also makes it simpler in situations where the user rolls back to a previous a workflow (the "working" workflow is the always the latest)
* Duplicate filtering will be the default behavior - this seems like a benefit for most use cases; if this becomes an issue, a parameter can be easily added later without breaking backwards compatibility
* There will not be a parameter in the clients to toggle this feature on/off - the use cases where duplicate filtering might be problem are very specific and currently don't pose a problem; additionally, not having it makes this feature much smaller

**Comment by berndruecker** [comment]
Great!
