### ISSUE TITLE
Release build: increment protocol version with every minor release

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#118]
We populate the protocol version based on Maven properties (see https://github.com/camunda-tngp/camunda-tngp/commit/5efb0fd2a105ef955723eb9ce347bdbd39cca336). The protocol version should be incremented with every minor release, because a minor release means new features. If we can automate this step, then we can eliminate an error source.

Related to #117.

**Comment by npepinpe** [comment]
Let's revisit what we want to achieve here

**Comment by npepinpe** [comment]
Ok so my understanding is this is to avoid potential issues where we introduce schema changes but forget to update the protocol. I believe this would be covered by our update-tests, more specifically our `RollingUpdateTests`, which test updating one broker at a time. Any changes which causes incompatibility between versions should get caught there. 

I'm not sure how useful it would be to increment the version every time even when there are no changes. We rarely modify the protocol these days, and it also sounds like it might prevent brokers from talking to each other when using the embedded gateway, so I would close it for now.
