### ISSUE TITLE
unanimous naming/constraints for requestCapacity

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#1183]
I get the error 

     java.lang.IllegalArgumentException: requestCapacity must be >= 2: requestedCapacity=1
	at org.agrona.concurrent.ManyToManyConcurrentArrayQueue.<init>(ManyToManyConcurrentArrayQueue.java:68)

when creating a job subscription.

In the agrona array it must have a value `> 1`. However, in the `JobSubcriptionBuilder` it is checked for `> 0`.

This aside, it is confusing, the value is configured as "bufferSize", handed over as "jobFetchSize" and validated as "requestCapacity" ... what is it?

**Comment by menski** [comment]
Job workers where rewritten in 0.12.0 and this should not happen anymore.

>  what is it?

The buffer size of a job worker is the maximal number of jobs the worker will activate at any time to work on them in parallel. Its kind of an indication about the work capacity of the job worker.
