### ISSUE TITLE
Decide on workflow instance lifecycle

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1187]
Should a workflow instance have extra lifecycle states or should it just have the same lifecycle as any scope (e.g. sub process)?

Follow-up of #1119.

### Current situation:

All stateful elements (service tasks, sub process, ..), except the process, have the same lifecycle:

```
ELEMENT_READY (initial) ----------------| 
      |                                 |
      V                                 V
ELEMENT_ACTIVATED -----------> ELEMENT_TERMINATING
      |                        ^       |
      V               /--------|       V
ELEMENT_COMPLETING --/         ELEMENT_TERMINATED (final)
      |
      V
ELEMENT_COMPLETED (final)
```

The process has the same lifecycle with some additional events:

```
   CREATED
      |
      V
ELEMENT_READY (initial) ----------> CANCELING
      |                   /            |
      V                  /             V
ELEMENT_ACTIVATED -------      ELEMENT_TERMINATING
      |                /               |
      V               /                V
ELEMENT_COMPLETING --/         ELEMENT_TERMINATED (final)
      |
      V
ELEMENT_COMPLETED (final)
```

Previously, we also had `COMPLETED` and `CANCELED` as final states.

The current solution is not consistent, because it has extra states in some places but in others it does not.

### Options

1. Extra lifecycle states for workflow instance scope: `CREATED`, `COMPLETED`, `CANCELED`, `CANCELING` (?)
1. No extra lifecycle states for workflow instance. `ELEMENT_READY`, `ELEMENT_COMPLETED` and `ELEMENT_TERMINATED` are enough. 
1. Separate the workflow instance from the root scope, i.e. let the workflow instance have the lifecycle `CREATED -> COMPLETED` (plus states for cancellation) and let the root scope have the common element lifecycle. With this solution, workflow instance and root scope would have different keys.
1. Workflow instance scope does not share lifecycle states with the other elements, i.e. only have lifecycle `CREATED -> COMPLETED` (plus states for cancellation)

**Comment by ThorbenLindhauer** [comment]
We will sync with the operate team on this and get input from the user perspective.

**Comment by ThorbenLindhauer** [comment]
Feedback from @sdorokhova:

* Explicit states for workflow instances would be nicer to use and would feel less hacky
* Separate value types for workflow and element instances could be a useful thing

**Comment by menski** [comment]
@ThorbenLindhauer If I remember correctly in our last meeting with the operate team we decided that we do not need separate events for the workflow instance or?
