### ISSUE TITLE
Create meaningful exceptions in Java Client

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1192]
The API might hit a lot of possible errors in various commands.

E.g.  
`Caused by: io.zeebe.gateway.cmd.ClientCommandRejectedException: Command (PUBLISH) was rejected. It has an invalid value. message with id '0:0' is already published`

This needs to be mapped to a meaningful exception

E.g.  `MessageAlreadyPublishedException`

to allow users to react appropriately. 

It should be also very clear which exception is raised in case the broker cannot be reached at all so you can distinguish between a rejected command and a network problem.

**Comment by npepinpe** [comment]
I think this was greatly improved since then, with error messages quite close to this (not all of them unfortunately). I would prefer to have concrete issues for the messages which are still confusing if any - please open such issues when you come across one.
