### ISSUE TITLE
Create meaningful errors in Go client

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1193]
As in https://github.com/zeebe-io/zeebe/issues/1192 - this should also be present in the GoLang client

**Comment by eggsbenjamin** [comment]
@berndruecker @menski I would love to help with this. I can have a look through the code but is there anywhere that I can find a list of error types?

**Comment by menski** [comment]
@eggsbenjamin thanks for offering help on this one. But to achieve this we have to first clean up some stuff in the broker part, where most error messages are created. This means at the moment you can't do much in this issue. I will ping you in case you are still interested in this issue when it is actionable.

**Comment by npepinpe** [comment]
I think this was greatly improved since then, with error messages quite close to this (not all of them unfortunately). I would prefer to have concrete issues for the messages which are still confusing if any - please open such issues when you come across one.
