### ISSUE TITLE
Refactor/simplify StateController

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1195]
Currently, the `StateController` embeds the stream processors state and manages its lifecycle.

Goal of here is to:

1. Create `ZbRocksDb` class that extends `RocksDB` and exposes some protected APIs.
1. Refactor `StateController` such that it accepts a list of observers/listeners, which are called with a direct reference to the `ZbRocksDb` object when the database is opened. Evaluate if they need to know about the whole lifecycle (e.g. `onOpen`, `onClose`, `onOpening` to provide a chance to modify creation options, etc.)
1. Move helper methods of `StateController` (e.g. `foreach`) into `ZbRocksDb`.
1. Optionally see if `StateSnapshotController` and `StateController`can be merged now (if it makes sense).

**Comment by ThorbenLindhauer** [comment]
Some rough ideas for simplification and separation of concerns:

* The entry point to our persistent store should allow me to ask for column families with a certain name and key format. The returned object should allow me to make more high-level access operations.
* The same for sequences (use case: key generator, version tracking).

**Comment by npepinpe** [comment]
I like the idea. Maybe declare column families the way we declare properties in UnpackedObject.

**Comment by ThorbenLindhauer** [comment]
I have some concrete ideas in mind and would like to be involved in the implementation here. Maybe I can find some time at the end of the workday and create a quick spike.

**Comment by ThorbenLindhauer** [comment]
I threw some things together on branch `1195-spike-thorben`, see https://github.com/zeebe-io/zeebe/tree/1195-spike-thorben. Most important to me is the programming model when building composite things consisting of multiple column families. On the branch, the class [io.zeebe.broker.spike.NewElementInstanceState](https://github.com/zeebe-io/zeebe/blob/1195-spike-thorben/broker-core/src/test/java/io/zeebe/broker/spike/NewElementInstanceState.java) shows how I would like to work with rocksdb persistence. I did not look so much into things like when to allocate value objects and how to avoid array copies best.

**Comment by npepinpe** [comment]
I've been playing around with some ideas on the weekend, nothing ground breaking, but going in the direction of what I'd discuss with Thorben at some point (after Chris's working hours ;))

https://github.com/zeebe-io/zeebe/tree/np-rocksdb-api

Pretty much all in logstreams/rocksdb. It's by no means finished, and I think it's maybe a little difficult to see what I'm going for since I was just trying things, but in general the idea is:

1. Externalize serialization strategies so they're reusable, eventually/ideally composable
1. Have stateless objects as much as possible so we can reuse them
1. Have an API that allows avoiding allocations as much as possible (except for static things or the likes, things not called often).
1. Have objects that once instantiated are useful (e.g. `Class(a, b)` should be useful without having to call a `#onOpen` method or something). That requires the use of descriptors, which isn't super great, but I didn't spend hours either, so maybe there's a better way... :man_shrugging: ?
