### ISSUE TITLE
Consolidate record value interfaces into zb-protocol

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1200]
We currently have quasi-identical interfaces describing the various record values (e.g. `IncidentRecord`, `JobRecord`, etc.) in different modules (broker, gateway, java client, and soon the exporter). We should rather consolidate them into the `zb-protocol` module (as they are tied to our `ValueType` enum anyway), and each module can later specialize those by wrapping around them if need be.

This is strictly about interfaces, not implementations.

## Goals

1. Add minimal interfaces for all record values in `zb-protocol` (see `ValueType` enum for list of records).
1. Remove duplicated interfaces in other modules where applicable
1. Add wrapping interfaces in other modules where applicable

**Comment by Zelldon** [comment]
Should be done with latest refactoring's. Not really sure what you mean with "wrapping interfaces" or where we should need that. Reopen it if you see anything which needs to be done.

**Comment by npepinpe** [comment]
It was for cases where you couldn't use the same interface directly (for performance reasons or anything), but it's not case anymore so all good :man_shrugging:
