### ISSUE TITLE
Exporter stream processor writes log event for exporter positions regularly

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1214]
The exporter stream processor maintains a state with the last confirmed position for every exporter. These are at the moment stored in the rocks db state. But are not persisted on the log. This results in complete reexporting of all events in case the rocks db state is lost or a leader change happens. The reexport is not a problem in general as this is not violating the exporter contract of seeing every event *at least* once, but it is unnecessary.

To prevent this, the exporter should regularly persist these positions also on the log stream as an event to allow reprocessing on all nodes of the cluster.

An idea could be to write an event after a given number or records are exported or if a deadline is exceeded and something changed.

**Comment by menski** [comment]
I will postpone this issue until Nicolas returns from vacation. I'm currently not convinced that the approach of persisting a log entry with the current exporter positions is feasible regards recovery. If it is only useful in the case we have stream processors running on followers then we should postpone this until we have this functionality.

**Comment by Zelldon** [comment]
Hey @menski what do you think about the following. The exporters call update position this causes a command to be written, for example called update exporter position. The export mgr (streamprocessor) process this event and THEN updates his position(his state) an writes the event updated. This would fix the avoiding of dublicate position update if event is processed and the reprocessing as well or?

**Comment by menski** [comment]
Interesting idea, that could work. The one thing we want to prevent is that we flood the log with update exporter position records. So only update the position on the log once in a while, not sure how to solve this.

**Comment by Zelldon** [comment]
Aggree, but I'm sure we can solve this.

The easiest way would be to document this behavior and to say the user has to do batching and only update the position from time to time. 

Alternative would be to check the given position and check if the diff is larger then a defined batch size, then write the command.

**Comment by npepinpe** [comment]
It's true this is more of an optimization than anything, so we could do without. I think it's a nice optimization as far as users are concerned (i.e. don't send me the same events again and again), but since they already have to handle duplicate events then it's not *wrong*, just annoying I guess.

I could do without for now, although I think we should eventually do it, as again it's "nice" from a user POV.

**Comment by saig0** [comment]
We might need these events on the followers to decide if we can delete data. We can only delete data from the logstream if all exporters saw the data.

**Comment by saig0** [comment]
The current re-processing doesn't work with writing the exporter positions. We would need to restore the positions from the latest snapshot first. Then, scan the log stream for exporter records, update the positions and start processing on the lowest position.

**Comment by saig0** [comment]
I close this issue for now since we have currently no plan to implement read-only followers (building own snapshot instead of replication).
