### ISSUE TITLE
SubscriptionCommandSender loses commands if partition leader is not known

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1245]
The `SubscriptionCommandSender` is used in all message related stream processors to open and correlate message and workflow instance subscriptions.

The method [sendSubscriptionCommand](https://github.com/zeebe-io/zeebe/blob/develop/broker-core/src/main/java/io/zeebe/broker/subscription/command/SubscriptionCommandSender.java#L174-L177) sends an command to an specific partition leader.
If the leader is currently not known then the method returns with `true`, without sending the command.
If we return `false` then execute side effects in the corresponding processor will be executed again and this will retry the send command method.
Probably, this is not the best solution. We could store the pending commands and send them if the leader comes back.

This explains also why we have from time to time failing message correlation tests.

**Comment by saig0** [comment]
Implementation context: the stream processing should not stop if a leader is currently not known. All message commands have a retry mechanism. So it should not happen that a command is lost.

**Comment by Zelldon** [comment]
I think you're right. I had a bug in my working branch, that the leader for partition 0 was never known.  Fix this with this commit https://github.com/zeebe-io/zeebe/pull/1255/commits/665c86c528b1acaaad43df47eb5df58587e31c68#diff-3587819d302468b505727f236c19d943L42 .
