### ISSUE TITLE
In the IT test it seems something leaks still memory

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1260]
With https://github.com/zeebe-io/zeebe/pull/1256 the releasing of resources in the clustering tests went better,
but still we have some resources which can't be collected.

![file](https://user-images.githubusercontent.com/2758593/45076427-8da47000-b0ea-11e8-95f9-66f64279d5d8.png)

In the normal IT tests the garbage is around 25-50 (which can't be released) in the clustering test around 80-100. I assume that there is something in the broker or client, which is not released correctly.
We should take a look into that.

**Comment by menski** [comment]
I didn't find anything interesting. If I run the IT suite with a max heap of 92MB the clustering tests use around 60MB and the single broker tests 20MB which is kind of expected as the clustering tests use 3 brokers. I will close this issue until we see a more specific problem.

![2018-09-06-02-18-18](https://user-images.githubusercontent.com/516296/45124862-3f37b580-b16c-11e8-9837-ddbec2ff0620.png)
