### ISSUE TITLE
problem with java9 and jaxb

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#1267]
I had serious issues deploying an bpmn-xml resource due to class-not-found  exceptions.
It turned out that my IDE was set to java9.
The default sun-jaxb-impl does not work with java9 anymore ... so an alternative solution should be found if zeebe should nit get stuck on java8.

**Comment by menski** [comment]
Hi Jan,

thanks for reporting. Jaxb is already gone on latest develop where we replaced our custom model API with a fork of the Camunda model API which seem to work with Java 10.
