### ISSUE TITLE
Numerical exporter arguments are returned as double from map

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1304]
If I configure a exporter with numerical arguments like a port and want to retrieve the port from the configuration map on startup a double value is returned. This is unexpected for the user.

**Comment by npepinpe** [comment]
I ran into this previously, but it should correctly instantiate a configuration class where the property is an int. The only thing is if you access the map directly, it will be a Double. This goes against the Toml parser's documentation, but I don't see what we're doing wrong here...

imo I'd rather not make an exception, or muck about and cast types, so I'm fine with it instantiating classes correctly where the final field will be an int, for example. afaik that should work

**Comment by npepinpe** [comment]
This isn't the case now that we've moved away from the Toml parser.
