### ISSUE TITLE
Workflow transformation assumes presence of optional BPMN property

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1306]
A sequence flow can be (optionally) added to the collection of incoming and outgoing flows of their respective source and target.

The workflow transformer currently assumes that this collection is always consistently populated, but this need not be the case.

**Comment by menski** [comment]
We have to check if it still is an issue.

**Comment by saig0** [comment]
I checked it and did not find any issue. Works as expected :)
