### ISSUE TITLE
Create generic MongoDB exporter

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1331]
Adds an exporter which simply pushes the JSON representation of records to MongoDB as documents.

**Comment by npepinpe** [comment]
Putting this on hold until @saig0 is back; since the main consumer of this was the Simple Monitor, and I feel like sqlite might be a better idea for it. We can discuss it later.

**Comment by asaf** [comment]
@npepinpe @saig0  I have an implementation of this, it is highly inspired by ES exporter as they are both acting almost the same. if you want, we can host this under `io.zeebe.exporters` package, otherwise I'll open a new repo for this.

Thanks.

**Comment by saig0** [comment]
Awesome :rocket: 

Please create a new repository for your exporter. Everything inside the Zeebe repository is maintained by the Zeebe team. 
You can add your exporter to the list here: https://github.com/zeebe-io/awesome-zeebe to make it more visible to the community.

**Comment by asaf** [comment]
@saig0 agreed!

**Comment by asaf** [comment]
for those who need this: here: https://github.com/crossid/zeebe-mongo-exporter
