### ISSUE TITLE
Switch to low level elasticsearch rest client

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1343]
The exporter currently uses the high level rest client which adds a lot of dependencies. To reduce this not required overhead use the low level rest client which has all features required for the exporter and a smaller footprint.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low.html

**Comment by npepinpe** [comment]
I pushed a branch with a working prototype that uses the low level client. My experience so far is that the low level client is extremely low level, so there needs to be a little more polishing here, it already works/tests are green. Lots of casting to `Map<String, Object>` though :sweat_smile:
