### ISSUE TITLE
Migrate Workflow cache and repository to rocks db

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1353]
blocks #1188

**Comment by Zelldon** [comment]
| column family           | Key                   | Value            | Comment                                                                                                                        |
|-------------------------|-----------------------|------------------|--------------------------------------------------------------------------------------------------------------------------------|
| workflowKey             | latestKey             | nextKeyValue     | To generate next workflow key                                                                                                  |
| workflowVersion         | bpmnProcessId         | nextVersionValue | To generate next workflow version                                                                                              |
| workflows               | workflowKey           | deployedWorkflow | stores the deployed workflow entity                                                                                            |
| workflowsByIdAndVersion | bpmnProcessId:Version | workflowKey?     | stores the workflow key (or also the entity?) for the bpmnProcessId and version. Latest is only bpmnProcessId without version. |

**Comment by ThorbenLindhauer** [comment]
We went with storing multiple copies of the XML in the different column families (as compared to storing references via keys), because it was easier to build at this point. No performance/memory considerations were taken into account so far. We can change the implementation in the future when we may have learned new things.

**Comment by Zelldon** [comment]
Thanks @ThorbenLindhauer  forget to mention that.
