### ISSUE TITLE
Evaluate performance impact of payload mapping in a workflow

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1360]
Goals:

* Understand the performance of workflows that use input/output mappings and identify limiting factors
* Decide if performance optimizations need to be applied, e.g. in the msgpack-json-path component

Scenarios to test:

* A workflow with `s` sequential service tasks and payload of size `p`
  * Variant 1: `overwrite` output mappings on all tasks, such that no payload is ever merged/mapped
  * Variant 2: Tasks use `merge` output mapping (default when no mappings are defined)
  * Variant 3: Every task has `o` output mappings
  * Variant 4 (optional): Every task has `o` input and output mappings
* Measure: Throughput of workflow instances

Use different configurations of `s`, `p` and `o`.

**Comment by ThorbenLindhauer** [comment]
If msgpack-json-path is the limiting factor, one limiting factor seems to be the performance of `MsgPackTree#merge`. Optimizations could be avoiding the method or improving it.

**Comment by npepinpe** [comment]
JSON path was removed from our project, so I will close this - we can still evaluate the impact of I/O mappings with our new expressions but that should be a separate issue.
