### ISSUE TITLE
Create a central constant for the ByteOrder

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1386]
Currently we use on the state management side every where `ByteOrder.Little_Endian`. We should use an own constant, so we could easily change the ordering and we are sure that use the right one.

See #1364

depends on #1195

**Comment by saig0** [comment]
Please keep in mind that the ByteOrder may also influence the ordering of the entries. For example, if I have a column family like <deadline|some-key> then the order is reversed by default when the ByteOrder is `Little_Endian`.

**Comment by Zelldon** [comment]
Finally with help of @saig0 reproduce the problem. I also now understand why the current tests didn't fail.

### Funny Example:

The following test will not fail even with `LITTLE_ENDIAN`
```java
@Test
  public void shouldFindMessageBeforeTime() {
    // given
    final long now = ActorClock.currentTimeMillis();

    final Message message = createMessage(1L, "name", "correlationKey", "{}", "nr1", 1234);
    final Message message2 = createMessage(2L, "otherName", "correlationKey", "{}", "nr2", 4567);

    stateController.put(message);
    stateController.put(message2);

    // when
    final long deadline = now + 2_000L;

    // then
    final List<Message> readMessage = new ArrayList<>();
    stateController.findMessagesWithDeadlineBefore(deadline, readMessage::add);

    assertThat(readMessage.size()).isEqualTo(1);
    assertThat(readMessage.get(0).getKey()).isEqualTo(1L);
  }
```
This test will fail:
```java
@Test
  public void shouldFindMessageBeforeTime() {
    // given
    final long now = ActorClock.currentTimeMillis();

    final Message message = createMessage(1L, "name", "correlationKey", "{}", "nr1", 1234);
    final Message message2 = createMessage(2L, "otherName", "correlationKey", "{}", "nr2", 2000);

    stateController.put(message);
    stateController.put(message2);

    // when
    final long deadline = now + 2_000L;

    // then
    final List<Message> readMessage = new ArrayList<>();
    stateController.findMessagesWithDeadlineBefore(deadline, readMessage::add);

    assertThat(readMessage.size()).isEqualTo(1);
    assertThat(readMessage.get(0).getKey()).isEqualTo(1L);
  }
```

### Explanation

We have a message with deadline `1234`, which is in binary `00000000 00000000 00000100 11010010` (BIG ENDIAN).
The number `4567` is in binary `00000000 00000000 00010001 11010111` (BIG ENDIAN)
and the number `2000` is in binary `00000000 00000000 00000111 11010000` (BIG ENDIAN).

If we store the values in LITTLE_ENDIAN they are reversed. RocksDB will start left (compare bit per bit probably) and order ascending the entries, which means `2000` will stay before `1234`. In the find method we iterated until the given deadline is reached. This means we will immediately stop and return no findings.

If `4567` is used instead of `2000` then the ordering is correct since even if we reverse the bits this value is larger then `1234`.

**Comment by Zelldon** [comment]
### Update:

One of the problem is why we have the byte wise correct ordering, is that the `Long.reverseBytes` which is used by agronas `UnsafeBuffer` reverses the bytes not the bits. This means we will have `LITTLE_ENDIAN` byte wise not bit wise.

```java
    /**
     * Returns the value obtained by reversing the order of the bytes in the
     * two's complement representation of the specified {@code long} value.
     *
     * @param i the value whose bytes are to be reversed
     * @return the value obtained by reversing the bytes in the specified
     *     {@code long} value.
     * @since 1.5
     */
    public static long reverseBytes(long i) {
        i = (i & 0x00ff00ff00ff00ffL) << 8 | (i >>> 8) & 0x00ff00ff00ff00ffL;
        return (i << 48) | ((i & 0xffff0000L) << 16) |
            ((i >>> 16) & 0xffff0000L) | (i >>> 48);
    }
```

This explains why `1` and `2` is in the correct order but not `1` and `256`.
