### ISSUE TITLE
RocksDB iteration seems to be slow

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1391]
It seems that the RocksDB Iterator is not fastest, for example take a look in the WorkflowStateTest, where the iterator is used to find all subscriptions.

https://github.com/facebook/rocksdb/issues/1263 they also mentioned a perf problem with the Iterators. The main problem is that the key and values are copied. 

Maybe we find a solution to bypass this, before that we should write some performance test to find out if this is a real issue for us.

**Comment by menski** [comment]
Current profiling indicates that Zeebe spends 75% of its time in the rocksdb iterator

**Comment by menski** [comment]
As discovered the reason we spend most of the time iterating was actually a bug introduced in 0.15.0 which did not stop iterating after the prefix was exceeded, see #2080.

After this change we now spend around 70% of our time in `RocksDB#get` which is kind of expected.

**Comment by Zelldon** [comment]
Ok :+1: more or less yes, as I have written above we could improve on that. Drawback would be that we use more space.

**Comment by npepinpe** [comment]
We should first implement #3959 and then re-evaluate if this is an issue

**Comment by npepinpe** [comment]
I would propose instead to close this in favour of https://github.com/zeebe-io/zeebe/issues/4002 and whatever outcome we find there.
