### ISSUE TITLE
Evaluate performance impact of RocksDB access patterns on workflow instance throughput

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1393]
Current situation:

* We access RocksDB during workflow instance stream processing driven by how it is most convenient to implement and not so much by performance

Goals:

* Identitfy limiting factors of workflow instance throughput caused by how we use RocksDB.
* Decide if we need to optimize for performance.

Proposed test scenario:

* A workflow with a couple of tasks
* A lot of instances running concurrently (so that every handled events requires different element instances)

Measure:

* Throughput of workflow instances

Optimization ideas:

* Whenever we process an event, we retrieve the current element instance and scope instance from RocksDB by default, although the handler may not actually need them.
* We currently flush updates to RocksDB for all selected element instances after an event was handled, regardless if the element instance was actually updated. We can improve this to only update instances with changed values.
* Batch handling of events in a single workflow instance to improve access locality

**Comment by menski** [comment]
Closed as we are currently not have any indication of problems. If we discover new problems during performance tests we will create specific issues.
