### ISSUE TITLE
Allow expression language in task type

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1412]
My use case is best explained to what I just did that on C# using C7 /External Tasks:
 
•	I try to give a synchronous response to an incoming REST request – even if workflow instance with External Tasks is involved
•	Therefor I basically wait in the thread serving the REST request if a workflow instance reaches a certain point (“Trigger Synchronous response”):
 
![grafik](https://user-images.githubusercontent.com/1217596/46343375-cda13900-c63d-11e8-8d49-841ea8a32d0e.png)

•	When using External Tasks I have to make sure that exactly the node that started the workflow instance also gets that task for execution – and I do this by using Expression Language in the task topic:
 
 
![grafik](https://user-images.githubusercontent.com/1217596/46343383-d134c000-c63d-11e8-8b35-1c435c3b1e5e.png)

 
I compare this to dedicated reply queues as you would use in e.g. RabbitMQ if you want to have a synchronous response.
 
Currently I cheat in my Zeebe demo (https://github.com/berndruecker/flowing-retail/blob/master/rest/java/payment-zeebe/src/main/java/io/flowing/retail/payment/rest/PaymentRestHacksControllerV4.java#L57) and simply subscribe to the task (as I do not have a cluster). Response times are quite good (<30 ms in total) – so this is cool. But to make it real the 
feature request is to support some kind of Expression Language within the Zeebe Task Type.

**Comment by npepinpe** [comment]
I believe this is done? @saig0 - if so please close :slightly_smiling_face:

**Comment by saig0** [comment]
Yes. We implemented the expression support for the job type in #3802.
