### ISSUE TITLE
Add sample exporter and guide

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1473]
We should create a sample, reference exporter, and documentation along with it on how to:

1. Implement a custom exporter
1. Testing your exporter
1. Configuring your exporter
1. Caveats, recommendations, best practices, etc.

Related to #1181

**Comment by menski** [comment]
We now have two blog posts:
- https://zeebe.io/blog/2019/05/exporter-part-1/
- https://zeebe.io/blog/2019/05/exporter-part-2/
