### ISSUE TITLE
Write tests for JobStateController

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1499]
I would like to have some tests for the JobStateController. 

For example for #1386 I wished I had tests for the `forEachTimedOutEntry` so we can ensure that the ordering is correct.

**Comment by Zelldon** [comment]
Then we had realized that the following does not work:
```java
  @Test
  public void shouldGetJobsInOrder() {
    // given
    stateController.activate(1, createJobWithDeadline(100L));
    stateController.activate(2, createJobWithDeadline(256L));

    // when
    List<Long> jobKeys = new ArrayList<>();
    stateController.forEachTimedOutEntry(150L, ((key, record, control) -> jobKeys.add(key)));

    // then
    assertThat(jobKeys).hasSize(1);
    assertThat(jobKeys).containsExactly(1L);
  }
```

**Comment by npepinpe** [comment]
I agree we should have unit tests for `JobStateController`, but knowing our tests, we probably wouldn't have caught it, since we don't usually use randomized test input, so we might well have written deadline 1000 and 1001. So I guess my point here is more, should we use randomized test input sometimes?

**Comment by Zelldon** [comment]
> we probably wouldn't have caught it, since we don't usually use randomized test input,

I agree, but if someone else writes the test the chance is higher that he choose other values than me. :) 

I think sometimes it makes sense, but if they spot errors it can be hard to reproduce.

**Comment by npepinpe** [comment]
Yeah I know, it's also not great, but I was just wondering how we could completely have prevented this without picking the right values. I can work on this once I'm through with training.
