### ISSUE TITLE
Reiterate control message request handling

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#151]
In the course of #121, we implemented an endpoint for control messages in the broker. It works such that one message is handled at a time. Message handlers can perform asynchronous work. The endpoint ensures that no other message is processed until the asynchronous work has completed. Handler implementations currently rely on this behavior (e.g. through object reuse).

There also is a timeout facility if asynchronous work does not complete. When the request times out, an error response is returned and a new request will be handled. However, the asynchronous work is not actively interrupted. That means, it is possible that two or more requests are handled at the same time. Also, if the timed out request eventually completes, the client receives a second response in addition to the error response.

**Comment by saig0** [comment]
ControlMessageHandler is rewritten and can deal with concurrency - #742.
