### ISSUE TITLE
Only export node id and not host:port in client topology response

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1516]
The topology exposed to the client should contain the following information:

- list of brokers with their node id and the hosted partitions and state of the partitions
- the cluster size
- the partition count
- the replication factor

**Comment by menski** [comment]
Topology now exports all the information requested

```
message BrokerInfo {
  int32 nodeId = 1;
  string host = 2;
  int32 port = 3;
  repeated Partition partitions = 4;
}

message TopologyResponse {
  repeated BrokerInfo brokers = 1;
  int32 clusterSize = 2;
  int32 partitionsCount = 3;
  int32 replicationFactor = 4;
}
```

**Comment by Zelldon** [comment]
I assumed the intent was to remove host port  and only have node id in the topology?
