### ISSUE TITLE
GatewayStartup fails because gateway is started on each broker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1525]
I dont know why this fails now :man_shrugging:

**Comment by menski** [comment]
The file https://github.com/zeebe-io/zeebe/blob/develop/qa/integration-tests/src/test/java/io/zeebe/broker/it/gateway/GatewayStartup.java does not match surefire naming conventions and is therefore not executed (it misses the `Test` suffix).

I think we can delete this test as I don't see value in it.

**Comment by Zelldon** [comment]
But yesterday it worked ? :laughing:
