### ISSUE TITLE
I can use zbctl inside the docker image without specifing the broker address

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1532]
Currently I have to specify the address of the broker to run zbctl inside the docker container like this

```
$ docker exec zeebe bash -c 'ZB_BROKER_ADDR=$(hostname -i):26500 zbctl status'
```

The reason is that on startup the broker binds to the external interface of the Container to get the topology announcement right to use it with an external gateway. 

Possible solution is to bind the embedded gateway to the local or all interfaces. The zbctl inside the container should work out of the box.

**Comment by berndruecker** [comment]
I wonder why the variable ZB_BROKER_ADDR for zbctl isn't simply set in the startup within the docker container?

https://github.com/zeebe-io/zeebe/blob/develop/docker/utils/startup.sh

**Comment by menski** [comment]
We don't need that, I tested it that if we configured the gateway to bind to all interfaces zbctl just works as expected.
