### ISSUE TITLE
Naming in Model api Workflow vs Process

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1574]
In the past we decided to go with the term workflow instead of process.
This was also the reason we renamed a lot of API's, for example `Bpmn.createExecutableProcess("process")` to `Bpmn.createExecutableWorkflow("process")`. 

In the last quarter we did a lot of changes, for example the Bpmn model api was refactored.
This means the name changed again to `Bpmn.createExecutableProcess("process")`. 

Is a reason behind that?
I assume it was done because in BPMN it is called process?

But it seems a bit inconsistent if I have something like this:

```java
Bpmn.createExecutableProcess("process")
            .startEvent()
            .serviceTask("serviceTask", t -> t.zeebeTaskType("foo").zeebeTaskRetries(3))
            .endEvent()
            .done();
```

Which creates a `final BpmnModelInstance modelInstance` (this btw was a WorkflowDefinition before).

And than add this to a deployment which says `workflowModel`

```java
        workflowClient.newDeployCommand()
            .addWorkflowModel(modelInstance, "workflow.bpmn")
            .send()
            .join();
```

**Comment by menski** [comment]
As the BPMN model API represents the BPMN meta model it should follow the naming of BPMN and not Zeebe in my opinion.

**Comment by Zelldon** [comment]
Yes aggree, but then I would expect to have a method like addBpmnModelInstance or something similar instead of add workflow model.

**Comment by menski** [comment]
I don't have a strong opinion on that matter, feel free to provide a pull request for this.

**Comment by npepinpe** [comment]
I believe this will come back soon (or so I've heard :wink:), but there's probably not much use keeping this opened until we get direction from product.
