### ISSUE TITLE
Gateway spawns many grpc threads

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1580]
On executing performance tests we saw that grpc spawns many threads, we should found out why.

[threaddump.txt](https://github.com/zeebe-io/zeebe/files/2525352/threaddump.txt)

**Comment by npepinpe** [comment]
By the default, the gRPC gateway uses a cached thread pool, which creates as many threads as it needs (unbounded) and caches them. So under very heavy load, it would create many, many threads. It's possible to configure it to use your own executor. What is the goal in the issue? If it was to explain it I would say we achieve that now ;)

**Comment by Zelldon** [comment]
yeah it was quite confusing the first time but this was two years ago so this is already clear to me :sweat_smile:
