### ISSUE TITLE
Duplicate "type" of BPMN file required

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1605]
For deployment I have to do (c# - but it boils down to the protobuf definition):

           client.DeployWorkflow(new DeployWorkflowRequest
           {
               Workflows = {
                   new WorkflowRequestObject {
                       Name = "test.bpmn",
                       Type= WorkflowRequestObject.Types.ResourceType.Bpmn,
                       Definition= ByteString.CopyFrom(File.ReadAllBytes("test.bpmn"))
                   }
               }
           });

Now I have to define the name - and it has to have the ending ".bpmn" - otherwise I end up with an error

Status(StatusCode=Internal, Detail="Cannot resolve type of resource 'test'.")

Why is that? I have to define the type via enum as well. Shouldn't that be sufficient?

**Comment by ThorbenLindhauer** [comment]
@berndruecker we fixed this such that by adding a third resource type `FILE` and giving two options:

1. The resource type is explicitly given (i.e. `BPMN` or `YAML`). Then the resource name can be any value.
1. The resource type is auto-detected (i.e. `FILE`). Then the resource name must match the pattern `*bpmn` or `*.yaml`.
