### ISSUE TITLE
I can declare an output mapping to map variables with propagating semantics to higher scopes

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1613]
With #1610, the job payload is propagated depending if output mappings are set or not. If an output mapping is set then the payload is only available on the local scope and need to be propagated explicitly by using output mappings on the activity. 

AT:
* if an output mapping is set then the variable is propagated to higher scopes (i.e. up to the scope where the variable is defined or to the workflow instance)
* if no output mapping is set for the variable then the variable is not propagated 
* if an activity has no output mappings then the complete job payload is propagated
* BUT if a sub-process has no output mapping then no variable is propagated (-> within a workflow instance variables are propagated on creation)
* I can also partially update a variable value (JSONPath expression in target variable value)
* if an activity has an output mapping and the variable is only set in the local scope (i.e. created from input mapping) then the variable is propagated

**Comment by saig0** [comment]
We should improve the tests for activity and sub-process output mappings. Currently, the different cases are hard to find and read.
