### ISSUE TITLE
I can update payload with local semantics

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1617]
With #1616, we change the behavior of the update payload command in a way that variables are propagated by default. So we need an optional parameter in the command to not propagate the variable and set/update them in the given scope locally.

AT:
* I can create new variables or update the value of existing variables in the given scope
* the variables are not propagated if they don't exist in the given scope

**Comment by npepinpe** [comment]
As we've migrated everything to use variables and everything to be an element, I would propose that we do not piggy back on the `WorkflowInstanceRecord` any more for this.

The only information needed for this command is now:

- the element instance key (or arguably the variable scope key)
- the payload itself
- the new flag on whether or not to propagate the changes up

While I'm not super happy about introducing a new record type, we would not be able to remove the `payload` property from the `WorkflowInstanceRecord` if we want to keep using this.

There are two options to implement this then:

1. Create a new record type, `VariableDocumentRecord`, with intents `UPDATE` and `UPDATED`.
2. Unpack the `UpdateWorkflowInstancePayloadRequest` in the gateway and create multiple `VariableRecord.SET` commands (to avoid the gateway having to figure if its an update or create). The one issue I see here though is how to handle propagation (add a "local" field to `VariableRecord` just for the `SET` intent, and which would always be true for `UPDATED` and `CREATED`?).

Side note: this is also related to #1970, as part of what the current `UpdatePayloadHandler` does is update failed records, which might not be necessary any more.

**Comment by npepinpe** [comment]
Splitting this into multiple PRs:

* [ ] Add new `VariableDocumentRecord` to handle variable state updates (see #2070)
* [ ] Replace `WorkflowInstanceRecord#PAYLOAD_UPDATE` and related by `VariableDocumentRecord#UPDATE` and related
* [ ] Rename `UpdateWorkflowInstancePayload` command to `SetVariables` and update go and java clients
* [ ] Export new record to Elasticsearch
