### ISSUE TITLE
Remove merging mappings

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1620]
* in code

**Comment by ThorbenLindhauer** [comment]
I will keep the changes in our json-path library introduced with https://github.com/zeebe-io/zeebe/commit/b001b2a8444624d99c194f04ba212c7387b552d3

* We may need this for other features down the road, maybe already for the changes to input/output mappings we will make
* They improved code quality in my opinion

**Comment by menski** [comment]
I think they also fixed some bugs :+1:
