### ISSUE TITLE
Investigate and document limitation of data path length

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1622]
A customer just reported problems when Zeebe was running in a path with a quite long directory name (~200 characters) on windows:

RocksDbException: Cannot write snapshot - access is denined
org.rocksdb.CeckpointcreateCheckpoint(Checkpoint.java 51)

The problem went away when Zeebe was moved to d:\Zeebe.

While it might still be a file access rights problem it is unlikely in this case - so we should check if the path length can be a problem and document that.

If required I can share the original failing path internally (contains customer name)

**Comment by menski** [comment]
We will close this issue, it seems more like a general Windows issue with long directory paths and not Zeebe specific. Feel free to reopen if you disagree.
