### ISSUE TITLE
README -  maven batch shows 0.11.0

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#1638]
but the linked resources are 0.13.0

seems like the zeebe-distribution link does not work with the batch?

**Comment by Zelldon** [comment]
Hey Jan, 

i think this is a browser cache problem. 
After hard reloading my browser I see the new badge :) 

Thanks for reporting.

Greets 
Chris

**Comment by jangalinski** [comment]
Does not change for me, even in anonymous new window ...

**Comment by menski** [comment]
I think this is fixed, let me know if you still have issues after refreshing your local cache.
