### ISSUE TITLE
Document client gRPC protocol 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1669]
AT:

- docs contain section describing the interaction protocol between gRPC client and gateway
- for every RPC the request response messages are explained with required and default values
- there should be some use cases described and the required message interchange
- goal is it to ease the development of new clients and the use of plain gRPC stubs in any language if not specific client wrapper is available

**Comment by npepinpe** [comment]
I think it will be useful in general as part of the Useful Error Messages milestone. Feel free to remove if you don't think so
