### ISSUE TITLE
Remove ZbMap

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1670]
Since #1573 the ZbMap is no longer used, we can remove it.

**Comment by npepinpe** [comment]
Does this mean we have no more stream processors using the old snapshot format?

**Comment by Zelldon** [comment]
> Does this mean we have no more stream processors using the old snapshot format?

More or less. The KeyGenerator is still used with the old SnapshortSupport stuff, but this is all of my todo list :) Will first do #1387 then we can remove/refactor the snapshoting stuff.
