### ISSUE TITLE
Remove outdated snapshot

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1676]
Since we are now fully migrated to RocksDB for state management, we can collapse the different snapshot concepts and use only the RocksDB one.

Some overlap with #1105

**Comment by Zelldon** [comment]
We have to do #1730 as first, only then we can delete some of the old unused snapshot classes. I will start with https://github.com/zeebe-io/zeebe/issues/1731 and simply remove the SnapshortStorage references from the StreamProcessing classes and refactor some things.

**Comment by saig0** [comment]
Done. We have only RocksDB state and snapshots.
