### ISSUE TITLE
Opening RocksDB on partition install

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1729]
I think it would be nice if we could create an RocksDB instance per Partition, this would mean that we open the RocksDB on Partition install and give the LogBlockIndex (if the LogBlockIndex is allready migrated to RocksDB https://github.com/zeebe-io/zeebe/issues/1730) and StreamProcessor access to the database, maybe via dependency.

There could exist an Service/Actor, which creates periodically checkpoints from the database. But we have to 
make sure that this causes no inconsistencies if an actor writes to RocksDB and an checkpoint is concurrently created. Possible solutions for this would be to suspend the other actors for this time of checkpoint creation OR they run all in the same actor OR maybe this is even no problem we have to find this out.

This solution would give us a separation of the RocksDB creation, data snapshoting and Event processing, because the StreamProcessorController is only interested in reading and writing events. We could deleted then the whole Snapshot stuff.

depends on https://github.com/zeebe-io/zeebe/issues/1730

**Comment by npepinpe** [comment]
From reading the RocksDB `checkpoint.cc`, it seems at some point it does fix the latest sequence number of the snapshot (such that further operations are ignored), so it seems possibly safe to concurrently do a checkpoint if we make sure all operations are "atomic" (i.e. batched). I'm only 70% sure of this though so we'd need to test it :sweat_smile: 

I don't think suspending the actor makes much sense, so if I'd rather fallback on running both services in the same actor.

**Comment by Zelldon** [comment]
We already implement the async snapshoting, see #2300.
