### ISSUE TITLE
Reiterate over LogBlockIndex Snapshots

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1730]
Currently the `LogBlockIndex` is the last one which uses the `SnapshotStorage`.

Possible solution would be to migrate to RocksDB, so we can remove the old `SnapshotStorage` and close #1676 . The question is would it use an own RocksDB or should it be shared with the StreamProcessor?
Maybe then we have the problem that they run in different threads (on different column families), we have to check that.

**Comment by menski** [comment]
I would assume that the log block index uses a different RocksDB then the workflow engine state.
