### ISSUE TITLE
Merge zbctl into go client source tree

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1740]
There is not real reason why we have `clients/go` and `clients/zbctl`. Instead zbctl should be merged into `clients/go`. We could reorganize the `clients/go` folder to follow the directory layout from https://github.com/golang-standards/project-layout

**Comment by menski** [comment]
@eggsbenjamin do you have an opinion about this issue? We think it would better follow normal go projects to merge the go client and zbctl into a single folder.

**Comment by eggsbenjamin** [comment]
It would make things neater and easier to reason about. 

I'd advise moving the contents of `clients/zbctl` into a new `cmd/zbctl` directory (as per https://github.com/golang-standards/project-layout) in `clients/go`.

Minikube use this directory structure - https://github.com/kubernetes/minikube/tree/master/cmd
