### ISSUE TITLE
Non-strict JsonPath conditions

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe#1751]
This:

```xml
 <bpmn:sequenceFlow id="SequenceFlow_0i25xlk" name="No" sourceRef="ExclusiveGateway_1lcuyv5" targetRef="EndEvent_0kr1brk">
   <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">$.existing_object.missing_field != true</bpmn:conditionExpression>
 </bpmn:sequenceFlow>
```

fails with

    JSON path `$.existing_object.missing_field` has no result.

and JsonPath workaround is not helping:

    JSON path `$.existing_object[?(@.missing_field)].missing_field` has no result.

I've found https://github.com/zeebe-io/zeebe/pull/1375
JsonPath conditions shouldn't be strict either. Currently i see no way of having a condition on missing field. It would be better always to evalute missing fields to null. Preferably with short-circuiting to null, so subsequent selectors would not fail either.

So `$.existing_object.missing_field` would be null and `$.existing_object.missing_field.some_subfield` would also be null without exception.

**Comment by saig0** [comment]
Hi @iamtakingiteasy,

thank you for raising this up. I agree that it would be useful if a non-existing field is evaluated to `null`.

I would expect the following behavior
 
payload | expression | result
-----------|----------------|---------
`{ }` | `$.foo == null` | true
`{ }` | `$.foo.bar == null` | true
`{ "foo": null }` | `$.foo == null` | true
`{ }` | `$.foo != null && $.foo < 3` | false
`{ }` | `$.foo < 3` | incident :warning: 

Do you agree with my expectation?

**Comment by iamtakingiteasy** [comment]
Yes, I agree with this. It is how current PR is operating with non-strict version of comparison, but I probably should add tests to assert that.

Also i think that strict version would not be needed in general, except very exceptional cases, when user must distinguish null value and missing value.

This however could be solved by `in` syntax from JS:

| **payload**        | **expression**           | **result**  |
| ------------- |:-------------:| -----:|
| `{ }`      | `"foo" in $` | false |
| `{ "foo": null }`      | `"foo" in $` | true |
| `{ "foo": 123 }`      | `"foo" in $` | true |
| `{ "foo": 123, "bar": "foo" }`      | `$.bar in $` | true |
| `{ "foo": 123, "bar": "baz" }`      | `$.bar in $` | false |

 `"foo" in $`
