### ISSUE TITLE
Handle message elements without correlation key

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1754]
If a process model contains a message which does not contain a `zeebe:subscription` extension element, i.e. has no correlation key defined, the workflow transformation will throw a null pointer exception.

We should either validate this on deploy and reject the workflow, or ignore messages which are not referenced by a message event definition.

**Comment by saig0** [comment]
Currently, the validator ignores messages which are not connected to a catch event or a receive task. We should do the same in the transformation.

**Comment by aleferov-v** [comment]
@menski @saig0 how I can validate my model? Because I don't know how and when, but my other model apparently broke again

**Comment by saig0** [comment]
@aleferov-v , I tested your model `demo2.bpmn` with the Zeebe 0.14.0 and it works. What error do you see? 

The validation of the BPMNs happen when they are deployed. However, you can also use the Zeebe BPMN model API to validate the models before: https://github.com/zeebe-io/zeebe/blob/develop/bpmn-model/src/main/java/io/zeebe/model/bpmn/Bpmn.java#L318
