### ISSUE TITLE
zeebe cluster support on aws ECS 

### ISSUE THREAD

**Issue by bhowmikdebarshi** [zeebe-io/zeebe#1764]
Does Zeebe cluster support on aws ecs ? 

Each node of zeebe cluster needs separate node id, cluster size and initial contact points. If we same task definition for all node, we can not have separate node id and separate initial contact points. 
In case of auto scale up, cluster size will be increased and we can not change the config of already running ecs containers.

**Comment by menski** [comment]
> we can not have separate node id and separate initial contact points.

If ECS does not allow you to have a unique identifier per container that it is not supported at the moment 

> In case of auto scale up, cluster size will be increased and we can not change the config of already running ecs containers.

At the moment Zeebe brokers do not support auto scale up/down.

That said we plan to improve the deployment experience especially in cloud environments in the upcoming months. We will keep your feedback in mind, thanks for raising the question.
