### ISSUE TITLE
Log request can overwrite prior state without notice

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#178]
* At the moment, all requests to a log must contain the entire state of the state machine that is addressed; for example, a set retries command must contain all the task properties including payload, headers, etc.
* This leads to lost updates when a client has an outdated event of that state machine at hand that it bases the request on

Solution possibilities:

1. broker rejects commands that address outdated state; client must therefore send the log position of the event that the command is based on; client must be able to cope with command failure
1. certain update APIs do not require the entire event to be sent, but only the delta of changed properties. For example, the set retries request only contains the new number of retries. On broker side, the event that confirms the request must be a combination of the last event on the log and the updated properties from the request. This requires random access to the log when processing the command and could therefore involve a performance impact, also slowing down following pending requests that are more performance-critical

**Comment by menski** [comment]
@ThorbenLindhauer did we solved this problem with the RocksDB state and key based commands?

And what is the difference to #177? :thinking:

**Comment by ThorbenLindhauer** [comment]
Yep, should be good now as well.

I think the separation was that #178 deals with cases where the client simply sends an outdated event, so an intermediate update is lost, and #177 deals with cases where client does send the latest event, but the update is still lost.
