### ISSUE TITLE
Timer rescheduling is done by BPMN step handler

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1784]
Instead of performing timer rescheduling from the `TriggerTimerProcessor`, which requires us to fetch the workflow definition + the handler node ID definition, we should simply trigger the event, and as part of its lifecycle, it should reschedule a timer.

This means timers are a bit less accurate, but it's a worthy trade off in my opinion.

**Comment by MiguelPires** [comment]
We discussed it and there's not much benefit in moving the rescheduling of the timer to the event occurred handler of the elements.
