### ISSUE TITLE
Cluster fails under load

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#1792]
I'm load testing a four node Zeebe cluster to profile its throughput in various scenarios.

I'm using https://github.com/jwulf/zeebe-examples - a fork that I've updated to use Zeebe 0.14.0 and a Go task worker cluster.

I can start 1.3 million workflow instances in about 50 minutes with no issue using multiple instances of `generator` running on the client nodes.

The task workers cannot keep up with this (they have completed about 130k workflows), so I stop the workflow generation and start scaling up the workers, by starting more instances of each taskworker on various machines.

At some point, all workers are failing with:

```
2018/12/17 01:01:23 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Here is what the topology reports at this point. Notice that two brokers are claiming to be the leader for Partition 0:
```
Broker ec2-18-185-132-2.eu-central-1.compute.amazonaws.com : 26501
  Partition 0 : Leader
  Partition 2 : Follower
Broker ec2-18-195-65-87.eu-central-1.compute.amazonaws.com : 26501
  Partition 1 : Leader
  Partition 2 : Follower
Broker ec2-18-197-152-62.eu-central-1.compute.amazonaws.com : 26501
  Partition 0 : Leader
  Partition 1 : Follower
Broker ec2-18-197-101-65.eu-central-1.compute.amazonaws.com : 26501
  Partition 2 : Leader
  Partition 1 : Follower
  Partition 0 : Follower
```

**Comment by jwulf** [comment]
Might have been a full disk. I will instrument the free disk space and try to reproduce.

**Comment by npepinpe** [comment]
From the error it's hard to tell whether the deadline occurred between the client-gateway or the gateway-broker. I'm assuming the broker is configured with the embedded gateway, so it would be unlikely (?) that it would timeout between gateway-broker, so my guess is the gateway is overloaded. 

How are the workers configured?

**Comment by menski** [comment]
Another problem is that partition 0 seems to have to leaders, which means the cluster is in an invalid state. It could also mean that no one is able to commit to partition 0 which could explain the worker problems.

**Comment by iriszou** [comment]
> Another problem is that partition 0 seems to have two leaders, which means the cluster is in an invalid state. It could also mean that no one is able to commit to partition 0 which could explain the worker problems.

my cluster has 3 node, it works good,then I kill(with Ctrl+C) node-1, cluster's status is:
./zbctl status --address 172.16.0.13:26500
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 172.16.0.13:26501
    Partition 0 : Leader
    Partition 1 : Follower
  Broker 2 - 172.16.0.9:26501
    Partition 0 : Follower
    Partition 1 : Leader

**after I kill node-1, my client(go client) go wrong with error log:**
2018/12/17 16:39:11 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/12/17 16:39:11 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/12/17 16:39:11 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/12/17 16:39:11 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded

**restart go client with error log:**
panic: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by menski** [comment]
@iriszou which address are you providing to the go worker? And is that the same node you kill in your test? The client only connects to a single broker which then forwards messages to other brokers, so make sure not to kill the one used by the worker.

**Comment by iriszou** [comment]
> @iriszou which address are you providing to the go worker? And is that the same node you kill in your test? The client only connects to a single broker which then forwards messages to other brokers, so make sure not to kill the one used by the worker.

my brokers list:
Brokers:
  Broker 0 - 172.16.0.13:26501
    Partition 0 : Leader
    Partition 1 : Follower
  Broker 1 - 172.16.0.6:26501
    Partition 0 : Follower
    Partition 1 : Follower
  Broker 2 - 172.16.0.9:26501
    Partition 0 : Follower
    Partition 1 : Leader

**go client dial to "172.16.0.13:26500"**

and I kill node-1 which IP is 172.16.0.6

**Comment by Zelldon** [comment]
We did a lot of bug fixes and stability improvements in the last releases. If you see any issue please open a more specialized one, which explains the exact problem you're encountering and if possible with  a process to reproduce.
