### ISSUE TITLE
Examine impact of simple copying of snapshots

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1812]
The Zeebe state is organized in two root folders `runtime`, which contains the current state, and `snapshot`, which contains all checkpoints. 

On recovery we will delete the `runtime` and `recover` via the latest valid snapshot, whereas valid means the position in the metadata complies with the latest commit position.

To recover in the past the RocksDB was opened in the corresponding snapshot directory, a checkpoint was created in the runtime, the DB was closed and opened again in the runtime folder.
The checkpointing will do hard links instead of simply copying, but it is not 100% clear what else is done in RocksDB and how performant it really is.

After https://github.com/zeebe-io/zeebe/pull/1798 the recovery was adjusted and the snapshot is simply copied recursively. The db is then opened in the runtime folder.

We should examine which approach should be preferred, regarding to performance and simplicity Maybe there is also a third option.

**Comment by Zelldon** [comment]
How about simply renaming the folder (`move`) :sweat_smile:

**Comment by saig0** [comment]
If we would rename the folder to `runtime` on recovery then we can not recover from this snapshot the next time.

**Comment by Zelldon** [comment]
Didnt we currently delete all snapshots after recovery anyway? 😅

**Comment by saig0** [comment]
Not anymore. Since we introduced the max snapshot count, we don't delete snapshots after recovery.

**Comment by Zelldon** [comment]
A true I removed that :see_no_evil:

**Comment by saig0** [comment]
I think that copying the snapshot folder is good enough for now. If we see any downsides then we can look into it. I close the issue for now.
