### ISSUE TITLE
Serialize Exporter record payload as a nested JSON document and not a string

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1821]
When serializing an exporter record, the payload should be a nested JSON document and not a string (i.e. serialized json document). This is more intuitive and probably what users expect.

Current blocker is the elastic search exporter, which would index and merge all properties of all payloads together...

**Comment by npepinpe** [comment]
This will probably be affected by #1846

**Comment by menski** [comment]
workflow instance records do not contain the payload anymore
