### ISSUE TITLE
Extend timer cycles to include starting timeDate

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#1834]
At the moment, timer cycles in Zeebee only support the specification of a number of repetitions and an interval. This could be extended to support the specification of a timeDate after which the time cycle would be applicable. For instance:

```
<startEvent id="theStart">
  <timerEventDefinition>
    <timeCycle>R4/2016-03-11T12:13/PT5M</timeCycle>
  </timerEventDefinition>
</startEvent>
```
For reference, [here is](https://docs.camunda.org/manual/7.10/reference/bpmn20/events/timer-events/#timer-start-event) the Camunda BPMN documentation page related to this feature. This is also contemplated in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals).

**Comment by saig0** [comment]
Closing this issue in favor of #3038.
