### ISSUE TITLE
A workflow instance record should contain the bpmn type of the element

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1839]
Every workflow instance record should have a field `bpmnType` which reflects the type of the related bpmn element. The type should be an enum in the protocol listing all currently supported types:

- Start/End/Intermediate Catch/Boundary Event
- Service/Receive Task
- Sequence Flow
- Exclusive/Event Based/Parallel Gateway
- Process/Sub Process

**Comment by npepinpe** [comment]
What's the use case here? Who consumes this?

**Comment by saig0** [comment]
The type is not required internally but can be consumed by an exporter (e.g. Operate). 

What about `process` and `sub-process`?

**Comment by menski** [comment]
Sorry forgot to mention the context, my fault. This can be useful for external applications, if you want to aggregate metrics for a specific type, or have to figure out the start/end intent for an event, see https://stage.docs.zeebe.io/reference/workflow-lifecycles.html#event-lifecycles.

**Comment by menski** [comment]
> What about `process` and `sub-process`?

Good point, I forgot about them but added it now to the list.
