### ISSUE TITLE
Add basic verification for processes

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#184]
AT:
* add basic validation rules for process

**Comment by menski** [comment]
@saig0 is this implemented with the switch to the model API and these validation rules: https://github.com/zeebe-io/zeebe/tree/44fe641993b594868fd766d8897b53ec899750dd/broker-core/src/main/java/io/zeebe/broker/workflow/model/validation

**Comment by saig0** [comment]
Yes, we have some basic verification rules now. So this is done!
