### ISSUE TITLE
Consider to replace JSON payload with variable key-value pairs

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1846]
Since the workflow instance payload is no single JSON document anymore, we should think about to replace the JSON payload in the other records as well (e.g. job, message, etc.).

Why?
* performance improvement because we don't need to create a document out of variables (e.g. job activation) and the other way around (e.g. job completing)
* uniform handling of variables

**Comment by aximo** [comment]
agree~

eg, you say that payload is a json,but [{}] is a valid json and zeebe not support, so it is actual key/value.

key/value is very clear/simple, the value format is only decided by client job implementor, he can set json/xml or something as String/number to  a key if necessary.

**Comment by saig0** [comment]
@aximo, we don't plan to drop the JSON support. The values should still be JSON. They can be a scalar value, an array or a document. If the values would not be JSON then you could not navigate into the JSON in input/output mappings or conditions.

**Comment by saig0** [comment]
Variables as JSON document:
* ActivatedJob
* CompleteJobRequest
* CreateWorkflowInstanceRequest
* PublishMessageRequest
* SetVariablesRequest

* ActivatedJob:  custom headers as JSON document

**Comment by saig0** [comment]
I split this issue into two pieces: #2699 + #2700
