### ISSUE TITLE
The ElasticSearch exporter influences every index named with the given prefix

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1864]
I currently write my own new "IndexRequest" for a non-yet existing index - which will cause it to be auto-created. The name was "zeebe-something". 

Since the latest ElasticSearch exporter this index now gets a configuration with type "_doc", alias "zeebe" and some fields. This seems to be configured by the exporter (I guess somewhere around https://github.com/zeebe-io/zeebe/blob/develop/exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java#L121). 

When I rename my index to "something" everything is fine - so this is not a pressing issue.

But I also expect confusion for people down the line - when they create own "zeebe-some-own-reporting-based-on-it" index.

**Comment by menski** [comment]
The zeebe elasticsearch exporter creates index templates for the given index prefix (default: `zeebe-record`), as seen here https://github.com/zeebe-io/zeebe/blob/b5c5435cb5cb8e55653e246955b0895bbbcb672c/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-template.json#L3

This can be configured through the exporter configuration https://github.com/zeebe-io/zeebe/blob/b5c5435cb5cb8e55653e246955b0895bbbcb672c/exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchExporterConfiguration.java#L41

Please don't use the same prefix for Zeebe indexes and your custom ones.

**Comment by menski** [comment]
Note if you don't change the default `zeebe-record` and still create custom `zeebe-*` indexes everything works as expected.
