### ISSUE TITLE
is there a clear way to fetch/listen incident event in java client?

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe#1866]
hi, i notice that there is document at https://docs.zeebe.io/reference/incidents.html, but how i can get the incident key firstly?

i also notice there is a issue #260, but it seems be not helpful for zeebe java client

**Comment by saig0** [comment]
Hi @aximo, you can implement an exporter which process incident events. The exporter can store the incident in a data source or send it to your application. 

There are also some exporters you can use or have a look at:
* https://github.com/zeebe-io/zeebe/tree/master/exporters/elasticsearch-exporter
* https://github.com/zeebe-io/zeebe-hazelcast-exporter
* https://github.com/zeebe-io/zeebe-kafka-exporter

Does this help you?

**Comment by aximo** [comment]
ok,that's enough,thanks~
