### ISSUE TITLE
Extract message correlation key from variable scope

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1891]
Currently, the message correlation key is extracted from the record payload. Since we have a variable scope, we should extract the key from the current or a higher scope.

AT:
* the message correlation key is extracted from the variable scope

**Comment by npepinpe** [comment]
For boundary events we should ensure that we use the activity's flow scope's variable scope and not the activity's itself.

**Comment by npepinpe** [comment]
Blocked by #1911
