### ISSUE TITLE
Propagate job/message payload to task scope

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1892]
Currently, the job/message payload is set on the scope instance (i.e. the scope above the task) if the task has no output mappings. This is ok in most cases BUT it is not consistent with the update-payload command. If the payload contains a variable which is set as local variable in the taks scope then the variable is still propagated to higher scope.

AT:
* the payload is propagated starting from the task scope

**Comment by npepinpe** [comment]
Blocked by #1891
