### ISSUE TITLE
zeebe user task

### ISSUE THREAD

**Issue by kratosmat** [zeebe-io/zeebe#1893]
Hi all,
I am studying zeebe as WF engine for microservices architecture.
I would like to know if there is a way to create and manage such user task concept with zeebe.

Regards,
Matteo.

**Comment by saig0** [comment]
Hi Matteo, currently Zeebe doesn't support user tasks. However, you can build a job worker to connect your application which manage the user tasks. The job worker can work for tasks of type `user`. When a job is activated then you create a user task in your application. When the user task is completed in the application then you complete also the related job. That's it.

Does this work for you?

**Comment by kratosmat** [comment]
Hi Philipp,
Thanks for the quick answer.

I think it is reasonable, but I have to implement it in order to complete
understand. I would like to know if you think to improve zeebe to
accomplish this kind of stuff or if you think this is out of scope.

Regards,
Matteo.

**Comment by saig0** [comment]
We will support user tasks at some point but not in the near future. However, it should be easy to integrate your application to work on user tasks. I think in most cases, users will build their own application for this anyway.

**Comment by kratosmat** [comment]
Thanks Philipp,
I will try to implement your advise.

**Comment by saig0** [comment]
:+1: Feel free to share your results :balloon:
