### ISSUE TITLE
Find better name for buffer size

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1894]
Currently users struggle to understand what the job worker property `bufferSize` means. We should find a name which better indicates the purpose of this setting.

For migration we should keep the buffer size method and mark it as deprecated, to be removed in upcoming releases.

**Comment by Zelldon** [comment]
I would propose limit, since it sets the maximum jobs which can be activated and works similar to the stream API limit method.

**Comment by Zelldon** [comment]
Then I would expect that I get always the number of jobs I have specified or? But this is not the case it is more an upper bound.

**Comment by berndruecker** [comment]
Agreed, but then probably we should distill it fom your sentence "maximum jobs which can be activated": 

- maximumNumberOfJobs
- maximumNumberOfJobsFetched
- limitOfJobs

I personally tend towards longer names that don't need interpretation, so I think "limit" is too short (what kind of limit is that? I need to look into the docs)

**Comment by npepinpe** [comment]
We shouldn't be afraid of longer names, most people have auto-completion these days. I think `maxJobsFetched` is pretty unambiguous (but I'm sure someone could argue against that), so it has my vote.

**Comment by jwulf** [comment]
`maxActiveJobs`, `maxConcurrentJobs`?

In my JavaScript client, I've called it `capacity`.

**Comment by jwulf** [comment]
https://jwulf.github.io/zeebe-node/interfaces/zbworkeroptions.html

![capacity](https://user-images.githubusercontent.com/406975/51505232-2553f200-1e31-11e9-991f-5457e5f5966b.png)

**Comment by Zelldon** [comment]
Yes, agree guys. 

The names `maxJobsFetched`, `limit`, `capacity` sound a bit as a total number for me, which could mean that no more jobs are activated by the worker after the limit is reached (so the worker might end after that?). Maybe `maxActiveJobs` or `maxConcurrentJobs` fits better, because it makes more clear that it only limits the current active/concurrent active jobs. 

But yeah I'm also fine with `maxJobsFetched`, everything is better then the current `bufferSize` :laughing:

**Comment by berndruecker** [comment]
While I understand "capacity" for the worker itself, I don't like that the name then differs from the parameter in the gRPC call. I personally don't care about the exact name - but prefer to have the same used everywhere.

**Comment by jwulf** [comment]
Is it the case that the number of jobs fetched == worker capacity - number of previously fetched jobs that are not yet completed?

And this is managed by the server when it streams the jobs in response to an ActivateJobsRequest?

**Comment by menski** [comment]
> While I understand "capacity" for the worker itself, I don't like that the name then differs from the parameter in the gRPC call. I personally don't care about the exact name - but prefer to have the same used everywhere.

I'm not sure which gRPC call you are referring to. The concept of the job worker is not represented in the protocol. The protocol contains the `ActivateJobsRequest` where the amount parameter limits the number of maximal activates jobs. The job worker will use this request, but depending on the already activated jobs use a different amount, I e. `amount = unfinished activated jobs - max active jobs`. So it's not a 1:1 mapping.

@jwulf the server keeps no state of the already activated jobs of a job worker. The job worker has to implement the logic to respect the still pending activated jobs when it activates more jobs. Does this answer your question?

**Comment by menski** [comment]
> So it is client-side logic, and client library implementations should track the ActivatedJobs count, and decrement it in the complete method.

- Yes, in the java and go worker we decrement the number of pending jobs when the job handler finished.
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/java/src/main/java/io/zeebe/client/impl/subscription/JobWorkerImpl.java#L124-L125
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/go/worker/jobPoller.go#L36-L37

- We then check if our pending jobs fall under a threshold, i.e. 30% of the buffer size (capacity). If this is the case the workers will poll for jobs to fill up queue again.
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/java/src/main/java/io/zeebe/client/impl/subscription/JobWorkerImpl.java#L117
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/go/worker/jobPoller.go#L52 

- And as you said we the use this to calculate the amount of jobs to activate
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/java/src/main/java/io/zeebe/client/impl/subscription/JobWorkerImpl.java#L97
https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/go/worker/jobPoller.go#L59

> Are we talking about the same thing?

I think so :+1:

**Comment by menski** [comment]
Yes in case the client does not complete/fail a job it will timeout on broker side, so it is again available for other workers.

In the Java client we catch any exception thrown by the job handler provided by the user and then try to fail the job ourself. This might reduce the time it takes for a job to be available again, and also makes this problem observable by a Zeebe operator. For example we also set the exception message as error message and reduce the retries count.

https://github.com/zeebe-io/zeebe/blob/03bc9225a28f7f1977513fbd70e40624f2d99225/clients/java/src/main/java/io/zeebe/client/impl/subscription/JobRunnableFactory.java#L40-L54

**Comment by Zelldon** [comment]
Can we do a poll ? :sweat_smile: 

 * maxActiveJobs = :heart: 
 * maxConcurrentJobs = :rocket: 
 * maxJobsFetched = :+1: 
 * limitOfActiveJobs = :eyes: 

Please vote with the corresponding reaction

**Comment by menski** [comment]
tendency in the team meeting: `maxJobsActive`

and we might call it task worker again :)
