### ISSUE TITLE
The occurred and the triggered event have the same key

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1899]
When a timer is triggered or a message is correlated then a workflow instance event is written with intent "EVENT_OCCURRED". If the event is related to a boundary event or an event-based gateway then it has a different key to the followup event "EVENT_TRIGGERING".

This looks a bit odd and causes problems for the mapping of the event payload.

Currently, the key is used to close the other event subscriptions when the event is triggered. If we change the key then we need to find the subscription in a different way, for example by introducing an event scope.

AT:
* workflow instance events which belongs to the same event (i.e. element instance) has the same key

**Comment by npepinpe** [comment]
Closed by #1939
