### ISSUE TITLE
Consider using Google well-known types in gRPC protocol

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1906]
Google offers a a set of so-called well known types under the [google.protobuf](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) package, which contains different types that could be useful to us.

They seem very well supported on the Golang and Java side, though I'm not sure about other languages.

Some that could be useful:

- [google.protobuf.Empty](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty): voids duplication of multiple empty response types (e.g. `UpdatePayloadResponse`, `CancelWorkflowInstanceResponse`, `CompleteJobResponse`, etc.)
- [google.protobuf.Timestamp](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#timestamp): encodes a timestamp as the UNIX epoch in seconds, and nano adjustements.
- [google.protobuf.Struct](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct): could be a useful replacement for the JSON encoded strings we use for payloads, custom headers, etc. It relies on `google.protobuf.Value`, which can be a limited set of things: null, boolean, list (of `google.protobuf.Value`), another google.protobuf.Struct, Number, String, and byte. It would already be marginally better than what we have, and potentially useful for the variables concept.
- [google.protobuf.Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration): encodes durations as a count of seconds and fractions of seconds at nanosecond resolution.

Things to consider here are: 

- are these types used outside of Google projects? (i.e. would it make our API more "standard")
- are these well supported in other languages (i.e. not go or java)?

**Comment by Zelldon** [comment]
I had this kind of discussion with @menski before. In case of UpdatePayloadResponse etc. we choosed this way because of backwards compatibility. It will break the compatibility if you change the whole return type but not if you simply add an field to the return type.

**Comment by npepinpe** [comment]
That's a good point, and I thought of that, but in other places it seems more unlikely that we will ever return anything on success (e.g. `CancelWorkflowInstance`). Either case it's cheap to have these messages, it was more of a "well if we're using these Google types, could be useful" kind of thing.

**Comment by npepinpe** [comment]
This can be closed by now - we can always reopen if we want to come back to it.
