### ISSUE TITLE
Review gRPC protocol

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1910]
After documenting the gRPC protocol, a few issues/questions were raised (see review of #1908) which I collect here so we can discuss at some point.

1. Do we still need all the info in `JobHeaders`?
1. Should we allow jobs to be completed even if not activated?
1. `ListWorkflows` should return an empty list if none found instead of an error `WORKFLOW_NOT_FOUND`?
1. Split protocol definition into multiple file, which can be imported piecemeal into the documentation?

**Comment by menski** [comment]
> Do we still need all the info in JobHeaders?

These headers where merged into the record itself.

> Should we allow jobs to be completed even if not activated?

This is fine and we will not change it for now.

> ListWorkflows should return an empty list if none found instead of an error WORKFLOW_NOT_FOUND?

Listing workflows was removed from the protocol.

> Split protocol definition into multiple file, which can be imported piecemeal into the documentation?

Not planned right now.
