### ISSUE TITLE
Google links to, an empty page  https://zeebe.io/de/

### ISSUE THREAD

**Issue by ahus1** [zeebe-io/zeebe#1921]
I've used Google to look up "Zeebe"

**Expected Behavior:**
Find the homepage of Zeebe

**Actual Behavior:**
It directed me to https://zeebe.io/de/ - an empty page

**Possible Cause/Remedy:**
It seems that a German (de) folder is created and is being indexed by Google. This folder should not be created, and/or should be excluded by a robots.txt

**Comment by Zelldon** [comment]
Hey @ahus1 ,

thanks for reporting this :+1: 
I'm able to reproduce it. We will have a look at this, thanks again.

Greets
Chris

**Comment by wints** [comment]
Thanks! I had actually just pushed a fix for this earlier this morning. Let me know if you continue to see the issue.
