### ISSUE TITLE
Delete zb-transport

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1927]
When all communication is happening over atomix we can remove zb-transport

**Comment by Zelldon** [comment]
**Idea on how we could replace transport:**

The command API subscribes for an topic called `commands-${partitionId}`.
The gateway sends an round-robin (1 - partitions-1) to `commands-${partitionId}`. 
Before sending an command the gateway generates an id (currently not sure how maybe host and request id ?) and subscribes to that (or maybe similar how it is in transport done).
Processor can send response back to the topic which consist of this id (response topic is stored in the command).

**Comment by npepinpe** [comment]
Done!

**Comment by Zelldon** [comment]
for reference https://github.com/zeebe-io/zeebe/pull/3547
