### ISSUE TITLE
Deployment rejection with multiple resources depends on resource order

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1933]
Currently if a deployment with multiple resources is deployed the resources are checked in order. 

If the first resource is invalid and the second one is valid, then deployment is accepted and deployed (only the valid one is available and returned as response).
If the order is the other way around, then the deployment is completely rejected.

```java

  @Test
  public void shouldNotDeployUnparsableModel() {
    // then
    exception.expect(ClientException.class);
    exception.expectMessage("'invalid.bpmn': SAXException while parsing input stream");

    final BpmnModelInstance workflow =
        Bpmn.createExecutableProcess("process").startEvent().endEvent().done();

    // when
    clientRule
        .getClient()
        .newDeployCommand()
        .addResourceStringUtf8("Foooo", "invalid.bpmn")
        .addWorkflowModel(workflow, "workflow.bpmn")
        .send()
        .join();
  }
```

**Comment by menski** [comment]
@Zelldon what would be your expected behavior? I would assume a deployment is successful when all resources where deployed.

**Comment by Zelldon** [comment]
I would assume that it an deployment is only successful if all resources are valid, otherwise I have to check manually whether my workflow is in the returned response.
