### ISSUE TITLE
Improve test suite efficiency by avoiding broker restart

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#196]
Follow-up of https://github.com/camunda-tngp/camunda-tngp/issues/185

* introduce operations in service container. An operation groups the
installation of a number of services in the container and succeeds /
fails atomically
* install all the system services (excluding log services,
streamprocessors ...) as part of the startup operations
* provide client api to create / delete topics and truncate topics
* around the testsuite, create a topic for the tests
* between each test, truncate the topic

**Comment by menski** [comment]
Topics where removed, so this is not longer a way to isolate tests. Either we would have to write tests which are not assuming a clean state, or we need a way to purge the log content. Neither of this will happen in the near future. We improved the test setup to allow parallel execution, which at least helped in the CI
