### ISSUE TITLE
Refactor BPMN step concept

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1969]
After #1939, the concept of the BPMN step processor is perhaps not the best-fitting.

Previously, the idea was to bind different `WorkflowInstanceIntent` values to an element's lifecycle; since we now have a single unified lifecycle, the goal has changed.

Current architectural idea is that every element executes a pre-defined handler for its current lifecycle state; if it has none, then we lookup the type hierarchy until we find the first one.

For example, when processing `ELEMENT_ACTIVATING` for a `SERVICE_TASK`, we would lookup a handler specifically for service tasks and this lifecycle phase, and if none found, lookup one for `ACTIVITY`, and then for the base flow node.

**Comment by menski** [comment]
We are not planning to work on this in the near future
