### ISSUE TITLE
Investigate usage of failed records

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1970]
After #1939, since everything has an element instance, it may not be necessary to store failed records on the scope when raising an incident. We should investigate and potentially remove it if it's unnecessary now.

NOTE: deferring records is still very much required for events.

**Comment by npepinpe** [comment]
@saig0 - is this still a thing with the refactoring? Should we close this?

**Comment by saig0** [comment]
We still store failed records if an incident is raised. This record is used for resolving the incident. I'm not sure how to do it without it. 

So, I don't see a problem for now. I'll close the issue.
