### ISSUE TITLE
Incidents should be resolved in the terminal state handler

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1978]
After a element is finished, not matter how it was terminated, all incidents should be resolved.

**Comment by Zelldon** [comment]
> all incidents should be resolved.

Do you mean removed from the state or should also the Resolve-Resolved Command-Event be written?

**Comment by menski** [comment]
Events, this issue is about this code block which should be moved
https://github.com/zeebe-io/zeebe/blob/f3cfe66cf11b1ecadcc292d654b608bcc4a6a873/broker-core/src/main/java/io/zeebe/broker/workflow/processor/handlers/element/ElementTerminatingHandler.java#L49-L57

**Comment by npepinpe** [comment]
I think it needs to be moved to TERMINATED as the `ResolveIncidentProcessor` attempts to continue processing if the element still exists, so we need to resolve incident as we are cleaning up any left overs.
