### ISSUE TITLE
A event based gateway does not emit the sequence flow which is taken afterwards

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1979]
At the moment the sequence flow between the event based gateway and the next event is not emitted in the event stream. This is not a technical problem, but could be confusing for event stream consumers and differs from other behavior.

**Comment by saig0** [comment]
As far as I know, this is compliant to the spec.

**Comment by menski** [comment]
> As far as I know, this is compliant to the spec

This is probably correct, this issue is more concerned about the fact that the event stream for an event based gateway differs from other gateways and might be unexpected for consumers of the exported event stream.

At the moment we do not plan to change the behavior but it might be interesting in the future.
