### ISSUE TITLE
Timer start event occurred should not use its position as key

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1981]
At the moment the timer start event occurred uses its position as key, which is not optimal as all keys should be unique and therefore we should not use the position as key anywhere. Please check that we do not do position as key.

**Comment by menski** [comment]
![screenshot-2019-02-07-11 28 56](https://user-images.githubusercontent.com/516296/52472766-63bd1100-2b94-11e9-88d3-e1ab11849dea.png)

**Comment by Zelldon** [comment]
>therefore we should not use the position as key anywhere. Please check that we do not do position as key. 

For this part I created an follow up issue
https://github.com/zeebe-io/zeebe/issues/2016
