### ISSUE TITLE
Subscribe requests processed after restart should be rejected

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#200]
Requests for a topic subscription that are rececvied before broker restart but are processed after broker restart should be rejected. This avoids having a subscription without a subscribing client, blocking any other clients from subscribing.

**Comment by ThorbenLindhauer** [comment]
Solution idea 2: Skip the side effects during recovery as discussed in https://github.com/zeebe-io/zeebe/issues/415. This may not be sufficient. It would prevent the pushing stream processor from being opened, but the subscriber would still appear as `SUBSCRIBED` on the log, which is not clean and could lead to corrupt index state (if any is based on the `SUBSCRIBED` event).

**Comment by menski** [comment]
topic subscriptions are no longer supported
