### ISSUE TITLE
Document how to create and configure a standalone gateway

### ISSUE THREAD

**Issue by wints** [zeebe-io/zeebe#2002]
We don't currently have docs on how to create and configure the standalone gateway.

**Comment by jwulf** [comment]
Created a docker-compose configuration for this: https://github.com/zeebe-io/zeebe-docker-compose/blob/0.18/standalone-gateway/docker-compose.yml

Related issues: 
https://github.com/zeebe-io/zeebe/issues/2017
https://github.com/zeebe-io/zeebe/issues/2501
https://github.com/zeebe-io/zeebe/issues/2526

**Comment by strawhat5** [comment]
Hi @menski @jwulf , the docker-compose file does give an idea on how to deploy standalone gateway. But, it would be great if we can have an equivalent `helm chart` for this. That would help us in readily deploying it to Kubernetes cluster. Is there any such document available?

**Comment by jwulf** [comment]
@salaboy is the one for the helm charts.

**Comment by npepinpe** [comment]
Closing and recreating in the new documentation project.
