### ISSUE TITLE
Replace position as key fallback with next key generation

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2016]
Currently the `TypedCommandWriterImpl` uses as fallback `#positionAsKey`, when the given key is less then zero, see this line [TypedCommandWriterImpl#L108](https://github.com/zeebe-io/zeebe/blob/develop/broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedCommandWriterImpl.java#L108)

This is problematic, since the position is not unique in a cluster. We should replace this fallback with the key generator.

**Comment by Zelldon** [comment]
It seems that `#positionsAsKey` is still used in the `SubscriptionApiCommandMessageHandler.java`, see here
https://github.com/zeebe-io/zeebe/blob/develop/broker-core/src/main/java/io/zeebe/broker/subscription/command/SubscriptionApiCommandMessageHandler.java#L255

**Comment by menski** [comment]
Can we please delete the method `positionAsKey`, thanks
