### ISSUE TITLE
Allow exclusion of sensitive exporter configuration when logging it

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2019]
When starting an exporter, we will log its configuration, using `Gson` to serialize it 

https://github.com/zeebe-io/zeebe/blob/9ca84c9fa756c67333aa1598ae1a73356b196f03/broker-core/src/main/java/io/zeebe/broker/system/configuration/BrokerCfg.java#L151

Since some exporters might contain sensitive information, we should provide a way to exclude some parameters from that.

One option would be to look into an [ExclusionStrategy](https://google.github.io/gson/apidocs/com/google/gson/ExclusionStrategy.html), another would be to use a different way (e.g. `toString() of the configuration class) than `Gson`.

**Comment by menski** [comment]
Main reason why I went for the gson approach is that it  does require custom `toString` implementations. My dislike of toString impls it that they often are forgotten, or at least we do not request them during reviews. And that they easily become outdated. Also pretty printing :heart_eyes:

Of course this did not take into account that we might print sensible data, it was just the fastest way to achieve what I wanted.

So we don't have to stick to Gson, but we could also validate if for example Jackson has simpler exclude/ignore strategies instead.

**Comment by npepinpe** [comment]
I have nothing against Gson, and the `ExclusionStrategy` seems like it would be a good solution, so why not. I think in general it'd be good that we provide some kind of way for exporter authors to hide anything they wouldn't want logged anyway.

**Comment by menski** [comment]
My problem with the exclusions strategy would be that it is quite a lot of boiler plate and I'm not sure how users would customize it as you have to add it when you configure Gson or not? That's why I thought there might be simpler ways with Jackson.

**Comment by npepinpe** [comment]
Well yes, but it's just modifying:

https://github.com/zeebe-io/zeebe/blob/9ca84c9fa756c67333aa1598ae1a73356b196f03/broker-core/src/main/java/io/zeebe/broker/system/configuration/BrokerCfg.java#L151

To:

```java
return new GsonBuilder().setExclusionStrategies(topSecretStrategy).setPrettyPrinting().create().toJson(this);
```

Admittedly I didn't look too much into it, so we'll see when we get around to it I guess.
