### ISSUE TITLE
I can get and set Zeebe properties using the Model Api

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#202]
AT:
* I can use the model API to read and write Zeebe properties 
* I can use the builder to set Zeebe properties
* I can validate a given model

**Comment by saig0** [comment]
I created a new repository: https://github.com/zeebe-io/zb-bpmn-model

Open TODOs:
* validation
* integration in the broker

**Comment by saig0** [comment]
We could also include the simple workflow YAML parser: https://github.com/sdorokhova/simple-workflow

**Comment by saig0** [comment]
Validation + YAML support is implemented.

The integration in the broker will be done in a follow-up issue.

**Comment by menski** [comment]
@saig0 I really like this model API :+1: my favorite feature is the closure style builder :heart_eyes: 

I have one question: What is the idea behind or usage of [BpmnAspect](https://github.com/zeebe-io/zb-bpmn-model/blob/cebeb68976bdd3146329d8caf89d049a8dbff136/src/main/java/io/zeebe/model/bpmn/BpmnAspect.java)?

**Comment by saig0** [comment]
@menski, BpmnAspect is used for the runtime. The workflow instance processor reads the aspect, e.g. take / consume token, instead of checking the outgoing sequence flows every time. I extended the transformer to set the aspects.

**Comment by menski** [comment]
Ok got it. Thanks :cookie:
