### ISSUE TITLE
Clean up state after event was skipped on processing error

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2028]
With  https://github.com/zeebe-io/zeebe/issues/1988 we skip on processing errors the corresponding record. If the record was an command we send an rejection back. If the record was an event we should clean up the state, since the instance is then anyway broken and there is currently no possibility to restart the instance.

If we not clean up the state we will end up with a lot of garbage and dead instances after skipping lot of events.

**Comment by Zelldon** [comment]
## Idea

On processing failure we write an error event. It can happen that there are follow up events which are related to the corresponding workflow instance. That is the reason why we have to blacklist the workflow instance. 

Since we write the error event on failure, this error event is the last existing event related to the workflow instance. (excluding user commands) This means on processing the error event we could remove the workflow instance from the state to clean up. This means for user commands after this clean up we will return an rejection with not found message.

**Comment by saig0** [comment]
We will postpone this topic. As for now, we don't want to delete this data. We might implement a way to restore a failed workflow instance.
