### ISSUE TITLE
Skip exporters that fail during their open phase

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2034]
At the moment, once the exporter stream processor has recovered, we will open exporters sequentially as defined in the configuration file; if one fails, then the stream processor itself crashes, and is never restarted.

As we're still not deleting any data, I would propose that exporters which fail during their open phases are skipped: we log the error and ignore them, such that the stream processor can do its work.

Recovery in this case (w.r.t to the failing exporter) would consist in restarting the broker, since when restarting the processor will allow the exporter to reprocess all records it hasn't seen, and will not forward previously seen records to the other exporters.

**Comment by saig0** [comment]
Since #2305, we delete data from the logstream. In order to export each record by all exporters, we can't skip a failing exporter. The operator needs to fix the problem either by fixing the failure with the exporter or removing the exporter from the configuration.
