### ISSUE TITLE
Exporter stream processor failure handling

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2044]
Investigate how we should handle single `Exporter#export(Record)` failures in the exporter stream processor.

Possibly take some inspiration from [Resilience4j](https://github.com/resilience4j/resilience4j)

**Comment by saig0** [comment]
Currently, we retry until the event is exported successfully. If we would skip the event then we might delete the event from the logstream and the exporter will never export it. This is not ok.

I see no need to improve the current behavior.
