### ISSUE TITLE
Generate keys explicitly for entities and not implicitly in stream writer

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2047]
As we use the key attribute as our unique entity identifier in our state database, we should move the automatic generation from the stream writer (which can introduce error if one forgets about it) to an explicit API, where we either pass -1 or a pre-generated key to the stream writer whenever appending records.

One option is to have the state DB handle all key generation, and enforce that all entities (e.g. ElementInstance, MessageSubscription, etc.) have a unique key which can be used when writing relevant records for those entities.

Related to #2045

**Comment by Zelldon** [comment]
related to https://github.com/zeebe-io/zeebe/issues/2016
