### ISSUE TITLE
Create distribution integration smoke test

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#207]
We should have a simple test case that runs the latest distribution build and executes a client command (e.g. create command) to ensure that both distro and client are not generally broken. 

* There is potential for dependency conflicts in the qa integration test suite due to its dependencies to both broker and client. An integration test that runs the actual distro avoids having the broker in the classpath and can therefore uncover dependency problems in the client.
* this will show problems if the distro's broker configuration is outdated

**Comment by npepinpe** [comment]
Our `update-tests` and several other TestContainers based test now cover this to varying degree.
