### ISSUE TITLE
ZeebeRocksDb iterate whileEqualPrefix does not break after prefix is exceeded 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2080]
This leads to situations where we iterate most of the rocksdb state on collecting variables or removing scopes etc.

https://github.com/zeebe-io/zeebe/blob/28261d5f24279364950d49ad2c1cf1227a8d59b3/zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDb.java#L389-L392

**Comment by Zelldon** [comment]
Do you have a failing test case for this? I had assumed that`#startsWith` catches this?

**Comment by menski** [comment]
The problem is not `startsWith`, but that we don't break if it is false. I have the fix but am fighting with a test case.

**Comment by Zelldon** [comment]
Ah now I get what you mean. We not call visit on the values but still iterate until the end.

I think you can skip the test creation 😅

**Comment by menski** [comment]
> I think you can skip the test creation ￼

Noooo I finally have a test case, it's not beautiful but it works :unicorn:
