### ISSUE TITLE
Rename payload property to variables

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2086]
As we are removing the payload property in #1852, it makes sense to stop talking about payloads and just about variables.

So we should remove (if applicable) or rename payload properties/fields in the clients, broker, gRPC API, etc.

Whoever picks this up should probably then split this into more issues.

**Comment by npepinpe** [comment]
Related to #1617

**Comment by menski** [comment]
broken down in smaller issues
