### ISSUE TITLE
Improve DB internal state management

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2098]
We've had a few run-ins with the fact that we reuse the same buffers/transaction in our current state abstraction (e.g. log block index being used in different actors, having nested iterators, etc.).

I think there are a few ways we could improve the current status:

1. Use buffer pools instead of a single reusable buffer

Having a dedicated buffer pool would allow us to support a minimum amount of concurrency when it comes to the state, and as an initial effort we could simply allocate new buffers when the pool is empty (with a warning log). That solves immediate problems (e.g. no need to have different prefix buffers, key, value, etc.), and there's a lot of known optimization techniques (e.g. tiered pools) that we could always add in the future, so it's a pretty flexible improvement.

2. Use an execution context

This is maybe a bit more work, but we could use an execution context which holds the buffers/transaction to use when running a particular operation on the database. If that's too ugly (e.g. having to pass a context all the time as a parameter), it's easily improved by using a facade which hides that (e.g. `ContextualStateDbDelegate` which has a fixed context).

Both could be combined as well, and I don't think either is very difficult to add/implement.

**Comment by menski** [comment]
First iteration for the execution context:

- Create a database context class which contains the shared state of the database interaction
  - Shared buffers
  - key, value instances
  - transaction instance
- Adjust column family interfaces to accept an context object to be used on db interaction
- Actors own their own context object

**Comment by menski** [comment]
First iteration -> https://github.com/zeebe-io/zeebe/issues/2184

**Comment by npepinpe** [comment]
From my side this is done :+1:
