### ISSUE TITLE
Merge JobHeaders with JobRecord

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2104]
As far as I know the JobHeaders have been introduced because of the fact that standalone jobs could be created, which means jobs which are not related to a workflow instance. This is not the case anymore. For now an job is always related to a workflow instance. I assume we can then simply merge the headers into the normal job record.

Would also be interesting whether we need all of these properties or it might be sufficient to just have: workflowInstanceKey, workflowKey and elementInstanceKey

**Comment by menski** [comment]
Please discuss this with Svetlana to verify the minimal required information.

**Comment by npepinpe** [comment]
I talked to Svetlana and while they consume the job records, it's temporary, in the sense that UX didn't come up with a concept yet for showing activity metadata, and Svetlana currently puts the JSON of the latest related event...but that's just her who came up with this, it's not an official thing.

So we should notify her about changes to job records, but there's no blocker.

**Comment by Zelldon** [comment]
closed by https://github.com/zeebe-io/zeebe/pull/2693
