### ISSUE TITLE
Split Incidents into Job and WorkflowInstance Incident

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2105]
Currently we could have two real different incidents: an incident which is job related or an incident which is workflow instance related.

They are distinguished via the job key, which is set only on the job related incident. They need to be distinguished because they are different handled and resolved. 
That fact brings me to the conclusion that it might make sense to have two different records and processors. Then we have no need to check whether it is a job or workflow instance related incident etc. it is then clear what to do.

**Comment by menski** [comment]
Personally I think there is no value in creating job incidents, as jobs are no standalone entity anymore, and every incident is related to a workflow instance. 

The current approach is to differentiate incidents by the `ErrorType` and which indicates clearly what went wrong and how to resolve it. Imagine a future where a job can also have an incident which does not require to update the retries, again you would have to differentiate by error type instead of incident type.

In my opinion the `ErrorType` enum is the better solution and already in place, so no need to introduce more incident types.

**Comment by Zelldon** [comment]
> every incident is related to a workflow instance

True but still we have kind of distinction

I assume here a clashing two different views, one is the record consumer which might use the error type as you described, but I meant more the developer view on developing the corresponding processor.

Currently we have something like this:

```java
  public boolean rejectIncidentCreation(
      IncidentRecord incidentEvent, CommandControl<IncidentRecord> commandControl) {
    final IncidentState incidentState = zeebeState.getIncidentState();

    final boolean isJobIncident = incidentState.isJobIncident(incidentEvent);

    if (isJobIncident) {
      return rejectJobIncident(incidentEvent.getJobKey(), commandControl);
    } else {
      return rejectWorkflowInstanceIncident(incidentEvent.getElementInstanceKey(), commandControl);
    }
  }
```
 OR this:
```java
  public void createIncident(long incidentKey, IncidentRecord incident) {
    zeebeDb.transaction(
        () -> {
          this.incidentKey.wrapLong(incidentKey);
          this.incidentRecordToWrite.wrapObject(incident);
          incidentColumnFamily.put(this.incidentKey, this.incidentRecordToWrite);

          if (isJobIncident(incident)) {
            jobKey.wrapLong(incident.getJobKey());
            jobIncidentColumnFamily.put(jobKey, this.incidentKey);
          } else {
            elementInstanceKey.wrapLong(incident.getElementInstanceKey());
            workflowInstanceIncidentColumnFamily.put(elementInstanceKey, this.incidentKey);
          }
        });
  }
```

If we have separate processors we have no need to use the conditional statements.

**Comment by menski** [comment]
I don't want to be nitpicking but if you have different record types you just move the if condition to another place in the code

**Comment by Zelldon** [comment]
Then the stream processor decides, with help of an mapping which we already have, who is in charge to process this record. :sweat_smile:   anyway just wanted to bring this up.

**Comment by menski** [comment]
Incidents will stay the same for now
