### ISSUE TITLE
Variable events should contain workflow key

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2115]
A variable record should contain the workflow key, which allows aggregation of variable values based on workflows. 

For reference https://forum.zeebe.io/t/how-to-measure-mean-time-to-resolve-for-workflow/278/3

**Comment by npepinpe** [comment]
If you mean the workflow instance key, it should already have it (not sure if that was included already in the latest release though). Even reading the forum post, I'm not sure I understand the use case for the workflow key itself, or why a variable should be aggregated over the workflow definition; is it so someone could measure different metrics across different process versions?

**Comment by menski** [comment]
The workflow key reference is important for business metrics over variable values. For us that would be Camunda optimize. With a reference to the workflow you can answer the question what is the max damage value of your fraud detection process. Or what are the most common values of your T-shirt color choice in your order process.

I agree that execution metrics should not be calculated over variables.
