### ISSUE TITLE
I can't get instance back to my worker after 126 retries

### ISSUE THREAD

**Issue by OlivierAlbertini** [zeebe-io/zeebe#2143]
Hi,

After making some tests with Zeebe, I found a weird behaviour. 

# Current Problem:

Indeed, After exactly 126 retries on a given instance, my workers don't get this instance again... 
I tried to restart the broker or my workers but nothing happens. This instance is not complete and can be seen with the zeebe-simple-monitor.

# Expected Behaviour

I want to retry my instance until I decide to set it as `Incident`.

# How to reproduce : 

I make a repo with all you need to reproduce this issue. Just read the readme.
https://github.com/OlivierAlbertini/zeebe-issues

# Related

After making  a search on your github repo, perhaps it could be related : #1988 

# Version

- zeebe_broker: `0.15.1`
- zeebe_simple_monitor: `0.11.0`
- zeebe_node: `1.0.5`

Let me know if I can do something else.

**Comment by npepinpe** [comment]
I can reproduce this with the follow test case:

```java
@Test
  public void shouldFailJobManyTimes() {
    // given
    createJobOfType("foo");

    final RecordingJobHandler jobHandler = new RecordingJobHandler();

    client
      .newWorker()
      .jobType("foo")
      .handler(jobHandler)
      .timeout(Duration.ofMinutes(5))
      .name("test")
      .open();


    // when
    for (int i = 0; i < 128; i++) {
      waitUntil(() -> !jobHandler.getHandledJobs().isEmpty());
      final ActivatedJob lockedJob = jobHandler.getHandledJobs().remove(0);
      client.newFailCommand(lockedJob.getKey()).retries(lockedJob.getRetries() + 1).send().join();
    }

    // then
  }
```

**Comment by npepinpe** [comment]
At first glance I imagine it's an overflow issue when writing or reading the msgpack record.

**Comment by Zelldon** [comment]
Worked for me:

```java

  @Test
  public void sdsaf() throws Exception {
    // given
    final AtomicInteger atomicLong = new AtomicInteger(0);
    final CountDownLatch latch = new CountDownLatch(1);
    createJobOfType("foo");

    final RecordingJobHandler jobHandler =
        new RecordingJobHandler(
            (c, j) -> {
              final int retries = atomicLong.incrementAndGet();
              System.out.println("retries " + retries);
              c.newFailCommand(j.getKey()).retries(retries).errorMessage("this failed").send();
              if (retries > 256) latch.countDown();
            });

    // when
    client.newWorker().jobType("foo").handler(jobHandler).name("myWorker").open();

    // then
    latch.await();
  }

```

**Comment by npepinpe** [comment]
I tried it in 0.15.0, but I think I remember you fixing a bug about overflows in msgpack? Maybe then it's fixed in 0.16.0

**Comment by Zelldon** [comment]
Yeah wanted to test this with 0.15.0 as well but had no time yet. True, fixed some overflow bugs, makes sense that this work then with 0.16 :+1:

**Comment by npepinpe** [comment]
@OlivierAlbertini 0.16.0 should be released soon, if you could try again then, but I think this bug was fixed in #2026

**Comment by OlivierAlbertini** [comment]
Ok I will try with 0.16.0 version. Thanks all.

**Comment by OlivierAlbertini** [comment]
Testing with 0.16.1 version. It's fixed. Thanks.

**Comment by Zelldon** [comment]
Thanks for checking @OlivierAlbertini
