### ISSUE TITLE
Add new metric for records skipped on failure

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2186]
At the moment, the skip record metric is incremented both when we skip a record on failure, and when we skip a record because the stream processor has no event processor registered for it.

We should either:

a) add a new metric for skipping on failure
b) challenge if we still need the metric for when there is no event processor registered

**Comment by menski** [comment]
I just started an empty broker with no starter/worker and it immediately reports a skipped metrics count of 1000. We should validate if these metrics are still correctly reported in general.

**Comment by Zelldon** [comment]
Maybe raft events?

**Comment by menski** [comment]
it's long time ago I wrote the raft implementation but it should not generate 1000 event on each partition on start up :laughing:

**Comment by menski** [comment]
Ignore my previous comments, yes it is raft, and of course its not 1k but 1.000 which means 1. Sorry that I failed to read the english decimal separator correctly :see_no_evil:

**Comment by Zelldon** [comment]
Hehe no prob👍😀

**Comment by npepinpe** [comment]
Is this still a thing? Do we care about having a metric for skipped records?

**Comment by npepinpe** [comment]
I'm closing this as I don't think it's important, feel free to reopen if you want to remove the metric or split it.
