### ISSUE TITLE
Investigate on RocksDbExceptions in terms of recoverabiity

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2188]
Currently we assume that all RocksDbExceptions kind of recoverable, which is probably not the case. If they are not recoverable it makes no sense to retry the processing.

**Comment by Zelldon** [comment]
I think for the Status Codes of the exception is interesting.

See [here](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/Status.java):

```java

  // should stay in sync with /include/rocksdb/status.h:Code and /java/rocksjni/portal.h:toJavaStatusCode
  public enum Code {
    Ok(                 (byte)0x0),
    NotFound(           (byte)0x1),
    Corruption(         (byte)0x2),
    NotSupported(       (byte)0x3),
    InvalidArgument(    (byte)0x4),
    IOError(            (byte)0x5),
    MergeInProgress(    (byte)0x6),
    Incomplete(         (byte)0x7),
    ShutdownInProgress( (byte)0x8),
    TimedOut(           (byte)0x9),
    Aborted(            (byte)0xA),
    Busy(               (byte)0xB),
    Expired(            (byte)0xC),
    TryAgain(           (byte)0xD),
    Undefined(          (byte)0x7F);
```

**Comment by Zelldon** [comment]
So would check the Statuscode of the Exception and for OK, IOError, MergeInProgress, Timeout, Aborted, Busy, Expired, TryAgain xodes I would throw RecoverableException otherwise normal RuntimeException.

Any thoughts @npepinpe ?

**Comment by npepinpe** [comment]
As far as I understood, every operation in RocksDB returns a status, a OK is basically when everything went well, so we shouldn't get an exception with that status (afaik). 

Otherwise seems good, the only thing is I'm not sure what aborted means. Is it related to transactions? In that case it's fine as well, since we retry the whole thing and restart the transaction.

**Comment by Zelldon** [comment]
>  a OK is basically when everything went well

Yes but to make sure that we not ignore OK status codes I would like to add this. 

>  Is it related to transactions? In that case it's fine as well, since we retry the whole thing and restart the transaction.

IdK. I assumed that.
