### ISSUE TITLE
Investigate RocksDB memory consumption

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2189]
At the moment we see increasing memory consumption also the JVM reports only 1.5G heap size and 6G direct memory size the jvm is killed by OOM at around 16G memory usage. Question is who used the other 8G. Current hypothesis: RocksDB

**Comment by menski** [comment]
Maybe interesting: https://issues.apache.org/jira/browse/FLINK-7289

**Comment by menski** [comment]
It seems that the "optimized" column family options are quite memory intensive
https://github.com/zeebe-io/zeebe/blob/7e62111a16214ff33336177d7c92c6733e7daa7c/zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java#L108

Tests with the default column family options are currently showing approximately 2G memory per partition and no noticeable performance loss.

**Comment by menski** [comment]
We will stick we the default options for now, until we see the need for optimization.

**Comment by Zelldon** [comment]
Kafka seems to have also some problems with RocksDB and memory consumption.

https://stackoverflow.com/questions/56663008/rocksdb-out-of-memory
https://issues.apache.org/jira/browse/KAFKA-8324
