### ISSUE TITLE
Possible missing follow up events on reprocessing with replication

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2214]
When reprocessing, we start from the snapshot position X, and seek til the end of the log for the greatest source event position Y, then reprocess from X until Y. During reprocessing, we don't execute side effects or write follow up events.

Although we write follow up events in a batch atomically to the dispatcher, they are not replicated together atomically. What this means is that we may have one of the follow up event point to Y, but may be missing another one which was also pointing to Y; since we only *reprocess* the event at Y, we will never write the missing follow up events, resulting in unpredictable behaviour.

**NOTE**: this might be fixed in the Atomix branch since there I think the replication of a follow up event batch is atomic?

**Comment by menski** [comment]
This should be fixed with the current distributed log approach
