### ISSUE TITLE
Make payload/variables naming consistent in job activation

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2215]
Examples: 
* https://github.com/zeebe-io/zeebe/blob/077fc30c70477a7fa9682baf6dde23a85edc1913/gateway-protocol/src/main/proto/gateway.proto#L50
* https://github.com/zeebe-io/zeebe/blob/077fc30c70477a7fa9682baf6dde23a85edc1913/gateway/src/main/java/io/zeebe/gateway/ResponseMapper.java#L212
* https://github.com/zeebe-io/zeebe/blob/077fc30c70477a7fa9682baf6dde23a85edc1913/clients/java/src/test/java/io/zeebe/client/job/ActivateJobsTest.java#L115

**Comment by Zelldon** [comment]
Dublicate https://github.com/zeebe-io/zeebe/issues/2195

**Comment by MiguelPires** [comment]
Isn't #2195 related job completion?

**Comment by Zelldon** [comment]
Ah true, sorry you're right. But maybe you can fix this in general in one shot ? 😅😀

**Comment by Zelldon** [comment]
I can review this😊

**Comment by MiguelPires** [comment]
Closed by #2226
