### ISSUE TITLE
Migrate payloadColumnFamily to variablesColumnFamily in VariablesState 

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2225]
VariablesState still has a payloadColumnFamily and it should be changed before we can finish renaming all of the occurrences of payload.

**Comment by npepinpe** [comment]
Wait, `payloadColumnFamily` has another meaning here; I think we already have a `variablesColumnFamily` for normal variables. Payload in the variable state currently acts as a "injected" payload for a given state, which is later merged with the other variables.

I'm not sure if it's necessary to change the name here.

**Comment by Zelldon** [comment]
It is still a bit misleading or inconsistent we can also call it `temporaryVariableStore`, since it is only stored for output mappings and then deleted.
