### ISSUE TITLE
Evaluate waffle.io Alternatives

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2229]
The service waffle.io is shutting down, therefore we need an alternative kanban board for our workflow.

Timebox: 1 Day
Date: After 2. April
Questions to answers:
- what are similar services and how do they fit our workflow
- what is automated/manual, current state:
  1. Columns are related to GitHub Labels
  1. Pushing to a branch prefixed with issue id moves ticket into **progress** column and assigns commit author
  1. Opening a PR moves issue issue into **needs review** column and attaches the PR to the issue, PR shows status on board (approval status/build status)
  1. Merging a PR/commit with `closes` reference to the issue moves the issue into the **done** column, this is optional as long as closed issue are removed from the board
- how can the board be filter, currently waffle supports a quite flexible filter for assignee, label and milestone

@Zelldon before you start to work on this issue please sync with me

**Comment by Zelldon** [comment]
> Merging a PR/commit with closes reference to the issue moves the issue into the done column, this is optional as long as closed issue are removed from the board

I think this is done by github built-in.

**Comment by menski** [comment]
> I think this is done by github built-in
I know, the part I'm interested in is that the issue is removed from the board are put into a column I can ignore.

**Comment by Zelldon** [comment]
## Waffle replacement

### Alternatives 
  - sources: 
    - https://stackshare.io/waffle-io/alternatives
    - https://stackshare.io/stackups/huboard-vs-waffle-io-vs-zenhub
    - https://alternativeto.net/software/waffle-io/
    - tested all boards
  - Github Projects https://github.com/Zelldon/Board-Integration-Test/projects/1
    - free to use
    - comes with some automation now
    - Most important thing, which I assume can be missed fast is that each issue needs a project reference otherwise it will not show up in the project board
  - ZenHub https://app.zenhub.com/workspaces/boardintegration-5caaf636b6a36b7d13bde5fc/board?repos=180080259
    - 40 $ per month for 8 developers
    - seems more for business user or manager (nice charts etc. )
  - HuBoard https://huboard.com/Zelldon/Board-Integration-Test#/
    - 24 $ per month
    - very lightweight - maybe to lightweight (sometimes needs to reload the page)
  - Codetree https://codetree.com/projects/uS8E/board
    - 49 $ per month for 8 developers
    - currently a good feeling with that
    - only tool which supports automation also on branch creation
    - On pr creation issue can be moved (configurable) and PR is added to this issue card, like it is done on Waffle
  - Zube - https://zube.io/test-172/boardintegration/w/workspace-1/kanban
    - 10 $ per user per month (80 $ for 8 devs)
    - a bit to much - not the automation we need
  - Self-hosting
    - Wekan
      - unclear feature set


----------


We decided to go with codetree
