### ISSUE TITLE
Duplicate EmbeddedBrokerRule

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2234]
There are two EmbeddedBrokerRule classes, one in the test module and another in the broker, which are identical.

**Comment by npepinpe** [comment]
iirc this is because `zeebe-test` is considered a public API, hence the internal `EmbeddedBrokerRule` we use. This is probably bad practice, as we should use the same API our users use - if only extended.

Important here is to not break compatibility with the one in the `zeebe-test` module.

**Comment by npepinpe** [comment]
Related to #3419

**Comment by npepinpe** [comment]
Closing for now in favour of #3419 - this isn't a big problem at the moment, and I'd rather we focus on #3419 in the future.
