### ISSUE TITLE
Logstream and Broker are too tightly coupled

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2243]
Our current stream processing abstraction, in the logstreams module, is hard to test and not optimal.

If we move the `TypedStreamProcessor` in the logstreams module we would be able to write kind of integration tests for the `StreamProcessors` with the `StreamProcessorController`. Currently we are not really able to do this, the current processor tests in the broker tests do not use the real `StreamProcessorController` for example. 
With introducing the error event in https://github.com/zeebe-io/zeebe/issues/2228, we need to test that the `ErrorEvent` are correctly written on unexpected exception. With the current abstraction this is not possible to test.

During this we could think about merging the `EventProcessors` with the `StreamProcessorController` https://github.com/zeebe-io/zeebe/issues/1048.

**Comment by saig0** [comment]
Also related to #2353
