### ISSUE TITLE
Refactor start message subscription closing/opening 

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2288]
This a follow-up issue for #2265 and #2156. The old state of the start message subscription workflow failed during reordered deployments and always issued CLOSE commands even when previous deployments didn't contain message start events. The current state doesn't fail and doesn't issue unnecessary CLOSE commands but still doesn't account for every configuration of reordered deployments and might, for instance, not close an outdated subscription (if version 1 is deployed and then version 3).

**Comment by Zelldon** [comment]
Also please make sure that we don't open subscriptions for old deployments
