### ISSUE TITLE
Improve error messages in LogStorageAppender

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2309]
Currently if the Appender fails to append an block it will simply go in fail state and prints always the same error message.

```java
 textPayload:  "15:54:19.662 [logstream.partition-0.storage.appender] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-fs-workers-0] ERROR io.zeebe.logstreams - Failed to append log storage on position '91697552523600'. Stop writing to log storage until recovered.
```

This is not very helpful, since the error is relative wide. It could be because of a to large event which can't be append or the disk is full etc. would be nice if we could print what is exactly the problem.

**Comment by menski** [comment]
depends on #2298
