### ISSUE TITLE
How to define Events, Fork / Join Concurrency for zeebe in YAML format?

### ISSUE THREAD

**Issue by MaksimRT** [zeebe-io/zeebe#2335]

**Comment by saig0** [comment]
Currently, the YAML format doesn't support these elements. Our primary format in BPMN XML. We recommend creating/modifying your workflows using the [Zeebe Modeler](https://github.com/zeebe-io/zeebe-modeler/).

However, if you think that YAML is important too then feel free to propose extensions for the YAML format. Pull requests are also welcome =)
