### ISSUE TITLE
Verify that a snapshot is replicated successfully

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2345]
AT:
* when a snapshot is replicated to a follower then the follower verifies that the snapshot is replicated  successfully (e.g. checksum, open snapshot, etc.)
* if the snapshot is correct then it is marked as valid
* otherwise, it is discarded

requires #2344

**Comment by Zelldon** [comment]
## Idea:

### What we need is:

 * ensuring max snapshot count also on follower replication
 * checksums per chunks which are validated on follower
 

### Discussion

What should happen on validation error:

   * one solution could be to ensure max count after received all chunks
      * we can delete all snapshots and tmps which are lower then the lowest valid snapshot
      * if chunk is not valid we do not write the file this means snapshot will never become valid and is deleted at some point
    * we write file called invalid and chexk if this exists on validating snapshot and remove the tmp dir then
