### ISSUE TITLE
Use one SnapshotController and DB per leader partition

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2353]
Currently we have per leader partition three SnapshotController's and DB instances. On a follower partition we have one in the LogBlockIndexWriter. The current architecture (see details below) makes it hard to implement the SnapshotReplication #2344  or rather the receiving of the snapshots on the followers, since the StreamProcessors are not running on the followers (we have no general point to receive the snapshots).

### Follower
  * DistributedLog
    * LogStream
      * LogStorage
      * LogBlockIndexWriter
        * SnapshotController
          * ZeebeDB

### Leader
  * DistributedLog
    * LogStream
      * LogStorage
      * LogBlockIndexWriter
        * SnapshotController
          * ZeebeDB
      * LogStorageAppender
    * StreamProcessorController
      * TypedStreamProcessor
      * AsyncSnapshotDirector
        * SnapshotController
          * ZeebeDB
    * StreamProcessorController
      * Exporter
      * AsyncSnapshotDirector
        * SnapshotController
          * ZeebeDB

### Follower

We have no need to run the `LogBlockIndexWriter` on the followers

  * SnapshotController (receives replicated snapshots)
  * DistributedLog
    * LogStream
      * LogStorage

### Leader

We have only on SnapshotController and ZeebeDB instance which is shared. This decrease the complexity and footprint.

  * SnapshotController $1
    * ZeebeDB  $2
  * AsyncSnapshotDirector
    * ref $1
  * DistributedLog
    * LogStream
      * LogStorage
      * LogBlockIndexWriter
        * ref $2
      * LogStorageAppender
    * StreamProcessorController
      * TypedStreamProcessor
      * ref $2
    * StreamProcessorController
      * Exporter
      * ref $2

**Comment by Zelldon** [comment]
kind of duplicate of #1729

**Comment by saig0** [comment]
Note that the log block index can be different on the follower if the log segment size is different from the leader.

**Comment by menski** [comment]
Also we have to think about snapshotting/restoring as they are currently different between workflow stream processor, exporter and log block index, and all of them are at different positions in the log, which might have an influence on when a snapshot is valid.

**Comment by Zelldon** [comment]
For exporters and log block idx the snapshots are immediately valid, since they write no events so they doesn't wait for anything. All of them store there last position in the state so recover should also no problem.

**Comment by Zelldon** [comment]
Extraction from logstream refactoring discussion:

------

## Three databases per partition:

Exporter, workflow processor and log block index have own RocksDB instance
 * means also three snapshots and replications (currently two)

### Symptoms:
 * for deleting we have to wait until we have all snapshots
    * larger footprint and overhead
 * if we have no exporters then no snapshot is replicated
   * followers can't delete data 
   * leader can delete
  * exporter removing is hacky
    * we need to remove the exporters from the state, even if we have no exporters left
    * open database from outside - without stream processor controller, we need to create a new snapshot afterwards

### Solution:

One database instance per partition, which is created on partition install.

Problem with log block index:

If `logSegmentSize` changes on follower, replicated snapshot is invalid.
To avoid that we could remove the `logSegmentSize` config from ZeebeConfig for now.
