### ISSUE TITLE
Access array index in I/O mapping

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe#2366]
How to access an array index with current I/O mapping?
#2172 seems to remove JSON path notion, so how arrays are supposed to be subscripted now?

**Comment by iamtakingiteasy** [comment]
Quick glance suggests that PR has not made any adequate substitute for handling array indexing, removing also any reference and tests that involved such.

**Comment by saig0** [comment]
You are right. Currently, it is not possible to access an array by index. We removed the function because it was not really useful in this form. 

What do you need exactly? 
Please describe your use case in detail. This will help us to build the feature in the right way.

**Comment by iamtakingiteasy** [comment]
Currently I had my I/O mappings fully refactored, this not an issue to me any more.

I agree that being lazy on writing actual unwrappers for cases where data comes in tuple-arrays was not a good design decision, so I had a rightful backfire. Just did not expected it to be that soon.
