### ISSUE TITLE
IO mapping fails when output mapping references variable with empty string at end

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe#2371]
When output mapping of service task references a variable that has an object in it, which is also happens to have value with empty string as it's last key in serialized JSON form, I/O mapping fails with incident.

Keys that are not mapped does not affect this, regardless of their contents.

e.g.: having "account" mapped to "inviterAccount" and service task returning JSON like

```json
{"account":{"id":"123","test1":"","test2":"success"}, "foo": {"unmapped_values_do_not_affect":""}}
```
everything is fine, because `account` variable has non-empty string as it's last value

However, when JSON like

```json
{"account":{"id":"123","test1":"test2 value causing incident","test2":""}}
```
Is returned, empty value of `test2` being the last key will cause problems.

I've created isolated test-case with docker-compose, golang service task worker and minimal bpmn process in this repository: https://github.com/iamtakingiteasy/zeebe-output-mapping-test

You can try it by getting the compose https://github.com/iamtakingiteasy/zeebe-output-mapping-test/blob/master/docker-compose.yml and doing `docker-compose up` in directory with it.

It will setup `camunda/zeebe:0.17.0` (with simple and hazelcast exporters) and `camunda/zeebe-simple-monitor:0.13.0` available on localhost:38080 of host machine. By the time both launches, third container, `golang:alpine` tester should fetch `github.com/iamtakingiteasy/zeebe-output-mapping-test`, build binary of it, upload the process (from bindata.go, generated by invoking `go generate` in project directory), push two tasks with diffrent results, await their completion and then exit, leaving results in simple-monitor interface to observe as two jobs, one failed, other successful.

**Comment by iamtakingiteasy** [comment]
Apparently that is due to readin 0 bytes past buffer capacity, which somehow throws an error:
https://github.com/zeebe-io/zeebe/blob/713b86e9bd4d4b975d13a1f3b17e2dc136a4a1ee/msgpack-core/src/main/java/io/zeebe/msgpack/spec/MsgPackToken.java#L64-L66

**Comment by saig0** [comment]
Hi @iamtakingiteasy,

thank you for raising this up and providing a fix :+1: We will have a look at it soon.

Best regards,
Philipp
