### ISSUE TITLE
Fix maven surefire ClassNotFoundException

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2379]
Since the atomix merge we get often on the CI, especially on bors ! the following exception:

```java
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project zeebe-qa-integration-tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed: java.lang.ClassNotFoundException: org.apache.maven.surefire.junitcore.JUnitCoreProvider -> [Help 1]
```
Which fails the build

**Comment by Zelldon** [comment]
Tried the following  https://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html

```xml
<useSystemClassLoader>false</useSystemClassLoader>
```

Still:

```java
[2019-04-25T11:48:51.099Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project zeebe-qa-integration-tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed: java.lang.ClassNotFoundException: org.apache.maven.surefire.junitcore.JUnitCoreProvider -> 
```

and new 

```java
[2019-04-25T11:48:05.632Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project zeebe-qa-integration-tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed. NullPointerException -> [Help 1]
```

**Comment by Zelldon** [comment]
We also tried to downgrade surefire and failsafe on https://github.com/zeebe-io/zeebe/pull/2340, same problem

**Comment by Zelldon** [comment]
Weird is that I run on the CI around 20+ builds with `<useSystemClassLoader>false</useSystemClassLoader>` and maven debug flag and this exception does not happened again :man_shrugging:

**Comment by Zelldon** [comment]
Ok finally the exception happend again with debug flag, also the NPE we have seen before. See the complete [log.txt](https://github.com/zeebe-io/zeebe/files/3126068/consoleText.txt)

**Comment by Zelldon** [comment]
@menski you mentioned that the qa and unit tests share the same local maven repository right? Can we change that?

**Comment by menski** [comment]
@Zelldon yes unit and qa are sharing the same container, i.e. same workspace and local maven repository. Yes we can change that, what is the desired setup?

**Comment by menski** [comment]
I will prepare a branch with a custom local maven repository for the qa tests and let you know when it's ready to be tested.

**Comment by Zelldon** [comment]
Thanks :+1:

**Comment by menski** [comment]
The branch https://github.com/zeebe-io/zeebe/tree/2379-qa-local-mvn-repo failed again with NPE in surefire after 134 builds.

**Comment by Zelldon** [comment]
Hm damn, was the debug flag enabled?

**Comment by menski** [comment]
No I didn't had debug enabled. would that give us more insides in this exception?

**Comment by Zelldon** [comment]
I think we see then the Stacktrace and stuff which happens before, so maybe 🤷‍♂️

**Comment by Zelldon** [comment]
Ok seems that the moduls download and finish from time to time the dependencies at the same time, which causes the problem (I would assume). I think we can't fix this without removing the parallel builds. I would say that we use the change you did on the branch and leave as it is for now. 134 builds after first fail sounds ok, better then before :sweat_smile: What do you think?

**Comment by menski** [comment]
So our assumption is that this bug happens when to modules tested in parallel are finishing at the same time?

> What do you think?

Yeah I also thought it happened less then before, so I will give this another thought and if I can't come up with something promising I will merge my change as first step.

**Comment by menski** [comment]
I'm currently testing an approach where we initially download all dependencies and then run the tests in offline mode in parallel on the branch 2379-offline-testing

**Comment by Zelldon** [comment]
Ah nice sounds nice, thought about this as well but was not sure if this is possble with maven 👍
