### ISSUE TITLE
Remove hack from exporter-logstream connection

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2381]
Currently, the logstream accesses the exporter state to determine the minimum exported position through a callback that is set and unset in the ExporterManagerService. This is necessary because this position must be taken into account when deleting data from the logstream and LogStreamService can't have a dependency on the ExporterManagerService because that would introduce a circular dependency between the logstreams and the broker. After these modules are refactored, this hack should be replaced by a more explicit mechanism.

**Comment by saig0** [comment]
Related to #2243

**Comment by MiguelPires** [comment]
The StreamProcessorController is built with a flag (deleteDataOnSnapshot) that tells it whether or not the AsyncSnapshottingDirector should have a callback to delete old data. This is necessary to ensure that data is only deleted after we reach the necessary count for snapshots of the stream processor's state, instead of being deleted after reaching Y snapshots for the exporters. This solution is hacky but since we plan to have only one RocksDb (and therefore only one type of snapshot) in the future, it will do until then. However, when the refactoring is done, this should be removed.

**Comment by menski** [comment]
related #2452

**Comment by MiguelPires** [comment]
Closed by https://github.com/zeebe-io/zeebe/pull/2548
