### ISSUE TITLE
Pull requests from external will not trigger CI builds

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2383]
See for example https://github.com/zeebe-io/zeebe/pull/2374

**Comment by Zelldon** [comment]
New candidate https://github.com/zeebe-io/zeebe/pull/2597

**Comment by menski** [comment]
At the moment I see this as feature, as user otherwise could modify the Jenkinsfile and extract secrets from the build. I agree that external PRs should be somehow tested, maybe travis CI would be a solution for that

**Comment by npepinpe** [comment]
For now we have few community PRs, so the process is to clone the branch and push it ourselves for Jenkins to build.
