### ISSUE TITLE
Find a better way to pass node specific configuration to distributed log primitive

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2385]
Currently logstream services are created by the log primitive. Otherwise, the primitive service cannot restore its state after a restart. We can only pass configuration common to all partitions/replicas through primitive's config. As a workaround, we now use a static map to store the configurations needed for creating logstream services. It would be also good, if we can decouple logstream service creation from the primitive.

**Comment by Zelldon** [comment]
We replaced the primitive and our log with the direct atomix journal usage
