### ISSUE TITLE
Reusing transaction with help of beginTransaction might be safer

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2397]
Currently we create one transaction object and reuse it all the time. This is probably OK. 
We observed with this approach no problems yet. But, the API provides a facility to reuse the transaction object.

```java
  /**
   * Starts a new Transaction.
   *
   * Caller is responsible for calling {@link #close()} on the returned
   * transaction when it is no longer needed.
   *
   * @param writeOptions Any write options for the transaction
   * @param transactionOptions Any options for the transaction
   * @param oldTransaction this Transaction will be reused instead of allocating
   *     a new one. This is an optimization to avoid extra allocations
   *     when repeatedly creating transactions.
   * @return The oldTransaction which has been reinitialized as a new
   *     transaction
   */
  Transaction beginTransaction(final WriteOptions writeOptions,
      final T transactionOptions, final Transaction oldTransaction);
```

It might be better to use the API, which also resets the internal state.

```c++
// begin with old trx calls Reinitialize

void OptimisticTransaction::Reinitialize(
    OptimisticTransactionDB* txn_db, const WriteOptions& write_options,
    const OptimisticTransactionOptions& txn_options) {
  TransactionBaseImpl::Reinitialize(txn_db->GetBaseDB(), write_options);
  Initialize(txn_options);
}

// TransactionBaseImpl
void TransactionBaseImpl::Reinitialize(DB* db,
                                       const WriteOptions& write_options) {
  Clear();
  ClearSnapshot();
  id_ = 0;
  db_ = db;
  name_.clear();
  log_number_ = 0;
  write_options_ = write_options;
  start_time_ = db_->GetEnv()->NowMicros();
  indexing_enabled_ = true;
  cmp_ = GetColumnFamilyUserComparator(db_->DefaultColumnFamily());
}
```

I don't think that this is urgent, since we also reset the transaction with rollbacks/commits.

```c++
Status OptimisticTransaction::Commit() {
  // Set up callback which will call CheckTransactionForConflicts() to
  // check whether this transaction is safe to be committed.
  OptimisticTransactionCallback callback(this);

  DBImpl* db_impl = static_cast_with_check<DBImpl, DB>(db_->GetRootDB());

  Status s = db_impl->WriteWithCallback(
      write_options_, GetWriteBatch()->GetWriteBatch(), &callback);

  if (s.ok()) {
    Clear();
  }

  return s;
}

Status OptimisticTransaction::Rollback() {
  Clear();
  return Status::OK();
}
```

But not all properties are then reset.

https://github.com/facebook/rocksdb/blob/189f0c27aaecdf17ae7fc1f826a423a28b77984f/utilities/transactions/optimistic_transaction.cc

**Comment by npepinpe** [comment]
Maybe I'm blind but I don't see this call available in the Java API =/ I'm also wondering if we should keep using `Transactions` and might not be better off using just plain WriteBatch? Is the only issue the fact `ExporterDirector` and `StreamProcessor` both write to the same column family (the one with the positions), and this can cause conflicts? :thinking: I think it's only conflicting if they write to the same values, no? I don't know how much overhead the transaction databases have, but it might be worth looking into if we don't need all these features.

**Comment by npepinpe** [comment]
Closing for now since it doesn't seem this API is available to us, however do reopen in case I was blind and it does :sweat_smile:

**Comment by Zelldon** [comment]
The API method is beginTransaction with the old transaction as param, see above.

**Comment by npepinpe** [comment]
Ah, sorry, I was looking for reinitialize. Thanks!
