### ISSUE TITLE
camunda/operate support  elasticsearch authentication config ?

### ISSUE THREAD

**Issue by rongfengliang** [zeebe-io/zeebe#2403]
as i known ElasticsearchExporter support authentication config  but i can't find any info about 
camunda/operate  for  authentication config

**Comment by wints** [comment]
Hi @rongfengliang, thank you for the question. Operate does not yet support Elasticsearch authentication. 

I'll bring this to the Operate team for discussion and close this issue (right now, we're using GitHub issues in this repo for open-source Zeebe only).

**Comment by TangJiong** [comment]
Same problem. Any progress here?

**Comment by sdorokhova** [comment]
This is implemented in Operate and will be relesed in upcoming v.0.25.0. Can be tested in v. 0.25.0-alpha2 .
(Corresponding issue is https://jira.camunda.com/browse/OPE-1006)

Configuration parameters are:
```
camunda.operate.elasticsearch.username
camunda.operate.elasticsearch.password
camunda.operate.zeebeElasticsearch.username
camunda.operate.zeebeElasticsearch.password
```
