### ISSUE TITLE
Provide a way to disallow a node from being stream processor leader

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2422]
If a log stream has be restored from a remote node, and the restore operation uses a snapshot, then until the restore operation is finished the node cannot be stream processor leader for this log stream, since the snapshot is not valid until the necessary events for the snapshot to be valid have been also been replicated.

AT:

- There is a way to block a node from being stream processor leader for a given partition, and to later allow it to be

**Comment by menski** [comment]
Wouldn't this be the case if we only install/join the leader election after the restore is finished, i.e. as last step?

**Comment by deepthidevaki** [comment]
While restore is in progress, other services in the broker are started. That means, the leader election service is also started and it will join the election.
