### ISSUE TITLE
Replace job worker usage with explicit activate/complete job helper in tests

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2439]
In general the java client job worker should only be used in tests which are actually concerned testing the job worker. In all other test cases a helper which actively polls and completes jobs should be used. The job worker gives no time guaranties about job completion as they could be delays in case a poll returned no jobs, i.e. no jobs are already created on starting the worker, the first poll will probably return zero jobs which leads to a delay of the maximum poll interval. This interval might even change in the future.

**Comment by npepinpe** [comment]
As far as I'm aware we're not using the job worker in any of those tests any more.
