### ISSUE TITLE
Implement delete and update for zbctl.

### ISSUE THREAD

**Issue by bncbodrogi** [zeebe-io/zeebe#2455]
Currently, as far as I can see, the only workflow related command in `zbctl`is `deploy`.
Is there a chance that a `delete` and `update` *(may be based on `workflow key`)* functionality will be implemented in the foreseeable future?

**Comment by Zelldon** [comment]
Hi @bncbodrogi ,

thanks for opening this issue.

If you want to update a workflow you can adjust the workflow model and re-deploy it. The version will be incremented and it will be used as latest version. 

I think there are currently no plans to support deleting of deployments in the near future.

Greets
Chris

**Comment by bncbodrogi** [comment]
Hey Chris,

Thanks for the quick reply.
Nice, will move accordingly ;)

Cheers
Bence

**Comment by lethe3000** [comment]
so any new plan about delete workflows?

**Comment by Zelldon** [comment]
@lethe3000 please take a look at https://github.com/camunda-cloud/zeebe/issues/2908
