### ISSUE TITLE
Merge block index DB with processor/exporter DB

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2473]
This is a follow up issue for #2353.

### Objective
Merging the log block index DB with the processor/exporter DB

### Benefits
* Reduced overhead

### Challenges
* With a single DB it becomes necessary for the log block index to be closed in the followers since a replicated snapshot will be installed and opened to determine the minimum exported position at the leader. The simplest way would be to only register the onCommit listener at the leader which would prevent the writer from being notified although that seems hacky. Probably the most stable solution would be to install it with the Partition for the leader.

**Comment by menski** [comment]
We decided to not merge the two databases, and keep the log block index for now. An alternative could be to completely remove the log block index and use a binary search approach to find a block.
