### ISSUE TITLE
need help about license

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe#2477]
Hi,all,  I notice that there is a AGPLv3 license about broke-core.

So, in my case, our company will:

1. Just deploy zeebe broker and will not change the source code of it
2. provide online serivce nor release software to customers
3. Our company source codes is not open source
4. Our company is a commercial corporation

Could our company to use zeebe-broker？

Just want to confirm it，thanks～

**Comment by menski** [comment]
Hi @aximo,

we cannot offer legal advice in this issue tracker. Please clarify these questions with the legal team of your company.

Cheers
Sebastian
