### ISSUE TITLE
Events has a wall-clock timestamp

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#248]
AT:
* every record has a wall-clock timestamp (broker time)
* the timestamp is automatically added

**Comment by menski** [comment]
- millisecond precision provided by (ActorClock)[https://github.com/zeebe-io/zb-util/blob/master/util/src/main/java/io/zeebe/util/sched/clock/ActorClock.java]

**Comment by npepinpe** [comment]
Closing in favor of #849, #850, and #851
