### ISSUE TITLE
Restore local log stream after full data loss

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2487]
There seems to be a limitation at the moment in Atomix related to how snapshots are propagated to nodes. It seems to be (although should be verified!) that once a node has sent a snapshot to another, it won't do it again; this means that if a node suffers from full data loss and it had already received the latest Atomix snapshot, then it will not attempt to restore, resulting in the primitive assuming it is ready to go. If this happens, then that node would end up with an inconsistent log, and so this issue should attempt to:

1. Ensure restore is called every time even with the same snapshot, or
1. Detect that it its local log is empty (or in an invalid state) and that it did not attempt to restore

In the last case, once we can detect this, then we should decide if we want to trigger the restore then or simply fail and require an operator to manually fix.

In either case we should not end up with an inconsistent log.

**Comment by npepinpe** [comment]
Related to https://github.com/zeebe-io/atomix/pull/13

**Comment by deepthidevaki** [comment]
This should be fixed by the atomix [PR](https://github.com/zeebe-io/atomix/pull/13)
