### ISSUE TITLE
Same ActorJob is executed twice by different threads

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2492]
In the `AsyncSnapshotingTest#shouldNotTakeSnapshotIfExistsAfterRestart` we observed that the `AsyncSnapshotDirector#prepareTakingSnapshot` runnable was invoked twice by different threads without the `snapshotRate` having passed.

**Comment by Zelldon** [comment]
Maybe because it is closed and submitted as new actor to the scheduler? Also the timer is incremented in the test.

**Comment by MiguelPires** [comment]
Thanks for the input, you're right. I was closing and re-opening the logstream in the test but didn't stop the actor scheduler so we had two running simultaneously.
