### ISSUE TITLE
Chaos: Mismatched cluster configs

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2502]
_Part of a series of "you're doing it wrong" tests to determine the behavior of the system when misconfigured or in a failed state._

**What happens if I try to start a cluster when the nodes have different replication factors and partitions configured?**

**Comment by npepinpe** [comment]
That's a good case - I expect it to explode. But we should be quite strict with this, true.

**Comment by npepinpe** [comment]
Closed in favor of #4609
