### ISSUE TITLE
Delete log storage segments

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2509]
When a node restore its logstream using a (stream processor) snapshot, it should delete all segments in the logstorage. Otherwise, there will be gaps in the logstream when it receives new events after the snapshot position.

**Comment by Zelldon** [comment]
Do we still want this? I mean normally it should be automatically deleted by our deletion logic, since we have a larger snapshot position?

**Comment by deepthidevaki** [comment]
Will it delete the segment if it is half filled and the delete position is the last event?

**Comment by Zelldon** [comment]
We migrated to atomix log
