### ISSUE TITLE
Rename port configurations

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2517]
- `26500` - gateway which is actually the client API
- `26501` - currently client API but actually the transport between gateway and broker
- `26505` - atomix which is actually the clustering/replication etc.

**Comment by menski** [comment]
Also https://github.com/zeebe-io/zeebe/blob/204973a24db1425a169692e72bfdaed0c3081973/dist/src/main/config/gateway.cfg.toml#L70 should be the same port as the atomix in the broker

**Comment by jwulf** [comment]
Suggested:

26500 - gRPC Gateway external communication
26501 - Gateway-to-broker communication
26505 - Broker clustering communication
