### ISSUE TITLE
Standalone gateway does not report complete broker topology

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2526]
Using the docker-compose configuration here: https://github.com/zeebe-io/zeebe-docker-compose/blob/0.18/standalone-gateway/docker-compose.yml

Querying the standalone gateway returns only the contact broker details (node0):

```
➜ ./zbctl.darwin status --address 127.0.0.1:26500
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 172.30.0.3:26501
    Partition 1 : Follower
    Partition 2 : Follower
```

Querying the embedded gateway on node0 returns the entire topology:

```
➜ ./zbctl.darwin status --address 127.0.0.1:26600
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 172.30.0.3:26501
    Partition 1 : Follower
    Partition 2 : Follower
  Broker 1 - 172.30.0.4:26501
    Partition 1 : Leader
    Partition 2 : Leader
  Broker 2 - 172.30.0.5:26501
    Partition 1 : Follower
    Partition 2 : Follower
```

**Comment by menski** [comment]
The reason for this seems to be a misconfiguraiton of the gateway host in our Dockerfile.
https://github.com/zeebe-io/zeebe/blob/353e5e19270675950fbeb1dc118373fa469453a0/Dockerfile#L7

**Comment by menski** [comment]
Actually the reason seems to be that the gateway cluster host has to be set to something internal reachable and not 0.0.0.0.
https://github.com/zeebe-io/zeebe/blob/353e5e19270675950fbeb1dc118373fa469453a0/dist/src/main/config/gateway.cfg.toml#L64-L66
