### ISSUE TITLE
Merge TypeRecord with ExporterRecords

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2531]
Currently we have two types of Records `TypedRecords<T extends UnpackedObject>` and the `RecordValue` classes, which are used by the exporters.

Problem with that is that if we want to change a record or add a new one we have to do it multiple times in different places.

We could use the interfaces and implement them with the `TypedRecords`. The methods which return a string can do this lazy and return a String only if necessary, with `BufferUtil.bufferAsString`. This will probably also create less garbage since I don't expect that some wants to  call all methods on the record explicit neither that they interested in the strings anyway :sweat_smile: 

The `toJson` could use the `UnpackedObject.writeAsJson`, no need to use the Jackson object mapper.

**Comment by npepinpe** [comment]
Regarding the `String` stuff, the guy from Chronicle describes how they use `CharSequence` for most of their APIs for this reason; on some implementation you can use a string, but for others it's easy to build a `StringView` which wraps a byte buffer (the only caveat being that a lot of things operating on `CharSequence` call `toString`). Might be worth looking into?

**Comment by Zelldon** [comment]
Yes might be better then using String, but probably byte[] would also be enough. I mean if some wants a string he can create one.

**Comment by Zelldon** [comment]
done by latest refactorings
