### ISSUE TITLE
WorkflowInstanceCreationRecordValue does not extends RecordValueWithVariables

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2532]
I don't why but the `WorkflowInstanceCreationRecordValue` does not extends `RecordValueWithVariables`, instead it has a own method which returns variables as a Map.

```
  /** @return the initial variables to use when starting the workflow instance */
  Map<String, Object> getVariables();
```

**Comment by npepinpe** [comment]
I think I added it during the transition from payload to variables, and I didn't want it to inherit from `RecordValueWithPayload` :see_no_evil: 

It would make sense now though

**Comment by Zelldon** [comment]
Ah ok thanks

**Comment by Zelldon** [comment]
Done due to latest refactorings
