### ISSUE TITLE
Discussion: Move Processing and Exporting installation in DistributedLogPrimitive

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2540]
Currently we have the DistributedLogPrimitive which is installed on start up (ClusterComponent).
The internal service is started for each member of a partition. We also install for each partition depending on follower or leader different services, like StreamProcessing, Exporting etc.

For me it seems that the DistributedLogPrimitive depends on things like StreamProcessing and Exporting since it uses the StateStorageController and the State to get the latest processed position etc. To have access to these kind of values we have some static Maps and create for example StateStorageController in the Primitive and also in the Partition, which is not necessary.

Could we just move the Primitive implementation in the Broker and install the Processing etc in the Primitive? This will also reduce some of the constructs we currently build and the usage of static maps I hope.

**Comment by npepinpe** [comment]
Yes to moving the primitive outside of logstream, we've been meaning to do that at some point anyway, and have the logstream module be just that, the log stream.

We also want to figure out how to better integrate the primitive into our dependency management/configuration system, to avoid using the static map.

The thing is, we have no control over when the `DefaultDistributedLogPrimitiveService` is started; the very first run, yes, we create it so no problem. But afterwards, Atomix will just recreate it by itself. That said, maybe it is a better solution to just do the minimum work with our services (i.e. read configuration, start Atomix, start DistributedLog service that gets a reference to the primitive), and have the `DefaultDistributedLogPrimitiveService` kickstart the start up of everything else (i.e. `BootstrapPartitions` which kickstarts `PartitionInstallService`, `PartitionLeaderElection`, and all other things). What do you think @deepthidevaki? It might be worth doing a quick spike to validate this.

**Comment by deepthidevaki** [comment]
+1 for moving primitive out of logstream.

It would be worth exploring the possibility of installing all partition services with in the primitive. We will be able to remove the static map if we don't need to pass any information in to or out of the primitive. 

One concern that I have is that Atomix re-creates the primitive during runtime (eg:- when it receives a raft backup from a remote node). I did not check how often this happens. How to handle (not) creating duplicate services if this happens? We already have this problem when creating logstream service with in the primitive.

**Comment by Zelldon** [comment]
we replaced the primitive with the atomix log
