### ISSUE TITLE
We swallow exceptions on BrokerSnapshotRestoreContext

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2541]
I saw this today that we swallow exceptions in the `BrokerSnapshotRestoreContext`, probably you thought we don't care if there was an error on opening the Database. But I'm not sure if this is a good way. If the log restoring not work because the opening always fails and the method always return minus -1, this would be nice to know. I think we should probably at least add a log statement with trace level.

Btw we already have some of this logic in the `Partition` to get the last exporter position. Maybe we can reuse some code here.

**Comment by deepthidevaki** [comment]
I agree with the exception handling. It is probably better to throw exception instead of returning -1, so that restore operation will be retried.
We already have an issue regarding duplicated logic #2522

**Comment by npepinpe** [comment]
I think this is solved? @deepthidevaki

**Comment by deepthidevaki** [comment]
Yes. Closing.
