### ISSUE TITLE
Merge ClientApiRule and PartitionTestClient

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2544]
At the moment the protocol test util contains a `ClientApiRule` and a `PartitionTestClient` where similar methods are implemented in many different ways. We should consolidate this and ensure that all methods have a unified way of usage and expected outcome. For example deployment should wait for `DISTRIBUTED` to ensure tests with with multiple partitions are not flaky because distributed didn't happen yet.

**Comment by npepinpe** [comment]
The `ClientApiRule` was removed as part of a refactoring.
