### ISSUE TITLE
Exporter interface does not declare that configure throws

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2546]
The docs say to throw in the `configure` method if your exporter is missing configuration or connections that it needs to operate.

However, the interface for `configure` does not declare that it throws, so unchecked exceptions will not compile.

That is to say, if I declare it as:

```java
configure(final Context context) throws Exception {}
```

```
configure(io.zeebe.exporter.api.context.Context) in io.zeebe.EventStoreExporter cannot implement configure(io.zeebe.exporter.api.context.Context) in io.zeebe.exporter.api.spi.Exporter
[ERROR] overridden method does not throw java.lang.Exception
```

Or
```java
configure(final Context context) {
	throw new IOException("No database, yo!");
}
```

```
 unreported exception java.io.IOException; must be caught or declared to be thrown
```

**Comment by jwulf** [comment]
It needs to be a `RuntimeException`. The way to do it is to catch any exception thrown in the `configure` method, then throw a `RuntimeException`, like this:

```java
try {
    sendBatchToEventStore(new JSONArray());
} catch (Exception e) {
    throw new RuntimeException(e);
}
```

**Comment by Zelldon** [comment]
I think you are right that it is more convenient with a throws clause on the interface.

**Comment by jwulf** [comment]
I tried to write a patch for it, but it breaks all existing exporter implementations....

**Comment by menski** [comment]
@npepinpe any reason we decided to not declare throw on these methods?

**Comment by npepinpe** [comment]
None other than we generally avoid checked exceptions, so it never came up in discussions.

I agree we should mark it as throws.
