### ISSUE TITLE
Feature: Add Prometheus metrics to exporter context

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2562]
It would be very useful to be able to write to the Prometheus metrics from an exporter, to check backpressure and aid in tuning batch size and export scheduling under various loads.

**Comment by Zelldon** [comment]
We already have some metrics for exporters, like exported records and skipped records. But you would like to have some more context specific?

**Comment by jwulf** [comment]
Yes, I'd like to emit metrics for REST exporters on REST calls and backlog

**Comment by menski** [comment]
This should be easy to achieve if we switch to the prometheus libs, then we don't even need to expose it through the context (#2576).
