### ISSUE TITLE
Broker should halt if exporter throws in configure

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2572]
At the moment the broker continues if an exporter throws in the `configure` lifecycle.

This means that the system is operating, but not how I expect it to.  

It would be preferably for me, as a system administrator, for the system to fail early so that I can identify and address the issue.

**Comment by npepinpe** [comment]
Can confirm this is already the case - the broker will instantiate all exporters once during startup and configure them - if this fails, then it will fail to start.
