### ISSUE TITLE
Exporter Controller#scheduleTask should return a cancellable timer

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2574]
At the moment scheduled tasks must handle themselves the case where they do not wish to run (i.e. no work is left to be done, or it is not necessary to run the task anymore, or similar tasks should be collapsed together, etc.). In such cases it is useful to be able to cancelled scheduled tasks. 

Considering the actor scheduler already has this concept, it shouldn't be too hard to extend it and add a `ScheduledTask` interface with a single `cancel` method to our exporters. This is purely a QoL feature, so low prio (imo), but it's also a low hanging fruit.

**Comment by aivinog1** [comment]
@npepinpe Hi! I would like to take this.

**Comment by npepinpe** [comment]
Sure, let me know if you have any questions. The actor scheduler isn't the most straightforward part of the code :wink:
