### ISSUE TITLE
Possibly unnecessary job activation in tests

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2600]
In some test classes, jobs are always activated before being completed despite it not being necessary. During the migration from broker to the engine module, the question was raised if this should be removed. The relevant test classes are CompleteJobTest, FailJobTest, JobTimeOutTest and JobUpdateRetriesTest

**Comment by npepinpe** [comment]
Dumb question maybe, but what do we want to achieve here?

**Comment by MiguelPires** [comment]
The goal was to simplify/shorten the tests but the benefit is probably not worth the effort.

**Comment by npepinpe** [comment]
I think you're better placed to know if it is worth doing or not - what do you think? If we don't expect to do this directly then I would close it.

**Comment by MiguelPires** [comment]
I'll close it then
