### ISSUE TITLE
Add a broker ready status in topology

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2610]
A broker is ready when the partition services for all the partition that it replicates is installed. I can know from the topology when a node is ready or not.

**Comment by Zelldon** [comment]
Be aware that the topology request is answered by the gateway (it uses the atomix cluster to get these information), so we don't ask a particular broker for the topology anymore. Just as a side note. I'm not sure if this is a problem or not

**Comment by deepthidevaki** [comment]
After the discussion, we decided not to update the topology, but only record the information in topology manager.
