### ISSUE TITLE
Resolving of an incident can lead to inconsistencies in the workflow instance

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#262]
Problem:
* when a command is executed to resolve an incident then a new (workflow instance) event is written
* if another command or event for the workflow instance is processed then the workflow instance may end in an inconsistent state  
* example: resolve incident + delete workflow instance

Related to Optimistic Logging Exception #178

**Comment by menski** [comment]
@ThorbenLindhauer and @saig0 is this still an issue with the new workflow instance processing and rocksdb?

**Comment by saig0** [comment]
I think it is still an issue. We should fix it when we rework the incident concept and port the incident state to RocksDB.

**Comment by ThorbenLindhauer** [comment]
I agree with @saig0. I think one of the problems is that the incident stream processor writes workflow instance events (not commands that could be rejected), which is still the case.

**Comment by Zelldon** [comment]
should be fixed with #1573
