### ISSUE TITLE
Potential race condition in DefaultRestoreInfoRequestHandler

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2633]
If snapshot is being deleted while the handler is calculating the number of chunks in the snapshot, it can return an incorrect number of chunks in the response. Probably not harmful because, when it later recieves `SnapshotRestoreRequest` the snapshot will be already deleted and the other node will restart the restore operation. But, it will be better to handle this case in the `DefaultRestoreInfoRequestHandler` itself.

**Comment by npepinpe** [comment]
One possible solution here would be to mark the snapshot as being deleted before starting deletion with a lock file (or something similar); each time a snapshot request is handled in `DefaultRestoreInfoRequestHandler` we can check for that marker, and return an error response. On the receiver side we can simply follow our default error handling strategy of restarting from the top.
