### ISSUE TITLE
Update checkstyle configuration

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2650]
* https://checkstyle.org/config_blocks.html#EmptyCatchBlock - yes, with comment format
* https://checkstyle.org/config_coding.html#EqualsAvoidNull - yes
* https://checkstyle.org/config_coding.html#DefaultComesLast - yes
* https://checkstyle.org/config_coding.html#InnerAssignment - yes
* https://checkstyle.org/config_design.html#InnerTypeLast - yes
* https://checkstyle.org/config_design.html#InterfaceIsType - yes
* https://checkstyle.org/config_coding.html#MagicNumber - enable and see what explodes
* https://checkstyle.org/config_coding.html#MissingSwitchDefault - yes
* https://checkstyle.org/config_design.html#MutableException - yes
* https://checkstyle.org/config_coding.html#NestedForDepth - https://checkstyle.org/config_coding.html#NestedIfDepth - https://checkstyle.org/config_coding.html#NestedTryDepth - yes, try with 1 and see what happens
* https://checkstyle.org/config_coding.html#OverloadMethodsDeclarationOrder - yes
* https://checkstyle.org/config_coding.html#ParameterAssignment - yes, probably explodes
* https://checkstyle.org/config_sizes.html#ParameterNumber - yes, try it and discuss how to refactor

**Comment by npepinpe** [comment]
Ok, so it seems `related to` also causes it to be closed now...

**Comment by menski** [comment]
Seems to be related to codetree and not GitHub. I can check the configuration later. Thanks for noticing

**Comment by menski** [comment]
I changed the config in codetree to not close issues on PR merge. Please try again and check if it now behaves again as expected.

**Comment by npepinpe** [comment]
So far checks related to code ordering should be done as:

1. Add the check style rules
1. Create IntelliJ code style for Zeebe based on the [Google style](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml)
1. Update style so it matches the new ordering rules
1. Reformat project using IntelliJ
1. Export style file to `build-tools` so it can be imported by others

After that, new code will be forced to use the ordering, but if you use the style then it's just a matter of using the built-in formatter (except for rearranging you need to use `Ctrl+Shift+Alt+L` and check `Rearrange entries` (see [here](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_file))

Since this is a change to everyone's workflow I'd like to discuss it with the team, but @Zelldon and @menski aren't there for a while so... :thinking:

**Comment by menski** [comment]
I use this plugin to automate actions on file save, it also supports rearrange as far as I remember 

https://plugins.jetbrains.com/plugin/7642-save-actions

**Comment by npepinpe** [comment]
Seems like it closed it again 🤷‍♂
