### ISSUE TITLE
Split metrics and http server configuration

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2652]
When the ready status of the broker is exposed via http server, it doesn't make sense if we keep the http configuration together with the metrics.

**Comment by deepthidevaki** [comment]
Here is a proposal for new config. Http server will be enabled always.
```
[network.httpServer]
# host = "0.0.0.0"
# port = 9600

[metrics]
# metricsFile = "metrics/zeebe.prom"
# reportingInterval = "5s"
```

**Comment by menski** [comment]
FYI we will remove the metrics file writer #2642

**Comment by npepinpe** [comment]
Should the configuration be more related to monitoring? At least we should document it for users so they know it's an http server for internal monitoring and they don't need to (and probably shouldn't) expose it.

**Comment by deepthidevaki** [comment]
May be name it `network.monitoring` to be more explicit?

**Comment by deepthidevaki** [comment]
After #2660, MetricsCfg contains only params related to http server. So may be we should just rename it to `MonitoringCfg` and document that it is for both metrics and general monitoring of the broker, which is currently only readiness check. In future it may also include live health check. What do you think? @menski @npepinpe

**Comment by menski** [comment]
I'm taking this over and will refactor the configuration during #2576
