### ISSUE TITLE
Please don't log all failed records on Elastic Search exporter failure

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2661]
I accidentally started a broker with the Elastic Search exporter enabled and no Elastic Search server.

My 4 CPU, 16GB machine running in Azure became unresponsive because it was repeatedly logging a failed deployment to the console, very fast.

The fact that it is failing is useful to me, but the data that didn't get exported less so.

**Comment by npepinpe** [comment]
This might be useful: https://logging.apache.org/log4j/2.x/manual/filters.html#BurstFilter/

**Comment by menski** [comment]
Minimal requirement, do not print all records which failed in the flush.
