### ISSUE TITLE
Investigate how we can store objects (variables) without indexing in elastic 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2665]
We would like to use json objects/maps instead of a string as `variables` value, see also #2625. If the value of the variables serialized as an json object, then they will be indexed by elastic.
But we would like to avoid the indexing, we need a solution to do that.

blocks #2628 
blocks #2625

**Comment by saig0** [comment]
In the template `zeebe-record-workflow-instance-creation`, we store variables as

```json
"variables": {
              "type": "object",
              "dynamic": false,
              "store": true,
              "index": true
            }
```

**Comment by npepinpe** [comment]
This is wrong and completely my fault, I imagine it should be 

```json
"variables": {
              "type": "object",
              "dynamic": false,
              "store": true,
              "index": `false
            }
``

**Comment by menski** [comment]
I'm currently trying to figure out if this is actually supported with es 6.8, see #2691
