### ISSUE TITLE
Can we loose events on append?

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2673]
I just had a look in the LogStorageAppener and was wondering how this works.

In the `LogStorageAppender` we consume the dispatcher and pass the blocks to the distributed log. After calling the async append, we directly mark the block as completed and complete the appending.

```java

  private void appendBlock() {
    final ByteBuffer rawBuffer = blockPeek.getRawBuffer();

    bytesToAppend = new byte[rawBuffer.remaining()];
    rawBuffer.get(bytesToAppend);

    // Commit position is the position of the last event. DistributedLogstream uses this position
    // to identify duplicate append requests during recovery.
    commitPosition = getLastEventPosition(bytesToAppend);
    actor.runUntilDone(this::tryWrite);
  }

  private void tryWrite() {
    distributedLog.asyncAppend(bytesToAppend, commitPosition);
    blockPeek.markCompleted();
    actor.done();
    /*// TODO: Handle error codes
    if (res >= 0) {
      blockPeek.markCompleted();
      actor.done();
    } else {
      // retry
      LOG.debug("Append failed, retrying");
      actor.yield();
    }*/
  }
```

In the DistributedLog at some point in time we receive the block *hopefully* and append this to the corresponding logstorage. 

```java

  @Override
  public long append(String nodeId, long commitPosition, byte[] blockBuffer) {
    // Assumption: first append is always called after claim leadership. So currentLeader is not
    // null. Assumption is also valid during restart.
    if (!currentLeader.equals(nodeId)) {
      logger.warn(
          "Append request from follower node {}. Current leader is {}.", nodeId, currentLeader);
      return 0; // Don't return a error, so that the appender never retries. TODO: Return a proper
      // error code;
    }

    return append(commitPosition, blockBuffer);
  }

  @Override
  public long append(long commitPosition, byte[] blockBuffer) {
    if (commitPosition <= lastPosition) {
      // This case can happen due to raft-replay or when appender retries due to timeout or other
      // exceptions.
      logger.trace("Rejecting append request at position {}", commitPosition);
      return 1; // Assume the append was successful because event was previously appended.
    }

    final ByteBuffer buffer = ByteBuffer.wrap(blockBuffer);
    final long appendResult = logStorage.append(buffer);
    if (appendResult > 0) {
      updateCommitPosition(commitPosition);
    } else {
      logger.error("Append failed {}", appendResult);
    }
    // the return result is valid only for the leader. If the followers failed to append, they don't
    // retry
    return appendResult;
  }
```

Does atomix guarantees that the append method of the primitive is called no matter what? Or can this be lost because of connection problems or idk what else can happen.
When the log storage returns an error code, because of an invalid block or full disk we just ignore this and just continue. Is this correct? 

It seems there some open TODO's in the code, maybe we need to tackle them before the release? Furthermore maybe we should wait on the future before we mark the block as completed?

**Comment by menski** [comment]
@deepthidevaki should be able to answer your questions.

**Comment by deepthidevaki** [comment]
> Does atomix guarantees that the append method of the primitive is called no matter what? Or can this be lost because of connection problems or idk what else can happen.

Atomix guarantees that the operations from a client is applied in sequence. The client also has a retry logic, when some operations are not delivered. As far as I understand, this would also work in case the leader changes and the client connects to new leader. But in our case, this is not a problem because client is running on the leader.

> When the log storage returns an error code, because of an invalid block or full disk we just ignore this and just continue. Is this correct?

Yes. We have an issue #2298 for that which I coincidentally started to worked on it today :slightly_smiling_face: . But, there is no proper way to handle this case other than retry the append with in the primitive or block the primitive. If the append failed in the follower, there is no way we can get it notified outside of the primitive. For #2298, I was thinking to loop for ever and thus block the primitive from making any progress so that it will never reach an inconsistent state.

**Comment by deepthidevaki** [comment]
> Furthermore maybe we should wait on the future before we mark the block as completed?

Do you mean using sync append? It is too slow because the future completes only after the operation is replicated to the quorum and applied on the leader.
Otherwise can we keep appending next blocks before marking a block as complete? Then if we track the futures, can we handle errors better?

**Comment by Zelldon** [comment]
Hey @deepthidevaki thanks for your answers.

> Yes. We have an issue #2298 for that which I coincidentally started to worked on it today 

Ah nice :+1: 

> But, there is no proper way to handle this case other than retry the append with in the primitive or block the primitive.

I'm not sure if this is correct.

> If the append failed in the follower, there is no way we can get it notified outside of the primitive
> For #2298, I was thinking to loop for ever and thus block the primitive from making any progress so that it will never reach an inconsistent state.

Blocking the next appends would be kind of problematic right? So maybe we wait then for the next snapshot and start with appending from the snapshot position again.

> Do you mean using sync append? It is too slow because the future completes only after the operation is replicated to the quorum and applied on the leader.
> Otherwise can we keep appending next blocks before marking a block as complete? Then if we track the futures, can we handle errors better?

I was more thinking of using `whenComplete` or something similar which only marks the block as complete when the future is complete. If the future was completed with an exception we can mark the block as failed.
