### ISSUE TITLE
cancelWorkflowInstance with a malformed key causes 13: INTERNAL

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2680]
On Zeebe 0.18, if I try to cancel a workflow instance passing in a bad key (example: `lolwut`), I see an error message on the broker saying:

```13 INTERNAL: Unexpected error occurred during the request processing```

The gateway does not throw an error in the Node client.

To replicate:

Throws as expected:
```TypeScript
try {
	await zbc.cancelWorkflowInstance('2251799813686202')
} catch (e) {
	expect(e.message.indexOf('5 NOT_FOUND:')).toBe(0)
}
```

Does not throw, causes `13 INTERNAL: Unexpected error occurred during the request processing` on the broker:
```Typescript
try {
	await zbc.cancelWorkflowInstance('lolwut')
} catch (e) {
	expect(e.message.indexOf('5 NOT_FOUND:')).toBe(0)
}
```

This cannot be replicated by `zbctl` because it sanitises the key:

```
# Behaves as expected
➜ bin/zbctl.darwin cancel instance 2251799813686202
Error: rpc error: code = NotFound desc = Command rejected with code 'CANCEL': Expected to cancel a workflow instance with key '2251799813686202', but no such workflow was found

# Unable to trigeer condition
bin/zbctl.darwin cancel instance lolwut
Error: invalid argument "lolwut" for "key": strconv.ParseInt: parsing "lolwut": invalid syntax
```

**Comment by menski** [comment]
The protocol defines the `workflowInstanceKey` as `int64`, the client should not accept strings as valid input.
https://github.com/zeebe-io/zeebe/blob/a6f493eb1694906ccd64214058564ef2980e145c/gateway-protocol/src/main/proto/gateway.proto#L67
