### ISSUE TITLE
Possibly flatten metadata into LoggedEvent

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2682]
After #2631 the Record will contain the metadata attributes directly instead of the RecordMetadata. However, the RecordMetadata is still used internally and contained by the LoggedEvent. We should discuss if this should be flattened as well so the RecordMetadata (and related classes) can be removed

**Comment by saig0** [comment]
For now, we will leave it as it is. The current approach could make it easier to deal with newer versions. Let's see and continue the discussion when we have more insides.
