### ISSUE TITLE
Require all nodes as initial contact points

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2684]
As a temporary fix for https://github.com/zeebe-io/atomix/issues/16, we should document that all nodes must be specified as initial contact points to ensure network partitions heal properly.

**Comment by Zelldon** [comment]
Did you tested broadcastUpdates property? https://atomix.io/docs/latest/user-manual/configuration/reference/#swim-protocol

**Comment by deepthidevaki** [comment]
Looks like `broadcastUpdates` is used only when propagating failure suspects.

**Comment by Zelldon** [comment]
Ah ok thanks
