### ISSUE TITLE
Add note to Message Correlation on Subscription 

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2688]
If I have an interrupting boundary message event, then any instances of that workflow must have a  value for the correlation key variable _when they start_. They cannot start with that undefined (that variable missing from the payload) and have it set at a later stage.

If that variable is not present when the token enters the process, it raises an incident.

I’m left wondering if it also means that a correlationKey value cannot be mutated inside a process. Obviously a subscription is opened when the token enters the process, using the current correlation key value. Is the subscription modified when the correlation key value changes?

Answer: No, the subscription does not update if the correlationKey value changes in the payload. It is created once on entry to the interruptible process.

**Comment by Zelldon** [comment]
Hey @jwulf,

just some corrections.

> If I have an interrupting boundary message event, then any instances of that workflow must have a value for the correlation key variable when they start. 

Not the workflow instance, but the element instance need this variable if the element is entered, which has a corresponding boundary event.

> If that variable is not present when the token enters the process, it raises an incident.

When it enters the element.

> Obviously a subscription is opened when the token enters the process, using the current correlation key value. Is the subscription modified when the correlation key value changes?

The subscription is created when the element is entered. Then yes the subscription can't be changed.
