### ISSUE TITLE
Include grpc direct from protobuf file

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2701]
Currently we have a not up to date copy of the protobuf file in the docs, see https://docs.zeebe.io/reference/grpc . As it happens with copies they often become stale we should try to directly include it.

**Comment by npepinpe** [comment]
I think we discussed it last time, and the result was that we liked the nicer format of the docs one. But we can challenge that.

**Comment by Zelldon** [comment]
Yes but i think the maintenance problem outweighs

**Comment by menski** [comment]
For now we will keep the sections as they improve the readability. We have to make sure that protocol additions after the GA are also updating the docs.

**Comment by npepinpe** [comment]
I think it's worth investigating how to do it better, is this really just a binary direct include vs manually formatting it? Maybe we can find something in between? e.g. [This](https://github.com/pseudomuto/protoc-gen-doc) can generate Markdown from protobuf files.
