### ISSUE TITLE
Handle corrupt raft snapshots

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2707]
Reference for https://github.com/zeebe-io/atomix/issues/14

After we have a "fix" in atomix we have to build a new fork release and use it in the broker.

**Comment by npepinpe** [comment]
So https://github.com/zeebe-io/atomix/pull/18 does not handle corrupt snapshots per se but it does prevent us from getting an inconsistent log, for the GA I think this is good enough (:tada:), but I hope we work on a better solution with the Atomix guys next quarter.

**Comment by npepinpe** [comment]
Closed via https://github.com/zeebe-io/atomix/pull/18
