### ISSUE TITLE
Spike: Clustering components should handle Connection Errors

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#272]
#### Problem

At the moment exceptions triggered by closed connections or not reachable hosts are not handled. This leads to a lot of exceptions printed on `System.out`. With this behavior it is complicated to test different cluster scenarios where nodes leave the cluster or rejoins. Because when a broker is stopped all other members start to print the connection exceptions. And this are so many that my machine basically is not usable in a scenario with 4 brokers. Also when a broker rejoins the exceptions do not stop, so it seems that there are still references to the already closed connections which are still probed.

#### Spike

This spike should explore possibilities to handle these exceptions in a better way. Which allows users and developers to still use a broker even if another broker was removed from the cluster. This will prevent the broker from flood the user with useless exceptions. And allows developers to test cluster scenarios with out to requirements to come up with solutions to filter the `System.out` for useful messages.

#### Side Node

Maybe it is also time to think about error signaling from the transport layer. Maybe exceptions are not the way to go here.

**Comment by meyerdan** [comment]
Not needed anymore
