### ISSUE TITLE
Exporter call-by-reference option

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2728]
Exporters are currently called by value, which means the complete logged event buffer are copied and a new Record is created. This is the default behavior, otherwise the exporters would observe weird behavior if they collect the records for batching purposes or just for recording or something similar.

This approach is not ideal to get high throughput on exporting, since the buffer is first copied and afterwards probably the `#toJson` is called, like it is done in the `ElasticSearchExporter`.

To improve the export performance of the `ElasticSearchExporter` we could think of a separate configuration parameter, which toggles this behavior such that no copy is created.

I think it makes sense to give the possibility to

**Comment by saig0** [comment]
So, you propose to not copy the buffer if the exporter process it directly.
If the exporter store the records first and process them in batch then you would copy the buffer. Correct?

**Comment by Zelldon** [comment]
Yes :)

**Comment by saig0** [comment]
I like it :+1: I guess that it would be the default behavior of the exporters.

**Comment by Zelldon** [comment]
> I guess that it would be the default behavior of the exporters.

Nah I'm not sure. If this is the default behavior we will have multiple issues where users see weird behavior. I think it is not intuitive and obvious. If we have this as configuration parameter the user can think about it as first :sweat_smile:

**Comment by npepinpe** [comment]
I think it might not be as uncommon; for example, Kafka batching (not the Kafka exporter, the normal Kafka stuff) batches the serialized records, not the records themselves, which is not a bad idea. I don't think it's so ridiculous to ask exporter authors to copy or create a specific data representation for their own needs when it comes to batching.

**Comment by Zelldon** [comment]
Ok nice, not expected that but it seems the majority is for default behavior :tada::laughing:

**Comment by npepinpe** [comment]
I mean verify with @menski , but I think it's not such a horrible requirement from exporter authors, and I think most exporters will anyway need to transform the model...so maybe as a compromise/helper we at least make sure that to provide a `copy` method for QoL

**Comment by Zelldon** [comment]
Maybe we should do this before the release @menski ? :sweat_smile:

**Comment by Zelldon** [comment]
Created a new branch (2728-exporter-no-copy) which does the following:

The `Record` interface now extends `Clonable` and gets a new method `#clone`, which creates a deep copy of the record. We can discuss if we want to go this way or not supporting `Clonable` and just have a `copy` method, was unsure here.

Records for an Exporter will wrap the internal buffer, which means we will not copy the record before we call the `#export` method. If an exporter wants to collect records for later usage, like the `RecordingExporter` he has to call `#clone` otherwise the exporter will see weird output.

I tried to update the exporter java doc.

One missing thing is the `toJson` conversion, since `#toJson` is now called on the `TypedEventImpl`. This means we try to directly convert msgpack to JSON, which is good but I think the current format is not exactly the same.
