### ISSUE TITLE
Use protocol for gossiping node properties

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2739]
At the moment the broker information for the topology are gossiped using JSON, which does not allow easy version management and extension. We should use one of our protocols, i.e. protobuf or SBE.

**Comment by npepinpe** [comment]
Considering we use SBE for inter broker communication so far, intuitively I'd say let's remain consistent. Of course we can challenge that if enough of us feel strongly about using protobuf in other places, the topology isn't exactly a high performance area...

**Comment by menski** [comment]
I'm currently implementing it using SBE to be consistent with our internal communication protocol.
