### ISSUE TITLE
Should we replace or refactor the ServiceContainer 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2749]
We should think about whether we want to maintain the service container as our own dependency injection and management framework and refactor it or move to a more common solution which is widely used and proved.

If we want to keep the service container I think we should take a look whether we can refactor it,
since the complexity of the implementation is high and not easy to understand or follow.
Furthermore to install a service we need a lot of boilerplate code, which is not ideal. See for example the `EngineService`:

```java

public class EngineService implements Service<EngineService> {

  private final Injector<ServerTransport> commandApiTransportInjector = new Injector<>();
  private final Injector<TopologyManager> topologyManagerInjector = new Injector<>();
  private final Injector<Atomix> atomixInjector = new Injector<>();

  private ServerTransport commandApiTransport;
  private TopologyManager topologyManager;
  private Atomix atomix;
  private final ServiceGroupReference<Partition> partitionsGroupReference =
      ServiceGroupReference.<Partition>create().onAdd(this::startEngineForPartition).build();

  public EngineService(ServiceContainer serviceContainer, BrokerCfg brokerCfg) {
    clusterCfg = brokerCfg.getCluster();

    this.serviceContainer = serviceContainer;
    final DataCfg dataCfg = brokerCfg.getData();
    this.snapshotPeriod = DurationUtil.parse(dataCfg.getSnapshotPeriod());
  }

  @Override
  public void start(final ServiceStartContext serviceContext) {
    this.serviceContext = serviceContext;
    this.commandApiTransport = commandApiTransportInjector.getValue();
    this.topologyManager = topologyManagerInjector.getValue();
    this.atomix = atomixInjector.getValue();
  }

 // ...


  @Override
  public EngineService get() {
    return this;
  }

  public Injector<ServerTransport> getCommandApiTransportInjector() {
    return commandApiTransportInjector;
  }

  public ServiceGroupReference<Partition> getPartitionsGroupReference() {
    return partitionsGroupReference;
  }

  public Injector<TopologyManager> getTopologyManagerInjector() {
    return topologyManagerInjector;
  }

  public Injector<Atomix> getAtomixInjector() {
    return atomixInjector;
  }
```

And installing the service then looks like this:

```java

    final EngineService streamProcessorService =
        new EngineService(serviceContainer, brokerConfiguration);
    serviceContainer
        .createService(ENGINE_SERVICE_NAME, streamProcessorService)
        .dependency(
            TransportServiceNames.serverTransport(TransportServiceNames.COMMAND_API_SERVER_NAME),
            streamProcessorService.getCommandApiTransportInjector())
        .dependency(
            ClusterBaseLayerServiceNames.TOPOLOGY_MANAGER_SERVICE,
            streamProcessorService.getTopologyManagerInjector())
        .dependency(
            ClusterBaseLayerServiceNames.ATOMIX_SERVICE, streamProcessorService.getAtomixInjector())
        .groupReference(
            ClusterBaseLayerServiceNames.LEADER_PARTITION_GROUP_NAME,
            streamProcessorService.getPartitionsGroupReference())
        .install();
```

I think if we use a different framework or just refactor the container, we could write the dependencies and service like this.

```java
@Service
public class EngineService implements Service<EngineService> {

  private final ClusterCfg clusterCfg;
  private final Duration snapshotPeriod;
  private ServiceStartContext serviceContext;

  private ServerTransport commandApiTransport;
  private TopologyManager topologyManager;
  private Atomix atomix;
  private BrokerCfg brokerCfg;

  @Inject
  public EngineService(
      ServerTransport commandApiTransport,
      TopologyManager topologyManager,
      Atomix atomix,
      BrokerCfg brokerCfg) {
    this.commandApiTransport = commandApiTransport;
    this.topologyManager = topologyManager;
    this.atomix = atomix;
    final DataCfg dataCfg = brokerCfg.getData();
    this.snapshotPeriod = DurationUtil.parse(dataCfg.getSnapshotPeriod());
  }
```

**Comment by saig0** [comment]
Possible frameworks for replacement:
* [Google Guice](https://github.com/google/guice)
* [Google Dagger](https://github.com/google/dagger) 
* Spring Core/Boot

**Comment by menski** [comment]
@npepinpe any other frameworks you are aware of?

**Comment by npepinpe** [comment]
Nope; Guice and Dagger are the only ones I've heard of in Java that do only DI (and I only have minimal experience with Dagger for Android). But I like the idea of using one :+1:

**Comment by npepinpe** [comment]
I think a good replacement for us would be [Netflix/Governator](https://github.com/Netflix/governator). It extends Guice to add lifecycle management, which should then cover all the features we need from our service container (which was both a DI framework and a IoC container). My only issue here is that Netflix is semi-famous for dropping stuff after a while...but so is Google, so... :man_shrugging: 

I think we should try it.

**Comment by npepinpe** [comment]
I did a bit more research, I would propose we try out [Gorvernator](https://github.com/Netflix/governator) (Guice with Lifecycle Management) and [PicoContainer](http://picocontainer.com/), a *very* light IoC container framework that does DI and lifecycle management as well. PicoContainer looks like it's straight from the 90s, but imo shouldn't be discounted - see [StackOverflow](https://stackoverflow.com/a/2028034).

I would also challenge the need for the service container at all - does it truly help us be more productive, over manually managing the dependencies? Is our dependency graph so complicated, or does it just seem so because we have no clear overview of it at the moment and rely too much on the container to manage the lifecycle?

**Comment by npepinpe** [comment]
Regarding the group references, for everything that uses the partition groups, we can simply use the Atomix partition service, which also allows registering listeners to keep track of the different roles (in the cases where we need to know only for leader/follower).
