### ISSUE TITLE
Spike: Create clustering testbed to verify long running stability

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#276]
TNGP is meant to be run in a cluster scenario for a long time without restarts. This requires that TNGP handles different kinds of external influences, e.g. by the network, disk and filesystem. To verify that TNGP can run for a long time without interrupts a testbed could be setup which can be used to run manuell tests. Additionally a permanent workload should be generated automatically.

This could help to detect rarely triggered race conditions and instabilities in handling external resources  (connections, fs writes, etc.).

Also monitoring of the nodes and network could give more insides in the requirements of TNGP and also detect anomalies.

**Comment by meyerdan** [comment]
We have created something which allows to run these kinds tests
