### ISSUE TITLE
Stop on-demand snapshot replication if snapshot pushed by leader

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2767]
There are two points where replicate snapshots: one is on-demand while restoring the primitive, and the other is when the leader pushes a new snapshot to us.

Right now, there is an edge case where if the snapshot is pushed and replicated by the leader right after on-demand replication started (but before a single chunk is replicated), all chunks are ignored and the `NoSuchFileException` is thrown when trying to move the directory.

If this happens while the leader is pushing the snapshot then we keep this behaviour, as we can't stop the leader; but for on-demand replication, we should detect this and stop requesting more chunks and just keep restoring.

**Comment by npepinpe** [comment]
Related to #2762

**Comment by Zelldon** [comment]
I think this is outdated.
