### ISSUE TITLE
Spike: Define metrics which could be used for raft balancing

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#277]
We will start with a very simple approach to balance raft leaders and followers in a cluster. This will achieve a homogeneous distribution of leaders and followers. Meaning that every node is approximately leader and follower of the same number of partitions. This assumes that every partition has the same workload. In the sense of nearly the same number of clients and similar workflows to execute.

As this simplification may not match the actual workload observed in a real world scenario it would be interesting to understand which metrics characterize the workload of a cluster node. And how these can be collected and used to better distribute the partitions, leaders and followers.

**Comment by meyerdan** [comment]
Le's close for now
