### ISSUE TITLE
Migrate ES exporter IT tests to use TestContainers instead of separate JVM

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2770]
We use a plugin to start a separate JVM for Elasticsearch for our Elasticsearch Exporter integration tests. This was a limitation back when we ran our own Jenkins with an old docker version; now that we moved to the cloud, we can use https://www.testcontainers.org/ to easily start Elastic instances for our tests.

**Comment by Zelldon** [comment]
I think this is done right?
