### ISSUE TITLE
Replace simple-monitor with Operate in getting started guides

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2777]
Currently https://stage.docs.zeebe.io/java-client/get-started.html and https://stage.docs.zeebe.io/go-client/get-started.html contain simple-monitor gifs to visualize the workflow instance state etc.

We should decide if we want to keep this, delete these visualizations or replace them with Operate.

**Comment by menski** [comment]
@wints I guess this is your call

**Comment by wints** [comment]
I think this is something we should do eventually, but it's not a must-have for the pre-release. Will assign to @jwulf in case he wants to tackle it in the future.

**Comment by npepinpe** [comment]
@menski let's talk about this, not sure how to prioritize it

**Comment by npepinpe** [comment]
Closing as this should be done as part of the new documentation project.
