### ISSUE TITLE
Challenge LogStreamReader#getPosition API

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2783]
I want to challenge the `LogStreamReader#getPosition` API, which is currently a bit confusing and also related to a bug which was fixed with #2782. 

The position which is returned by the `getPosition` is the position of the last returned event not the position of the reader

**Comment by Zelldon** [comment]
On refactoring the logstream api we should remove this @npepinpe

**Comment by Zelldon** [comment]
We should remove it https://github.com/zeebe-io/zeebe/blob/develop/logstreams/src/main/java/io/zeebe/logstreams/log/LogStreamReader.java#L64

**Comment by npepinpe** [comment]
atm it's used strictly for testing, so I don't see anything that speaks against removing it :+1:

**Comment by Zelldon** [comment]
I think we remove that already.
