### ISSUE TITLE
Remove data.directories setting from zeebe.cfg.toml

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2789]
I propose that we remove the data.directories config option from zeebe.cfg.toml.

The data.directories config option is old school and hasn't been maintained or tested. According to @saig0 it is not respected across the board - in at least some places the  parameter is ignored and only the first value is used.

**Comment by Zelldon** [comment]
Not sure what you're referring to and why we should remove it :thinking: Could you elaborate on that? Is this still the case that you want to remove it?

**Comment by npepinpe** [comment]
From my point of view, this is mostly confusing for users. We only look at the first directory, so configuring multiple ones does nothing.

Please deprecate in favour of a new configuration option `directory`, but fallback to the `directories` if not specified by the user.

Note that I would still like to try specifying multiple directories, but I think the interface will be different - we can look into this at a later point.
