### ISSUE TITLE
Inquiries about elasticsearch index rotations

### ISSUE THREAD

**Issue by OlivierAlbertini** [zeebe-io/zeebe#2807]
Hi,

First, thanks for supporting Elasticsearch as official exporter.
I use Zeebe a couple of days and here alias/indexes in Elasticsearch:

![Capture d’écran, le 2019-07-08 à 12 35 47](https://user-images.githubusercontent.com/3801683/60827031-3b563480-a17d-11e9-9264-3934db12d325.png)

I'm wondering why you rotate indexes based on date ?

Indeed, by default, I would rotate index based on size (It could be configurable with through the exporter config) but It will be safe to set a default size to 20go (depending hardware, you could go to 40go).
This would decrease the rotation and the number of index. Queries would be more performant since you reduce the number of index to query. The throughput will significantly better.

Let me know, thanks!

**Comment by npepinpe** [comment]
@menski ? I'm not familiar enough with Elastic to answer this :slightly_smiling_face:

**Comment by menski** [comment]
Timebased indexing is a common pattern in log ingestion in Elasticsearch. We had in mind that you might only want to keep data for a specific time frame, to ensure all external tools where able to import the data correctly.

There is value in having a different approach, an interesting article about that is for example https://www.elastic.co/blog/managing-time-based-indices-efficiently

**Comment by menski** [comment]
For now we don't plan to change the index rotation.
