### ISSUE TITLE
Netty: connection reset by peer

### ISSUE THREAD

**Issue by RedUno** [zeebe-io/zeebe#2809]
Hi, 
Using zeebe 0.18.0, running on kubernetes as a cluster of two nodes. I'm having warnings bellows every 10 to 40s. is this a normal behaviour or there is something wrong?
 thanks.

> INFO: Transport failed
> io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
>         at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
> 
> Jul 09, 2019 7:02:03 AM io.grpc.netty.NettyServerTransport notifyTerminated
> INFO: Transport failed
> io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
>         at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
> 
> Jul 09, 2019 7:02:13 AM io.grpc.netty.NettyServerTransport notifyTerminated
> INFO: Transport failed
> io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
>         at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)

**Comment by Zelldon** [comment]
Please update to the latest version
