### ISSUE TITLE
ExporterManagerTest shouldRemoveExporterFromState is flaky

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2810]
```
java.lang.AssertionError:
Expecting:
<[-1L,
2251799813685251L,
-1L,
2251799813685252L,
2251799813685252L,
2251799813685252L]>
to contain:
<[2251799813685250L, 2251799813685252L]>
but could not find:
<[2251799813685250L]>
at io.zeebe.broker.exporter.ExporterManagerTest.shouldRemoveExporterFromState(ExporterManagerTest.java:112)
```

**Comment by menski** [comment]
The issue seems to be that no snapshot is taken after the exporter is removed. So after the last restart the exporter is still known and old records are not exported

**Comment by menski** [comment]
I ignored the test for now as it often fails on CI https://github.com/zeebe-io/zeebe/commit/02d23914493cbfe9589e9cf165fcd879e0215f59

**Comment by Zelldon** [comment]
There is open bug issue for this https://github.com/zeebe-io/zeebe/issues/2490

**Comment by menski** [comment]
The test explicitly writes an event, we created #2490 to remove this workaround from the test.

https://github.com/zeebe-io/zeebe/blob/fb1a1db6d928f3c7a387835b04208205cc911c53/broker-core/src/test/java/io/zeebe/broker/exporter/ExporterManagerTest.java#L100-L102

**Comment by saig0** [comment]
Currently, the `ExporterManagerTest` doesn't test the behavior of the `ExporterManager`. Since the broker has more exporters configured, it calls the `ExporterDirector` instead. 

I think we need to refactor the `ExporterManager` first in order to write a reliable test.

**Comment by pihme** [comment]
I would suggest to close this issue. It hasn't occurred once in the weeks since I started tracking flaky tests. That means it hasn't occurred once in over 4 weeks,

The class has changed and is now `io.zeebe.broker.exporter.stream.ExporterDirectorTest#shouldRemoveExporterFromState`

**Comment by Zelldon** [comment]
No because the test is ignored right?

**Comment by pihme** [comment]
If it's ignored, please tell me where the statement to ignore the test is configured. 

(there is no annotation in the test; +I didn't find any text references to the method in the code base - it might be configured in a black list file, but then I would expect it to reference the method)

**Comment by Zelldon** [comment]
Ok weird I thought it is still ignored. I think you're right.
