### ISSUE TITLE
http-debug shows exception on 0.19.0.alpha 

### ISSUE THREAD

**Issue by vpathare** [zeebe-io/zeebe#2821]
The http-debug show javascript exception as below:

Uncaught (in promise) TypeError: Cannot read property 'valueType' of undefined
    at checkboxForRecord ((index):132)
    at (index):128
    at Array.filter (<anonymous>)
    at filterRecords ((index):128)
:8000/favicon.ico:1 Failed to load resource: net::ERR_EMPTY_RESPONSE

It looks like exporter is not publishing data correctly

**Comment by saig0** [comment]
Thank you for reporting. :+1: I can reproduce the issue with 0.19.0. 

The problem is that the JS is not updated to the new record schema.
