### ISSUE TITLE
The configuration file and path fixed in /bin/broker

### ISSUE THREAD

**Issue by vpathare** [zeebe-io/zeebe#2830]
The configuration file and relative path  is fixed in /bin/broker. So its difficult to override the configuration for each instance of zeebe broker.

Can we have facility to override configuration and log path with environment variables. Similar issue with operate as well.

**Comment by vpathare** [comment]
The elasticsearch provide this facility and we can run different instances with diff configuration.

**Comment by Zelldon** [comment]
About what kind of scenario we talking about? In k8s you could create a configmap and mount that to that specific point.

**Comment by Zelldon** [comment]
Due to inactivity I will close this issue. Feel free to reopen it.
