### ISSUE TITLE
Deploy workflow with parallel multi-instance sub-process

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2846]
**Is your feature request related to a problem? Please describe.**
I want to use parallel multi-instance on a sub-process to execute it for each element of a collection.

**Describe the solution you'd like**
* when the sub-process is entered, it creates one instance of each element in the collection
* when all instances are completed, the sub-process is left

Same as for service tasks #2845.

requires #2845

**Comment by saig0** [comment]
**Bonus:** parallel multi-instance receive task :candy:

**Comment by knji** [comment]
Guys is this feature available for preview in 0.21?

**Comment by saig0** [comment]
Multi-Instance is supported with 0.21.0. The release will be available in the next days. If you don't want to wait then you can use the lastest 0.21.0-alpha3 release. Have fun :balloon:
