### ISSUE TITLE
File ordering convention

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2866]
**Description**

Splitting off from #2650, as this one is about reformatting to have a more consistent style and improve readability.

This will change the development workflow a little, as the google format plugin doesn't care about ordering within a file.

Part of the PR will be to provide the IntelliJ Java code style XML in our `build-tools` project so everyone can import and use it; when formatting IntelliJ can take care of rearranging the code, keeping overloaded methods together, etc. Then we can add Checkstyle rules to enforce this (to some extent), as well as the import ordering (as defined by the google java formatter).

### Ordering

Given a Java class/interface/enum, proposed ordering of its body is:

1. Constants (i.e. `public static final ...`) in order of visibility (public, protected, package private, and private)
1. Static fields, in order of visibility
1. Static initialization block
1. Final instance fields, in order of visibility
1. Instance fields, in order of visibility
1. Instance initialization block
1. Constructors
1. Methods
  1. Overloaded methods will be grouped together based on the type they overload
1. Inner enum/interface/class*

* Since IntelliJ requires us to specify a single type, there is an explicit ordering here where inner enums are first, then interfaces, then classes; there is no way to just say "inner type" unfortunately.

### Considerations

This is basically the Oracle Java conventions for file ordering. Methods are recommended to be kept together according to functionality; I've seen other places where methods are ordered by visibility (what I usually do on top of keeping overloaded methods together). Some projects also put static methods before instance methods, before or after the constructor (e.g. Atomix does this to some extent). There I have no strong preference, but if anyone does I'd be OK with applying that.

**Comment by npepinpe** [comment]
@saig0 I assigned you just to check in if you have any objections before I reformat everything; also @Zelldon if you find a minute to just quickly check just in case 🙂

**Comment by Zelldon** [comment]
I like that we use the java conventions as default, I think this makes sense. From my feeling I would write private as first and then later public, but I don't know where this came from. Personally I mostly avoid public fields anyway. I'm OK with this order you mentioned, since this is a java convention. 

Probably I would move static method over fields, which means under class fields. Feels somehow related, since they belong to the class (static fields and static methods) and then the fields and methods which belong to the object. This is probably a matter of taste. :man_shrugging: Would be interesting what you guys think

**Comment by saig0** [comment]
I'm fine with the Java conventions. It's also like I would do it ;)

**Comment by npepinpe** [comment]
> Probably I would move static method over fields, which means under class fields. Feels somehow related, since they belong to the class (static fields and static methods) and then the fields and methods which belong to the object. This is probably a matter of taste.

I also prefer this, but I had no strong argument for it so I didn't include it as it's really just a matter of taste :sweat_smile:
