### ISSUE TITLE
zeebe-operate configuration customization

### ISSUE THREAD

**Issue by vpathare** [zeebe-io/zeebe#2882]
**Description**
Hi,

I am using Zeebe and Operate to test my usecase. But I want to use Operate configuration location to be $HOME/application.yml instead of "$BASEDIR/config".

I tried to send Sprint argument "spring.config.name and spring.config.location" to use different path and file name. It doesn't work. Do we have any alternate way to provide config file and location to operate.

**Comment by romansmirnov** [comment]
Hi @vpathare,

The easiest way to override the configuration is to set the `CLASSPATH_PREFIX` variable to the folder containing your `application.yml`

```
./bin/operate CLASSPATH_PREFIX=<path_to_your_configuration>
```

Best,
Roman

**Comment by vpathare** [comment]
Hi Roman,

I tried below suggestion but it doesn't work as expected. It doesn't look at my new configuration folder. 

1. I renamed config folder to new-name and changed all ports in config_new/application.yml
2. call `./bin/operate CLASSPATH_PREFIX=<abs path>/config_new/`
3. my new ports are not considered.

**operate still connect to port localhost:9200 & localhost:26500**

Regards,
Vaibhav
