### ISSUE TITLE
Workflow deployments and partitioning

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#290]
When deploying a bpmn xml, it is sent to the broker, where it is validated and if valid, a new workflow definition is created which is assigned a version. The version is currently used when creating an instance: this always used the "latest" version.

Currently this is done against a single partition of the topic to which the workflow is deployed.

**Problem:** how should this work with multiple partitions?

If we naively apply the current implementation, we would probably have the client orchestrate deployment against all partitions of the topic. However, this raises the following questions:
* Do we need to guarantee atomicity? What happens if deployment against 7 partitions succeeds but fails against the 8th partition? 
* Do we need broker assigned versions? How to guarantee that the same version is assigned on all partitions? Multiple racing deployment commands could be executed in a different order on different partitions assigning different versions.

**Initial Assumptions**

I would immediately discard all alternatives which do not maintain atomicity in the sense that the deployment is successful (from the point of view of the client) but it effectively failed (or is not yet completed) on some of the partitions.

Also, I would like to see an implementation where the client does not act as the coordinator. This kind of complexity should not need to be handled in the client.

**Implementation alternatives**

Remains the question of whether broker assigned versions need to be supported or not.

If true, generation of these versions needs to be _localized_ in some way, meaning some variation on initially all deployments going through the same partition. This can either be a special topic which only has a single partition or it can be a special partition on the existing topic (ie. the first).

1. The client initially sends the deployment to a random broker node which validates it and then coordinates a deployment to all partitions of the selected topic. If deployment to one of the partitions fails or times out, the coordinator attempts to roll it back on the other partitions as well. We accept that the "roll-back" can fail and an orphaned deployment remains. Compaction will get it. In this option, broker-assigned versions are not supported.
2. The workflow deployment it coordinated by a processor on a special topic which has a single partition only (Alternative: special partition, ie. always Partiton 1). Initially, all deploy commands go through this partition and get executed sequentially. As a first step a deployment is validated and the version is assigned. Once successful, it is then propagated to all partitions of the target topic with the semantics outlined in Option 1 (failure to deploy to one of the partitions rolls back the deployment).

**Thinking outside the box**

There could also be completely different solutions or approached which lead to the problems not appearing at all or the problems appearing in a different shape. Example:
There could be a 1 to 1 deployment <> topic mapping: creating a deployment effectively means creating a new topic. In this case the workflows are propagated to all partitions upon creation of the topic.

**Next Steps**

I would like to collect feedback on this until 9.6 and then write the spec.

**Comment by saig0** [comment]
We choose option 2: the deployment command is sent to the system topic which distributes the create workflow event to the partitions.

Followup on #482
