### ISSUE TITLE
Client API for defining a new Topic

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#291]
Currently it is not possible to define a topic using the client API.

A topic has the following properties:

* Topic Name (String): uniquely identifies the topic in the cluster
* Number of Partitions (int): the number of "shards"
* Desired Replication Factor (int): number of copies that should be kept kept for each partition. Commit is defined as the quorum of this number.

The client should be able to execute a command which defines a new topic and allocates the requested partitions and replicas.

# Questions

1. How to guarantee that the topic name is unique in the cluster?
2. Should the client be able to block until the topic is allocated in the sense that if it executes a request right after the topic definition command returns, the command is successful?
3. Balancing of partitions and replicas? -> See: #226 and #227
4. Should atomicity be guaranteed? (What happens if 7 partitions can be created but the 8th one fails to create?)

# Implementation Idea

Introduce management topic as built-in system topic with single partition to localize decisions.

* To guarantee **uniqueness** of the topic name, some form of _locality_ is required. In this approach, a **management topic** is introduced to which commands are initially sent. This topic is built-in and has a single partition only. (This is similar to a database using a special system table for maintaining metadata of user-defined tables.) The current leader for this topic has a stream-processor responsible for coordinating management operations across the cluster. It inspects a "define topic" cmd received by a client and validates it against it's internal state. Does a topic with the provided name already exist? If the request is valid, it can now coordinate creating the requested partitions.
* After inspecting and validating the "create-topic" cmd, the stream processor creates a set of sub-cmds, one for each partition. Executing the sub cmds can be retried until they eventually succeed. The client which submitted the initial "create-topic" cmd receives a positive response once the first partition is created. It can then start submitting requests to the first partition.
* This approach would have the advantage that there would be a system topic which can be queried for an exact listing of topics / partitions in the cluster ("Schema"). Note that it would not contain the assignment of partitions to nodes and master / leader assignments ("Topology"). The latter should not be centralized but should continue to be distributed, as well as the balancing algorithms.

Effectively this means that ZB has a a layered approach to cluster / topic management:

* Bottom layer (distributed):
    * filling up (or shrinking down) raft groups: when a raft group does not have enough members to satisfy it's replication level, the leader invites new members to join the group
    * balancing (see #226 and #227)
* Upper layer (centralized): service running off a built-in system topic coordinates creation and destruction of user-defined topics. This service itself requires the bottom layer to function.

Or in other words: things that need to be decided "at the topic level" are centralized, decisions which need to be taken "at partition level" are distributed.

The upper layer can take over more responsibilities like the topic-level aspects of balancing consumer groups for subscriptions etc... future work.

**Comment by ThorbenLindhauer** [comment]
Breakdown:

* There is a management topic
* Management topic is created by initial broker
  * next iteration: topic is replicated to a configurable number of followers
* Initial broker no longer creates default topic
* Client can make topic creation request with topic name and number of partitions
  * next iteration: number of replicas per partition
* Management broker triggers partition creation, for each such request waits until raft group is complete; sends success response to client
* On any type of failure or timeout (e.g. one of the partitions cannot be created), management broker responds with failure to client
  * next iteration: Management broker cleans up any resources already created
  * next iteration: Management broker retries partition creation in case of a recoverable failure or timeout

**Comment by ThorbenLindhauer** [comment]
> * On any type of failure or timeout (e.g. one of the partitions cannot be created), management broker responds with failure to client => #408
>   * next iteration: Management broker cleans up any resources already created => #409
>   * next iteration: Management broker retries partition creation in case of a recoverable failure or timeout

The concept and #409 in particular has been changed to a retry mechanism. It is not easily possible to clean things up reliably in a distributed system. Instead, we retry partition creation, if we don't observe a partition leader after a defined amount of time. From a user's perspective, this means making a request for x partitions results in a minimum of x partitions when the request returns. The case where more than x partitions are created should be unlikely, though.

**Comment by ThorbenLindhauer** [comment]
Closing this. The current feature set is enough for now.
