### ISSUE TITLE
How to implement job progress

### ISSUE THREAD

**Issue by kirgene** [zeebe-io/zeebe#2916]
I'd like to notify other services about the progress of a long-running job.
So I wonder what is a proper way to do it with Zeebe client.

**Comment by saig0** [comment]
Hi @kirgene,

one option would be to split the job into multiple tasks which are called sequentially by the workflow (e.g. `step-1 -> step-2 -> step-3`).

Why do you want to inform other services about the progress?
What should the other services do with this information?

**Comment by kirgene** [comment]
I have 2 types of services/workflows:

- the first one is responsible for managing/scaling worker VMs
- the second one is performing actual processing of tasks

The tasks are long-running and compute-intensive and are been processing in a distributed fashion.
So I need to scale (down) workers based on the progress of running tasks and other estimates.

I suspect that it should be implemented via Throwing/Catching Signals, but haven't found info on how to use them.

**Comment by saig0** [comment]
Currently, BPMN signal events are not supported. You could use messages to communicate with workflow instances (i.e. publishing a message from a client that is processed by one or more workflow instances).

Does this help you?

Feel free to share more insides about your use case. It would help to find a proper solution.

**Comment by kirgene** [comment]
I have multiple services that should be updated using this info (progress). Are messages publish in broadcast or peer-to-peer way?

**Comment by saig0** [comment]
Messages can be correlated to multi workflow instances. Please have a look at the docs: https://docs.zeebe.io/reference/message-correlation.html

Would you like to share your workflow to get a more concrete idea of what you are building?

**Comment by jwulf** [comment]
Messages are ingested only. In order to inspect a running workflow atm you have to put "spy" tasks in it, and have workers that service them. These workers can then publish whatever they need to about the state / progress of the workflow.

**Comment by Zelldon** [comment]
I assume this is solved. I will close this issue then. Feel free to reopen it if there is anything unclear.

**Comment by ysaakpr** [comment]
This is still a valid issue,
Uber cadance has similar feature by heart beat


@saig0 many time splitting a job to minute workflow tasks is heavy. For example, i have a task which does a database scanning for a specific value. I know the total number of records in database by a count(*) query.  Now is there a way to publish the task progress saying it completed this much percentage of the total number. of records back to the service.

One option is multi-instance tasks to do that, but which actually adds more complexity for the tasks, simple progress tracking and heartbeat feature would be ideal in this case.

I feel this is still a valid issue, though there are alternative to achieve the same, for a qualified workflow system, this is a good feature.

**Comment by saig0** [comment]
I think it depends on how you want to track the progress of the worker. 

If you want to track the progress in the workflow instance itself then one simple option could be a variable that is updated by the worker. The worker sets/updates a variable (e.g. `progress`) in the scope of the current job using the `SetVariablesCommand` of the client.
