### ISSUE TITLE
zeebe-operate configuration customization #2882

### ISSUE THREAD

**Issue by vpathare** [zeebe-io/zeebe#2918]
Continue to issue: #2882

I tried below suggestion but it doesn't work as expected. It doesn't look at my new configuration folder.

I renamed config folder to new-name and changed all ports in config_new/application.yml
call **./bin/operate CLASSPATH_PREFIX=<abs path>/config_new/**
my new ports are not considered.
operate still connect to port localhost:9200 & localhost:26500

Regards,
Vaibhav

**Comment by vpathare** [comment]
I am using operate version distributed with zeebe-0.18.0

**Comment by Zelldon** [comment]
I think this is quite outdated. Please use the latest Zeebe version 0.23.2. I will close this issue now.
