### ISSUE TITLE
Add a zbctl shortcut for the insecure option

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2923]
**Is your feature request related to a problem? Please describe.**
I don't want to type `--insecure` for using zbctl

**Describe the solution you'd like**

A shortcut option.

**Describe alternatives you've considered**

There are none.

**Additional context**
To use zbctl we need now either a valid certificate or the insecure option.

**Comment by npepinpe** [comment]
You mean a short option, e.g. `-i`? Another option is to support a user config file, e.g. `~/.zbctl.toml` (or any format viper supports), afaik that's supported out of the box by cobra.

**Comment by Zelldon** [comment]
> You mean a short option, e.g. -i?

Yes, but `-i` might be not so clear :man_shrugging: 

>  Another option is to support a user config file, e.g. ~/.zbctl.toml (or any format viper supports), afaik that's supported out of the box by cobra.

Don't get this one.

**Comment by npepinpe** [comment]
A lot of CLI utilities support having a config file in the user directory to specify default configuration options, so you don't have to type them over and over. In this case though, since we don't have a `--secure` option to overwrite it if you did set it as default, it wouldn't be too great :see_no_evil:

**Comment by MiguelPires** [comment]
Is this really a problem? And, if so, what is a reasonable solution? If `--insecure` is too long and `-i` is too short to be understandable, what are the alternatives other than have another config file? Changing it to `--unsafe` would save 2 characters so I don't think there's much benefit.

**Comment by npepinpe** [comment]
So one option I see that is a compromise is:

1. Add an option `--secure` which enforces using TLS.
1. Add support for a user configuration file `~/.zbctl.toml` (or YAML or JSON or whatever) where a user can specify default options that will be used on every call, e.g. `--insecure`.

Once your default is to use a plain text connection, you can also manually overwrite it when you need by adding the flag `--secure`. Just an idea.

**Comment by menski** [comment]
My two cents:
- let's don't encourage config files for zbctl for now
- if you want to implement a shorthand I would propose `-k` as used in `curl`
- I personally don't see this as a high priority issue

**Comment by Zelldon** [comment]
Agree is not high priority let us keep it simple. 
Might that no one else needs this.

**Comment by salaboy** [comment]
It will be great to follow the same approach as `kubctl` which uses a configuration file plus an environment variable. This will be needed is we want to interact against different clusters. This is already affecting the user experience of the getting started guide adding --insecure to the commands if you are running in your own cluster.

**Comment by menski** [comment]
@MiguelPires please add an environment variable to support setting insecure. We will not add a short option name. Please create a separate issue for supporting configuration files.

**Comment by MiguelPires** [comment]
For documentation purposes, the config file issue is here https://github.com/zeebe-io/zeebe/issues/3095
