### ISSUE TITLE
Chaos test with standalone Gateway

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2926]
**Description**

Currently on the chaos tests we have setup with embedded gateway, we should also have a setup with a standalone gateway.

**Comment by npepinpe** [comment]
Might be that @afirth already has some k8s templates for us there?

**Comment by Zelldon** [comment]
@menski told me that they currently use the embedded gateway and one broker.

**Comment by npepinpe** [comment]
What is the goal here? What are we trying to achieve?

**Comment by Zelldon** [comment]
This is done
