### ISSUE TITLE
Performance drop after long polling was added

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2934]
**Describe the bug**
It seems that the commit https://github.com/zeebe-io/zeebe/commit/c553760c6c3de5ddc7fafa67a583da2f2a1a5ea5 introduces a bug, where the
performance drops significantly after some minutes.

**To Reproduce**

You can reproduce it with trying out the following images and run the benchmarks.

Merge commit before the long polling was added [gcr.io/zeebe-io/zeebe:SNAPSHOT-2019-08-06-b3d6ca6f](gcr.io/zeebe-io/zeebe:SNAPSHOT-2019-08-06-b3d6ca6f)
Merge commit after the long polling was added [gcr.io/zeebe-io/zeebe:SNAPSHOT-2019-08-06-08beeece](gcr.io/zeebe-io/zeebe:SNAPSHOT-2019-08-06-08beeece)

The following images shows the broker/processing performance before the commit:

![before-long-polling](https://user-images.githubusercontent.com/2758593/62534982-96e21380-b84a-11e9-8d37-65d8d5b58692.png)

Even after 30 minutes this is stable:

![before-long-polling-30-min](https://user-images.githubusercontent.com/2758593/62534979-96e21380-b84a-11e9-91aa-bee0c19385eb.png)

After adding the long polling we see the following:

![after-long-polling](https://user-images.githubusercontent.com/2758593/62535313-5df66e80-b84b-11e9-860a-d35941a09d41.png)

As you can see after 3 min of processing the performance drops.

In the following you can see the comparison:
![comparison](https://user-images.githubusercontent.com/2758593/62535311-5df66e80-b84b-11e9-8f1e-2c2a37b39430.png)

My current assumption is that the exist check causes this, but I have to verify this.
https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/state/instance/JobState.java#L294

**Expected behavior**
No performance drop.

**Environment:**
 - OS: k8s
 - Zeebe Version: 21-SNAPSHOT

**Comment by Zelldon** [comment]
OK I'm pretty sure it is the prefix search.

I replaced it by:

```java

  final Set<DirectBuffer> jobTypes = new HashSet<>();

  private void makeJobActivatable(DirectBuffer type, long key) {
    EnsureUtil.ensureNotNullOrEmpty("type", type);

    jobTypeKey.wrapBuffer(type);

    final boolean firstActivatableJob =
        !jobTypes.contains(type); // !activatableColumnFamily.existsPrefix(jobTypeKey);

    jobKey.wrapLong(key);
    activatableColumnFamily.put(typeJobKey, DbNil.INSTANCE);
    if (firstActivatableJob) {
      jobTypes.add(type);
      notifyJobAvailable(type);
    }
  }
```

And get the following result:

![fix](https://user-images.githubusercontent.com/2758593/62542153-825a4700-b85b-11e9-9b98-35fdd86aa2ef.png)

You can test it with the following image: 
 [gcr.io/zeebe-io/zeebe:SNAPSHOT-without-prefix-search]( gcr.io/zeebe-io/zeebe:SNAPSHOT-without-prefix-search)

**Comment by npepinpe** [comment]
Unfortunately I don't think there's any other way to do prefix lookup in RocksDB without creating an iterator. But I think it's enough to simply do a seek for prefix, and check if the iterator is valid; if nothing with that prefix exists it will simply be invalid, so no need to deserialize it or anything.

I tried inlining the code (i.e. remove the call to `whileEqualPrefix` and just past the iterator creation/seek/validate) and in micro benchmarks it gives better performance (~33%) but that's still a regression I guess.

One thing I was thinking, does this need to be done synchronously? Could we defer the check/notification to a separate thread? It's fine if it's a little slow as long as it doesn't block our processor, I think.

**Comment by Zelldon** [comment]
I'm unsure why the current approach is a problem. The iterator#valid is btw checked before the prefix is validated so this should not be a problem.

I think alternative we could have a columnfamily which counts the jobs per type.
If it is zero or not exist we can notify the gateway by the nexit occurrence.

**Comment by deepthidevaki** [comment]
The first approach I had was to keep an in-memory map of jobType to count. But it seems to be very error prone, because there were cases where a job is marked "notActivatable" when it is already "notActivatable". This made it complicated and error prone to keep the count consistent. But If the use of iterator prefix is expensive, we could revisit the previous approach and maintain the count either in memory or in rocksdb.

**Comment by Zelldon** [comment]
Did a profiling with the async-profiler on the CI and this shows clearly the existsPrefix check.
[flamegraph.zip](https://github.com/zeebe-io/zeebe/files/3485102/flamegraph.zip)

**Comment by deepthidevaki** [comment]
Solutions considered:
1. Keep an in-memory count of the job types and broadcast notification when a job type becomes re-available.
2. Same as above, but keep the count in rocksdb
3. Broadcast notification for every job created.

With our current benchmark setup, all the three approaches have similar performance behavior. So we will go with the simplest solution that is broadcast for every job created. In future, if we find that it causes any issues such as flooding the network, we could consider other solutions where notify only when necessary.
