### ISSUE TITLE
Is it possible to start a worker from nodes different than Zeebe cluster?

### ISSUE THREAD

**Issue by sathyatvrcbe** [zeebe-io/zeebe#2966]
**Description**

A clear and concise description of what this issue is about.

**Comment by Zelldon** [comment]
Hey @sathyatvrcbe 

could you elaborate on that, please?
Do you read the documentation about [job workers](https://docs.zeebe.io/basics/job-workers.html)?

Greets
Chris

**Comment by jwulf** [comment]
Workers do not run in the Zeebe broker cluster. They run in other processes (on other machines, except maybe during dev) and communicate with the broker cluster via gRPC.

**Comment by Zelldon** [comment]
Closed due to inactivity
