### ISSUE TITLE
Client contact point is called brokerContactPoint

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2973]
**Describe the bug**
The contact point should not be called `brokerContactPoint`, since it does not directly communicate with the broker. 

```java
    final var zeebeClient = ZeebeClient.newClientBuilder()
                                       .brokerContactPoint("192.168.30.188:26500")
                                       .usePlaintext()
                                       .build();
```

**Expected behavior**

Might make sense to just call it contact point.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by jwulf** [comment]
In the Node client it is called `gatewayAddress`

**Comment by jwulf** [comment]
Can we synchronise on this? Because we should use the same term across clients and the cloud console.

So that the instructions are `put flap A in slot A`.

**Comment by Zelldon** [comment]
In which console you mean? I would vote for gatewayAddress, since this is exactly what it is :sweat_smile:

**Comment by menski** [comment]
related with #3544

**Comment by aivinog1** [comment]
@Zelldon Hello, I think that I understand what needs to be done, can I take that issue? I have these questions:
1. Why it is a bug? I think that this is more an API improvement (and that change shouldn't be backported)
2. Changes should still be backward compatible, right? Needs to deprecate `brokerContactPoint` method and create another `gatewayAddress` method, right?

**Comment by aivinog1** [comment]
@menski @jwulf Hello, maybe you can help me with this one: https://github.com/zeebe-io/zeebe/issues/2973#issuecomment-690102638 ? :)

**Comment by npepinpe** [comment]
Hey @aivinog1, Zelldon is away these days so he won't be particularly responsive ;)

You're correct on 1, this isn't a bug more than it's poor UX, and I wouldn't expect us to backport it. And on 2, also correct, we should deprecate `brokerContactPoint` for the next release, and remove it after 2 releases :+1:

**Comment by aivinog1** [comment]
@npepinpe Thanks :)

**Comment by Zelldon** [comment]
Yeah sorry wanted to answer over the weekend but missed it 😃

**Comment by aivinog1** [comment]
@Zelldon no problem, thanks anyway :)
