### ISSUE TITLE
Long polling activates Job even if client dies

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2979]
**Describe the bug**

If we have not enough jobs for a given type, we will collect and block the regarding poll requests.
If we close the client of the worker and start a new client/worker for the same type and then a job is created it will be assigned to the first registered worker, even if this is already dead. 

This means we will activate the job with the old worker and block this job for a given timeout.
The other/new worker is not able to activate the job until the job times out.

This is quite annoying on development if you restart your clients/workers to test them after changing some code.

**Expected behavior**

That the new worker can activate the created job without any problems.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.21.0-SNAPSHOT]
 - Configuration: [e.g. exporters etc.]

**Comment by deepthidevaki** [comment]
Until this is fixed, for testing purposes, you can also disable long polling on the client side or configure a smaller timeout.

**Comment by Zelldon** [comment]
**BTW:** We saw this problem also in a larger Process (exploding-kitten process). If you start all workers and one instance of this workflow, where it takes time to get to a specific job type it sometimes happens that the job polling was not able to fetch a specific job correctly, but it was already activated by the long polling, which means it had to time out before it was newly activated and distributed :man_shrugging:

**Comment by jwulf** [comment]
You can set a client-side timeout, which will close the gRPC connection. The responseObserver has an `onCancelHandler` that  can be used to detect this on the server. See https://github.com/zeebe-io/zeebe/issues/2987.

**Comment by Zelldon** [comment]
I think i found a solution for that. https://github.com/zeebe-io/zeebe/tree/fix-long-poll
I have to write some test tomorrow and test it in the cluster.
