### ISSUE TITLE
Broker version via API

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2981]
Ruby, Elixir, and Elm are famous for helpful error messages.

At the moment, users get cryptic error messages due to client protocol mismatches. 

For example, if you run a 0.15 client against a 0.20.0 broker and try to use the old query API, it blows up and it is not clear why. An example error message:

```
Error: 12 UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/ListWorkflows
```
Seen in the wild: https://zeebe-io.slack.com/archives/CKRHB068Z/p1565629750001000

Is there a way that we can do something like that to inform the user, or return back the broker version so that we can program the client to inform the user of the likely cause? E.g:

```
This client targets the 0.20.0 broker, and the broker is running 0.22. Check for an updated client lib version.
```

**Comment by menski** [comment]
@MiguelPires 

TODO:
- gRPC endpoint to get version of gateway
- java client supports version command
- go client support version command
- `zbctl status` contains version of gateway

Next Topic:
- extend broker info in topology to contain broker version
