### ISSUE TITLE
Resolve task failure by update payload

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#300]
AT:
* try to resolve a task incident (i.e. no retries left) by update the workflow instance payload

Use case:
* a worker marked a task as failed because expected payload is missing / invalid (input mapping was ok)
* the client provides new payload to resolve this incident
* the broker locks the failed task again with the new payload

**Comment by menski** [comment]
@saig0 do you know if this is already implement?

**Comment by saig0** [comment]
@menski , this isn't implemented yet.

**Comment by Zelldon** [comment]
we have now a new incident concept #1668
