### ISSUE TITLE
Formatting and style issues in Go client

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3004]
**Describe the bug**
The Go client has some places where it's not correctly formatted, we should correct this.
Similarly, `golint` also outputs a lot of style issues which can also be easily solved. I'm not proposing that we strictly enforce `golint`, the project itself doesn't claim to be a gold standard. However, it's a useful tool and we might want to use more often.

**To Reproduce**
https://goreportcard.com/report/github.com/zeebe-io/zeebe shows the output of several compliance tools

**Expected behavior**
Go code that follows guidelines that Go developers expect.

**Comment by slewiskelly** [comment]
I came across this project during the "Lost in Transaction?" talk at GopherCon UK yesterday, and would be extremely interesting in contributing. This sounds like a good introductory issue to work on.

**Comment by slewiskelly** [comment]
The contributing page makes mention of a CLA, but I can't seem to find it?

**Comment by Zelldon** [comment]
Hey, 

I think if you create an PR the CLA Bot will complain und you can follow the link which the bot provides. But I aggree that we should add a link somewhere.

Greets 
Chris

**Comment by slewiskelly** [comment]
Sorry, I've been on vacation but I'm ready to work on this.

If contributions are welcome, feel free to assign to me.
