### ISSUE TITLE
[Java Client] Add support to import/export Client Commands as JSON

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/zeebe#3011]
Working with the Java Client.  Is it possible to generate Commands that can be passed around as a JSON object?  Would be great to have this so commands can be created by classes that dont have access to the Client, and so they can pass the commands around in a serialized forward that will be brought into the client to execute.

**Comment by saig0** [comment]
Sorry, I don't understand this use case. If the class doesn't have access to the Zeebe client, how can it create the correct JSON which would be accepted by the client?

Please share more details about this use case.

**Comment by Zelldon** [comment]
It seems for me that you have lot of different use cases which are not fit with the current java client. Might make sense to generate the grpc classes by yourself und use them?

**Comment by Zelldon** [comment]
Due to inactivity I will close this issue. Feel free to reopen it.
