### ISSUE TITLE
Java client: add ability to recreate job from json

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/zeebe#3017]
Currently you can turn a ActivatedJob into Json, but there does not appear to be a public APi to turn it from Json back into a ActivatedJob object.

**Comment by saig0** [comment]
Why do you want to deserialize the JSON back into a ActivateJob?

Please share more details about your use case.

**Comment by Zelldon** [comment]
To complete or fail a job you only need a valid key. Why do you want to recreate the object?

**Comment by Zelldon** [comment]
Due to inactivity I will close this issue. Feel free to reopen it, if there is anything unclear or you have open questions.
