### ISSUE TITLE
Java client: ConpleteCommand does not suport easy compartmentalization if steps so they can be wrapped in if statements: Variables cannot be If

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/zeebe#3018]
Currently it appears the java client does not allow you to send Null variables or a empty hashMap. The Future just seems to stall. On top of this it's very difficult to wrap the current builder with different steps being If statements.
So I cannot seem to easily do something like "if variables hashMap is empty or null then don't do the variables step of the builder"

**Comment by saig0** [comment]
I'm sorry but I can not reproduce this behavior. The following command works with the latest version:

```
client.newCompleteCommand(jobKey).variables(Map.of()).send().join();
client.newCompleteCommand(jobKey).variables("null").send().join();
```

Please provide a minimal reproducer to analyze this issue.

**Comment by Zelldon** [comment]
Due to lack of activity I will close this issue. Feel free to reopen this.
