### ISSUE TITLE
Fix javadoc generation for JDK 11

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3045]
**Describe the bug**

Currently we do not generate javadoc for some modules (json-el, gateway-protocol-impl and protocol-assert), which prevent us to do an release on maven central.

On solution would be to just create an empty javadoc jar
https://vzurczak.wordpress.com/2014/08/01/generate-an-empty-javadoc-jar-file/ 

But this would be not the ideal solution, we should try to fix the real issues before we go this way.

### Problem with `json-el`

Scala has currently only an experimental support for Java 11 and on java doc creation we use Java 11 which gives us linkage errors.
https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

### Problem with `gateway-protocol-impl`

The protocol sources are generated and buld with Java 8 and javadoc is run with 11, which means it will not find javax as dependency.

### Problem with `protocol-assert`

I think it was similar to the javax problem.

**Comment by menski** [comment]
empty jar generation implemented with 839ebc29038d6a54c7c341e582aa91082cc37176
