### ISSUE TITLE
Rabbitmq Support for messages input and output

### ISSUE THREAD

**Issue by danshapir** [zeebe-io/zeebe#3046]
Rabbitmq is one of the most popular, strong and yet simple queuing platforms.
Zeebe currently only supports Kafka which is much more complex and doesn't fit most regular applications (or is at least an overkill). This means you can only enjoy Zeebe at it's full when using it with Kafka, while ignoring the huge eco-system around rabbit.

As most services are now moving to be event-driven, or at least even heavy, not being able to listen to event generated from rabbit really drops the usability of Zeebe.

**Comment by npepinpe** [comment]
Hi! Just a note regarding Zeebe and Kafka, Zeebe does not officially support Kafka (yet anyway), these are community projects mostly driven by me and @berndruecker to get feedback and test the waters.

That said, creating a basic RabbitMQ exporter shouldn't be too hard; I would propose following a similar approach as the [Kafka](https://github.com/zeebe-io/zeebe-kafka-exporter) or [Hazelcast](https://github.com/zeebe-io/zeebe-hazelcast-exporter/) exporters.

If you need any help there we will be happy to answer your questions on Slack or in the forums, and I know our developer advocates are always eager to hear about new community projects!

**Comment by menski** [comment]
We are closing this issue, as it's a feature which needs to be implemented as exporter. This can be done as a community project. If someone is interested to contribute this to the community we are more then happy to help and support.

**Comment by TarekMebrouk** [comment]
Hello everyone ! 

if there are still people interested in using a RabbitMQ exporter, I have just created a [repository](https://github.com/TarekMebrouk/zeebe-rabbitmq-exporter) with a simple Java code that exports all Zeebe records to a RabbitMQ queue. 

The [repository](https://github.com/TarekMebrouk/zeebe-rabbitmq-exporter) also includes instructions for local (Docker) or manual installation.
