### ISSUE TITLE
Remove ActivateJobRequestCommand#timeout(long) method from java client

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3049]
**Description**

It is always unclear if we have methods like this what the unit of the given value is. Is it in this case seconds, milliseconds or minutes? We have to write this in the docs and the user have to read the docs to fully understand the usage.

It is easier and clearer to have a method like `#timeout(Duration)`, since then the user have to do something like this `Duration.ofMillis(...)` or `Duration.ofSeconds(...)` etc. and we can calculate the value in the unit we need.

_BTW:_ We have only one #requestTimeout(Duration) method on ActivateJobsRequest

**Comment by pihme** [comment]
Method was moved/renamed to ActivateJobsCommandStep3#timeout(long) in the interim
