### ISSUE TITLE
When a message starts a workflow instance it is also correlated to a corresponding intermediate message event later

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#3050]
**Describe the bug**
Given this process which listens to the same message in the start event and the following intermediate message event:

![grafik](https://user-images.githubusercontent.com/1217596/64274407-9de06c80-cf43-11e9-9b86-659cd2dcfef2.png)

Now you publish a message, e.g.

```
zbc.publishMessage({
        correlationKey: "1",
        messageId: "1",
        name: 'Message_A',
        variables: { myCorrelationKey: "1" },
        timeToLive: 10000,
    })
```

the workflow advances one step too far, so the same message is consumed twice for the workflow instance:

![grafik](https://user-images.githubusercontent.com/1217596/64274983-db91c500-cf44-11e9-8a1a-9662efae91d4.png)

**To Reproduce**
Code is here: https://github.com/berndruecker/messaging-patterns-zeebe/tree/master/accumulation

**Expected behavior**
A message should be send to one workflow instance only once - if it starts the workflow it can't trigger the intermediate message event.

**Environment:**
 - Zeebe Version: [e.g. 0.20.0]

**Comment by berndruecker** [comment]
@falko FYI

**Comment by npepinpe** [comment]
Nice catch, and I will have a fix out soon, but out of curiosity, how does this not end up in an endless loop of starting new workflow instances in order to finish the existing ones?

**Comment by jwulf** [comment]
Hmmm... this seems like a design anti-pattern. As you point out @npepinpe, future correlated messages will also start new workflow instances. 

If you don't want your start message to be correlated to the intermediate event of the workflow instance that it starts, you would set the TTL to -1, no?

But if you have the same message for an intermediate event and a start event, then semantically you are saying: "Start a new workflow _and_ correlate with any running workflows".

**Comment by jwulf** [comment]
If you have a `correlationKey` (_should be `correlationValue`, just sayin'_) on a message then you could say that it should not trigger start events, but _only_ be correlated with running workflow instances. 

That would be a design choice that would mean when coding Zeebe systems if you want both behaviours you have to send two messages that are identical except for the presence of a `correlationKey`.

But at the moment a single message does both, and I have workflows that rely on this behaviour - so probably others do too.

**Comment by berndruecker** [comment]
In the customer scenario an idempotency key was used, that's why we did not end up in an endless loop.
I do see the use case for messages arriving where you say "correlate to some workflow instance, but if non is there, start a new one" - which works nicely with the current implementation.

**Comment by jwulf** [comment]
I understood the idempotency key to mean a second instance of the same message would be ignored - does it affect correlation with start / intermediate events?
