### ISSUE TITLE
ActivatedJob Created Date?

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/zeebe#3053]
A ActivatedJob does not seem to have a original job creation date?

Is this correct?, if so, what is the reasoning on this?

**Comment by saig0** [comment]
Yes, the `ActivatedJob` doesn't have the creating time of the job. But it has the deadline of the job (i.e. the time how long the job is activated).

What do you want to achieve?
Why do you need the creation time of the job?
Are there any alternatives you can use?

**Comment by StephenOTT** [comment]
In operational scenarios is important to understand what the original job creation time was.  The deadline may be a calculation and deadlines may change. But a original creation is tells you how long that job existed for, not just its deadline.  There may not be a "deadline" from a ops perspective, but you want to understand how old the job is.  This would be basic bpm stats

**Comment by saig0** [comment]
This kind of information can be extracted using an exporter - like this is done for Operate. The `ActivatedJob` object just holds the data you need to execute the work item.

**Comment by StephenOTT** [comment]
Yes understanding that "everything" can come from the exporter; do you see the value in understanding original job creation time from the perspective of the job worker?

**Comment by saig0** [comment]
Nope :sweat_smile: Please elaborate on the use cases you have in mind.

**Comment by Zelldon** [comment]
Due to inactivity I will close this issue. Feel free to reopen it.
