### ISSUE TITLE
Clean up/simplify/improve Elasticsearch exporter integration tests

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3055]
**Description**

After migrating to [TestContainers](https://testcontainers.org) for integration testing, we should spend some time cleaning up/simplifying/improving the ES integration tests.

1. Remove SSL testing: I don't believe the current test brings any value. We simply change the URL from `http://localhost` to `https://localhost`, but still test that that works...? We're not testing our code at all, just that changing the scheme works?
1. Remove abstractions: we have an abstract test class, a test client, an abstraction over the integration node (which was useful to migrate from forked jvm to docker container, but can be removed now), etc. We should look into collapsing those.
1. Make tests deterministic: I don't think I need to convince anyone here :sweat_smile: 

Related to #2140

**Comment by Zelldon** [comment]
is this done?

**Comment by npepinpe** [comment]
Not even close a little bit :)

**Comment by npepinpe** [comment]
This issue is superseded by #4571 #4572
