### ISSUE TITLE
Atomix: Can not apply index error on 0.20.0 version

### ISSUE THREAD

**Issue by bhowmikdebarshi** [zeebe-io/zeebe#3073]
Hello

We have a Zeebe cluster with 3 nodes ( installed as docker image version - 0.20.0 on three EC2 instances ) . 
Partition count - 3
Replication Factor -3 
Embedded Gateway 
Java Clients 
AWS Elastic Search Exporter

We are seeing following error on one node - 

> 00:24:01.519 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368802
00:24:01.523 [] [raft-server-raft-atomix-partition-2] WARN io.atomix.protocols.raft.roles.LeaderRole - RaftServer{raft-atomix-partition-2}{role=LEADER} - An unexpected error occurred:
{}
java.lang.IndexOutOfBoundsException: Cannot apply index 25368802
at io.atomix.protocols.raft.impl.RaftServiceManager.applyIndex(RaftServiceManager.java:398) ~[atomix-raft-3.2.0-alpha4.jar:?]
at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$enqueueIndex$9(RaftServiceManager.java:360) ~[atomix-raft-3.2.0-alpha4.jar:?]
at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha4.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

After few of this error, it keeps coming indefinitely until we restart that node - 

> 00:24:05.802 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368809
00:24:05.823 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368810
00:24:05.829 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368811
00:24:05.839 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368812
00:24:05.845 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368813
00:24:05.851 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368814
00:24:05.858 [] [raft-server-raft-atomix-partition-2] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-2} - Cannot apply index 25368815

After restarting, it works fine for 1 or 2 days, and suddenly starts popping this error and keeps coming up until restart the node. 

I haven't seen this issue in version 0.15.0. 

I don't see this issue had been reported earlier, but it's so obvious in my case (after upgrading to 0.20.0) I've started feeling that something messed up in the configuration. But unable to find out what. 
Any advise on the reason for this error would be really appreciable.

**Comment by jwulf** [comment]
@bhowmikdebarshi Is it always on the same node?

**Comment by bhowmikdebarshi** [comment]
No, it can be seen randomly on any node.

**Comment by jwulf** [comment]
Can you please try it with the 0.21-alpha3 release.

**Comment by bhowmikdebarshi** [comment]
I have upgraded broker to 0.21-alpha3 release. Haven't seen any issue after one day. Will keep monitoring for few more days and keep updating here.

**Comment by utkarshdeep** [comment]
@bhowmikdebarshi using the `0.21-alpha3` are you able to run the `zeebe cluster` for days without any issue?

**Comment by bhowmikdebarshi** [comment]
@utkarshdeep  it looks much better with  `0.21-alpha3`. Its running for 1 week and haven't had to restart any node. ( Though dint do any load test and only 30-40 request per hour ). 
I also had no exporter configured with this deployment. I'm not sure if enabling elasticsearch exporter reintroduce the issue. 

Though I haven't had to restart the cluster, but I see following errors in last few days in logs - 

`io.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (RESOURCE_EXHAUSTED): Reached maximum capacity of requests handled` 

- There were almost no load but still this error appeared almost whole day on Sept 28th on Node 2. 

`io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 16030100c7010000c30303db8a6ceb826edf2c61231c197f`  

`01:52:14.658 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-atomix-partition-1} - AppendRequest{term=1, leader=1, prevLogIndex=506481, prevLogTerm=1, entries=0, commitIndex=506482} to 0 failed: java.util.concurrent.TimeoutException: Request type raft-atomix-partition-1-append timed out in 5000 milliseconds`


Following Warnings - 

`io.zeebe.gateway - Failed to activate jobs for type fetchDocumentMetadata from partition 2` 

-  this warning appeared on node 2 log almost whole day of Sept 28th. ( Somehow linked with RESOURCE_EXHAUSTED error ? )

`io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@503a625d` 

Here is the Cluster status - 

```
root@ip-10-35-230-118:/usr/local/zeebe/bin# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 10.35.231.235:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Leader
  Broker 1 - 10.35.234.86:26501
    Partition 1 : Leader
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 2 - 10.35.230.118:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
```

I see node 2 isn't leader of any of the partitions and Node 1 is leader of 2 partitions  ( Not sure why ).

**Comment by bhowmikdebarshi** [comment]
Thanks @npepinpe  for quick response.

Makes sense for leaders. Agree that code processing is much critical than load balancing. 

For `RESOURCE_EXHAUSTED` issue, not sure if I need to worry. We have only 7-8 workers ( Java clients) for these three brokers and only 30-40 workflow-instances per hour had created. 
There are no "timer start" events, long running workflows or long polling. 

As of now we have only two workflows. One is having 8 sequential service tasks only and another one has 8 sequential service tasks along with a message event. So processing would have been pretty simple. 

I'm more worried about two facts -  
  - this error has appeared on only one node ( if it's related to processing, shouldn't it come on all nodes? ) and appeared whole day ( took whole day to recover? )
  - at the same time we had this warning `io.zeebe.gateway - Failed to activate jobs for type fetchDocumentMetadata from partition 2`  - probably this error has link with `RESOURCE_EXHAUSTED` ? Either this is cause or result of `RESOURCE_EXHAUSTED` error

**Comment by npepinpe** [comment]
Resource exhausted will cause it to fail to activate jobs, so that makes sense. As for the error appearing only on one node, that depends on the workload, I guess. Backpressure is per-partition, so if one node is leader for most it makes sense it would generating these errors and not the other nodes.

It's possible our rate limiting is a little to pessimistic, it's the first iteration we have with it so it might need some tuning.

You can disable backpressure entirely by adding the following to your config:

```toml
[backpressure]
enabled = false
```

I wouldn't recommend it however; in general `RESOURCE_EXHAUSTED` is not a terrible error as you can simply retry. I hope in the future the clients will have built-in strategies to deal with this.

**Comment by bhowmikdebarshi** [comment]
Thanks. 

Have restarted Zeebe with Elasticsearch Exporter enabled. Will keep an eye if we see the atomix error `Can not apply index`. If no, we can close this ticket. 

Btw, the current topology is as followed after restarting of all nodes -   

```
root@ip-10-35-230-135:/usr/local/zeebe/bin# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 10.35.230.135:26501
    Partition 1 : Leader
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 1 - 10.35.231.32:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - 10.35.234.66:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower

```

**Comment by jwulf** [comment]
> I hope in the future the clients will have built-in strategies to deal with this.

The Node client has such a built-in retry strategy. See: https://github.com/creditsenseau/zeebe-client-node-js#client-side-grpc-retry-in-zbclient

At the moment it is enabled only for network-related errors, but enabling it for this would not be hard.

**Comment by Zelldon** [comment]
I think this is out dated and can be closed. Feel free to reopen if you see this issue again
