### ISSUE TITLE
Are there some plans to support Elasticsearch 7.x ?

### ISSUE THREAD

**Issue by imsuperman0920** [zeebe-io/zeebe#3078]
Elasticsearch 7.2 is used in my project, the zeebe broker 0.20 running with it is perfect，but when the operate-1.0.0 started I got a exception as below:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'startupBean': Invocation of init method failed; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=illegal_argument_exception, reason=Setting index.mapper.dynamic was removed after version 6.0.0]]

How to fix this ?
Do you some plans to support ES 7.X ?

**Comment by tvvignesh** [comment]
Hi. I see the upgrade to 6.8.4 here: https://github.com/zeebe-io/zeebe/pull/3248

Would be great if we can have 7.x support. Lots of enhancements and fixes have been made - https://www.elastic.co/blog/elastic-stack-7-4-0-released

Thanks.
