### ISSUE TITLE
Cannot deploy workflow to broker started in clustered mode Same as [#1766]

### ISSUE THREAD

**Issue by vpathare** [zeebe-io/zeebe#3083]
**Description**
The cluster for zeebe is not working well for me. I am getting "Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded" error all the time. This exact same issue "https://github.com/zeebe-io/zeebe/issues/1766" and solution not working for me.

***Environment:*** Linux 2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
*** version ****: zeebe-broker-0.20.0
***Configuration:*** 
*Cluster size:* 3
*Partitions count:* 3
*Replication factor:* 2

Result when request status, leader is not printed so not sure if leader is selected or not.
`./bin/zbctl status`
`Result
Cluster size: 3
Partitions count: 3
Replication factor: 2
Brokers:
  Broker 0 - localhost:26501
  Broker 1 - localhost:26501
  Broker 2 - localhost:26501
`

**Comment by vpathare** [comment]
***Full configuration:*** Using default configuration but setting environment variables
as below:
*Node0:*
ZEEBE_DIRECTORIES=<Path for data>
ZEEBE_NODE_ID=0
tried with with and without below env variable:
ZEEBE_CONTACT_POINTS="node0:26502"

*Node1:*
ZEEBE_DIRECTORIES=/cis/data/zeebe/data
ZEEBE_NODE_ID=1
ZEEBE_CONTACT_POINTS="node0:26502"

*Node2:*
ZEEBE_DIRECTORIES=/cis/data/zeebe/data
ZEEBE_NODE_ID=2
ZEEBE_CONTACT_POINTS="node0:26502"

# Zeebe broker configuration file

# Overview -------------------------------------------

# This file contains a complete list of available configuration options.

# Default values:
#
# When the default value is used for a configuration option, the option is
# commented out. You can learn the default value from this file

# Conventions:
#
# Byte sizes
# For buffers and others must be specified as strings and follow the following
# format: "10U" where U (unit) must be replaced with K = Kilobytes, M = Megabytes or G = Gigabytes.
# If unit is omitted then the default unit is simply bytes.
# Example:
# sendBufferSize = "16M" (creates a buffer of 16 Megabytes)
#
# Time units
# Timeouts, intervals, and the likes, must be specified as strings and follow the following
# format: "VU", where:
#   - V is a numerical value (e.g. 1, 1.2, 3.56, etc.)
#   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
#
# Paths:
# Relative paths are resolved relative to the installation directory of the
# broker.

# ----------------------------------------------------


[gateway]
# Enable the embedded gateway to start on broker startup.
# This setting can also be overridden using the environment variable ZEEBE_EMBED_GATEWAY.
# enable = true

[gateway.network]
# Sets the host the embedded gateway binds to.
# This setting can be specified using the following precedence:
# 1. setting the environment variable ZEEBE_GATEWAY_HOST
# 2. setting gateway.network.host property in this file
# 3. setting the environment variable ZEEBE__HOST
# 4. setting network.host property in this file
# host = "0.0.0.0"

# Sets the port the embedded gateway binds to.
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_PORT.
# port = 26500

[gateway.cluster]
# Sets the broker the gateway should initial contact.
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CONTACT_POINT.
contactPoint = "127.0.0.1:26501"

# Sets size of the transport buffer to send and received messages between gateway and broker cluster.
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_TRANSPORT_BUFFER.
# transportBuffer = "128M"

# Sets the timeout of requests send to the broker cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_REQUEST_TIMEOUT.
# requestTimeout = "15s"

[gateway.threads]
# Sets the number of threads the gateway will use to communicate with the broker cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_MANAGEMENT_THREADS.
# managementThreads = 1

[gateway.monitoring]
# Enables the metrics collection in the gateway
# enabled = false

[network]                                                                                                                                                                                                                                                                                                                                                       [153/1963]

# This section contains the network configuration. Particularly, it allows to
# configure the hosts and ports the broker should bind to. The broker exposes two sockets:
# 1. command: the socket which is used for gateway-to-broker communication
# 2. internal: the socket which is used for broker-to-broker communication
# 3. monitoring: the socket which is used to monitor the broker

# Controls the default host the broker should bind to. Can be overwritten on a
# per binding basis for client, management and replication
#
# This setting can also be overridden using the environment variable ZEEBE_HOST.
# host = "0.0.0.0"

# If a port offset is set it will be added to all ports specified in the config
# or the default values. This is a shortcut to not always specifying every port.
#
# The offset will be added to the second last position of the port, as Zeebe
# requires multiple ports. As example a portOffset of 5 will increment all ports
# by 50, i.e. 26500 will become 26550 and so on.
#
# This setting can also be overridden using the environment variable ZEEBE_PORT_OFFSET.
# portOffset = 0

[network.commandApi]
# Overrides the host used for gateway-to-broker communication
host = "localhost"

# Sets the port used for gateway-to-broker communication
port = 26501

# Sets the size of the buffer used for buffering outgoing messages
# sendBufferSize = "16M"

[network.internalApi]
# Overrides the host used for internal broker-to-broker communication
# host = "localhost"

# Sets the port used for internal broker-to-broker communication
# port = 26502

[network.monitoringApi]
# Overrides the host used for exposing monitoring information
# host = "localhost"

# Sets the port used for exposing monitoring information
# port = 9600


[data]

# This section allows to configure Zeebe's data storage. Data is stored in
# "partition folders". A partition folder has the following structure:
#
# partition-0                       (root partition folder)
# ├── partition.json                (metadata about the partition)
# ├── segments                      (the actual data as segment files)
# │   ├── 00.data
# │   └── 01.data
# └── state                             (stream processor state and snapshots)
#     └── stream-processor
#                 ├── runtime
#                 └── snapshots

# Specify a list of directories in which data is stored. Using multiple
# directories makes sense in case the machine which is running Zeebe has
# multiple disks which are used in a JBOD (just a bunch of disks) manner. This
# allows to get greater throughput in combination with a higher io thread count
# since writes to different disks can potentially be done in parallel.
#
# This setting can also be overridden using the environment variable ZEEBE_DIRECTORIES.
# directories = [ "data" ]

# The size of data log segment files.
# logSegmentSize = "512M"

# How often we take snapshots of streams (time unit)
# snapshotPeriod = "15m"
# The maximum number of snapshots kept (must be a positive integer). When this
# limit is passed the oldest snapshot is deleted.
# maxSnapshots = "3"
#
# How often follower partitions will check for new snapshots to replicate from
# the leader partitions. Snapshot replication enables faster failover by
# reducing how many log entries must be reprocessed in case of leader change.
# snapshotReplicationPeriod = "5m"


[cluster]

# This section contains all cluster related configurations, to setup an zeebe cluster

# Specifies the unique id of this broker node in a cluster.
# The id should be between 0 and number of nodes in the cluster (exclusive).
#
# This setting can also be overridden using the environment variable ZEEBE_NODE_ID.
# nodeId = 1

# Controls the number of partitions, which should exist in the cluster.
#
# This can also be overridden using the environment variable ZEEBE_PARTITIONS_COUNT.
partitionsCount = 3

# Controls the replication factor, which defines the count of replicas per partition.
# The replication factor cannot be greater than the number of nodes in the cluster.
#
# This can also be overridden using the environment variable ZEEBE_REPLICATION_FACTOR.
replicationFactor = 2

# Specifies the zeebe cluster size. This value is used to determine which broker
# is responsible for which partition.
#
# This can also be overridden using the environment variable ZEEBE_CLUSTER_SIZE.
clusterSize = 3

# Allows to specify a list of known other nodes to connect to on startup
# The contact points of the internal network configuration must be specified.
# The format is [HOST:PORT]
# Example:
# initialContactPoints = [ "192.168.1.22:26502", "192.168.1.32:26502" ]
#
# This setting can also be overridden using the environment variable ZEEBE_CONTACT_POINTS
# specifying a comma-separated list of contact points.
#
# To guarantee the cluster can survive network partitions, all nodes must be specified
# as initial contact points.
#
# Default is empty list:
initialContactPoints = [ "tcilnjdcisap07:26502", "tcilnydcisap07:26502", "tcilnjdcisap08:26502" ]

# Allows to specify a name for the cluster
# This setting can also be overridden using the environment variable ZEEBE_CLUSTER_NAME
# Example:
# clusterName = "zeebe-cluster"

[threads]

# Controls the number of non-blocking CPU threads to be used. WARNING: You
# should never specify a value that is larger than the number of physical cores
# available. Good practice is to leave 1-2 cores for ioThreads and the operating
# system (it has to run somewhere). For example, when running Zeebe on a machine
# which has 4 cores, a good value would be 2.
#
# The default value is 2.
#cpuThreadCount = 2

# Controls the number of io threads to be used. These threads are used for
# workloads that write data to disk. While writing, these threads are blocked
# which means that they yield the CPU.
#
# The default value is 2.
#ioThreadCount = 2
# Configure exporters below; note that configuration parsing conventions do not apply to exporter
# arguments, which will be parsed as normal TOML.
#
# Each exporter should be configured following this template:
#
# id:
#   property should be unique in this configuration file, as it will server as the exporter
#   ID for loading/unloading.
# jarPath:
#   path to the JAR file containing the exporter class. JARs are only loaded once, so you can define
#   two exporters that point to the same JAR, with the same class or a different one, and use args
#   to parametrize its instantiation.
# className:
#   entry point of the exporter, a class which *must* extend the io.zeebe.exporter.Exporter
#   interface.
#
# A nested table as [exporters.args] will allow you to inject arbitrary arguments into your
# class through the use of annotations.
#
# Enable the following debug exporter to log the exported records to console
# This exporter can also be enabled using the environment variable ZEEBE_DEBUG, the pretty print
# option will be enabled if the variable is set to "pretty".
#
# [[exporters]]
# id = "debug-log"
# className = "io.zeebe.broker.exporter.debug.DebugLogExporter"
# [exporters.args]
#   logLevel = "debug"
#   prettyPrint = false
#
# Enable the following debug exporter to start a http server to inspect the exported records
#
# [[exporters]]
# id = "debug-http"
# className = "io.zeebe.broker.exporter.debug.DebugHttpExporter"
# [exporters.args]
#   port = 8000
#   limit = 1024
#
#
# An example configuration for the elasticsearch exporter:
#
#[[exporters]]
#id = "elasticsearch"
#className = "io.zeebe.exporter.ElasticsearchExporter"
#
#  [exporters.args]
#  url = "http://localhost:9200"
#
#  [exporters.args.bulk]
#  delay = 5
#  size = 1_000
#
#  [exporters.args.authentication]
#  username = elastic
#  password = changeme
#
#  [exporters.args.index]
#  prefix = "zeebe-record"
#  createTemplate = true
#
#  command = false
#  event = true
#  rejection = false
#
#  deployment = true
#  error = true
#  incident = true
#  job = true
#  jobBatch = false
#  message = false
#  messageSubscription = false
#  variable = true
#  variableDocument = false
#  workflowInstance = true
#  workflowInstanceCreation = false
#  workflowInstanceSubscription = false

**Comment by vpathare** [comment]
Can some please help me on this quicker?

**Comment by Zelldon** [comment]
Hey @vpathare thanks for trying Zeebe.

What is your reason behind using a replication factor of 2 ?
How large is your deployment?
Could you please try the latest alpha?

Greets
Chris

**Comment by vpathare** [comment]
I am trying to use machines in diff data-centers so my partition to be replicated across 2 machines at-least.

I can try latest alpha if 0.20.0 is not working well. Please suggest if 0.20.0 has issue.

**Comment by vpathare** [comment]
Also I am seeing warning as "05:22:24.915 [] [netty-messaging-event-epoll-client-2] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Received invalid handshake, closing connection"

**Comment by Zelldon** [comment]
> I am trying to use machines in diff data-centers so my partition to be replicated across 2 machines at-least.

You should be aware that this not really make sense, since we using RAFT as consensus protocol (https://raft.github.io/). Having an number less then three or even is not a good idea, since the quorum is calculated like this `quorum = floor(replicationFactor / 2) + 1. This means if you have a replication factor of 2 your quroum is as well 2, so if one node dies your can't make any progress any more (because you have no quroum).

> I can try latest alpha if 0.20.0 is not working well. Please suggest if 0.20.0 has issue.

It depends I mean sure we fixed some issues in the meantime. That is the reason why I asked about your deployment size.

Can you share the complete logs of the brokers? Do you see any exceptions?

**Comment by vpathare** [comment]
Please find logs below:

06:21:33.188 [service-controller] [0.0.0.0:26501-zb-actors-1] INFO  io.atomix.core.Atomix - 3.2.0-alpha4 (revision bfdbdd built on 2019-07-16 09:20:45)

06:21:33.277 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:26502
06:21:33.281 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
06:21:33.306 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:26502
06:21:33.309 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
06:21:33.311 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member activated: Member{id=0, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}}
06:21:33.323 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
06:21:33.323 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
06:21:33.324 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
06:21:33.330 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
06:21:33.345 [] [atomix-0] INFO  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Started
06:21:33.348 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 0 received event ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=0, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}}, time=1568715693318} with BrokerInfo{nodeId=0, partitionsCount=1, $
lusterSize=1, replicationFactor=1, partitionRoles={}}
06:21:33.349 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:26501-zb-actors-1] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=0, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}}, time=1$
68715693318} with BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}}
06:21:33.354 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:26501-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:26501' on transport 'gateway-broker-client'
06:21:33.373 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.primitive.partition.GroupMember already registered as 502. Skipping 553.
06:21:33.374 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.cluster.MemberId already registered as 503. Skipping 554.
06:21:33.375 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.primitive.partition.MemberGroupId already registered as 504. Skipping 555.
06:21:33.375 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.primitive.partition.PartitionId already registered as 505. Skipping 556.
06:21:33.391 [] [atomix-0] INFO  io.atomix.primitive.partition.impl.HashBasedPrimaryElectionService - Started
06:21:33.432 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class io.atomix.protocols.raft.ReadConsistency already registered as 535. Skipping 550.
06:21:33.432 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.ArrayList already registered as 27. Skipping 551.
06:21:33.432 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.LinkedList already registered as 28. Skipping 552.
06:21:33.432 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.Collections$EmptyList already registered as 41. Skipping 553.
06:21:33.433 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.HashSet already registered as 29. Skipping 554.
06:21:33.438 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: class java.util.ArrayList already registered as 27. Skipping 612.
06:21:33.438 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: class java.util.HashSet already registered as 29. Skipping 613.
06:21:33.442 [] [atomix-0] INFO  io.atomix.protocols.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=system}
06:21:33.503 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Loaded disk segment: 1 (system-partition-1-1.log)
06:21:33.503 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Found segment: 1 (system-partition-1-1.log)
06:21:33.585 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to FOLLOWER
06:21:33.593 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.cluster.impl.RaftClusterContext - RaftServer{system-partition-1} - Attempting to join via 2
06:21:33.597 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.cluster.impl.RaftClusterContext - RaftServer{system-partition-1} - Failed to join 2
06:21:33.598 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.cluster.impl.RaftClusterContext - RaftServer{system-partition-1} - Attempting to join via 1
06:21:33.598 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.cluster.impl.RaftClusterContext - RaftServer{system-partition-1} - Failed to join 1
06:21:33.598 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.cluster.impl.RaftClusterContext - RaftServer{system-partition-1} - Failed to join cluster, retrying...
06:21:34.697 [] [netty-messaging-event-epoll-client-0] DEBUG io.atomix.cluster.messaging.impl.NettyMessagingService - Activating server protocol version V2 for connection to /<IP-address>:54718
06:21:34.716 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member added Member{id=1, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQABAAAAAwAAAAMAAAACAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}}
06:21:34.717 [] [atomix-cluster-events] ERROR io.zeebe.broker.clustering - Static configuration of node 1 differs from local node 0
06:21:34.718 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 0 received event ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=1, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQABAAAAAwAAAAMAAAACAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}, version=3.2.0-alpha4, timestamp=1568714741647, state=ALIVE, incarn$
tionNumber=1568715488878}, time=1568715694717} with null
06:21:34.718 [] [atomix-cluster-events] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - 0 - Bootstrapping from member Member{id=1, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQABAAAAAwAAAAMAAAACAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}, version=3.2.0-alpha4, timestamp=1568714741647, state=ALIVE, inc$
rnationNumber=1568715488878}
06:21:34.718 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:26501-zb-actors-1] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=1, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAAAQABAAAAAwAAAAMAAAACAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAA==}, version$
3.2.0-alpha4, timestamp=1568714741647, state=ALIVE, incarnationNumber=1568715488878}, time=1568715694717} with BrokerInfo{nodeId=1, partitionsCount=3, clusterSize=3, replicationFactor=2, partitionRoles={}}
06:21:34.723 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:26501-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '1' with address '0.0.0.0:26501' on transport 'gateway-broker-client'
06:21:36.667 [] [netty-messaging-event-epoll-client-1] DEBUG io.atomix.cluster.messaging.impl.NettyMessagingService - Activating server protocol version V2 for connection to /<IP-ADDRESS>:54730
06:21:37.930 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Heartbeat timed out in PT4.34S
06:21:37.934 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling members [DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}]
06:21:37.934 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for next term 7
06:21:37.936 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for next term 7
06:21:37.938 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - java.net.ConnectException
06:21:37.938 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=6, candidate=0, lastLogIndex=0, lastLogTerm=0}: candidate's log is up-to-date
06:21:37.940 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Received accepted poll from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}
06:21:37.940 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to CANDIDATE
06:21:37.942 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Starting election
06:21:37.947 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Set term 7
06:21:37.950 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Voted for 0
06:21:37.951 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting votes for term 7
06:21:37.952 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for term 7
06:21:37.954 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for term 7
06:21:37.957 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.net.ConnectException
06:21:37.958 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Received rejected vote from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}
06:21:37.959 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to FOLLOWER

**Comment by vpathare** [comment]
I tried using latest alpha as well and same issue. I am curious about ports "***/<IP>:54730***"
06:21:36.667 [] [netty-messaging-event-epoll-client-1] DEBUG io.atomix.cluster.messaging.impl.NettyMessagingService - Activating server protocol version V2 for connection to ***/<IP>:54730***
06:21:37.930 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Heartbeat timed out in PT4.34S
06:21:37.934 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling members [DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}]
06:21:37.934 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for next term 7
06:21:37.936 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Polling DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z} for next term 7
06:21:37.938 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - java.net.ConnectException
06:21:37.938 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=6, candidate=0, lastLogIndex=0, lastLogTerm=0}: candidate's log is up-to-date
06:21:37.940 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - Received accepted poll from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:16:17.953Z}
06:21:37.940 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to CANDIDATE

**Comment by vpathare** [comment]
Now tried with below configuration as per documentation:
"nodeId": 0,
    "partitionsCount": 5,
    "replicationFactor": 3,
    "clusterSize": 5,
    "clusterName": "zeebe-cluster-topo"

Still election of leader is failing all the time:

07:30:31.407 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to CANDIDATE
07:30:31.407 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Starting election
07:30:31.411 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Set term 525
07:30:31.412 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Voted for 0
07:30:31.412 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting votes for term 525
07:30:31.412 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:42:28.295Z} for term 525
07:30:31.412 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:42:28.295Z} for term 525
07:30:31.413 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Received rejected vote from DefaultRaftMember{id=2, type=ACTIVE, updated=2019-09-17T10:42:28.295Z}
07:30:31.413 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Received rejected vote from DefaultRaftMember{id=1, type=ACTIVE, updated=2019-09-17T10:42:28.295Z}
07:30:31.413 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to FOLLOWER
07:30:31.413 [] [raft-server-system-partition-1] DEBUG io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - Cancelling election

**Comment by jwulf** [comment]
@vpathare are you running these nodes in different data centers now, or testing this locally first?

We do not currently recommend or support cross-DC replication because the latency will kill perfarmonce, since the nodes need to commit each event across the cluster before processing it.

**Comment by Zelldon** [comment]
Hey @vpathare ,

one thing I think is interesting I found in your logs is:
```
06:21:34.717 [] [atomix-cluster-events] ERROR io.zeebe.broker.clustering - Static configuration of node 1 differs from local node 0
```

Do you have different configurations for your nodes ? Please make sure that clustersize, replicationFactor and partitionCount have always the same values. Furthermore the node id's need to start from 0 to clusterSize - 1. Could you please verify that.

Greets
Chris

**Comment by vpathare** [comment]
I tried to set below environment variables and it started working. but doesn't explain me the issue yet.

ZEEBE_HOST=host-name
ZEEBE_CONTACT_POINTS=<with all hosts>
