### ISSUE TITLE
zbctl --help add ENV Variables names

### ISSUE THREAD

**Issue by salaboy** [zeebe-io/zeebe#3087]
**Description**

Right now `zbctl` is not expressing consistently the ENVIROMENT variables that it is consuming expressed in the FLAGs section. For example:

```
 --address string        Specify a contact point address
```
Doesn't specify what is the name of the ENV Variable that can be exported to provide that flag. 
Also notice the difference in terms between "address" and "contact point"
This needs to be unified in all clients and tools.

**Comment by salaboy** [comment]
Also.. address and port should be split so the port can be defaulted

**Comment by menski** [comment]
First iteration: all help options should contain the environment variables, we will not address splitting address port for now. please create a new issue
