### ISSUE TITLE
Broker get OutOfMemory after a while

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3090]
**Describe the bug**

Currently it seems that the broker get out of memory exceptions after while.
This causes leader changes and in the end to a dead cluster. I have seen this also in the Camunda Cloud, that the cluster is no longer responsive.

![first](https://user-images.githubusercontent.com/2758593/65322441-22b7c100-dba7-11e9-9445-7d3811494f09.png)

After the first node dies it never comes back, but we can make progress since we have replication factor of 3.

![screenshot2019-09-2012:03:22](https://user-images.githubusercontent.com/2758593/65321782-627da900-dba5-11e9-95b8-cc495864dfd2.png)

After the second gets OOM Exception the cluster is dead (since no quorum).

![screenshot2019-09-2012:08:13](https://user-images.githubusercontent.com/2758593/65321683-24808500-dba5-11e9-86b7-c9fe4920d485.png)
![second](https://user-images.githubusercontent.com/2758593/65322446-277c7500-dba7-11e9-89c5-d6e6cfec3635.png)
![third](https://user-images.githubusercontent.com/2758593/65322447-277c7500-dba7-11e9-855e-68d997ad3eed.png)

**To Reproduce**

I started a cluster for 3 nodes, replication factor 3 and one partition.

I wanted to test backpressure and run 3 starter, which start 75 workflow instances per second. Furthermore I had 6 workers running. As first it seemed everything good, since the throughput was 
kept up and the latency very low, but after a while the broker just dies.

**Expected behavior**
The load is kept and the cluster is healthy.

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source) ~[?:?]
	at java.io.ByteArrayOutputStream.grow(Unknown Source) ~[?:?]
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source) ~[?:?]
	at java.io.ByteArrayOutputStream.write(Unknown Source) ~[?:?]
	at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:249) ~[elasticsearch-rest-high-level-client-6.8.3.jar:6.8.3]
	at org.elasticsearch.client.RestHighLevelClient$$Lambda$1189/0x00000008008f6840.apply(Unknown Source) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1760) ~[elasticsearch-rest-high-level-client-6.8.3.jar:6.8.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.3.jar:6.8.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.3.jar:6.8.3]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:472) ~[elasticsearch-rest-high-level-client-6.8.3.jar:6.8.3]
	at io.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:104) ~[zeebe-elasticsearch-exporter-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:87) ~[zeebe-elasticsearch-exporter-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:93) ~[zeebe-elasticsearch-exporter-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flushAndReschedule(ElasticsearchExporter.java:84) ~[zeebe-elasticsearch-exporter-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter$$Lambda$1007/0x00000008007a7840.run(Unknown Source) ~[?:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
```

</p>
</details>

Might be related to https://github.com/zeebe-io/zeebe/issues/2991
**Environment:**
 - OS: k8s
 - Zeebe Version: [0.21.0-alpha3]
 - Configuration: [elastic exporter]

**Comment by kunalkrishna1111** [comment]
Can we get this prioritized, it seems to a serious issue.

**Comment by deepthidevaki** [comment]
Java memory management in docker used to have some issues before. It should be fixed in later versions though. Did you observe similar behavior when running without docker?

**Comment by Zelldon** [comment]
>  docker used to have some issues before. It should be fixed in later versions though.

Later version of zeebe or docker? :sweat_smile: 

> Did you observe similar behavior when running without docker?

Didn't tested without docker yet but is on my todolist.

**Comment by deepthidevaki** [comment]
Later versions of Java (> 8):smile:.

**Comment by Zelldon** [comment]
We using java 11 so this shouldn't be the issue I hope.

**Comment by Zelldon** [comment]
I did a new round of testing with the same setup and VisualVM. I performed some GC's while running, as you can see nothing was really released. After 30 minutes the broker dies.

![screenshot-grafana](https://user-images.githubusercontent.com/2758593/65414823-c0ec9680-ddf4-11e9-8abd-ca82c477469e.png)
![screenshot-visual](https://user-images.githubusercontent.com/2758593/65414825-c0ec9680-ddf4-11e9-8336-3b83df310b9a.png)

I examined the Heap dump and found the following:

![screenshot-reader](https://user-images.githubusercontent.com/2758593/65414824-c0ec9680-ddf4-11e9-94a2-ca14d2b950f2.png)
![screenshot-writer](https://user-images.githubusercontent.com/2758593/65414826-c0ec9680-ddf4-11e9-85fd-97f8bb375ac1.png)

We have around 300 `io.atomix.storage.journal.FileChannelJournalSegmentWriter` instances and around 900 `io.atomix.storage.journal.FileChannelJournalSegmentReader` instances. All of theses instances hold an byte array of `8,388,648 B`. 

This multiplied by the count is `1200 * 8,388,648 B = 10066377600 B`.
This is around 10 GB of memory.

**Comment by npepinpe** [comment]
This is without any failover or anything right? The only thing I can imagine why we have so many writers opened is that we don't close them when we move on to the next segment? :see_no_evil:

**Comment by Zelldon** [comment]
I digged deeper into this and yes as you mentioned we do not close the writers/readers because we have around 300 open `JournalSegment`'s, which are referenced by the `SegmentedJournal`. It seems to be intended to keep them open.

**Comment by Zelldon** [comment]
**Problem:**

It takes a while for atomix under high load until it forces to compact the log. Until this happens all Journals are kept open (Files and allocated buffers as well).

**Proposal solution:**

For now I could think of increasing the segment size to 512 MB (currently 32 MB this a factor 16). This is the same value which we currently have with our log segments. If we change this, then this will decrease the open `Journals` (files and buffers). Since we then only have 8 MB buffer per 512 MB `Journal`, instead of 8 MB buffer per 32 MB `Journal`. This would probably also fix https://github.com/zeebe-io/zeebe/issues/3091. Currently I'm not 100% sure if this really fixes this or just delay the issue. But my hope is that at some point atomix is able to compact the log with some of these larger journals and frees memory.

**Alternative solution:**

We could investigate whether it is really necessary to keep all theses journals open. As far as I saw all the implementation relays on that. Since they want to find the last and first journal etc, but maybe we can change that.

I'm happy to hear other proposals.

**Comment by npepinpe** [comment]
I think we should investigate. My understanding is we keep track of all segments, but we shouldn't be keeping them all opened, as they should be closed when not in use anymore (there's even some kind of reference counting implemented). If what you changed mitigates the problem, we can move this to a separate issue.

**Comment by Zelldon** [comment]
I can explain it if you like. To keep it short it is simply not implemented to close the Journals before compaction.

If you take a look at this https://github.com/zeebe-io/atomix/blob/zeebe/storage/src/main/java/io/atomix/storage/journal/SegmentedJournalWriter.java#L100 . You see that the journal is released and here comes also your mentioned reference count into play but this does nothing if the StorageLevel is not Mapped. If it is mapped then this file is umapped and some resources are release, but also allocates again a new reader/writer with in-memory byte array idk why :see_no_evil: 

If StorageLevel.Disk then nothing will happen. This would be a nice place to maybe just set the allocated byte array to null and release some other resources :man_shrugging: 
But yeah might be a reason behind this.

If compact is called then the ConcurrentSet is cleared in the SegmentedJournal and this is the point where the GC finally is able to collect all these Journal objects.

**Comment by Zelldon** [comment]
OK as somehow expected the memory increases much slower but still increases.
Unfortunately prometheus was killed by k8s during the test run, most of the data was lost.
I probably need to adjust the scheduling such that prometheus is not scheduled on preemtable nodes.

I haven't seen any OOM exceptions but the cluster is however dead after a run of around 6 hours. Had no time yet to dig into this. I assume is the same issue as #2991 . I think the nodes have been restarted or something similar.


I think a quick fix for our current problem is to set the reader and writer of the journal to `null` in the `umap` or `close` method. But the _best_ solution would be to just have **one** reader and writer. These are given to the `JournalSegment` if a new one is created.

**Comment by Zelldon** [comment]
OK I think I know how to fix it. I tried it with releasing the readers and writers without real success, because the reader and writers are used later in truncation/compaction etc. Ideally I would like to have solution which do not need so many reader and writer but I think this is a bigger topic and refactoring work. The segmented journal seems a bit to complex more then probably necessary.

After I went this direction I thought about why the hell the compaction doesn't trigger.
And I found the following in the `RaftServiceManager` https://github.com/zeebe-io/atomix/blob/zeebe/protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftServiceManager.java#L135
```java
  private boolean isRunningOutOfMemory() {
    StorageLevel level = raft.getStorage().storageLevel();
    if (level == StorageLevel.MEMORY || level == StorageLevel.MAPPED) {
      long freeMemory = raft.getStorage().statistics().getFreeMemory();
      long totalMemory = raft.getStorage().statistics().getTotalMemory();
      if (freeMemory > 0 && totalMemory > 0) {
        return freeMemory / (double) totalMemory < raft.getStorage().freeMemoryBuffer();
      }
    }
    return false;
  }
```

Probably here the assumption was that we do not need to release memory if we running in DISK mode which is not true as we all know now :sweat_smile: 
I removed the conditional statement and tested it, but it doesn't work. The reason behind this is that the returned values from `StorageStatistics` (https://github.com/zeebe-io/atomix/blob/fix-out-of-mem/storage/src/main/java/io/atomix/storage/statistics/StorageStatistics.java) are not correct.
The class `StorageStatistics.java` uses MxBean to resolve the free and total memory. The value seem to be the memory of the k8s node instead of the specific JVM, which we can access via `Runtime`.

I did this here https://github.com/zeebe-io/atomix/commit/3f5be0151eec9a738f8526a7910ddd3e6e54f1e5#diff-4ee198e208b1d6ef0498322c9c93ce18R934 . This prints on our k8s setup the following:

```
 // Free memory: 28171657216 runtime free mem 380942632, total memory: 31622692864 runtime total mem 845152256
    final long free = 28_171_657_216L;
    final long runtimeFree = 380_942_632;

    final long total = 31_622_692_864L;
    final long runtimeTotal = 845_152_256;
```

And a bit later
```
    // Free memory: 19922669568 runtime free mem 1040520768, total memory: 31622692864 runtime total mem 4016046080

    final long free = 19_922_669_568;
    final long runtimeFree = 1_040_520_768;

    final long total = 31_622_692_864L;
    final long runtimeTotal = 4_016_046_080;
```

As you can see the returned values are not the right ones. I hope if we use the runtime value we get compaction running. I will try this tomorrow.

**Comment by Zelldon** [comment]
OK I tried out the fix on k8s and seems to work!

![screenshot-fix-mem-0](https://user-images.githubusercontent.com/2758593/65589720-caf3ce00-df89-11e9-88df-cc7f738b7a32.png)
![screenshot-fix-mem-all-0](https://user-images.githubusercontent.com/2758593/65589721-caf3ce00-df89-11e9-812c-a9a01e742767.png)
![screenshot-fix-visual-0](https://user-images.githubusercontent.com/2758593/65589723-cb8c6480-df89-11e9-89a3-ee3795a44239.png)

It seems that the collector is now able again to reclaim the memory

**Comment by Zelldon** [comment]
I created a PR to fix this issue in atomix https://github.com/zeebe-io/atomix/pull/28

![screenshot-fix2-graph-0](https://user-images.githubusercontent.com/2758593/65602500-4a8e9680-dfa4-11e9-8bad-4fefd2822e2e.png)

I currently run my test since 3.5 hours, seem to more or less work fine. Had one leader change but this is properly related to a different problem. First leader was broker 2 now it is broker 1.


Weird is that one of the followers (broker 0) consumes now a lot of memory. I will check this.

![screenshot-fix2-vm-0](https://user-images.githubusercontent.com/2758593/65602951-0ea80100-dfa5-11e9-9a44-99585681901f.png)

**Comment by jwulf** [comment]
Will this make it into the next release?

**Comment by npepinpe** [comment]
Yes :rocket:

**Comment by Zelldon** [comment]
We merged a PR in atomix, which should solve this issue https://github.com/zeebe-io/atomix/pull/28 also https://github.com/zeebe-io/zeebe/pull/3114 should reduce the used memory
