### ISSUE TITLE
Use StorageLevel.Mapped instead of DISK

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3094]
I would suggest that we use the `StorageLevel.Mapped` setting on creating the Raft partition group.

```
public class AtomixService implements Service<Atomix> {
...
    final RaftPartitionGroup systemGroup =
        RaftPartitionGroup.builder(systemPartitionName)
            .withNumPartitions(1)
            .withPartitionSize(clusterCfg.getClusterSize())
            .withMembers(getRaftGroupMembers(clusterCfg))
            .withDataDirectory(systemDirectory)
            .withFlushOnCommit()
            .withStorageLevel(StorageLevel.MAPPED) // <----
            .build();
```

Currently we set nothing, which means we use `DISK`. I would like to validate whether we get here a performance benefit.

**Comment by npepinpe** [comment]
I don't expect a big performance gain since I don't think we spend most of our time there, but it seems like a really low hanging fruit so I vote we do it. It anyway should not have any negative impact (except maybe bugs :sweat_smile:)

**Comment by Zelldon** [comment]
> I don't expect a big performance gain since I don't think we spend most of our time 
there,

Disagree, since we do a lot of IO on append and reading

**Comment by menski** [comment]
> since we do a lot of IO on append and reading

There should not be much traffic on the system partition. For the raft partition itself I would question if it's a good idea, as it might break the persistence guarantees required by raft to be safe. I.e. write to a memory mapped file might be different to writing to a file etc.

**Comment by Zelldon** [comment]
Didn't we use memory mapped files for our logstream as well?

**Comment by npepinpe** [comment]
> as it might break the persistence guarantees required by raft to be safe. I.e. write to a memory mapped file might be different to writing to a file etc.

I think if we flush on commit we should not be breaking any guarantees; in fact, writing to a file without flushing on commit (which we do atm) has the same breaking properties, no? Since you don't know when the OS will flush its IO buffers.

**Comment by Zelldon** [comment]
> I think if we flush on commit we should not be breaking any guarantees; in fact, writing to a file without flushing on commit (which we do atm) has the same breaking properties, no? Since you don't know when the OS will flush its IO buffers.

Agree. We did that in our LogStorage impl as far as I know

**Comment by npepinpe** [comment]
My main worries would be more that it's writable mmap IO, so higher risk of segmentation faults as opposed to Java exceptions, but the benefits probably outweigh the cost.

**Comment by Zelldon** [comment]
superseded by #4274 I hope we do this at some point...
