### ISSUE TITLE
Handle i/o mapping exceptions explicitly

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#311]
AT:
* handle i/o mapping exceptions directly there it can be thrown and write an incident event (this give us a better control of the processing)
* replace the incident error handler which is only used for the workflow instance processor

**Comment by ThorbenLindhauer** [comment]
+ exceptions on gateway condition evaluation

**Comment by ThorbenLindhauer** [comment]
Review:

The `StreamProcessorErrorHandler` concept is no longer used, so we should remove it for the time being.

**Comment by menski** [comment]
@saig0 is this issue done? there is a commit referencing it and kind of review hints?

**Comment by saig0** [comment]
@menski , it isn't done yet. I must apply the review hint and delete some stuff.
