### ISSUE TITLE
Investigate in more performant seek strategy

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3123]
**Description**

_**Note:** If we moved to the atomix log and have no longer our own log we do not need this anymore. But until then we need a solution, such that it doesn't take so long._

As we saw in https://github.com/zeebe-io/zeebe/issues/3107 and #2991 etc.
Our current log seek takes a while, which is kind of expected since we removed our log block index and have to read from the start of the log.

One of the improvements we can easily do is to reduce the snapshot interval such that compaction happens more often.

But to improve the seek in general we can do several things.

### Double linked list in the log

We could store in each log record the size of the record in the beginning **and** in the end of the record. With this we could also iterate over the records from the end of the log. This will increase the used space for each log record.

### Binary search

We need to store on each segment header the position of the first stored record, then we should be able to implement binary search for the seek to position. This means we would check the middle of our segments whether the stored position is higher or lower then our position where we want to seek to etc.

There are probably also other approaches we can discuss.

**Comment by deepthidevaki** [comment]
I have hacked in a prototype for an improved seek [here](https://github.com/zeebe-io/zeebe/commit/d9435c2d0fab9a8a47eb6a8134837d5397de058d). It's similar to the binary search approach you described, but instead using linear search. Read the first event in the segment, and skip to the next until we find the right segment, and then iterate over all events in a segment.

Results look promising. At this point the cluster was already running for an hour. Seek took 1s, Scan < 1m, Reprocessing ~1m.
```
12:44:19.535 [partition-1-processor] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot 
12:44:19.536 [partition-1-processor] INFO  io.zeebe.logstreams - Seek to snapshot position 3225527679720 
12:44:20.820 [partition-1-processor] INFO  io.zeebe.logstreams - Finished seeking to snapshot position 3225527679720 
12:44:20.821 [partition-1-processor] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position 3225527679720 
12:44:21.011 [partition-1-processor] DEBUG io.zeebe.processor - Start scanning the log for error events. 
12:45:12.825 [partition-1-processor] DEBUG io.zeebe.processor - Finished scanning the log for error events. 
12:45:12.825 [partition-1-processor] INFO  io.zeebe.processor - Processor seeking to snapshot position 3225527679720 
12:45:12.891 [partition-1-processor] INFO  io.zeebe.processor - Finished seeking to snapshot position 3225527679720 
12:45:12.891 [partition-1-processor] INFO  io.zeebe.processor - Processor starts reprocessing, until last source event position 3826821142392 
12:46:29.178 [partition-1-processor] INFO  io.zeebe.processor - Processor finished reprocessing at event position 3826821142392 
```

**Comment by npepinpe** [comment]
Using your prototype it should easy to quickly test out different search algos no?

**Comment by deepthidevaki** [comment]
Test for performance? We should first generate test data containing several large log segments. Now, I tested it by running it on the cluster ;)

**Comment by npepinpe** [comment]
Yes, and yeah, let's get a base log so we can compare properly.

**Comment by Zelldon** [comment]
We replaced our own log with atomix. We need to refactor the journal to  get better performance there
