### ISSUE TITLE
API Command to "turn broker on/off"

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#3148]
**Is your feature request related to a problem? Please describe.**
Brokers disappearing, then reappearing in production is a real thing. On Kubernetes, pods are pre-empted and rescheduled. 

At the moment the Node client at least has retry and reconnection logic to deal with this, but testing it in CI is difficult. 

On CircleCI it is trivial to test against a running broker or a non-existent broker, but to have a running broker and then have it disappear and reappear is non-trivial.

**Describe the solution you'd like**
Some API command to tell the broker to disappear, and another to tell it to reappear. It will need to be on a separate channel from the standard gRPC command API, and should only be enabled when some testing flag is set in the environment.

**Describe alternatives you've considered**
At the moment my approach is to script the broker bouncing via docker commands, but this can only be run locally and doesn't work in CircleCI. Ref: https://github.com/creditsenseau/zeebe-client-node-js/issues/82

**Comment by jwulf** [comment]
Currently planning to build a small scriptable gRPC mock from the protocol file: https://github.com/creditsenseau/zeebe-client-node-js/issues/85

**Comment by Zelldon** [comment]
Might make sense to use testcontainers for that as well https://github.com/testcontainers/testcontainers-node . We now writing go and c# integration tests with them 😊

**Comment by npepinpe** [comment]
The node version of testcontainers is already stable, so I second the recommendation :+1:

**Comment by Zelldon** [comment]
@menski can we close this?
