### ISSUE TITLE
Spike: Await workflow outcome

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3160]
**Description**

Implement a prototype for #2896.

Goal:
* Client sends request to create workflow instance
* When workflow instance completes a response is sent back to client
* Response contains variables (all root scope)
* Default failure cases are acceptable, i.e. gateway/broker failure leads to request timeout
* Canceling a workflow instance does not complete the request

**Comment by Zelldon** [comment]
I'm curios, do we have an idea how the API could look like? I have some ideas if you need input :slightly_smiling_face:

**Comment by deepthidevaki** [comment]
@Zelldon  There is no concrete plan. We should talk.

**Comment by deepthidevaki** [comment]
Result of spike:

In Java client:
 ```
ZeebeFuture<WorkflowInstanceEventResult> result =
        client
            .newCreateInstanceCommand()
            .bpmnProcessId(processId)
            .withResults()
            .send()
```
grpc:
```
rpc CreateWorkflowInstanceWithResults (CreateWorkflowInstanceWithResultsRequest) 
   returns (CreateWorkflowInstanceWithResultsResponse) {
}
```
In broker:
 * Added a new command for CREATE_WITH_AWAIT_RESULT. This would create the workflow instance as usual, but instead of sending the CREATED response, it stores the request info for future.
 * ELEMENT_COMPLETED handler writes a followup command SEND_RESULT with the set of variables
* SEND_RESULT command handler send the response back to the client

**Comment by Zelldon** [comment]
Closed with https://github.com/zeebe-io/zeebe/pull/3242
