### ISSUE TITLE
Use Raft directly

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3169]
**BREAKING CHANGE**

**Is your feature request related to a problem? Please describe.**

While we already use Raft as the back-bone for our consistency guarantees, but quite indirectly at the moment; we have a lightweight Atomix primitive, the `DistributedLog`, which writes to a self-managed segment journal, the `logstream`. The latter is what the engine reads from. In order to write entries to the log, we then have to go through the primitive, which means session handling, command sequencing, passing through the Atomix log, then finally through our primitive and then into our own `logstream`.

What this does is generally increase the complexity of an already complex program, and widens the error domain space, making things more difficult to debug and reason about.  

**Describe the solution you'd like**

The primary goal here is to simplify the overall architecture by making Zeebe simpler to reason about, simpler to debug, and simpler to maintain (note: I expect some performance increase due to the reduced overhead, but this is not the goal here). 

The proposed solution is then to eschew the primitive approach and use the Atomix multi-raft directly. This means writing and reading directly from the Atomix log: no more Raft sessions, command sequencing, log restoration, etc. 

As for snapshots and compaction, some changes were made to Atomix to accomodate our more controlled, asynchronous way of doing things: we will initially keep snapshots asynchronous, as they are, and will disable Atomix built-in snapshots. Rather once a snapshot is replicated, we will trigger compaction ourselves by using a compaction marker.

**Describe alternatives you've considered**

We considered different alternatives that still made use of the primitives, but generally these proved more complex.

Another one would be to do nothing, but as we all know, we are not yet as stable as we would wish, and the complexity of our stack is not helping anyone. The fact Atomix is rather opaque also doesn't help, nor does the fact that the maintainer is migrating the codebase to Go, meaning we can expect little support in the future.

**Additional context**

This is more of a catch-all issue, and I expect that smaller ones will be created with more specific goals; this will then be closed once the first iteration of a working, unified log is finished.

## Upgrade

The engine will now process the Atomix log directly, which means that our previous log will be discarded. To be safe, I would recommend users to perform a fresh install, but it might be possible to upgrade by ensuring that the processor has processed up to the end of the log and taken a snapshot. The reason I wouldn't recommend this is because it can be difficult to ensure that Zeebe has processed the whole log and no more events are being written to it, and a snapshot was taken.

**Comment by npepinpe** [comment]
We typically mark breaking changes in the PR and not in the issue, but I can see how this could be useful to have in the issue as well :+1:

**Comment by ysaakpr** [comment]
We are using zeebe in production, And we have long-running workflows which will take weeks to complete. How could we safely migrate the version to the new zeebe, with these braking changes ?. As suggested running a fresh installation is not a viable solution. Do you call it as Zeebe is not yet production-ready?
