### ISSUE TITLE
Follower does not receive AppendRequests

### ISSUE THREAD

**Issue by romansmirnov** [zeebe-io/zeebe#318]
**Given:**
* Broker `l1` (leader)
* Broker `f1` (follower)
* Broker `f2` (follower)

**When:**
`l1` sends append requests to `f1` and `f2`.

**Observed Behavior:**
`f1` receives after a certain amount of time append requests which `l1` actually sent to `f2`. As a result, `f2` times out and starts a poll.
In some cases, it also happens that `f1` receives append requests which `l1` sent to `f2` and vice versa.

It looks like that there exists a map, that caches the channels, without removing them, whenever a channel gets closed.

In this particular case, there exists for example the following channels
* `c1`: `l1` -> `f1` with the id `5`.
* `c2`: `l1` -> `f2` with the id `10`

After a certain amount of time a new channel is opened:
* `c3`: `l1` -> `f1` with the id `13`.

Afterwards again a new channel is opened:
* `c4`: `l1` -> `f2` with the id `5`.

So that every request which should be sent to `f2` is actually sent to `f1`.

Maybe this is related to https://github.com/camunda-tngp/zb-transport/issues/18 or it is actually a bug in Raft.

**Comment by menski** [comment]
As far as I know this does not happen anymore
