### ISSUE TITLE
A problem I found while clustering

### ISSUE THREAD

**Issue by YAoXIhOnG** [zeebe-io/zeebe#3182]
Have you consider a condition that run a cluster with docker in different virtual machine? I try that then the problem occur. 

> 06:40:09.399 [] [main] INFO  io.zeebe.broker.system - Starting broker with configuration {
  "network": {
    "host": "172.17.0.2",
    "portOffset": 0,
    "commandApi": {
      "host": "172.17.0.2",
      "port": 26501,
      "sendBufferSize": "16M"
    },
    "internalApi": {
      "host": "172.17.0.2",
      "port": 26502,
      "sendBufferSize": "16M"
    },
    "monitoringApi": {
      "host": "172.17.0.2",
      "port": 9600,
      "sendBufferSize": "16M"
    }
  },
  "cluster": {
    "initialContactPoints": [
      "192.168.175.131:26502",
      "192.168.175.132:26502"
    ],
    "partitionIds": [
      1,
      2
    ],
    "nodeId": 0,
    "partitionsCount": 2,
    "replicationFactor": 2,
    "clusterSize": 2,
    "clusterName": "zeebe-cluster"
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/usr/local/zeebe/data0"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "snapshotReplicationPeriod": "5m",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "hazelcast",
      "className": "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args": {
        "enabledValueTypes": "JOB,WORKFLOW_INSTANCE,DEPLOYMENT,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION"
      }
    }
  ],
  "gateway": {
    "enable": true,
    "network": {
      "host": "0.0.0.0",
      "port": 26500
    },
    "cluster": {
      "contactPoint": "172.17.0.2:26502",
      "transportBuffer": "128M",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "172.17.0.2",
      "port": 26502
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "172.17.0.2",
      "port": 9600
    }
  }
}
06:40:10.315 [service-controller] [172.17.0.2:26501-zb-actors-1] INFO  io.zeebe.transport - Bound commandApi.server to /172.17.0.2:26501
06:40:18.174 [] [zb-blocking-task-runner-1-172.17.0.2:26501] INFO  io.zeebe.gateway - Version: 0.20.0
06:40:18.176 [] [zb-blocking-task-runner-1-172.17.0.2:26501] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "enable": true,
  "network": {
    "host": "0.0.0.0",
    "port": 26500
  },
  "cluster": {
    "contactPoint": "172.17.0.2:26502",
    "transportBuffer": "128M",
    "requestTimeout": "15s",
    "clusterName": "zeebe-cluster",
    "memberId": "gateway",
    "host": "172.17.0.2",
    "port": 26502
  },
  "threads": {
    "managementThreads": 1
  },
  "monitoring": {
    "enabled": false,
    "host": "172.17.0.2",
    "port": 9600
  }
}
06:40:19.271 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [172.17.0.2:26501-zb-actors-0] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '172.17.0.2:26501' on transport 'gateway-broker-client'
06:40:23.919 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - java.net.ConnectException
06:40:25.362 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [172.17.0.2:26501-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '1' with address '172.18.0.3:26501' on transport 'gateway-broker-client'
06:40:30.266 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:40:36.547 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:40:43.827 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:40:48.956 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:40:55.360 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:41:02.516 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:41:08.664 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502
06:41:14.369 [] [raft-server-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - io.netty.channel.ConnectTimeoutException: connection timed out: /172.18.0.3:26502

My two vms' IP are '192.168.175.131' and '192.168.175.132', and '172.18.0.3' is the IP of the docker run on anther vm  so cannot connection it.So i try make two docker become a subnet using route then clustering again. This time i run a zeebe cluster success but anther problem arise on hazelcast：program pending with the message : 'Initializing cluster partition table arrangement...' . Is it just because configuring in error? I sincerely hope you'll help me.（I‘m not good at English so excuse my poor English）

**Comment by jwulf** [comment]
What host OS are you running on? Docker networking on Windows is tricky.

You can use port binding in Docker to forward the ports from the container to the host, then explicitly set the network interfaces to publish in the zeebe.cfg.toml.

**Comment by jwulf** [comment]
Did you find a fix for this?

**Comment by YAoXIhOnG** [comment]
> Did you find a fix for this?

I'm sorry for reply so late. My Host OS is centos 7 x64, And i do use port binding in Docker  and  use the default network interfaces. But I still cannot succeed.I try to find the reason and found this:
![image](https://user-images.githubusercontent.com/37016436/68909615-e0b39180-0789-11ea-8738-78d7abc5a6c8.png)

Here I drow a picture to explain how i maker the cluster.And the below picture is the log out:
![image](https://user-images.githubusercontent.com/37016436/68909639-f759e880-0789-11ea-8836-c1ef30ba03d6.png)

I think the connect Ip maybe the 192.168.175.132 but not 172.18.0.3 for the reason that docker 1 and docker 2 are not at same subnet.

**Comment by npepinpe** [comment]
These days, you could use the `advertisedHost` property to differentiate between the interface you should bind to, i.e. `host`, and the interface other nodes should contact, i.e. `advertisedHost`. Hope this solves the issue!
