### ISSUE TITLE
Rename GitHub Organization

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#321]
As it seems that waffle does not support free access to private repositories we decided to rename the GitHub organization when we open source Zeebe.

AT:
- `camunda-tngp` -> `camunda-zeebe`
- open main source projects

**Comment by menski** [comment]
@Zelldon I think https://github.com/camunda-zeebe/zb-build-tools should also be open source? As it is needed by our parent pom. What do you think? If so we should add a license to the repository. Sorry I forgot that when extracting it.

**Comment by Zelldon** [comment]
Hm, is it possible to release something on maven central without being open source? 
If so I'm not sure if we really need to publish this repo, but I can do if you like.

**Comment by menski** [comment]
What would be a reason to keep it closed source? It doesn't contain any source :)

**Comment by Zelldon** [comment]
To not confuse the users :D I will publish it

**Comment by Zelldon** [comment]
Done :)

**Comment by menski** [comment]
We now have to adjust all the Jenkin JobDSL files to contain the correct github organization `camunda-zeebe` instead of `camunda-tngp`. Until then no Jenkins Builds will be triggered by git push.

**Comment by menski** [comment]
We also have to adjust the github urls in all the pom files, e.g. https://github.com/camunda-zeebe/zeebe/blob/master/pom.xml#L55-L57
