### ISSUE TITLE
Workflow wide headers

### ISSUE THREAD

**Issue by sergeylebed** [zeebe-io/zeebe#3218]
Currently, you can define custom headers on workflow elements. There's a situation that I want to have common information shared between all elements. For example, I want to TenantId to be common for all elements in a workflow.  

It will be convenient if it is possible to set workflow wide headers and they are available in a worker in the job parameter, as job.WorkflowHeaders().

Actually, the "header" does not seem to be related to workflows. I suggest to call them Properties.
So, they will be job.ElementProperties(), job.WorkflowProperties(), and [job.InstanceProperties()](https://github.com/zeebe-io/zeebe/issues/3219)

**Comment by saig0** [comment]
If you create a workflow instance with variables then the variables are available for all elements in the workflow. So, every worker can access it. 

Is this what you are looking for? If not, why not using variables?

**Comment by sergeylebed** [comment]
Headers are not changeable from a worker. Variables are. That is the difference that is important to me.

**Comment by jwulf** [comment]
You could do this using the variables now by having a `readOnly` subkey or similar.

It would still be by convention, as they could be mutated or the key overwritten, but it would give you a namespace that would need to be explicitly overwritten. If you are coding in a language with a type system, like TypeScript, then you could make it readonly in the interface definition.

That will land faster than this as a feature, unless someone PRs it in.

**Comment by sergeylebed** [comment]
I though about it as feasible workaround but it is not completely safe. For example, TenantId must not be changeable under any condition. 

For this particular case with headers, it is better to just repeat such properties in each element. It increase the storage size but at least it is the safe solution.

**Comment by jwulf** [comment]
Ah, where you don't control and cannot trust the worker code.... Yes, it becomes not just a surface area for bugs then, but a vector for attack.

**Comment by saig0** [comment]
It seems that this feature request can be solved by #3219. If "read-only variables" can be defined on workflow instance creation then they can act as static headers of the workflow.

I'm closing this issue in favor of #3219. Feel free to re-open it if you still see a strong need to it :)
