### ISSUE TITLE
Not found order-process.bpmn in Quickstart

### ISSUE THREAD

**Issue by tonny1983** [zeebe-io/zeebe#3222]
In Step 3 of **[1.3 Quickstart](https://docs.zeebe.io/introduction/quickstart.html#step-3-deploy-a-workflow)** of current docs, it mentions an example process named **order-process.bpmn** and there is a download link (https://docs.zeebe.io/introduction/order-process.bpmn) for it. 
Unfortunately, the URL returns 404 and the bpmn file cannot be downloaded via it.

**Comment by saig0** [comment]
Thank you for reporting :+1: 

I'm fixing it...
