### ISSUE TITLE
Change name to property "zeebe.client.job.worker"

### ISSUE THREAD

**Issue by spulci** [zeebe-io/zeebe#3231]
Looking at class ClientProperties in the io.zeebe.client package, it specifies several properties. I'm referring to this one:

/** @see ZeebeClientBuilder#defaultJobWorkerName(String) */
  public static final String DEFAULT_JOB_WORKER_NAME = "zeebe.client.job.worker";

IMHO it should be renamed to somenthing likke:

"zeebe.client.job.workerName" or a more hierarchical  one (more future proof) like "zeebe.client.job.worker.name"

**Comment by saig0** [comment]
Good point :+1:  

Feel free to open a PR. I would change it to `zeebe.client.worker.name` to be consistent with the other properties like `zeebe.client.worker.threads`.
