### ISSUE TITLE
--insecure flag is not working

### ISSUE THREAD

**Issue by victorrumanski** [zeebe-io/zeebe#3246]
**Description**
I am following this tutorial
https://docs.zeebe.io/getting-started/deploy-a-workflow.html#check-the-status-of-the-broker
on windows
when I run ./bin/zbctl.exe --insecure status
it gives this message:

$ bin/zbctl.exe --insecure status
Error: unknown flag: --insecure
Usage:
  zbctl [command]
...

**Comment by victorrumanski** [comment]
If I ommit the flag it works, and I get the status

**Comment by menski** [comment]
What is your `zbctl` version, i.e. run `./bin/zbctl.exe version`?

**Comment by victorrumanski** [comment]
NB25950@LT128251 MINGW64 /c/dev/zeebe/zeebe-broker-0.20.0
$ ./bin/zbctl.exe version
zbctl 0.20.0 (commit: 1ddfb216)

**Comment by menski** [comment]
The insecure flag was added with zbctl 0.21.0, as since this version secure is the default. Your version (0.20.0) always is insecure.
