### ISSUE TITLE
Don't write snapshot for topic subscription

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#326]
We do not need to write a snapshot for topic subscriptions.

**Comment by Zelldon** [comment]
> We do not need to write a snapshot for topic subscriptions.
@saig0 I'm not quite sure if this is still the case. Since the topic subscription creates a snapshot of the acked positions, if this will not happen it will resume from begin. What do you mean?

**Comment by saig0** [comment]
@Zelldon ,  that's true for `TopicSubscriptionManagementProcessor`. But there is a second stream processor `TopicSubscriptionPushProcessor` that doesn't use / need the snapshot.

**Comment by menski** [comment]
Topic subscriptions are no longer supported
