### ISSUE TITLE
Atomix segment creation causes small processing performance drops

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3266]
**Description**

On investigating #3257 I deployed an workflow which contains an endless loop. I created ca. 300 instances to see how the cluster and the processing behaves. It seems quite stable but we observed some smaller drops. It seems that these drops are related to Atomix segment creation. 

![endless-instances](https://user-images.githubusercontent.com/2758593/67664207-774d1980-f967-11e9-9f95-d7f8a3feee4c.png)

```
I 2019-10-28T08:20:29.590319424Z 2019-10-28 08:20:29.590 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=6, version=1, index=7250558}
 
I 2019-10-28T08:20:29.601408568Z 2019-10-28 08:20:29.601 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=6, version=1, index=7250558}
 
I 2019-10-28T08:26:44.784625858Z 2019-10-28 08:26:44.784 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=8700030}
 
I 2019-10-28T08:26:44.819771496Z 2019-10-28 08:26:44.819 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=8700030}
 
I 2019-10-28T08:26:44.828672107Z 2019-10-28 08:26:44.828 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=8700030}
 
I 2019-10-28T08:32:59.598119480Z 2019-10-28 08:32:59.597 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=10149503}
 
I 2019-10-28T08:32:59.634794121Z 2019-10-28 08:32:59.634 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=10149503}
 
I 2019-10-28T08:32:59.635891406Z 2019-10-28 08:32:59.635 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=10149503}
 
I 2019-10-28T08:39:15.956736581Z 2019-10-28 08:39:15.956 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=11598977}
 
I 2019-10-28T08:39:15.991925323Z 2019-10-28 08:39:15.991 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=11598977}
 
I 2019-10-28T08:39:16.002398668Z 2019-10-28 08:39:16.002 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=11598977}
 
I 2019-10-28T08:45:31.052464819Z 2019-10-28 08:45:31.052 [] [raft-server-raft-atomix-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=10, version=1, index=13048448}
 
```

Would be nice if we find a solution to avoid these drops.

**Comment by Zelldon** [comment]
In the following image we can see that the compaction and snapshot correlate to the processing drops.

![endless-compaction](https://user-images.githubusercontent.com/2758593/67677997-c99d3300-f985-11e9-8467-e03bc0a26a76.png)

**Comment by npepinpe** [comment]
I think we discussed possibly performing compaction asynchronously; in theory safe, but I don't think the Atomix Journal is thread safe, so might require some more serious work.

**Comment by deepthidevaki** [comment]
It is the flush of previous segment which takes too long. 
![segment-flush](https://user-images.githubusercontent.com/1997478/68131729-d1c51780-ff1d-11e9-8376-b4fcb3a3a785.png)

**Comment by npepinpe** [comment]
Don't we also flush on commit? Or is that something else?

**Comment by Zelldon** [comment]
> Don't we also flush on commit? Or is that something else?

Unfortunately we are don't but we should I think.

**Comment by Zelldon** [comment]
Interesting for me was also that it took 7 sec with using the persistent storage @deepthidevaki tested that without and with that.

**Comment by deepthidevaki** [comment]
Broker configured with persistent disk volumes:
![with-pd](https://user-images.githubusercontent.com/1997478/68134450-6f224a80-ff22-11e9-804c-baff96c5bb1e.png)

With out peristent disk volumes:
![no-pd](https://user-images.githubusercontent.com/1997478/68134479-78131c00-ff22-11e9-9c93-5914b4effd53.png)

Writing to persistent disk volumes have some affect on flush latency. But even with local disk, it sometimes take > 1s.

**Comment by Zelldon** [comment]
This was fixed with the referenced flush on commit fix
