### ISSUE TITLE
Remove ExporterClearStateService and related components

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3311]
**Description**

It seems the functionality to clear an exporter's state when it is removed from the configuration was moved to the `ExporterDirector`, but we still create the `ExporterClearStateService` and related classes.

We should remove its usage as it is not necessary anymore.

**Comment by Zelldon** [comment]
The `ExporterClearStateService` is installed to clear the state when no exporter is configured.

**Comment by npepinpe** [comment]
Is this because we don't install any other exporter related services if we no configured exporters?

**Comment by Zelldon** [comment]
Yes and we need to depend on the related partition otherwise we can get again race conditions. https://github.com/zeebe-io/zeebe/issues/3256

**Comment by npepinpe** [comment]
Gotcha :+1:
