### ISSUE TITLE
How are partitions selected (What is used as the partition key?)

### ISSUE THREAD

**Issue by dctc42** [zeebe-io/zeebe#3351]
Hi,

I'm researching workflow engines for a new project. One of the capabilities I'm looking for is the ability to segregate differently workflows into different partitions. Specifically, I'd like to be able to segregate particularly intensive workflows and workflows from different teams. Netflix's conductor supports the concept of a domain that can be used to partition workloads. 

1.- Can partitions be used to accomplish this?
2.- Is workflow id used to route workflows to different partitions?

**Comment by jwulf** [comment]
1. No, you need to use different clusters for this at the moment.
2. Yes.

Why do you want to do this? Can you give me more background on the scenario? There may be another way to accomplish the desired outcome with Zeebe.

**Comment by saig0** [comment]
To be more concrete on the second point, workflow instances are created on different partitions in a round-robin way. So, the instances are spread across all partitions. There is no way to control the assignment.

**Comment by dctc42** [comment]
Thanks for your response. Here's my scenario at a high level:
- Need to orchestrate service workflows across multiple customer-facing SaaS applications. 
- The different applications are owned by different teams, developed using different platforms, deployed on different data centers.
- All applications are multi-tenant.

It would be nice to be able to control partition assignment through a workflow execution key. I anticipate some customers triggering a disproportionate amount of workflow executions, in temporary spikes, that can impact other customers. (noisy neighbor problem) 

I was part of the original team that built AWS Lambda and we solved this by using consistent hashing/hash-ring to place customer jobs in the same bucket of resources, i.e. partition.

**Comment by jwulf** [comment]
You may want route across different clusters at the infra level for this. Zeebe is designed to load balance work and execute everything as fast as possible, in the order it is received.
