### ISSUE TITLE
Standalone gateway doesn't always receive leader change events

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3361]
**Describe the bug**
When using a standalone gateway, sometimes the gateway doesn't receive leader change cluster event.  Broker-4 is the new leader for partition-3. But the gateway still thinks broker-3 is still the old leader. Leader change has already happened a few minutes earlier.

![image](https://user-images.githubusercontent.com/1997478/68761210-e5563980-0613-11ea-8f40-7270976816d1.png)

**To Reproduce**
It doesn't always happen. But you can probably reproduce it with a standalone gateway and 5 brokers.

**Expected behavior**
Gateway immediately receives cluster events.

**Comment by Zelldon** [comment]
Related to that https://github.com/zeebe-io/atomix/issues/16 ?

**Comment by deepthidevaki** [comment]
Yes. That's my guess.

**Comment by npepinpe** [comment]
So if we have the gateway contact all brokers as well then it should be fine? Not great but it's a workaround :sweat_smile:

**Comment by deepthidevaki** [comment]
Or does the brokers have to know about gateway? :thinking: Because brokers should gossip to the gateway.

**Comment by npepinpe** [comment]
:scream: 

I would hope the brokers don't have to know, then I'd rather work on a real solution than a workaround :s

**Comment by Zelldon** [comment]
No gateway will contact an initial node and join the cluster - if the join succeed eventually the brokers will know the gateway.

**Comment by deepthidevaki** [comment]
So, this is the same issue as #3364. From the logs, gateway has received all events. But the leader change event of node 4 was overwritten by events from node-3.
```
11:34:09.246 Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=4, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={3=LEADER, 4=FOLLOWER, 5=LEADER, 8=LEADER}} 
11:34:43.756 Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=3, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={2=FOLLOWER, 3=LEADER, 4=LEADER, 7=FOLLOWER, 8=FOLLOWER}} 
11:34:46.722 Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=3, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={2=FOLLOWER, 3=LEADER, 4=LEADER, 7=FOLLOWER, 8=LEADER}} 
11:34:48.309 Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=3, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={2=FOLLOWER, 3=FOLLOWER, 4=LEADER, 7=FOLLOWER, 8=LEADER}} 
11:34:54.994 Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=3, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={2=FOLLOWER, 3=FOLLOWER, 4=LEADER, 7=FOLLOWER, 8=FOLLOWER}} 
```

**Comment by deepthidevaki** [comment]
Closing this now. Can reopen if we find issues with gossip.
