### ISSUE TITLE
Topology manager receives events in different order resulting in wrong leader info 

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3364]
**Describe the bug**
When there is a back-to-back leader transition, topology updates might be received in the wrong order. See below log.
 1. Gateway receives events saying broker 3 is the leader for partition 2
 2. Gateway updates leader for partition 2 as broker 3
 3. Receives events saying broker 2 is leader for partition 1 and 2 (It is not clear, if this was the event for partition 2 leader change or partition 1 leader change)
 4. Gateway updates the leader for partition 2 as broker 2
 5. Gateway receives events with broker 2 is follower for partition 2.
 6. Gateway removes broker 2 from leaders. There is no leader for partition 2 according to the gateway.
In this case, broker 3 is the actual leader, but that info was overwritten. Broker 2 was elected as the leader for only short time. (Why that happened, idk).
```
I 2019-11-12T16:59:13.656942129Z 2019-11-12 16:59:13.656 [GatewayTopologyManager] [zeebe-4.zeebe.default.svc.cluster.local:26501-zb-actors-7] DEBUG io.zeebe.gateway - Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=3, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={2=LEADER, 3=FOLLOWER, 4=FOLLOWER, 7=LEADER, 8=FOLLOWER}} 
 
I 2019-11-12T16:59:15.713919400Z 2019-11-12 16:59:15.713 [GatewayTopologyManager] [zeebe-4.zeebe.default.svc.cluster.local:26501-zb-actors-4] DEBUG io.zeebe.gateway - Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=2, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={1=LEADER, 2=LEADER, 3=FOLLOWER, 6=FOLLOWER, 7=FOLLOWER, 8=FOLLOWER}} 

I 2019-11-12T17:00:49.713773874Z 2019-11-12 17:00:49.713 [GatewayTopologyManager] [zeebe-4.zeebe.default.svc.cluster.local:26501-zb-actors-4] DEBUG io.zeebe.gateway - Gateway received new event of type: METADATA_CHANGED and subject BrokerInfo{nodeId=2, partitionsCount=8, clusterSize=5, replicationFactor=3, partitionRoles={1=LEADER, 2=FOLLOWER, 3=FOLLOWER, 6=FOLLOWER, 7=FOLLOWER, 8=FOLLOWER}}
```

There might be a couple of problems in play here:
1. Events can be reordered. It is gossip, no guarantee of ordering.
2. When we get a topology event, we overwrite the topology with the new event. The event might only indicate a change in the information of 1 partition.

**Comment by Zelldon** [comment]
Nice catch :+1:

**Comment by Zelldon** [comment]
Can we just build the topology from the member properties? On topology request? Or can we easy detect that an old event arrived or only has a partial update?

**Comment by deepthidevaki** [comment]
> Can we just build the topology from the member properties? On topology request? 

This would be possible and solve the problem, I guess. As far as we know, embedded gateways never miss any updates. So if we just read the member properties, we would eventually have the right info. There can be an intermediate states where it thinks there are two leaders for a partition.

> Or can we easy detect that an old event arrived or only has a partial update?

We can add leader term into the properties. That way we can find which is the latest update.

**Comment by Zelldon** [comment]
> This would be possible and solve the problem, I guess. 

Might be not so performant, if we always re-build the state from the properties.

**Comment by menski** [comment]
I would add the term info into the properties and update accordingly.

**Comment by npepinpe** [comment]
Doesn't that just lower the probability of missing updates? It's still possible to miss some, no?

**Comment by Zelldon** [comment]
> Doesn't that just lower the probability of missing updates? It's still possible to miss some, no?

The probability is the same I would say if we add just add the term :slightly_smiling_face:
