### ISSUE TITLE
Ability to specify Zeebe Workflow Engine Instance URL in Call Activity

### ISSUE THREAD

**Issue by tvvignesh** [zeebe-io/zeebe#3366]
Hi. I was going through https://stage.docs.zeebe.io/bpmn-workflows/call-activities/call-activities.html and https://github.com/zeebe-io/zeebe/issues/3180 and while this is exactly what I need to enable micro-service communication, how do we specify the Zeebe Instance URL when invoking call activity?

When I have one Zeebe Workflow Engine per Microservice, then the processId alone is not enough for me to do callActivity since the other workflow is running in some other Zeebe Instance. It would be great if we have the ability to specify the workflow instance url when doing call activity along with the processId.

Thanks in advance.

**PS:** Btw, you guys are doing amazing work with Zeebe. Kudos.

**Comment by npepinpe** [comment]
Hi @tvvignesh! The call activity currently is started on the same partition as the workflow instance being executed, meaning that it can currently only be started on the same node. This was done to simplify the first iteration of the future. So right now it's not possible to execute the call activity on a different broker. Possibly in the future it can be distributed, but I don't imagine it will ever leave the same Zeebe cluster.

Hope that answers your question! Feel free to ask in the channel if you have a specific use case that you're wondering how to architecture, the community can always help there.

**Comment by jwulf** [comment]
Workaround: if you are committed to multiple engines, you could write a worker that calls createWorkflowInstance using config from the headers/variables.

Although - if you are doing this across engines, what are you actually isolating? Because more engines = more ops complexity, and you are coupling them anyways with this...

**Comment by tvvignesh** [comment]
@npepinpe Thanks a lot for your response. Was doing this mainly since I wanted to have a WFE per microservice but as all of you suggest, it feels like I am going overboard to start with :P 
Will go with what @jwulf has suggested then if at all I want to do this.

@jwulf I was thinking of doing the orchestration between the WFE through some sort of event queue so that the event published by a WFE instance can be consumed by another. But, nevermind. Thanks.

**Comment by npepinpe** [comment]
If that's all, then I'll close this, feel free to reopen it or talk to us on the slack channel if there's anything else.
