### ISSUE TITLE
Enable gRPC keepalive

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#3368]
**Is your feature request related to a problem? Please describe.**

To support long living connections like, long polling and await workflow result, the grpc client should send keep alive messages to prevent intermediate proxies from closing the connection.

https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Describe the solution you'd like**

The java and go client should send a keep alive every 30s. It should be configurable at client level.

**Additional context**

https://github.com/camunda-cloud/cluster-infra/issues/93

**Comment by npepinpe** [comment]
Like I mentioned in the discussion, I think server side all that's needed is to configure a max acceptable keep alive rate (to avoid aggressive clients), then it's purely client configuration I think.

I think we should also make sure to test this with the cloud team, make sure it works with the nginx ingress controller, I think there might be some issues at play there as well.
