### ISSUE TITLE
zeebe-broker 0.21.1 do not support java 8 when compile project?

### ISSUE THREAD

**Issue by Jungle666** [zeebe-io/zeebe#3369]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (java-compile) on project spring-zeebe-broker: Compilation failure
[ERROR] /E:/obs/zeebe/spring-zeebe-master/broker/spring-zeebe-broker/src/main/java/io/zeebe/spring/broker/ZeebeBrokerObjectFactory.java:[3,23] cannot access io.zeebe.broker.Broker
[ERROR] error class file: .m2\repository\io\zeebe\zeebe-broker\0.21.1\zeebe-broker-0.21.1.jar(io/zeebe/broker/Broker.class)
[ERROR] class file has the wrong version 55.0, should be 52.0
[ERROR] Please delete the file or make sure it is in the correct classpath subdirectory.

**Comment by Zelldon** [comment]
It is expected since the broker only supports java 11+
