### ISSUE TITLE
Create snapshots with an randomized offset

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3376]
**Is your feature request related to a problem? Please describe.**
Currently we take snapshots for all partitions on the same time. This affects the network, because then for each partition the snapshots have to be replicated to all followers, this can be a lot of data.

**_Latest benchmark:_** 
We can see here that every 15 min, the processing drops.
![processoing](https://user-images.githubusercontent.com/2758593/68924056-2c613d80-0780-11ea-8e69-38e60c66bf96.png)

And the network and disk io has a lot to do.
![io](https://user-images.githubusercontent.com/2758593/68924342-e3f64f80-0780-11ea-9b9e-60609a2d177a.png)

**Describe the solution you'd like**
We should consider to take snapshots not on fixed rate for all partitions.

If we pseudo randomize the snapshot interval for each partition, e.g. add an random offset of 1 between 30 sec. to the interval it might distributed the load better.

**Describe alternatives you've considered**
There is none.

**Additional context**

_Note:_ I think it also makes sense to have an lower bound for the snapshot interval like 1 min. Otherwise we will flood the network with snapshot replications.

**Comment by deepthidevaki** [comment]
I ran an experiment with randomized delay of 0-3 minutes. At first, the state is small. The number of running workflow instances are less < 300K. At this time, snapshots are not affecting the processing. Once the number of running workflow instances > 500K, we start to see the dips. At this point, the snapshots are close to 1GB. So it is consuming both the network bandwidth and disk bandwidth available for the processing.

![image](https://user-images.githubusercontent.com/1997478/69160301-a4fe2c00-0ae9-11ea-9325-887d192ecd9b.png)

**Comment by npepinpe** [comment]
It might be a good time to look into tuning RocksDB, but I guess that will only mitigate the problem. The main solution here is to investigate having the followers also build their own state, but for that we should probably wait until we've merged the new log stream.

**Comment by Klaus-Nji-sp** [comment]
> I ran an experiment with randomized delay of 0-3 minutes. At first, the state is small. The number of running workflow instances are less < 300K. At this time, snapshots are not affecting the processing. Once the number of running workflow instances > 500K, we start to see the dips. At this point, the snapshots are close to 1GB. So it is consuming both the network bandwidth and disk bandwidth available for the processing.
> 
> ![image](https://user-images.githubusercontent.com/1997478/69160301-a4fe2c00-0ae9-11ea-9325-887d192ecd9b.png)

Would it be accurate to say that the size of workflow variables could also negatively affect performance.  In other words you could be running a lot less than 500K workflows but if you do not take into consideration the size of the variables, not only could there be some negative performance consequences from delays in serialization and navigation of these large json maps but one could also be seeing snapshots 1G in size?

**Comment by deepthidevaki** [comment]
Yes. The size of the snapshot will be affected by variables size. Number of running workflows is not a reliable metrics to estimate snapshot size.

**Comment by Zelldon** [comment]
>  The main solution here is to investigate having the followers also build their own state

Would probably the best agree.
