### ISSUE TITLE
Please add a section on nomenclature to the documentation

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [zeebe-io/zeebe#3379]
**Description**

There is a lot of terminology surrounding Zeebe, its architecture and implementation.  We have snapshots, brokers, clients, clusters, gateways, partitions, etc.

While there is a section in your documentation describing some of these concepts, a section on commonly used terminology within the architecture may help users and readers better understand the system.  Also, since you guys use the terminology in your day-to-day communication, it will also help others following the development to have a better understanding of the issues/features you are working on.

**Comment by saig0** [comment]
Thank you for raising this up! It's a good idea.

Do you want to make the first step and create the initial section?
It seems that you already have an idea that terms should be listed there.

**Comment by Klaus-Nji-sp** [comment]
> Thank you for raising this up! It's a good idea.
> 
> Do you want to make the first step and create the initial section?
> It seems that you already have an idea that terms should be listed there.

I can certainly do that.  Will need a thorough review though as I am still learning the underpinnings.  How do I proceed? Does not look like there is a different repo for docs.....

**Comment by saig0** [comment]
Nice :+1: 

The documentation is in this repository under `/docs`. Please have a look at the README: https://github.com/zeebe-io/zeebe/tree/develop/docs.

**Comment by Klaus-Nji-sp** [comment]
Please see https://github.com/zeebe-io/zeebe/pull/3407

**Comment by Zelldon** [comment]
I think this is done with the referenced PR. I will close this, feel free to reopen this if there is anything left
