### ISSUE TITLE
Deleting non-recoverable snapshots

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3382]
**Description**

At the moment, on recovery, if we cannot recover from a particular snapshot, *regardless of the error*, we delete the snapshot. In a worse case scenario, we could delete all available snapshots, leaving us in an inconsistent state (i.e. a log but not state to recover from). This could happen if, for example, file system permissions were messed up and we couldn't open the snapshots even though they're perfectly valid.

I'd just like to question whether it makes sense to just delete the snapshots without investigating; maybe we should put them in a "dead" snapshots folder, and only delete them once we build more snapshots again? If we can't recover at all from any, then we can stop and there is a chance (depending on the error) that an operator could manage to recover from those snapshots. 

In any case, the most important part is that if we fail to recover from any snapshot, we shouldn't start processing a truncated log as we've got no state at this point, and that partition should then be "suspended" on that broker; is this what we're currently doing?

**Comment by Zelldon** [comment]
I think we can close that, since we using only one snapshot right?

**Comment by npepinpe** [comment]
Correct - however I see we still have the code to check if we have more snapshots :sweat_smile: I can create another issue to remove this
