### ISSUE TITLE
zbctl deploy displays unhelpful error

### ISSUE THREAD

**Issue by brepine** [zeebe-io/zeebe#3388]
Falko asked that I report this.

My issue was that I was using the latest version of the Zeebe modeler but not the latest zeebe-docker-compose so when I tried to deploy a .bpmn w/a Call Activity I received the following error which was not very helpful in determining the issue:

cmd:
...\Docker\zeebe-docker-compose> .\bin\zbctl.exe --insecure deploy .\bpmn\diagram_2.bpmn

error:
Error: rpc error: code = InvalidArgument desc = Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following errors:
'.\bpmn\diagram_2.bpmn': class org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl cannot be cast to class io.zeebe.model.bpmn.instance.BpmnModelElementInstance (org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl and io.zeebe.model.bpmn.instance.BpmnModelElementInstance are in unnamed module of loader 'app')

Once I had all the versions in sync I was able to deploy the .bpmn

**Comment by saig0** [comment]
Thank you for reporting! This is the same issue as #3278
