### ISSUE TITLE
Allow to specify every technical attribute as expression

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#3417]
**Is your feature request related to a problem? Please describe.**

Most technical attributes, i.e. timer duration, task headers, called process id, are set as static value during the modeling phase. But often these values depend on runtime data provided to the process itself. It should be possible to set technical attributes using expressions.

**Describe the solution you'd like**

A technical attribute is per default an expression an evaluated based on the process variables. A constant value is a valid expression. i.e. strings can be quoted.

**Describe alternatives you've considered**

Having different attributes which distinguishes constants and expressions. This requires more input fields in the modeler and the user has to understand the differences while modeling.

**Additional context**

Camunda BPM allows to set expressions for the majority of attributes but uses JUEL with a specific syntax to mark an expression to distinguish it from constant values, i.e. `${myVariable}`. It needs to be decided if we want to have expressions or constants as default.

**Comment by saig0** [comment]
## Outcome of discussion:
* one input field in the modeler to avoid confusion 
* supporting the user to write either a static value or an expression (e.g. toggle the input field between both) 
* use two attributes in the XML: one for the static value and one for the expression
* using FEEL as the expression language for Zeebe

**Comment by 0x15e** [comment]
After reading [some docs about FEEL](https://docs.camunda.org/manual/latest/reference/dmn11/feel/), it looks like it's intended for decision-making expressions. Will there be features for, e.g., string concatenation, simple math, date math, etc. included? How fully-featured is the FEEL implementation you intend to use and are there additional docs I could read to learn more about it?

**Comment by falko** [comment]
@0x15e Yes, FEEL is part of the [DMN Standard](https://www.omg.org/spec/DMN) and like JSONPath has been originally derived from XPath to work on object structures. One advantage over JSONPath is exactly that FEEL has a [built-in function library](https://camunda.github.io/feel-scala/feel-built-in-functions) and does not rely on any underlying scripting language for more complex expressions. [Our implementation](https://github.com/camunda/feel-scala/) is 99.5% feature-complete as [demonstrated through the DMN Technology Compatibility Kit](https://dmn-tck.github.io/tck/archive-DMNv1.1/overview_Camunda%20BPM_7.9.0.html#tab2).

**Comment by 0x15e** [comment]
Fantastic. Thanks!

**Comment by saig0** [comment]
Thank you for your interest! Here is an overview of the expressions you can write with FEEL: 
https://camunda.github.io/feel-scala/feel-expression. 
* math expressions :heavy_check_mark: 
* date/time/duration expressions :heavy_check_mark: 
* string concatenation :heavy_check_mark: 
* comparisons :heavy_check_mark: 
* list operations: every, some, for, filter, projection :heavy_check_mark: 
* and more using the built-in functions

**Comment by B-Stefan** [comment]
Just an idea: 

Maybe it would be nice to register a worker to evaluate expressions. 
The use case would be to support multiple expression-languages depending on customer needs. 
For us, a some kind of [Mongo like](https://github.com/kofrasa/mingo) syntax could be interesting.

**Comment by saig0** [comment]
The idea with the worker is possible in addition to the builtin expression support. There is already a community project like this: https://github.com/zeebe-io/zeebe-script-worker

However, in Zeebe we also need some kind of expression support to do variable mappings or to define conditions on exclusive gateways. This kind of expressions should be evaluated inside the Zeebe broker itself to reduce the latency.
For now, we decided against a pluggable expression support to have more control over the expressions.

**Comment by saig0** [comment]
Closing this proposal issue. The state can be tracked via milestone: https://github.com/zeebe-io/zeebe/milestone/35
