### ISSUE TITLE
The java-client should provide a callback for status changes (connection unavailable/available)

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#3429]
Somewhere in the GRPC stack it should be possible to register pieced of code that indicate if the connection to the broker works - or does not.

This should be easily consumable to allow https://github.com/zeebe-io/spring-zeebe/issues/79 (which again is required by https://github.com/zeebe-io/zeebe-http-worker/issues/8).

A TypeScript example using the NodeJS client library is here: https://github.com/camunda-cloud/zeebe-http-worker/blob/master/src/worker/worker.ts#L86

**Comment by npepinpe** [comment]
I see the related spring-zeebe issue was closed - is this still something you need? How would it work exactly? We don't exactly keep a long running connection open, so the state would mostly be based on the previous request status. Or maybe I misunderstood the request?

**Comment by berndruecker** [comment]
The health check in spring-zeebe now polls the cluster topology to check for health. This works, so I think we can close it (even if conceptionally it feels better to catch the connection exceptions from GRPC to judge about health - but well ;-))
