### ISSUE TITLE
Add RocksDB snapshot metrics

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3447]
**Is your feature request related to a problem? Please describe.**

We currently have no metrics on RocksDB snapshots, which could be crucial in determining the behaviour of our brokers (i.e. replication, impact of large states, compaction, etc.)

**Describe the solution you'd like**

Adding metrics for the following:

1. Snapshot count
1. Snapshot sizes
1. Snapshotting runtime

Optionally, also the current runtime size would be interesting.

**Describe alternatives you've considered**

**Additional context**

To be done after we merge our log iteration.

**Comment by Zelldon** [comment]
I would love to have snapshot metrics back :sweat_smile:
