### ISSUE TITLE
Parallel Gateway: Not combining results, throwing IO_EXceptio

### ISSUE THREAD

**Issue by dinilv** [zeebe-io/zeebe#3449]
**Describe the bug**
While using parllel gateway to combine results from two nodes, variables are not getting passed over to next node. Behaviour is unstable in which same zeebe-modeler diagram gives Pass in one test and next test it fails keeping no changes to zeebe-clients and workflow same
**To Reproduce**
Steps to reproduce the behavior
1. try one workflow with parallel gateway
2. restart your docker 
3. try the same workflow 
4. throws IO-Error
5. Another instance it passes variables.
If possible add a minimal reproducer code sample
 - when using the goClient

**Expected behavior**
Stable behaviour experimenting ParallelGateway

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: MacOS
 - Zeebe Version:latest Docker
- Configuration: gitlab.com/go-seller/zeebe-manager/zeebe-docker-compose/operate-simple-monitor

docker-compose up

**Comment by saig0** [comment]
Hi @dinilv,

thank you for reporting! 
Unfortunately, I can't reproduce this issue with your description. Please check the link to the gitlab repository, it's returning 404.

**Comment by dinilv** [comment]
Will add more details, is it possible that its an intermittent issue since am running the instance in docker(MacOS) ?
Variables were not passing to next node on the workflow and was throwing exception.
