### ISSUE TITLE
Restarting a broker with many segments causes broker timeout

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3456]
**Describe the bug**

When restarting with a large state, the broker start up times out after 40 seconds before Atomix has successfully joined. My guess is this is due to Atomix rebuilding its log-block-index equivalent which requires it to read all segments.

**To Reproduce**

Create a large enough state and restarting a broker will take longer and longer - eventually it takes longer than the broker start up time out (40 seconds), which means Atomix will eventually join and start doing its thing, but none of our services will be installed afterwards, resulting in a partially started node.

**Expected behavior**

A node with a large state can eventually start.

**Comment by npepinpe** [comment]
Related to #3454

**Comment by Zelldon** [comment]
This problem seems to exist also on clean restart.

**Comment by Zelldon** [comment]
Seems to be a race condition after clean restart it looks good again

![restart](https://user-images.githubusercontent.com/2758593/69911036-a3036980-1415-11ea-9a71-597685dcb38e.png)

**Comment by npepinpe** [comment]
What do you mean by clean restart?
