### ISSUE TITLE
Improve zbctl test coverage

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3472]
**Description**

Currently there are some basic integration tests for zbctl which test some common commands as well as some tests for configuration. These should be extended to test that zbctl is well configured with different combinations (e.g., flags, env vars, different methods for different parameters, etc)

**Comment by MiguelPires** [comment]
Add a test for the throw error command

**Comment by menski** [comment]
@MiguelPires could you break this issue down to specific actionable items, i.e. what tests are missing so me can individually prioritize them. I think with #3462 we already improved here, correct?

**Comment by MiguelPires** [comment]
Yes, https://github.com/zeebe-io/zeebe/pull/3462 adds tests for some features but there are still some missing. I opened more focused issues #4583 and #4584, to add tests for secure gateways and missing job features, respectively.

**Comment by npepinpe** [comment]
I assume this is superseded by these issues then? I'll close this, feel free to reopen.
