### ISSUE TITLE
Raise an incident if an error is not caught

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3503]
**Is your feature request related to a problem? Please describe.**
I want to see if an incident is not caught by a boundary event or an event subprocess. An error should always be caught in the workflow. If not then there is a misconfiguration in the job worker or workflow.

**Describe the solution you'd like**
* if an error is not caught then an incident is created on the service task that throws the error
* the incident can not be resolved - only by canceling the activity, the scope, or the workflow instance
* the incident contains the error message of the error event if provided by the client 
* the incident has the error type: `UNCAUGHT_ERROR`

**Describe alternatives you've considered**
* cancel the workflow instance if the error is not caught -> less transparent for the user
* ignore if the error is not caught -> also, less transparent
* reject the command from the client -> every worker would be responsible for notifying the problem to the user  

**Additional context**

requires #3497 
requires #3498 
requires #3502

**Comment by menski** [comment]
@saig0 let's sync on this on Monday
