### ISSUE TITLE
Test module clarification

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3521]
**Description**

Actually I'm currently a bit unsure who uses this module and what is purpose is. Could the usage also replaced by test containers? My problem with this module is that we have a copy of the EmbeddedBrokerRule, which we need to maintain as well.

**Comment by npepinpe** [comment]
I think this is part of the discussion with #3419

**Comment by saig0** [comment]
Closing this issue in favor of #3419.
