### ISSUE TITLE
Allow context in Go client API

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3530]
**Describe the solution you'd like**
Support passing Context in the Go client. Currently, the user can specify a timeout which we use to create a context which is then passed on to the command API. However, user code will probably already have a context since it's the idiomatic way and receiving a context would also allow the user to cancel the request, specify a deadline or propagate a cancellation/timeout down to zeebe (which currently isn't possible).

**Additional context**
More information context:
https://golang.org/pkg/context/
https://blog.golang.org/context

**Comment by MiguelPires** [comment]
For now, we will leave the `setRequestTimeout` and `Send` methods in the interface and mark them as deprecated. The new `Send(context.Context)` method will take the context as is, without setting default timeouts or deadlines. In the release after the next, the way of setting timeouts will be through the `Send(context.Context)`. We could optionally have a client configuration that allows the user to set the timeout once and use it in every request if no other timeout is present in the context. This would reduce the amount of work the user has to do if it wants to use the same timeout for every request. At the same time, it would be simpler to have a single way of setting timeouts instead of having two and forcing the user to know which takes precedence/how they relate to the other.

**Comment by MiguelPires** [comment]
This is blocked by https://github.com/zeebe-io/zeebe/issues/3580

Short summary of the issue before I go on vacation: 
The first iteration added a context, eliminated the `setRequestTimeout` method and moved that configuration to the client configuration. The reasoning was permitting the user to pass his own contexts while also providing a way to only have to set a timeout once. However, that requires us to look into the context to see if it has a deadline and, if not, using the one configured in the client. That's easily done but if the user wants to have a default timeout and then disable it for a single request, then that's impossible, he'd have to set a very long timeout instead. Also, the minimum amount of work done by the user would be passing `context.Background()` to the `Send` method, so requiring an actual timeout isn't much more work. These considerations together with the long-polling issues, make this too much stuff for the user to know about a single parameter imo. I'd prefer having only the context.Context, it would greatly reduce cognitive load, be much more transparent (what you type is what we used) and it would be more idiomatic. This is obviously my biased opinion but I think would be simpler in the medium and long term to have a single knob to configure this quantity.

**Comment by zeromberto** [comment]
Hey @MiguelPires,

we would like to see this issue resolved as well. The reason we want to pass a custom context to `Send()` is that we want to transmit tracing information which usually lives in the context. In our use case we want collect traces from our api through zeebe to the job worker at the end. We use the opentracing standard for that. Also see #2932 for further information regardinf zeebe and opentracing.

**Comment by MiguelPires** [comment]
Hey @zeromberto, thank you for the feedback. There are just a few questions that I have to clarify internally and then this issue should be ready
