### ISSUE TITLE
TransactionOperation may run out of ZeebeDbTransaction by ZeebeDbTransaction.run()

### ISSUE THREAD

**Issue by jan4984** [zeebe-io/zeebe#3542]
**TransactionOperation may run out of ZeebeDbTransaction by ZeebeDbTransaction.run()**

I'm implementing a zeedb adapter to postgresql other than rocksdb becaure our k8s not have persistent filesystem supports now. After reading the source code, everything seems reasonable, but I can not find out how `ZeebeDbTransaction.run()` can make sure the TransactionOperation runs in the transaction? Becaure the `TransactionOperation.run()` not has argument to bind TransactionOperation to some Transaction, neither some `ThreadLocal` storages(if one transaction bind to one thread).

Please Zeebe teem can tell me what I missed?

**Comment by Zelldon** [comment]
Hey @jan4984 this is interesting. What was the reason behind choosing a relational database and over a nosql one? 

Currently the transaction is opened when the ZeebeTransaction is created. So it is a 1:1 mapping. But you could also open a new one when run is called and run the changes which are made during this time in a transaction. On commit call the underlying transaction should be committed.

Be aware that zeebe expects on iterating that the key-value pairs are ordered. Can you do that with your postgres adapter?

**Comment by jan4984** [comment]
Thanks for replying quickly.

I'm not sure what the `1:1 mapping` mean to my question. Does it means `ColumnFamily` operations invoked in `TransactionOperation`  should have the same underlying transaction instance with `ZeebeDbTransaction` who runs the `TransactionOperation`?

The reason I have mentioned that our k8s not have persistent filesystem supports for containers now.

About the key-value pairs order, rocksdb orders bytes lexicographically by default, postgres order bytea column in same way. I think it's not a problem, hopefully.

**Comment by jan4984** [comment]
It's said zeebe use local file system not only via rocksdb, but also raft. There are too much works. I have to giveup using zeebe and find some other tools.
