### ISSUE TITLE
Add OAuth timeout config in Java client

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3556]
**Is your feature request related to a problem? Please describe.**
The Go client allows the user to specify a timeout for the OAuth request through code and an environment variable.

**Describe the solution you'd like**
Allow user to configure a timeout for the OAuth request through code and an env var.

**Comment by aivinog1** [comment]
@npepinpe @MiguelPires Hi! I think I can take this. I have some questions about it:
1. In the Java client we have a [readTimeout](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setReadTimeout-int-) and a [connectTimeout](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setConnectTimeout-int-). Should a configuration specified both?
2. What will be the defaults of such timeouts?
3. I think that we should use a Duration to specify this in the configuration. Am I right?

**Comment by MiguelPires** [comment]
Hey @aivinog1, thank you for picking up this issue! I'll try to answer your questions:

1. Yes, I think that would be best
2. The Go client has a 10 second timeout for the whole request so maybe 5 seconds for each timeout would be similar and also enough. But feel free to challenge this
3. Yes, but also bear in mind that the env var should be the same as the one in the Go client (ZEEBE_AUTH_REQUEST_TIMEOUT) and that one is interpreted as the number of milliseconds

Let me know if there's anything I can do to help

**Comment by aivinog1** [comment]
@MiguelPires Thanks :)
