### ISSUE TITLE
Document Prometheus metrics

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3569]
**Description**

In the last months we added a lot of new metrics, which are currently not yet documented. 
In order to get better understanding and user adoption we should document them.

**Comment by npepinpe** [comment]
I'd also like to publish our Grafana dashboard, but I'm not sure how to do so without it becoming something "official" 😅 I'd rather not have more stuff to support/explain, but I think for some people that dashboard could be a very useful resource.

**Comment by npepinpe** [comment]
We document some metrics already, but we're not strict when it comes to documenting all of them. I'll bring it up at the next team meeting.
