### ISSUE TITLE
Validate snapshot on commit

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3577]
**Description**

When committing a new pending snapshot, we should validate it before returning success. Validation is most simply done by opening/closing the database, as RocksDB will check the integrity of the DB using its manifest.

We already check replication with checksums, but I've seen it happen in practice that the RocksDB detects a failure and refuses to open the database, so imo the safest way is to simply do this. It's unfortunately a little more time consuming, but as this happens in the background (and hopefully with #3376 this shouldn't be as much of a problem).

**Comment by Zelldon** [comment]
Currently we send per snapshot chunk a checksum, which is based of that chunk. We could also add a checksum for the complete snapshot. Which is then verified after we received all chunks.

**Comment by npepinpe** [comment]
That would probably guarantee integrity, but the real test is that RocksDB can read the snapshot, isn't it? I'm wondering if we gain that much (e.g. performance) by using the checksum over letting RocksDB runs its integrity checks.

**Comment by Zelldon** [comment]
But if the leader creates the snapshot then it should be readable right (i hope) :sweat_smile: 

> I'm wondering if we gain that much (e.g. performance) by using the checksum over letting RocksDB runs its integrity checks.

This is probably something we need to test.

**Comment by npepinpe** [comment]
I can do some tests and see how bad it would be to open/close the DB. A checksum of the whole snapshot should be safe enough though, right? I still feel like the real test is that RocksDB can recover it :man_shrugging:

**Comment by npepinpe** [comment]
As we now know, we should avoid opening snapshots, and only open the runtime database. As such, we can use a total checksum to verify that the snapshot was correctly transferred - the next question is should we store the checksum along with the snapshot, such that we can also verify it when we want to recover from it? I would say yes, but perhaps I'm forgetting something and this isn't necessary?

**Comment by npepinpe** [comment]
Closing as the current feature set is acceptable for now.
