### ISSUE TITLE
Long-polling configuration question

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3580]
**Description**

When introducing contexts in the Go client #3530, there were some issues with the long-polling configuration. The first is related to the naming. Here's an excerpt from the activate jobs command:
https://github.com/zeebe-io/zeebe/blob/b1c8e303a37e8e619ddf9ca562d057bb98b05b3d/clients/go/pkg/commands/activateJobs_command.go#L120-L128
There's `timeout`, `requestTimeout` and `RequestTimeout` which is somewhat confusing. Since `requestTimeout` is the "client-side" timeout and the `RequestTimeout` is the server-side/long-polling timeout, I'll stick to that terminology for this issue. 
The other issue is that if the user passes a context with a client-side timeout then it's likely he won't be aware of the relationship between these timeouts and add a margin to the one in the context. In the current implementation, when the user sets the long-polling timeout we add an offset to the client-side one to avoid failing the command which is impossible using contexts. This is also seems do differ from the CreateInstanceWithResult which doesn't allow settings the long-polling timeout. One simple solution would be to always take in the client-side timeout from the context/configuration and calculate the long-polling timeout from that. From the user's perspective, there would only be one knob to configure this quantity. I'd like your opinion @deepthidevaki and @menski, do you see a reason or use case to keep this parameter available to the user?

**Comment by Zelldon** [comment]
I had the same issue with the C# client. I renamed this request timeout, which is the long polling timeout, to polling timeout. https://github.com/zeebe-io/zeebe-client-csharp/blob/master/Client/Api/Worker/IJobWorkerBuilderStep1.cs

**Comment by deepthidevaki** [comment]
> One simple solution would be to always take in the client-side timeout from the context/configuration and calculate the long-polling timeout from that. From the user's perspective, there would only be one knob to configure this quantity. do you see a reason or use case to keep this parameter available to the user?

Users can disable long polling by specifying a timeout < 0. If we configure long polling timeout indirectly, we wouldn't be able to disable it. Otherwise, I don't see any big issue if we calculate any one timeout from the other.

**Comment by MiguelPires** [comment]
Thanks for the feedback
