### ISSUE TITLE
Zeebe-Operate Failed to Show running instance

### ISSUE THREAD

**Issue by dinilv** [zeebe-io/zeebe#3588]
**Describe the bug**
Deploy an instance to Workflow using Go-Client multiple times. 
Check the same instance has come in Zeebe-Operate.
At least 2/10 deployments will be failed to show in operate

**To Reproduce**
Zeebe-Cluster deployed in kubernetes using latest Helm Chart

If possible add a minimal reproducer code sample

> func InitiateBpmnInstance(workflow, uploader, ip string, variables map[string]interface{}) bool {

	request, err := zbc.Client.NewCreateInstanceCommand().BPMNProcessId(workflow).LatestVersion().VariablesFromMap(variables)
	log.Println("Variables:-",variables)
	if err != nil {
		log.Println("Error in instance creation BPMN", err)
		return false
	}
	resp, err1 := request.Send()
	if err1 != nil {
		log.Println("Error in instance creation BPMN", err, err.Error(), resp)
		return false
	}

	return true
}

**Expected behavior**
See all Instances appear in Zeebe-Operate
**Log/Stacktrace**
Logs are same as usual but failed to show on Zeebe-Operate  

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS:kubernetes version: v1.13.11
 - Zeebe Version: 0.22
 - Configuration:

**Comment by sdorokhova** [comment]
Hi @dinilv ,
did I get it right, that you have one workflow deployed and you start several instances of it?
Please provide logs of both Zeebe and Operate, so that we can check what's going on

**Comment by Zelldon** [comment]
This issue seems for me outdated. I will close this issue. Feel free to reopen it if the issue still exist.
