### ISSUE TITLE
Output Parameters with result dict

### ISSUE THREAD

**Issue by mirecl** [zeebe-io/zeebe#3621]
Hi guys.
I'm create process with two steps. 
First step option output parameters:
`price : result.price`

after i see response `{"result":{"price":100}}`
Seconds step option output parameters:
`amount : result.amount`
and after i see `{"result":{"amount":1200}}`

But  i want to see response `{"result":{"price":100,"amount":1200}}`

**Comment by Zelldon** [comment]
Hey @mirecl ,

could you please provide a minimal process and example payload, such that we can reproduce this issue easier. 

Greets
Chris

**Comment by mirecl** [comment]
I'm use camunda/zeebe:0.21.1 from **operate-simple-monitor**.
Worker write on Go.
[simple.zip](https://github.com/zeebe-io/zeebe/files/4039569/simple.zip)

**Comment by Zelldon** [comment]
Hey @mirecl 

thanks  for reporting this. I was able to reproduce this issue.
It seems to be a bug in the variable merging, we will take a look at this soon.

Greets
Chris
