### ISSUE TITLE
Cluster Manager should save/load state of current rafts

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#363]
The Cluster Manager component has to:
- regularly write the state of all its current rafts on to disk
- on startup of the cluster manage all raft states are loaded and recreated

Raft state to save:
- log stream (topic, partition, term, location, ...)
- votedFor

Note: This was already implemented with the old raft implementation. While integrating the new raft module this code was deleted.

**Comment by menski** [comment]
Today I learned that this is required to get recovery working so I have to implement it with the raft replacement anyways.

**Comment by menski** [comment]
It seems I don't have to implement it yet... just need to get my service start order right :balloon:

**Comment by ThorbenLindhauer** [comment]
Review hints:

* `RaftPersistentFileStorage`: `Files#move` has an option to configure an atomic move, if supported. Maybe we can use that to reduce the probability of inconsistencies even further
* `RaftPersistentFileStorage`: can use a single buffer for read and write
* `RaftPersistentFileStorage`: votedFor is currently not persisted
* `RaftPersistentStorageTest#shouldPersistConfiguration`: assertion of the term is always true
* Replace `LangUtil#rethrowUnchecked` with runtime exceptions
