### ISSUE TITLE
Go integration tests are flaky

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3641]
**Description**

Some builds fail at times due to the Go integration tests failing, even when no changes where made to the Go client. While this is possible (i.e. if we drastically change a command, or we remove a command, etc.), it definitely happens at times where it shouldn't (e.g. updating a build time dependencies or maven plugin), hinting that there's some flakiness going on with them. Since the reporting is currently kind of iffy it's hard to say what the problem is.

**Comment by MiguelPires** [comment]
Note: the flaky integration tests are the zbctl ones.
I ran them locally for a while but couldn't reproduce the issue

**Comment by npepinpe** [comment]
Recently came across this:

```
Error
Failed
Stacktrace
+ OS=(linux windows darwin)
+ BINARY=(zbctl zbctl.exe zbctl.darwin)
++ dirname ./build.sh
+ SRC_DIR=.
+ DIST_DIR=./dist
+ VERSION=release-test
+ COMMIT=1234567890
+ mkdir -p ./dist
+ rm -rf ./dist/zbctl ./dist/zbctl.darwin ./dist/zbctl.exe
+ for i in "${!OS[@]}"
+ '[' 1 -eq 0 ']'
+ '[' linux = linux ']'
+ for i in "${!OS[@]}"
+ '[' 1 -eq 0 ']'
+ '[' windows = linux ']'
+ for i in "${!OS[@]}"
+ '[' 1 -eq 0 ']'
+ '[' darwin = linux ']'
+ wait
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands.Version=release-test -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands.Commit=1234567890' -o ./dist/zbctl ./main.go
main_test.go:108: couldn't build zbctl: signal: killed
```

**Comment by npepinpe** [comment]
This is happening more often, we should invest a bit of time soon-ish.

**Comment by npepinpe** [comment]
So a bit of a update: there's a time out in the zbctl integration tests around the `buildZbctl()` step, which was previously 30s; we increased it to 2 minutes, as compilation in the cloud on a slow machine might exceed 30s at times, but we'll monitor it.

**Comment by npepinpe** [comment]
So some progress, it looks like the builds are timing out, but the tool we use to convert the Go test output to JUnit mangles the panic output, resulting in this weird, hard to understand output.

At least we now know the issue: by default the go test has a 10 minutes time out. On passing builds, the tests take ~1 min, but on those where we get the weird stacktrace only output, they time out after 10 minutes, indicating something probably went terribly wrong. As it happens solely with integration tests, my guess is it's related to test container more than anything, and the container either fails to start up, or has some error.

**Comment by npepinpe** [comment]
Related to #3809
