### ISSUE TITLE
Add dynamic duration for Timer Boundary Event

### ISSUE THREAD

**Issue by ezolnbl** [zeebe-io/zeebe#3655]
In Camunda Timer Boundary Event's timeDuration attribute can be referenced as a context / execution variable with expression language. This feature is missing from zeebe. Currently there is a validation at bpmn deploy time for the duration attribute which could be turn off or simply handle the value as an expression in case of invalid duation interval. At CatchEvent timer subscription time the variable's value could be aquired from the context with MsgPackQueryProcessor. I propose a new ExpressionTimer implementation to be used to wrap the interval expression and fill it at first initialization before event subscription.

**Comment by kjozsa** [comment]
the lack of this feature is a blocker in our use-case, so please consider adding this functionality to the engine.

**Comment by saig0** [comment]
@ezolnbl, thank you for your input!

We are aware that this is an important topic and want to tackle this in the near future :artificial_satellite: 

Related issues: #3417, #3079

**Comment by saig0** [comment]
Done by #3799

**Comment by asaf** [comment]
@saig0 docs state that [Time Date](https://docs.zeebe.io/bpmn-workflows/timer-events/timer-events.html#time-date) should work but seems like a specific point in time is not working.

Version: 0.24.1

Results:

```
value: 2019-10-01T12:00:00Z
error: Expected result of the expression '2019-10-01T12:00:00Z' to be parsed to duration, but was '2019-10-01T12:00:00Z' and encountered error: Text cannot be parsed to a Period


value: = date and time("2019-10-01T12:00:00Z")
error: Expected result of the expression ' date and time("2019-10-01T12:00:00Z")' to be one of '[DURATION, PERIOD, STRING]', but was 'DATE_TIME'
```

Should I open a new ticket for this?

Thanks,

Asaf.

**Comment by saig0** [comment]
@asaf thank you for reporting. Yes, please open a new issue. Don't forget to share your BPMN. 

Maybe, there is an issue of how the timer is configured. Currently, a date-time is available for timer start events only.

**Comment by asaf** [comment]
@saig0 oh, I tried with a standard timer event, I'll open an issue for that, thanks!
