### ISSUE TITLE
Integration test suite fails on linux with too many open files

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#366]
At the moment I cannot run the integration test suite on my local machine as it fails after some tests with `java.io.IOException: Too many open files`. My machines is configured to allow 4096 open files per process, which is the default I think for linux. The test suite still passes on Jenkins as we allow 1048576 open files per process inside the docker container.

I think it would still be nice to run the test suite on a default configuration of 4096 max open files. Attached is the output of `lsof` for the surefire process before the test suite bails out.

[lsof-surefire.txt](https://github.com/camunda-zeebe/zeebe/files/1191735/lsof.txt)

**Comment by ThorbenLindhauer** [comment]
Review hints:

* let's try to avoid having two flags that indicate if a client conductor is closing
* also close `AcceptTransportPoller` and `ReadTransportPoller` properly
