### ISSUE TITLE
Check positions increasing on reprocessing

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3662]
**Description**

in order to avoid issues like #3651 we should add an verification in our system, which detects such issues early on. 

Since we scan the log on reprocessing already, we could here add a check for the positions. This means just check that the positions are always increasing. If there is an error we should fail the stream processor start and step down with #3499

**Comment by npepinpe** [comment]
We only partially scan the log, or? So it may not catch everything (like we discussed, the issue we had wasn't immediately apparent because sometimes it still worked :sweat_smile:), but I agree it would already be useful and it's quite cheap (though not sure what the user is supposed to do with that error).

**Comment by Zelldon** [comment]
> We only partially scan the log, or? So it may not catch everything (like we discussed, the issue we had wasn't immediately apparent because sometimes it still worked ￼), but I agree it would already be useful and it's quite cheap (though not sure what the user is supposed to do with that error).

Yes only the part which is interesting since the other are already processed.

> though not sure what the user is supposed to do with that error

Nothing the user should not need to do anything. I mean he can't :sweat_smile: The leader should step down, in worst case all nodes have inconsistent log and the processing stops gracefully.

**Comment by Zelldon** [comment]
Done with https://github.com/zeebe-io/zeebe/pull/4093
