### ISSUE TITLE
Include Grafana dashboard

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3674]
**Description**

While Zeebe provides a number of metrics, these are often poorly (or not) documented, and not easily understandable by everyone. As we internally maintain our own Grafana dashboard to monitor our tests/benchmarks of Zeebe anyway, it would be beneficial for everybody all around to have this dashboard available - it would also allow us to check in the related dashboard modifications when we add new metrics, so the visualization of said metrics is more easily testable by the reviewer.

(pinging @afirth since you were interested :eyes:)

**Comment by afirth** [comment]
Also allows loading by Prometheus operator by url, since it's in an open repo, reducing effort
