### ISSUE TITLE
Intermittent gRPC Error 13 when publishing multiple messages to the same workflow instance

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#3675]
**Describe the bug**

On 0.22-alpha1, when publishing a bunch of messages to Zeebe, I periodically get an Internal error response in the client. On the server I see this:

```
2020-01-15 14:53:04.903 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [172.19.0.3:26501-zb-actors-0] ERROR io.zeebe.gateway - Error handling gRPC request
io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.1.jar:1.24.1]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:352) ~[zeebe-gateway-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:281) ~[zeebe-gateway-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:146) ~[zeebe-gateway-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:182) ~[zeebe-gateway-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:32) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-alpha1.jar:0.22.0-alpha1]
Caused by: io.zeebe.transport.RequestTimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.sender.OutgoingRequest.timeout(OutgoingRequest.java:143) ~[zeebe-transport-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.transport.impl.sender.Sender.onTimerExpiry(Sender.java:291) ~[zeebe-transport-0.22.0-alpha1.jar:0.22.0-alpha1]
	at org.agrona.DeadlineTimerWheel.poll(DeadlineTimerWheel.java:344) ~[agrona-1.0.10.jar:1.0.10]
	at io.zeebe.transport.impl.sender.Sender.processTimeouts(Sender.java:100) ~[zeebe-transport-0.22.0-alpha1.jar:0.22.0-alpha1]
	... 6 more
```

**Comment by Zelldon** [comment]
Hey josh,

could you try to reproduce this with the latest Snapshot. We replaced the transport impl. Would be interesting if this changes due to this replacement.

Greets
Chris

**Comment by jwulf** [comment]
On 0.22.1 this morning:

```
zeebe_1          | 2020-01-17 07:33:15.980 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-0-zb-actors-1] ERROR io.zeebe.gateway - Error handling gRPC request
zeebe_1          | io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing
zeebe_1          | 	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
zeebe_1          | 	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:372) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:301) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:147) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:183) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_1          | Caused by: java.util.concurrent.TimeoutException: Request type command-api-1 timed out in 15000 milliseconds
zeebe_1          | 	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-alpha10.jar:?]
zeebe_1          | 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
zeebe_1          | 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
zeebe_1          | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
zeebe_1          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
zeebe_1          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
zeebe_1          | 	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Zelldon** [comment]
Thanks josh I some more questions:

Does is affect only a little percentage of your requests or really all?
A little percentage would be expected.
How does your setup look like? 
Is this easy to reproduce for you?
Could you share your example code?

Could you check how the topology look like?
Do you see any other errors in the broker log?
Do you have access to the metrics?

**Comment by jwulf** [comment]
It happens a lot. 
I can reproduce it reliably every time.
I don't have an MRE atm - it's part of my running system. 
I can show you it running when you are in the office next.

One broker with embedded gateway.
No load to speak of....

**Comment by jwulf** [comment]
Reproducer: https://github.com/jwulf/zeebe-3675-reproducer

**Comment by jwulf** [comment]
Here is some further info:

1. On an AWS instance with 4GB of RAM, single broker in Docker, it presents from message ~200 - ~600.
2. On a local broker in Docker on my machine, it happens at above 1000, somewhere between ~1500 - 2000
3. On Camunda Cloud, it happens at ~130.

It seems to be proportional to the network latency between the client and the broker - the higher the latency, the lower the number of messages are needed to trigger the unexpected internal error.

**Comment by Zelldon** [comment]
Ok so you're saying only some of these requests are rejected not all eight? This seems to me expected, since this back pressure algorithm is latency based.

https://github.com/Netflix/concurrency-limits


> Java Library that implements and integrates concepts from TCP congestion control to auto-detect concurrency limits for services in order to achieve optimal throughput with optimal latency.

Maybe @deepthi can give some more insights here.
Are you using different correlation keys? If not be aware that these messages are always targeting the same partition, which means less throughput as well.

**Comment by jwulf** [comment]
The issue is the broker returns an "error 13 unexpected error".

The back pressure message appeared since 0.22-alpha2, and is a different issue related to performance. That is handled on the client by the retry strategy. 

The error 13, however, causes a fatal exception on the client and is some kind of bug. 

Have a look at the reproducer.

**Comment by jwulf** [comment]
I have some further information. The issue is mitigated by raising the gateway timeout. In Scenario 2 [here](https://github.com/zeebe-io/zeebe/issues/3675#issuecomment-575797736), if I raise the gateway timeout to 30s, I can pump in 3000 messages without hitting this error.

So the broker is processing all the messages without triggering backpressure, but is not responding to the gateway fast enough, and the gateway is throwing an error to the client.

**Comment by jwulf** [comment]
Hmmmm - to make my workflows that can take more than 15s to complete awaitable, I have to raise the global timeout.....

Can we make the gateway timeout for workflow outcomes configurable in the request?

**Comment by npepinpe** [comment]
Isn't the gateway timeout calculated from the request timeout?

**Comment by jwulf** [comment]
With this parameter?

https://github.com/zeebe-io/zeebe/blob/develop/gateway-protocol/src/main/proto/gateway.proto#L121

**Comment by npepinpe** [comment]
Yes, this should control the timeout across the board.

**Comment by jwulf** [comment]
Can confirm that this works with the Node client:

```
const result = await this.zbc.createWorkflowInstanceWithResult({
      bpmnProcessId,
      variables: {
        instanceId,
        username,
      },
      requestTimeout: 120000,
    });
```
