### ISSUE TITLE
Event metadata should include event position

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#368]
When a client makes a request and receives a response event, it should be possible to inspect the position of the response.

**Comment by menski** [comment]
@ThorbenLindhauer can we close this ticket as the EventMetadata now contains the position?
https://github.com/zeebe-io/zeebe/blob/cd216531535cb2fb9e437074f144d9a29f3aee67/client-java/src/main/java/io/zeebe/client/event/EventMetadata.java#L34

**Comment by ThorbenLindhauer** [comment]
I think this is still valid. The API is there, but the returned value is the position of the request, not the response, if I remember correctly.

**Comment by menski** [comment]
Oh sorry I missed the part that you want the position of the response. :see_no_evil:

**Comment by ThorbenLindhauer** [comment]
No worries :)

**Comment by ThorbenLindhauer** [comment]
Closing this in favour of https://github.com/zeebe-io/zeebe/issues/374
