### ISSUE TITLE
Validate commands in broker

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#369]
For all event types, implement context-aware validation of command requests (e.g. version must be >= -1 when starting a new workflow instance).

Side note: we removed some client-side validation with https://github.com/camunda-zeebe/zeebe/issues/357 some there is not much validation at this point.

**Comment by ThorbenLindhauer** [comment]
There should be a generic command error event that should replace all the individual `*_REJECTED` states. That would make it easier to develop clients and broker. The response should include an error message and point to the command it is a follow-up to.

**Comment by menski** [comment]
Implemented in the mean time.
