### ISSUE TITLE
Return DEADLINE_EXCEEDED on Gateway transport timeout 

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3699]
**Description**

After migrating the transport module for the Gateway, the transport may now throw `TimeoutException`, which we return to the user as `INTERNAL` errors, when they should really be `DEADLINE_EXCEEDED`.

Current error message associated with the timeout is something like:

> java.util.concurrent.TimeoutException: Request type command-api-1 timed out in 45000 milliseconds

Not sure this is particularly useful for the user however. I think we can come up with a better error message that means something to the user (we can still log the original error for us).

**Comment by npepinpe** [comment]
:eyes: @Zelldon any ideas?

**Comment by jwulf** [comment]
Hahahahahahahahahahaha - https://github.com/zeebe-io/zeebe/issues/3675

Here is the error message that would have made it clear to me:

`The gateway timed out while waiting for broker response to command ${command}. The gateway timeout configured as ${ZEEBE_GATEWAY_TIMEOUT}`. Consider raising this timeout to a higher value if your request takes longer to complete.`

Especially now that we have awaitable outcomes, and given the current latency overhead of complex processes, I think users will hit this, and need a useful message.

Also: If we can't / until we do make the gateway timeout configurable in the request, we should raise the limit on Camunda Cloud from the 15s default.

**Comment by Zelldon** [comment]
Oh @josh i'm so sorry I thought about this this morning that this might be the issue. 🙈

**Comment by jwulf** [comment]
What's the implication of raising the gateway timeout? Does it tie up threads longer, potentially?

**Comment by npepinpe** [comment]
As far as I'm aware, the time out between the Gateway and the Broker is controlled by the request time out - the difference is that it includes times where the request may not have been sent (e.g. the topology doesn't know any brokers so until it gets one it will wait).
