### ISSUE TITLE
AtomixTransportTest#shouldOnInvalidResponseRetryUntilTimeout is flaky

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3703]
**Description**

`AtomixTransportTest#shouldOnInvalidResponseRetryUntilTimeout` sometimes fails with the following error:

```
Expecting:
 <1L>
to be greater than:
 <1L>
```

The test sends requests, and expects them to be retried on timeout. On receiving a request, it increments a `retries` counter. At the end of the test, it asserts one request was sent (blocks until it times out), then it asserts that counter is > 1 (e.g. at least one retry occurred).

Hypothesis is that there is a race condition, where one request is sent (so `retries` is 1), but the next assert happens before the retry is performed (as requests are sent async - otherwise we'd be in an endless loop). Using a latch instead of a counter would solve the issue.

**Comment by Zelldon** [comment]
Please see here https://github.com/zeebe-io/zeebe/pull/3620 :laughing:

**Comment by npepinpe** [comment]
My bad

**Comment by Zelldon** [comment]
Hey no problem :+1:
