### ISSUE TITLE
Follower join seems to trigger a new election 

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3705]
**Describe the bug**

While I was debugging the unstable `RestoreTest`, it seems the cause is due to a transition of the leader to follower while writing some commands - we send a create workflow request which is put on the dispatcher of the leader, but an election is triggered before it is written to the log, causing it to eventually time out and the test to fail.

The test essentially does this:

- Fill at least one segment
- Stop the leader and restart it (and make sure a new leader is elected)
- Fill at least another segment on the new leader

On the last step is where for some reason another election is triggered, and it seems to be immediately after the follower (that is, the previous leader) rejoined. We then see a few appends that failed, explaining the timed out command.

In production this can occur, and so by itself a time out is not a bug - but there should not be any more transitions, esp. in a test environment.

**To Reproduce**

Run the `RestoreTest#shouldKeepPositionsConsistent` in a loop until failure - it eventually happens. I could reproduce it fairly easily locally.

**Expected behavior**

Transitions do not occur in a test environment once everything is up and running.

NOTE: I'm tagging this as both Unstable and Bug, since I'm unsure on which side it falls =/

**Comment by Zelldon** [comment]
This blocks my current PR to merge and develop build seem also to fail because of this.

**Comment by Zelldon** [comment]
Do we have an fix for this?

Could it be that this issue is caused because of the bootstrap leader mechanic?

**Comment by npepinpe** [comment]
I have to apologize, I've been multi tasking too much :sweat_smile: 

I'm still not 100% sure what the issue is. The bootstrap leader mechanic is an interesting lead, I'll look into it. But if you're blocked you can take over, I didn't make any substantial progress here.

**Comment by Zelldon** [comment]
> I have to apologize, I've been multi tasking too much

No problem I know this too good :D 

I can try but need to some other things before.

**Comment by npepinpe** [comment]
I had a short look again at this, and I still don't know but made a bit of progress. Quick reminder, the set up is: 3 nodes (0, 1, 2), 1 partition, replication factor 3. Initially 0 is the leader for partition 1.

When restarting 0, on restart, it will start an election; 0 starts as BOOTSTRAP and goes to CANDIDATE, but on term 2 (which is the term after fail over), and all votes are rejected. It does this for both the system and the data partition. Seems safe-ish, as far as I can tell, but unnecessary - from the code it looks like we expected it would check if a leader is known but I guess it doesn't try to find a leader, or doesn't manage to figure out fast enough.

What happens later is that the other follower node (2) starts sending poll requests, and receives a majority response (probably from node 0 which has no leader for a while), and then starts an election with term 3. The question is why is node 2 sending poll requests at all if it has a leader? Did we get a new leader but we forgot to cancel the poll requests/the time out for the poll requests is too high?

**Comment by npepinpe** [comment]
Further updates:

It seems when the scheduled heartbeat timer is triggered, it will set `heartbeatTimeoutTimer` since it expects it to be done (so no need to cancel), but seems like sometimes it's a new timer already: possibly because we created the timer on a different thread and the scheduled callback is executed on. This results in us sometimes setting a running timer to `null` resulting in us not cancelling the timer, which can cause these weird elections - my guess is the election goes through because the member happens to poll the re-joining node which has no leader yet and thus agrees to an election.

**Comment by npepinpe** [comment]
Alright, so I think I figured out the root cause:

When the leader dies, the two remaining followers go into election due to heartbeat time outs. The problem is that once one of the two is elected, the other (which is still a follower) is stuck with a dangling scheduled timer, which is not cancelled, but is re-scheduling itself, so from time to time the `heartbeatTimerTimeout` will overwrite a scheduled value from the normal `resetHeartbeatTimeoutFromHeartbeatThread` way, which results in that one now being dangling, and results in its callback being executed even if we do receive heartbeats.

So we have a follower which might get stuck in a state where its sending poll requests every once in a while, which is sort of safe, except if a node is rejoining and responds to it before having a leader, resulting in an election being triggered and a new leader elected (since the remaining follower has a higher term than everybody).

**Comment by npepinpe** [comment]
Simple solution: use different timers for poll and heartbeat time outs, and make sure only one thread accesses one timer at a time, and cancelling the poll time out when a new leader is elected (since polling is triggered by heart beat time out no need to ensure we cancel the heart beat timer).

**Comment by npepinpe** [comment]
Latest proposal after some discussion:

We will serialize access to the heartbeat timer through the heartbeat thread. This means we remove the guard clause which lets only the leader schedule things on the heartbeat thread (not sure why we had a guard clause to prevent access to the heartbeat thread except from the leader? @Zelldon maybe you know), we schedule the time out callback on the heartbeat thread, and we schedule the poll timeout as well on the heartbeat thread (but the poll requests are still send on the raft thread). 

This makes sure we never have any dangling timers.

**Comment by npepinpe** [comment]
Related to [zeebe-io/atomix#139](https://github.com/zeebe-io/atomix/issues/139)

**Comment by npepinpe** [comment]
Should be solved by [zeebe-io/atomix#148](https://github.com/zeebe-io/atomix/pull/148)
