### ISSUE TITLE
RFE: Suppress llegal reflective access warning

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#3711]
At the moment (0.22.1), the following message appears when starting the broker:

```
zeebe_broker | WARNING: An illegal reflective access operation has occurred
zeebe_broker | WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/usr/local/zeebe/lib/kryo-4.0.2.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
zeebe_broker | WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil
zeebe_broker | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
zeebe_broker | WARNING: All illegal access operations will be denied in a future release
```

Can we suppress this message? According to [this comment](https://github.com/EsotericSoftware/kryo/issues/543#issuecomment-395959003) you can suppress it if you add the following to your JVM args `--add-opens=java.base/java.nio=ALL-UNNAMED`.

Since there is nothing for users to do about this, they don't need to see this in the logs.

**Comment by npepinpe** [comment]
Fair point, we can add that to our official dist.

**Comment by npepinpe** [comment]
So, it seems Kryo does a bunch more illegal reflection access. On the plus side, it also works without reflection (e.g. `--illegal-access=deny`), as it falls back to other mechanisms, but I'm not sure what the impact of doing so is.

**Comment by npepinpe** [comment]
I've pushed a branch where you can see the required modules; one other option is, like I said, to try with `illegal-access=deny`, but I'm not sure if that will cause performance issues (?). They already decided not to move to `Unsafe` (at least not in v4, which we use).
