### ISSUE TITLE
Race condition with snapshot replication

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3717]
**Describe the bug**

After taking a new snapshot, Zeebe will attempt to push it to all followers by using a simple async file replication mechanism. The problem with this is that at the same time we might attempt to compact our log - compacting the log results in Zeebe opening the snapshot again to read the latest processed position/latest exported position. When opened, a RocksDB snapshot has a few extra files which not only should not be replicated, but only exist when the snapshot is opened.

This means there's a race condition, where potentially we start replicating with X chunks (where the snapshot is currently opened), and as the snapshot is closed during replication, some of the files go missing, resulting in missing chunks on the follower side.

As stated in their FAQ:

> Q: Is it safe to directly copy an open RocksDB instance?
   A: No, unless the RocksDB instance is opened in read-only mode.

**To Reproduce**

The `ClusteredDataDeletionTest#shouldDeleteDataOnFollowers` test seems to fail fairly often, and seems to be related to this issue. As it's a race condition, reproducing this reliably in prod is a bit difficult, but in a test you can basically run it until failure, where we fail we wait for a snapshot to be replicated as it's basically waiting for a missing chunk.
 
**Expected behavior**

I expect snapshots to be reliably replicated, and different read-only accesses to an immutable snapshot to not interfere with each other.

**Comment by npepinpe** [comment]
Small update: the real issue with the test is that we do try to transmit the `LOCK` chunk, but as it has no contents, our code at the moment to serialize/deserialize cannot cope with it and explodes (silently :see_no_evil:), resulting in missing chunks.

So the immediate problem is we can't send empty files, and the more interesting problem is we should not be sending temporary files like the LOCK files; I'm actually unsure what the impact of sending a locked snapshot would be (can we even open it on the receiver side?).

**Comment by deepthidevaki** [comment]
> So the immediate problem is we can't send empty files, and the more interesting problem is we should not be sending temporary files like the LOCK files; I'm actually unsure what the impact of sending a locked snapshot would be (can we even open it on the receiver side?).

Does that explain corrupted snapshots that were observed before?

**Comment by npepinpe** [comment]
The one I observed was complaining about mismatched file lengths for some SST files, so probably not? Might explain it for others.

**Comment by Zelldon** [comment]
Why you can't just try to open it ? :sweat_smile: Why do you need read only feature for that?

**Comment by npepinpe** [comment]
Ok, I tested it out and it seems safe-ish to transfer LOCK files since RocksDB uses `flock` on the file in the end - it's just a place holder. So that it already exists is safe-ish since as long as no process has locked it it's not a problem.

It could still be an issue that we have multiple things trying to open it on the same node, as that will definitely explode. At the moment I think it's OK-ish because we control the order in which these happen: 

- Leader: take snapshot, then delete (again open the DB)
- Follower: replicate snapshot, then delete (again open the DB)

Seems brittle however, but I guess we can postpone the read only stuff.

**Comment by Zelldon** [comment]
Btw the snapshot is not opened at all right ? So we should not have a problem to replicate?

**Comment by npepinpe** [comment]
The deletion service opens the snapshot to delete, which might happen while we're replicating - but for replicating we don't open the snapshot so only one thing on the node is opening it.

**Comment by Zelldon** [comment]
Aaah ok thanks
