### ISSUE TITLE
Broker: Command responses should contain position of written event

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#374]
We added positions to command requests and responses in #370 and camunda-zeebe/tasks#35.

E.g. for a task CREATE event, the response should contain the position of the CREATED event (such that a client can base its next request on this and we can implement an optimistic-locking mechanism).

This is not trivial for two reasons:

* We currently send responses before we write to the log
* When we write to the log, the entry is not yet committed, so the returned position may not be durable

**Comment by ThorbenLindhauer** [comment]
The currently returned position is 0, so the API does not really work in any way.

**Comment by menski** [comment]
Positions are not exposed to the client anymore and are also not required anymore
