### ISSUE TITLE
Manipulate the time to trigger timer events in tests

### ISSUE THREAD

**Issue by VB9991** [zeebe-io/zeebe#3751]
I suppose it would be useful to be able to manipulate time to develop unit tests.
This will be especially useful for testing flow which contain timer event node.

Mr @saig0 said:  
> the clock util is currently not exposed in the zeebe-test module

I think it's necessary to add the ability to manipulate time.

[Linked discussion on Zeebe forum ](https://forum.zeebe.io/t/is-it-possible-to-simulate-a-timer-event/953)

**Comment by Fufusulier** [comment]
Hello,
any new regarding this? I need to test a workflow usin zeebe test 
![image](https://github.com/camunda/zeebe/assets/823294/da17ca3e-c0a8-4866-a63d-a3fa52d51534)

and it seems like even with hardcoded 1sec value the test doesn't pass
![image](https://github.com/camunda/zeebe/assets/823294/2a67c469-e364-4d14-800d-90b00df8a1ad)

even after waiting with Thread.sleep (what a savage)

![image](https://github.com/camunda/zeebe/assets/823294/9299e958-3304-4c05-b8bb-492df768b9a6)

Is there something specific to configure for timers in the contect of unit tests? All other tests in which I'm using the mocked zeebe client are working.

Thanks

**Comment by saig0** [comment]
Hey @Fufusulier, have a look at [Zeebe Process Test](https://docs.camunda.io/docs/next/apis-tools/java-client/zeebe-process-test/). The test framework allows to increase the time and trigger timer events (implicitly), see [here](https://github.com/camunda/zeebe-process-test/blob/main/api/src/main/java/io/camunda/zeebe/process/test/api/ZeebeTestEngine.java#L61).

**Comment by Fufusulier** [comment]
Ok, thank you. I wasn't aware that library existed.
