### ISSUE TITLE
Introduce new responses in java client

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3755]
**Description**

We should introduce new Response types for Commands, which currently just return `void`.
Even if this means introducing an empty interface, to be more future proven.

**Example**
```java

public interface ResolveIncidentCommandStep1 extends FinalCommandStep<Void> {
  // the place for new optional parameters
}

```

If we _now_ want to add a property in the response we need to change the response type from `Void` to a new response type. This will break the backwards compatibility. If we introduce an empty interface before hand, like:

```java

public interface ResolveIncidentCommandStep1 extends FinalCommandStep<ResolveIncidentResponse> {
  // the place for new optional parameters
}

public interface ResolveIncidentResponse {
  // the place for new properties
}

```

This would be backwards compatibility, example in the C# client https://github.com/zeebe-io/zeebe-client-csharp/blob/master/Client/Api/Commands/IResolveIncidentCommandStep1.cs

As reference see also the following discussion https://github.com/zeebe-io/zeebe/commit/35f17ad52e5b1645d678824f1b6a0712d2caa5ed#r37035500

If necessary we should split this in multiple issues. Feel free to challenge this.

AT:

 * all commands return an specific type, even if this is an empty interface
 * **Bonus**: all responses return at least the specific key

**Comment by pihme** [comment]
@Zelldon @npepinpe 
Hi guys,

I could use some guidance here. I pushed my work in progress to a branch. It doesn't compile yet, but it would be nice, if you could take a look at it, before I go too far astray.

So far, I mainly changed the code in a pattern matching way. There are some classes I am unsure about:
- I did rename _DeploymentEvent_ to _DeployWorkflowResponse_. I am still happy with that change overall
- by the same logic I did rename _WorkflowInstanceEvent_ to _CreateWorkflowInstanceResponse_, and -WorkflowInstanceResult_ to _CreateWorkflowInstanceWithResultResponse_  A bit unwieldy, but it is still consistent to the commands and even IMHO a little better than trying to figure out the difference between _WorkflowInstanceEvent_ and _WorkflowInstanceResult_ in the existing code.
- where I stopped the pattern renaming was at _Topology_. I could rename it, but it would sound weird. 

Please let me know what you think of the changes so far.

I think the general question is whether I should roll back some of the changes, or go ahead and make more changes. And in both cases, which direction I should take.

There are some other points "alongside the road":
- _WorkflowInstanceResult_ should IMHO extend from _WorkflowInstanceEvent_ given that it supposedly adds additional fields
- _TopologyRequest_ is the only class without a verb and without a command in its name. If this is deliberate (in the sense of query/command/event topology), maybe this could warrant a package _requests_ if we imagine we will have other requests in the future
- I did notice that the factory methods _newCreateInstanceCommand()_ and _newCancelInstanceCommand()_ in _ZeebeClient_ don't match the class names precisely _Create/Cancel*Workflow*InstanceCommand_. Maybe it is obvious from the context that this is about workflow instances. But having used one of the Camunda APIs as part of the coding challenge myself recently, I remember that I was very confused about all the different instances there are - at least in the Camunda BPM tool

Anyways, I would appreciate it, if you could add your two cents to this.

**Comment by Zelldon** [comment]
Hey Peter I will try to answer when I have time just two cents😃

About the inheritance thing:

We normally avoid inheritance and favor composition. I get the point that it make sense were you just add properties, but if you introduce a hierarchy you always been limited more then if you just use composition. Example would be if you want to add a property which only makes sense in the WorkflowInstanceResponse but you dont want to have it in the other *Result. I think you can discuss it with the team and decide. Nicolas and Phillip have probably also an opinion on this.

> I did notice that the factory methods newCreateInstanceCommand() and newCancelInstanceCommand() in ZeebeClient don't match the class names precisely Create/CancelWorkflowInstanceCommand.

I get the point and like it 👍, but I think for that we should create a separate issue. In this issue we can then discuss if we want to do it and when, because this will be a breaking change and it is probably out of scope of this current issue here.

**Comment by npepinpe** [comment]
@pihme All good points as far as I'm concerned. I'm also unsure about the inheritance part - I'd rather have a little bit of duplication, I'm unsure what we gain by having these interfaces extend each other (but admittedly it's been a while since I had anything to do with the client API so it might be more obvious than I remember).

I would also vote that we keep this issue simple and to the point, and we create a separate issue to align the command creation names with the request/response types.

**Comment by pihme** [comment]
New issue for naming consistency created as #3819
