### ISSUE TITLE
I can fail a job without activating it

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3757]
**Is your feature request related to a problem? Please describe.**
When the processing of a job fails in a worker then it sends a `fail` command to report the failure. If the job is not activated anymore (because the job timeout is reached) then the command is rejected. So, the job needs to be processed again.   

**Describe the solution you'd like**
I can fail a job even if it is not activated anymore.

**Describe alternatives you've considered**
I need to activate the job again (the current behavior).

**Additional context**
Job `complete` and `throw error` commands are accepted if the job is not activated. All these commands should be handled in the same way.

**Comment by Zelldon** [comment]
related/ might have impact on this https://github.com/zeebe-io/zeebe/issues/3409

**Comment by Zelldon** [comment]
related also to https://github.com/zeebe-io/zeebe/issues/2600
