### ISSUE TITLE
Zeebe Community License questions and clarifications

### ISSUE THREAD

**Issue by datocrats-org** [zeebe-io/zeebe#3770]
I cannot seem to find a similar license to your own.  I do not understand its intent and have several questions of what would be permissible. 

1. Can you provide some examples of what is and is not proper?  
2. Can you include the "stubs for the protocol" from the Readme.md in the license somehow?
3. Can you clarify some semantics and help define specific verbs "enable" and "access"
- "enabling" vs. "allowing"

  - If a derivative work _assists or instructs_ a client how to connect the derivative work to a version of the Zeebe Software the _client itself controls_?  In this example, I want to provide instructions on how to run a docker container that can send and receive instructions over the client's own network and infrastructure.

- "access"[ing] vs. "forwarding and receiving commands to and from"
  - Wouldn't remote procedural calls to and from the Software via its APIs that are activated through an intermediary be permitted, in that no access is directly provided?

> A "Commercial Workflow Service" is a service intended for or directed towards
> commercial advantage or monetary compensation for the provider of the service
> **enabling** third parties (other than the provider’s employees or Contractors) to
> deploy and execute Custom Workflows or to access the Software via its APIs.

4. Would it be permissible for the derivative work's authors to "allow third parties to execute a pre-defined programmatic services made available by" **a third party** instead of the "Commercial Workflow Service"? 

> "Custom Workflows" means workflow descriptions contained in BPMN or similar
> configuration files, that specify the logic for executing programmatic
> services, such that third parties can define these programmatic services freely
> (as opposed to selecting them from a restricted set of pre-defined programmatic
> services made available by the provider of the Commercial Workflow Service).

The use case I am considering is essentially a "stub for the protocol."  It would be container-based and rely on individual company's own client (peer) devices to provision the Zeebe Software on containers running in the client's own environments or clouds of choice.  My derivative work would permit users to forward copies of their BPMN designs to a shared channel, provide copies of those instances to other client peers.  All peers would run the zeebe independently and then only share _inputs, outputs, and errors_ or _modifications to the BPMN process_ with each other.  In summary, any client is its own author and executor, but they can propose new workflows to be included in a repo then share results.

**Comment by jwulf** [comment]
It is to stop a cloud provider from providing it as a commodity service. Mongo, Elastic, Confluent and others have similar licenses to stop being consumed by, let’s be honest, Amazon. 

As long as you build some software with it, you’ll be fine. If you offer it as-is as a service, that it will violate the license. 

See these discussions: 

* https://zeebe.buzzsprout.com/454051/1445587-zeebe-and-open-source-with-daniel-meyer
* https://forum.zeebe.io/t/about-zeebe-community-license-1-0/901


I’m not sure I understand your proposed use-case, so I can’t comment on whether it meets the license conditions. @meyerdan is the best person to assess this, or put you in touch with someone who can.

**Comment by Zelldon** [comment]
I assume we can close this. If you have any further questions or comments regarding this topic feel free to re-open it.
