### ISSUE TITLE
Official dockerized zbctl image

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3782]
**Is your feature request related to a problem? Please describe.**

The official Docker image contains `zbctl`, but it's rather large if all you'd want to use is `zbctl`. It should be trivial to release a standalone `zbctl` docker image as part of our release pipeline.

**Describe the solution you'd like**

- there exists a standalone `camunda/zbctl:<VERSION>` image which follows the same versioning pattern as our releases
- on a new release, we build and push the new image
- the image should be as small as possible and be cloud-compatible (e.g. contain ca certificates)

**Describe alternatives you've considered**

- Build zbctl locally (most devs will already be doing this)
- Use the official `camunda/zeebe` image - also feasible

**Additional context**

I already have a `Dockerfile.zbctl` which can build an image from local code such that you can run it as:

```shell
$> docker run camunda/zbctl status --address ${address} --clientId ${clientId} --clientSecret ${clientSecret}
Cluster size: 1
Partitions count: 2
Replication factor: 1
Gateway version: unavailable
Brokers:
  Broker 0 - zeebe-0.totally-not-shady-cluster.org:26501
    Version: unavailable
    Partition 1 : Leader
    Partition 2 : Leader
```
The file is meant to live under `clients/go` directly and be built from there:

```Dockerfile
FROM golang:1.13.7-alpine3.11 as builder
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates

# Prepare source
RUN mkdir -p /src/dist
ADD . /src
WORKDIR /src

# Prepare go mod
RUN go mod download
RUN go mod verify

# Build our binary
WORKDIR /src/cmd/zbctl
RUN GO111MODULE=on CGO_ENABLED=0 go build -mod=vendor -a -tags netgo -ldflags '-s -w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands.Version=development' -o ./dist/zbctl ./main.go

# Build the final container. Use scratch as the smallest possible container
FROM scratch

# Add in certs
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Add the binary
COPY --from=builder /src/cmd/zbctl/dist/zbctl .

# Run it
ENTRYPOINT [ "./zbctl" ]
```

**Comment by npepinpe** [comment]
@jwulf if you try this before https://github.com/zeebe-io/zeebe/pull/3781 then it won't work yet, but with that fix I tested that the image works perfectly both locally (so without TLS) and with the cloud (with TLS)

**Comment by jwulf** [comment]
You can also `npm i -g zbctl` at the moment.

**Comment by npepinpe** [comment]
To be revisited if we ever split the clients from the core distribution.
