### ISSUE TITLE
Zeebe Elasticsearch index names contain version number

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#3785]
**Is your feature request related to a problem? Please describe.**

The Zeebe records exporter into elasticsearch have a strict type mapping. During the evolution of Zeebe this data schema might change. Do enable Zeebe to continue exporting without migration downtime we will include the Zeebe version into the schema index names.

**Describe the solution you'd like**

The Zeebe elasticsearch exporter creates schema templates that contain the Zeebe version and exports to them accordingly. There is no data migration needed when upgrading Zeebe.

**Describe alternatives you've considered**

- Having a dynamic schema in elasticsearch which would allow adding new fields, downside the type is guessed by Elasticsearch and it's not clear for a consumer which schema to expect
- Migrating data when upgrading Zeebe, still would require multiple indexes (i.e. different names) and additionally leads to longer downtime of a broker and decided when to upgrade data is complex a Zeebe exporters are distributed through the whole cluster

**Additional context**
- Broker version is already available https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/Broker.java#L79
- We could add the version to the exporter context to make it available to exporters in general https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/exporter/context/ExporterContext.java
- Encoding of the schema version should be in the same way as we did it in Operate
- We can discuss if we should include the version through a properties file instead of the implementation version https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/Broker.java#L78, but we should do this in another issue

**Comment by sdorokhova** [comment]
Discussed the source of the version once again and decided:
* within #3793 `VersionUtil` class was created in `zeebe-util` module that return current Zeebe version
* we can use this class directly from exporter, as Elasticsearch exporter version will always be aligned with other Maven  module versions (in out case with `zeebe-util` module)
