### ISSUE TITLE
Broker losses leadership when receiving a bigger number of request

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#380]
### Scenario

- 3 brokers
- NonBlockingTaskCreator with 1.000.000 request

### Observation

After around 8 minutes one of the follower starts a poll/vote cycle and wins the election. This should not happen as the leader is still alive and should be able to handle the number of requests and still send append requests.

### Possible Explanations

- the replicate log controller of raft is not invoked often enough to not trigger a election timeout
- the append requests are not successfully delivered to the followers, this could be a similar issue we sometimes see in the raft test suite (https://github.com/zeebe-io/zb-raft/issues/1) where join requests are not received from the leader

**Comment by meyerdan** [comment]
Let's close in favor of #758
