### ISSUE TITLE
Define the job retries statically or as expression

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3803]
**Is your feature request related to a problem? Please describe.**
For a service task, I can define the `retries` as a number or dynamically as an expression.

**Describe the solution you'd like**
Same as in #3792.

**Comment by pihme** [comment]
@saig0 This would require a change to `.ZeebeTaskDefinition`. Is this ok?

**Comment by saig0** [comment]
Yes :+1: You need to change the type from `Integer` to `String` (`integerAttribute` to `stringAttribute`) in order to support expressions.
