### ISSUE TITLE
Find alternative tool to convert Go test output to XML

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3807]
**Description**

The tool we're currently using to convert Go test output to XML has been showing some limitations, namely it removes the plus and minus signs of diffs (https://github.com/jstemmer/go-junit-report/issues/95) and it completely mangles the output when a panic occurs. These issues make it difficult to understand test results. For instance, the panic output issue made it hard to understand the source of this issue #3641.
Since `go test` has an option to output JSON, there's probably a better alternative that converts the JSON to the XML we need to display test results in Jenkins. This tool https://github.com/gotestyourself/gotestsum might be an alternative.

**Comment by npepinpe** [comment]
Related: https://github.com/jstemmer/go-junit-report/issues/28

That explains why we were getting this "Failed" message with nothing else :eyes: 

Related to #3641
