### ISSUE TITLE
Align bpmn xml handling in client API

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#382]
At some parts of the API the BPMN XML is handed out as byte[] at another as String. See

https://github.com/zeebe-io/zeebe/blob/master/client-java/src/main/java/io/zeebe/client/workflow/impl/DeploymentEventImpl.java#L43
vs
https://github.com/zeebe-io/zeebe/blob/master/client-java/src/main/java/io/zeebe/client/event/impl/WorkflowEventImpl.java#L74

This should be aligned.

**Comment by Zelldon** [comment]
this is outdated
