### ISSUE TITLE
Google Pub/Sub Connect

### ISSUE THREAD

**Issue by jbeaudoin11** [zeebe-io/zeebe#3826]
**Is your feature request related to a problem? Please describe.**
We are currently evaluating Zeebe for our serverless orchestration on Google Cloud Platform. I'm surprised to see a Kafka connector, but not a Google Pub/Sub one...

**Describe the solution you'd like**
I would like to be able to use Google Pub/Sub as a source and sink.

**Describe alternatives you've considered**
Kafka is not an option, we don't have the resources to maintain it.
We want something managed.

We could use http/https but would rather have the ability to make this async as much as possible

**Additional context**
If it's not possible to have something "fast", maybe we can make one our self.
We can use the kafka-connect-zeebe project as reference.

**Comment by saig0** [comment]
Hi @jbeaudoin11,

at the moment, we have no plans to build an official exporter/connector for Google pub/sub. But this sounds like a great community project :+1: 

The Zeebe Kafka connect project is a good reference or have a look at other community exporters/projects: https://github.com/zeebe-io/awesome-zeebe#exporters

If you have questions or need help then just ask in the forum or Slack :)
