### ISSUE TITLE
Health status of a Zeebe cluster

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3835]
**Description**

This is a catch all issue to break down and track progress of the requested health check endpoint feature #2484 

##### Health check for a broker
A zeebe broker is healthy when it is functioning as expected. If the broker is the leader for a partition, it can accept requests and process workflows. If the broker is a follower for a partition, it is replicating the state and is capable of becoming leader in case of a fail-over. 

To expose the health status of a broker, we will have 

1. A health monitor in a broker that monitors each partition and aggregates the status (https://github.com/zeebe-io/zeebe/issues/3832). 
2. Each partition monitors the relevant components in a hierarchical manner. Each component decides for itself what it is meant to be healthy.
- [x]  Raft Partition (#3853 )
- [ ]  LogStream
   - [x] LogStorageAppender (#4000)
   - [ ] Dispatcher
- [x] StreamProcessor (#3854 )
- [ ] Exporter
- [ ] Snapshot director
-  and more
3. An http endpoint that exposes the health status of the broker. In the first iteration we will have only two levels - healthy or failed (https://github.com/zeebe-io/zeebe/issues/3833)
   -  Later we can add more levels to the health status indicating different levels of partial failures  
   -  Also later, it would be interesting to expose more details such as which component/partition failed

4. Also expose the health status of partitions via prometheus metrics (https://github.com/zeebe-io/zeebe/issues/3834)

##### Health check for a gateway
TBD if gateway needs a complex health check. For now, gateway is healthy if it is up and accepting requests.

##### Health check for the cluster
A cluster is healthy when all brokers are healthy and there are leaders for all partitions. Note that a cluster can be in a partial healthy state where there are partial failures which does not immediately affect the user experience. It may or may not leads to a catastrophic failures later. Hence it would be interesting to add multiple levels of health status. 

- Exposes the overall health of the cluster via a query to gateway similar to `zbctl status`

**Comment by npepinpe** [comment]
Closed as done for now, we should extend the health check as we work on other components.
