### ISSUE TITLE
Add configuration classes for backpressure configuration

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#3843]
**Description**

The backpressure configuration is currently done through env variables. This issue is about adding full-fledge configuration objects for these settings.

* Move `BackPressureCfg` into `Logstream` module
* Extend it so that it covers all settings for the existing algoithms
  - tbd shall we spell all settings out, or shall we use a general map style approach
* Clear up confusion about whether we have two algorithms or three
* Expand validation logic for backpressure coniguration
* Make `LogStorageAppender` respect the configuration

**Comment by menski** [comment]
BackPressureCfg is the command API backpressure, whereas the env variables are related with the log storage append backpressure (see https://github.com/zeebe-io/zeebe/pull/3309). As far as I remember we decided to not expose the cfg for the log storage appender back pressure. @Zelldon can you confirm?

**Comment by Zelldon** [comment]
The problem we had before was that the LogStorage, the Backpressure and the related cfg was created inside the Distributed Primitve, which had no access to the broker or other related stuff. Dependency injection was also not possible. This was the reason why we where not able to make it public and just created Env variables for that, as far as I remember.

Would be nice if we can configure it now also from the BrokerCfg, but this is probably only for testing purposes helpful. I think it makes sense to not make it more public as it needed.

**Comment by pihme** [comment]
If we add it to the `BrokerCfg` as part of the object structure, it will be hard to hide it from qualified eyes.

E.g. the broker prints out its configuration at startup and it looks like it just dumps the `BrokerCfg` as Json. So if it becomes part of it, it will also become visible

**Comment by pihme** [comment]
Won't do for now. Might be addressed in the future
