### ISSUE TITLE
Document Grafana dashboard panels

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3848]
**Description**

The current Grafana dashboard works well, but it is not obvious how to interpret each panel. While it's meant to serve a springboard for users to build their own dashboards, it's also used internally by the Zeebe team, and having non-documented panels leads to:

1. Steeper learning curve to onboard new developers
1. Older members have to still edit the panel to figure out what is the data if they were not involved in the addition of the panel/metric

It's possible in Grafana to add help information to the dashboards, so the first step should be to do this for all panels. If we need more complete documentation, the next step would be to add it as part of the monitor `README.md` file.

**Comment by falko** [comment]
I indeed have a couple of customer questions about the Grafana dashboard and would be happy to contribute to the documentation if I would only have the answers ;-)

What does “Partition health” mean, i.e. which checks are behind it, and should one be alarmed if it's unhealthy?

What exactly are:

- Number of records not processed
- Append Backpressure: Inflight-for, try-to-append, deferred, queue-limit
- Command API Backpressure: inflight, received, dropped, queue-limit
- Number of records exported but not acknowledged

**Comment by Zelldon** [comment]
Maybe we can sit together @falko and just do it together in an afternoon or so :)

**Comment by npepinpe** [comment]
I would close this for now - I think in the future the Grafana dashboard should be part of the public API, and as a rule we should always document it as much as possible in the dashboard itself (for the team), but in the official documentation I would wait for product to push for it.
