### ISSUE TITLE
Integrate Atomix into Zeebe Repository

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3855]
**Is your feature request related to a problem? Please describe.**

I would like to move our current atomix fork into the Zeebe repository.
This makes it easier to maintain the project, since we do not need to open and work on different Intellij projects and it is closer to our project.
This makes it easier to release our project, since we do not need to release atomix before. We can integrated easier in our release cycle. 
This makes it easier to apply checkers, development rules or code rules to atomix. Like checkstyle, spotbugs, sonar etc.

**Describe the solution you'd like**

I would like to remove everything from the atomix project, which we don't use and need. 
I would like to migrate the remaining source to java 11. 
I would like to reformat the code based on our codestyle.
I would like to check the source code for source flaws, bugs and fix them.

I think each of these things can be done in separate issues.
We probably need to think of re-licensing the code as well?

**Describe alternatives you've considered**
Keep it like it is, but it annoys me..:sweat_smile:

@npepinpe @menski @deepthidevaki Would like to hear your opinion on that.

**Comment by npepinpe** [comment]
I agree, I'd also like for this to be a long term goal.

First step would be reducing the dependency surface. I think https://github.com/zeebe-io/atomix/issues/52 would be a good first step - if we can remove the system partition, then we can move on to https://github.com/zeebe-io/atomix/issues/39 or similar, that is, essentially rewrite the partitioning service to have no dependency on anything but Raft and Cluster. At this point we can have complete control over the Atomix start up process and can implement something similar to https://github.com/zeebe-io/atomix/issues/45. At that point, we should be dependent purely on cluster, raft, and utils, so we can bring that all back into the repo, reformat (https://github.com/zeebe-io/atomix/issues/43), and integrate it better (and eventually implement something for https://github.com/zeebe-io/atomix/issues/44).

I'm not sure we need to relicense existing code, or that we even can?

**Comment by Zelldon** [comment]
I see no problem in doing this (removing system partition) after we moved it in our repo to be honest :slightly_smiling_face: 

> I'm not sure we need to relicense existing code, or that we even can?

Not sure. Probably we need to discuss this with legal? 
I mean our current build would fail at least we need to adjust the licence check somehow. New resources at least need to have our license header probably.

**Comment by npepinpe** [comment]
> I see no problem in doing this (removing system partition) after we moved it in our repo to be honest

I was trying to keep what we move in to a minimum, if we move it in as is, then we will still have the primitive module and so on, right? That's quite a lot of added code :s

**Comment by Zelldon** [comment]
It is done.
