### ISSUE TITLE
Place data directory in distribution outside of bin folder

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#387]
At the moment the configuration included in the distribution creates the data directory where the broker is started. If I remember correctly you can only start the broker from inside the bin directory as its expects the configuration to be placed under `../conf`. Therefore the data directory containing the log, metadata etc. is created inside the bin folder, which could surprise the user as its not common.

**Comment by meyerdan** [comment]
Yes, also, we built this feature for specifying the folder where to place all data with one config entry. I think we called it "global" configuration. We are not using this currently in the distribution and we probably shoul.
