### ISSUE TITLE
Upgrade to Go 1.14

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#3881]
**Description**

This issue is a bit premature since Go 1.14 hasn't even been released yet but I wanted to write down a few things that can be improved which are related to the release. When the release comes out, I'll link to the appropriate sources.

* When the main module contains a top-level `vendor` directory, go defaults to `-mod=vendor` so we can remove it from all the scripts
* The testing package now supports cleanup functions. I'm not sure we need this but it might be an opportunity to have another look into the way our tests are setup. We use a lot of suites but I think they are unnecessary for most tests, except for integration tests where we actually keep state. For instance, the environment suite is useful but it forces us to create new suites for each class and use struct composition. It might be simpler and more explicit to just do:

```go
environ := env.copy()
defer env.overwrite(environ)
```

**Comment by Zelldon** [comment]
Go 1.14 was released on 25 February 2020 https://blog.golang.org/go1.14

**Comment by npepinpe** [comment]
Let's check if it's possible to upgrade to 1.15, and see what the blockers are - as for new features, we can discuss each separately if they make sense.

**Comment by npepinpe** [comment]
Please update to 1.15 :+1:
