### ISSUE TITLE
DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#3904]
### Description
The test failed with a timeout; at a subsequent run the test succeeded.

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
	at app//io.zeebe.broker.it.clustering.ClusteringRule.createGateway(ClusteringRule.java:312)
	at app//io.zeebe.broker.it.clustering.ClusteringRule.before(ClusteringRule.java:187)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
```

The following tests were failing at the same time:

```
    Test (Java) / io.zeebe.broker.it.client.command.CompleteJobTest.shouldRejectIfVariablesAreInvalid
    Test (Java) / io.zeebe.broker.it.clustering.BrokerLeaderChangeTest.shouldBecomeFollowerAfterRestartLeaderChange
    Test (Java) / io.zeebe.broker.it.clustering.DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances
    Test (Java) / io.zeebe.broker.it.clustering.GossipClusteringTest.shouldRemoveMemberFromTopology
    Test (Java) / io.zeebe.test.UpgradeTest.shouldCompleteJobAfterUpgrade
    Test (Java) / io.zeebe.test.UpgradeTest.shouldSupportOlderVersionedGateway
```

<summary>Full Log</summary><details><pre>
14:55:44.996 [] [main] INFO  io.zeebe.test - Test started: shouldDeployWorkflowAndCreateInstances(io.zeebe.broker.it.clustering.DeploymentClusteredTest)
14:55:45.002 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27888 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=89}
14:55:45.002 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27889 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=90}
14:55:45.002 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27890 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=91}
14:55:45.002 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27891 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=92}
14:55:45.003 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27892 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=93}
14:55:45.003 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/junit14082561996543249393/0
14:55:45.004 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27893 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=94}
14:55:45.004 [] [Thread-2268] INFO  io.zeebe.broker.system - Version: 0.23.0-SNAPSHOT
14:55:45.004 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27894 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=95}
14:55:45.005 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27895 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=96}
14:55:45.005 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27896 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=97}
14:55:45.005 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27897 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=98}
14:55:45.005 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/junit14082561996543249393/1
14:55:45.006 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27898 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=99}
14:55:45.006 [] [Thread-2268] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "0.0.0.0",
      "port": 27890,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27890
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "0.0.0.0",
      "port": 27891,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27891
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "0.0.0.0",
      "port": 27892,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27892
    }
  },
  "cluster": {
    "initialContactPoints": [],
    "partitionIds": [
      1,
      2,
      3
    ],
    "nodeId": 0,
    "partitionsCount": 3,
    "replicationFactor": 3,
    "clusterSize": 3,
    "clusterName": "zeebe-cluster-4",
    "gossipFailureTimeout": 2000,
    "gossipInterval": 150,
    "gossipProbeInterval": 250
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/tmp/junit14082561996543249393/0/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "test-recorder",
      "className": "io.zeebe.test.util.record.RecordingExporter"
    }
  ],
  "gateway": {
    "enable": false,
    "network": {
      "host": "0.0.0.0",
      "port": 27888,
      "minKeepAliveInterval": "30s"
    },
    "cluster": {
      "contactPoint": "0.0.0.0:27891",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 27889
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "0.0.0.0",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  },
  "stepTimeout": "5m"
}
14:55:45.006 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27899 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=100}
14:55:45.006 [] [Thread-2273] INFO  io.zeebe.broker.system - Version: 0.23.0-SNAPSHOT
14:55:45.006 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler
14:55:45.006 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27800 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=101}
14:55:45.006 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27801 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=102}
14:55:45.006 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27802 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=103}
14:55:45.006 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/junit14082561996543249393/2
14:55:45.007 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler started in 1 ms
14:55:45.007 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol
14:55:45.012 [] [Thread-2273] INFO  io.zeebe.broker.system - Starting broker 1 with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "0.0.0.0",
      "port": 27895,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27895
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "0.0.0.0",
      "port": 27896,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27896
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "0.0.0.0",
      "port": 27897,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27897
    }
  },
  "cluster": {
    "initialContactPoints": [
      "0.0.0.0:27891"
    ],
    "partitionIds": [
      1,
      2,
      3
    ],
    "nodeId": 1,
    "partitionsCount": 3,
    "replicationFactor": 3,
    "clusterSize": 3,
    "clusterName": "zeebe-cluster-4",
    "gossipFailureTimeout": 2000,
    "gossipInterval": 150,
    "gossipProbeInterval": 250
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/tmp/junit14082561996543249393/1/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "test-recorder",
      "className": "io.zeebe.test.util.record.RecordingExporter"
    }
  ],
  "gateway": {
    "enable": false,
    "network": {
      "host": "0.0.0.0",
      "port": 27893,
      "minKeepAliveInterval": "30s"
    },
    "cluster": {
      "contactPoint": "0.0.0.0:27896",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 27894
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "0.0.0.0",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  },
  "stepTimeout": "5m"
}
14:55:45.013 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [1/10]: actor scheduler
14:55:45.013 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27803 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=104}
14:55:45.013 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27804 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=105}
14:55:45.013 [] [Thread-2278] INFO  io.zeebe.broker.system - Version: 0.23.0-SNAPSHOT
14:55:45.013 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [1/10]: actor scheduler started in 0 ms
14:55:45.013 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [2/10]: membership and replication protocol
14:55:45.014 [] [Thread-2273] DEBUG io.zeebe.broker.clustering - Member 1 will contact node: 0.0.0.0:27891
14:55:45.014 [] [Thread-2278] INFO  io.zeebe.broker.system - Starting broker 2 with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "0.0.0.0",
      "port": 27800,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27800
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "0.0.0.0",
      "port": 27801,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27801
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "0.0.0.0",
      "port": 27802,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 27802
    }
  },
  "cluster": {
    "initialContactPoints": [
      "0.0.0.0:27891"
    ],
    "partitionIds": [
      1,
      2,
      3
    ],
    "nodeId": 2,
    "partitionsCount": 3,
    "replicationFactor": 3,
    "clusterSize": 3,
    "clusterName": "zeebe-cluster-4",
    "gossipFailureTimeout": 2000,
    "gossipInterval": 150,
    "gossipProbeInterval": 250
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/tmp/junit14082561996543249393/2/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "test-recorder",
      "className": "io.zeebe.test.util.record.RecordingExporter"
    }
  ],
  "gateway": {
    "enable": false,
    "network": {
      "host": "0.0.0.0",
      "port": 27898,
      "minKeepAliveInterval": "30s"
    },
    "cluster": {
      "contactPoint": "0.0.0.0:27801",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 27899
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "0.0.0.0",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  },
  "stepTimeout": "5m"
}
14:55:45.014 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [1/10]: actor scheduler
14:55:45.015 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [1/10]: actor scheduler started in 1 ms
14:55:45.015 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [2/10]: membership and replication protocol
14:55:45.015 [] [Thread-2278] DEBUG io.zeebe.broker.clustering - Member 2 will contact node: 0.0.0.0:27891
14:55:45.017 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol started in 10 ms
14:55:45.017 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport
14:55:45.018 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [2/10]: membership and replication protocol started in 5 ms
14:55:45.018 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [3/10]: command api transport
14:55:45.019 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [2/10]: membership and replication protocol started in 4 ms
14:55:45.019 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [3/10]: command api transport
14:55:45.019 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27890 
14:55:45.020 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport started in 2 ms
14:55:45.020 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler
14:55:45.020 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler started in 0 ms
14:55:45.020 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api
14:55:45.020 [] [Thread-2268] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api started in 0 ms
14:55:45.020 [] [Thread-2268] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services
14:55:45.022 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27895 
14:55:45.022 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [3/10]: command api transport started in 4 ms
14:55:45.022 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [4/10]: command api handler
14:55:45.023 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [4/10]: command api handler started in 1 ms
14:55:45.023 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [5/10]: subscription api
14:55:45.023 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27800 
14:55:45.023 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [3/10]: command api transport started in 4 ms
14:55:45.023 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [4/10]: command api handler
14:55:45.023 [] [Thread-2273] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [5/10]: subscription api started in 0 ms
14:55:45.023 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [4/10]: command api handler started in 0 ms
14:55:45.023 [] [Thread-2273] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [6/10]: cluster services
14:55:45.023 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [5/10]: subscription api
14:55:45.024 [] [Thread-2278] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [5/10]: subscription api started in 0 ms
14:55:45.024 [] [Thread-2278] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [6/10]: cluster services
14:55:45.024 [] [atomix-0] WARN  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Failed to locate management group via bootstrap nodes. Please ensure partition groups are configured either locally or remotely and the node is able to reach partition group members.
14:56:20.569 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:56:20.569 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:56:46.991 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:56:46.991 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:56:59.745 [] [raft-server-1-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:56:59.745 [] [raft-server-2-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:07.581 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:07.581 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:10.589 [] [raft-server-2-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:10.589 [] [raft-server-1-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:26.205 [] [raft-server-2-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:35.837 [] [raft-server-2-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:43.311 [] [raft-server-2-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
14:57:44.033 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.util.concurrent.TimeoutException: Request type system-partition-1-vote timed out in 5000 milliseconds
</pre></details>

**Comment by pihme** [comment]
@npepinpe Created this issue when you asked for team members to create unstable test issues a while ago. I haven't observed this test being flaky in a while; please close if you believe it is resolved

**Comment by npepinpe** [comment]
See https://github.com/zeebe-io/zeebe/issues/3906#issuecomment-603948295
