### ISSUE TITLE
CompleteJobTest.shouldRejectIfVariablesAreInvalid flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#3906]
### Description 
The test failed with a timeout; at a subsequent run the test succeeded.

Stacktrace:
<pre>
io.zeebe.client.api.command.ClientStatusException: deadline exceeded after 9.999644729s. [remote_addr=0.0.0.0/127.0.0.1:29800]
	at io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.zeebe.broker.it.util.GrpcClientRule.createWorkflowInstance(GrpcClientRule.java:188)
	at io.zeebe.broker.it.util.GrpcClientRule.lambda$createJobs$7(GrpcClientRule.java:141)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.zeebe.broker.it.util.GrpcClientRule.createJobs(GrpcClientRule.java:142)
	at io.zeebe.broker.it.util.GrpcClientRule.createSingleJob(GrpcClientRule.java:122)
	at io.zeebe.broker.it.util.GrpcClientRule.createSingleJob(GrpcClientRule.java:113)
	at io.zeebe.broker.it.client.command.CompleteJobTest.init(CompleteJobTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.999644729s. [remote_addr=0.0.0.0/127.0.0.1:29800]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 61 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.999644729s. [remote_addr=0.0.0.0/127.0.0.1:29800]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$1CloseInContext.runInContext(ClientCallImpl.java:416)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

The following tests were failing at the same time:
<pre>
    Test (Java) / io.zeebe.broker.it.client.command.CompleteJobTest.shouldRejectIfVariablesAreInvalid
    Test (Java) / io.zeebe.broker.it.clustering.BrokerLeaderChangeTest.shouldBecomeFollowerAfterRestartLeaderChange
    Test (Java) / io.zeebe.broker.it.clustering.DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances
    Test (Java) / io.zeebe.broker.it.clustering.GossipClusteringTest.shouldRemoveMemberFromTopology
    Test (Java) / io.zeebe.test.UpgradeTest.shouldCompleteJobAfterUpgrade
    Test (Java) / io.zeebe.test.UpgradeTest.shouldSupportOlderVersionedGateway
</pre>

<summary>Full Log</summary>
<details><pre>
14:50:42.278 [] [main] INFO  io.zeebe.test - Test finished: shouldCompleteJobWithoutVariables(io.zeebe.broker.it.client.command.CompleteJobTest)
14:50:42.278 [] [main] INFO  io.zeebe.test - Test started: shouldRejectIfVariablesAreInvalid(io.zeebe.broker.it.client.command.CompleteJobTest)
14:50:48.441 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithoutVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithoutVariables after timeout of PT10S
14:50:48.441 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobNullVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobNullVariables after timeout of PT10S
14:50:48.447 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithVariables after timeout of PT10S
14:50:58.284 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldRejectIfJobIsAlreadyCompleted","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldRejectIfJobIsAlreadyCompleted after timeout of PT10S
14:50:58.447 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobNullVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobNullVariables after timeout of PT10S
14:50:58.560 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithVariables after timeout of PT10S
14:51:02.426 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithoutVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithoutVariables after timeout of PT10S
14:51:08.328 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldRejectIfJobIsAlreadyCompleted","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldRejectIfJobIsAlreadyCompleted after timeout of PT10S
14:51:08.464 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobNullVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobNullVariables after timeout of PT10S
14:51:08.675 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithVariables after timeout of PT10S
14:51:15.906 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithoutVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithoutVariables after timeout of PT10S
14:51:18.412 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldRejectIfJobIsAlreadyCompleted","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldRejectIfJobIsAlreadyCompleted after timeout of PT10S
14:51:18.476 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobNullVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobNullVariables after timeout of PT10S
14:51:18.795 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"job-shouldCompleteJobWithVariables","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type job-shouldCompleteJobWithVariables after timeout of PT10S
14:51:20.762 [] [main] INFO  io.zeebe.test - Test failed, following records where exported:
14:51:20.802 [] [main] INFO  io.zeebe.test - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685294,"position":4295049024,"timestamp":1582296642278,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":4,"workflowKey":2251799813685286,"elementId":"task","bpmnProcessId":"process","workflowInstanceKey":2251799813685289,"flowScopeKey":2251799813685289,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":4295047960}
14:51:20.809 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295049328,"timestamp":1582296642281,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldRejectIfJobIsAlreadyCompleted","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.817 [] [main] INFO  io.zeebe.test - {"valueType":"DEPLOYMENT","key":-1,"position":4295049544,"timestamp":1582296642291,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfZmJiZGM3NTUtNDdkZS00M2ZmLTk3YjQtM2I1YTBhMGVmNzIzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93Xzk4MTUzMjgxLWY0MTctNDYyYy04NTMyLWI4YTNjZDMzOGQ5YTwvb3V0Z29pb...
14:51:20.817 [] [main] INFO  io.zeebe.test - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685294,"position":4295052352,"timestamp":1582296643127,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":4,"workflowKey":2251799813685286,"elementId":"task","bpmnProcessId":"process","workflowInstanceKey":2251799813685289,"flowScopeKey":2251799813685289,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":4295049024}
14:51:20.817 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685301,"position":4295052656,"timestamp":1582296648219,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldRejectIfJobIsAlreadyCompleted","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295049328}
14:51:20.819 [] [main] INFO  io.zeebe.test - {"valueType":"DEPLOYMENT","key":2251799813685303,"position":4295052888,"timestamp":1582296648283,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfZmJiZGM3NTUtNDdkZS00M2ZmLTk3YjQtM2I1YTBhMGVmNzIzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93Xzk4MTUzMjgxLWY0MTctNDYyYy04NTMyLWI4YTNjZDMzOGQ5...
14:51:20.819 [] [main] INFO  io.zeebe.test - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685304,"position":4295055792,"timestamp":1582296648289,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":4,"workflowKey":2251799813685286,"elementId":"sequenceFlow_0a76676a-3add-458c-9977-825d086a90bb","bpmnProcessId":"process","workflowInstanceKey":2251799813685289,"flowScopeKey":2251799813685289,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":4295052352}
14:51:20.819 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295056144,"timestamp":1582296648529,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithoutVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.820 [] [main] INFO  io.zeebe.test - {"valueType":"DEPLOYMENT","key":2251799813685303,"position":4295056360,"timestamp":1582296652407,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfZmJiZGM3NTUtNDdkZS00M2ZmLTk3YjQtM2I1YTBhMGVmNzIzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93Xzk4MTUzMjgxLWY0MTctNDYyYy04NTMyLWI4YTNjZDM...
14:51:20.820 [] [main] INFO  io.zeebe.test - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685305,"position":4295059264,"timestamp":1582296652408,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":4,"workflowKey":2251799813685286,"elementId":"end","bpmnProcessId":"process","workflowInstanceKey":2251799813685289,"flowScopeKey":2251799813685289,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":4295055792}
14:51:20.820 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685306,"position":4295059560,"timestamp":1582296652409,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithoutVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295056144}
14:51:20.821 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295059792,"timestamp":1582296653638,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.821 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295060000,"timestamp":1582296653638,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobNullVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.821 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295060208,"timestamp":1582296662445,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithoutVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.822 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295060424,"timestamp":1582296663666,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldRejectIfJobIsAlreadyCompleted","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.823 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295060640,"timestamp":1582296663666,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.824 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":-1,"position":4295060848,"timestamp":1582296663666,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobNullVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":-1}
14:51:20.824 [] [main] INFO  io.zeebe.test - {"valueType":"DEPLOYMENT","key":2251799813685303,"position":4295061056,"timestamp":1582296665897,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfZmJiZGM3NTUtNDdkZS00M2ZmLTk3YjQtM2I1YTBhMGVmNzIzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93Xzk4MTUzMjgxLWY0MTctNDYyYy04NTMyLWI4YTNjZDMz...
14:51:20.824 [] [main] INFO  io.zeebe.test - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685305,"position":4295063960,"timestamp":1582296665898,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":4,"workflowKey":2251799813685286,"elementId":"end","bpmnProcessId":"process","workflowInstanceKey":2251799813685289,"flowScopeKey":2251799813685289,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":4295059264}
14:51:20.825 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685307,"position":4295064256,"timestamp":1582296665898,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295059792}
14:51:20.825 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685308,"position":4295064480,"timestamp":1582296665899,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobNullVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295060000}
14:51:20.825 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685309,"position":4295064704,"timestamp":1582296665899,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldCompleteJobWithoutVariables","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295060208}
14:51:20.825 [] [main] INFO  io.zeebe.test - {"valueType":"JOB_BATCH","key":2251799813685310,"position":4295064936,"timestamp":1582296670759,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"type":"job-shouldRejectIfJobIsAlreadyCompleted","timeout":300000,"worker":"default","truncated":false,"maxJobsToActivate":32,"jobKeys":[],"jobs":[]},"sourceRecordPosition":4295060424}
</pre></details>

**Comment by pihme** [comment]
@npepinpe Created this issue when you asked for team members to create unstable test issues a while ago. I haven't observed this test being flaky in a while; please close if you believe it is resolved

**Comment by npepinpe** [comment]
I'll close them as lately it's always the same few coming back. But it makes me realize we should keep track of these better in order to notice when they stop happening. If you know of anything to do this, let me know, otherwise I will try to think of something.

In the meantime I'll close this and the other ones you reported, as well as do a general clean up on those that were previously reported.
