### ISSUE TITLE
Hangs during cluster services start

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3912]
**Describe the bug**

When restarting a node, it sometimes happens that on restart, the node is stuck on the 7th step, trying to start cluster services. This may have flown under the radar as that step is notoriously slow, but it seems sometimes it fails to create the partitions entirely (even though no exceptions are thrown). This is currently an assumption - after waiting quite a while for the integrity checks to run on a small log, I checked a heap dump of my process only to find out I had 2 live instances of `RaftContext` in memory, one for the system partition, and one for our data partition 1. We expect to have 4, one for each data partition + the system partition.

This to me indicates somehow the creation of the partitions failed, and they simply never started - even though no error was thrown.

A workaround at the moment is to restart the node again, as this is a recoverable error, and does not happen all the time. It is however difficult to determine if the integrity checks are slow or if it's simply stuck.

**To Reproduce**

Using the latest snapshot from today (commit: `b8c8bcdc6072e40e801e1542a85040bb1236f5f3`), start a cluster of 3 nodes, 3 partitions, replication factor 3, snapshot period 2 minutes, max snapshot count 1, then run some light load, ~150wfi/s. After a few minutes, kill a node (usually I kill node 2 - probably has no effect, but you never know). On restart, if it takes more than a few minutes to restart, perform a heap dump (or even thread dump - you should see a few named threads for each Raft partition), and notice some partitions are missing.

**Expected behavior**

I expect all partitions to be recreated on restart **always**.

**Additional context**

Attached is a heap dump:
[heap.zip](https://github.com/zeebe-io/zeebe/files/4244740/heap.zip)

**Comment by deepthidevaki** [comment]
Might be related to https://github.com/zeebe-io/atomix/issues/137 ?

**Comment by npepinpe** [comment]
Wouldn't the partition context have been created before we scan the log? So I would expect the `RaftContext` for the partition to exist in memory?

**Comment by deepthidevaki** [comment]
> Wouldn't the partition context have been created before we scan the log? So I would expect the `RaftContext` for the partition to exist in memory?

`RaftContext` is created when the partition is started. From the logs linked in the above issue, we can see that partitions are started sequentially. Start of a partition is completed only after scanning the logs are done. `RaftContext` for a partition is not available until previous partition start is completed.

> 
> Like I said this is an assumption, the log was ~1GB and I waited ~25 minutes thinking

Then there might be some other issues. If it was due to slow scanning of logs, it should eventually complete the service start.

**Comment by npepinpe** [comment]
Hm, could be that. Any ideas why even with the similar log sizes, the times are very inconsistent? I sort of expect similar performance if using a PVC tbh.

**Comment by npepinpe** [comment]
> Then there might be some other issues. If it was due to slow scanning of logs, it should eventually complete the service start.

If the partitions are created sequentially, then it's a little hard to tell if it's just slow or it failed somewhere along the way. How long is too long? I figured for 1GB per partition, 25 minutes was too much, but that's also another assumption.

Perhaps we should revisit this once https://github.com/zeebe-io/atomix/issues/161 is implemented, which should speed up the restart to something more predictable.

**Comment by npepinpe** [comment]
Closing as it is likely an issue with the very, very slow recovery process.
