### ISSUE TITLE
Add broker steps startup/shutdown metrics

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3913]
**Is your feature request related to a problem? Please describe.**

It would be helpful when deploying changes to know how they impact startup/shutdown (start up in particular is important for quick failover).

**Describe the solution you'd like**

Add metrics to monitor startup/shutdown time, total and split by steps, so we can see the difference over time.

**Describe alternatives you've considered**

Checking the logs - works OK-ish, but easy to overlook.

**Comment by aivinog1** [comment]
@npepinpe Hi, I think I can take this :) If I understand correctly these times (step-by-step: `io.zeebe.broker.bootstrap.StartProcess#startStepByStep` and `io.zeebe.broker.bootstrap.CloseProcess#closingStepByStep`) already calculated and just needs to add metrics on these :) I'm thinking that it should be a pie chart with sectors - steps.

**Comment by npepinpe** [comment]
iirc pie charts in Grafana aren't built-in, so I wouldn't expect most users to have this floating around. I hadn't really thought about it up until now to be honest. We could go with a single gauge metric, with a label for the step itself? As step number can change, maybe we can use the step name as the label value (that's possibly less likely to change).
