### ISSUE TITLE
Message start event missing correlation-key

### ISSUE THREAD

**Issue by ezolnbl** [zeebe-io/zeebe#3930]
**Describe the bug**
I can not correlate a message inside an embedded non terminating sub process because it can only start with a timer, message start or error but the message start event does not support correlation-key.

**To Reproduce**
with message start events:
![multi_non_int_proc](https://user-images.githubusercontent.com/3415684/75356194-e4d66b80-58af-11ea-99ae-f6aa41464407.jpg)

with event gateway:
![multi_non_int_proc_2](https://user-images.githubusercontent.com/3415684/75356427-40a0f480-58b0-11ea-8c1d-1f4477f8edd6.jpg)

with none start event:
![multi_non_int_proc_3](https://user-images.githubusercontent.com/3415684/75356722-9d041400-58b0-11ea-81dd-a770ead07eff.jpg)

Either starting a process then sending a message or sending a message to the start events directly prodcues the same error, the inner process's top(start - receive termination - stop) interrupting flow does not start and the original message is not forwarded to the non interrupting subprocess.

If possible add a minimal reproducer code sample
 ```
zeebeClient.newPublishMessageCommand()
                            .messageName(msg)
                            .correlationKey(oid)
                            .variables(variables) (populated with the oid also)
                            .send();
```

**Expected behavior**
An outer message should be forwared to the parent subprocess and from that point any matching message with the matching correlation key should start a non terminating sub process inside the parent subprocess as long as the parent subprocess lives.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
zeebe-1_1        | 2020-02-26 14:44:14.883 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR io.zeebe.processor - Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}, value={"bpmnProcessId":"some_flow","version":5,"workflowKey":2251799813685454,"workflowInstan
ceKey":2251799813685469,"elementId":"SubProcess_0mnjlo2","flowScopeKey":2251799813685469,"bpmnElementType":"SUB_PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'null' .
zeebe-1_1        | java.lang.NullPointerException: null
zeebe-1_1        |      at io.zeebe.msgpack.query.MsgPackQueryProcessor.process(MsgPackQueryProcessor.java:29) ~[zeebe-msgpack-json-path-0.23.0-alpha1.jar:0.23.0-alpha1]
zeebe-1_1        |      at io.zeebe.engine.processor.workflow.CatchEventBehavior.extractCorrelationKey(CatchEventBehavior.java:215) ~[zeebe-workflow-engine-0.23.0-alpha1.jar:0.23.0-alpha1]
zeebe-1_1        |      at io.zeebe.engine.processor.workflow.CatchEventBehavior.extractMessageCorrelationKeys(CatchEventBehavior.java:281) ~[zeebe-workflow-engine-0.23.0-alpha1.jar:0.23.0-alpha1]
zeebe-1_1        |      at io.zeebe.engine.processor.workflow.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:79) ~[zeebe-workflow-engine-0.23.0-alpha1.jar:0.23.0-alpha1]
zeebe-1_1        |      at io.zeebe.engine.processor.workflow.handlers.CatchEventSubscriber.subscribeToEvents(CatchEventSubscriber.java:26) ~[zeebe-workflow-engine-0.23.0-alpha1.jar:0.23.0-alpha1]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: camunda/zeebe:0.23.0-alpha1
 - Configuration: default

**Comment by saig0** [comment]
I prepared a workflow similar to your example: https://gist.github.com/saig0/f36817700d486dbe373600fb32915ca4

You can run the following commands after the workflow is deployed: 
```
// initial message
./zbctl publish message "Message1" --correlationKey="key-1" --variables="{\"key\":\"key-1\"}" --ttl=1m --insecure

// follow-up messages
./zbctl publish message "Message1" --correlationKey="key-1" --variables="{\"key\":\"key-1\"}" --ttl=1m --insecure
./zbctl publish message "Message2" --correlationKey="key-1" --variables="{\"key\":\"key-1\"}" --ttl=1m --insecure

// termination message
./zbctl publish message "Message3" --correlationKey="key-1" --variables="{\"key\":\"key-1\"}" --ttl=1m --insecure
``` 

Does this behave as you expect?

Related bug in the Zeebe modeler: https://github.com/zeebe-io/zeebe-modeler/issues/151

**Comment by ezolnbl** [comment]
The initial message1 shouldnt be forwarded to the subprocess?  Why is it stopping at the boundary of parent subprocess? Can it be forwarded?

**Comment by saig0** [comment]
What exactly do you mean with forwarded to the subprocess?

The first/initial message triggers the message start event and creates a new instance. Within this instance, this message is not correlated anymore because a message can only be correlated once to an instance. 
The message event subprocess can only be triggers after the instance is created.

**Comment by ezolnbl** [comment]
yes that was a false assumption from me that messages are forwarded to subprocesses (inside a subprocess) if there are outer messages correlations instead every subprocess is initialized once then every other message are correlated to an already running subprocess inside the parent subprocess

**Comment by ezolnbl** [comment]
however there is another problem, the variables which i send with the correlation for the second time are not visible in the embedded non terminating subprocess (in your example it's also not working), i did not configured any in/out mapping for the subprocesses

**Comment by saig0** [comment]
I can confirm this behavior :+1: 

It seems that something goes wrong with the message variables. The variables are not propagated to the root scope when the message is correlated (as they should). When the embedded subprocess is completed, the variables are propagated. But only for the first message. This is definitely a bug in the broker.
