### ISSUE TITLE
Detect position inconsistency on reprocessing

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3936]
**Description**

Currently we encounter more often inconsistent logs, which causes really bad issues on further processing. To detect or check the log we often uses an external tool like https://github.com/Zelldon/playground/releases . It should also be possible that the broker detects for itself and refuses to start.

It would be also nice to detect on writing but this is another topic. I will create a separate issue for that.

**Comment by npepinpe** [comment]
I would like that we attempt to do so on writing as well, to be honest, as once it's written and committed recovery is almost impossible.

**Comment by npepinpe** [comment]
In general I'd like to brainstorm on what measures we could implement to prevent these kind of inconsistencies happening. Maybe we can have a quick brainstorm session (~30 min) and then expand on those ideas here in paper (or write a ZEP?).

**Comment by npepinpe** [comment]
Outcome of the session (for posterity):

```
Define inconsistencies
Not ordered positions == positions are not strictly increasing
Missing events == 
Not ordered indexes == indexes are not strictly incremented without gaps

Potential checks
Change positions => read last index and position on the log on start, and encode index into position, with the lower bits representing the index in the array of records in the IndexedEntry. Verify impact on the dispatcher (how are segments/offset used)
Doing this allows us to detect gaps in the positions as well as the indexes and detect missing events
Consistency check on writing to the log:
Detect missing positions/indexes and keep track of expected positions/indexes
Step down if detected
Possibly more eventually?
Check consistency/expected indexes/positions when building the ZeebeIndex
On startup this causes a hard fail
Init container as a debugging tool to detect inconsistencies


Recoverable cases
Writer check fails -> step down, recoverable
Check fails on reading ->
Manual tooling for recovering some cases
If snapshot position is < than the “error record” position, we could truncate and recover from snapshot
Reorder log by shutting down all nodes and doing it offline on all machines



Things we didn’t discuss
Testing these in a deterministic way (in addition to chaos test) 
```

**Comment by Zelldon** [comment]
We decided to check the positions on reprocessing (that they always increase). If we encounter a problem then we want either to stop starting the broker completely or step down for that partition.

We have to test and decide what is the better approach. If we just step down on one partition then the other partitions can still make progress. This will cause an error loop since this event is commited, which means it will also happen on the new leader.
