### ISSUE TITLE
Task worker of sample application does not complete task correctly

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#394]
In the current sample application there is an output mapping of the task:

https://github.com/zeebe-io/zeebe/blob/master/samples/src/main/resources/demoProcess.bpmn#L19

This is not set by the worker example:

https://github.com/zeebe-io/zeebe/blob/master/samples/src/main/java/io/zeebe/workflow/WorkflowInstanceWorker.java#L64

This raises an incident which is nowhere shown, which I think could be confusing for beginners:

```
>>> [topic: 0, position: 4295030400, key: 4295030008, type: INCIDENT]
{"state":"CREATED","errorType":"IO_MAPPING_ERROR","errorMessage":"Task was completed without an payload - processing of output mapping failed!","failureEventPosition":4295029760,"bpmnProcessId":"demoProcess","workflowInstanceKey":4295026088,"activityId":"taskA","activityInstanceKey":4295027088,"taskKey":-1,"payload":"gA=="}
===
```

**Comment by berndruecker** [comment]
By the way - a question which came up my mind here: What's the bets practice for a worker to get notified of such a problem he basically caused by providing the wrong data - so the worker itself could also fix it? Subscribe to the incidents and filter for work he has done in the past? Not very convenient. Better ways?

**Comment by menski** [comment]
I guess this is outdated
