### ISSUE TITLE
Control package level logging through environment variables

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#3941]
**Is your feature request related to a problem? Please describe.**
Currently, Zeebe provides only 1 `ZEEBE_LOG_LEVEL` environmental option at an overall application level. This configures the logging level for all the packages within broker and exporters. There is no way to fine-tune it for different packages based on user requirement. Sometimes we have specific use-case to log only the `ERROR` logs for exporter packages while `DEBUG` logs for zeebe broker.

**Describe the solution you'd like**
Zeebe should provide environment parameters to configure package level logging, something similar to what Spring provides.

**Additional context**
We should be able to provide a map or list of packages along with their logging level, that should override the `ZEEBE_LOG_LEVEL` environment parameter for only the respective packages.

**Comment by npepinpe** [comment]
Is providing a different configuration not possible for your use case? In our own tests, we'll typically do this by overwriting the `log4j2.xml` configuration packaged in the distribution.

**Comment by strawhat5** [comment]
Yeah that can be done, but then we would have to maintain our own version of Zeebe images, instead of using `camunda/zeebe` images.

Our opinion is that logging should be a configurable parameter, which can be tweaked using environment variables or using `zeebe.cfg.toml`. I believe other users might also have this use-case to control what exactly they want to log using config parameters. And it might become a hassle for all those users to maintain their own sets of Zeebe distribution instead of using official `camunda/zeebe` images.

**Comment by npepinpe** [comment]
> Yeah that can be done, but then we would have to maintain our own version of Zeebe images, instead of using camunda/zeebe images.

Is it not feasible or convenient for you to just mount a custom log configuration file to `config/log4j2.xml`? That's usually how I overwrite the settings. Or if you wanted a different logging backend, e.g. logback, you could mount the JAR to `lib/logback.jar`, and inject the configuration file by mounting it and passing its path as an argument in your podspec, e.g. `args: ["-Dlogback.configurationFile=/path/to/config.xml"]` (or appending it to the `JAVA_OPTS` environment variable).

That said, I assume this is a feasible/convenient option for most use cases, but I could be wrong. If mounting files is not something feasible when deploying your container, could you elaborate? And additionally, how would the configuration look like using environment variables?  It's difficult to predict which packages should be instrumented/which are interesting for all use cases - do you have any ideas there? Or a flexible way of configuring the logging over environment variables? I couldn't find much in the log4j2 documentation about multiple configuration sources or configuring through environment variables.

**Comment by strawhat5** [comment]
> Is it not feasible or convenient for you to just mount a custom log configuration file to config/log4j2.xml? That's usually how I overwrite the settings.

Ah I see.. That is definitely a convenient option for me. Since Zeebe uses `startup.sh` script to start the broker, I didn't think that mounting the `log4j2.xml` file may work. My bad. 🤗 In that case, we probably don't need it in environment variables. We can control it by tweaking the `log4j2.xml` file at runtime.

I will try this out. Meanwhile, should this be added to the Zeebe documentation? 🤔

**Comment by npepinpe** [comment]
Good point, we should add it to the [Zeebe Operations](https://docs.zeebe.io/operations/index.html) section :+1:

**Comment by npepinpe** [comment]
I opened the following: https://github.com/zeebe-io/zeebe/issues/4076

I'll wait to hear if customizing the file is sufficient for you, and if so we can close this in favor of the #4076.

**Comment by strawhat5** [comment]
I have verified by mounting my custom `log4j2.xml` file at `config/log4j2.xml`. It is working as expected.

Thanks for your inputs @npepinpe ! I am closing this in favour of #4076 .
