### ISSUE TITLE
ActivateJobsRequest doesn't specify units for timeout and requestTimeout

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#3944]
The interface doc for [ActivateJobsRequest](https://docs.zeebe.io/reference/grpc.html#activatejobs-rpc) doesn't specify units for `timeout` and `requestTimeout` (they are both `int64`, which gives no information about the semantics of the number). 

`requestTimeout` looks to be milliseconds from testing.

From [here](https://docs.zeebe.io/clients/java-client-examples/job-worker-open.html#jobworkercreatorjava), it looks like `timeout` is seconds?

Can we clarify this and add that to the comments in the proto file please.

**Comment by Zelldon** [comment]
We added with https://github.com/zeebe-io/zeebe/pull/3780 this to the docs, but still we need to add this to the proto file. Good point btw @jwulf
