### ISSUE TITLE
Restart job with Golang client

### ISSUE THREAD

**Issue by mirecl** [zeebe-io/zeebe#3949]
Hi!
Pls help restart job with Golang client. I not find method.

If my Worker (Golang) crashed, my job restart after 5 minute - I can to configure this time?

**Comment by menski** [comment]
Hi @mirecl,

this can be configured by setting using the `Timeout` method of `ActivateJobsCommand`.

https://github.com/zeebe-io/zeebe/blob/1d7b0e19aa9a9a30189c5ea6e5633ba000cdf187/clients/go/pkg/commands/activate_jobs.go#L66

The default is 5 minutes for the job timeout.

https://github.com/zeebe-io/zeebe/blob/1d7b0e19aa9a9a30189c5ea6e5633ba000cdf187/clients/go/pkg/commands/activate_jobs.go#L26

You can read more about what this timeout means in our docs https://docs.zeebe.io/basics/job-workers.html.

Cheers,
Sebastian

**Comment by mirecl** [comment]
Thanks!
How I can restart job with golang client?
