### ISSUE TITLE
Subscription iterator is reset on channel close

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#395]
To distribute the events to multiple subscriptions the [LockTaskStreamProcessor](https://github.com/zeebe-io/zeebe/blob/65108b27d3f9f16661b99c073898eb8a4fd1f90e/broker-core/src/main/java/io/zeebe/broker/task/processor/LockTaskStreamProcessor.java#L85) uses [an iterator](https://github.com/zeebe-io/zeebe/blob/65108b27d3f9f16661b99c073898eb8a4fd1f90e/broker-core/src/main/java/io/zeebe/broker/task/processor/LockTaskStreamProcessor.java#L235).

If a connection is closed the [internal iterator is reset](https://github.com/zeebe-io/zeebe/blob/65108b27d3f9f16661b99c073898eb8a4fd1f90e/broker-core/src/main/java/io/zeebe/broker/task/processor/LockTaskStreamProcessor.java#L189). This will reset also the subscription iterator so the "round-robin" starts from the beginning.

We discovered that with the go client, where we use a client for the subscriptions and then another short living client to create tasks. Every time the client creates a task he disconnects afterwards which triggers an iterator reset.

**Comment by ThorbenLindhauer** [comment]
Commit: https://github.com/zeebe-io/zeebe/commit/c5dd556c5e6170ce2f4367d89f67de7fe9b2cffb
