### ISSUE TITLE
SetVariables Command can cause GRPC 13: INTERNAL ERROR / GRPC 4: TIME OUT

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#3961]
**Describe the bug**
Issuing this command to the broker causes GRPC 13: Internal Error on 0.22, and GRPC 4 DEADLINE EXCEEDED on 0.23.0-alpha1:

(Node.js code)

```
await zbc.setVariables({
	elementInstanceKey: '0', 
	local: false,
	variables: {
		conditionVariable: false,
	},
})
```

**To Reproduce**
Send a SetVariables command for a non-existent elementInstance.

**Expected behavior**
I would expect 5 NOT FOUND. And does it have to wait to the gateway timeout...?

Is it waiting for that element to appear?

If it is, I'll need to document this and wrap the error to have it make sense for the user in the client.

**Environment:**
 - OS: Docker
 - Zeebe Version: Camunda Cloud, and 0.23.0-alpha1 in Docker.
 - Configuration: nada in Docker.

**Comment by korthout** [comment]
Reproduced GRPC 4 DEADLINE EXCEEDED on `0.23.0-alpha1` and on `0.22`, but unable to reproduce GRPC 13: Internal Error.

The element instance is used in the gateway to find the partition that contains that specific instance. However, in this case the partition can not be found, and in turn also no broker can be found. It appears that gRPC times out, while the gateway keeps trying to sent the SetVariable request to a none-existing broker.

I'm going to look into responding a Not Found from the gateway, which in turn can stop trying to reach out to the none-existing broker.
