### ISSUE TITLE
Job handler interface should declare `throws Exception`

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#397]
And then document that a thrown exception is communicated to the broker as a failed task.

**Comment by ThorbenLindhauer** [comment]
Does this affect wirting task handlers as lambdas?

**Comment by jangalinski** [comment]
@ThorbenLindhauer yes, throwing checked exceptions will lead to not being able to use lambdas.

**Comment by ThorbenLindhauer** [comment]
@jangalinski This works, though:

```
public class Main
{
    public static void main(String[] args) throws Exception
    {
        int val = 1;
        int result = compute(i -> 2*i, val);
        System.out.println(result);
    }

    protected static int compute(MyFunction function, int param) throws Exception
    {
        return function.compute(param);
    }


    @FunctionalInterface
    public interface MyFunction
    {
        int compute(int param) throws Exception;
    }
}
```

Or am I missing the point here?

Isn't the issue with checked exceptions and functional interfaces/lambdas rather that you can't use method references for methods that take `java.util.function.Consumer` (or similar Java 8 functional interfaces) if the method declares a checked exception (and in turn, makes the streaming API hard to use)?

**Comment by Zelldon** [comment]
@menski do we want this for the GA?

**Comment by menski** [comment]
thanks @Zelldon, I will have a look and decide it later this week
