### ISSUE TITLE
Set default value of lock owner in task subscription message pack to empty string

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#400]
Currently the default value for `lockOwner` [is `default`](https://github.com/zeebe-io/zeebe/blob/9b5cd8605cc6bac7999fc1ab6057a55f8f8794d5/broker-core/src/main/java/io/zeebe/broker/task/processor/TaskSubscriptionRequest.java#L33). The value is for example returned in the close task subscription response. I was surprised when the broker returned a `lockOwner` which did not match the value set during the creation of the subscription. Therefore I would suggest to set the default value to the empty string similar to `taskType`.

**Comment by menski** [comment]
@saig0 was there a reason to set the value to `default` instead of an empty string?

**Comment by saig0** [comment]
@menski , I set this value to make it easier to create a subscription. However, I agree that we should use an empty string instead. Maybe we can provide a default value of client side.

**Comment by menski** [comment]
@saig0 thanks for clarification. I'm not sure if we should set a default value for lock owner. As far as I remember the lock owner should be unique to the worker? So setting a default increases the chance that every worker has the same lock owner. What do you think? Or what happens if multiple workers have the same lock owner?

**Comment by saig0** [comment]
@menski , if multiple workers share the same lock owner then another client could complete / fail a task which is locked by someone else. What do you think that you can set the lock owner in the client properties? If not set, you have to set the lock owner at the create subscription request.

**Comment by menski** [comment]
Yeah I think our current approach is using java properties in the client, so I would vote for using it also for the lock owner name.

**Comment by menski** [comment]
this is fixed
