### ISSUE TITLE
Clarification of the ZEEBE-COMMUNITY-LICENSE license

### ISSUE THREAD

**Issue by mprinc** [zeebe-io/zeebe#4006]
**Description**

Dear @jwulf and @meyerdan et al,

We need clarification regarding the [Zeebe license](https://github.com/zeebe-io/zeebe/blob/develop/licenses/ZEEBE-COMMUNITY-LICENSE-1.0.txt)

We did read the https://github.com/zeebe-io/zeebe/issues/3770#issuecomment-580995142, but it is still unclear to us. 

**Scenario**

We have designed a DH (Digital Humanity) solution for Universities, and apart of providing free use scenarios, it has commercial scenarios as well. It lets users design DH workflows and executes them.

Now we are in the process of migrating to the next generation and we are considering running Zeebe as the workflow backbone. We wonder if, in this scenario, the Zeebe license allows us to integrate Zeebe and providing the commercial service which is free for us regarding Camunda?

Thanks,
Sasha

**Comment by jwulf** [comment]
This is not a legal opinion, but this sounds to me (without seeing the specifics) that it will fall inside the license.

I looked at some of your previous papers and work at https://www.researchgate.net/profile/Sasha_Rudan, and everything in that domain is fine.

If you want more specific guidance, you can email details of your use case to feedback@zeebe.io.

**Comment by Zelldon** [comment]
I assume we can close this. If you have any further questions or comments regarding this topic feel free to re-open it.
