### ISSUE TITLE
Add Connector example

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#401]
I built a simple Zeebe example that uses the Java client, task headers and payload to make POST requests to a REST service, available here: https://github.com/ThorbenLindhauer/zeebe-example

Should become part of the zeebe samples. May require restructuring the samples a little (one submodule per example).

**Comment by menski** [comment]
We now also have https://github.com/zeebe-io/zeebe-http-worker

**Comment by Zelldon** [comment]
i think this is out dated
