### ISSUE TITLE
CI builds fail due to benchmark module not building

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4016]
**Description**

Sometimes builds in Jenkins will fail, the cause being that the shaded JAR for the benchmark module cannot be built. You can pretty much restart your build, but as it's quite annoying we should fix it eventually.

**Comment by Zelldon** [comment]
Yes saw that as well - maybe because we build with multiple threads?

**Comment by npepinpe** [comment]
Why do you think? Have you come across this before?

**Comment by Zelldon** [comment]
I think peter had issues lately with running `mvn -T1C`
