### ISSUE TITLE
Take snapshots even when no processing occurs

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4017]
**Description**

While reviewing #3962 (https://github.com/zeebe-io/zeebe/pull/3962#discussion_r390148228) we discussed the possibility of taking snapshots like clockwork every X minutes, regardless of whether we processed or exported anything.

The main motivation here is to solve the current issue we have when no processing is done but we are exporting (e.g. exporters were behind), and to reduce complexity (no need to keep track of any state, just take a snapshot at a particular interval).

While this is very tempting, I'd like to consider the worst case scenario here if we were to do this naively. For example, if we have a very large state, this could be quite expensive for no reason, as we're not only snapshotting the current state, but also replicating it, potentially uselessly.

**Comment by Zelldon** [comment]
> While this is very tempting, I'd like to consider the worst case scenario here if we were to do this naively. For example, if we have a very large state, this could be quite expensive for no reason, as we're not only snapshotting the current state, but also replicating it, potentially uselessly.

But if you haven't done anything; then it also not really problematic that you do something different like snapshotting :man_shrugging: Which is btw only every X (snapshotInterval, which is currently 15 min). It would be also better for the big state and log, because then it might be possible that we can delete, since the exporter position might have been updated.

I would vote for make it more simple.

**Comment by npepinpe** [comment]
> But if you haven't done anything; then it also not really problematic that you do something different like snapshotting

That's assuming evenly distributed load across all partitions - which is probably usually the case, but not sure. We should try it out first in a benchmark, just to make sure we didn't forget any side effects. But you're probably right, it's probably safe to do just always snapshot/compact.
