### ISSUE TITLE
Dockerfile: Make network configurations configurable via environment variables

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#402]
The Dockerfile should allow to set the HOST in the config via environment variable, see also https://forum.zeebe.io/t/connect-to-zeebe-in-a-docker-compose-environment/58/4

**Comment by menski** [comment]
Personally I think all the network configurations (client/management/replication) have to be configurable through environment variables.

**Comment by berndruecker** [comment]
Agreed - adjusted the title

**Comment by menski** [comment]
With #1041, #1043 and #1045 this is partial implemented and the most common network/cluster configs can be set as environment variable. There is no env variable yet for specific hosts. I'm not sure if we still need this with the new architecture. I'm closing this for now and will create new issues if we discover that we need other variables as well.
