### ISSUE TITLE
Benchmarks: Refactor Starter/Worker to be Camunda Cloud compatible

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4022]
The Starter/Worker applications should be configurable from the environment, and be cloud-compatible - that is, exporting the environment variables as described in the cloud dashboard should be enough to allow running the applications against a cloud-hosted cluster, which I have found is not the case at the moment.

**Comment by menski** [comment]
@npepinpe we merged a while ago #4104 which I used to test against the cloud. Could you review if this closes this issue, or if there is anything missing from your side.

**Comment by npepinpe** [comment]
I wasn't aware of this - no, it looks fine :+1:
