### ISSUE TITLE
Provide a way to generate inconsistent log

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4075]
**Description**

In the last weeks we had often problems with an inconsistent log. Such problem should always be avoided. It can bring down the complete system. Currently it is hard to test how the system behaves when we have a inconsistent log. We need a way to create an inconsistent log such that we can use it in our tests and also chaos experiments, such that we are sure that we can detect it successfully and also able to handle such cases.

**Comment by npepinpe** [comment]
Closing, we should work on this in the context of a chaos test which requires such functionality.
