### ISSUE TITLE
Taking snapshot can cause leader election

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4077]
**Describe the bug**

It seems that we have currently the problem that on taking snapshot we miss heartbeats, which in the end causes to a new leader election.

I run several different benchmarks, which different branches (incl. diff changes) all behave the same that the leader changes happen on snasphot intervals. Not always but it is really likely.

| Branch | Processing  | Heartbeats |
|-----------|---------------|------------------|
| Remove system partition | ![zell-rm-sys-proc](https://user-images.githubusercontent.com/2758593/77078679-35e10780-69f7-11ea-85f7-699f04b6aada.png) |      ![zell-rm-sys-heartbeats](https://user-images.githubusercontent.com/2758593/77078680-36799e00-69f7-11ea-98d0-d34c8723a36b.png) |
| Min. based snapshotting | ![zell-min-based-proc](https://user-images.githubusercontent.com/2758593/77078682-36799e00-69f7-11ea-8b07-85baf6db31db.png) | ![zell-min-based-heartbeats](https://user-images.githubusercontent.com/2758593/77078685-37123480-69f7-11ea-95ef-2598a4182a28.png) |
| Milli. based snapshotting | ![zell-3376-2-proc](https://user-images.githubusercontent.com/2758593/77078687-37aacb00-69f7-11ea-943b-faee7ca7decc.png) | ![zell-3376-2-heartbeats](https://user-images.githubusercontent.com/2758593/77078689-38436180-69f7-11ea-8a0f-cb111e830835.png) |

**Comment by npepinpe** [comment]
So this explains the flaky test? Any ideas?

**Comment by Zelldon** [comment]
> So this explains the flaky test? Any ideas?

I assume. Currently I would guess that it is because we directly delete/compact. I think this was the only thing we changes lately on the snapshots.

**Comment by npepinpe** [comment]
Closed by #4102
