### ISSUE TITLE
Nullpointer on ZeebeStateMachine

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4086]
**Describe the bug**
Since the NPE has no stack trace it is not really clear where it happens, based on the other log statements I assume it happens in the ZeebeStateMachine, might be related to the 

```
I 2020-03-20T06:38:24.482496649Z 2020-03-20 06:38:24.481 [] [raft-partition-group-raft-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2430768
 
I 2020-03-20T06:38:25.058637716Z 2020-03-20 06:38:25.058 [] [raft-server-0-raft-partition-partition-3] ERROR io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - An uncaught exception occurred
 
I 2020-03-20T06:38:25.058664788Z java.lang.NullPointerException: null
 
I 2020-03-20T06:38:25.077926422Z 2020-03-20 06:38:25.077 [] [ForkJoinPool.commonPool-worker-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Closing state machine raft-partition-partition-3
 
I 2020-03-20T06:38:25.077970494Z 2020-03-20 06:38:25.077 [Broker-0-ZeebePartition-3] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=3, group=raft-partition}
 

```

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&authuser=1&minLogLevel=0&expandAll=false&timestamp=2020-03-20T07:09:30.233000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-min-based-offset%22%0Alabels.k8s-pod%2Fapp%3D%22zell-min-based-offset-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-min-based-offset%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0ANOT%20textPayload:%22gateway%22&scrollTimestamp=2020-03-20T06:38:25.081421344Z&pinnedLogId=170b01bdp09sfqeev&pinnedLogTimestamp=2020-03-20T06:38:25.058664788Z

**Comment by Zelldon** [comment]
Normally the jvm trims the stack trace when the exceptions was thrown often in a row - so it might be related to https://github.com/zeebe-io/atomix/issues/186

**Comment by npepinpe** [comment]
As it happened right at compaction, this sounds related to the bug you fixed - what do you think?

**Comment by Zelldon** [comment]
Yes sorry forgot to reference it, should be fixed with https://github.com/zeebe-io/zeebe/pull/4102
