### ISSUE TITLE
Improve nil initialisation of locally scoped outputElement for feel expressions

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4100]
For multi instance activities we can define the outputElement as a feel expression. To make sure that this variable is available during execution of the multi instance body, it needs to be initialised with a nil-value. Otherwise, each iteration over the body might write values to it at a non-local scope. This only needs to be done for expressions that are just a variable or a nested variable.

This was quickly (and ugly) coded with a simple regex check. But that might lead to some unnecessary (i.e. unwanted) variables on the local scope. For example, when a more advanced expression is used as an outputElement.

This is specifically for `engine/processor/workflow/handlers/multiinstance/AbstractMultiInstanceBodyHandler.java`

**Comment by saig0** [comment]
Idea:
* `Expression` exposes a method `getVariableName(): Optional<String>` 
* it returns the name of the variable if the expression access a single variable or nested property of it (e.g. `x`, `x.y`) 
* for more complex expressions, it returns no variable name 
* the variable name is extracted from the parsed FEEL expression (`Path` or `Ref`)
