### ISSUE TITLE
Brokers stops receiving requests from clients

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4107]
**Description**

In my latest benchmark it happend that the complete processing went down.

![no-progress](https://user-images.githubusercontent.com/2758593/77283951-dbcd9400-6ccd-11ea-8e43-691106dd0941.png)

After taking a look at the metrics I found out that the reason for that is that no requests are received by the brokers or none are send by the clients.

![no-requests](https://user-images.githubusercontent.com/2758593/77283947-db34fd80-6ccd-11ea-89b7-533179d58036.png)

The Network traffic went completely down.

![io](https://user-images.githubusercontent.com/2758593/77284004-f7d13580-6ccd-11ea-90dc-c0f189df0ace.png)

In the metrics above we can see that around 02:17 broker 1 was restarted and it took a while until he comes back. Around 12:00 starters AND workers are restarted, but it seem it is not enough to bring them back. Only after worker, starter and a node was restarted around 16:00, requests seem to be received again.

![worker](https://user-images.githubusercontent.com/2758593/77284537-33b8ca80-6ccf-11ea-8ce9-fda4e748dabd.png)
![starter](https://user-images.githubusercontent.com/2758593/77284539-34516100-6ccf-11ea-8de1-24bf808ba389.png)
![broker](https://user-images.githubusercontent.com/2758593/77284549-3ddac900-6ccf-11ea-8251-e77d32607440.png)

In our setup we using the embedded Gateway and I assume this might be one of the reason why this happens. If the broker is restarted the gateway as well. It might be that the requests for the clients are not routed correctly then.

**Comment by npepinpe** [comment]
Related to https://github.com/zeebe-io/zeebe/issues/4023 ?

**Comment by Zelldon** [comment]
I think this no longer happens.

 * I haven't seen this for a while
 * We now use standalone gw in our benchmarks
 * we have several chaos tests were we restart or disconnect the gateway and this haven't been reproduced

For these reason I will close this for now. Feel free to reopen it.
