### ISSUE TITLE
Remove need for boilerplate code in stream processors

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#411]
Writing a new stream processor involves a lot of copying of boilerplate code. Get rid of that as good as possible.

Basic idea: Stream processors read and write log events. Most stream processors work on a higher abstraction than raw log events. This requires repeated encoding and decoding of event header and event body. Writing to a log stream and writing responses is also always the same code except for the event header, body and position.

Build a stream processor abstraction that works on this level.

**Comment by saig0** [comment]
Review Hints:
* TypedStreamProcessor: only one event registry 
* TypedEventStreamProcessorBuilder: avoid zb-map close callback -> add callback while register map as state resource
