### ISSUE TITLE
Remove Support for Legacy Environment Variables in 0.24.0

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4121]
**Description**

With release 0.23.0 the TOML based configuration was replaced with YAML based configuration. This also resulted in a change to environment variables to configure the system.

The old environment variables are still supported for backwards portability in 0.23.0. This support is scheduled to be removed in 0.24.0.

This entails the following steps:
* Remove maven module `zeebe-legacy-toml-config`
* Clean up callers of this module
* Remove corresponding sections in `deprecated-features.md`

**Comment by aivinog1** [comment]
@pihme @npepinpe Hello, I would like to take this. It's pretty clear for me what needs to be done :)

**Comment by pihme** [comment]
Hi @aivinog1 

thanks for your interest and contribution. I will look at your PR shortly. 

Would you tell me what your interest in Zeebe is and your experience with OS contributions? I am asking out of curiosity.

Best regards
Peter

**Comment by aivinog1** [comment]
Hell @pihme, thanks for your fast response :) 

My primary interest in Zeebe is that I think that Zeebe is a future of BPMN engines and I'm interested in the application with such architecture :) I'm using Camunda BPM for about 3 months in my current job as Java Developer and decide that Zeebe will not such complexity in high load.

About my OS contributions - I'm using a lot of OS projects in my work, pet projects, so I'm trying to do some sort of payback for their projects when it looks interesting and promising. Or I find some projects with interesting concepts, architecture, idea and trying to participate in it :)

**Comment by pihme** [comment]
Glad to hear that! All contributions are welcome. 

Also I should mention that we will be participating in Hacktoberfest: https://camunda.com/hacktoberfest2020/

**Comment by aivinog1** [comment]
@pihme Sure, I'll try it, thanks :)
