### ISSUE TITLE
Make partition IDs unique

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#414]
This is an idea and request for comments.

Currently, we identify a partition via a composite key of (topic name, partition id). With #291, we have introduced a system partition that orchestrates topic and partition creation. This single point of truth allows us to make partition IDs unique. The topic name would then become an attribute of the partition.

Pro:

* Events no longer need to contain both topic name and partition id. This means less data needs to be sent over the wire.
* Easier to program for: In various places (Client subscriptions, broker system topic state), we organize things hierarchically by topic name and partition id (=> e.g. maps of maps). This becomes easier when the partition id is already unique.

Con:

* Received subscribed events of different partitions cannot be easily be compared with respect to topic, if the topology is not known. For example, imagine you have received two events, one from partition x and one from partition y. It is not obvious if these events belong to the same topic.
* Partition id becomes a `long` instead of an `int` value (which is ok, if we save the topic name)

**Comment by ThorbenLindhauer** [comment]
Re con 1: Clients can probably hide this from the end user. In order to receive any events from a partition (be it a subscription or a command response), the client must previously have made a request to request this input. At that point, the topic name must have been known (via user input or via topology request).

**Comment by meyerdan** [comment]
I think that:

a) yes, we should do this for the "pro" reasons you mention
b) I agree with your second comment: whenever we hand over events to the user in the client, we must _always_ resolve the string topic name

**Comment by ThorbenLindhauer** [comment]
This will make a lot of things around topic creation easier, so I will implement this after the 0.3.0 release.

**Comment by o314** [comment]
Hello Zeebe,

Here are my pointers for id generation :

SOFTS

- [ids](https://github.com/bpmn-io/ids)
- [hashid](http://hashids.org)
- [shortid](http://www.npmjs.com/package/shortid)
- [shortid](http://github.com/dylang/shortid)
- [uniqid](https://github.com/php/php-src/blob/php-7.1.10/ext/standard/uniqid.c)

DOCS

- [a simple short unique id in c# without using guid](http://schroedman.wordpress.com/2012/01/19/short-unique-id-in-c-without-using-guid)
- [generating random tokens](http://wyattbaldwin.com/2014/01/09/generating-random-tokens-in-python)
- [generating url-safe short ids in postgresql](http://blog.andyet.com/2016/02/23/generating-shortids-in-postgres/?utm_source=postgresweekly&utm_medium=email)
- [sharding & ids at instagram](http://engineering.instagram.com/sharding-ids-at-instagram-1cf5a71e5a5c)
- [substacknode-hat generate random ids and avoid collisions](http://github.com/substack/node-hat)


That may help

**Comment by ThorbenLindhauer** [comment]
commit not yet linked: https://github.com/zeebe-io/zb-protocol/commit/a14918a5adfb59bd1769c2ff3a62d091b9631ddb#diff-aa3cfd0b2c72db625cc18431127e4ab4

**Comment by ThorbenLindhauer** [comment]
What I implemented:

* Removed topic name from the client API protocol wherever possible (detailed changes see https://github.com/zeebe-io/zbc-go/issues/81)
* Removed topic name from log stream source pointers
