### ISSUE TITLE
Detect inconsistencies during initial log scan

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4152]
**Description**

We should know ASAP when our log is inconsistent to prevent any further issues arising from processing the wrong things in the wrong order. To that end, we can attempt to detect inconsistencies when reading the log on startup (e.g. when we build the index).

See zeebe-io/atomix#174 - similar idea.

**Comment by npepinpe** [comment]
@Zelldon didn't you implement something for this?

**Comment by Zelldon** [comment]
It depends what is meant by this issue. We detect inconsistency on reprocessing, but not on journal opening.

**Comment by npepinpe** [comment]
Ah, I thought we had added that as well on start. My bad then.

**Comment by npepinpe** [comment]
Fits in our current OKR topics

**Comment by MiguelPires** [comment]
When #3987 is closed, we will be checking that no inconsistencies are introduced when appending to the log. Even with that change, it's still possible that the log is already inconsistent when upgrading. Detecting gaps in the log when scanning it would prevent poisoning the log, but only in situations where something has been written but not committed. However, it's just as likely that inconsistencies have already been committed, in which case there is nothing we can do. I think that, if we're expanding our fault model to include all of the cases in these types of faults, then we'd have to do a lot more than this to be safe. It's my opinion that the benefit this would give us is small and outweighed by the possibility of introducing other bugs when versioning entries, which would be required to maintain backwards compatibility. I've checked this would Nicolas and he agreed this can be closed. I'll keep this open until tomorrow's daily, in case someone wants to object
