### ISSUE TITLE
PartitionID wrong type

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zeebe#416]
When I execute topology request and get cluster topology from the message pack I receive partition ID as uint64 and in SBE (ExecuteCommandRequest) we define that same value as uint16. 

This is a problem for Go client cause I have to do checking and converting to a type which is smaller in size, so fixing this on the client is not perfect and could lead to some unexpected behavior.

Can we maybe ensure on the broker side that I receive it as uint16?

**Comment by ThorbenLindhauer** [comment]
The broker should always encode `int` values with the smallest possible format (e.g. it the value is less than `2**7`, use `positive fixnum`, etc) . We should check if that is the case for this response.

**Comment by menski** [comment]
We looked at the hexdump of the topology response and open task subscription response and saw that the partition id was correctly encoded as `0x00`, which should be a positive fixint with value `0` as far as I understand the message pack spec. So we assume that the go message pack library not uses the smallest type for deserializing the value. Sam will investigate that on the go side.

**Comment by jsam** [comment]
Yes, thanks for help @menski <3

**Comment by menski** [comment]
If I remember this correctly this was an issue in the go msgpack library and not in the broker.
