### ISSUE TITLE
Refactor storage and journal

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4162]
The current storage implementation has lot of complexities which are not necessary. The different storage levels, which we are not using, increase the complexity.

**E.g.:**

On creation of an RaftLog we create an SegmentedJournal, which consist of different JournalSegments. On creating a new JournalSegment, we create a MappableJournalWriter, which can either be MappedJournalWriter or FileChannelJournalWriter.

If we open an reader we first open an SegmentedJournalReader, which are tracked by the SegmentedJournal. These will create MappableJournalReader in the corresponding JournalSegment, which also tracks the MappableJournalReader. This reader can either a Mapped or FileChannel-JournalReader. To increase the complexity all these classes have bi-directional access to the other properties. 

These bi-directional increase not only the complexity also cause issues on closing.
For example in the JournalSegment:

```java

  /**
   * Closes a segment reader.
   *
   * @param reader the closed segment reader
   */
  void closeReader(MappableJournalSegmentReader<E> reader) {
    readers.remove(reader);
  }


  /**
   * Closes the segment.
   */
  @Override
  public void close() {
    unmap();
    writer.close();
    readers.forEach(reader -> reader.close());
    open = false;
  }
```

If we call close it will call close on each readers, these readers will then call closeReader on the journal

```

  @Override
  public void close() {
    reader.close();
    try {
      channel.close();
    } catch (IOException e) {
      throw new StorageException(e);
    } finally {
      segment.closeReader(this);
    }
  }
```

This can cause concurrent modification exceptions, since we iterating over the same collection while removing. It also not really obvious for the reader what exactly is happening.

Since the readers are tracked also on multiple levels it can happen that we not clean up correctly.
![mme](https://user-images.githubusercontent.com/2758593/69621846-23a21e80-1040-11ea-9f09-3b8fc307db4c.png)

I had a benchmark with 395 open readers, where each of them holds an byte array of 2 Mb.

**Comment by npepinpe** [comment]
We will not currently refactor the journal/storage until we again tackle the issue of performance/low latency, at which point we should create specific issues for what we want to refactor.
