### ISSUE TITLE
Default config location

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4182]
**Description**

During our engine performance tests, we wanted to change some defaults in the broker.
We only get it working with setting the env. variable to the cfg location. This was for us a bit unexpected. The env. is a nice to have, but we would expected that the cfg file is normally always in the same place, in the config folder next to the bin folder. I would suggest that we still support a default cfg location, as we did before.

Either by setting the env variable in the broker script, if not specified OR some logic in the broker itself.

**Comment by pihme** [comment]
Please confer with @npepinpe . The way I understood him, we wanted to refrain from using a default location. But I may have misunderstood him.

The issues I had with the old way was that the configuration was hard-coded into the `broker.sh` and `gateway.sh` scripts as program arguments, and you couldn't overwrite it.

If we want to support it again, then I would strongly suggest to make it changeable. I would vote against any logic in the broker and gateway.

Note also that the operate team doesn't use any environment variable at all. They put the configuration in `/conf/application.yml` and by convention Spring picks it up from there.

So there is a trade off here between behaving like Zeebe used to behave in the past and behaving like any other Spring application would. (and my vote would be for the latter)

Also, if we make changes as a result of this issue, we also need to update the corresponding description in the documentation.

**Comment by npepinpe** [comment]
I'm also more inclined to follow Spring conventions, as one benefit of switching to Spring Boot is that configuring a Spring Boot application is well documented (e.g. in the pending PR of our Helm chart for 0.23.0, it still uses a config file, and only sets the `spring.config.location` to point to it). 

As far as I'm concerned this a deployment specific issue, but I'll admit I'm not that familiar with deploying Spring Boot applications - perhaps setting a default path as to file which contains actual defaults (as opposed to commented out) is more common and users would expect this? It was not my impression from reading the docs, however.

**Comment by Zelldon** [comment]
> The issues I had with the old way was that the configuration was hard-coded into the broker.sh and gateway.sh scripts as program arguments, and you couldn't overwrite it.

I get that point. Still we could set the env inside these scripts if the env doesn't exist.

> Note also that the operate team doesn't use any environment variable at all. They put the configuration in /conf/application.yml and by convention Spring picks it up from there.

Correct https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files which is much more convenient when it is automatically detected

> I'm also more inclined to follow Spring conventions, as one benefit of switching to Spring Boot is that configuring a Spring Boot application is well documented

Then we should do it the Spring way in the full not a mixed way right? :sweat_smile: So e.g. using application.properties or having the cfg next to the binary.


For me it feels totally inconvenient and I think with that we added a new source of error here, which we could easily avoid. It is not easy to detect. If you change something in the cfg you always need to have a look at the printed cfg as well and if you miss that you will probably also wonder later why it has no effect at all.

If you use docker you now also need to mount the cfg AND set the env. variable. Instead before just overwrite the default cfg. I like to avoid doing two things for one. 

But maybe it is just me.

@saig0 @berndruecker any thoughts on that?

**Comment by saig0** [comment]
I prefer to follow the Spring Boot conventions. So, putting the configuration in a `config` folder next to the binary (`/bin/config/application.yml`). We can benefit from the Spring Boot documentation and the existing conventions.

**Comment by pihme** [comment]
> 
> 
> I prefer to follow the Spring Boot conventions. So, putting the configuration in a `config` folder next to the binary (`/bin/config/application.yml`). We can benefit from the Spring Boot documentation and the existing conventions.

That would be clearer if we had two deliverables. Right now it is unclear to me whether you are configuring the standalone broker of the standalone gateway. And yes, you could merge the two configurations, but this will also introduce some confusion.

**Comment by berndruecker** [comment]
I agree that we should follow the Spring conventions - as this is what is expected and well documented. 
If we run one binary that is broker and gateway - that would result in a merged config file I guess - but I don't see big problem here. Whatever you want to config goes into that file - it can have one section for the broker and one for the gatway? For me that sounds quite intuitive and in sync what I would expect from a Spring Boot app.

**Comment by Zelldon** [comment]
I think the discussion shifts a bit from the real topic why I created this issue.

Currently I NEED to specify a env. variable to change the default config and this is for me unexpected.

See here https://github.com/zeebe-io/zeebe/blob/develop/dist/src/main/config/zeebe.cfg.yaml

```
 
# Zeebe broker configuration file
# ! ! ! ! ! ! ! ! ! !
# In order to activate the settings in this file, please set the following environment variable:
# export SPRING_CONFIG_LOCATION='file:./config/zeebe.cfg.yaml'
#
# Alternatively, you can also pass it as a command line argument:
# ./bin/broker --spring.config.location=file:./config/zeebe.cfg.yaml
# ! ! ! ! ! ! ! ! ! !
```

If we want to discuss the sections stuff we could do this here https://github.com/zeebe-io/zeebe/issues/4184 or here https://github.com/zeebe-io/zeebe/issues/4185

**Comment by pihme** [comment]
See #4185 for discussion on why having sections for broker and gateway is confusing, in my mind. Both in terms of providing a full template and in terms of explaining to the user which branches are relevant for which use case.

**Comment by berndruecker** [comment]
Ok - we should not need any environment variable for configuration. That is uncommon with Spring Boot apps

**Comment by npepinpe** [comment]
By default spring will load ./config/application.yaml, correct? So mounting your configuration file there should work out of the box? At least as far I understand with my limited spring boot experience.

**Comment by pihme** [comment]
> By default spring will load ./config/application.yaml, correct? So mounting your configuration file there should work out of the box? At least as far I understand with my limited spring boot experience.

This does work and is also mentioned in the documentation as an option. 

Still I understand Chris' assumption that he wants to make changes to the provided templates, and have them take effect without any additional steps (be it environment variable, or renaming a file)

**Comment by npepinpe** [comment]
Proposal:

Forget about `config/zeebe.cfg.yaml` and `config/gateway.cfg.yaml`. Instead, we follow Spring Boot conventions and provide the following:

1. `config/application.yaml` -> non-commented configuration for a broker with an embedded gateway and default configuration (e.g. cluster size 1, node id 0, partition count 1, etc.).
1. `config/application-full.yaml` -> fully commented configuration file which includes all settings as a reference for users (name can be `application-complete`, `application-template`, as you prefer). I would propose that it is uncommented, as I'm still not 100% sure of the value of fully commented out config files
1. `config/application-gateway.yaml` -> non-commented out configuration for a standalone gateway
1. `config/application-broker.yaml` -> non-commented out configuration for a broker without embedded gateway

> I thought about possibly merging the last two, as we do have a single deliverable, and it should be able to handle having both standalone gateway and broker in the same config file, as they more or less need to be used in conjunction. But it may be confusing for users?

The idea here is that by default Spring picks up `config/application.yaml`, and we set that to the default set up you need to be able to just run `bin/broker` and have a working Zeebe broker with no configuration. If you require different set ups, you can always copy the variants over the application.yaml, or if deploying via Docker/Kubernetes, mount a file there as you want. The variants are then mostly there as examples, but should also work out of the box.

I see two downsides however: one is that `application-PROFILE` is a Spring Boot feature, so we either have to make it clearer that these are not profile, or alternatively, we could see if profiles would help us better improve things here as a feature (e.g. `broker-with-gateway` profile, `standalone-gateway` profile, etc.), though my understanding of profiles is that's not really meant to be the goal.

The second one is again coming back to us having a single deliverable for two applications, so it's not clear what `application.yaml` refers to - the argument here is that in most cases, especially when people are discovering Zeebe, the application for them will be the broker. Once a user gets to a point of deploying a cluster + a standalone gateway, it may be reasonable to expect them to have more knowledge of how to deploy Zeebe, and they would know that depending on which app they launch (`bin/broker` or `bin/gateway`) what `application.yaml` refers to.

Let me know what you think, or if I was not clear on any point! Also, all the names I offered are of course examples, I am terrible at naming things so don't be scared by things like `broker-with-gateway` profile name :sweat_smile:

**Comment by menski** [comment]
if `application-broker.yaml` classes with spring boots profile handling we can also do `application.broker.yaml` to make sure we are not mixing stuff up

**Comment by Zelldon** [comment]
I like the proposal thanks 👍as far as I understood  I could then easily change the application.cfg without setting any env. and broker will pick it up right? 😀

**Comment by pihme** [comment]
I like the proposal, except for the `application-full.yaml` part. I think this file will be more confusing than helpful. And since this file carries most of the documentation burden, I would not want too much confusion here.

Instead I would go for configuration file interlaced with comments (and the exporter section of Broker all commented out) :
```
# Paths:
# Relative paths are resolved relative to the installation directory of the broker.
# ----------------------------------------------------

zeebe:
  broker:
    # Sets the timeout for each start and closing step.
    #
    # Broker bootstrap and closing is divided in several individual steps.
    # Each step should take at max the defined stepTimeout, otherwise the bootstrap is aborted.
    #
    # This setting can also be overridden using the environment variable ZEEBE_BROKER_STEPTIMEOUT.
    # stepTimeout: 5m

    gateway:
      # Enable the embedded gateway to start on broker startup.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_ENABLE.
      enable: true

      network:
```

**Comment by pihme** [comment]
If we make changes to this, we should also give a heads up to the Cloud team and Operate team.

My best knowledge is that Operate put their own `application.yaml` file, so we need to make sure we don't overwrite it, if we now provide one of our own.

Cloud uses an environment variable to define the configuration file.

I don't think there will be problems for either of them, but just to keep them in mind. If we do have a "standard" way of configuring Zeebe, we should also recommend it to the other teams, IMHO.

**Comment by npepinpe** [comment]
Yes, I wasn't sure about `application-full` to be honest, so I'm OK with having comments in the default `application.yaml` with the more unused settings commented out (if I understood you correctly).

Good point about keeping the other teams in the loop, I already notified Alastair about this, but I'd greatly appreciate if you guys can coordinate with both teams as well on this. Like you said, I don't expect this to be problematic for either (I think the Cloud mostly uses env variables, and Operate would probably just overwrite our application.yaml on deployment), but they will know better.

**Comment by pihme** [comment]
I think one missing piece is still how to deal with `startup.sh` and the `$ZEEBE_STANDALONE_GATEWAY` flag.

If we use `application.yaml` for the configuration defaults for broker, I don't know what @Zelldon 's expectation is what should happen for the standalone gateway.

Do we expect users to mount the right config file into the container? Do we want to default to one of the gateway config templates?

Please put your heads together (I mean those guys who are there longer than me), cause I am unable to anticipate what "feels natural" for this situation. And I felt this detail got overlooked so far.
