### ISSUE TITLE
Fix bugs reported by SonarCloud introduce by Atomix merge

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4205]
**Description**

With merging of atomix in our code base https://github.com/zeebe-io/zeebe/pull/4136 we introduce some new code flaws and some bug where reported by sonar cloud which we should tackle. This is more a general issue and can be seen as a reminder. It should be splitted in smaller issues for several bug types etc.

**Comment by npepinpe** [comment]
To revisit once we're done refactoring/merging Atomix.
