### ISSUE TITLE
A missing variable/nested property can not be handled

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4212]
**Describe the bug**
In an expression, a missing variable or a non-existing nested property can not be handled. It is handled as a failure (i.e. `ValError`) in the FEEL engine. Some boolean expressions, like an equal comparison (e.g. `= x = "here"`), can deal with it and returns `false`. 

But it is not possible to check if a value/property is missing using the `null` value. For example,

```
not_existing = null
// false

not_existing != null
// true
``` 

This behavior is not intuitive.

**To Reproduce**
* workflow with an exclusive gateway with a condition `x != null`
* create a workflow instance without variables
* verify that the sequence flow with the condition is taken

**Expected behavior**
A missing variable/nested property can be compared to `null` and returns `true`.

Alternatively, provide a method to check if a variable/property is not present (e.g. `isPresent(x)`). 

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by saig0** [comment]
Current workaround:
* check if a variable has a specific type
```
if(x instance of string) then x else "default"
```

**Comment by korthout** [comment]
I'd like to re-evaluate the priority of this issue.

**Comment by asaf** [comment]
@korthout this is a big issue, we avoided upgrading because of this.

some examples we ended up with but felt like it's way to compex to be used:

```
=(get value (products, "lists") instance of list and count(get value (product, "lists")) > 0
=not(get value(person.org, "manager") instance of context
```

btw, in general, it's very annoying that Zeebe fails when accessing a nonexisting variable, this makes it very hard to ask if "foo.bar.baz" exists in gateways and such.


Thanks.

**Comment by saig0** [comment]
@asaf, thank you for your input. We'll work on this soon.

My idea is to use the `null` check for non-existing variables and variables with `null` values. This should work also for nested properties if the property or the variables doesn't exist.

```
x = null 
// true if x is null or doesn't exist

x.y = null  
// true if x is null or doesn't exist
// true if y is null or doesn't exist
```

If the value or nested property is accessed without `null` check then an incident can be raised.

Do you have any proposals for your other examples?

**Comment by asaf** [comment]
@saig0 I think that fixing null equality is top priority
and safe get (e.g., "x.y.z") even if `x` or `y` does not exist will solve most of the issues

If you can't do it, then at least `get value (obj, "x.y.z")` should do the trick

**Comment by asaf** [comment]
@saig0 per your last comment, please pay attention that in case `y` does not exist on `x` an expr such:

```
x.y != null
```

will cause an error that x context does not contain y.

this behavior blocks checking `x.y == null`

**Comment by saig0** [comment]
Open PR: https://github.com/camunda/feel-scala/pull/176

**Comment by npepinpe** [comment]
Will this be fixed by https://github.com/zeebe-io/zeebe/pull/5355?

**Comment by saig0** [comment]
I'll open a new PR. I need to add some integration code :)
