### ISSUE TITLE
RocksDB out of memory can be reproduced 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4230]
**Description**

Previous we had the problem that we were not able to reproduce RocksDB out of memory, which where reported by customers. I was able to reproduce the RocksDB out of memory. It just needs to trim some parameters in the configuration.

![out-of-memory](https://github.com/Zelldon/perf-tests/blob/master/metrics/rocksdb-memory-no-rep-tmpfs-entry256-128mbsegm.png?raw=true)

I changed in this benchmark the replication to zero, the maxEntrySize to 256KB and the log segment size to 128. Furthermore we used a tmpfs instead of a persistent storage.

Benchmark configuration can be found [here](https://github.com/Zelldon/perf-tests/tree/master/tmpfs/benchmark)

**Comment by npepinpe** [comment]
Blocked by #4606

**Comment by Zelldon** [comment]
Related Informations https://github.com/zeebe-io/zeebe/issues/3988

**Comment by korthout** [comment]
RocksDB is new ground for me. Discussed with @pihme and @Zelldon to first dig into how RocksDB works, then checking out our Grafana RocksDB dashboard and then rerun the benchmark with configuration to reproduce the OOM. After that we can further discuss why this might occur and how we might solve it.

**Comment by korthout** [comment]
After running a benchmark with a similar configuration (but without tmpfs) for about 20 hours, I was unable to reproduce the OOM. Likely the OOM occurred because all data was persisted in memory (because of tmpfs) and reducing memory footprint by writing to disk is not possible as the file system is also in memory.

**Comment by Zelldon** [comment]
Yes I think as we discussed yesterday this is probably the reason. I think we can close this. Maybe you can reproduce it with big state, so not completing the tasks.

**Comment by korthout** [comment]
@Zelldon I'll give that a try

**Comment by korthout** [comment]
@Zelldon Only starting new instances does not increase the active memory size of rocksdb. It does grow the SST tables size linearly. 
![image](https://user-images.githubusercontent.com/3511026/87050648-d2295700-c1fe-11ea-8953-fb083adf9bd3.png)
I feel that this will also not reproduce the OOM:
![image](https://user-images.githubusercontent.com/3511026/87050748-f84ef700-c1fe-11ea-8732-09385af2808d.png)

**Comment by korthout** [comment]
@Zelldon I want to verify that the OOM was produced due to tmpfs. I'll reopen this until I've verified it.

**Comment by korthout** [comment]
Verified that indeed OOM is easily reproduced with tmpfs. This is just a logical outcome of using only memory as storage.
