### ISSUE TITLE
Gateway doesn't distribute work equally

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4232]
**Description**

It seems that the gateway doesn't spread the work equally over the partitions. Just run a benchmark and you will see that mostly partition 2 gets 200 events less to process as the other partitions.

At this point in time I don't know why this is the case, but I have seen this now in actually all benchmarks I run.

Further investigation of the behavior and Gateway code lead to that the round robin is not ideal on all cases, especially the combination of create workflow instance and activate job request. 

If you create a workflow instance on partition the first activate job will go to next partition. If you have N partitions then you will test N partition before reaching the partition where you created the instance. This is because the `BrokerActivateJobsRequest extends BrokerExecuteRequest`,
which implements:

```java
  @Override
  public boolean requiresPartitionId() {
    return true;
  }
```

This information is used in the [BrokerRequestManager](https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/impl/broker/BrokerRequestManager.java) to determine the partition:

```java

  private BrokerAddressProvider determineBrokerNodeIdProvider(final BrokerRequest<?> request) {
    if (request.addressesSpecificPartition()) {
      final BrokerClusterState topology = topologyManager.getTopology();
      if (topology != null && !topology.getPartitions().contains(request.getPartitionId())) {
        throw new PartitionNotFoundException();
      }
      // already know partition id
      return new BrokerAddressProvider(request.getPartitionId());
    } else if (request.requiresPartitionId()) {
      if (request instanceof BrokerPublishMessageRequest) {
        determinePartitionIdForPublishMessageRequest((BrokerPublishMessageRequest) request);
      } else {
        // select next partition id for request
        int partitionId = dispatchStrategy.determinePartition();
        if (partitionId == BrokerClusterState.PARTITION_ID_NULL) {
          // could happen if the topology is not set yet, let's just try with partition 0 but we
          // should find a better solution
          // https://github.com/zeebe-io/zeebe/issues/2013
          partitionId = Protocol.DEPLOYMENT_PARTITION;
        }
        request.setPartitionId(partitionId);
      }
      return new BrokerAddressProvider(request.getPartitionId());
    } else {
      // random broker
      return new BrokerAddressProvider();
    }
  }
```

**Comment by Zelldon** [comment]
I think @falko also mentioned that Customers noticed different memory consumption on different nodes, where each node was leader of one partition.

**Comment by npepinpe** [comment]
We changed the logic this year, and I would expect this isn't the case anymore, but someone should verify this.

**Comment by falko** [comment]
I did not observe this as a problem recently. More prominent was an uneven distribution of partition leadership among the brokers which would force the gateway to also distributed unevenly to brokers. But on the partition level, I have no data point.
