### ISSUE TITLE
Leverage Spring configuration for exporter configuration

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4236]
**Description**

Before switching our configuration to Spring, we used to instantiate exporter configuration as a `Map<String, Object>`. From there, we would pass this to `Gson` as a JSON tree and rely on it to instantiate the bean from the user, e.g. `Configuration#instantiate(Class)`. The choice to use Gson here stemmed from our TOML parser which was also using Gson under the hood.

So, to sum up, the way it currently works now, is our exporter specific `ExporterConfiguration` is created with the `Map<String, Object>`, and it will lazily create an intermediate `JsonTree` representation that is used to instantiate the bean.

This seems to be like technical debt - it currently works, hence why it wasn't necessary to tackle it now, but I feel like we could better leverage Spring for this. For me this means I would need to do more research here (e.g. can we do partial instantiation with Spring, kind of like a pull-parser can do?).

@pihme any thoughts? Like I said, this isn't urgent as it still works, but my impression is there might be a better way now to do this with Spring

**Comment by pihme** [comment]
Relates to #4037

**Comment by npepinpe** [comment]
Oh, sorry, I missed that one :sweat_smile: Definitely a duplicate, closing in favor of it :+1:

**Comment by pihme** [comment]
I would replace GSON with Jackson. From there I am not sure whether there is a need to change.

There is two aspects we currently try to configure: 
* The list of exporters
* The configuration for each exporter

I think the mechanism is fine, as it is. I probably wouldn't change it given the flexibility it now provided.

The only thing that warrants a change, in my opinion is if we use Spring Boot for exporter configuration and registration/discovery. This would then allow to configure exporters in a decentralized way.

Long term, my personal vision is that exporters are no longer part of the Broker at all. 
Instead the environment (e.g. the cloud, helm charts, whatever) would provision these. In this scenario the Broker wouldn't need to care about exporters anymore. 

Each exporter would then report it's last exported event log record to a central log deletion service, the broker would do the same (except in this case it's not the last exported record, but the last snapshoted and replicated record). 
So then the environment is responsible for the life-cycle of the exporters, the log deletion service can use service discovery to find out which consumers are reported, and we get a little more decoupling.

Got a little longer. You asked for my thoughts, and not all of them are covered by #4037

**Comment by npepinpe** [comment]
That's a great idea! Not sure how it would look in practice without adding too much complexity to the deployment, but getting the exporters out of the broker has been something we've thought of but don't know how to achieve properly for a while, we should definitely explore this!
