### ISSUE TITLE
I can configure an upper limit for the number of partitions per topic

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#424]
* safety feature for when topic creation API is accidentally misused

**Comment by meyerdan** [comment]
Maybe this should just be a documented constant for now

**Comment by Zelldon** [comment]
do we need an upper limit? or can this issue be closed?

**Comment by ThorbenLindhauer** [comment]
I'd say we close this, because it is no longer possible to create topics and partitions at runtime and we can trust users to get their configs right.
