### ISSUE TITLE
Execution of StreamProcessorHealthTest takes to long

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4240]
**Description**

I was wondering why this test `StreamProcessorHealthTest`takes so long. For example the test `shouldMarkUnhealthyWhenReprocessingRetryLoop` takes around 13 seconds. It seems that the update to the clock does not work as expected. Might be due to the `runUntilDone` endless loop.

**Comment by Zelldon** [comment]
The problem is that the ActorClock is not accessed in a ActorThread, which means it will used the normal system clock.

```

  static ActorClock current() {
    final ActorThread current = ActorThread.current();
    return current != null ? current.getClock() : null;
  }
```

```

  @Override
  public HealthStatus getHealthStatus() {
    if (actor.isClosed()) {
      return HealthStatus.UNHEALTHY;
    }

    if (!processingStateMachine.isMakingProgress()) {
      return HealthStatus.UNHEALTHY;
    }

    // If healthCheckTick was not invoked it indicates the actor is blocked in a runUntilDone loop.
    if (ActorClock.currentTimeMillis() - lastTickTime > HEALTH_CHECK_TICK_DURATION.toMillis() * 2) {
      return HealthStatus.UNHEALTHY;
    } else {
      return HealthStatus.HEALTHY;
    }
  }
```

**Comment by deepthidevaki** [comment]
Good catch. 
I'm wondering if this could be a problem in a production run. `getHealthStatus` is called by health monitors which in our case is an actor but not the same as StreamProcessor actor.
