### ISSUE TITLE
Massive cache misses due to big default maxEntrySize

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4249]
# Description

## Summary

During our engine latency investigation we found out that the Atomix Journal is one of our hot spots, where the most time is spent. Someone could argue that this is kind of expected, since we have to read and write a lot. We found out if we change the `maxEntrySize` and `segmentSize` then the latency (performance) changes significant. 

## Tests

We tested different entry and segment size configurations. The test consist of starting a simple workflow with just a start and end event. We had a look at the latency between `START_EVENT:ELEMENT_ACTIVATING` and `START_EVENT:ELEMENT_ACTIVATED`.

The warm up phase started 1000 workflow instances. The test also run again 1000 workflow instances. The code can be found [here](https://github.com/Zelldon/perf-tests/tree/master/perf-test)

<details>
<summary>Test Results</summary>

Description to the output: 
<pre>
  public String asCSV() {
    return startEventName
        + ";"
        + endEventName
        + ";"
        + getAVG()
        + ";"
        + getRMSSD()
        + ";"
        + min
        + ";"
        + max
        + ";"
        + count
        + ";"
        + histogram.values().stream().map(String::valueOf).collect(Collectors.joining(";"));
  }
</pre>
<pre>
09:38:56.640 [] INFO  io.zeebe.broker.workflow - Run 42 tests. Print results...
entrySize 64.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.6993554779999996;0.4296406753920768;0.330595;12.955831;1000;0;18;729;194;57;1;0;0;1;0;0;0;0
entrySize 128.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7403657850000004;0.6412458036079539;0.342898;20.174112;1000;0;4;702;227;66;0;0;0;1;0;0;0;0
entrySize 256.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.871426137000001;0.5635341758019697;0.458952;15.076269;1000;0;3;377;473;141;4;0;0;2;0;0;0;0
entrySize 512.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8540596729999999;0.2121526987680905;0.431633;2.840521;1000;0;6;357;476;159;2;0;0;0;0;0;0;0
entrySize 1024.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8932052330000007;0.8440467310205934;0.497207;26.493805;1000;0;2;331;496;168;2;0;0;0;1;0;0;0
entrySize 4096.0 KB - log segment size 0.5 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.9649286140000003;1.3272545648950749;0.483598;32.233247;1000;0;1;258;480;254;4;1;0;0;2;0;0;0
entrySize 64.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.6220735549999995;0.13303132524237757;0.218699;1.845042;1000;1;14;892;65;28;0;0;0;0;0;0;0;0
entrySize 128.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.69167771;0.7874825892891073;0.257684;25.141709;1000;0;4;845;119;30;1;0;0;0;1;0;0;0
entrySize 256.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7956015409999991;0.8394936289082435;0.293709;26.230504;1000;0;4;585;350;57;3;0;0;0;1;0;0;0
entrySize 512.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8782247450000001;0.7345771103910197;0.48363;23.100569;1000;0;1;285;597;116;0;0;0;1;0;0;0;0
entrySize 1024.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.2156697810000008;0.8469535031278767;0.473084;25.821999;1000;0;5;153;164;660;17;0;0;0;1;0;0;0
entrySize 4096.0 KB - log segment size 1.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.2308103820000005;0.3281062392199563;0.478872;4.273327;1000;0;7;135;225;593;40;0;0;0;0;0;0;0
entrySize 64.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.6599105410000005;0.5859553600347499;0.217993;18.917407;1000;1;40;822;106;30;0;0;0;1;0;0;0;0
entrySize 128.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7256795449999988;0.701344340718257;0.27038;21.942562;1000;0;2;754;201;41;1;0;0;1;0;0;0;0
entrySize 256.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8382921699999996;0.6993408350754283;0.466384;21.942205;1000;0;1;346;587;63;2;0;0;1;0;0;0;0
entrySize 512.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.0262774509999997;0.6631939841174501;0.649465;19.761107;1000;0;0;1;721;268;9;0;0;1;0;0;0;0
entrySize 1024.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.7702658170000019;0.7689514961712507;1.259689;17.772324;1000;0;0;0;0;925;71;0;2;2;0;0;0;0
entrySize 4096.0 KB - log segment size 16.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;7.188507929000001;0.849770065215872;3.755985;10.760618;1000;0;0;0;0;0;1;605;387;7;0;0;0;0
entrySize 64.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7257121109999997;0.5465954917962776;0.211097;16.484873;1000;1;4;757;185;51;1;0;0;1;0;0;0;0
entrySize 128.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8064409989999994;0.5734243549007892;0.262323;16.433861;1000;0;2;549;362;84;0;2;0;1;0;0;0;0
entrySize 256.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7940582619999986;0.41895997726134654;0.296794;12.487047;1000;0;3;598;345;53;0;0;0;1;0;0;0;0
entrySize 512.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.034136158;0.6465456451710753;0.565652;18.56266;1000;0;0;2;719;265;13;0;0;1;0;0;0;0
entrySize 1024.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.7377939910000018;0.6435634185270875;1.15916;15.159091;1000;0;0;0;0;947;50;1;1;1;0;0;0;0
entrySize 4096.0 KB - log segment size 64.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;7.169417315999996;0.9907313486186952;4.991566;17.129558;1000;0;0;0;0;0;1;616;368;15;0;0;0;0
entrySize 64.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.6422015799999993;0.5087158113603737;0.34235;13.946914;1000;0;10;899;35;53;1;0;1;1;0;0;0;0
entrySize 128.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.6719790990000007;0.25667195215370137;0.264538;7.413017;1000;0;2;870;96;30;1;0;1;0;0;0;0;0
entrySize 256.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8061710639999993;0.40823603069330267;0.272114;12.134476;1000;0;2;476;464;57;0;0;0;1;0;0;0;0
entrySize 512.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.0775836370000003;0.4525509262703641;0.381157;6.855764;1000;0;1;3;592;390;11;3;0;0;0;0;0;0
entrySize 1024.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.6396500590000025;0.538854156185405;0.767223;6.653157;1000;0;0;0;1;933;62;4;0;0;0;0;0;0
entrySize 4096.0 KB - log segment size 128.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;8.009636965;1.1500120614723432;4.04781;15.03395;1000;0;0;0;0;0;1;354;532;113;0;0;0;0
entrySize 64.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8438387319999998;0.3197387764514873;0.228567;5.608031;1000;1;4;461;343;187;2;2;0;0;0;0;0;0
entrySize 128.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7706310320000004;0.5671532072079853;0.281658;17.499005;1000;0;4;685;251;56;3;0;0;1;0;0;0;0
entrySize 256.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8195660350000009;0.23008557960899678;0.283486;3.68766;1000;0;3;337;597;60;3;0;0;0;0;0;0;0
entrySize 512.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.0016310539999995;0.30713061350039594;0.370597;3.214882;1000;0;1;2;786;204;7;0;0;0;0;0;0;0
entrySize 1024.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.6877228639999984;0.5270400585750035;0.655674;4.785212;1000;0;0;1;1;917;81;0;0;0;0;0;0;0
entrySize 4096.0 KB - log segment size 256.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;7.240919989999988;0.9411906807807511;4.302974;20.82496;1000;0;0;0;0;0;1;596;383;20;0;0;0;0
entrySize 64.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.687913602999999;0.43572519522990827;0.25443;13.444925;1000;0;6;780;178;34;1;0;0;1;0;0;0;0
entrySize 128.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.7096281230000007;0.6695508801170894;0.249278;20.885573;1000;1;1;821;140;34;2;0;0;1;0;0;0;0
entrySize 256.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;0.8545631109999996;0.42143309779429955;0.314701;12.332672;1000;0;2;205;726;63;3;0;0;1;0;0;0;0
entrySize 512.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.0963122200000006;0.46830054971202123;0.361921;10.420799;1000;0;1;2;541;441;14;0;0;1;0;0;0;0
09:38:56.654 [] INFO io.zeebe.broker.workflow - entrySize 1024.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;1.6997604730000004;0.6766549225037863;0.772016;10.041829;1000;0;0;0;1;942;52;0;4;1;0;0;0;0
09:38:56.654 [] INFO io.zeebe.broker.workflow - entrySize 4096.0 KB - log segment size 512.0 MB;START_EVENT:ELEMENT_ACTIVATING;START_EVENT:ELEMENT_ACTIVATED;7.187188305999998;0.9321319815848834;4.298758;15.187114;1000;0;0;0;0;0;1;627;348;24;0;0;0;0
09:38:56.655 [Broker-0-Snapsh
</pre>
</details>

## Cache Misses 

Based on these results we found out that smaller entry size bring us better performance. After thinking about it we found out that the real time was spent due to cache misses. We thought about the `maxEntrySize` and evaluated some real world deployments how big they actually are at max. The biggest process model @falko found was around 140 KB. so we decided to test further with `256KB` to be safe.

To track the cache misses we used the [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) and had run this command:
```bash
./profiler.sh -e cache-misses  -d 30 -i 1ms -o traces -f outputfile.txt
```

If we used the default configuration we saw on the top three the following results. You can also find the results [here](https://github.com/Zelldon/perf-tests/blob/master/tmpfs/cache-misses/entry4mb-128.txt)

```

--- 2204118897 misses (30.95%), 2204 samples
  [ 0] jlong_disjoint_arraycopy
  [ 1] java.lang.ThreadLocal.get
  [ 2] sun.nio.ch.Util.getTemporaryDirectBuffer
  [ 3] sun.nio.ch.IOUtil.read
  [ 4] sun.nio.ch.FileChannelImpl.read
  [ 5] io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext



--- 1016972174 misses (14.28%), 1017 samples
  [ 0] copy_user_enhanced_fast_string_[k]
  [ 1] copyout_[k]
  [ 2] copy_page_to_iter_[k]
  [ 3] shmem_file_read_iter_[k]
  [ 4] new_sync_read_[k]
  [ 5] vfs_read_[k]
  [ 6] ksys_read_[k]
  [ 7] do_syscall_64_[k]
  [ 8] entry_SYSCALL_64_after_hwframe_[k]
  [ 9] __GI___read
  [10] sun.nio.ch.FileDispatcherImpl.read0
  [11] sun.nio.ch.FileDispatcherImpl.read
  [12] sun.nio.ch.IOUtil.readIntoNativeBuffer
  [13] sun.nio.ch.IOUtil.read
  [14] sun.nio.ch.FileChannelImpl.read
  [15] io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext

--- 908023203 misses (12.75%), 908 samples
  [ 0] jlong_disjoint_arraycopy
  [ 1] java.lang.ThreadLocal.get
  [ 2] sun.nio.ch.Util.getTemporaryDirectBuffer
  [ 3] sun.nio.ch.IOUtil.read
  [ 4] sun.nio.ch.FileChannelImpl.read
  [ 5] io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext
  [ 6] io.atomix.storage.journal.FileChannelJournalSegmentReader.hasNext

```

If we used the as entry size 256KB and log segment size 128 MB as configuration we saw on the top three the following. You can find the results also [here](https://github.com/Zelldon/perf-tests/blob/master/tmpfs/cache-misses/entry256-128.txt)

```
--- 26000916 misses (4.92%), 26 samples
  [ 0] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 1] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 2] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 3] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 4] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 5] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 6] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 7] start_thread

--- 21000294 misses (3.98%), 21 samples
  [ 0] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 1] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 2] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 3] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 4] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 5] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 6] start_thread

--- 14999911 misses (2.84%), 15 samples
  [ 0] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 1] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 2] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 3] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 4] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 5] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 6] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 7] /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
  [ 8] start_thread
```

If we search for the readNext in the results we can find it on 6th place.

```

--- 7000341 misses (1.33%), 7 samples
  [ 0] jlong_disjoint_arraycopy
  [ 1] sun.nio.ch.NativeThreadSet.add
  [ 2] sun.nio.ch.FileChannelImpl.position
  [ 3] io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext
  [ 4] io.atomix.storage.journal.FileChannelJournalSegmentReader.hasNext
```

As you can see the cache misses are much less then before, this is also reflected in the overall latency as we saw above in our tests.

As reference I tested that on a my machine with a [Intel® Core™ i7 Prozessor 8665U](https://ark.intel.com/content/www/de/de/ark/products/193563/intel-core-i7-8665u-processor-8m-cache-up-to-4-80-ghz.html). It has a `8MB`! smart cache, which means this last layer of the cache is shared between the cores, so it is no surprise that we getting cache misses here.

## Performance

To make sure this would work in a more "real-world" scenario we setup some benchmarks to test this further. To set the `maxEntrySize` and `logSegmentSize` in a benchmark we added the following environment variables to our `zeebe-values.yaml` file.

On our first tests we had the problem that the brokers went fast out of memory because of a smaller segment size. To reduce the log size we configured the snapshot period to one minute.

```yaml
env:	
  - name: ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE	
    value: "256KB"	
  - name: ZEEBE_BROKER_DATA_LOGSEGMENTSIZE	
    value: "128MB"	
  - name: ZEEBE_BROKER_GATEWAY_ENABLE	
    value: "true"	
  - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD	
    value: "1m"
```

### Throughput

As reference this is the throughput of a default configuration:

![default-throughput](https://github.com/Zelldon/perf-tests/blob/master/metrics/troughput-metrics-entry-4mb-segment-128mb.png?raw=true)

This is the throughput of 256KB entry size and 128 MB and segment size.

![smaller-cfg-throughput](https://github.com/Zelldon/perf-tests/blob/master/metrics/troughput-metrics-entry-256kb-segment-128mb.png?raw=true)

We can see the throughput was doubled.

### Latency

To track the latency of a workflow instance, job activation and job life time we added some more metrics to the system. Take a look at https://github.com/zeebe-io/zeebe/pull/4233 for more information.

As reference again the latency of the default configuration

![default-latency](https://github.com/Zelldon/perf-tests/blob/master/metrics/latency-metrics-entry-4mb-segment-512mb.png?raw=true)

The latency with 256KB entry size and 128 MB segment size.

![smaller-cfg-latency](https://github.com/Zelldon/perf-tests/blob/master/metrics/latency-metrics-entry-256kb-segment-128mb.png?raw=true)

We can see we were able to bring the processing latency for events and command down by a factor  5 - 10. The latency was mostly before between 100 - 250 ms with the smaller cfg it was 10-25 ms.

The processing execution was reduce by factor two. Before it was around 2.5 seconds with the smaller cfg it was ~ 1 sec.

#### Journal
During the latency investigation we found out that the Journal implementation is sub-optimal for our use case the latency here can be really effected by the maximum entry size. There are some issues in the Journal we need to fix:

  * Reader throws half buffer away #4248 
  * Reader resets buffer needless #4252 

#### Event count #4255 

We can think about the current event count. We currently have really much small events, which is probably not necessary but due to this each event needs time to be processed, read etc, which we could reduce when we reduce the event count.

#### MMap File usage https://github.com/zeebe-io/zeebe/issues/4274

We should think about using a mmap file instead of our current approach, since we are really IO intense and need to search and read a lot. Atomix also supports mmap and it has not the problems of reading big chunks of data. It just reads from the buffer the entry size.

Memory-Mapped Files are also better handled by java and the OS so we can avoid here probably the problems of cache misses better, at least we get a lot of performance gain since we don't need to copy the buffers between the layers.

**Comment by Zelldon** [comment]
I started to use the Java Mission Control and saw with this also a high peak on reading, especially on taking snapshots. Each read with 8MB took around 6 seconds!


![screenshot2020-04-0911:46:17](https://user-images.githubusercontent.com/2758593/78881919-bb386480-7a57-11ea-915d-ca7bde83fc27.png)

**Comment by npepinpe** [comment]
So I've been wondering, how could we make this backwards compatible? We want to change the defaults, but if you have an existing installation, we can't do that. I think we can reach a compromise, where we allow reading previous entries that were bigger than the new max message size, but disallow writing entries that are now larger. That leaves us with two cases:

1. Currently running workflows which will end up being stuck
1. Unable to support previously acceptable payloads

These cases however don't brick your cluster - you can simply reconfigure to what used to be the default, and restart, and it will work without any data loss. Not great, but could be acceptable.

**Comment by Zelldon** [comment]
We gain no benefit if you still read the 4 Or 8 MB. But maybe we can improve the read logic in the reader.

**Comment by npepinpe** [comment]
> Or do you mean you only read larger chunks if the entry size is bigger then the default?

Yes, exactly that :slightly_smiling_face: So it's more of a fallback for people who already wrote larger entries

**Comment by Zelldon** [comment]
Maybe it makes more sense to invest in the mmap file? Then maybe we could keep the size?

Maybe it is possible to map old journals? Or we just use for old segments the normal and for new mmap.

What do you think?

**Comment by npepinpe** [comment]
I already tried it, you can totally go from mapped to file and back again on the same journal, so no loss there.

My proposal is just about reading entries larger than the max size for back wards compatibility. Though now I realize these entries may need to be replicated, therefore written on the other side, so... :thinking:

**Comment by npepinpe** [comment]
Still the case, unfortunately not a priority at the moment. I would like to tackle it next quarter or the one after, however. Let's see if I can make this happen.

**Comment by falko** [comment]
I thought the switch to memory-mapped files mitigated this issue?

**Comment by npepinpe** [comment]
It did, but it didn't remove it either, and we may have just traded it for page faults. Generally reducing the max message size a user can send (while keeping a way to have larger batch sizes) is something that we should do, as most of our systems work best with smaller amounts of data (we're not optimized to store large amounts, and never will be).

**Comment by falko** [comment]
Well, the cache misses are not caused by users actually sending big messages but by taking `2*maxEntrySize` as buffer size.
Nevertheless, if we want to reduce the default `maxEntrySize` we must fix the issue with large job activation batches that exceed maxEntrySize.

**Comment by Zelldon** [comment]
For me it would make sense to set the size lower in this quarter, for several reasons. We can discuss this f2f.

**Comment by npepinpe** [comment]
I'd like to lower the default soon to start indicating not just via documentation but how the software is used that Zeebe is not a data store, and you should keep only very lightweight context information on it, but this is a product decision. However do list any reason you have here or directly to me, as that's still useful - and of course you can also always talk to product directly if you want.

**Comment by npepinpe** [comment]
We have other issues to change the maxMessageSize - I think here though the root cause is pretty much fixed (i.e. the cache misses). Closing, but feel free to challenge if we should look into cache misses more.
