### ISSUE TITLE
Reduce the general event count to reduce overall execution latency

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4255]
**Description**

As we saw with https://github.com/zeebe-io/zeebe/issues/4249 each event/command needs time to be processed, at least ~ 5ms with good configurations. In our performance workshop we were able to bring it down to 0.7ms but only with a tmpfs. In real-world scenario or at least most of our users wouldn't use that. 

If we take a simple process with just a start event, service task and end event we will produce roughly these events:

- 2 workflow instance creation
- 2 process start
- 4 start event
- 1 SEQ
- 2 Service Task act
- 7 Job (incl. CREATE,ACTIVATE, COMPLETE)
- 2 Service Task complete
- 1 SEQ
- 4 end event
- 2 process completion

So we have ~26 commands/events to process for just a single workflow instance. This means we need at least 26 * 5 = 130 ms to run a workflow instance (excl. the time the job handler needs etc.)
This also means we have to access the database for each record to get the current state and store it back after processing it. Actually we currently do it more often see here #4227  We need to decode and encode before and after the processing, write follow up events, which need to be replicated etc.

If we would reduce the events this would mean we would get lower latency in the overall workflow instance execution time, because we would reduce all that preparation, encoding, decoding work we need to do now to process several records.

For example if we always process until a wait state then we can access the db once for retrieving all information we need work and store it back after the processing. No need to access the db in between. This would mean for this example the first 11 events could be trimmed to one command. 

**Pros:**

 * less IO (less reads and writes)
 * less DB access during processing a workflow instance
 * less encoding decoding records
 * better performance (latency)
 * we can simplify the processing since we process it directly

**Cons**

 * we can't interrupt the instance execution in the same way as we had before
 * incidents resolving might need to re-start on the safepoint
 * actor scheduler executes bigger tasks then before can't do things in between (but this is no longer an issue since raft used different thread pool)

**Comment by Zelldon** [comment]
I think I have an idea to test this out and to not write events anymore. It would be possible to just write commands from the CommanApi to the logstorage dispatcher and the stream processor has its own dispatcher, which he directly consumes. He can directly call the next step processor. If there is nothing more on the stream processor dispatcher, he reached a wait state and can consume the next command. 

It would be possible to write also these events to the actual log, but just ignore it on reading. This should be not so hard to try out.

**Comment by npepinpe** [comment]
Writing events is necessary with our new processing concept. However writing less events is always useful - just not a priority at the moment, and probably won't be for the next year.
