### ISSUE TITLE
Java client should send the client type and version with his auth request 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4265]
**Is your feature request related to a problem? Please describe.**

On camunda cloud we have sometimes bug reports / incidents which might be already fixed with the latest version of the client, but the user uses a old client version.

**Describe the solution you'd like**

We would like to detect the client type and version, on requesting the auth token. This would make incident investigation much easier, since we then don't need to ask the user for this kind of information if there went something wrong. It would also make it possible to correlate failures with know bugs.

We thought about adding this kind of information in the user agent header on the client HTTP request. 

**Describe alternatives you've considered**
The alternative would be to ask the user for this kind of information.

**Additional context**

The content of the user agent should at least contain:

 * client type, e.g. java client
 * client version, e.g. 0.22.2

**Comment by npepinpe** [comment]
Please set it for every request.
