### ISSUE TITLE
Export interface should not use raw type for parameterized Record Type

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4275]
**Description**

Currently the Exporter#export interface looks like this:

```

  void export(Record record);
```

It uses a raw type which causes warnings on implementing exporters.
It should be changed to:

```

  void export(Record<?> record);
```

Further information:
http://www.javapractices.com/topic/TopicAction.do?Id=224
> When generics were introduced in JDK 1.5, raw types were retained only to maintain backwards compatibility with older versions of Java. Although using raw types is still possible, they should be avoided:
> 
> - they usually require casts
> - they aren't type safe, and some important kinds of errors will only appear at runtime
> - they are less expressive, and don't self-document in the same way as parameterized types

**Comment by saig0** [comment]
Agree on this. What are the alternatives? One method per record value type?
