### ISSUE TITLE
Searching entry on taking snapshot is not efficient

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4287]
**Description**

I started to use the Java Mission Control and saw with it has a high peak on reading, especially on taking snapshots. Each read with 8MB took around 6 ms to find the corresponding entry.

![screenshot2020-04-0911:46:17](https://user-images.githubusercontent.com/2758593/78881919-bb386480-7a57-11ea-915d-ca7bde83fc27.png)

If we would have this https://github.com/zeebe-io/zeebe/issues/3987 we could avoid this.

**Comment by npepinpe** [comment]
I would close this for now as we will fully switch to mmap storage - there might still be some improvement, however looking for the position on snapshot isn't something we do often (at most every minute), so to shave a few ms every minute, I wouldn't spend too much time on that.
