### ISSUE TITLE
io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest.testClusterEventService is flaky

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4307]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 
Seen it a few times, but not necessarily more than other flaky tests

- Does it block your work?
To some extent, blocks merging PRs.

- Do we suspect that it is a real failure?
Could be; the `DefaultClusterEventService` is known to be quite buggy, so I wouldn't be surprised.

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error
expected:<3> but was:<0>
Stacktrace
java.lang.AssertionError: expected:<3> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest.testClusterEventService(DefaultClusterEventServiceTest.java:193)
...
</pre>
</details>

**Hypotheses**

Nothing in particular, but this service is known to be buggy in general, see https://github.com/zeebe-io/zeebe/issues/4154

**Logs**

<details><summary>Logs</summary>
<pre>
14:55:06.742 [] INFO  io.zeebe.test - Test started: testClusterEventService(io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest)
14:55:07.262 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
14:55:07.266 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Member activated: Member{id=1, address=localhost:1, host=localhost, properties={}}
14:55:07.342 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
14:55:07.347 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
14:55:07.444 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
14:55:07.447 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
14:55:07.447 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Member activated: Member{id=2, address=localhost:2, host=localhost, properties={}}
14:55:07.453 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
14:55:07.454 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
14:55:07.456 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
14:55:07.459 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
14:55:07.460 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Member activated: Member{id=3, address=localhost:3, host=localhost, properties={}}
14:55:07.464 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
14:55:07.466 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
14:55:07.469 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
</pre>
</details>

**Comment by korthout** [comment]
Seen again in https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/staging/1671/pipeline/82

**Comment by korthout** [comment]
I'm mistaken, the merged PR above is just not part of the backport yet. I guess that's fine.
