### ISSUE TITLE
Use zeebe_health metrics to extract label values in Grafana dashboard

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4308]
**Description**

At the moment, we use a combination of `jvm_info` and `zeebe_stream_processor_*` metrics to extract labels. This has several disadvantages:

1. `jvm_info` is a generic Prometheus Simple Client metric, so any other Java process scraped will most likely export it; this means we resort to using a custom "all" regexp to properly match pods, for examples, which is not very portable, and definitely unexpected.
1. We don't get partition labels until we process something.

The `zeebe_health` metric is a good alternative, as we always report all our partitions, and it has all necessary information. Additionally, if it isn't there, it most likely means something went wrong very early on.

Let me know what you think, @deepthidevaki and @Zelldon

**Comment by Zelldon** [comment]
Do you have a specific example and maybe a solution how to do it differential because from the issue description I'm not really sure what you're talking about sorry :sweat_smile: Do you mean the dashboard variables?

**Comment by npepinpe** [comment]
Yes, sorry, thats exactly what I meant!

**Comment by Zelldon** [comment]
Aah ok you mean this

![grafana](https://user-images.githubusercontent.com/2758593/79302999-18b43180-7eee-11ea-8116-d18e5d67af77.png)

I think it makes sense what you wrote.

**Comment by deepthidevaki** [comment]
Agree. That would make sense.
