### ISSUE TITLE
Use the Zeebe Model API in the Broker

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#431]
AT:
* replace the broker model with the new Model API
* use the Model API in the broker test cases
* add the Model API to the build / pom

**Comment by menski** [comment]
@saig0 who should review this?

**Comment by menski** [comment]
@saig0 what do you think about having a WorkflowModels class for common reusable workflow models similar to the [ProcessModels](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/models/ProcessModels.java) class in camunda-bpm-platform. This could reduce the test boiler plate.

**Comment by saig0** [comment]
@menski if you think that makes it easier for the tests then it's ok. But I'm not a big fan because you need to switch to another class to understand the test case.

**Comment by menski** [comment]
@saig0 yeah I agree that this could be a problem, it's fine for now just saw the we often use the same simple process over and over again in this change
