### ISSUE TITLE
Extract the rules when an workflow instance event is processed

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4334]
**Description**

* currently, every handler can implement `shouldHandleState()` to determine if the event should be processed
  * the inheritance of the handlers make it hard to see when an event is handled
  * no central rules for the different handlers
* the goal is to have explicit and clear rules when events are handled or not

**Comment by saig0** [comment]
The downside of the current approach is that it is not clear from the outside  (e.g. an exporter view) that an event was not processed. We just write a logging statement but mainly for debugging. 

We could think about preventing the situation by not writing follow-up events if the processing was interrupted by a user command or external/internal trigger.

**Comment by npepinpe** [comment]
Please close if this isn't relevant after the next refactoring.

**Comment by saig0** [comment]
Good point. We improved already in the last refactoring. 
The [new proposal](https://github.com/zeebe-io/enhancements/pull/9) will change the behavior in a way that commands will be rejected if the preconditions are not met.
