### ISSUE TITLE
Clean up atomix and zeebe parallel classes and hierarchies

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4344]
**Description**

Currently we have a RaftStateMachine implementation, which is used per default in atomix. It is also used in their tests. Furthermore there exist a bunch of classes and implementation of interfaces for snapshots etc, which are set per default but actually replaced by our implementation in the broker.

We should remove the uncessary classes and migrate to our classes, such that the tests are also running with our classes.

This will reduce some of the unnecessary complexity we currently have.

**Comment by npepinpe** [comment]
If we rewrite the partitioning service, we can better control the bootstrapping of the partitions. The `Atomix` facade is just a wrapper to coordinate the partitioning service and the cluster management (see the Atomix `ZeebeTest` and helpers for an example). By writing our own partitioning service, we could have more control on how partitions are created (inject the implementations that we want and create them in the order we want), and could have a proper supervision hierarchy to control partitions.

Definitely a topic where we need to discuss more, but yeah there is still more work on the Atomix front :)
