### ISSUE TITLE
SnapshotChunks are not validated on InstallRequests

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4345]
**Describe the problem**

Currently we don't calculate or verify checksums on the InstallRequests, which means we can't guarantee that we writing the correct chunk.

Our snapshot replication (periodically) contains verification of chunks https://github.com/zeebe-io/zeebe/blob/develop/logstreams/src/main/java/io/zeebe/logstreams/state/FileSnapshotConsumer.java#L93

**Comment by deepthidevaki** [comment]
For streamprocessor snapshot replication we added whole snapshot checksums (https://github.com/zeebe-io/zeebe/pull/4278) . May be we can add the same to Install requests?
