### ISSUE TITLE
Possible corrupted snapshot on InstallRequest

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4346]
**Describe the bug**
On our snapshot replication we make snapshots valid IF all chunks have been received.
Each chunk contains as header the chunk counts. It is always checked whether there exist enough files to make the snapshot valid.

On the InstallRequest we just check for the `complete` flag of the last received chunk.

1. This is problematic since it can happen that the requests are received out of order.
2. If we fail to write a chunk we abort the pending snapshot. This means we delete everything and set `this.pendingSnapshot = null`. When we receive new chunks afterwards we continue with them and create a new pendingSnapshot, since we do not check the counts we might complete the snapshot with missing chunks.

On our own snapshot replication we keep the snapshot Id and ignore all other chunks if this happens.

**To Reproduce**
Inject a `IOException` on writing the chunk.

**Expected behavior**
We don't count this snapshot as valid or retry the write.

**Proposals**

 * Check the snapshot chunk count. 
 * Either delete the file on IOException OR marke the pending snapshot as invalid
 * only mark snapshot as valid if enough chunks have been received

 The best would be to use the same classes which we use for our snapshot replication.

**Comment by deepthidevaki** [comment]
I don't think it happens. If writing a chunk fails, the follower respond with an error response. Then the leader resets the snapshot replication and restarts it.

**Comment by Zelldon** [comment]
Hey @deepthidevaki I think you're right. When I created the issue I had also the assumption all chunks are send at once, but it seems it is more done sequentially which makes it in that case safer. Thanks.
