### ISSUE TITLE
Run chaos tests on our gke cluster

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4361]
**Description**

Currently we run our chaos tests in the infra cluster. This has some requirements and limitations like:

 * tests should not run to long
 * we can't easily run/deploy via helm, we have to run the template command to get the yaml files, which then need to be applied to the cluster
 * elastic is not deployed during the tests 
 * we have no real insights like logs, metrics etc.

I would suggest that we try to run our chaos tests still in the jenkins pipeline but deploy them in our google cloud, in a namespace called `zeebe-chaos`. 

**Pro's**

 * We can add tests with elastic 
 * We can then use elastic to verify certain things, like all instances are completed or something similar
 * We are able to root cause issues, since we have access to the logs
 * We can observe the metrics via grafana

**Cons**

Right out of my head I have none. Probably we need to find a way to do that in our cluster. But I assume it is enough to store the credentials in our jenkins ?

**Comment by Zelldon** [comment]
### Handover

During the last weeks we had several discussions and ideas and we concluded that it would be best to run our tests, experiments and benchmarks in the Camunda Cloud environment. They had setup us a new GKE called `ultrachaos` where we can deploy new Zeebe Clusters with there used configuration which makes the tests, experiments and benchmarks also more realistic. I adjusted our benchmark setup here https://github.com/zeebe-io/zeebe/pull/5183

Currently it is not possible via API to create new Zeebe clusters, which means as start we would need to create a Zeebe cluster which is used as target and is long living. After https://github.com/camunda-cloud/enhancements/blob/master/CEP017-programmatic-access-to-console.md is implemented we can adjust our setup, such that we creating new zeebe clusters on running the experiments.

Yesterday I run the first chaos day to try the different cluster sizes and compare it with our known setup https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-days/2020-08-20/README.md. 

Together with @afirth I was able to create a new serviceaccount, role and rolebinding, see this commit to know what was applied https://github.com/zeebe-io/zeebe/commit/17ff0d155a0cd6032149f6aeb29e1fb83a48a6b5 . The serviceaccount is under the namespace `zeebe-chaos` in the ultrachaos k8 cluster.

I added the team as cluster admins so all should be able to create, get, update and delete new resources.

We need to apply the serviceaccount token to the Infra database such that it is available in our jenkins job. The kubernetes context need to be changed then in the chaos pipeline. After we did that we should be able to run automated chaos experiments against the new cloud. Our current INFRA DRI will be in vacation next week and I'm on parental leave in September which is why I created an related INFRA ticket, which described everything what we need https://jira.camunda.com/browse/INFRA-1723.

It would be nice if someone of you (@pihme, @saig0 or @npepinpe ) can take this over during my parental leave. Feel free to ask questions if there is anything unclear.

@npepinpe @menski  I will remove my assignment since I will not finish this before the parental leave

**Comment by Zelldon** [comment]
Created today a PR to run automated chaos experiments in camunda cloud

For reference in the following I summarized how to achieve that.

### What I did to achieve that

In order to be able to run the chaos experiments in a different gke, we need to get access to this cluster first.
This is normally done by kubernetes servicesaccounts. I deployed in the `ultrachaos` in a new namespace called `zeebe-chaos` a serviceaccount with certain roles and rolebindings. The details you can find here https://github.com/zeebe-io/zeebe/commit/c1f69ab6bdc010dbb21f88f250cb078be1743766 .

After creating the serviceaccount and retrieving the related token, I created an INFRA Jira issue, such that the infra team can add the token to there vault. This is necessary to become available in our jenkins and not visible for the public. Related issue https://jira.camunda.com/browse/INFRA-1723

With several resources, like:

 * https://docs.armory.io/docs/spinnaker-install-admin-guides/manual-service-account/
 * http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/

and others I was able to create a kubeconfig which works. See related kubeconfig change https://github.com/zeebe-io/zeebe/commit/d696b6c81865e37d806c5a582e8d74279799d9cb . The user and related token is added during the pipeline execution.

The chaos experiments have expected different labels for the zeebe pods, since they are used to work with helm. I added a new flag which allows us to switch between the environments https://github.com/zeebe-io/zeebe-chaos/commit/b4e1f8fbc38cd5059b5e01a4dfe9fbceaff363c9

During the chaos experiments we need running workers to complete workflow instances. Previous `ultrachaos` gke was not allowed to retrieve docker images from our gcr. I added the default camunda cloud serviceaccount to our IAM. I followed this https://medium.com/google-cloud/using-single-docker-repository-with-multiple-gke-projects-1672689f780c

At the time I worked on this it was not yet really possible to create new Zeebe clusters on the fly. This is the reason why I had to pre-create a zeebe cluster in camunda cloud. In the Zeebe and Operate Developers orga. I chosed as cluster plan type `Production M`, since this fits mostly our previous setup. In order to run our workers, I create also ZeebeClient credentials for them and deployed the credentials as a secret in the same namespace. See this https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/setup/cloud-default/cloudcredentials.yaml for an example

When we can create Zeebe clusters and ZeebeClient credentials via scripts, we can of course replace that.

After all these changes it finally worked :) 

![chaos](https://user-images.githubusercontent.com/2758593/91431220-5c398780-e860-11ea-83a9-fa6099cc63a2.png)

**Comment by afirth** [comment]
great stuff @Zelldon

**Comment by Zelldon** [comment]
Thanks @afirth :) and of course thanks for all the help !
