### ISSUE TITLE
Finding compactable index from position should return an index closer to the given position

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#4373]
**Description**

Hot fix for #4350 relies on ZeebeIndexMapping to find a compactable index from the given position. It only finds an approximate index <= the actual compactable index. 
This has implications that the tests need to make sure the indexing density is one or write many events, otherwise snapshots are not taken. It also affects a production deployment if the indexing density is too sparse the compaction is not as frequent as we want. 

To address this issue `AtomixRecordEntrySupplier::getIndexedEntry` should return more accurate compactable index and preferably not entirely rely on index mapping density.

**Comment by npepinpe** [comment]
Adding it to the journal refactor milestone - while this is slightly out of scope, it may inform some decisions for the future (i.e. use a sparse index or use a B+ tree). This does not need to be finished for the milestone to be completed! Again, it's just so we're aware of it when refactoring.

**Comment by npepinpe** [comment]
I don't think this is necessary anymore. The new journal handles ASQNs, so the `AtomixRecordEntrySupplier` simply relies on `seekToAsqn`. There is another issue to improve it, so this issue becomes redundant I think.
