### ISSUE TITLE
Long Polling is blocked even though jobs are available on the broker 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#4396]
**Describe the bug**

While using the java client to complete jobs we observed that sometimes the job worker will hang for the long polling timeout although jobs are available in the broker.

**To Reproduce**

Not totally clear. I often saw it by having a constant stream of create workflow instances and then at the same time a job worker running. Periodically the job worker was waiting for up to 20s before failing to activate jobs and then on repolling it found new jobs.

**Expected behavior**

Job workers should always be able to acquire jobs if they are available without running in any blocking timeout.

**Environment:**
 - OS: Linux/Camunda Cloud
 - Zeebe Version: 0.23.0
 - Configuration: default

**Comment by menski** [comment]
We the following assumptions at the moment:

1. Race condition between activating long polling and creating new jobs, i.e. a job is create in the moment the gateway transitions to long polling
2. Gateway does not handle backpressure of activate job batch commands correctly and switches to long polling, although tasks are available and then does not get notified that jobs are available

**Comment by kjozsa** [comment]
We can confirm this bug, we also experienced this many times in the past weeks.

**Comment by ezolnbl** [comment]
it is strange because there 2 different times here:
jobPollInterval which is set to default 100 ms
and a requestTimeout "Set the request timeout for activate job request used to poll for new job" and set to default 20 seconds
For me this 2 are doing the same functionality but the first is constantly querying the broker and the second accomplish a long poll but why can these both configured at the same time? Shouldn't be only one of them, or they exclusively override each other?
There is also a third timeout configuration which is clearly the job's working timeout, how a long a worker can work on a given job.

**Comment by wenminglei** [comment]
We have been troubled by this problem for three weeks, and sincerely hope that you can make optimizations.

**Comment by pihme** [comment]
@kjozsa @ezolnbl @wenminglei: Thank for your comments. I will be looking into the issue. Before that, however, I would like to answer the questions that have been raised and suggest a workaround which you can use right now.

Why is there a jobPollInterval and a requestTimeout and how do they relate to each other?

The `requestTimeout` defines the length of a long polling job request. During this request, no other polling will take place. The request will complete when either the desired number of jobs have been returned, or through timeout, whichever comes first. 
The `jobPollInterval` is the time between the end of one long poll and the begin of the next. 

Is it possible to acquire multiple jobs?

Yes that is possible, if you set `maxJobsActive`:
```
      client
          .newWorker()
          .jobType("foo")
          .handler(new DemoJobHandler())
          .maxJobsActive(10)
          .open();
```
I am not familiar with camel sqs, but I guess that this is slightly diffent from `MaxMessagesPerPoll`. 

At first, when no jobs are running, it will request `maxJobsActive` jobs. The next time, some of the jobs are already completed, but you might still have `n` jobs running and the worker will request. `maxJobsActive - n` new jobs. So it's less about how many jobs to request and more about how many jobs should be running concurrently in the worker.

By the way, you can also configure a long polling of an hour and a high max job count. This can work ok if the jobs come trickling in at a sustainable rate. But it could also happen that you get a large number of jobs all at once, which could overwhelm your worker. 

Now to the workaround - you can reduce the timeout for the job poll requests individually:
```
      client
          .newWorker()
          .jobType("foo")
          .handler(new DemoJobHandler())
          .requestTimeout(Duration.ofSeconds(1))
          .open();
```
This doesn't remove the bug, but it makes the undesired behavior less pronounced.

Hope this helps. 

(btw, my comments are based on the Java client. I am less familiar with the go client)

**Comment by pihme** [comment]
# Analysis of Race Condition Assumption

There is strong evidence for assumption 1 - race condition between jobs being activated and switching requests to long polling. There is a blind window between the moment the request is received and the moment the request is enqueued for long polling. In the current implementation the gateway will query the brokers one by one for jobs. During this time the request is not yet enqueued for long polling on the gateway. If the gateway receives a new jobs notification from a broker which it has already visited, then this notification gets lost.

## Thinks that don't add up
There are two self-healing mechanisms:
- Each subsequent job activation after the request has been enqueued for long polling will fulfill the request
- There is a periodic retry every 10 seconds

Thus the maximum time of a request being stuck would be 10 seconds, not the timeout of the request. Not sure if the reporters of this bug were aware of this distinction though.
Also, for systems with high volumes of job creations this should not produce the observed behavior.

Thus, this alone maybe doesn't fully explain the observed hebavior.

**Comment by pihme** [comment]
# Analysis of Backpressure Assumption
There is also strong evidence for assumpton 2. If the available jobs are on a broker which rejects requests due to backpressure it is effectively as if the broker would have no jobs at all. 

@menski It is not clear to me what the desired behavior is for this case. We could be more aggressive in querying the back pressure broker again, but given that it is already limiting requests this might be counterproductive. Please advise

**Comment by menski** [comment]
@pihme regarding the backpressure issue, my initial thought was that we should not block/long-poll a request which is not answered because of back pressure. I would assume that we return an empty response to the client, so the client can decide when to poll again. I'm not sure if we should propagate the partial backpressure back to the client, as there might be brokers which are not suffering yet.

Alternative if we want to block even on backpressure we have to make sure that this request is retried even without a notification on the gateway to prevent starvation.

**Comment by salaboy** [comment]
Reported in the CSharp and Spring clients: https://github.com/zeebe-io/spring-zeebe/issues/98

**Comment by jooble** [comment]
Hi, i have similar problem. I noticed its 2 days ago when i had zeebe version 0.23.0, after that i updated cluster on 0.24.4 and this version fixed all my problem, but not today that problem has returned and i don`t know what happened.
I have 0.24.4 zeebe broker and zeebe gateway and spring zeebe.
