### ISSUE TITLE
Increase max snapshot count to be more resilient

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4398]
**Description**

There exist several cases how snapshots can be corrupted, since we currently using only one snapshot this means the node has no back up plan. This means that on fail-over an corrupted snapshot can lead to bigger problems. 

We reduced the max snapshot count to one, since we found out that it is unsafe to keep more snapshots and the related log. The problem was that we might end in situations where the log contains gaps, which could lead to inconsistency if we fail-back to a previous snapshot.
You can read more about that here https://github.com/zeebe-io/zeebe/issues/3573. The problematic situation can only happen if the leader sends a snapshot via raft to a slower follower.

**Proposal**

In order to be more resilient on fail-over I would suggest to bring back the maximum snapshot count and set it to e.g. three. To avoid the problem described above, the follower should truncate the log if he received a new snapshot from the leader via raft. This should only be done if the leader send a snapshot because the follower was to slow, because this is only the situation where we can end in a inconsistent log.

On our normal snapshot replication, which we do periodically, this will not happen since we also continue with sending related events/commands. In this case it is not necessary to truncate the log here. 

To reduce the persisted log size and the kept data in-memory I would also suggest to reduce the snapshot interval to 5 minutes. This would mean we keep the same data as we do currently, since we have a snapshot interval of 15 minutes and a max snapshot count of one.

**Comment by npepinpe** [comment]
After discussion, we keep the focus on cloud deployments as opposed to bare metal deployments. This means the likelihood of file corruption (e.g. bitrot) is very low, so we will focus on mitigating errors that can occur through us (e.g. replication) instead of random corruption.

**Comment by Zelldon** [comment]
As written here https://github.com/zeebe-io/zeebe/issues/4423#issuecomment-641122566 we currently focus on the cloud. We introduced new mechanism to avoid snapshot corruptions in #4641 based on checksums. I will close this for now until we see a need again for this.
