### ISSUE TITLE
Allow to configure raft intervals

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#440]
Raft uses three static time intervals currently:

```
public static final int HEARTBEAT_INTERVAL_MS = 250;
public static final int ELECTION_INTERVAL_MS = 400;
public static final int FLUSH_INTERVAL_MS = 500;
```

These intervals define when an election is triggered or buffered events are written to the log. The heartbeat/election intervals maybe have to be adjusted to match the network round trip time. Therefore these intervals should be configurable by the user.

**Comment by Zelldon** [comment]
Perhaps we can use RaftProperties for the properties which are set by the user to avoid misconception?
