### ISSUE TITLE
Add configuration parameter to enable memory mapped files for non-replicated log storage

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#4413]
**Description**

Expose a configuration option to enable memory mapped file for log storage.

The user can set the environment variable `ZEEBE_BROKER_DATA_USEMMAP` to enable this feature.

If the user sets this option to `true` but also uses replication we will log a warning and disable this option to not prevent the broker from starting.

**Comment by menski** [comment]
@npepinpe regarding

> If the user sets this option to `true` but also uses replication we will log a warning and disable this option to not prevent the broker from starting.

I would push for this to easily test the behavior for non replicated tests. Let me know if this is a blocker for you.

**Comment by npepinpe** [comment]
As discussed, the broker will fail to start if replication is on, as warnings may be ignored and we cannot currently guarantee safety if replication is used with the memory mapped file storage.
