### ISSUE TITLE
Improve on skip compaction log message

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4414]
**Description**

It seems the following log statement is somehow broken:

```
ZeebeRaftStateMachine5947999{partition=raft-partition-partition-3} - Skipping compaction of non-compactable index 5802441 (first log index: {})
```

More Context:

```
2020-04-29 13:42:22.409 CEST
Received all snapshot chunks (123/123), snapshot is valid
2020-04-29 13:42:22.419 CEST
Purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5947999-14-1588160541853, metadata=DbSnapshotMetadata{index=5947999, term=14, timestamp=2020-04-29 11:42:21,853}}
2020-04-29 13:42:22.420 CEST
Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5899299-14-1588160482227, metadata=DbSnapshotMetadata{index=5899299, term=14, timestamp=2020-04-29 11:41:22,227}}
2020-04-29 13:42:22.482 CEST
Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5899299-14-1588160482227, metadata=DbSnapshotMetadata{index=5899299, term=14, timestamp=2020-04-29 11:41:22,227}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@4871f610
2020-04-29 13:42:22.482 CEST
Search for orphaned snapshots below oldest valid snapshot with index 5947999 in /usr/local/zeebe/data/raft-partition/partitions/3/pushed-pending
2020-04-29 13:42:22.482 CEST
Compacting Atomix log up to index 5947999
2020-04-29 13:42:22.482 CEST
Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5947999-14-1588160541853, metadata=DbSnapshotMetadata{index=5947999, term=14, timestamp=2020-04-29 11:42:21,853}}
2020-04-29 13:42:22.483 CEST
ZeebeRaftStateMachine5947999{partition=raft-partition-partition-3} - Skipping compaction of non-compactable index 5802441 (first log index: {})
```

It is logged when compaction doesn't happen, but actually I'm not 100% sure what exactly it tells me.

Is there are reason why we now use these ContextualLoggers?

\cc @deepthidevaki @npepinpe

**Comment by npepinpe** [comment]
This came about because we sometimes log that we trigger compaction, but do not actually compact as the index is in deemed "non-compactable". I didn't want to write what that means as that's implementation detail (meaning it's in the first segment so there is nothing below to compact), but I still want to be aware so we don't think compaction is broken.

Feel free to propose a better statement. As for the context logger, I agree, I wanted to add context since we didn't have the partition there, but actually since we're single threaded we could just use the MDC for the Raft thread :man_shrugging:

**Comment by Zelldon** [comment]
> I didn't want to write what that means as that's implementation detail (meaning it's in the first segment so there is nothing below to compact), but I still want to be aware so we don't think compaction is broken.

For me it was a bit confusing, because it was not clear what the numbers really tell me here. I mean why I can't compact if I have an index `5947999` and `5802441` :sweat_smile: 

Furthermore the output is somehow broken.

**Comment by npepinpe** [comment]
The thing is, if I explained why we're not compacting, we're coupling it to the underlying log storage implementation. I think it's OK that not every body knows what this means, the important part is that we are skipping it so it's expected. But yeah, feel free to fix it and improve the message if it's unclear :+1:
