### ISSUE TITLE
I can deploy a simple workflow as YAML

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#442]
AT:
* in addition to BPMN XML, I can deploy a simple workflow as YAML file

**Comment by saig0** [comment]
Protocol Change:
* DeploymentEvent: add property "resourceType" of type Enum: BPMN_XML | YAML_WORKFLOW
* DeploymentEvent: rename property "bpmnXml" to "resource"

**Comment by menski** [comment]
@saig0 I would like to change the wording in the docs a little bit as *simple* can be misinterpreted in docs in my opinion. Could you please review this pull request https://github.com/zeebe-io/zeebe/pull/453. Thanks
