### ISSUE TITLE
Reference model for getting started tutorial fails to deploy

### ISSUE THREAD

**Issue by pinkertonpg** [zeebe-io/zeebe#4421]
**Description**

This finished workflow model linked to in the Getting Started Tutorial does not deploy on Zeebe 0.23.1: https://github.com/zeebe-io/zeebe/blob/0.23.1/docs/src/getting-started/img/order-process.bpmn

Attempting to deploy it gives me two errors, referencing missing '='.

```
$ zbctl --insecure deploy order-process.bpmn 
Error: rpc error: code = InvalidArgument desc = Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following errors:
'order-process.bpmn': - Element: Message_155nrcd > extensionElements > subscription
    - ERROR: Expected expression but found static value 'orderId'. An expression must start with '=' (e.g. '=orderId').
- Element: SequenceFlow_1girnrf > conditionExpression
    - ERROR: Expected expression but found static value 'orderValue>=100'. An expression must start with '=' (e.g. '=orderValue>=100').
```

**Environment**
I have Zeebe cluster and operate running in a Kubernetes cluster, using the helm charts.

<details><summary>zbctl status</summary><p>
```
$ zbctl --insecure status
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.23.1
Brokers:
  Broker 0 - master-zeebe-0.master-zeebe.pgp-zeebe.svc.cluster.local:26501
    Version: 0.23.1
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 1 - master-zeebe-1.master-zeebe.pgp-zeebe.svc.cluster.local:26501
    Version: 0.23.1
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 2 - master-zeebe-2.master-zeebe.pgp-zeebe.svc.cluster.local:26501
    Version: 0.23.1
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Leader
```
</p></details>

**Possible fix?**
Disclaimer, I'm just an infrastructure person trying to set up and test out Zeebe, I know nothing of BPMN so this might not be an appropriate fix.

I was able to get this to deploy properly by changing the two references to `orderID` and `orderValue` in the .bpmn to `=orderID` and `=orderValue`. It then deployed successfully and I was able to view the workflow in Operate. If it's that simple I'm happy to open a PR, but would want some confirmation that it's a valid fix first.

**Comment by saig0** [comment]
Hi @pinkertonpg :wave: 

Thank you for reporting this! You're right that the equal signs `=` are missing in the BPMN workflow. 
Looking forward to see your PR :+1:
