### ISSUE TITLE
Message Events Process is confusing for users

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4422]
**Description**

The process shown at [Message Events](https://docs.zeebe.io/bpmn-workflows/message-events/message-events.html) is a bit confusing, since it seems the service task is directly completed and we wait until we receive a message which tells us that the money was collected.

We should try to re-model this process.

Related Zeebe Forum post 

https://forum.zeebe.io/t/is-the-zeebe-task-blocking-or-synchronous/1183

**Comment by Zelldon** [comment]
Alternatively we could describe that the service task is used as trigger for an external process, which will send a message when the system is done.

**Comment by npepinpe** [comment]
Opened https://github.com/camunda-cloud/camunda-cloud-documentation/issues/146
