### ISSUE TITLE
RFC: Cluster bootstrapping with single configuration file

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#443]
#### Current Bootstrapping Requirements

To bootstrap a Zeebe cluster every node requires a different configuration file which contains specifics for the node.

1. the `host`/`port` argument has to be configured in a way that other nodes/clients can access it
1. the `initialContactPoints` have to be set on all nodes except for one, which is the bootstrap node and creates the `internal-system` topic

#### Limitations

With this requirements it is not possible to create a single configuration and elastically scale a cluster, as every node requires an own configuration. For example `docker-compose scale` or a stateful set on a kubernetes cluster do not allow to set specific configurations/environment variables for every instance of the cluster.

#### Proposal

1. the `host` should only be used to bind to an interface, so that `0.0.0.0` is a acceptable default configuration
1. allow to specify advertised addresses for all APIs (https://github.com/zeebe-io/zeebe/issues/298)
1. allow to use environment variables inside the configuration file, for example to map environment variables to the advertised addresses
1. decouple `initialContactPoints` from bootstrapping and allow not reachable contact points, this would allow to specify a general list of probably available points in a cluster and on bootstrap the broker would try to sync with any of them until it was successful
1. allow manual bootstrapping by adding another non-topic command `bootstrap` similar to the `topology` command, this can be send to any node in the cluster and would trigger the creation of the `internal-system` partition on that node
1. to ease single node/get started setups add `bootstrap` option to config to trigger bootstrapping on startup, which behaves as if there are not `initialContactPoints` are specified at the moment

**Comment by menski** [comment]
@hawky-4s- and @AndreaGiardini any input from a ops perspective on this? Do you things this would solve problems in a kubernetes environment?

@ThorbenLindhauer do you thing the proposal for the boostrapping (4 + 5 + 6) are possible and sensible?

**Comment by ThorbenLindhauer** [comment]
Sounds good to me.

**Comment by menski** [comment]
> A possible solution for that would be a proxy which talks to the client and abstracts the cluster.

I agree that there is a use case for this. But this is not in the scope of the normal Zeebe Cluster setup so I would exclude it from this proposal. Nevertheless I plan to build this kind of proxy in the near future.

What would be interesting for this is issue is if it is possible with kubernetes to expose the whole cluster or if this in general not possible? Would be great if you could give feedback on this.

**Comment by menski** [comment]
We started to allow specifying configuration parameters as environment variables. Also the architecture changed to contain kind of proxy in front of the cluster which should ease cluster setups.
