### ISSUE TITLE
TimerCatchEventTest.testLifeCycle flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4437]
**Summary**

- How often does the test fail? - Once so far
- Does it block your work? - not really
- Do we suspect that it is a real failure? - unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error Message

No event found matching the criteria

Stacktrace

io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
	at io.zeebe.engine.util.client.WorkflowInstanceClient$ExistingInstanceClient.lambda$static$0(WorkflowInstanceClient.java:151)
	at io.zeebe.engine.util.client.WorkflowInstanceClient$ExistingInstanceClient.cancel(WorkflowInstanceClient.java:200)
	at io.zeebe.engine.processor.workflow.timer.TimerCatchEventTest.cleanup(TimerCatchEventTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
10:17:08.558 [] INFO  io.zeebe.test - Test finished: shouldCreateTimerBasedOnBoundaryEvent(io.zeebe.engine.processor.workflow.timer.TimerCatchEventTest)
10:17:08.558 [] INFO  io.zeebe.test - Test started: testLifeCycle(io.zeebe.engine.processor.workflow.timer.TimerCatchEventTest)
10:17:13.650 [] INFO  io.zeebe.test.records - Test failed, following records where exported:
10:17:13.706 [] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":4295297456,"timestamp":1588414628568,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfOWY4Y2NkYWQtZjE2Ny00ODIzLWE0MTctZjc1Y2U5Yjk2NGE2IiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0idGVzdExpZmVDeWNsZSIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2Y5ODc0NDViLTA1MTEtNDMyYS04YzM2LWM4MjBiNGIwNTRmMCI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfNTRmZTk0ZGQtOTU4Zi00OTk0LTgyZGMtNDQ2NmIzOWVmNjM1PC9vdXRnb2luZz4KICAgIDwvc3Rhc...
10:17:13.707 [] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685432,"position":4295300568,"timestamp":1588414645593,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfOWY4Y2NkYWQtZjE2Ny00ODIzLWE0MTctZjc1Y2U5Yjk2NGE2IiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0idGVzdExpZmVDeWNsZSIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2Y5ODc0NDViLTA1MTEtNDMyYS04YzM2LWM4MjBiNGIwNTRmMCI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfNTRmZTk0ZGQtOTU4Zi00OTk0LTgyZGMtNDQ2NmIzOWVmNjM1PC9vdXRnb2luZz4K...
10:17:13.708 [] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685432,"position":4295303784,"timestamp":1588414645594,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfOWY4Y2NkYWQtZjE2Ny00ODIzLWE0MTctZjc1Y2U5Yjk2NGE2IiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0idGVzdExpZmVDeWNsZSIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2Y5ODc0NDViLTA1MTEtNDMyYS04YzM2LWM4MjBiNGIwNTRmMCI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfNTRmZTk0ZGQtOTU4Zi00OTk0LTgyZGMtNDQ2NmIzOWVmNjM1PC9vdXRnb2l...
10:17:13.708 [] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685432,"position":4295307000,"timestamp":1588414645595,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfOWY4Y2NkYWQtZjE2Ny00ODIzLWE0MTctZjc1Y2U5Yjk2NGE2IiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0idGVzdExpZmVDeWNsZSIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2Y5ODc0NDViLTA1MTEtNDMyYS04YzM2LWM4MjBiNGIwNTRmMCI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfNTRmZTk0ZGQtOTU4Zi00OTk0LTgyZGMtNDQ2NmIzOWVmNjM1PC9vdXRnb2lu...
10:17:13.734 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":4295310216,"timestamp":1588414628595,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":-1,"variables":{},"bpmnProcessId":"testLifeCycle","workflowKey":-1,"workflowInstanceKey":-1},"sourceRecordPosition":-1}
10:17:13.738 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295310400,"timestamp":1588414645620,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"testLifeCycle","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295310216}
10:17:13.738 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685434,"position":4295310688,"timestamp":1588414645620,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"variables":{},"bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295310216}
10:17:13.738 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295310912,"timestamp":1588414645621,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"testLifeCycle","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295310400}
10:17:13.738 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685435,"position":4295311216,"timestamp":1588414645622,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"startEvent_f987445b-0511-432a-8c36-c820b4b054f0","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295310912}
10:17:13.739 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685435,"position":4295311568,"timestamp":1588414645623,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"startEvent_f987445b-0511-432a-8c36-c820b4b054f0","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295311216}
10:17:13.739 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685435,"position":4295311920,"timestamp":1588414645624,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"startEvent_f987445b-0511-432a-8c36-c820b4b054f0","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295311568}
10:17:13.739 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685435,"position":4295312272,"timestamp":1588414645625,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"startEvent_f987445b-0511-432a-8c36-c820b4b054f0","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295311920}
10:17:13.739 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685436,"position":4295312624,"timestamp":1588414645626,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"sequenceFlow_54fe94dd-958f-4994-82dc-4466b39ef635","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295312272}
10:17:13.739 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685437,"position":4295312976,"timestamp":1588414645627,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"INTERMEDIATE_CATCH_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"timer","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295312624}
10:17:13.741 [] INFO  io.zeebe.test.records - {"valueType":"TIMER","key":-1,"position":4295313296,"timestamp":1588414645628,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"targetElementId":"timer","repetitions":1,"dueDate":1588414645627,"elementInstanceKey":2251799813685437,"workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295312976}
10:17:13.743 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685437,"position":4295313512,"timestamp":1588414645628,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"INTERMEDIATE_CATCH_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"timer","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295312976}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"TIMER","key":2251799813685438,"position":4295313840,"timestamp":1588414645628,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"targetElementId":"timer","repetitions":1,"dueDate":1588414645627,"elementInstanceKey":2251799813685437,"workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295313296}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"TIMER","key":2251799813685438,"position":4295314072,"timestamp":1588414645629,"recordType":"COMMAND","intent":"TRIGGER","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"targetElementId":"timer","repetitions":1,"dueDate":1588414645627,"elementInstanceKey":2251799813685437,"workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295313512}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685437,"position":4295314304,"timestamp":1588414645631,"recordType":"EVENT","intent":"EVENT_OCCURRED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"INTERMEDIATE_CATCH_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"timer","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295314072}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"TIMER","key":2251799813685438,"position":4295314608,"timestamp":1588414645631,"recordType":"EVENT","intent":"TRIGGERED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"targetElementId":"timer","repetitions":1,"dueDate":1588414645627,"elementInstanceKey":2251799813685437,"workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295314072}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685437,"position":4295314848,"timestamp":1588414645632,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"INTERMEDIATE_CATCH_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"timer","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295314304}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685437,"position":4295315168,"timestamp":1588414645633,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"INTERMEDIATE_CATCH_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"timer","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295314848}
10:17:13.744 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685440,"position":4295315488,"timestamp":1588414645634,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"sequenceFlow_edd4c295-18d3-429a-9c88-4477d55e1b29","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295315168}
10:17:13.745 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685441,"position":4295315840,"timestamp":1588414645635,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"endEvent_ddef0e37-d782-4df3-a1d9-97f7366a9ea8","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295315488}
10:17:13.745 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685441,"position":4295316184,"timestamp":1588414645636,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"endEvent_ddef0e37-d782-4df3-a1d9-97f7366a9ea8","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295315840}
10:17:13.746 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685441,"position":4295316528,"timestamp":1588414645637,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"endEvent_ddef0e37-d782-4df3-a1d9-97f7366a9ea8","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295316184}
10:17:13.747 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685441,"position":4295316872,"timestamp":1588414645638,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":2251799813685433,"bpmnElementType":"END_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"endEvent_ddef0e37-d782-4df3-a1d9-97f7366a9ea8","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295316528}
10:17:13.747 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295317216,"timestamp":1588414645639,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"testLifeCycle","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295316872}
10:17:13.747 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295317520,"timestamp":1588414628640,"recordType":"COMMAND","intent":"CANCEL","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":-1,"flowScopeKey":-1,"bpmnElementType":"UNSPECIFIED","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"","bpmnProcessId":"","workflowKey":-1,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":-1}
10:17:13.747 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295317776,"timestamp":1588414645640,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"testLifeCycle","bpmnProcessId":"testLifeCycle","workflowKey":2251799813685431,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295317216}
10:17:13.747 [] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685433,"position":4295318080,"timestamp":1588414645646,"recordType":"COMMAND_REJECTION","intent":"CANCEL","partitionId":1,"rejectionType":"NOT_FOUND","rejectionReason":"Expected to cancel a workflow instance with key '2251799813685433', but no such workflow was found","value":{"version":-1,"flowScopeKey":-1,"bpmnElementType":"UNSPECIFIED","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"elementId":"","bpmnProcessId":"","workflowKey":-1,"workflowInstanceKey":2251799813685433},"sourceRecordPosition":4295317520}
</pre>
</details>

**Comment by saig0** [comment]
related to #3618
