### ISSUE TITLE
Job worker should apply backoff on job polling in case of service unavailable 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#4443]
**Describe the bug**

When a job worker receives a services unavailable or similar (5xx) error the worker should apply a backoff strategy to decrease the load on the failing service.

**To Reproduce**

1. Create a development Zeebe cluster on the cloud
1. Kill the zeebe pod inside the cluster
1. Let the job worker run

**Expected behavior**

If the service is unavailable the job worker backs off and doesn't overload the service.

**Environment:**
 - OS: Camunda Cloud

**Comment by npepinpe** [comment]
There's a branch with some code already on it - let me know if you want to kick it off
