### ISSUE TITLE
Log/Protocol: Move term id from metadata to log entry header

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#446]
The raft term is a concept on log level (not log content level), e.g. see `LogStream#getRaftTerm`, so the association between log entry and term should be maintained in the log entry header, not the event metadata. This also removes some cases where we have to decode/encode the metadata.

**Comment by ThorbenLindhauer** [comment]
Regarding protocol change: clients should not be affected by this.

**Comment by menski** [comment]
@ThorbenLindhauer you are right, i removed the label again
