### ISSUE TITLE
Partitions Not available if single broker is missing

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#4462]
**Describe the bug**

When starting a cluster of brokers without replication, and a single broker is not able to start, non of the partitions will become available.

**To Reproduce**

Start a single broker with a cluster size of `2`, i.e. using docker:
```
docker run --rm -p 26500:26500 -e ZEEBE_CLUSTER_SIZE=2 camunda/zeebe:0.20.1
```

Check the topology using zbctl

```
$ ~/zeebe-broker-0.20.1/bin/zbctl statusCluster size: 2
Partitions count: 1
Replication factor: 1
Brokers:
  Broker 0 - 172.17.0.2:26501
```

**Expected behavior**

A partition should be accessible as soon as all replication members are available, i.e. without replication the partitions on the started brokers should be accessible.

**Environment:**
 - Zeebe Version: 0.20.1 - 0.23.1
 - Configuration: Broker Cluster with multiple partitions but no replication

**Comment by menski** [comment]
The root cause seems to be that Atomix will wait for all cluster members to join before finishing the start up completely. Which is the requirement for Zeebe to initialize the partition services.

**Comment by npepinpe** [comment]
I guess this is only an issue on cluster-wide restart?

**Comment by deepthidevaki** [comment]
I guess this won't be a problem anymore since we removed system partition #4238

**Comment by menski** [comment]
Yes I can confirm that a broker starts on `SNAPSHOT` with a missing broker.
