### ISSUE TITLE
A partition which is not available impacts the completion of workflows on other partitions

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#4496]
**Describe the bug**
In a cluster  replication factor = 1, if a broker for one partition is down, we observe the following behavior
1. A number of create workflow instance requests times out because gateway still attempt to send the request to the failed partition.
3. Activate jobs requests latency spikes. This is again because gateway attempts to send the requests to failed partition, waits for the timeout of 15s (default gateway timeout) and then retries with other partition. In some cases, we also observed that no jobs get completed because all requests are send to the failed partition. Thus either the job activation latency is increased or no jobs are activated at all when one partition is not available. 

**Expected behavior**
If one or more partitions are not available, it should not have impact on job activation on other partitions which are healthy. 

**Environment:**
 - Zeebe Version: [e.g. 0.20.0]

Related to [SUPPORT-7670](https://jira.camunda.com/browse/SUPPORT-7670)

**Comment by npepinpe** [comment]
Looks good, let's merge it :muscle:

**Comment by npepinpe** [comment]
Closed by #4497
