### ISSUE TITLE
Metrics about scheduled jobs

### ISSUE THREAD

**Issue by AndreasBieber** [zeebe-io/zeebe#4500]
**Is your feature request related to a problem? Please describe.**
We want to provide metrics about our zeebe workers to better monitor them. Specifically, how many jobs a worker has scheduled (`jobPoller`).

**Describe the solution you'd like**
The `JobWorker` offers a possibility to register a consumer implementation of an interface predefined by the zeebe go client

**Describe alternatives you've considered**
IMHO there is no alternative because the information about remaining jobs is currently not exposed

**Comment by npepinpe** [comment]
@MiguelPires let's talk about this when you have some time

**Comment by npepinpe** [comment]
Let's discuss it at triage - seems like a reasonable feature which could also be useful for us, and would also need the java client to be sync'd.

**Comment by menski** [comment]
@npepinpe let's talk about this next week

**Comment by AndreasBieber** [comment]
Any update on this or chance to get the linked PR merged?

**Comment by npepinpe** [comment]
Sorry for the slow progress, I'll take a look at it :slightly_smiling_face:
