### ISSUE TITLE
Missing information why Leader change happens

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4529]
**Description**

I have a benchmark where a lot of leader changes happing at some point the cluster went out of disk space, since it was not able to compact anymore. To understand the issue I searched for the first leader change or why the leader partition was closed.

The only thing I found was this:

```
D 2020-05-14T10:28:31.135Z ZeebeRaftStateMachine502304{partition=raft-partition-partition-1} - Compacting log up from 1398730 up to {} 
D 2020-05-14T10:28:45.289Z Partition role transitioning from FOLLOWER to CANDIDATE 
D 2020-05-14T10:28:45.729Z Removing leader partition services for partition PartitionId{id=1, group=raft-partition} 
D 2020-05-14T10:28:45.729Z Closing Broker-2-Exporter-1 
D 2020-05-14T10:28:45.732Z Partition role transitioning from LEADER to FOLLOWER 
D 2020-05-14T10:28:45.752Z Closed exporter director 'Broker-2-Exporter-1'. 
```

In the logs we just see that one Broker steps up and the other immediately steps down.
If we filter the logs for the failing broker (Broker-2) then we see the last thing he did was replicating a snapshot:

```
D 2020-05-14T10:28:27.714Z Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1522399-1-1589452087864/CURRENT 
D 2020-05-14T10:28:27.714Z Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1522399-1-1589452087864/MANIFEST-000004 
D 2020-05-14T10:28:27.714Z Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1522399-1-1589452087864/OPTIONS-000090 
D 2020-05-14T10:28:45.729Z Removing leader partition services for partition PartitionId{id=1, group=raft-partition} 
```

This is also reflected by the metrics.

![atomix](https://user-images.githubusercontent.com/2758593/82017330-33abca00-9683-11ea-8512-7e24e2fe08d2.png)
![snapshot](https://user-images.githubusercontent.com/2758593/82017331-34446080-9683-11ea-8914-0266484fdf29.png)

Interesting is that we see that the hearbeat time goes up, but we see no missing heartbeat in the metrics nor in the log.

If we check the other Brokers log (Broker-0):

```
D 2020-05-14T10:28:31.023Z ZeebeRaftStateMachine502304{partition=raft-partition-partition-1} - Compacting log up from 1398730 up to {} 
D 2020-05-14T10:28:45.289Z Partition role transitioning from FOLLOWER to CANDIDATE 
D 2020-05-14T10:28:46.893Z Received metadata change for 2, partitions {1=FOLLOWER, 2=LEADER, 3=LEADER} terms {2=1, 3=1} 
```

There is no information why he stepped up. I would expect that we would see here a warning that we missed a heartbeat and that the metrics work as expected. Otherwise I don't understand why he is stepping up.

A clear and concise description of what this issue is about.

**Comment by npepinpe** [comment]
Already done.
