### ISSUE TITLE
Add a health endpoint to the Broker

### ISSUE THREAD

**Issue by hawky-4s-** [zeebe-io/zeebe#454]
### Usecase
Advanced cluster schedulers like [Nomad](https://www.nomadproject.io/docs/job-specification/service.html#check) or [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) require a health check to determine if the application they are running is healthy. Otherwise they need to react accordingly.

Currently Zeebe does not offer this kind of health check. 
Ideally it should be available through HTTP, but TCP or running a possible CLI cmd would also be ok.

**Comment by menski** [comment]
What is important for the health check? That the broker is running? Or that a specific topic exists? I don't think we will support a HTTP health check. A TCP check could validate that all API sockets are open. With the zbctl you could run the `zbctl describe topology` command to check that broker is responding.

**Comment by menski** [comment]
At the moment we provide zbctl as CLI and export prometheus metrics. Will close this for now until we have a specific idea for health endpoint. TCP will not be trivial as we only expect SBE messages at the moment.
