### ISSUE TITLE
Milestone Summary - Replace custom HTTP server with spring boot server

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4547]
**Description**

The goal of this milestone is to replace the custom HTTP server with a Spring Boot based server.

***Status Quo***
* Broker - for the broker, the following endpoints are exposed via a custom HTTP server
  * Health Probes
  * Prometheus Metrics
  * ready Probe
* Gateway - for the gateway the following endpoints are exposed via a custom HTTP server
  * Prometheus Metrics
 
For Broker the user can configure port and host of the endpoints.
For Gateway the user can configure port and host of the endpoint. The user can also disable the endpoints

***Scope***
* Replace custom HTTP Server with Spring Boot server to achieve feature compatibility
* Move new Gateway liveness probe and health checks onto the same port and make it comply with the monitoring enabled switch

***Nice to Have***
* Reuse the very same endpoints 

***Misc Tasks***
* Investigate Footprint
* Inform team about changes and new capabilities

**Comment by pihme** [comment]
@menski @Zelldon I am pinging you because your names appear at the code lines which I want to discuss. The discussion will be about how breaking changes and how true we want to be to the original. And I want to ask you to weigh in on the issue.

As part of this OKR I want to replace the hand written metrics endpoint with a canonical Spring implementation.

This would look like this:
```
 @GetMapping(METRICS_URI)
    public ModelAndView metrics() {
      return new ModelAndView("forward:/actuator/prometheus");
   }
```

It is a simple (internal) forward from the `/metrics` path to where Spring will publish the metrics.  (I want to keep the old path as some sort of stable API; if we later replace Spring with something else, we could change the forward to wherever it then needs to go)

However, if I do this, this is a breaking change for this functionality:
```
  private static Set<String> metricsFilter(final QueryStringDecoder queryStringDecoder) {
    final List<String> names = queryStringDecoder.parameters().get("name[]");
    if (names != null && !names.isEmpty()) {
      return new HashSet<>(names);
    } else {
      return Collections.emptySet();
    }
```

Is this breaking change ok, or is somebody relying on the filter options?

Note that this feature is 
* not documented
* difficult to implement in Spring without breaking changes, because `[]`are invalid characters in a request at that position and Spring refuses to process the request. So at least we would have to come up with a different query parameter

**Comment by Zelldon** [comment]
I don't know why this exist to be honest. Maybe @menski can tell

**Comment by npepinpe** [comment]
@Zelldon What is it you want to know? Why we are replacing it? What we want to do achieve?

**Comment by Zelldon** [comment]
I was talking about the query params, sorry to be not very precise.

**Comment by menski** [comment]
I build the filtering for fun, as I saw it in some example implementations. We can remove it as I don't think it's required and nobody should rely on it. It's just nice for development and you can easily replace it with `grep`. 

I like the forwarding approach. :+1:

**Comment by pihme** [comment]
@npepinpe Remember we talked about the monitoring disabeled switch and we wanted to add such a switch also to the Broker? Looking at the code it would be much easier to remove the switch from the Gateway and have monitoring running by default. What do you think?

**Comment by npepinpe** [comment]
In a sense, this is a breaking change for those who may have previously disabled it. However, what will go wrong for these users? The metrics have to be pulled, so in that sense assuming they had it disabled, they would probably not have been scraping them. Or am I missing something?

That said, braindump, I've been thinking that in any case, we need to harmonize the monitoring configuration - and the more I think about it, the more I think it could be a separate section, e.g.

```yaml
zeebe:
  gateway:
    ...
  broker:
    ...
  monitoring:
    tracing: true # just an example, not a proposal
    metrics: true
```

**Comment by pihme** [comment]
Footprint:

### Jar Size
- 0.24.0-alpha2: 67 MB
- now: 75 MB

### Startup Time

### Memory at Idle after Start

### Thread Count at idle after Start

**Comment by pihme** [comment]
Summary of discussions with @npepinpe 
- Not implemented and out of scope 
  - transforming broker health checks into Spring health checks
  - add Gateway liveness probes to broker health checks
  - endpoints with Kubernetes naming conventions (_/livez_ vs _/live_)
- Monitoring enabled flag on Gateway now has a slightly different behavior:
   - Metrics and health probes are available regardless of the flag
   - If flag is enabled, GRPC metrics will be added to the metrics

Scope and shortcomings were approved.
