### ISSUE TITLE
Review log level usage in Atomix

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4555]
**Description**

We currently have quite a high Atomix log level because debug logging in Atomix leads to a lot of noise - we should revise logs are used in Atomix so that we can make good use of the debugging information. Normally I would propose that we do this as we refactor, but it's currently a blocker for us, and a lot of these places we have no plans near-term to refactor anything, so unfortunately it may need to be a separate issue.

Acceptance criteria is that we can lower the log level of `io.atomix` to debug such that the information we get then is useful and not noise.

**Comment by Zelldon** [comment]
Things I found during reviewing/searching logs and where I think we can improve.

**Noisy NettyMessagingService**
The class `atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java` prints a lot on debug and I'm not sure if this is really useful. 

Example:

```
2020-06-09 17:34:41.555 CEST
Activating client protocol version V2 for connection to 10.0.15.4/10.0.15.4:26502
 
2020-06-09 17:34:42.243 CEST
Activating server protocol version V2 for connection to /10.0.15.4:60582
```

**Logs which just print started or joined**

Actually they are all from different services but you can only see it based on the logger name. We probably should add here more information.
```
2020-06-09 14:39:48.999 CEST
Started
2020-06-09 14:39:49.000 CEST
Started
2020-06-09 14:39:49.002 CEST
Started
2020-06-09 14:39:49.008 CEST
Started
```

**Canceling election after becoming leader**

      log.debug("Cancelling election"); is done on Candidate#stop

Looks weird if you see the node becomes leader but then cancel’s election

**Endless loops of:**

`Received a reply for message id:[35797] but was unable to locate the request handle`

I dont know what I can do with this information.

**Comment by npepinpe** [comment]
Downgrading as this is not critical for our current OKRs.

**Comment by npepinpe** [comment]
We decided on log levels, and I would close this for now and basically recommend that we approach it like everything else - adjust them as you needed. If they create noise, change them - if you're refactoring a piece, adjust the level to make sense.
