### ISSUE TITLE
Unstable cluster on bigger state

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4560]
**Describe the bug**

I have setup an stable cluster on gke (no preemtable nodes) and expected to run a benchmark for a while. Unfortunately it died after around 12 hours.

![general](https://user-images.githubusercontent.com/2758593/82406568-451c1a00-9a67-11ea-87c8-86b621daf239.png)

Investigating this I saw that we had unexpected often Leader changes in the cluster.

![to-many-leader-changes](https://user-images.githubusercontent.com/2758593/82406591-51a07280-9a67-11ea-909f-5b14008366b0.png)

These caused then also a growing of the disk space. Because we are not able to compact if we have to often a leader change.

![growing-resources](https://user-images.githubusercontent.com/2758593/82406747-b8259080-9a67-11ea-975f-f06766478b5b.png)

As we can see above only a few restarts are really related due to restarts. The restarts were caused by reaching the memory limit. Probably rocksdb reached there limits again.

![memory](https://user-images.githubusercontent.com/2758593/82406755-bfe53500-9a67-11ea-8c83-214a0466f909.png)

We had the problem with our helm charts that the gateway used only one thread to process the requests, which means we were not able to work fast on the created jobs. See related issue #4524 . This caused an growing running count.

![running](https://user-images.githubusercontent.com/2758593/82406837-edca7980-9a67-11ea-8f4d-9ad811c8230d.png)

As you can see we have around 2 million running instances. This big state causes also a bigger snapshot size. 
![snapshot-size](https://user-images.githubusercontent.com/2758593/82406868-02a70d00-9a68-11ea-9c31-e1119c8a27b5.png)

This might be related to the leader changes, because it will take a long time to replicate these snapshots. Furthermore it increases the disk usage as well.

**To Reproduce**

Start an usual benchmark with non preemtable nodes and start less workers.
Steps to reproduce the behavior

**Expected behavior**
A stable running system.

**Environment:**
 - OS: k8
 - Zeebe Version: 0.24.0-SNAPSHOT
 - Configuration: elastic, standalone gw

**Comment by Zelldon** [comment]
Happens again with a new benchmark. We are not able to work on all jobs, which means we building up a bigger state. This causes also bigger snapshot sizes.

![bigger-load-snapshot](https://user-images.githubusercontent.com/2758593/82637602-69adf880-9c05-11ea-8430-fb5bb605a0bc.png)

We see a lot of leader changes in the benchmark and missing heartbeats.

![role-changes](https://user-images.githubusercontent.com/2758593/82637608-6b77bc00-9c05-11ea-95e2-7f8c127fc62b.png)

In the end we went out of disk space.

![disk](https://user-images.githubusercontent.com/2758593/82637595-6450ae00-9c05-11ea-8482-c8d653dc711c.png)

**Comment by npepinpe** [comment]
Downgrading, as while this is important to figure out, it does not impact our own production environment (thanks pre-emptible nodes), and as such isn't critical to our OKRs.
