### ISSUE TITLE
Resetup test cluster with OS which is maintainable by team and devops

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#458]
- currently the Zeebe test cluster is using Gentoo as OS, which is only maintainable by Tim
- with the further development we may need a test cluster which we have to adjust to specific needs (software, network config, etc.)
- I think it would be better if the team/devops at the Berlin office feel comfortable to adjust the cluster to our needs
- I would propose to resetup the cluster using a common OS like CentOS, Debian or Ubuntu

**Comment by menski** [comment]
@meyerdan I would be interested in your input

**Comment by meyerdan** [comment]
I agree.

**Comment by menski** [comment]
@AndreaGiardini and @hawky-4s- any suggestions which distribution to choose?

**Comment by AndreaGiardini** [comment]
I would feel comfortable with Debian/CentOS . I've used them both in the past and they just do the job

**Comment by menski** [comment]
We will setup CentOS on the servers. Currently we evaluate if we want to buy a license for the remote management interface of the server to allow full control from the office without going to the server room.

**Comment by menski** [comment]
We installed a license on the third Zeebe server, which can now be installed with CentOS.

**Comment by menski** [comment]
I installed CentOS 7 on cam-int-3. The next step would be to create some ansible playbooks to configure the system as required.

**Comment by menski** [comment]
all machines are now running CentOS 7 and are setup using ansible playbooks found in https://github.com/zeebe-io/zeebe-cluster-tests
