### ISSUE TITLE
Follower should reset his log on restart when it has received a newer snapshot

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4587]
**Describe the bug**
Based on the fix of https://github.com/zeebe-io/zeebe/pull/4451 we introduced logic where the follower deletes the log when he receives an snapshot with higher index then the last entry.

The problem with this is that it might fail in between, which means we still have a small chance that this happens, because of node crash.

**To Reproduce**
We need a slow follower, which receives a regular snapshot. Before he is able to delete the log the node needs to be shutdown. On start the follower has the old log and the newer snapshot.

**Expected behavior**
The follower detects it has an newer snapshot and resets his log based on that.

**Comment by npepinpe** [comment]
Please back port this to stable/0.24 for 0.24.1 :+1:
