### ISSUE TITLE
how to upgrade zeebe (docker) from 0.20.0 to  0.23.2?

### ISSUE THREAD

**Issue by huqiangjz** [zeebe-io/zeebe#4605]
**Description**
I did not see the document about it in zeebe.io.

I want to keep the existing data. 
is it any safe way to accomplish it?

**Comment by saig0** [comment]
Hi @huqiangjz :wave: 

> I want to keep the existing data.
is it any safe way to accomplish it?

Unfortunately, there is no way to upgrade Zeebe to `0.23.0` and keep your existing data. The version contains breaking changes. So, you need to start with a fresh setup.

It is mentioned in the release blog post: https://zeebe.io/blog/2020/04/zeebe-operate-023-release/
