### ISSUE TITLE
Export RocksDB metrics on Transaction#commit

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4606]
# Description

## Motivation

During investigating of the RocksDB memory usage we exported some metrics to better understand how RocksDB behaves and where the memory is spent etc. It was quite interesting to see in which column family the most data is stored and how much space the WAL, sst files etc take on disk. With the metrics it was also possible to take a correlation between our throughput drops and the memtable flush time.

The above described scenarios and use cases where the reason why we wanted to export the RocksDB metrics on regular basis.

## Implementation

On our investigation we polled the metrics from RocksDB every 5 seconds. In order to do that we added new methods to the ZeebeDB abstraction etc. It was maybe not ideal. We decided to do it differently without exposing it on the API. We thought as first approach to export them on each transaction commit, but we should also check how other systems like kafka streams do it.

We should export the metrics we have already exported on this branch https://github.com/zeebe-io/zeebe/tree/zell-rocks-metrics
For each metric we should have an own gauge or counter.

We should check whether the exporting takes to much time and maybe limit it if necessary to export it just every 100 commits or something else.

## Acceptance Test

 * export RocksDB statistics on regular basis
 * counter/gauge per statistic
 * same statistics exported as in the [branch ](https://github.com/zeebe-io/zeebe/tree/zell-rocks-metrics)
 * metric exporting doesn't drop the throughput to much (less then 5%)

## Further Work

Later we could improve here and maybe add an toggle to disable some of these metrics.

**Comment by pihme** [comment]
Why pull the metrics on commit / on each 100th commit? This seems suboptimal because we won't have metrics when the system is idle and a high volume when load is high.

Was it just an issue of scheduling? If so this might be helped by Spring mechanisms.

**Comment by Zelldon** [comment]
> Why pull the metrics on commit / on each 100th commit? This seems suboptimal because we won't have metrics when the system is idle and a high volume when load is high.

True, this was the simplest for now to understand what is going on in the system. As you can see in the branch I did it via scheduling every 5 seconds. Works also well.

I would like to not pollute every module with spring dependencies, so would be nice if we could do it differently.

**Comment by pihme** [comment]
It was agreed in a conversation that the frequency need not be configurable of the performance loss at 5s frequency is acceptable.
