### ISSUE TITLE
use only slf4j for logging - set log4j deps to provided

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#461]
I am having  trouble in spring boot with duplicate loggers. I noticed, taht although slf4j is already used, a lot of util-moduls (zb-map for example) come with a transitive dep to log4j-slf4j-impl.

I would vote for not having those modules a "compile" dependency on log4j, it is enough to have it optional or provided, so the aggregating module can decide which logging impl to use.

see https://github.com/zeebe-io/spring-zeebe/issues/12

**Comment by menski** [comment]
Hi @jangalinski,

with https://github.com/zeebe-io/zb-util/commit/9655deec630c81d7caa86e599911b3a7b8c30b5b and https://github.com/zeebe-io/zeebe/commit/429cd7dbd222e2aff73fe600c0a4482de5795f75 only the dist/perf/samplels have a compile dependency on log4j libs. Does that work for you?

**Comment by jangalinski** [comment]
yes, cool, solved!
