### ISSUE TITLE
Broken links in FEEL expressions docs

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4623]
**Description**

There are some broken links at the bottom of the FEEL expression documentation [here](https://docs.zeebe.io/reference/expressions.html), namely: 

- [FEEL - Data Types](https://camunda.github.io/feel-scala/feel-data-types)
- [FEEL - Expressions](https://camunda.github.io/feel-scala/feel-expression)
- [FEEL - Built-in Functions](https://camunda.github.io/feel-scala/feel-built-in-functions)

**Comment by menski** [comment]
@saig0 you know where they should point to?

**Comment by saig0** [comment]
It is already fixed in stage environment: https://stage.docs.zeebe.io/reference/expressions.html

**Comment by npepinpe** [comment]
From my side this is then fixed and already merged :+1:
