### ISSUE TITLE
'backpressure' cannot be set to false in version 0.23.2

### ISSUE THREAD

**Issue by wenminglei** [zeebe-io/zeebe#4643]
**Describe the bug**
'backpressure' cannot be set to false in version 0.23.2
I set backpressure to false in the configuration file. But the log shows that it did not take effect.

```
backpressure:
      enable: false
```
Output:
```
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
```

**Environment:**
 - OS: [Linux]
 - Zeebe Version: [0.23.2]
 - Configuration: [e.g. exporters etc.]

**Comment by Zelldon** [comment]
Hey @wenminglei as you can see on the output the flag is called `enabled` instead of `enable` you missed an `d`. Can you verify that? I will close this for now. Feel free to reopen it.
