### ISSUE TITLE
No election/failover when leader goes away

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4656]
**Describe the bug**

During the latest long-running test for 0.24.0-alpha2, while most things worked smoothly, we had on 02.06.2020 08:44:45 CEST a partial outage for partition 3 - the leader node (node 0) went down (most likely pre-empted, but I didn't verify). This should be fine, but the issue is that no other node was elected as leader for partition 3 until node 0 came back at around 9am. Looking through the logs, it looks like node 2 was trying to poll other nodes for an election, but all its requests were timing out. Unfortunately the time out exception doesn't tell you which node it tried to connect to, so in that sense it's not very useful.

The cluster eventually recovered when node 0 came back, but for 15 minutes we had noticeably decreased performance due to having no leader for partition 3.

**To Reproduce**

Not sure, as this was not controlled - set up was 3 nodes, 3 partitions, replication factor 3, constant load of about 140 wfi/s completed. Kill the leader and eventually this may happen?

**Expected behavior**

A leader is always elected if at least 2 nodes are available.

**Log/Stacktrace**

The logs are available on Stackdriver using the following query:

```
resource.type="k8s_container"
resource.labels.project_id="zeebe-io"
resource.labels.location="europe-west1-b"
resource.labels.cluster_name="zeebe-cluster"
resource.labels.namespace_name="release-0240-alpha2"
resource.labels.pod_name="release-0240-alpha2-zeebe-1"
-jsonPayload.context."actor-name"="Broker-1-Exporter-1"
-jsonPayload.context."actor-name"="Broker-1-Exporter-2"
```

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.24.0-alpha2
 - Configuration: benchmark configuration

**Comment by npepinpe** [comment]
May be related to #4587

**Comment by MiguelPires** [comment]
I couldn't reproduce the reported behavior exactly but I observed other strange behaviors. After killing a leader of a partition, it's common for that broker to that upwards of 15 minutes to rejoin the cluster and sometimes the broker doesn't rejoin at all. From the profiles I took, the broker seems to be reading segments in the journal and appending entries but, mainly doing GC.
The logs also show a continuous loop of messages:
```
{"timestampSeconds":1591282524,"timestampNanos":498000000,"severity":"DEBUG","thread":"netty-messaging-event-epoll-client-3","logger":"io.atomix.cluster.messaging.impl.NettyMessagingService","message":"Activating client protocol version V2 for connection to mp-baseline-zeebe-0.mp-baseline-zeebe.mp-baseline.svc.cluster.local/10.0.22.27:26502","context":{}}
{"timestampSeconds":1591282521,"timestampNanos":936000000,"severity":"DEBUG","thread":"netty-messaging-event-epoll-client-7","logger":"io.atomix.cluster.messaging.impl.RemoteServerConnection","message":"No handler for message type raft-partition-partition-3-append from mp-baseline-zeebe-1.mp-baseline-zeebe.mp-baseline.svc.cluster.local:26502","context":{}}
```
Presumably, `raft-partition-partition-3-append` is the topic where append requests are published for partition 3 and the restarted broker drops them because it hasn't created a handler for them yet. I think this is done as part of the last start up step and starting Atomix is the 7th.

**Comment by npepinpe** [comment]
Feel free to pair with or ask for help from @deepthidevaki i or @Zelldon, they might have more insight in how to figure out what went wrong from the existing cluster, as that cluster still exists and you can look at its metrics and logs :slightly_smiling_face:

**Comment by MiguelPires** [comment]
I already scheduled a meeting for another topic, I was just working on this so wasn't blocked while waiting for that

**Comment by MiguelPires** [comment]
Current observations:
* Broker 0 suspects that it is partitioned from broker 1 and steps down. Eventually, it moves to candidate and about 12 minutes later is comes back as leader
* Broker 1 continuously sends requests to broker 0, which always timeout, but it never initiates a leader election
* Broker 2 sends poll requests which fail. We can assume that these poll requests are for both broker 1 and 0 but the timeout doesn't specify the target so I'm not sure (#4748 addresses this)

Seems like a very asymmetrical network partition. Nicolas suggested that DNS issues may cause one broker to have the wrong address for another which would explain some of this behavior.

Currently, we're putting this on ice until we can gather more information or observe this again.

**Comment by npepinpe** [comment]
I talked to Chris, and he had some good leads on this one, which we could look into together. Basically the way the poll mechanism works is strange, and it might explain why it looked like one node was trying to poll but no election ever took place. When you have some time to revisit this we can look zoom and talk about it

**Comment by MiguelPires** [comment]
Sounds good, I'll schedule something for this week

**Comment by npepinpe** [comment]
Let's check in with Zoltan about setting up an alarm which notifies us when we have less than 3 leaders for at least, say, 5 minutes - that way we can have a look next time it happens

**Comment by npepinpe** [comment]
I'm closing this for now as we've never managed to reliably reproduce it and get more information; feel free to reopen should this happen again.
