### ISSUE TITLE
Do not log broker rejections in the gateway at ERROR level

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4665]
**Description**

Logging at ERROR level will result in a new error being aggregated in the Error Reporting tool. A broker rejection is expected, as it results from the client trying to do something they shouldn't, and isn't an error that we should look into as developers.

Whether rejections should be logged at all is also open for debate during the kick off here.

**Comment by korthout** [comment]
Next to BrokerRejectionException, this should also count for client requests that fail with PartitionNotFoundException. For example, a client requests to cancel a non-existent instance (e.g. `zbctl cancel instance 123` on a cluster without deployed workflows), then the Partition cannot be found as it is part of the provided key. This is just a client error.

**Comment by korthout** [comment]
The gateway deals with many different exceptions in the same code location as the BrokerRejectionException. As part of this issue, we've decided to improve the log messages and lower the log level for each type of exception that is considered a client-side error. These will then no longer be picked up by our error reporting tool.
