### ISSUE TITLE
Elasticsearch exporter ignores errors on flush

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4667]
**Describe the bug**
If a failure occurs while exporting records to Elasticsearch then the failure is not reported and no retry happens. As a result, records may not be exported.   

**To Reproduce**
Not sure how to trigger a failure expect using mocks.

Found while fixing #4640.

**Expected behavior**
The failure is reported to the log and the exporter try again.

**Log/Stacktrace**
Nope.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.24.0-alpha2
 - Configuration: elasticsearch-exporter

**Comment by npepinpe** [comment]
Out of curiosity, how did you find it out? I had seen that getting a 5xx would throw an exception, and otherwise hasErrors would be true - how are errors now reported?

**Comment by saig0** [comment]
## Hints

* the response from ES: 
```
{took=3, errors=true, items=[{index={_index=test-record_job_0.24.0-snapshot_2020-06-04, _type=_doc, _id=1-4294983448, status=400, error={type=illegal_argument_exception, reason=Can't merge a non object mapping [value.customHeaders.x] with an object mapping [value.customHeaders.x]}}}, {index={_index=test-record_job_0.24.0-snapshot_2020-06-04, _type=_doc, _id=1-4294983792, status=400, error={type=illegal_argument_exception, reason=Can't merge a non object mapping [value.customHeaders.x] with an object mapping [value.customHeaders.x]}}}]}
```
* the response is deserialized by `BulkResponse`
* the field `errors` in the DTO is not set because it has no public setter

**Comment by npepinpe** [comment]
My bad, I was under the impression that Jackson didn't require a public setter to deserialize a field :see_no_evil: You should check the other DTOs that we also have then (about 4)
