### ISSUE TITLE
An incident at a gateway is always resolved, even if it fails 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#469]
Problem:
* given: an incident at an exclusive gateway 
* when: update workflow instance payload to resolve the incident
* then: the incident is resolved, even if the payload isn't correct 
* in this case, the workflow instance is stuck at the gateway

Hints: 
* there are two incident events: resolved_failed + resolved
* the current logic to detect a resolved incident doesn't work for gateways because it's only one event (activity/task incidents have multiple events with the same key)

**Comment by Zelldon** [comment]
fixed XOR incident handling:
 * on resolving the incident the event, which creates the incident, is again written
 * the position is saved in a zb-map
 * if a new event is created with a sourceEventPosition, which is equal to the saved position, the incident is resolved
 * in that case the resolved incident event is written
 * If the execution would create a new incident the incident resolve will fail and the resolve failed event is written

**Comment by saig0** [comment]
**Review Hints:**
* IncidentStreamProcessor:
** onWorkflowInstanceEvent() -> only process required events 
** ResolveIncidentProcessor -> on reprocessing, the written event is not added to the index. instead, you must read the written event afterwards and add it to the index

**Comment by Zelldon** [comment]
Fixed incident resolving on recovery problem.

As discussed also created new issues for refactoring the incident stream processor and
removing the target log stream:

 * https://github.com/zeebe-io/zeebe/issues/553
 * https://github.com/zeebe-io/zeebe/issues/552
