### ISSUE TITLE
One Node in Cluster Down

### ISSUE THREAD

**Issue by dinilvsellerapp** [zeebe-io/zeebe#4712]
**Describe the bug**

Nodes showing Warning message and one node is down.

Zeebe-Node-1(Not Ready State)
_2020-06-12 09:46:06.445 [] [raft-server-0-system-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - java.util.concurrent.TimeoutException: Request type system-partition-1-poll timed out in 5000 milliseconds_

Zeebe-Node-2
_2020-06-12 09:46:21.051 [] [raft-server-1-raft-partition-partition-3] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-3} - AppendRequest{term=4, leader=1, prevLogIndex=8664602, prevLogTerm=3, entries=0, commitIndex=8939363} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException_

Zeebe-Node-3
2020-06-12 09:47:14.339 [Broker-2-SnapshotDirector-2] [Broker-2-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/8649899-16-1591955233833/005137.sst
**To Reproduce**
Steps to reproduce the behavior

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**
All nodes up and running
https://gist.github.com/dinilvsellerapp/a0890e6a7a931861c40039df8fa5c72b
One node names goseller-zeebe-0 is down with above error logs
**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
Version: 0.23.2
helm-chart-version: zeebe-full-Latest
Kubernetes version: v1.14.10
Deployment: Kubernetes 3-Node Cluster
Client: Go Lib Latest

**Comment by npepinpe** [comment]
Hi @dinilvsellerapp

The errors you see above are typically due to network partitions, or mis-configuration, e.g. a node cannot connect to the others. Was the node ever ready/up? How many partitions do you have configured, and with what replication factor? Can you share the configuration for goseller-zeebe-zeebe-0 and at least one of the other nodes, e.g. goseller-zeebe-zeebe-1, so we can compare?
