### ISSUE TITLE
How could operate connect to ES cluster which has password

### ISSUE THREAD

**Issue by Young1989** [zeebe-io/zeebe#4749]
I got confused, I could not see any document which mention about that how to set operate connect to ES cluster which has account and password
![image](https://user-images.githubusercontent.com/3414477/84775166-6d207e00-b011-11ea-8b34-b28ef57827a0.png)

cloud any one know how ot achieve this?

**Comment by menski** [comment]
Hi @Young1989 ,

thanks for raising the issue.  At the moment Operate does not support basic authentication, feel free to comment on the open feature request https://jira.camunda.com/browse/OPE-1006.

I will close this issue here as Operate uses JIRA for issue tracking.
