### ISSUE TITLE
Add a code of conduct to all projects

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#476]
- [x] Decide on code of conduct to use
  - https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
  - http://citizencodeofconduct.org/
  - https://geekfeminism.org/about/code-of-conduct/
  - https://www.djangoproject.com/conduct/
  - https://www.python.org/psf/codeofconduct/
  - https://www.ubuntu.com/about/about-ubuntu/conduct
- [x] Request approval from all team members
- [x] Add code of conduct to all zeebe projects
- [x] Add link to code of conduct in README and zeebe.io
- [x] Create pull request on all Zeebe community projects to also accept the code of conduct

**Comment by menski** [comment]
I would propose that we adopt [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as Code of Conduct for the Zeebe Project.

Therefore I would like to request that every member of the Zeebe team (@meyerdan @ThorbenLindhauer @jsam @saig0 @Zelldon @DNCamunda) reads the Code of Conduct and answer the following two questions:
1. Do you accept the Code of Conduct for the Zeebe Project?
2. Which e-mail should be used for reporting issues? info@zeebe.io (redirect to @DNCamunda and @menski) or code-of-conduct@zeebe.io (redirect to all team members)?

If you have any questions or feedback you can also approach me personally.

**Comment by meyerdan** [comment]
1. OK from my side
2. No opinion, please decide.

**Comment by ThorbenLindhauer** [comment]
Same.

**Comment by saig0** [comment]
Same for me.

**Comment by Zelldon** [comment]
1. Yes
2. Vote for redirect to all.

**Comment by jsam** [comment]
Same.

**Comment by menski** [comment]
Kerstin created the address code-of-conduct@zeebe.io which we will use as contact point

**Comment by DNCamunda** [comment]
1. Read and looks good
2. No opinion, happy with whatever the group decides :).

**Comment by menski** [comment]
I added the Code of Conduct to all Zeebe projects and created a pull requests in all community projects. Waiting for the pull requests to get merged.

**Comment by menski** [comment]
All pull requests were merged so I close this ticket
