### ISSUE TITLE
Workflow not available for CREATE directly after DEPLOY

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#4761]
**Describe the bug**
A workflow definition is not available for creating new instances directly after deployment.

**To Reproduce**
Deploy a workflow definition to a single node cluster.
The response comes back, eg:

```
{
  workflows: [
    {
      bpmnProcessId: 'Process_1iddwk3',
      version: 1,
      workflowKey: '2251799813685249',
      resourceName: 'test-process.bpmn'
    }
  ],
  key: '2251799813685250'
}
```

Immediately on receiving the response, in code, create an instance of the workflow.

It throws an error: 

```
(node:33738) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: Command rejected with code 'CREATE': Expected to find workflow definition with process ID 'test-process', but none found
```

To work around this, I have added a 1 second delay in the Node client test suite.

**Expected behavior**
If the broker responds to a deployment request, it should be able to create an instance.

This seems to be an issue with 0.23.x. It is present on 0.23.[2|3].

It didn't behave like this previously.

**Environment:**
 - OS: Linux / Docker
 - Zeebe Version: 0.23.2|3
 - No exporters loaded

**Comment by npepinpe** [comment]
Hey Josh, is this with one or multiple partitions? What's the cluster configuration, specifically number of nodes, partitions, and replication factor?

**Comment by jwulf** [comment]
Closing for now - this looks like a different issue. I will reopen it if it turns out to be this.

**Comment by denissabramovs** [comment]
Same issue here, just used your docker-compose example from operate folder.

**Comment by Zelldon** [comment]
@denissabramovs could you please provide some more information about your setup please?

**Comment by denissabramovs** [comment]
Ok i guess i have found the reason.
Resolved it.
So the issue is that the name of the workflow should be reflected inside xml itself.
Inside Zeebe Modeler it is not obvious.
So the general id should match with the name of workflow we are trying to deploy.
So it is not the name of the file, but the name given inside the flow planner.

**Comment by denissabramovs** [comment]
So in the this issue owner case, he should give the workflow name as `Process_1iddwk3` instead of `test-process` from `bpmnProcessId: 'Process_1iddwk3',`

**Comment by denissabramovs** [comment]
```
<bpmn:process id="createUser.bpmn" name="New user creation flow" isExecutable="true">
```

```
<bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="createUser.bpmn">
```

Are these correct?

**Comment by denissabramovs** [comment]
from my runtime after resolving this:
```
@acpdev/tenant-dashboard-api: Workflow createUser.bpmn has started: {
@acpdev/tenant-dashboard-api:   workflowKey: '2251799813685288',
@acpdev/tenant-dashboard-api:   bpmnProcessId: 'createUser.bpmn',
@acpdev/tenant-dashboard-api:   version: 2,
@acpdev/tenant-dashboard-api:   workflowInstanceKey: '2251799813685290'
@acpdev/tenant-dashboard-api: }
```

**Comment by denissabramovs** [comment]
Hope this will help someone else, because i found this issue via google.
