### ISSUE TITLE
Difference between default request timeout in documentation and java client

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4762]
**Description**

In the description about long polling in https://docs.zeebe.io/basics/job-workers.html#long-polling, it is stated that:

> A worker can also specify a RequestTimeout which is the duration for which the request is queued. **The default timeout is 10 seconds.**

However, `clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientBuilderImpl.java` uses 20 seconds.

This originates from a discussion in #4719

**Comment by korthout** [comment]
The Go client does use a default request timeout of 10 seconds in `clients/go/cmd/zbctl/internal/commands/root.go`: `defaultTimeout = 10 * time.Second`. This is not a documentation issue

**Comment by korthout** [comment]
Requested solution: change the default request timeout in the java client to 10 seconds, to make it match the documentation and the go client.

**Comment by aivinog1** [comment]
@korthout Hello, I would like to take this, I understand that issue and can fix it

**Comment by korthout** [comment]
Hi @aivinog1, sorry for taking my time to get back to you. I was enjoying my holiday. The changes look good and I've already accepted the main PR. I'm also happy to see you've added a backport PR for `0.24`. Can you please provide a backport to the `stable/0.23` branch as well? We try to maintain backports for the last 2 minor versions.

**Comment by aivinog1** [comment]
Hi, @korthout, thanks :) Sure, I'll add a backport to `stable/0.23` today.

**Comment by aivinog1** [comment]
@korthout Done :)

**Comment by korthout** [comment]
@aivinog1 Yay! They're all merged! Thanks again for this contribution. Sorry it took a lot longer than was expected for such a small change, but we managed to sort out some faulty tests because of it. 🥇
