### ISSUE TITLE
Request to add example properties file to configure java client

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4763]
**Description**

In the Java client a user can configure the Zeebe client in 2 ways: using the type safe java api or using a `java.util.Properties` object. The latter uses milliseconds as the unit for all durations.

I am unable to find any documentation about this usage, which is why I suggest to introduce an example properties file with the default values for the java client.

This originates from a discussion in #4719

**Comment by npepinpe** [comment]
Reopened in the new repo: https://github.com/camunda-cloud/camunda-cloud-documentation/issues/174
