### ISSUE TITLE
Investigate impact of locking in Dispatcher#offer

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#4774]
**Description**

The Dispatcher's offer method was made `synchronized` in PR https://github.com/zeebe-io/zeebe/pull/4717. This is necessary because acquiring memory for the fragment/batch needs to be done atomically with getting and increasing the record position. Otherwise, two fragments could be claimed and with the first having a smaller position than the second one. Since the same PR introduced consistency checks, this would be detected but it would seriously affect the system's ability to make progress. Another approach, that doesn't require `synchronized`, would be to make it lock-free: 
```
do {
currentPosition =   position.get()
// claim memory
nextPosition += fragmentCount;
 } while (!position.cas(currentPosition, nextPosition))
```
This should work in theory but it's significantly more complex and error-prone because, if the `compareAndSet` fails, the fragment or batch needs to be aborted. This is further complicated due to the fact that claiming might have failed in the first place, so we have to take care not to abort in that case or we'd probably have a segmentation error. Nonetheless, it's probably a good idea to look into the performance impact of locking this method since it's a central part of writing to the log.
Also interesting is that this race condition didn't exist before because, claiming memory and getting the position both depended on getting and increasing an offset, so we only had to that operation atomically which is easily accomplished. This way a clever way of dealing with it but, since now the record position is not based on the fragment offset, we need to ensure this is synchronized in a more explicit manner.

**Comment by npepinpe** [comment]
If that's alright, I would close this for now as I doubt we'll ever do this - if we were to actually work in the dispatcher at this point, I'd propose we look into replacing it with something simpler. Feel free to challenge this.
