### ISSUE TITLE
Recovery: First log event is not reprocessed if it is the reprocessing limit

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#478]
* Have a log with entries `[a, b, c]` where `a` is the source of `c`. `a` must be the first event on the log.
* There is no snapshot available.
* Perform reprocessing.

Expected behavior:

* `a` is reprocessed

Current behavior:

* `a` is not reprocessed
* `a` is regularly processed a second time, including side effects and follow-up events

**Comment by Zelldon** [comment]
We should verify whether this is still the case or not
