### ISSUE TITLE
Workflow instance with no payload does not get pushed to subscription

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zeebe#479]
When I create workflow instance with no payload I get the response from the broker "WORKFLOW_INSTANCE_CREATED". However, that workflow instance is not pushed to the opened task subscription.

Steps to reproduce the issue:
1. Deploy demoProcess.bpmn from examples folder using ```zbctl create workflow demoProcess.bpmn```
2. Open examples/create-workflow-instance.yaml and delete payload
3. Create workflow instance using ```zbctl create instance create-workflow-instance.yaml```
4. Open task subscription ```zbctl sub task```

You should see this newly create workflow instance once the subscription is opened.

**Comment by menski** [comment]
This was related to a IO mapping error. The process defines a io mapping which requires a payload when a workflow instances is created. That is why the task was not pushed to the subscription.
