### ISSUE TITLE
StackdriverLayoutTest.shouldContainTime flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4793]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**
Currently no details are available.

**Comment by npepinpe** [comment]
I thought I'd fixed this - is this happening on develop?

**Comment by pihme** [comment]
Maybe you have fixed it. I am updating the statistics from last week when I was on holiday.

**Comment by pihme** [comment]
Duplicate of #4770
