### ISSUE TITLE
As an User I can get the message key as response from the message publish command

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4794]
**Is your feature request related to a problem? Please describe.**
Currently we get an empty response when we publish a message, which means we know nothing about the published message. It would be useful in some cases at least to have the key, so we can for example find the message in elastic and also know where the message was published (on which partition).

**Describe the solution you'd like**
Just send as response the key.

**Describe alternatives you've considered**
There are none.

**Comment by npepinpe** [comment]
I suppose alternative is to send a unique ID and look for it in Elastic, but it's true that's not very convenient

**Comment by aivinog1** [comment]
Hello, I would like to take this one. I understand what needs to be done

**Comment by aivinog1** [comment]
@Zelldon @npepinpe @saig0 Hello, can you please post a link if there exists the API change guide? I understand that I need to create a separate method in the command that returns a new version of `PublishMessageCommandStep3` (it will be a different interface) that returns a `FinalStep` parameterized new interface with a method that returns a message id. And deprecate old ones. Am I right?

**Comment by saig0** [comment]
@aivinog1 not exactly. We don't need to change the builder command API. Instead, we can modify the [response](https://github.com/zeebe-io/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/api/response/PublishMessageResponse.java) and just add a method to return the message key. This change would be backward-compatible.

Does this make sense for you?

**Comment by aivinog1** [comment]
@saig0 Got it, thanks :)
