### ISSUE TITLE
AvailabilityTest.shouldActivateJobsWhenOnePartitionDown flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4795]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**
Currently no details available.

**Comment by npepinpe** [comment]
Closing as this hasn't happened in a while, and the CI pipeline is a lot more stable now. Please re-open if you see this occur again.
