### ISSUE TITLE
Extend limit of 20 partitions

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zeebe#480]
Currently, there is a limitation in broker which defines max number of partitions in the cluster which is 20. This means that we can have 20 topics with 1 partition or 1 topic with 20 partitions, either way, number of partitions should be extended or the broker should not crash on the creation of partition number 21.

This currently causes some minor issues if I run zbc-go integrations tests multiple times.

**Comment by menski** [comment]
This is a limitation of the gossip peer list at the moment as it limits the [maximal number of raft memberships](https://github.com/zeebe-io/zeebe/blob/6415b754abd27e0d4e823dcec05fd844cc7c5e4f/broker-core/src/main/java/io/zeebe/broker/clustering/gossip/data/Peer.java#L54). Hope we can get rid of this during the gossip refactoring.

**Comment by Zelldon** [comment]
I think we can closes this issue?

**Comment by menski** [comment]
This is fixed with the new gossip implementation.
