### ISSUE TITLE
I want to understand the next long polling and how the broker side handles the long polling messages. And some suggestions.

### ISSUE THREAD

**Issue by wenminglei** [zeebe-io/zeebe#4808]
I don't understand how brokers handle long polling messages. Today I saw a message broker RocketMQ (https://github.com/apache/rocketmq) that also completely uses the pull mode to process messages. 
The basic design idea is: if the consumer fails to try the Pull message for the first time (for example, there is no message that can be consumed at the Broker end), it does not immediately return a Response response to the consumer client, but first hold and suspend the request Save the request to the pullRequestTable local cache variable), and then the Broker side independent thread-PullRequestHoldService will continue to fetch from the pullRequestTable local cache variable, the specific method is to query whether the offset of the message to be pulled is less than the maximum deviation of the consumer queue The amount of shift, if the condition is true, it means that a new message has reached the Broker end (here, there will be a background independent thread on the Broker end of RocketMQ—ReputMessageService keeps building ConsumeQueue/IndexFile data, and at the same time takes out the held request and performs secondary processing ), then re-call the business processor—PullMessageProcessor's processing request method—processRequest() to retry to pull the message (here, retry every 5S, the default long polling time is set to 30s).
I think this may be similar to Zeebe's long polling. Is it necessary to compare which method is better？

**Comment by Zelldon** [comment]
Would it help if we have a better explanation how long polling works in detail in the docs?

**Comment by Zelldon** [comment]
Please read the https://docs.zeebe.io/basics/job-workers.html?highlight=long,polling#requesting-jobs-from-the-broker doc for long polling explanation. I will close this issue. Feel free to reopen it with more detailed and more specific questions.
