### ISSUE TITLE
Does Zeebe need a Contributor License Agreement

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#481]
Do we have to ask outside contributors of non-trivial patches to sign a Contributor License Agreement before merging there changes?

**Comment by menski** [comment]
@meyerdan maybe you already have some experience with this topic?

**Comment by meyerdan** [comment]
Yes. If it comes up, let me know, we have a template for that

**Comment by Zelldon** [comment]
@menski I think this is already done right?

**Comment by menski** [comment]
All Zeebe repositories have a CLA bot configured
