### ISSUE TITLE
Ignore the fmt-maven-plugin check for the jdk8 builds

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4833]
**Description**

`com.coveo:fmt-maven-plugin` version 2.10 no longer plays nicely with jdk8. This is causing problems in our release builds and blocks us from merging #4655. However, the check and format Mojo's add no value to the release and the jdk8 specific unit test builds. It should be ignored on jdk8 and lower.

**Comment by korthout** [comment]
@npepinpe I was taking another look at this. I would like to take the following solution:

- move the `fmt-plugin:format` in the parent-pom to a profile that is activated for jdk9+
- remove the `fmt-plugin:check` and `com.mycila:license-maven-plugin:check` from the release/build scripts
- add these removed check steps to a special checks profile that we activate in the release/build scripts

Do you agree with this approach?

**Comment by npepinpe** [comment]
So in `zeebe-test-container` I ended up doing the other way around - enabling it by default and disabling it for a profile called jdk8. My reasoning is that jdk8 is the exception, not the rule here, and I would argue this is the same with Zeebe.

For the other steps it sounds good :+1:
