### ISSUE TITLE
Allow using JobWorker in a try-with-resources

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4837]
**Is your feature request related to a problem? Please describe.**

I'd like to use `JobWorker` in a `try-with-resources` block, which is currently not possible even though `JobWorker` implements as `close` method.

**Describe the solution you'd like**

If `JobWorker` implements `AutoCloseable`, then I can create an instance as part of a `try-with-resources` so it can be safely closed once I'm done with it.

**Describe alternatives you've considered**

Close the worker in a finally block, which is fine but not ideal.

**Comment by aivinog1** [comment]
Hello, I would like to take this issue. It's pretty clear for me.

**Comment by saig0** [comment]
@aivinog1 that is great to hear :tada: 

Feel free to ask questions if you need help or something is unclear. 
Don't forget to look into our [contribution guide](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#create-a-pull-request).
