### ISSUE TITLE
Detect length of source document on extract and merge

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#484]
Currently if extract or merge is called with a document which contains message pack and more stuff like zero's at the end, the resulting message pack is invalid. 

We have to use a buffer which has the same length/capacity like the message pack document, but as result we get a buffer which is larger then the resulting message pack. (since the buffer is pre-allocated and increased if the result gets larger). But if we reuse this buffer in the next call the next result will be invalid since the message pack is wrong interpreted, perhaps there is a simple way to detect this. I think the problem is that we use `traverser.wrap(document, 0, document.capacity());`.

One solution would be to call merge or extract with the length of the msg pack document or wrap them before.

This is also a problem if the payload is set via the update payload command

**Comment by menski** [comment]
@Zelldon do you know if this is still the case or could you check? thanks

**Comment by Zelldon** [comment]
Seems to be an issue on merge, if the target buffer is larger as the real msg pack document.
I will take a look into that.

**Comment by menski** [comment]
Thanks. Just want to figure out if this is still valid, cause then I might put it on the list we take care of in the stability topic. So maybe you can give me an opinion how often this case can happen and if it is something we should fix in the near future.

**Comment by Zelldon** [comment]
We migrated the merging and extraction to feel, so I will close this issue. 

@saig0 correct me if I'm wrong

**Comment by saig0** [comment]
You're right. This bug is gone.
