### ISSUE TITLE
Parallel multi-instance call activity cannot collect output

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4860]
**Describe the bug**
The output of the multi-instance cannot be collected into the output collection, because its value is overwritten at the moment that one of its call activities completed. 

**To Reproduce**
Consider the following example:
<img src="https://user-images.githubusercontent.com/3511026/86255668-ae8b5e80-bbb7-11ea-885a-f6dbeae84be4.png"  height="200px">

With the following multi-instance configuration:

<img src="https://user-images.githubusercontent.com/3511026/86255733-c5ca4c00-bbb7-11ea-8d4d-003b9a6c9f47.png" height="200px">

Create an instance of this workflow with variable `inputs` = `[1,2]`

When the multi-instance activates, the output collection variable is created as a nil values array (e.g. `[null,null]`). Whenever the first called workflow completes it offers all of its variables to the call activity which copies all these variables, which overwrites the output collection. Then at the end of this multi-instance body, its output is collected into this variable, but as soon as the next called workflow completes, its overwritten to the nil values array again.

**Expected behavior**
The outputs should just be collected correctly.

**Environment:**
 - OS: macOS 10.15.5
 - Zeebe Version: 0.23.3
 - Configuration: hazelcast exporter

**Comment by saig0** [comment]
**Workaround**
Define an output mapping at the call activity. Define all variables that should be propagated from the child to the parent instance (e.g. the variable of the `output element`). The other variables will be ignored.

**Comment by raduone** [comment]
@saig0 I reached this issue. I don't exactly understand, what is the workaround.
How can you collect the variables into a collection, using the output mappings on a call activity ?
You could theoretically have a mapping of `output element` -> `some other variable`, but
in the end you would have only one variable on the parent, having the value, one of
the instances variables. (The first one I think).
So how can this approach can be used to collect the variable from all instances ?

**Comment by raduone** [comment]
@saig0 Oke, I think I understand. So you can create a mapping `output - output`. This way the output will not be changed for an instance, but any other variable will be ignored from the instance, therefore the collection variable that is in the instance, will not override the one from the call activity, that aggregates the result.
I think this is the case. Maybe you can confirm it to me, that my understanding is oke. Thank you !

**Comment by saig0** [comment]
@raduone, correct :+1: 

Let's have a quick example to make it more clear.

* multi-instance output element: `=output`
* variable in the child instance that holds the result: `x`
* output mapping on the call activity should be: 
```
source: =x
target: output
```

* if the child instance has another variable `y` then the output mapping should be:
```
source: =x
target: output.x

source: =y
target: output.y
```

**Comment by raduone** [comment]
Thanks! @saig0 :)

**Comment by saig0** [comment]
**Idea:**
* introduce a new Zeebe attribute on the call activity `propagateAllChildVariables`: `true | false`
* don't copy variables from child instances unless
  * an output mapping is defined on the call activity to map the variables explicitly, or
  * the new attribute `propagateAllChildVariables` is set to `true`
* if the new attribute is not set then it will propagate the child variables by default to be backward-compatible and not break existing workflows 
* add the attribute `propagateAllChildVariables` in the Zeebe modeler and set it to `false` by default to avoid overwriting existing variables

**Comment by saig0** [comment]
Related issue for the Zeebe modeler: https://github.com/zeebe-io/zeebe-modeler/issues/252
