### ISSUE TITLE
Test key-value lengths for put/remove/get on ZbMap impl

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#487]
Currently the methods like put, get or remove of the ZbMap implementations are not enough tested regarding to exceeding the length.

**Comment by Zelldon** [comment]
I would say this is already done. 
In the BytesArrayKey- and ValueHandler there exist a check method which is called before working with the key or value. If the size is larger then expected an IllegalArgumentException is thrown.

See also this commit https://github.com/zeebe-io/zb-util/commit/dc30431cfcbea2196cdf7a293941244e117d9fb3 which addes some missing test cases.
