### ISSUE TITLE
Benchmark 0.24.0-RC1 stopped making progress

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4871]
**Describe the bug**
The benchmark stopped making progress around 1:50 AM tonight.

***Preliminary Analysis***
(this is not a root cause analysis; rather it is a first glance at the metrics and coming up with a hypothesis)

1. Snapshot replication stopped dead
![image](https://user-images.githubusercontent.com/14032870/86441725-f4a60680-bd0c-11ea-9e9b-4552bdb8d065.png)
1. Java Memory Consumption went up
![image](https://user-images.githubusercontent.com/14032870/86441811-130c0200-bd0d-11ea-8406-11176e5603d0.png)
1. Disk was filled to the max
![image](https://user-images.githubusercontent.com/14032870/86441887-2fa83a00-bd0d-11ea-866f-17e6e7b6d4f5.png)

***Misc Observations***
* There was a several hour restart:
![image](https://user-images.githubusercontent.com/14032870/86442006-61210580-bd0d-11ea-972f-8abbdd6ae669.png)
* RocksDB took even more memory (although it must have been idle)
![image](https://user-images.githubusercontent.com/14032870/86442106-8c0b5980-bd0d-11ea-95ca-58f7d694a274.png)
* AtomixComaption stopped at the same time
![image](https://user-images.githubusercontent.com/14032870/86442228-bceb8e80-bd0d-11ea-812a-e7f830fecd78.png)

**Comment by Zelldon** [comment]
We reached again elastic limits

![pvc](https://user-images.githubusercontent.com/2758593/86443176-30da6680-bd0f-11ea-8ee0-0428a60216de.png)

**Comment by npepinpe** [comment]
Some hypotheses/guesses:

![Screenshot from 2020-07-03 09-23-23](https://user-images.githubusercontent.com/43373/86442990-e0fb9f80-bd0e-11ea-9150-b9a76e6ecda7.png)

Elastic disk filled up, which I expect is why our own PVCs filled up - but it was cleared around 3am, leaving us a full hour to export more and do compaction, yet I don't see any noticeable dip in our PVC usage after 3am...could it be that we did do some compaction but the exporter was so far behind that it didn't matter and never managed to catch up?

Snapshot replication duration is as viewed from the consumer side, so if it's out of disk space I guess it makes sense that we it stops. Further, once out of disk space, no new snapshots can be taken so we won't be pushing them out any more. We also stopped taking snapshots a bit before 2am, which makes sense if we couldn't export, but never ever tried to do so again between 3am and 4am...were we not exporting anymore, even if Elastic had disk space available at that point?

**Comment by Zelldon** [comment]
@npepinpe can you check whether elastic is set to read-only?

**Comment by Zelldon** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html

**Comment by Zelldon** [comment]
We were able to verify that elastic was [set to read-only](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-07-02T23:30:30.812000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-0240-rc1%22%0Alabels.k8s-pod%2Fapp%3D%22release-0240-rc1-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22release-0240-rc1%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0AjsonPayload.thread:%22zb-fs-workers-%22%0ANOT%20jsonPayload.exception:%22Unexpected%20error%20occurred%20during%20RocksDB%20transaction.%22&scrollTimestamp=2020-07-02T23:34:22.908084000Z&dateRangeStart=2020-07-02T22:30:30.812Z&dateRangeEnd=2020-07-03T00:30:30.812Z)

```

This was the reason why Zeebe went out of disk space.

We followed the camunda cloud runbook https://github.com/camunda-cloud/runbook/blob/master/monitoring/runbook.md to recover. 
E 2020-07-02T23:34:11.450926Z Error on exporting record with key 4503599811371405 
W 2020-07-02T23:34:11.630661Z Failed to flush 1000 item(s) of bulk request [type: cluster_block_exception, reason: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];] 
E 2020-07-02T23:34:11.631053Z Error on exporting record with key 6755399638511119 
W 2020-07-02T23:34:11.792652Z Failed to flush 1000 item(s) of bulk request [type: cluster_block_exception, reason: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];] 
```

**Comment by npepinpe** [comment]
Did the node recover after fixing Elastic and increasing the PVC size?

**Comment by pihme** [comment]
Not yet determined. Nodes keep running into OOM in Java heap space and subsequently get killed and restarted by Kubernetes. It is unknown whether the nodes can make progress before the OOM.

OOM is caused by millions of scheduled future tasks. 
![image](https://user-images.githubusercontent.com/14032870/86464941-e4078780-bd30-11ea-882f-aefcb7c8fd0e.png)

**Comment by Zelldon** [comment]
@pihme could you please check where the tasks came from? You can do it in visalvm via checking the reference

**Comment by npepinpe** [comment]
I think this might be related to https://github.com/zeebe-io/zeebe/issues/4848 - I had a quick look at the dumps and I see the same thing, 3Gb taken by the ScheduledThreadPoolExecutor

![Screenshot from 2020-07-03 13-47-59](https://user-images.githubusercontent.com/43373/86466399-d56e9f80-bd33-11ea-96e7-21bb48f11b54.png)

**Comment by pihme** [comment]
Likely to be related to #4876 

@deepthidevaki Could you confirm/refute this is related to your bug?

![image](https://user-images.githubusercontent.com/14032870/86466814-a147ae80-bd34-11ea-8dd7-20e36efb1b87.png)

We can also go over the heap dump together, if you want.

**Comment by npepinpe** [comment]
Ah, then seems like it's a different bug than #4848 :thinking:

**Comment by deepthidevaki** [comment]
@pihme I did not observe any OOM related to #4876. Also I don't know yet if #4876 is applicable in 0.24.x because we had done some refactoring in snapshot replication.

**Comment by pihme** [comment]
Still unknown why we have the OOM issues

**Comment by deepthidevaki** [comment]
My preliminary investigation says #4876 is not an issue in 0.24.0-SNAPSHOT

**Comment by pihme** [comment]
I better write down what I have observed, before I forget it:

* the scheduled thread executor service in `SingleThreadContext`is not configure to remove tasks on cancel
  * in the follower role I did see lots of cancelled tasks (albeit in a shorter work queue)
  * in the leader role I did not see many cancelled tasks
  * in the heap dump (not sure which role the broker was in) I did not see any cancelled tasks. However, I only looked at samples from the latest 1K tasks out of 6M tasks
* In the leader role most tasks came in through `SingleThreadContext#execute`, the bulk of it was alternating:
  * `io.atomix.raft.impl.zeebe.ZeebeRaftStateMachine#applyIndex --> io.atomix.raft.impl.RaftContext#setLastApplied`, and
  * ` MessageDispatcher#channelRead0 --> runOnContext(() -> role.onJoin(request)` from `io.atomix.raft.impl.RaftContext#registerHandlers`
  * the alternation seemed to be exact; for each apply index there was one join request. Not sure what to make of this
* In the follower role tasks came in through `runOnContext(() -> role.onJoin(request)` from `io.atomix.raft.impl.RaftContext#registerHandlers` and the work queue was considerable shorter (most of the time < 20, but sometimes also in the order of 100K)

Debugging was difficult, because stopping code in debugger has an effect on the perceived speed of the broker.

**Comment by npepinpe** [comment]
It would seem `snapshot-20200702-d92acde53` is in the same boat. It segfaulted due to the metrics exporter (this is now fixed), and now there's some heap dumps there. It hasn't be able to run since the 4th of July, and it can never get ready _but_ the memory is churning like crazy, so something's happening.
