### ISSUE TITLE
Start metrics server before other services

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#4872]
**Description**

Currently we start metrics server after clustering step https://github.com/zeebe-io/zeebe/blob/d937676cde6e12a7d8584860e9f3bf900a710385/broker/src/main/java/io/zeebe/broker/Broker.java#L174

Clustering step in general takes longer to start and some times too long. Since the metrics server is started after that, we don't get any metrics to investigate if something goes wrong during starting clustering step.

**Comment by npepinpe** [comment]
Verify if this would solve getting metrics as soon as possible for non-ready pods.

**Comment by deepthidevaki** [comment]
While debugging another issue, we were able to directly get metrics (some of them) from the broker even though it is not available in Grafana. So I don't think not starting the server is the problem.

**Comment by npepinpe** [comment]
Thanks for verifying :) Then I would say it's not as important then.

**Comment by npepinpe** [comment]
Wouldn't help at all right now since we have to wait for partitions to be ready for zeebe_health metric to be emitted.
