### ISSUE TITLE
Zeebe Event Subprocess unable to trigger multiple times

### ISSUE THREAD

**Issue by arpitagarwal78** [zeebe-io/zeebe#4878]
**Describe the bug**
As per the documentation 

https://docs.zeebe.io/bpmn-workflows/event-subprocesses/event-subprocesses.html

_A non-interrupting event subprocess can be triggered multiple times. An interrupting event subprocess can be triggered only once._

**To Reproduce**
Tried Non interrupting event similar message not getting correlated twice.

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**
Should allow me to trigger subprocess event multiple times.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux] MAC
 - Zeebe Version: [e.g. 0.20.0]  0.23.1
 - Configuration: [e.g. exporters etc.]

Sample Image

<img width="521" alt="Screenshot 2020-07-03 at 5 20 24 PM" src="https://user-images.githubusercontent.com/37263155/86466905-21304180-bd52-11ea-82d5-9e1f550ae79b.png">

**Comment by saig0** [comment]
Hi @arpitagarwal78 :wave: 

Were you able to solve the issue?
What was the problem?
