### ISSUE TITLE
Reducing the overall workflow instance completion latency

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4879]
**Description**

Today @saig0  and I did a slack day to investigate whether we are able to reduce the workflow instance completion latency via batch processing. 

**TL;DR**

Yes. We reduced the latency by factor two. Branch https://github.com/zeebe-io/zeebe/tree/4879-workflow-batch-processing

## Changes

With the changes we process in batch until a wait state. This means we start to process and write follow up events in a queue to directly process them afterwards. Concurrently we write the events also in the current batch. After reaching a wait state we completing our processing, which means we commit the transaction and flushing our batch.

## Test - Setup

In order to just test the latency we reduced the load to 10 workflow instances per second.
The job worker poll interval was set to 1 ms and also the job completion delay to 1 ms.

 * three nodes
 * three partitions
 * repl. factor three
 * 12 workers

### Test One

We tested with one task:

![one-task](https://user-images.githubusercontent.com/2758593/86466882-bde3e680-bd34-11ea-93dc-57388de4a07d.png)

Without the changes we need ~ 1 - 2.5 seconds to complete a workflow instance.

With our changes we need ~500 - 750 ms
![changes-one-task](https://user-images.githubusercontent.com/2758593/86466877-bd4b5000-bd34-11ea-83d7-62f60e09ab32.png)

### Test Two

We also tested the workflow instance completion with ten sequential tasks. Notice the job completion is directly done.

![ten-task](https://user-images.githubusercontent.com/2758593/86465847-bd4a5080-bd32-11ea-8bfe-4623f1c744d2.png)

Without the changes we need ~ 5 - 7.5 seconds to complete a workflow instance.

With the changes we need ~ 2.5 - 5 seconds to complete the workflow instances in avg.
![changes-ten-task](https://user-images.githubusercontent.com/2758593/86465844-bc192380-bd32-11ea-8767-4b794d24aeec.png)

**Comment by npepinpe** [comment]
Did you mean completion delay to 1ms instead of 1s?

**Comment by Zelldon** [comment]
@npepinpe yes sorry :D

**Comment by Zelldon** [comment]
Yeah this is a thing which we need to investigate - I think we could mark multiinstance as wait state and process it separately maybe

**Comment by menski** [comment]
> This means we start to process and write follow up events in a queue to directly process them afterwards. 

Do you process them before they are committed, i.e. replicated to the replicas?

**Comment by Zelldon** [comment]
Yes

**Comment by Zelldon** [comment]
Regarding to @npepinpe 

>Also we'd previously discussed something like this, but how would this handle, say, a huge multi instance sub process where you may have to do tons of processing until the next wait state?

This is already a problem we have.

**Comment by Zelldon** [comment]
Just did some new tests with MMap file and no replication.

One Task workflow execution latency:

![changes-mmap-one-task](https://user-images.githubusercontent.com/2758593/86497183-e72a6400-bd80-11ea-91a6-bee71c957b10.png)

It goes down to 25-50 ms !

Ten task workflow execution latency:

![changes-mmap-ten-task](https://user-images.githubusercontent.com/2758593/86497208-02956f00-bd81-11ea-84fc-14c5b38e84a5.png)

The latency is the similar as before with one task without mmap and replication on at the begining at least.

It fluctuates a bit, but looks still better
![changes-mmap-ten-task-2](https://user-images.githubusercontent.com/2758593/86497367-c282bc00-bd81-11ea-94d7-4a502df17d8b.png)

**Comment by npepinpe** [comment]
Great stuff, let's talk about the PR before merging.

**Comment by Zelldon** [comment]
@nico will you look at this during your latency improving?


I think we need to discuss some certain points regarding the changes.

For example:

 * We process until wait states, which means we can reduce the latency of single workflow instance's. But it might be bad for big load scenario, several running instances in parallel.
 * It changes the behavior how we process records in general
    * It is not possible to interrupt instances between wait states, before we were able to cancel instances everywhere
 * We could end in endless processing loops - call activties calling same workflow
   *  Can be avoided with interrupting processing after reaching an specific amount of time or follow up events.

There are probably other things we need to discuss maybe @saig0 you have some additions.

**Comment by saig0** [comment]
> We process until wait states, which means we can reduce the latency of single workflow instance's. But it might be bad for big load scenario, several running instances in parallel.

I don't see a downside for the throughput if we limit the number of steps that are done in a batch to a reasonable number (e.g. 10-30). It might be a good idea to make this number configurable.

> It changes the behavior how we process records in general
It is not possible to interrupt instances between wait states, before we were able to cancel instances everywhere

Yes, in theory, this is true. But I think in practice, this is not a difference. If you cancel a workflow instance in Operate then the state that you see is already a few seconds or more old.

> We could end in endless processing loops - call activties calling same workflow
Can be avoided with interrupting processing after reaching an specific amount of time or follow up events.

Yes. This can be fixed by limiting the number of steps.

One bigger challenge is the max. message size. If we process more records at once then we also write more records in a batch.  Especially for multi-instance, it is more likely that the batch exceeds the max. message size.

**Comment by korthout** [comment]
@Zelldon I assume you meant me 😄 

I'll definitely bring this up at the next discussion on cycle time improvements. Cool stuff.

**Comment by Zelldon** [comment]
Haha yes @korthout you're right sorry @nico 😃

**Comment by npepinpe** [comment]
As we've achieved our current performance goals for this quarter, I'm downgrading this. I'm not closing it however as I think there's merit to it and we should get around to digging more into this.

**Comment by npepinpe** [comment]
If that's OK, I would close this now - I imagine we'll get around to working on this, but I'd wait until our PM gives us actionable performance goals.
