### ISSUE TITLE
Bytes2LongZbMap: Do not copy keys and values on get/put/remove

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#488]
There is no benefit in copying the key.

**Comment by Zelldon** [comment]
Done on https://github.com/zeebe-io/zb-util/commit/4c4b8437b5ef70d26e79426641e55a692159468b for the BytesArrayValueHandler. Needs to be done for the ByteArrayKeyHandler.

**Comment by ThorbenLindhauer** [comment]
Review:

* `ByteArrayKeyHandler#keyEquals`: Should ensure that all remaining bytes are 0
* `ByteArrayKeyHandler#keyHashCode`: Should include remaining 0 bytes in the computation to ensure that keys [1, 2, 3] and [1, 2, 3, 0, 0] receive the same hash code (which is the contract of the map)
