### ISSUE TITLE
Handle snapshots with many chunks

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#4887]
**Description**

While investigating #4784, it was observed that the snapshots in that cluster had more than 20000 chunks. Since the snapshot replication initiated via raft sends the chunk sequentially, it takes several minutes (>15 min) for a follower to catch up its state.

* Investigate why there are so many chunks in a snapshot even though the overall snapshot size was < 100mb. Investigate how to tune Rocksdb to minimize the number of chunks and the impact of it.
* Investigate if we can improve the speed of snapshot replication via raft.

**Comment by Zelldon** [comment]
https://github.com/facebook/rocksdb/wiki/Compaction 

> Options::target_file_size_base and Options::target_file_size_multiplier - Target file size for compaction. target_file_size_base is per-file size for level-1. Target file size for level L can be calculated by target_file_size_base * (target_file_size_multiplier ^ (L-1)) For example, if target_file_size_base is 2MB and target_file_size_multiplier is 10, then each file on level-1 will be 2MB, and each file on level 2 will be 20MB, and each file on level-3 will be 200MB. Default target_file_size_base is 64MB and default target_file_size_multiplier is 1.

Just a guess but maybe the reason?

**Comment by npepinpe** [comment]
We think it may affect production users who have low load, so first step is to confirm this. If this is false, then let's re-prioritize.

**Comment by deepthidevaki** [comment]
https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool This might be useful to manually compact the snapshots when it has too many chunks. I didn't test it. But might be worth looking into.

**Comment by Zelldon** [comment]
I think I can reproduce it.

I starting one workflow and complete it per second.
![general](https://user-images.githubusercontent.com/2758593/89533123-35ed7280-d7f3-11ea-91fc-05061dcd7951.png)
![resource](https://user-images.githubusercontent.com/2758593/89533127-36860900-d7f3-11ea-9f6f-e60e8a5acbe7.png)

RocksDB and snapshot seem to be increasing.
![rocks1](https://user-images.githubusercontent.com/2758593/89533128-371e9f80-d7f3-11ea-8531-c7f1a6188526.png)
![rocks2](https://user-images.githubusercontent.com/2758593/89533129-384fcc80-d7f3-11ea-8d62-576655d3c433.png)
![snapshot](https://user-images.githubusercontent.com/2758593/89533130-384fcc80-d7f3-11ea-83b8-69bbe75f5211.png)

**Comment by deepthidevaki** [comment]
Thanks @Zelldon

**Comment by deepthidevaki** [comment]
Yesterday I tried to use [ldb tool](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool) to manually compact a snapshot. I tried it on a snapshot with 63 files, and after compaction it was 55 files. So it looked good. Then I tried it on a snapshot with ~23000 chunks. But it did not compact and the number if files remained unchanged :shrug:

**Comment by deepthidevaki** [comment]
@Zelldon Since low load is causing this I think taking [load based snapshot](https://github.com/zeebe-io/enhancements/pull/5) would prevent this.

**Comment by Zelldon** [comment]
At least it will delay it but still we would have at some point lot of SST files 😃

**Comment by npepinpe** [comment]
Even with having followers build their own state, we would run into this potentially on start up (which is what we're trying to solve right now). I think the solution is to look into replicating with fixed size chunks. It may still take some time however if the state is quite large, so having some level of parallelism is also important. I missed half the discussion last time, what was the final consensus?

**Comment by deepthidevaki** [comment]
We decided that we will work on improving raft replication protocol.

**Comment by deepthidevaki** [comment]
Closing this issue as we 
* Improved snapshot replication and now restart is very fast even if there are many files in a snapshot #5135 
* Have another issue for large number of files in a snapshot https://github.com/zeebe-io/zeebe/issues/5137
