### ISSUE TITLE
Serialized hash index should contain more information for validation during deserialization

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#489]
The only information which is persisted during the serialization of a hash index is the version of the serializer.

The following information are not persisted:
- length of the index buffer resp. index size
- length of the data buffer
- key length
- max block length

As these information are missing we assume that the serialized hash index is always restored into a identically configured hash index (index size, key length, max block length). But we cannot check this during deserialization without these information. This means a deserialization in a different hash index configuration can cause illegal memory access, or the usage afterwards.

We also assume that we can read the full snapshot during deserialization. We cannot differentiate between an expected end of stream and an IO error. If an early end of stream happens while reading the data buffer the deserialization is successful. But if the index is used afterwards the index store can contain offsets outside of the allocated memory and cause illegal memory access.

**Comment by Zelldon** [comment]
Currently we see no case where this could happen. That's why we will close this issue.

> We also assume that we can read the full snapshot during deserialization. We cannot differentiate between an expected end of stream and an IO error.
We have unit test which test read and write with repeatedly failing Input/OutputStream,
see io.zeebe.map.BucketBufferArrayIOTest or op.zeebe.map.ZbMapSerializerTest.
