### ISSUE TITLE
peekBlock() should return error code if available block is greater than given max size

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#492]
AT:
* `Subscription#peekBlock()` return a specific error code if a block / fragment is available which has is larger than the given max size
* so the caller can handle this error (i.e. increase the size) - otherwise, the caller can not peek any further blocks

**Comment by saig0** [comment]
It seems that this is currently not an issue. So, let's close the issue and open new issues if we see any concrete problems.
