### ISSUE TITLE
Elasticsearch exporter seems to have stopped exporting records

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#4921]
**Describe the bug**
We have observed in our Zeebe cluster that Elasticsearch exporter is not exporting records to our Elastic cluster. I have verified that it is not an issue with Elastic cluster, as my local Zeebe instance is able to export the records to the same cluster.

**To Reproduce**
Not available. This happened couple of days back and the cluster has restarted after that, but the exporter issue still exists.

**Expected behavior**
Exporter should be able to export all records to Elastic cluster.

**Log/Stacktrace**
No error or warning logs are getting printed. Current broker logs shows that the exporter was successfully opened. Still we are not seeing any documents on elastic search.

```
2020-07-08 17:27:56.788 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] [36mDEBUG[m io.zeebe.broker.exporter - Open exporter with id 'elasticsearch'
2020-07-08 17:27:56.807 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] [32mINFO [m io.zeebe.broker.exporter.elasticsearch - Exporter opened
```

**Environment:**
 - Zeebe Version: `0.23.2`

<details><summary>Configuration</summary>
 <p>

```
Starting standalone gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 26500,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "prod-zeebe-zeebe-broker:26502",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "100.100.128.4",
    "port" : 26502
  },
  "threads" : {
    "managementThreads" : 2
  },
  "monitoring" : {
    "enabled" : true,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  }
}


Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26501,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501",
      "address" : "0.0.0.0:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26502,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502",
      "address" : "0.0.0.0:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 9600,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:9600",
      "address" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-1.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 0,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK"
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : url,
        "bulk" : {
          "delay" : 15,
          "size" : 1000
        },
        "authentication" : {
          "username" : user,
          "password" : password
        },
        "index" : {
          "prefix" : "zeebe-prod",
          "createTemplate" : true,
          "command" : true,
          "event" : true,
          "rejection" : true,
          "deployment" : true,
          "error" : true,
          "incident" : true,
          "job" : true,
          "jobBatch" : true,
          "message" : true,
          "messageSubscription" : true,
          "variable" : true,
          "variableDocument" : true,
          "workflowInstance" : true,
          "workflowInstanceCreation" : true,
          "workflowInstanceSubscription" : true,
          "ignoreVariablesAbove" : 16384
        }
      },
      "external" : false
    },
    "hazelcast" : {
      "jarPath" : "/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar",
      "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args" : {
        "port" : 5701,
        "enabledValueTypes" : "DEPLOYMENT,JOB,WORKFLOW_INSTANCE,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION",
        "enabledRecordTypes" : "EVENT",
        "name" : "zeebe",
        "capacity" : 100000,
        "timeToLiveInSeconds" : 300,
        "format" : "protobuf"
      },
      "external" : true
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}

```

</p>
</details>

**Comment by strawhat5** [comment]
After investigating deeper into Elasticsearch cluster, we observed that the documents were getting indexed very slow. It was not an issue with Zeebe exporter. Sorry for the false alarm. :)

Hence marking this issue as closed.

**Comment by strawhat5** [comment]
Hey opening up this issue again, as I found some more observations. We actually didn't hit the CPU/Memory limits on Elasticsearch cluster (as you can see below), and the indexing has been happening at a decent pace.

<img width="613" alt="Screenshot 2020-07-11 at 9 13 44 PM" src="https://user-images.githubusercontent.com/10865861/87227975-e49cbf80-c3bb-11ea-9544-663a03716de6.png">



**But I did observe delay in Zeebe broker while exporting records to Elasticsearch.** Attaching some relevant details below:

<img width="1363" alt="Screenshot 2020-07-11 at 9 01 44 PM" src="https://user-images.githubusercontent.com/10865861/87227969-d8186700-c3bb-11ea-9bd1-df4de6a09b1a.png">

As you can see in the above image, we had a huge load of `Job activated` requests which started flooding into Zeebe 2 days ago. And since then, the `Processor vs Exporter` graph started going **positive to a high value**, until we finally shut down the source of incoming `Job activated` requests (around 07/11 00:00 in the graph). Post that, it has started going negative which means it is gradually catching up with the non-exported records.

I also observed Zeebe hitting CPU and Memory limits until the time we shut down the incoming requests.

<img width="1347" alt="Screenshot 2020-07-11 at 9 02 27 PM" src="https://user-images.githubusercontent.com/10865861/87227972-e1a1cf00-c3bb-11ea-8645-9289f7af17cb.png">

It indicates that probably our Zeebe cluster with the current CPU/Memory configurations is not capable to handle such high volumes. Adding our current configs below:
```
resources:
  limits:
    cpu: 2
    memory: 10Gi
  requests:
    cpu: 1
    memory: 10Gi

cpuThreadCount: 2
ioThreadCount: 2
```

If the above analysis is correct, could you guys suggest any further tuning to the current configuration? Also, if there are some benchmarks on Load vs CPU/Memory configurations, that would be a great reference for us. I know the easy answer would be `It Depends!` 🙂 , still few recommendations here would help us in tuning our cluster better.

**Comment by Zelldon** [comment]
Hey @strawhat5 

sorry for the late response.

As you already mention it depends :smile:
But as you already shared your configuration I will try to work with that. 

I would suggest to put the threadCount's to three, since you have three partitions.

```
cpuThreadCount: 3
ioThreadCount: 3
```

SideNote: `cpuThreadCount` is used for processing `ioThreadCount` is used for exporting.

I would increase the limits to something like
```
resources:
  limits:
    cpu: 5
    memory: 10Gi
  requests:
    cpu: 3
    memory: 10Gi
```

The are also other threads which have to be run like raft etc. which are currently unrelated to `cpuThreadCount` and `ioThreadCount`
You can also find our default benchmark config here https://github.com/zeebe-io/zeebe/tree/develop/benchmarks/setup

Hope that helps.

Greets
Chris

**Comment by strawhat5** [comment]
Thanks Chris for sharing these details! I'll definitely try out your suggestions.

**Comment by Zelldon** [comment]
Hey @strawhat5 did you tried the configuration? Can we close this issue?

**Comment by strawhat5** [comment]
Hey sorry I forgot to update this thread. Yeah I tried the suggested configs, and it did speed up the exporter. Closing this issue now.

**Comment by Zelldon** [comment]
Thanks @strawhat5 :+1:
