### ISSUE TITLE
offer() and claim() should return fragment offset

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#493]
Currently the offer() and claim() methods return the "next position" ie. the position at which the next message would be written.
It would be probably better if the methods returned the position of the message which was written. This way, the position could be used to uniquely identitfy the message which was just written, not the "next message". It would then play the role of a unique message id and could also be passed in to the frame and block handlers.

**Comment by saig0** [comment]
It seems that this is currently not an issue. So, let's close the issue and open new issues if we see any concrete problems.
