### ISSUE TITLE
I can poll the file channel if log buffer uses memory mapped file

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#494]
In case the log buffer is placed in a memory mapped file writing to the buffer means writing to the os page cache. Most OSs can efficiently transfer data from page cache to a network socket (or to another file) without any copies in user space.

Allowing consumers on the dispatcher to poll the underlying fileChannel allows them to efficiently replicate the buffer to a log file or over the network.

See also
- http://man7.org/linux/man-pages/man2/sendfile.2.html
- Java NIO FileChannel transferTo()
- https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/java/uk/co/real_logic/aeron/logbuffer/FileBlockHandler.java

**Comment by npepinpe** [comment]
Would require a lot of refactoring to apply to Atomix - we can revisit this if we are ever in a state where this is again possible
