### ISSUE TITLE
Performance drop between 0.20 and 0.23

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4942]
**Describe the bug**

One user in Slack reported running benchmarks on a beefy single node machine, testing various configurations between 0.20 and 0.23. We're all aware of the performance drop, and have many ideas on how to fix it, but I figured I'd add the issue here as there were some interesting observations from their benchmark.

> The VM we are testing is 16 core 32 GB memory. the "normal" in disk description is 'ssd'.
> Let us suppose some founding here:
> May be starting from 0.21, there are some code change which significant increased the IO.
> May be starting from 0.22, the CPU can not be used fully utilized, may be there is some algorithm or some limitation to protect or prevent the broker from consuming more CPU.
> IO is somehow a bottleneck in recent versions

![image](https://user-images.githubusercontent.com/43373/87150609-b4b5c500-c2b2-11ea-8b7e-2b01a485e4ea.png)

The user also tried with different `cpuThreadCount` and `ioThreadCount`, but there didn't seem to be much of a difference.

> we did try to tune it with cpuThreadCount higher,  for example 12( as we used 16 core, so we make it as high as possible) , but there's no big difference between the value 2 and 12 for cpuThreadCount, in our performance testing. our ioThreadCount is 4 or 2, and also no big difference in performance.  we did check the threads details and we did see 12 threads opened in the top output. but all of the threads only consume about 20% CPU.  and a theads called  raft-xxxxx comsumes about 100% CPU.  add them all is the real CPU cosumming, around 300% CPU.

One other interesting observation was this one:

> curious about one question about IO. when doing the performance test, we see the log  folder size growing rate is around 2 Mb/s, but when we use the iostat to monitor the disk IO, we see the the write bytes keeps high at around 12 Mb/s.  as you said this IO is only for logging, but why it shows high in iostat, not in the real file size?

**To Reproduce**

Start a VM with 16 CPU, 32Gi RAM, SSD disk. I will try to get more info from the user about how exactly the benchmark is ran.

**Comment by floydljy** [comment]
[performance.zip](https://github.com/zeebe-io/zeebe/files/4910433/performance.zip)

add some detail output. please check the two testing between mmap enabled and disabled. 

mmap significantly improved the performance , the result is doubled than the mmap disabled( 3xx : 8xx)

The observation about the IO things, please check the "command output" in the test of "without_mmap"

the folder we monitored is the "data" folder. 

Hope it can help you to investigate. 

Thanks.

**Comment by PinoNTK** [comment]
@npepinpe we got the same issue when using Zeebe version 0.22.x. We run benchmarks with various versions from 0.21.x to the latest 0.25.x and the results are quite same as yours. With version 0.21.x (0.21.0-alpha3), we see Zeebe can make use of CPUs. It means CPUs' usage is high and equal in each core but it is low with the other versions. I think maybe we're missing some configs?
Have you figured out anything?
Currently, we are running benchmarks on a server with 16 CPUs, 16G RAM, HDD Disk.

**Comment by korthout** [comment]
> We run benchmarks with various versions from 0.21.x to the latest 0.25.x

If you're trying out `0.25.0`, I suggest that you try to the `data log segment file channels should be memory mapped` configuration. This should optimise IO.

You can enable this by setting the env var `ZEEBE_BROKER_DATA_USEMMAP` to `true` or by setting the config property `zeebe.broker.data.useMmap` to `true`.

Note, that this is an experimental setting. It is not yet as mature as direct file channels (default). I recommend to first test this for your usecase before applying it to production. I'm curious to hear whether this solved your issues.

**Comment by PinoNTK** [comment]
> > We run benchmarks with various versions from 0.21.x to the latest 0.25.x
> 
> @PinoNTK If you're trying out `0.25.0`, I suggest that you try to the `data log segment file channels should be memory mapped` configuration. This should optimise IO.
> 
> You can enable this by setting the env var `ZEEBE_BROKER_DATA_USEMMAP` to `true` or by setting the config property `zeebe.broker.data.useMmap` to `true`.
> 
> Note, that this is an experimental setting. It is not yet as mature as direct file channels (default). I recommend to first test this for your usecase before applying it to production. I'm curious to hear whether this solved your issues.

Oh, great, I'll try it and reply you as soon as possible!!! :D

**Comment by npepinpe** [comment]
From our point of view, we've achieved a substantial gain - I'd still like to wait and hear what users have to say, but I will already downgrade the priority and mark it as needs information for now.

**Comment by npepinpe** [comment]
Closing for now as we believe we achieved something on par (if not with the same behaviour) as before. More improvements will come, but they should be tracked in their own issues.
