### ISSUE TITLE
High execution times for clusters with replication factor > 1

### ISSUE THREAD

**Issue by hisImminence** [zeebe-io/zeebe#4948]
**Description**
We added a panel showing the execution time of instances being processed by our e2e test.
Interestingly, cluster with `replication factor > 1` are having execution times up to 20 sec, on our `production S` cluster on `prod`-stage. See [grafana E2E dashboard](https://grafana.internal.camunda.io/d/LyetkKRUy/e2e-tests?orgId=1&from=now-24h&to=now&refresh=30s), panel `Existing cluster test: instance execution time [ms]`.

This dashboard is showing the execution time for 2 clusters:

![image](https://user-images.githubusercontent.com/55736962/87292151-ab219c80-c500-11ea-9ff2-0a23af67fffd.png)

Checking these times with [operate](https://b9de84b3-70ae-46cb-bf1b-c53bdd881822.operate.camunda.io/#/instances?filter={%22workflow%22:%22e2e%22,%22version%22:%221%22,%22incidents%22:true,%22active%22:true,%22completed%22:true,%22canceled%22:true}&name=%22e2e%22), seem to confirm these time intervals:
![image](https://user-images.githubusercontent.com/55736962/87298326-4ec37a80-c50a-11ea-9449-fa59fcbdc22c.png)

This is also happening with the e2e-test clusters on [`int`-stage](https://grafana.internal.ultrawombat.com/d/LyetkKRUy/e2e-tests?orgId=1&refresh=30s), having a `replication factor >1`.

We are using the worker `"zeebe-node": "^0.23.3"` and thought that as it happens just to clusters with `replication factor > 1`, its probably not correlated to the worker. Anyway, it is not blocking us in any way. We just wanted to let you know in case this is not a known issue yet.

**Comment by npepinpe** [comment]
Hey @hisImminence, thanks for reporting. Just some quick questions:

1. What versions are these clusters on? Also 0.23.3?
1. How old are these clusters?

As we don't see this in our own tests, I'm thinking there may be something going on with how your tests are built, but the above questions might already help.

**Comment by hisImminence** [comment]
Of course! So the cluster with the high execution times in production is the:
* `Production S`-cluster
* version `Zeebe 0.23.4`
* cluster creation time: 2020-07-06 ~9:00 am

**Comment by npepinpe** [comment]
This is not the case any more

![Screenshot from 2020-12-14 14-26-37](https://user-images.githubusercontent.com/43373/102086458-6c2da500-3e18-11eb-92be-83897b21732b.png)

**Comment by hisImminence** [comment]
Nice!!! Great job!
