### ISSUE TITLE
Only promise throughput which respects max message size

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4956]
**Description**

I think in general it is clear that variable size impact the throughput. I just want to summarize my observations in this issue and highlight that we can only promise throughput goals which uses the max message size. This might be again a good reason to shrink the max message size.

Example benchmarks:

 * Throughput with 42 kb variables, ~250 workflow events /s.
 * Throughput with 1 MB variables, ~20 workflow events /s.

I will add later some more observations.

**Comment by Zelldon** [comment]
Throughput with 300 workflow instance creations per second and variable size 42 kb. 

![throughtput-small-variables](https://user-images.githubusercontent.com/2758593/87395067-001ceb80-c5b1-11ea-8f0f-664b532a2477.png)

Throughput with 300 workflow instance creations per second and variable size 1 MB. 

![throughput-big-variables](https://user-images.githubusercontent.com/2758593/87395097-0e6b0780-c5b1-11ea-973a-00ccbcdc751e.png)

**Comment by saig0** [comment]
Other factors related to variables that might have also an impact are:
* the number of variables
* the input/output variable mappings in the workflow
* the fetched variables of job workers
* usage of multi-instance or call activities
* usage of variables in expressions (e.g. exclusive gateway)

**Comment by Zelldon** [comment]
Our benchmark setup corresponds almost to the cluster M plan where we have

![clusterplans](https://user-images.githubusercontent.com/2758593/87396000-82f27600-c5b2-11ea-88e5-80e622af1f35.png)

**Comment by menski** [comment]
Just to be clear `Flow Nodes/s` is not equal to `Workflow instances/s`, i.e. I used the following metric to calculate it.

```
sum(rate(zeebe_element_instance_events_total{action=\"completed\", type!=\"PROCESS\", namespace=\"$namespace\"}[1m]))
```

Meaning the number of other elements and tasks in the process also important for this metric. I think we have to come up with a average process to give any number at all.

**Comment by Zelldon** [comment]
Thanks for sharing. Yes what I wanted to highlight with the results above is that when we have larger variables values we will not reach our current goals.

**Comment by Zelldon** [comment]
For reference:

How we tested the current goals:

> @zell I have a process which creates tasks in parallel using a loop https://raw.githubusercontent.com/menski/cloud-benchmark/master/src/main/resources/bpmn/parallel-tasks.bpmn with a ~1kb payload https://raw.githubusercontent.com/menski/cloud-benchmark/master/src/main/resources/payload/loop.json which creates 30 tasks per instance before finishing, code can be found here https://github.com/menski/cloud-benchmark

**Comment by npepinpe** [comment]
The current goal is to track and verify that we meet our promised goals. Once we start tracking, if we figure out certain configurations don't allow us to meet those goals, then we should either:

1. Provide a different configuration
1. Fix the issues which prevent us

Without more info it's hard at the moment to decide a general course to take, so once we have more info we start on a case-by-case and develop a rule of thumb from there.

**Comment by npepinpe** [comment]
We're currently tracking FNI/s, which is great; the last step needed to do before GA is to verify that we can maintain the promised throughput under load for each cluster type. This may be something we can achieve by including the load tests in the testbench (though unsure how we would measure the FNI/s with the testbench - maybe @pihme has some ideas there).
