### ISSUE TITLE
Variable state is not cleaned up if an event is triggered

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4957]
**Description**

When an event (timer/error) is triggered for a workflow instance then it inserts data in the variable state. This data is not removed when the workflow instance is completed/terminated. 

As a result, the RocksDB state and the snapshot size grows over time and can finally lead to out-of-disc-space.

**Comment by Zelldon** [comment]
I can back this up with data.

I created yesterday a benchmark (default setup). Where I created and completed 10 workflow instances per second and variable size 1 MB. We can clearly see that the rocks db size is growing.


![mem](https://user-images.githubusercontent.com/2758593/87394194-b67fd100-c5af-11ea-840b-4a1d548457e4.png)
![rocks-mem](https://user-images.githubusercontent.com/2758593/87394197-b7186780-c5af-11ea-879b-996519a5828e.png)
![rocks-mem-tables](https://user-images.githubusercontent.com/2758593/87394200-b7186780-c5af-11ea-8788-25b8686fe19c.png)
![throughput](https://user-images.githubusercontent.com/2758593/87394202-b7b0fe00-c5af-11ea-8e9a-7b0b904c0bd5.png)
