### ISSUE TITLE
Rolling update not possible with 0.24

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4961]
**Describe the bug**

We removed in the last version unused requests, commands, primitives and sessions etc. from atomix, related PR https://github.com/zeebe-io/zeebe/pull/4466.

The problem is that  we remove types from the RaftNamespace [here](https://github.com/zeebe-io/zeebe/commit/d34a70ac0ead5ff927ea939d695576da626412a0#diff-21fe866d2487733146e40ee22dcef1b0), which breaks rolling updates.

Internally the atomix namespace classes are based on kryo, which assign each registered type an index. If you remove one of these types in between the types get different values as on the previous version. It is like an enum ordinal.

To fix this for the storage we introduce `void` types into the namespace to keep the ids
https://github.com/zeebe-io/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftNamespaces.java#L102-L114

For the communication namespace we haven't done that, because no test were failing. The problem was we had no tests for rolling updates.

**Comment by npepinpe** [comment]
Either as part of this or as a separate issue, let's add a test for rolling upgrade. We should be able to do that with test containers
