### ISSUE TITLE
I can get log stream info without opening the stream

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#497]
AT:
- I can get information on a log stream without opening the stream in the way that it is possible to write to it.
- Provided information is: position of last event in the stream

Usecase: when using an externally managed write buffer, I must set the correct log partition id on the write buffer before providing it to the stream builder. In order to do that correctly, I need to know the position of the last event in the stream without actually opening it for writing.

Related to #10

**Comment by Zelldon** [comment]
we replaced our log stream with atomix
