### ISSUE TITLE
Default settings ignored when using SPRING_CONFIG_LOCATION

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4976]
**Describe the bug**

When using the environment variable `SPRING_CONFIG_LOCATION` then the internal configuration in `application.properties` is ignored. 

This is bad, because without the internal configuration, no metrics are available.

This is also bad, because at various places it is recommended to use this environment variable.

**Expected behavior**
Change documentation and examples to either not use this environment variable, or to explain how to use it properly

**Environment:**
 - Zeebe Version: > 0.23

**Comment by Zelldon** [comment]
Dumb question why are these values:

```
management.endpoint.health.show-details=always
management.health.elasticsearch.enabled=false
management.health.ping.enabled=false
#Metrics related configurations
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoint.health.group.startup.include=gatewayStarted
management.endpoint.health.group.startup.show-details=never
management.endpoint.health.group.liveness.include=gatewayStarted,livenessGatewayResponsive,livenessGatewayClusterAwareness,livenessGatewayPartitionLeaderAwareness,livenessDiskSpace,livenessMemory
management.endpoint.health.group.liveness.show-details=never

```

Not defaults in code if we rely on them?

**Comment by pihme** [comment]
Here we are using Spring classes. Their defaults are defined in the depth of the Spring Jars. 
What the file above does is overwrite the Spring defaults.

**Comment by Zelldon** [comment]
And we can't set it in the Broker directly?

**Comment by pihme** [comment]
I don't know how. Besides, all of the settings are evaluated way before the Broker starts.

**Comment by Zelldon** [comment]
ok nevermind I just had the feeling that the current approach is a bit vulnerable

**Comment by npepinpe** [comment]
Is this not possible in Spring via an EnvironmentPostProcessor, or maybe ApplicationContextInitializer? e.g. Spring Sleuth does it from what I remember for tracing defaults, see https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java

Though yeah doesn't seem like the cleanest thing =/

**Comment by npepinpe** [comment]
After discussion, this simpler approach is a better fit since the other ways would prevent users from configuring these things, so the additional complexity isn't worth it. Users can still provide additional configuration by overwriting the `application.yml` file or using the `SPRING_CONFIG_ADDITIONAL_LOCATION` environment variable.
