### ISSUE TITLE
Detect whether last event was fully written in FSLogStorage

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#498]
When re-opening ("recovering") a log stream, the last event in the stream may or may not be fully written. (System may have been killed or crashed  in the middle of a write operation).

As part of the log stream opening and closing lifecycle a mechanism for validating the last event needs to be established

**Comment by meyerdan** [comment]
AFIK we have this behavior. @saig0, do we have it?

**Comment by Zelldon** [comment]
Atomix will replay the latest events
