### ISSUE TITLE
Unable to build stable/0.23 branch

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4985]
**Description**

Currently it is not possible to build the stable/0.23 branch.

This ticket is to figure out why and to fix this.

**Comment by saig0** [comment]
I saw the following failures a lot on `0.23`:

```
Test / testInstallSnapshotOnApply – io.atomix.raft.impl.RaftServiceManagerTest
Test / testInstallSnapshotOnApply – io.atomix.raft.impl.RaftServiceManagerTest
Test / testStreamSnapshot – io.atomix.raft.storage.snapshot.impl.FileSnapshotStoreTest
Test / shouldReportUnhealthyWhenLeaderTransitionFailed – io.zeebe.broker.it.health.HealthMonitoringTest
```

**Comment by pihme** [comment]
Here the list of problems I encountered:

| Problem | Workaround | Fix |
| --- | --- | --- |
| Tests that use FileSnapshotStore fail always, because temporary files are not found | Disable parallel tests for JUnit test stage |  |
| AtomixTest.testScaleUpPersistent fails always, because address is in use | Ignore test | |
| ... |

The strategy is to first use workarounds until we have a successful build.

Then we can look at the number of problems we need to solve. 

Maybe it is better to commit the workarounds, so people can merge again, while we go about fixing the problems. But that remains to be seen.

**Comment by npepinpe** [comment]
Regarding the `FileSnapshotStore`, I've tried it with using regular files as opposed to temp files, and it made no difference iirc.

**Comment by pihme** [comment]
Workaround has been committed to 0.23. Detailed investigation is pending.

**Comment by pihme** [comment]
closed in accordance with Nicolas
