### ISSUE TITLE
Consider system load for choosing when to write a snapshot

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#499]
Think about when is the best time for creating a snapshot (block index & stream processor resource).

Currently, it can happen that a snapshot is created under high load. Maybe it's better to prefer creating it when there are no new events.

**Comment by meyerdan** [comment]
related to #771

**Comment by saig0** [comment]
We implemented that snapshots are taken asynchronously. This may reduce the problem that we take snapshots under high load a bit because the stream processing is not blocked anymore.

Also, it is not so easy to detect that we are under load. I close this issue until we see any problems.
