### ISSUE TITLE
Decide on multiple data points

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4992]
**Description**

Currently we have not a clear decision whether we want to support multiple data points or not.
In our configuration we support a list of data directories, but at the end we just use the first one.

It would be quite useful to avoid IO contention to support multiple data points, which means for each partition an own data dir (e. g. pvc).

If we dont want to support that then we should remove the current possibility, since it is confusing to the users.

**Comment by npepinpe** [comment]
Let's drop the list configuration option and only allow setting a single directory to avoid any confusion, as even if you configure multiple directories we only use the first one. Please make the configuration change backwards compatible.

Regarding supporting multiple disks to reduce I/O contention, this should be a separate issue which should focus on investigating how much performance we could gain in a cloud deployment, as well as if it would reduce costs (e.g. two smaller disks vs 1 big one, less resource usage, etc.).

**Comment by npepinpe** [comment]
Closed as we now support only one.
