### ISSUE TITLE
I can get the position of the last written event

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#501]
Currently raft uses the `getCurrentAppenderPosition()` method to get maximal position to commit on the leader. This method returns a position after the last event written. This leads to the problem that in a single node cluster events get committed before they are written.

Therefore we need a solution to get the position of the last event to not commit the wrong position.

**Comment by Zelldon** [comment]
We migrated to atomix, so I think this is not longer needed. If some speaks against it just reopen the issue
