### ISSUE TITLE
Stream processor skips events on recovery

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#504]
If a stream processor is closed when it hasn't caught up yet to the head of the log, it may happen that the remaining events are not processed after recovery. This happens when the snapshot position refers to a position greater than the positions of the remaining events.

Example:

* Assume Log with events [x, y] at positions [0, 1].
* Stream processor handles x and writes event z at position 2 (=> `#writeEvent` returns 2), updates index based on new state
* Stream processor is closed, snapshot is written for position 2
* Stream processor is reopened
* **Current behavior**: Stream processing resumes at position 2
* **Expected behavior**: Stream processing resumes at position 1

Solution ideas:

* the recovery position should not be based on the snapshot position => it's nice to have, though
* the snapshot position should never refer to any position other than the one the streamprocessor is currently at (=> enforcing this will require rethinking how some stream processors work, e.g. https://github.com/zeebe-io/zeebe/blob/0.1.1/broker-core/src/main/java/io/zeebe/broker/task/processor/TaskExpireLockStreamProcessor.java)

Test case: 

* https://github.com/zeebe-io/zb-logstreams/commit/c4752bd1216c2646957b448f9297463c9a937645

**Comment by Zelldon** [comment]
This is no longer the case. The snapshot is based on the last successful process position, which is written in the state. The snapshot is valid after the last written event is committed.
