### ISSUE TITLE
Getting error while starting operate with elastic xpack security.

### ISSUE THREAD

**Issue by akshaykumarhc** [zeebe-io/zeebe#5049]
Hi team,
I've enabled `xpack.security.enabled: true ` in the elastic which I'm running.
With the same, I've put the credentials and started Zeebe broker it's working fine for the dev testing I needed **operate** .
I need to know a few things: 
1. whether the operate works with elasticsearch `xpack.security` feature.
2. If the answer is yes to the above question. What will the configuration of the same in **zeebe-docker-composer/lib/applicatio.yml**

I've attached logs also by adding 
username: "username" 
password: "password"
on top of this, I'm getting the auth exception.
[operate.log](https://github.com/zeebe-io/zeebe-docker-compose/files/4971229/operate.log)

**Comment by saig0** [comment]
@sdorokhova / @ralfpuchert, please have a look if this is something that can be configured in Operate, or if this is a bug. Thank you :cookie:

**Comment by sdorokhova** [comment]
At the moment Operate does not support authentication for Elasticsearch.
There is an issue for this in Operate backlog:  https://jira.camunda.com/browse/OPE-1006

**Comment by saig0** [comment]
I'm closing this issue because it is only related to Operate. The state can be tracked in the Jira issue: https://jira.camunda.com/browse/OPE-1006
