### ISSUE TITLE
Zeebe worker api support specifying process id(s) to avoid job type conflict

### ISSUE THREAD

**Issue by TangJiong** [zeebe-io/zeebe#5054]
**Is your feature request related to a problem? Please describe.**
We have different workfow processes of which may contain same job type. However, these jobs carry out totally different business logic.
```
my-first-process
    job-init
    job-aaa

my-second-process
    job-init
    job-bbb
```
The Zeebe worker api doesn't support handle a job type of specified process id(s) which may cause disaster when a worker handle a unrelavant job type.

Defining a job type with process id as prefix(eg: `my-first-process.job-init`) may help, but we can't guarantee everyone in the team obey the rules.

**Describe the solution you'd like**
Zeebe client supports api like this
```
client.newWorker()
    .processIds("my-first-process")
    .jobType("jobInit")
    .handler(...)
    .name("")
    .open()
```

**Describe alternatives you've considered**

**Additional context**

**Comment by TangJiong** [comment]
#3439

**Comment by saig0** [comment]
Hi @TangJiong. Is this feature included in the other issue #3439?

If yes then I would like to close this one.

**Comment by TangJiong** [comment]
@saig0 Tannks for reply. 
Yes, similar to #3439 , but I found no progress info or plan there.

**Comment by saig0** [comment]
#3439 is passed to the stakeholders. This would be a bigger change and they need to decide if and when we can work on it (i.e. needs to be prioritized along with other things we're working on because of limited resources)
You can support the issue by giving it a :+1: 

So, I'm closing this issue in favor of #3439.
