### ISSUE TITLE
Record with Non-ASCII characters fails to export to Elasticsearch 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#5059]
**Describe the bug**
A record with a non-ASCII character (e.g. a variable record) is not exported to Elasticsearch. 

**To Reproduce**
* deploy a simple workflow (e.g. a start event + end event) 
* create a new workflow instance with variables `{"x":"Á"}` 

**Expected behavior**
Records with any UFT-8 character can be exported to Elasticsearch.

**Log/Stacktrace**

<details><summary>Zeebe Log Output</summary>
 <p>

```
14:48:53.532 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.broker.exporter.es - Failed to flush 1 item(s) of bulk request [type: mapper_parsing_exception, reason: failed to parse]
14:48:53.532 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] ERROR io.zeebe.broker.exporter.es - Unexpected exception occurred on periodically flushing bulk, will retry later.
```

</p>
</details>

<details><summary>Full Response from Elasticsearch</summary>
 <p>

```
{"took":0,"errors":true,"items":[{"index":{"_index":"test-record_workflow-instance-creation_0.24.2-snapshot_2020-07-27","_type":"_doc","_id":"1-5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Invalid UTF-8 middle byte 0x22\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@22d18169; line: 1, column: 127]"}}}}]}
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.1 (>= 0.24.0)
 - Configuration: Elasticsearch exporter

**Comment by saig0** [comment]
**Hints:**
* the failure seems related to the content-type `application/x-ndjson` which is used by the REST client
* the failure disappears if I change the content-type to `application/json; charset=utf-8`

**Comment by saig0** [comment]
Since the Elasticsearch exporter is not able to flush this kind of record, it can not update the exporter position. As a result, the data can not be compacted and the broker runs out-of-diskspace eventually.

**Comment by menski** [comment]
From what I understand elasticsearch is using `application/x-ndjson` to allow a single bulk request to contain multiple unrelated json docs. What I noticed is that the charset is missing from the content-type, i.e. `application/x-ndjson; charset=utf-8`. We should check if we can achieve this with the elasticsearch client.

**Comment by saig0** [comment]
Currently, no charset can be added to `application/x-ndjson`. See https://github.com/elastic/elasticsearch/issues/28123

**Comment by menski** [comment]
Just checked the request we send with 0.23 where we still used the high-level rest client from elasticsearch. With 0.23 we are able to process this record and the request header from the es client contains `Content-Type: application/json`

```
POST /_bulk?timeout=1m HTTP/1.1\r\n
Content-Length: 39444\r\n
Content-Type: application/json\r\n
Host: localhost:9200\r\n
Connection: Keep-Alive\r\n
User-Agent: Apache-HttpAsyncClient/4.1.4 (Java/11.0.6)\r\n
\r\n
```

**Comment by menski** [comment]
@npepinpe do you remember why you decided to use the content type `application/x-ndjson` when replacing the high level rest client? https://github.com/zeebe-io/zeebe/commit/6740ce3e01a3cfafbf581018a7ee051723318345#diff-97c561c6cb4c87bb23236eaa5775f6d1R55

**Comment by npepinpe** [comment]
The Elastic doc says thats the content type to set for the _bulk endpoint: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-bulk.html

It would be a weird thing for me to invent, but maybe I misunderstood the doc
