### ISSUE TITLE
Refactor NettyMessagingService

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5072]
**Description**

See comments in this issue https://github.com/zeebe-io/zeebe/issues/4952

> We probably should - at the same time, how much gain do we have removing this branch? I looked at the messaging service, and it's again another of these classes that I think needs refactoring - it supports protocol versioning (unused), SSL (unused), multicast (unused), this notion of keepAlive/not (unused), is pretty big with nested types, and is hard to test to some extent since it's very black-box y.

There a several "features" which are not used and make the class to complex. We should try to remove as much as possible.

**Comment by npepinpe** [comment]
We will most likely implement gRPC transport. I'm keeping this open to track that we still want to refactor the transport, but we should close this afterwards. I've created a milestone pre-emptively so we can more easily find it again.
