### ISSUE TITLE
Log statements are merged in stackdriver view

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5079]
**Describe the bug**

I'm not 100% sure whether this is a stackdriver issue or an issue how we use our loggers,
but it seems sometimes the log output is not correctly rendered in stackdriver. It seems two log statements are merged together.

![stackdriver](https://user-images.githubusercontent.com/2758593/88908813-a841de00-d25a-11ea-912e-432d1b41aa1f.png)

**To Reproduce**
Not sure.

**Expected behavior**
Log statements are shown correctly.

**Log/Stacktrace**

```
I 2020-07-30T09:16:47.053339Z Bootstrap Broker-1 partitions succeeded. Started 3 steps in 166 ms. 
I 2020-07-30T09:16:47.053352763Z {"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"function":"startStepByStep","file":"StartProcess.java","line":63},"message":"Bootstrap Broker-1 partitions [3/3]: partition 1 started in 7 ms","serviceContext":{"service":"zeebe-broker","version":"zeebe-chaos-metric-exporter"},"context":{"threadId":1,"broker-id":"Broker-1","threadPriority":5,"loggerName":"io.zeebe.broker.system","threadName":"main"},"timestampSeconds":1596100607,"timestampNanos":52869000,"logger":"io.zeebe.broker.system","thread":"main"}{"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"function":"calculateHealth","file":"CriticalComponentsHealthMonitor.java","line":91},"message":"The components are healthy. The current health status of components: {ZeebePartition-1=HEALTHY}","serviceContext":{"service":"zeebe-broker","version":"zeebe-chaos-metric-exporter"},"context":{"threadId":263,"threadPriority":5,"loggerName":"io.zeebe.broker.system","threadName":"Broker-1-zb-actors-3","actor-name":"Broker-1-ZeebePartition-1"},"timestampSeconds":1596100607,"timestampNanos":52860000,"logger":"io.zeebe.broker.system","thread":"Broker-1-zb-actors-3"}
 
I 2020-07-30T09:16:47.053379451Z 
```

**Environment:**
 - OS: k8
 - Zeebe Version: snapshot
 - Configuration: metrics exporter

**Comment by npepinpe** [comment]
Let's verify via raw logs if this is a problem with our StackdriverLayout or not - hopefully it is and we can fix it ourselves.

**Comment by Zelldon** [comment]
Saw this today on investigating a benchmark.

```
{"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"onVoteResponseError","file":"CandidateRole.java","line":245},"message":"RaftServer{raft-partition-partition-1}{role=CANDIDATE} - io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-1.zeebe-broker-service.8e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe.svc.cluster.local/10.56.0.3:26502","serviceContext":{"service":"zeebe","version":"SNAPSHOT"},"context":{"threadId":42,"threadPriority":5,"loggerName":"io.atomix.raft.roles.CandidateRole","threadName":"raft-server-2-raft-partition-partition-1"},"timestampSeconds":1601479268,"timestampNanos":242184000,"logger":"io.atomix.raft.roles.CandidateRole","thread":"raft-server-2-raft-partition-partition-1"}{"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"function":"onRoleChange","file":"ZeebePartition.java","line":190},"message":"Partition role transitioning from FOLLOWER to CANDIDATE","serviceContext":{"service":"zeebe","version":"SNAPSHOT"},"context":{"threadId":28,"threadPriority":5,"loggerName":"io.zeebe.broker.system","threadName":"Broker-2-zb-actors-0","actor-name":"Broker-2-ZeebePartition-1"},"timestampSeconds":1601479268,"timestampNanos":242071000,"logger":"io.zeebe.broker.system","thread":"Broker-2-zb-actors-0"}
```

https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-09-30T15:20:49.000000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%228e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22&scrollTimestamp=2020-09-30T15:21:08.242967292Z&dateRangeStart=2020-09-30T14:20:49.000Z&dateRangeEnd=2020-09-30T16:20:49.000Z

**Comment by Zelldon** [comment]
And again 

https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-09-30T15:20:49.000000000Z&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%228e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22&scrollTimestamp=2020-09-30T15:31:17.072794000Z&dateRangeStart=2020-09-30T14:20:49.000Z&dateRangeEnd=2020-09-30T16:20:49.000Z&pinnedLogId=gjcsmf9tokx7c84xu&pinnedLogTimestamp=2020-09-30T15:31:08.168705952Z

**Comment by npepinpe** [comment]
imo this isn't a big blocker, as it happens seldom and we can always figure out how to read it. I would not spend time on this, but challenge this if this is a pain for you in your day to day
