### ISSUE TITLE
Improve on atomix bootstrap log statements

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5080]
**Description**

In our benchmarks we lowered the log level to info, which makes it easier to see what is happening in atomix.
For the atomix bootstrap phase there some statements which are just noise, which are not really useful.

On each service there exist a log statement which prints `started` in the end it looks like this:

```
I 2020-07-30T10:17:54.198527Z TCP server listening for connections on 0.0.0.0:26502 
I 2020-07-30T10:17:54.199468Z Started 
I 2020-07-30T10:17:54.223547Z UDP server listening for connections on 0.0.0.0:26502 
I 2020-07-30T10:17:54.224941Z Joined 
I 2020-07-30T10:17:54.228644Z Started 
I 2020-07-30T10:17:54.229384Z Started 
I 2020-07-30T10:17:54.229856Z Started 
I 2020-07-30T10:17:54.231121Z Started 
```

We should improve these log statements, such that it is clear what exactly have been started. Furthermore I think it would be useful to add how long does it take to start the corresponding service.

We could put these statements also to debug level if we think it is not useful in normal run.

**Comment by npepinpe** [comment]
Let's add more context information such as service configuration, startup duration, etc. Please discuss it during kick off

**Comment by npepinpe** [comment]
Downgrading as this isn't something we need to tackle now - however, if anybody is involved in an incident where this would've unblocked them or helped them diagnose something earlier, please let me know.

**Comment by npepinpe** [comment]
Please rewrite them as you go along - we will be refactoring more and more parts of Atomix, so I expect this will mostly get done organically. I wouldn't block anyone on this for now.
