### ISSUE TITLE
RocksDB estimated Live data doesn't shrink

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5081]
**Describe the bug**

During the chaos day I created benchmarks with exporters, without exporters and only with a metric exporter. 
In one of the benchmarks (in the default one) I saw that the RocksDB estimated live data is not longer released.
Furthermore the live data seems to be also quite large in comparison to the other benchmarks, which is unclear to me.

![livedataproblem](https://user-images.githubusercontent.com/2758593/88918768-4ee1ab00-d26a-11ea-9e88-e7790a0f64aa.png)

Normally it looks like this:

![livedatanormal](https://user-images.githubusercontent.com/2758593/88918781-54d78c00-d26a-11ea-889a-99ffc53fafc9.png)

**To Reproduce**
Not sure whether this is reproducible

**Expected behavior**
The data is released.

**Environment:**
 - OS: k8s
 - Zeebe Version: snapshot [e.g. 0.20.0]
 - Configuration: default

**Comment by npepinpe** [comment]
May be closed by #6162 - we should verify with the load tests if this is the case.

**Comment by Zelldon** [comment]
It seems to be still the case.

Normal one column family benchmark:

![estimate](https://user-images.githubusercontent.com/2758593/106556332-9437ab80-651f-11eb-8aca-45b74be4032f.png)

One column family benchmark with freq. snapshots:

![freq-snap-estimate](https://user-images.githubusercontent.com/2758593/106556345-9dc11380-651f-11eb-8a9c-22bf3ae3414a.png)

But tbh I dont think this is an issue. I think it is related to the benchmark setup, we create and complete constantly workflow instances, so overtime it is always the same amount of running workflows instances in the state, might explain this.
