### ISSUE TITLE
Need documentation on various types of records exported by Zeebe

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5082]
**Description**

We need a more detailed documentation on various types of records exported by Zeebe. I am referring to [these records](https://github.com/zeebe-io/zeebe-docker-compose/blob/master/operate/application.yaml#L115).

It would be useful to add these details on the [Exporters](https://docs.zeebe.io/reference/exporters.html) page with a more detailed info like this:
| RecordType | ValueType | Intent | Meaning | Triggered_By | Triggered_When |
|:---:|:---:|:---:|:---:|:---:|:---:|
| EVENT | JOB | TIMED_OUT |   |   |   |

[Related Slack archive](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1594997786329300)

**Comment by npepinpe** [comment]
It was decided that this will not be part of the public API, so it wouldn't appear in the official documentation. However, you can read the accepted proposal for the new engine which should give you some insight into these. At this time it's the best I can offer. Generally, the `protocol` should also be well documented.

See https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md
