### ISSUE TITLE
I can close a Channel gracefully 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#509]
It should be possible to gracefully close a connection. Either side can initiate this.
The connection finishes exchange of any "in-flight" messages and messages in the send buffers on either side and is then closed.

Rough idea for the protocol:

Initiating the close:
- Connection tracks id of last message that was written to the send buffer
- When close() is called, connection is set to state CLOSING. It now stops accepting new messages
- Connection is given to the sender for closing along with the if of the last message published to connection
- When sender writes a message with message id larger or equal than the last id, it knows that it has published all the messages in this connection.
- Sender then writes a CLOSE control frame

Handling Close Control Frame
- When the Reader sees a CLOSE control frame it knows that there will be no more messages coming in from this connection.
- Connection is put into CLOSING state on this side as well.
- Again it is handed to the sender. Sender sends END_OF_STREAM frame after the last message is sent

Handling END_OF_STREAM Control Frame
- Physically close the connection and tranistion to state CLOSED
- The other side will then get -1 bytes in the reader... and close as well.

What happens if connection is closed on both sides concurrently?
- then we se a CLOSE message on a connection which is already in state CLOSING
- convention: this message must be ignored by the client

**Comment by npepinpe** [comment]
I think this is outdated - our transport was replaced by an Atomix based transport, so this doesn't exist anymore.
