### ISSUE TITLE
ElasticsearchExporterAuthenticationIT.shouldExportRecords flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5100]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**
 Failed in https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/2108/

Couldn't find any information in the archived test logs.

**Comment by npepinpe** [comment]
Closing as this hasn't happened in a while, and the CI pipeline is a lot more stable now. Please re-open if you see this occur again.
