### ISSUE TITLE
Rolling update from 0.23 to 0.24 is not possible

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5102]
**Describe the bug**

Rolling update from 0.23 to 0.24 is not possible if the restarted node has to replicate snapshot from brokers on older version. Only rolling update is affected. You can shutdown the whole cluster and restart all brokers with new version.

Reference https://github.com/zeebe-io/zeebe/issues/5035

**Environment:**
 - Zeebe Version: 0.24.1

**Comment by npepinpe** [comment]
As the fix would be complex, and you can still upgrade from 0.23 to 0.24 with some downtime, we will not backport to make rolling upgrade possible, but rather add a test to ensure we're aware of this problem in the future.

**Comment by npepinpe** [comment]
Done
