### ISSUE TITLE
Document blacklisting concept and implications

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5120]
**Description**

As an user I want to read documentation about blacklisting.
The documentation should cover the general concept and following points:

 * what it is
 * why we have this
 * when this can happen
 * what implication has this

As a developer I might want to have more deeper knowledge maybe it make sense to write an ZEP for it.

**Comment by npepinpe** [comment]
@menski I would downgrade this right now as it's mostly for on-prem customers, however it may be useful for the Operate team - is this something that would greatly help the Operate engineers?

**Comment by Zelldon** [comment]
Disagree that this is only for on-prem. We had related incidents in Camunda Cloud especially on Game Days and turned out that most of the people didn't know about the concept, which why we created issues for it. So the target group would include us.

**Comment by npepinpe** [comment]
Hm, i figured internally the Zeebe team was aware of this, and my main concern was with other teams at camunda (e.g. Operate). Do you think this is knowledge thats not shared by everyone in the core team, and/or that its something that's also important for teams other than operate?

**Comment by Zelldon** [comment]
It is important for everyone since it is not obvious that instances are not progressing anymore, especially if you look at operate. But we have open issues to add indications to operate too. I think we shared some knowledge with the Gamedays but cant say that everyones knows about it.

**Comment by npepinpe** [comment]
Do you think a runbook/troubleshooting guide would also cover this? I mention both here as I'm working on setting this up this weekend in the sre team's repo.

**Comment by Zelldon** [comment]
Sounds good👍

**Comment by npepinpe** [comment]
I created https://github.com/camunda-cloud/runbook/issues/54 and https://github.com/camunda-cloud/camunda-cloud-documentation/issues/145
