### ISSUE TITLE
Document known failure cases for users

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5122]
**Description**

Related to #5120 we should have a document which list's known failure cases and describes them. This could help users to overcome failures easier. Furthermore it makes it easier in support or forum to point to such a document, which contains the explanation of a seen behavior and maybe also the reasoning behind it.

**Comment by npepinpe** [comment]
I'm downgrading this as it's currently primarily for on-prem users, and I'd like us to work on the runbook/troubleshooting guide first (which may partially solve this)

**Comment by Zelldon** [comment]
Disagree that this is only for on-prem. This wad an out come from a game day and we thought it would be quite useful for SREs but also us. So the target group would include us.

**Comment by npepinpe** [comment]
Do you think creating the runbook and the troubleshooting guide would not cover these cases? I figured those would cover our internal use cases (i.e. SRE, tech support, etc.), and this issue would then be more for our on prem user docs.

**Comment by npepinpe** [comment]
We have a troubleshooting guide now and run books - it's not yet for user consumption, but I imagine post GA and we focus on on-prem again this will come up. For now I would close as it would be open in the docs repo anyway.
