### ISSUE TITLE
Remove legacy configuration support

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5128]
**Description**

We kept some form of backwards compatibility when migrating from TOML configuration to Spring config for 0.23.x. As we don't support any versions which is configured via TOML or the old environment variables, please remove legacy TOML configuration support for versions post 0.24.x.

**Comment by Zelldon** [comment]
Is this duplicate of https://github.com/zeebe-io/zeebe/issues/4121 ?

**Comment by npepinpe** [comment]
You're right, my bad!
