### ISSUE TITLE
Implement TLS for transport

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#513]
Allow to configure TLS for transport connections client/broker resp. broker/broker. Probably start with TLS 1.2 but also check if there is any support for TLS 1.3 in Java already.

also look into https://netty.io/4.0/api/io/netty/handler/ssl/OpenSslEngine.html
It is usable indenpendently of netty project and supposedly does a much better job in terms of performance then the JDK builtins

the pure java non-blocking SSL way looks painful http://docs.oracle.com/javase/6/docs/technotes/guides/security/jsse/JSSERefGuide.html#SSLENG

**Comment by afirth** [comment]
This page has been updated a bit recently https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-netty-tcnative-on-boringssl with more clear recommendations.
A relatively low cost option might be to replace netty with netty-shaded behind a feature flag. I think this will enable boringssl out of the box. For my use case, getting TLS into the clients is more important than the server, and I think this might be a common case if the clients are hitting a reverse proxy which can terminate client TLS and potentially supports mTLS injection between the proxy and gateway. In the client I think you add an SSL context to each channel as it's created, which is simpler in some languages than others, but generally documented in the grpc libraries. I see @xmclark has taken a shot at it for the rust client already.
