### ISSUE TITLE
low load causes continuously growing of snapshot file count

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5137]
**Describe the bug**
In order to reproduce https://github.com/zeebe-io/zeebe/issues/5135 I have setup a benchmark with quite small load. One workflow per second created and completed. The configure is our default one.

![lowload](https://user-images.githubusercontent.com/2758593/89757913-df2fb380-dae6-11ea-9908-98f6e85bcaf3.png)

If the load is quite small, then the snapshot file count seems to grow continuously. The size of RocksDB seems also to grow. It seems that RocksDB does no compaction.

![lowloadres](https://user-images.githubusercontent.com/2758593/89757914-e060e080-dae6-11ea-80f1-59a65eab7d55.png)
![lowloadrocks1](https://user-images.githubusercontent.com/2758593/89757916-e0f97700-dae6-11ea-9f27-28491795d7a7.png)
![lowloadrocks2](https://user-images.githubusercontent.com/2758593/89757917-e1920d80-dae6-11ea-9030-c2b8266b1d79.png)
![lowloadrocks3](https://user-images.githubusercontent.com/2758593/89757920-e22aa400-dae6-11ea-9449-0835220251f8.png)

If we take a look at the snapshot metrics, then we can see that the snapshot file count is continuously growing.

![lowloadsnapshot](https://user-images.githubusercontent.com/2758593/89757922-e2c33a80-dae6-11ea-8893-9446ff01f92b.png)

**To Reproduce**

Run benchmark with low load.

**Expected behavior**

State and snapshot file count is not increasing.

**Environment:**
 - OS: k8s
 - Zeebe Version: SNAPSHOT
 - Configuration: our default benchmark

**Comment by npepinpe** [comment]
Let's reassess this based on the results of #5135

**Comment by deepthidevaki** [comment]
This can lead to "Too many open files" error as reported by a member in [slack](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1599124205029600)

**Comment by deepthidevaki** [comment]
Might be worth looking into tuning rocksdb parameters to prevent this case when #5279 is done.

**Comment by Zelldon** [comment]
[This caused again an incident ](https://docs.google.com/document/d/1HUCkdg6XLOJdhjySv3ha_tsxV7L8cz34WBTLSyrDTGk/edit#heading=h.e7don26yefrg) and also growing the snapshot to a size of ~ 4 gig, which at the end caused out of disk errors because the current out of disk detection assumes at max snapshot sizes of 2 gig. We should get the rocksdb configuration under control ASAP.

Errors:

 * https://console.cloud.google.com/errors/CL-71-LNwOPNHg?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
 * https://console.cloud.google.com/errors/CKjN-8qmwNKc0wE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
