### ISSUE TITLE
Support `now` for date / time / date and time constructors

### ISSUE THREAD

**Issue by asaf** [zeebe-io/zeebe#5140]
Support `now` for date / time / date and time constructors

In order to calculate a diff period such:
```
= date and time("2019-10-01T12:00:00Z")- date and time(now)
```

this requires adding another node to calculate "now".
This is a suggestion for supporting an empty constructor for date time funcs, set to now (or another method named now()).

Related to #3655

**Comment by saig0** [comment]
Related issue in the FEEL engine: https://github.com/camunda/feel-scala/issues/118
