### ISSUE TITLE
Failure message why snapshot was not take is to generic 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5142]
**Description**

We currently have multiple failure cases in the code why we can't take a snapshot but often we only see
`Failed to obtain a pending snapshot directory for position 1063013`, which is way to generic. It is totally unclear for the reader what excatly has failed, or what was expected etc. We should improve this error message, this would help investigating a lot.

**Comment by npepinpe** [comment]
Yes it's frustrating at the moment, happy to hear any suggestions on how we can make this better. I think the issue we had is that the rejection/failure happens usually far from the call site.
