### ISSUE TITLE
Execute SpotBugs in Maven build

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#515]
* Run [SpotBugs](https://spotbugs.github.io/) with every Maven build
* Configure it such that only patterns are detected which ALWAYS result in unintended behavior (for example: `#equals` invocation on objects of different type)
* If anything is detected, let the build fail
* Do this for all projects

**Comment by Zelldon** [comment]
For transparency:

> Hey Team we decided to slowly introduce spotbugs in multiple phases:
> 1. We will add spotbugs plugin to the maven build and ignore all bug categories, we also hide it behind a profile to only enable it on Jenkins for now

 -> Corresponding PR #2057 

> 2. We will then enable one bug category after the other and fix the bugs present in the corresponding PR
> 3. After a while we should have a configuration which we will then test in our normal routine and validate after some weeks if it works for us

**Comment by menski** [comment]
We added spotbugs and will enable more checks over time
