### ISSUE TITLE
Increase prometheus data retention time

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5153]
**Description**
On investigating https://github.com/zeebe-io/zeebe/issues/5127 I wanted to check the metrics again from 31-07-2020 but it seems Prometheus only keeps the data for 10 days.

![metrics](https://user-images.githubusercontent.com/2758593/89875106-1b354800-dbbd-11ea-9e1f-37d49ccb586e.png)

It would be nice to increase the retention time to something like 30 days.

**Comment by npepinpe** [comment]
Won't do as we will switch to a managed cluster provided by the SRE team.
