### ISSUE TITLE
Unify retry behavior when using Dispatcher#claim

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#516]
The method `Dispatcher#claim` is used in various parts of the code to allocate memory in a dispatcher. In the current implementation, the method may return status codes that indicate that claiming was not successful, in particular that the current partition does not have enough space.

Code that uses this method typically retries the claim operation in that case. In our current implementation, we do that inconsistently, e.g. we do not react to all status codes (-1 and -2). We should find a solution to solve this correctly and in one place.

Proposal for response writer: 
* implement the writer as state machine
* tryWrite() goes to a state and try to write it 3 times
* write failure if was not successful

**Comment by npepinpe** [comment]
Is this still required?

**Comment by npepinpe** [comment]
I would rather investigate replacing the dispatcher than do additional work on it, barring fixes.
