### ISSUE TITLE
I can use a tool to inspect a log in a human-readable format

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#517]
- useful for debugging
- similar to H2 console for Camunda BPM 7 development
- Reads a log from a file on disk
- log entries can be scrolled on the console

**Comment by npepinpe** [comment]
We have some debug exporters, so to some extent this is partially done - but it's not quite in my opinion, as I would also like a tool to inspect a log directly. I think it's a worthwhile goal.

**Comment by Zelldon** [comment]
Can be done with https://github.com/Zelldon/zdb/releases/tag/0.2.0

**Comment by npepinpe** [comment]
Yes, I was about to go and comment that :sweat_smile: 

For now I would propose to close this, and if this becomes part of our day to day tools (which I expect), we can discuss officially adopting zdb (assuming the author accepts :wink:)
