### ISSUE TITLE
Creation of 21 partitions raises outOfMemory exception in the container with 4GB of RAM

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zeebe#518]
In the attachment, there is broker log dump.

[error.txt](https://github.com/zeebe-io/zeebe/files/1394482/error.txt)

**Comment by menski** [comment]
Environment: MacOS with Docker VM configured to use 4GB of Memory

**Comment by menski** [comment]
related to https://github.com/zeebe-io/zeebe/issues/390

**Comment by menski** [comment]
with Zeebe 0.9.0 I'm able to create 128 partitions with a 4GB container without any problems
