### ISSUE TITLE
Investigate high snapshot frequency

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5185]
**Description**

In order to implement https://github.com/zeebe-io/zeebe/issues/5184 we need to investigate before whether it is problematic to take snapshot in a high frequence.

What we know is that snapshot replication might be problematic in that case, but does it also affect RocksDB? Can handle RocksDB high checkpoint rate?

blocks #5184

**Comment by npepinpe** [comment]
May be closed by #6162 - to verify with the load tests.

Latest results seem to indicate the RocksDB memory is under control, however our heap memory is growing consistently.

**Comment by Zelldon** [comment]
We run a benchmark with high frequent snapshots (snapshot interval 1 min) and saw no issues.
Snapshots doesn't defragment anymore size and number of files is stable overtime.

![snap](https://user-images.githubusercontent.com/2758593/106556069-11aeec00-651f-11eb-95a0-d1c98208b4db.png)

Resources look good as well (java heap growing is related to https://github.com/zeebe-io/zeebe/issues/6237)

![res](https://user-images.githubusercontent.com/2758593/106556022-fa6ffe80-651e-11eb-87b5-57ba09211e42.png)
![disk](https://user-images.githubusercontent.com/2758593/106556021-f9d76800-651e-11eb-924b-d62bd1c2abd3.png)

Throughput looks also good

![th](https://user-images.githubusercontent.com/2758593/106556116-29867000-651f-11eb-814c-518ba02e4540.png)
