### ISSUE TITLE
Schedule asynchronous commands

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#519]
Use Case:
* a stream processor has a command which runs a check at a fixed rate
* the command run in the context of the stream processor (i.e. using the processor command queue)
* avoid another invocation of the command until it's finished, even if it takes longer than the given rate
* currently, the command queue may reach their limit (e.g. when debugging the command) 

AT:
* I can schedule an asynchronous command
* an asynchronous command is scheduled again when it's finished

**Comment by menski** [comment]
@saig0 is this possible with the new actor scheduler framework? If so please close this issue. Thanks

**Comment by saig0** [comment]
Yes, this should work with the actor framework now.
