### ISSUE TITLE
Change default values for diskUsage watermarks

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5199]
**Description**

Current defaults for diskUsageCommandWatermark and diskUsageReplicationWatermark are 0.8 and 0.9. That means, we need to have atleast 20% unused disk space. With these defaults, I am not able to run a broker on a machine that has 50GB free :smile: 
I would suggest that we increase the defaults. Otherwise some one trying out Zeebe for first time might fail to run it. This would mean that defaults may be not good for production and one should tune them for production deployment.

**Comment by Zelldon** [comment]
@deepthidevaki why it is not possible to run on 50 GB? What is the issue you're seeing? This means we would keep 10 gig free right?

**Comment by deepthidevaki** [comment]
50 out of ~500GB is free. So it requires atleast 100GB to be free.

**Comment by deepthidevaki** [comment]
@sdorokhova also had similar problems. She had to change these values to make it run.

**Comment by npepinpe** [comment]
That's a good point - 80% of 500 is 400, so with 100Gb left (which is more than enough locally) you can't do anything :sweat_smile: 

The low watermark is to let us make internal progress and replicate snapshot, so disk space will be used for log and snapshot. Once you hit the high watermark, it's purely for snapshot, correct? So the amount of space you need is to replicate/take snapshot, right?

**Comment by Zelldon** [comment]
Actually the argument was when we implemented that we expect high load with big disk's which might mean bigger states :D

**Comment by npepinpe** [comment]
Let's switch the defaults to 0.97 and 0.99 for a simpler getting started experience; ensure we log a warning if on startup you break either threshold, and let's add documentation on how to configure these settings in production, all before the next minor release :slightly_smiling_face:

**Comment by menski** [comment]
I'm not able to run Zeebe dev build anymore as I normally have less then 15% disk space free :see_no_evil:

**Comment by npepinpe** [comment]
Feel free to reprioritize ;)

**Comment by menski** [comment]
I will just implement it :shipit:
