### ISSUE TITLE
Do not log RESOURCE_EXHAUSTED exceptions in job worker (GO)

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5229]
**Description**

Related to https://github.com/zeebe-io/zeebe/issues/5187 we have seen recently an huge increase of log statements, which are related to `RESOURCE_EXHAUSTED` errors. The job worker in the java or go client, log errors when they happen during activating. These kind of "errors" are not really errors and are handled gracefully internally by the job worker, via retry so it is not necessary to log them. The user can't do much in this case. The log statements spread more confusion and seem to be not really helpful.

**Comment by Zelldon** [comment]
I would like to tackle this, but tbh I have not really a clue how. I'm feeling a bit uncomfortable to change the go code :see_no_evil: maybe @MiguelPires you can help me here. 

I assume I need to change this line https://github.com/zeebe-io/zeebe/blob/develop/clients/go/pkg/worker/jobPoller.go#L90, but how I check what kind of error this is etc. I would like to achieve a similar thing as I did with this PR for java https://github.com/zeebe-io/zeebe/pull/5232

**Comment by MiguelPires** [comment]
@zell I can take this off your plate, if you want. I didn't reproduce/test this but you can check the error code with `status.Code(err) != Codes.ResourceExhausted`

**Comment by Zelldon** [comment]
Would it be necessary to cast it ? Does this even exist in go?

> @Zell I can take this off your plate, if you want.

This would be awesome. I would be happy to review it so I can learn something new :)

**Comment by MiguelPires** [comment]
The call to `status.Code` does that basically. It checks if the error matches a certain interface (in Go it's called type assertion) and, if it does, then the error is cast to that interface which allows it to extract the error code. Sounds good, I'll open a PR :smiley:
