### ISSUE TITLE
Detect wrongly mapped Gateway error responses earlier

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5237]
**Description**

We had an issue (https://github.com/zeebe-io/zeebe/issues/5187) where we haven't mapped a returned ErrorResponse correctly to a StatusRuntimeException, which caused in the client weird error messages and per default the error is then mapped to `UNKNOWN`. 

This PR https://github.com/zeebe-io/zeebe/pull/5228 fixed that, but it doesn't prevent it from happening again.
We currently have two problems in the Gateway:

 1. We aren't testing error handling or sending error responses properly
 2. We can send errors and in general response everywhere in the code. This means it is hard to make sure that all errors are mapped correctly, you can just call `streamObserver.onError(Throwable)` and it will be returned to the client.

## Proposal:

I have two possible solutions for this:

### First solution

In order to overcome this, we could wrap the `StreamObserver` and `EndpointManager`, such they intercept every call and verify that the `Throwable`, which is given into the `onError` is actually a `StatusRuntimeException`. If not we could throw a new exception that indicates this problem. This exception we then should see at least in our benchmarks, ideally of course in our tests as well. You can find at this branch https://github.com/zeebe-io/zeebe/tree/zell-gateway-wrapper a working example.

### Second solution

Another approach would be to refactor the gateway in a way that the response handling is at one place. We could achieve that for example with futures. We give the request handlers instead of the stream observer an future which can be completed with the response or an exception. We add a completion handler to the future which then sends the correctly mapped exception or the response.

In all cases we need to improve our test coverage in the gateway.

**Comment by npepinpe** [comment]
I'm bumping the priority as there is a clear concept, and it will simplify other changes that arose in another PR.
