### ISSUE TITLE
Workflow key mismatch in Zeebe Java client

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5277]
**Describe the bug**
We are seeing a mismatch between the key which is generated by the broker when a workflow is created, and the key which is returned to the Zeebe client. It is also happening in case of workflow instance creation. The key returned by the client is generally off by one.
```
Deployment created with key: 2251799813687106
```
<img width="1262" alt="Screenshot 2020-09-02 at 11 44 04 AM" src="https://user-images.githubusercontent.com/10865861/91938628-f80c3d00-ed11-11ea-8cef-e760f56d00fc.png">
<img width="888" alt="Screenshot 2020-09-02 at 11 45 56 AM" src="https://user-images.githubusercontent.com/10865861/91938632-fb072d80-ed11-11ea-9232-88614e0af6a1.png">

**To Reproduce**
Start a Zeebe broker and deploy a workflow using Java client:
```
try (final ZeebeClient client = clientBuilder.build()) {
  final DeploymentEvent deploymentEvent =
      client
          .newDeployCommand()
          .addResourceFromClasspath("order-process.bpmn")
          .send()
          .join();
  System.out.println("Deployment created with key: " + deploymentEvent.getKey());
}
```
It does not happen every time, but we have seen it happen quite often.

**Expected behavior**
The deployment key or workflow instance key returned by the Zeebe client should match the actual key generated by broker.

**Environment:**
- Zeebe Version: 0.24.2 (we have seen it in previous versions as well)

**Comment by menski** [comment]
The key returned by the deployment command is the deployment key. As a deployment can contain multiple resources, it can also contain multiple workflows. If you are interested in the workflow key, you can iterate over the list of workflows inside the returned deployment, or just access the first one in case there was only one workflow deployed.

```
deploymentEvent.getWorkflows().get(0).getWorkflowKey()
```

**Comment by strawhat5** [comment]
Ah my bad. 😅  Thanks for clarifying. :)
