### ISSUE TITLE
Expose spring endpoints for dynamically configuring log levels

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5281]
**Description**

Production clusters are not usually running with debug log level. When something fails in a production cluster, in some cases it will be useful to temporarily increase the log level to inspect the running system. Especially atomix debug logs are sometimes very useful, but generates a huge amount of logs if permanently enabled. Spring already have endpoints for it. We should enable them. https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers-setting-level

**Comment by menski** [comment]
Please create a follow up issue to remove ZbLogger indirection to allow dynamic log levels
