### ISSUE TITLE
Failed to take snapshot. Expected to find an indexed entry for given snapshot position, but found no matching indexed entry which contains this position

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5294]
**Describe the bug**

After a specific time, no partitions were able to take a snapshot. Interesting things that happened at this time 
* 2 nodes were restarted
* Elastic was restarted and remained unavailable after this time. 

However not exporting should not affect finding the index for a snapshot position. 

```
I 2020-09-03T08:50:42.909800Z Finished taking snapshot, need to wait until last written event position 92177208 is committed, current commit position is 92177208. After that snapshot can be marked as valid. 
I 2020-09-03T08:50:43.025026Z Current commit position 92177208 is greater then 92177208, snapshot 72694299-5-1599123042546-92177202-92176016 is valid and has been persisted. 
I 2020-09-03T08:50:46.586284Z Finished taking snapshot, need to wait until last written event position 92834088 is committed, current commit position is 92834088. After that snapshot can be marked as valid. 
I 2020-09-03T08:50:46.678231Z Current commit position 92834088 is greater then 92834088, snapshot 73295199-6-1599123046239-92834086-92832638 is valid and has been persisted. 
W 2020-09-03T08:57:09.727479Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 92972134, but found no matching indexed entry which contains this position. 
W 2020-09-03T08:57:50.236950Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 92408747, but found no matching indexed entry which contains this position. 
W 2020-09-03T08:59:04.398724Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 96063780, but found no matching indexed entry which contains this position. 
W 2020-09-03T09:02:09.735510Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 93291699, but found no matching indexed entry which contains this position. 
W 2020-09-03T09:02:50.265595Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 92740810, but found no matching indexed entry which contains this position. 
W 2020-09-03T09:04:04.414313Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 96401054, but found no matching indexed entry which contains this position. 
W 2020-09-03T09:07:09.736556Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 93620744, but found no matching indexed entry which contains this position. 
```

Prior to first 'Failed to take snapshot', two node were restarted including elastic. But Elastic did not start and was not available after that. Following is logs from one broker. It cannot export because elastic is not available.

```
I 2020-09-03T08:56:10.274085Z Exporter opened 
I 2020-09-03T08:56:10.844931Z Processor starts reprocessing, until last source event position 92927359 
E 2020-09-03T08:56:11.278363Z Error on exporting record with key 4503599666512179 
I 2020-09-03T08:56:29.944010Z Processor finished reprocessing at event position 92927359 
...
...
W 2020-09-03T08:57:09.727479Z Failed to take snapshot. Expected to find an indexed entry for given snapshot position 92972134, but found no matching indexed entry which contains this position. 
W 2020-09-03T08:57:10.103332Z RaftServer{raft-partition-partition-3} - AppendRequest{term=5, leader=2, prevLogIndex=75643079, prevLogTerm=5, entries=0, commitIndex=75667861} to 0 failed: RaftError{type=UNAVAILABLE, message=null} 
```

[Link to logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-09-04T08%3A17%3A02.619000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22dd-medium-load-zeebe-2%22%0Aresource.labels.namespace_name%3D%22dd-medium-load%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Atimestamp%3D%222020-09-03T08%3A57%3A09.727479000Z%22%0AinsertId%3D%22abfy14t63d7mg2n2l%22&scrollTimestamp=2020-09-03T08%3A57%3A11.409581000Z)

**Environment:**
 - Zeebe Version: 0.25.SNAPSHOT

**Comment by Zelldon** [comment]
Good opportunity to test zdb :clap: :grin:

**Comment by falko** [comment]
My current customer is also experiencing this during load testing.

**Comment by falko** [comment]
Will this be fixed for 0.25.0?

**Comment by deepthidevaki** [comment]
@falko We were never able to reproduce this bug. So could not root cause it yet. Was it easy for them to reproduce it? Did it get resolved when the broker is restarted?

**Comment by Zelldon** [comment]
Saw the same today on a testbench cluster. I will take a further look. 

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-10-01T08:04:04.361000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%228e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22&scrollTimestamp=2020-10-01T07:39:47.880523000Z&pinnedLogId=jijo0zk05ltl94nky&pinnedLogTimestamp=2020-10-01T07:04:47.759428Z

**Comment by Zelldon** [comment]
Interesting is the following:

```
2020-09-30 17:24:13.052 CEST
Broker-2-SnapshotDirector-1
Based on lowest exporter position '330' and last processed position '330', determined '330' as snapshot position.
```

[Console log](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-09-30T15:20:49.000000000Z&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%228e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0AjsonPayload.message:%22snapshot%22&scrollTimestamp=2020-09-30T15:24:13.265544000Z&dateRangeStart=2020-09-30T14:20:49.000Z&dateRangeEnd=2020-09-30T16:20:49.000Z&pinnedLogId=c9dtye11y1vqmruul&pinnedLogTimestamp=2020-09-30T15:24:13.052959Z)


After several restarts of the nodes we see the following:

```
2020-09-30 17:32:09.916 CEST
Broker-1-SnapshotDirector-1
Based on lowest exporter position '-1' and last processed position '330', determined '-1' as snapshot position.
```

[Console log](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-09-30T15:20:49.000000000Z&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&scrollTimestamp=2020-09-30T16:17:10.093299000Z&dateRangeStart=2020-09-30T14:20:49.000Z&dateRangeEnd=2020-09-30T16:20:49.000Z&pinnedLogId=gjcsmf9tokx7c88xa&pinnedLogTimestamp=2020-09-30T15:32:09.916689Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%228e80f2b1-eee8-4bf2-a8eb-33af3cf65a5a-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22)

**Comment by Zelldon** [comment]
I checked it with ZDB and found the following:

**Runtime:**
```
root@zeebe-0:/usr/local/zeebe/data# java -jar zdb.jar status -p=raft-partition/partitions/1/runtime/
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

Last processed position: 330
Lowest exported position: -1
Blacklisted instances: No
Incidents: No
```

**Snapshot:**
```
root@zeebe-0:/usr/local/zeebe/data# java -jar zdb.jar status -p=raft-partition/partitions/1/snapshots/199-1-1601479453054-330-330
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

Last processed position: 330
Lowest exported position: 330
Blacklisted instances: No
Incidents: No
```

**Log status:**
```
root@zeebe-0:/usr/local/zeebe/data# java -jar zdb.jar log status -p=raft-partition/partitions/1
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/usr/local/zeebe/data/zdb.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Scan log...
Log scanned in 2518 ms

Scanned entries: 1
Maximum entry size: 11
Minimum entry size: 11
Avg entry size: 11.0
LowestRecordPosition: 9223372036854775807
HighestRecordPosition: -9223372036854775808
HighestIndex: 1
LowestIndex: 1
InitialEntries: [InitializeEntry{term=0, timestamp=1970-01-01 12:00:00,001}]
```

\cc @npepinpe @deepthidevaki

**Comment by deepthidevaki** [comment]
Since exportedPosition is -, it is trying to find the entry at position -1 and it fails. Is that reason?

**Comment by Zelldon** [comment]
Actually it is weird. The last exported position is in the snapshot `330` and in the runtime `-1`. It seems to search for 330, but the log is totally compacted and it only consist of an initial entry.

**Comment by Zelldon** [comment]
Next thing is how can it be that the log is only one entry? The segment size is 512 MB. I have written 330 records, which means each need to have ~ 1.5 mb to fill a complete segment such that the next initial entry ends in the next segment. I see the chances for that really really small. I have the feeling we compacted wrong or we truncated data.

**Comment by Zelldon** [comment]
I enhanced the status output to see all exporter positions.

**SNAPSHOT**
```
root@zeebe-0:/usr/local/zeebe/data# java -jar zdb.jar status -p=raft-partition/partitions/1/snapshots/199-1-1601479453054-330-330/
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

Last processed position: 330
elasticsearch: position 330
MetricsExporter: position 330
Lowest exported position: 330
Blacklisted instances: No
Incidents: No
```

**Runtime**
```
root@zeebe-0:/usr/local/zeebe/data# java -jar zdb.jar status -p=raft-partition/partitions/1/runtime/
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

Last processed position: 330
elasticsearch: position -1
MetricsExporter: position 330
Lowest exported position: -1
Blacklisted instances: No
Incidents: No
```

**Comment by Zelldon** [comment]
I'm able to reproduce this with the following test:

```
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.0. You may not use this file
 * except in compliance with the Zeebe Community License 1.0.
 */
package io.zeebe.broker.it.startup;

import static org.assertj.core.api.Assertions.assertThat;

import io.zeebe.broker.Broker;
import io.zeebe.broker.PartitionListener;
import io.zeebe.broker.it.clustering.ClusteringRule;
import io.zeebe.broker.it.util.GrpcClientRule;
import io.zeebe.broker.system.configuration.ExporterCfg;
import io.zeebe.broker.test.EmbeddedBrokerRule;
import io.zeebe.client.api.ZeebeFuture;
import io.zeebe.client.api.response.PublishMessageResponse;
import io.zeebe.logstreams.log.LogStream;
import io.zeebe.snapshots.broker.impl.FileBasedSnapshotMetadata;
import io.zeebe.test.util.record.RecordingExporter;
import io.zeebe.util.sched.future.ActorFuture;
import io.zeebe.util.sched.future.CompletableActorFuture;
import java.io.File;
import java.time.Duration;
import java.util.Optional;
import org.awaitility.Awaitility;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.RuleChain;

public class BrokerRestartTest {
  private final EmbeddedBrokerRule brokerRule = new EmbeddedBrokerRule(brokerCfg ->{
    final var exporterCfg = new ExporterCfg();
    exporterCfg.setClassName("io.zeebe.exporter.ElasticsearchExporter");
    brokerCfg.getExporters().put("elasticsearch", exporterCfg);
  });
  private final GrpcClientRule clientRule = new GrpcClientRule(brokerRule);

  @Rule public final RuleChain ruleChain = RuleChain.outerRule(brokerRule).around(clientRule);

  @Test
  public void test() {
    // given
    final var listener = new Listener();
    brokerRule.getBroker().addPartitionListener(listener);

    // when
    for (int i = 0; i < 100; i++) {
      generateLoad();
    }

    final var count = RecordingExporter.messageRecords().limit(200).count();
    assertThat(count).isEqualTo(200);

    brokerRule.getClock().addTime(Duration.ofMinutes(15));
    waitForNewSnapshotAtBroker(brokerRule.getBroker(), null);

    brokerRule.restartBroker(listener);

    brokerRule.getClock().addTime(Duration.ofMinutes(15));
    waitForNewSnapshotAtBroker(brokerRule.getBroker(), null);
  }


  FileBasedSnapshotMetadata waitForNewSnapshotAtBroker(
      final Broker broker, final FileBasedSnapshotMetadata previousSnapshot) {
    final File snapshotsDir = ClusteringRule.getSnapshotsDirectory(broker);

    return Awaitility.await()
        .pollInterval(Duration.ofMillis(100))
        .atMost(Duration.ofMinutes(1))
        .until(
            () -> findSnapshot(snapshotsDir),
            latestSnapshot ->
                latestSnapshot.isPresent()
                    && (previousSnapshot == null
                    || latestSnapshot.get().compareTo(previousSnapshot) > 0))
        .orElseThrow(
            () ->
                new IllegalStateException(
                    "Snapshot expected, but reference to snapshot is corrupted"));
  }

  private Optional<FileBasedSnapshotMetadata> findSnapshot(final File snapshotsDir) {
    final var files = snapshotsDir.listFiles();
    if (files == null || files.length != 1) {
      return Optional.empty();
    }

    final var snapshotPath = files[0].toPath();
    return FileBasedSnapshotMetadata.ofPath(snapshotPath);
  }

  private void generateLoad() {
    publishMessage(1).join();
    publishMessage(2).join();
  }

  private ZeebeFuture<PublishMessageResponse> publishMessage(final int key) {
    return clientRule
        .getClient()
        .newPublishMessageCommand()
        .messageName("name")
        .correlationKey(String.valueOf(key))
        .timeToLive(Duration.ofMinutes(2))
        .send();
  }

}
```

Output:

[output.txt](https://github.com/zeebe-io/zeebe/files/5316208/output.txt)

**Comment by Zelldon** [comment]
Ok found the issue.

If we have exported all records, do a snapshot and restart the broker then there is nothing the export. The `ElasticSearchExporter` does an periodically flush, which also updates the lastExportedPosition, see [here](https://github.com/zeebe-io/zeebe/blob/develop/exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchExporter.java#L126). If the elasticsearch exporter hasn't seen any records after restart it will update the position to `-1`, since this is the default value.

In the ExporterDirector we don't validate the position, whether it is smaller then the previous value which means we just update the position, see [here](https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java#L473).
