### ISSUE TITLE
Performance drop on 0.24.3 release candidate 

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5300]
**Description**

Average throughput is smaller on a benchmark running 0.24.3-rc1 compared to snapshot. Processing latency is also higher on average.

![image](https://user-images.githubusercontent.com/1997478/92251573-53cef580-eecd-11ea-99ee-c726941e14cf.png)

![image](https://user-images.githubusercontent.com/1997478/92251524-431e7f80-eecd-11ea-86a8-415fe6bacad8.png)

![image](https://user-images.githubusercontent.com/1997478/92251614-60ebe480-eecd-11ea-9795-98691e4b05f8.png)

**Comment by deepthidevaki** [comment]
Reverting #5244 resulted in much higher throughput, comparable to benchmarks running on snapshot.

![image](https://user-images.githubusercontent.com/1997478/92370755-020bb280-f0fb-11ea-9e98-f3710adf6289.png)
![image](https://user-images.githubusercontent.com/1997478/92370865-29627f80-f0fb-11ea-8be4-7023e0926195.png)
![image](https://user-images.githubusercontent.com/1997478/92370973-51ea7980-f0fb-11ea-912f-a33692f76f39.png)

**Comment by deepthidevaki** [comment]
@npepinpe FYI  The PR for fixing compatibility between 0.24 and 0.25 had performance impact. So we temporarily reverted it for the patch release. So 0.24.3 won't be compatible with 0.25. We should revisit #5244 before 0.25.0 release.

**Comment by MiguelPires** [comment]
I'm trying to reproduce this performance drop but I'm not seeing it after a few hours of running the benchmarks. Did it take a while for the degradation to become apparent or was it always slow? @deepthidevaki

**Comment by deepthidevaki** [comment]
@MiguelPires It was always slow. I restarted the cluster a couple of times, but the results were same.
