### ISSUE TITLE
Use dynamic buffers in journal reader and writer

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5306]
**Is your feature request related to a problem? Please describe.**

To mitigate the issue https://github.com/zeebe-io/zeebe/issues/4249 we could use a dynamic buffer in the journal readers and writers, which are resized dynamically if they read are larger entry. This would be a backward compatible change and a quick solution until we either replace the log or refactor it.

**Describe alternatives you've considered**

Replace the log, or use mmap journal.

**Additional context**

As addition we could add logic to shrink the buffer again, like the last 1k entries avg or max size. But this would be a nice to have but not necessary for the first step.

**Comment by npepinpe** [comment]
Closing in favour of focusing on the mmap journal.
