### ISSUE TITLE
Complete BPMN chapter in docs

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#531]

**Comment by ThorbenLindhauer** [comment]
Result of today: I wrote the BPMN primer section and slightly polished the sections on events, gateways, tasks. 

Open TODO: The dataflow section can be consolidated a bit and maybe we should have a dedicated section on *process payload* (if there is more to tell than what is covered by the *Basics* section). *Gateways* and *Dataflow* rely on that the user has understood the general idea of process payload being a JSON document. Maybe *dataflow* should also be moved into second position after *BPMN primer* and then give a proper introduction on the process payload topic.

**Comment by meyerdan** [comment]
Hi @ThorbenLindhauer

I took over this review from Phil who will be out of office for the next 2 weeks.

The chapter is really great, do not see any way to improve this easily except for one thing that I am not sure about.

In the [data flow section](https://stage.docs.zeebe.io/bpmn-workflows/data-flow.html) we make the distinction between "Tightly coupled task workers" vs. "Loosely coupled task workers". While the complete content makes sense, I worry that "Tightly coupled" has negative connotations for a developer and a developer who only reads it in a superficial way is going to go "Hey I do not want tightly coupled stuff", let's do the other option. Maybe we can select a term that is more neutral. Do you see what I mean? We can just talk about it F2F if you like

**Comment by ThorbenLindhauer** [comment]
Thanks for the feedback. I understand the concern regarding "tight coupling" and raised a follow-up issue: https://github.com/zeebe-io/zeebe/issues/840. Will have to think about better terms.
