### ISSUE TITLE
In the README link to the Configuration is broken

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5311]
**Description**

When I click on the Configuration link: https://github.com/zeebe-io/zeebe/blob/ca48b92facc2ecc9a5631e1d91439ed6ee2a9d1b/README.md#L42
I'm going to the: https://docs.zeebe.io/operations/the-zeebecfgyaml-file.html which response 404.

**Comment by saig0** [comment]
Good catch. Thank you for reporting :+1:

**Comment by aivinog1** [comment]
@saig0 Hello, I think I can fix it, what do you think?

**Comment by saig0** [comment]
Go for it :+1:

You're very active in contributing! Awesome :tada:
