### ISSUE TITLE
Complete Basics Section in docs

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#532]

**Comment by ThorbenLindhauer** [comment]
Purpose of the `Basics` section:

* Explains the core concepts Zeebe, e.g.
  * Architecture
  * What is a workflow? What is a task?
  * How to implement a workflow?
  * Stream processing
* Can be read in one sitting along the order of subsections
* When I have understood this section and am working with Zeebe, I should not need to go back there (i.e. it is not a reference)
