### ISSUE TITLE
The legacy TOML configuration module isn't removed in the 0.25.0-alpha2

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5328]
**Description**

Based on this comment: https://github.com/zeebe-io/zeebe/pull/5312#issuecomment-690134719. Release (https://github.com/zeebe-io/zeebe/releases/tag/0.25.0-alpha2) issued out earlier that the commit that fixed issue pushed into the develop branch.

**Comment by pihme** [comment]
Yep, you're right. These alpha releases are still confusing to me. Fixed it.
