### ISSUE TITLE
Partition is not replicated to new broker when there is no leader

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#534]
When there is no leader for a partition and a new broker joins the cluster, it will will not be invited to that raft group. This breaks the expected behavior that all partitions are supposed to be replicated on all nodes. Follow-up of https://github.com/zeebe-io/zeebe/issues/378

**Comment by menski** [comment]
I think this issue to be not urgent and will be obsolet when we implement the replication factor for partitions (#407). The replication factor will require some logic which ensures that enough followers are acquired before a partition is available and it will remove the assumption that a partitions is replicated in the whole cluster.

**Comment by meyerdan** [comment]
Let's close it
