### ISSUE TITLE
Unable to apply rocksdb column family options using environment variables

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5364]
**Is your feature request related to a problem? Please describe.**

#5336 exposes rocksdb's column family options, but in order to keep its implementation flexible it does not specify exactly which properties can be set. Given that RocksDB expects key names with underscores; AND Spring replaces underscores in environment variable names with dots makes it impossible to define these options using environment variables, currently.

For example, ```export ZEEBE_BROKER_DATA_ROCKSDB_COLUMNFAMILYOPTIONS_WRITE_BUFFER_SIZE=8388608``` results in a config (note the dots in the key of the `write.buffer.size` property):
```
"rocksdb" : {
  "columnFamilyOptions" : {
    "write.buffer.size" : "8388608"
  }
}
```

**Describe the solution you'd like**
I propose to change ` io.zeebe.broker.system.configuration.RocksdbCfg#getColumnFamilyOptions()` with an implementation that replaces dots in the key names with underscores.

**Describe alternatives you've considered**
We currently recommend not to use env variables to set these properties, so we might as well fully disable it. Or we could implement it less flexible, specifying which options are available in `RocksdbCfg`.

**Comment by npepinpe** [comment]
@korthout Let's time box it and keep it simple - we can talk about it before you start
