### ISSUE TITLE
On parallel topic creation first response lost or not send

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#537]
#### Scenario
- execute at least two create topic requests async to a single broker
- wait for both requests to return with `CREATED` status

#### Problem
- only the second request receives a response
- the first request never receives a response and times out
- although the topics are correctly created on the broker

#### Note
I discovered this while developing my rust client. The test suite is executed with multiple threads and often failed to create a topic. By debugging with wireshark I saw that the test suite send two create topic request and a topology request but only a single create topic response and the topology was returned by the broker. I was able to reproduce this behavior in a [java test case](https://github.com/zeebe-io/zeebe/blob/367c71405701ec26807c9baf486701803bc017cf/qa/integration-tests/src/test/java/io/zeebe/broker/it/topic/CreateTopicTest.java#L71).

**Comment by ThorbenLindhauer** [comment]
Please give https://github.com/zeebe-io/zb-raft/commit/a772a02a02331fbdf2d0d87fe2fc951fb7b02c64 another look.

**Comment by menski** [comment]
@ThorbenLindhauer I moved the fix for the test race condition to the BeforeClass method to initially wait for a  stable known state and then freeze the raft nodes itself (https://github.com/zeebe-io/zb-raft/commit/54f79a434136918f2c0b76d9b1c4272e77e3108d). This should have the same effect as your fix but maybe you can still give it a try on your machine.

**Comment by ThorbenLindhauer** [comment]
Looks good. Thanks for looking into this.
