### ISSUE TITLE
Version increment policy for feel-scala

### ISSUE THREAD

**Issue by bulldetektor** [zeebe-io/zeebe#5374]
Hi,

I see that the current version of camunda/feel-scala bundled with Zeebe is at 1.11.2, ref: 
https://github.com/zeebe-io/zeebe/blob/4a93e6edb0853850a36f36467fa56e16b9329e67/parent/pom.xml#L86

The latest release of feel-scala is however at 1.12.1. In 1.12.0 they added "new temporal functions: now() + today()" which I'd like to use in a timer.

So my question is; Do you have any policy on how often you will update the feel-scala version in Zeebe?

**Comment by saig0** [comment]
Hi @bulldetektor :wave: 

Usually, we update the dependencies of our development version when a new version is available. Our bot is responsible for this. 

Here is the PR for the FEEL engine: https://github.com/zeebe-io/zeebe/pull/5355

I'll merge the PR soon. I need to change a few small things to integrate :)

**Comment by bulldetektor** [comment]
Thanks, @saig0 !
