### ISSUE TITLE
All workflow instance related record values should implement WorkflowInstanceRelated

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5378]
**Description**

Some record values (e.g. `WorkflowInstanceCreationRecordValue` implement `WorkflowInstanceRelated`, which helps us group records which are directly related to a workflow instance. However, some record values (e.g. `VariableRecordValue`, `TimerRecordValue`), which do have a workflow instance key property, do not implement the interface.

One question would be, was this on purpose, or was this an oversight? It seems natural to me that these classes also implement the interface if they are indeed related to a workflow instance. This has some impact on the black list, and could have more impact in the future if we were to naturally assume that checking for the interface type would catch all workflow instance related records.

**Comment by saig0** [comment]
Looking at the code, I see that the classes implement the interface `WorkflowInstanceRelated` instead. For example, `TimerRecordValue` doesn't implement the interface but `TimerRecord` does it :) 
So, it should not have any negative effects.

**Comment by npepinpe** [comment]
Let's implement it in the public API, but as @saig0 pointed out, the impact is not as bad as I thought.

**Comment by aivinog1** [comment]
@npepinpe @saig0 Hi! While I'm waiting for responses from issues/review, I would like to take this one :)
