### ISSUE TITLE
Output broker version on startup

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#539]
- helps to pin down version of broker from log file
- maybe some pom magic which could also fetch commit has?

**Comment by ThorbenLindhauer** [comment]
There's also this: https://forum.camunda.org/t/get-camunda-version-via-api/920/2

**Comment by menski** [comment]
The package metadata is only set if the broker/client class is from the packed jar. So in an IDE or tests it will not be set so I decided to just print `development`.
