### ISSUE TITLE
Log invalid static configuration when detected

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5394]
**Description**

In the broker topology, we currently check if the static configuration of two brokers match - that is, that the cluster size, replication factor, and partition count all match. When this is false, we log that there's a mismatch, but do not log what exactly was mismatched, reducing the usefulness of the log statement. See: https://console.cloud.google.com/errors/CM_ridKXqsyn4QE?service=zeebe&version=0.24.2&time=P1D&project=camunda-cloud-240911&organizationId=669107107215

No need to log the exact differences, but we need to log at least both configurations so a human can find the differences.

**Comment by sccalabr** [comment]
Id like to pick this up. Where is the logging currently done?

**Comment by npepinpe** [comment]
Hi @sccalabr, this is the specific line where log this: https://github.com/zeebe-io/zeebe/blob/c29fc16a5cc71797bed157946d3ee17a77ca63e3/broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java#L192

The idea here would be to additionally log what is the local node's static configuration, and what is the remote node's static configuration (explicitly), so we can better diagnose the issue.
