### ISSUE TITLE
Lower the log level of AtomixServerTransport#sendResponse on leader change

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5396]
**Description**

If the leader changes while we're responding to a request, we will log the following message:

```java
          final var requestMap = partitionsRequestMap.get(partitionId);
          if (requestMap == null) {
            LOG.error(
                "Node is no longer leader for partition {}, tried to respond on request with id {}",
                partitionId,
                requestId);
            return;
          }
```

However, this is an expected case, as fail over could occur before the request is sent. I'm not sure that this needs to be an error log - the only case where we'd want to be aware is if it occurs repeatedly, and I'm not sure this is the right approach for this.

I would propose to lower the log level to WARN, as this is mostly useful for diagnosing issues, and would avoid polluting our error reporting tool.

**Comment by haardikdharma10** [comment]
Hey @npepinpe, can I trigger this issue and lower the log level to warn? Even I think the point you mentioned is valid. Let me know if I can go ahead and change it.

**Comment by npepinpe** [comment]
Sure, go for it :slightly_smiling_face:

**Comment by ChandaB** [comment]
@npepinpe Is this still a valid issue?  It appears a pull request was already opened and merged?

**Comment by npepinpe** [comment]
Ah, correct, this can be closed.
