### ISSUE TITLE
Need independent advertisedHost and advertisedPort (independent advertisedAddress) for command and internal APIs

### ISSUE THREAD

**Issue by sebascarra** [zeebe-io/zeebe#5410]
I need to deploy Zeebe nodes (brokers with embedded gateways) behind three different proxies. commandApi has address1:8443, internalApi has address2:8443 and monitoringApi has address3:8443. The proxy will then forward all traffic to the same host on ports 26501 and 26502, as Zeebe nodes usually work. However, I'm being unable to set advertised host and ports to each API separately. They just take the single advertisedHost and the same ports used for the same-pool node's internal communication (26501 and 26502). We are not allowed to use NodePort services (that would allow me to use just one proxy with more than one port).

Thanks for the help.

**Comment by deepthidevaki** [comment]
It works for me.  I set the following in application.yaml.
```
    network:
      host: 0.0.0.0

      commandApi:
        advertisedHost: 1.1.1.1
        advertisedPort: 1111
      internalApi:
        advertisedHost: 2.2.2.2
        advertisedPort: 2222
```

And the broker has set the configured advertisedHost correctly as shown in the logs.
```
2020-09-24 08:41:41.113 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "1.1.1.1",
      "advertisedPort" : 1111,
      "address" : "0.0.0.0:26501",
      "advertisedAddress" : "1.1.1.1:1111"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "2.2.2.2",
      "advertisedPort" : 2222,
      "address" : "0.0.0.0:26502",
      "advertisedAddress" : "2.2.2.2:2222"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 9600,
      "address" : "0.0.0.0:9600",
      "advertisedAddress" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
```

**Comment by sebascarra** [comment]
Genious, this is not documented anywhere! I will test this and let you know if this solves my issues.

**Comment by sebascarra** [comment]
Can these be set using environment variables such as "ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST", "ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDPORT" and so on? Thank you.

**Comment by sebascarra** [comment]
Yes it works! There is no mention to that in the code, but I think you just have a function that maps THIS_IS_MY_VARWOOHOO to this.is.my.varWooHoo, so even though there is no list of env vars, everything single configuration key-value pair is reachable by an env variable. It would be nice to document this behavior (maybe it is?).

**Comment by deepthidevaki** [comment]
> This is not documented anywhere, so thanks for having replied so fast
Sorry. All configuration parameter and environment variables are documented here https://docs.zeebe.io/appendix/broker-config-template.html. I will create an issue for these missing ones.

**Comment by sebascarra** [comment]
I think there is a bug with this. network.internalApi.advertisedPort is being used by the embedded gateway as gateway.cluster.port. See issue https://github.com/zeebe-io/zeebe/issues/5422
