### ISSUE TITLE
Warn on start up if replication factor is even

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5416]
**Description**

It's currently possible to start a cluster with an even replication factor. This leads to undefined behavior - it may work for some time in some cases, or fail, etc. It's also unclear how the election process will react. But more importantly, it generally breaks the Raft contract, where we expect quorum to be `ceil(N/2)` to avoid split brain issues. But with, say, 4 nodes, how can we guarantee we won't have two elected leaders? Maybe, maybe not - we don't test it, so as mentioned, it's unclear.

We should simply validate that the replication factor is odd in the system context, on start up, and stop the broker if it's even.

**Comment by deepthidevaki** [comment]
Why is even replication factor a problem? The quorum is calculated as floor(N/2) + 1 
https://github.com/zeebe-io/zeebe/blob/cd1ebb20466a3bf133608f7320da775255e8417a/atomix/cluster/src/main/java/io/atomix/raft/cluster/impl/RaftClusterContext.java#L746

**Comment by npepinpe** [comment]
Can we guarantee the system works as expected with an even replication factor, e.g. it has no impact on election, joining/bootstrapping, etc.? We never test any config with even factors

**Comment by deepthidevaki** [comment]
We have one set of tests running with 4 replicas - `RaftFailOverTest`. But no integration tests.

**Comment by npepinpe** [comment]
Is there any advantage to letting a user run with a system with even replication factor? I mean, let's say you set it to 2 - you can't really tolerate any failures. At this point the only advantage I can think of is that redundancy (in case of data loss)?

**Comment by deepthidevaki** [comment]
Even replication factor is not ideal. But I'm not sure if we want to disable it. I could see some cases where it is useful - like the case you mentioned, or  to deploy a zeebe cluster across two data centres for protection against data loss for example. We should disable it if it doesn't work now. But I don't understand why it doesn't work.

**Comment by npepinpe** [comment]
Some users ran into stability issues when running with even factor, though to be honest it's unclear to me if those issues were because of that or something else.

So let's keep it around, but print a warning on start up so users are aware this isn't a use case we explicitly support.
