### ISSUE TITLE
Zeebe Hazelcast Exporter also stops exporting records when error is encountered in Zeebe Elasticsearch Exporter

### ISSUE THREAD

**Issue by abhi1git** [zeebe-io/zeebe#5438]
**Describe the bug**

* Zeebe Elasticsearch started facing issue (illegal_argument_exception : exceed total filed limit for index) while putting data into ES so no data was being inserted into ES
* Along with this even simple monitor and Zeeqs stopped receiving data from Hazelcast exporter. 
* After increasing ES total field limit records started inserting in ES but still simple monitor and Zeeqs did not receive data from Hazelcast Exporter
* When restarted simple monitor and Zeeqs individually to obtain new hazelcast connection only simple monitor started receiving data from Hazelcast exporter and Zeeqs did not receive any data
* So restarted zeebe broker after that only Zeeqs started receiving data from Hazelcast exporter

**To Reproduce**
* Start zeebe broker with both Elasticsearch exporter and zeebe-hazelcast-exporter enabled
* Introduce anomaly in ES record insertion for zeebe ES exporter (for e.g any illegal_argument_exception)
* Because of that error ES exporter will continuouly keep on trying to insert that record until success
* Now deploy a sample workflow in zeebe now check its entry in simple monitor, it won't be updated.(Concluding even simple monitor stopped receiving data or zeebe hazelcast exporter stopped exporting data after error occurs in ES exporter even though simple monitor is not related anyhow to ES exporter)

**Expected behavior**
* As both exporters are independent of each other Error in one exporter should not affect the working of other exporter
* Hazelcast exporter should stop exporting records only if it itself faces some error while insertion
* Zeeqs should have started receiving data after its own restart as it obtains a new connection (i.e broker restart should not have been required)

**Environment:**
 - OS: Kubernetes
 - Zeebe Version: 0.24.2
 - Configuration: (1 Standalone gateway and 1 Broker) , zeebe-elasticsearch-exporter, zeebe-hazelcast-exporter, 

- clusterSize: "1"
- partitionCount: "1"
- replicationFactor: "1"
- cpuThreadCount: "2"
- ioThreadCount: "2"

Setup Details - Zeebe Cluster  is deployed on Kubernetes cluster using Zeebe Cluster Helm chart. Enabled zeebe elasticsearch exporter as well as zeebe Hazelcast exporter on zeebe broker. Zeebe Elasticsearch exporter is being used to export data to our Elasticsearch endpoint and Zeebe hazelcast exporter is configured to export data to simple monitor as well as Zeeqs( Postgresql as underlying DB ).

**Comment by npepinpe** [comment]
Hi @abhi1git! This is a limitation of Zeebe - exporting is unfortunately not yet a very cheap operation, so to keep it simple and avoid some overhead, all exporters are instantiate once per partition and grouped together. More specifically, for every partition, there is one exporter "read context", which reads every record, and for every record, will pass it on to all known exporters. This avoids the overhead of every exporter reading (I/O), deserializing, etc. The downside is that if one exporter is failing, it blocks all the others, as until that exporter has accepted the record, we cannot move on to the next one. This could be mitigated with some read-ahead and buffering, but that wouldn't solve the underlying issue, which is that all exporters in a partition must read at the same pace - meaning they export at the pace of the slowest exporter. To solve this, we would have to have one reading context per exporter - but as mentioned, at the moment it's just not cheap enough.

I hope we can solve this in the long run, but unfortunately I don't expect it to happen any time soon. Let me know if you have any other questions!

**Comment by npepinpe** [comment]
Closing for now, feel free to ping me if there's anything

**Comment by abhi1git** [comment]
Thank you @npepinpe  for the detailed explanation.
