### ISSUE TITLE
Improve Go client documentation

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#5444]
**Description**

Users have mentioned that the example https://stage.docs.zeebe.io/clients/go-client/get-started.html#work-on-a-task is a bit confusing. The previous example had a deadlock when closing which I replaced with a channel that the handler uses to signal that it's finished. While this fixes the deadlock, users have expressed that it is convoluted and it would be useful to have a more complete example. 
Some ideas for improving this: We could write a sample application that does the usual "order-process" thing but in a more organized way. Having a `main()` function that does everything showcases the most common API calls but it doesn't help the user understand how Zeebe can be used within an application. We could build a small app that set up a process when it's created, reacts to new orders by creating instances, deals with jobs and closes workers and the client when it's closed. Then the `main()` could start an app, submit orders, inspect results and close. It would accomplish the same but it would use the client API in a way that actually resembles real-world usage.

**Comment by adithyaakrishna** [comment]
@npepinpe Can I work on this issue?

**Comment by MiguelPires** [comment]
Hi @adithyaakrishna, thank you for showing interest in this. However, this is probably not the best issue to start with since the outcome is not clear. It might require experimenting a bit to come up with something that showcases the important parts of the api but doesn't overwhelm the docs with a huge example.

**Comment by npepinpe** [comment]
I would close this for now as DevRel will now take over the getting started guide/experience, which will include the things we wanted to improve here. Let me know if I misunderstood and we should reopen this in the other repo.
