### ISSUE TITLE
zb-parent checkstyle false positive for annotations

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#547]
When building spring-zeebe with the zb-parent 0.2.0, i get

```
UnusedImports: Nicht benutztes import - org.springframework.stereotype.Component.
```

which is wrong and happens for all annotation types ...

**Comment by menski** [comment]
Thanks for reporting, I will look into this in the next days

**Comment by menski** [comment]
@jangalinski I look into this and sorry if I again miss some spring knowledge but the Component import is actually unused. Intellij also shows it and the other imports as not used. And if I remove them I can still build the whole project and execute the tests. I created a pull request with my changes https://github.com/zeebe-io/spring-zeebe/pull/19. Could you explain why you think Component is not an unused import.

**Comment by jangalinski** [comment]
You are right and I was wrong ... don't know why I got the impression .... thanks!
