### ISSUE TITLE
A gateway should know a partition health.

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5481]
**Is your feature request related to a problem? Please describe.**
This issue is a part of #4853. To respond to the client a gateway should know partition health.

**Describe the solution you'd like**
To implement this, you'll need to use gossip to inform the gateway of the partition health. Start by adding additional info to the membership gossip protocol. Add an additional map from partition to health here: https://github.com/zeebe-io/zeebe/blob/develop/protocol-impl/src/main/java/io/zeebe/protocol/impl/encoding/BrokerInfo.java#L67 and make sure it get's wrapped and written correctly. Just have a look at how this class deals with its `partitionRoles` field. This will need to be updated in the sb definition of the gossip protocol: https://github.com/zeebe-io/zeebe/blob/develop/protocol/src/main/resources/protocol.xml#L112. Remember to add a `sinceVersion` attribute and update the protocol version in the pom here: https://github.com/zeebe-io/zeebe/blob/develop/protocol/pom.xml#L28. And where the gateway receives it: https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/impl/broker/cluster/BrokerTopologyManagerImpl.java#L120.

**Describe alternatives you've considered**
N/A.

**Additional context**
This issue created from https://github.com/zeebe-io/zeebe/issues/4853#issuecomment-703527007

**Comment by npepinpe** [comment]
Hey @aivinog1, I assume you'll be working on this :slightly_smiling_face: Just an FYI, low priority here means we'd be happy to have this, but the core team will not work on this anytime soon - you're still more than welcome to do so.

**Comment by aivinog1** [comment]
@npepinpe Hi, sure I'm working on these three tasks that I created. Thanks, I'll do my best on it :)
