### ISSUE TITLE
Create Jenkins release job for spring-zeebe community project

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#549]
- there exists a job on Jenkins to build and release spring-zeebe project
- artifacts are pushed to Camunda Nexus and Maven Central

**Comment by menski** [comment]
@jangalinski should there also be a GitHub release with some jar files? If so could you list the jar files which should be uploaded?

**Comment by jangalinski** [comment]
will do ... currently I cannot build due to the checkstyle restrictions ... I pushed anyway so you can reproduce it.

**Comment by menski** [comment]
Release job exists, we will debug and fix it if need when we do the first release
