### ISSUE TITLE
RuntimeException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition...

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5501]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CMrRvpP8i6OuygE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2

**Comment by Zelldon** [comment]
Last seen on 1 Oct 2020 no logs available. @npepinpe you can decided what we do with it.

**Comment by npepinpe** [comment]
I will close this for now - I think changes to the medic role will help prevent these situations to occur in the future. For now, as it never reoccurred, I wouldn't spend resources on this.
