### ISSUE TITLE
Unexpected error on retrieving commit position

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5503]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CKSU4cOXvJbGzQE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.23.4

**Comment by Zelldon** [comment]
This error is logged in the AsyncSnapshotdirector, when it is not able to retrieve the commit position. [It happens during closing partition and other dependencies are already closed.](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-20T14:14:50.473000000Z&dateRangeStart=2020-11-20T13:14:50.473Z&dateRangeEnd=2020-11-20T15:14:50.473Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22ff073a96-1bd3-4dee-a0f7-00c194bb0bfd-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-20T14:15:38.741490000Z&pinnedLogId=t579d3fiupyn7&pinnedLogTimestamp=2020-11-20T14:14:20.473830Z)


```

E 2020-11-20T14:14:20.365372Z Failed to append block with last event position 62350042333728. 
D 2020-11-20T14:14:20.365765Z Closing Broker-2-Exporter-1 
D 2020-11-20T14:14:20.365937Z Partition role transitioning from LEADER to FOLLOWER 
E 2020-11-20T14:14:20.366187Z Actor Broker-2-LogAppender-1 failed in phase STARTED. 
I 2020-11-20T14:14:20.367552Z Close appender for log stream logstream-raft-partition-partition-1 
E 2020-11-20T14:14:20.368219Z logstream-raft-partition-partition-1 failed, marking it as unhealthy 
D 2020-11-20T14:14:20.368566Z Detected unhealthy components. The current health status of components: {ZeebePartition-1=HEALTHY, Raft-1=HEALTHY, Broker-2-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=UNHEALTHY} 
E 2020-11-20T14:14:20.368773Z Partition-1 failed, marking it as unhealthy 
D 2020-11-20T14:14:20.368965Z Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY} 
D 2020-11-20T14:14:20.369216Z Dispatcher closed 
I 2020-11-20T14:14:20.369451Z On closing logstream logstream-raft-partition-partition-1 close 3 readers 
I 2020-11-20T14:14:20.369613Z Close log storage with name logstream-raft-partition-partition-1 
I 2020-11-20T14:14:20.468679Z Exporter closed 
D 2020-11-20T14:14:20.470580Z Closed exporter director 'Broker-2-Exporter-1'. 
D 2020-11-20T14:14:20.471008Z Closed Broker-2-Exporter-1 successfully 
D 2020-11-20T14:14:20.471343Z Closing Broker-2-SnapshotDirector-1 
E 2020-11-20T14:14:20.473830Z Unexpected error on retrieving commit position 
  undefined

```

**Comment by npepinpe** [comment]
Should not impact 0.24 or 0.25 as we don't take snapshot while closing anymore. 0.24 and 0.25 also saw improvements in how we handle resources during transitions.
