### ISSUE TITLE
ElasticsearchExporterException: Failed to put index template (503, timeout)

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5509]
**Describe the bug**
Observed as error in production log.

**Expected behavior**
* Zeebe is robust against 503 errors, timeouts from Elasticsearch
* 503 responses are not logged as errors
* timeouts are not logged as errors

**Log/Stacktrace**
https://console.cloud.google.com/errors/CNSazOy7rtzhlwE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CNX1zKu-3LS2Kw?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CLyP6ZOnnLychQE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.3

**Comment by Zelldon** [comment]
Related to https://github.com/zeebe-io/zeebe/issues/5564 we now lowered the log level of export fails
