### ISSUE TITLE
IndexOutOfBoundsException in LogSttreamReader

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5511]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/COKX89Cps72ocQ?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2

**Comment by npepinpe** [comment]
Closing as it unfortunately hasn't happened in 30 days, meaning we've lost the logs for this issue. I will keep that in mind for the future when it comes to triaging/root causing in issue - apologies that we didn't get around to it sooner.
