### ISSUE TITLE
ElasticsearchExporterException: Failed to put index template (unknown host)

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5512]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CIeD1OHpx4PtLw?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2

**Comment by pihme** [comment]
@npepinpe Let us talk about this issue when you are back

**Comment by pihme** [comment]
system retired export and recovered on its own

**Comment by npepinpe** [comment]
Looks like it primarily needs to be a warning then - this should be covered in https://github.com/zeebe-io/zeebe/issues/5564. I would propose closing this then since that issue has already been solved.
