### ISSUE TITLE
custom serializer configuration for zeebe Java client

### ISSUE THREAD

**Issue by gunanidhisagria** [zeebe-io/zeebe#5578]
Currently, there is no way to set the custom Object serializer to zeebe for serializing variables while creating workflowInstance.

The below statements describes the problem:
Assume, I am creating a Map object where multiple key-value pairs I am setting which all need to set as variables into workflowInstance.

Map<String, Object> **variable**=new HashMap<String,Object>();
variables.put("interaction",PartyInteraction);    // here PartyInteraction is a pojo object which may contain null values.
variables.put("productOrder",ProductOrder);  // here ProductOrder is a pojo object which may contain null vaues

zeebeClient.newCreateInstanceCommand().bpmnProcessId(bpmnProcessId).latestVersion().variables(**variable**).send());

and like the above statement, I am creating workflowInstance by passing the variable which is of type Map.
here when the variables will get serialized to workflowInstance , then all object property  with null/empty values also get serialized, 
 to avoid this null/empty value, we can think of taking the help of ObjectMapper and setting the JsonIncludeValue to nonNull 
and asking zeebe to take my ObjectMapper for serializing , but there is no way we can set a customised ObjectMapper to zeebe.

**Comment by aivinog1** [comment]
@npepinpe Hi again! :) I think that I can take this one. I think that I will add a new configuration property for a class name of extension of `io.zeebe.client.impl.ZeebeObjectMapper`. And in the `io.zeebe.client.impl.ZeebeClientImpl`, I can set it as a constructor parameter.
