### ISSUE TITLE
Write a Zeebe upgrade guide for K8s/Helm

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#5582]
**Description**

Extent the upgrade guide that was introduced with #5534 by a section on how to do the upgrade with K8s/Helm.

**Comment by Zelldon** [comment]
In your referenced PR you write:

> Because of current issue, it is not recommended to perform a rolling upgrade. Please follow the upgrade procedure instead.

This is something you should mention in this issue or at least to me :see_no_evil: 

So instead of the normal helm upgrade we would do an uninstall and install again.

**Comment by npepinpe** [comment]
Check whether this issue should be opened on the docs repo instead

**Comment by npepinpe** [comment]
It seems we will not publish the new documentation for at least 2 or 3 weeks, and my understanding is that's a conservative estimate, so maybe longer. This is the last piece of documentation that we would need to release on the older docs, but it should be possible to release this by using the `stable/0.25` branch. Let's do this as soon as possible please - if you need anything we can chat first and figure out how this will look like. It would make sense to also have one of the SREs involved (@afirth or @ztombol - I would link david but seems faffnir is not in our org :open_mouth:), if only for a review or maybe to give some input initially.

**Comment by npepinpe** [comment]
As mentioned in the PR, for now I will close this and we will write a new issue to update the upgrade guide once we have a solution for it.
