### ISSUE TITLE
Does Zeebe support writing to and reading from TLS-only Elasticsearch clusters?

### ISSUE THREAD

**Issue by sebascarra** [zeebe-io/zeebe#5585]
Question is if I can enable TLS in the application.yml for Zeebe Operate deploymennt and the Zeebe Cluster statefulset, so I can have Zeebe interact with a TLS-protected Elasticsearch cluster.

The following issues from February 2019 indicate the answer might be "no" but I wanted to confirm there have been no further developments on this.

https://github.com/zeebe-io/zeebe/issues/1990
https://github.com/zeebe-io/zeebe/issues/1992
https://github.com/zeebe-io/zeebe/issues/1993

If this is not supported yet, I will raise a feature request for this.

Thank you.

**Comment by saig0** [comment]
@sebascarra thanks for raising this up. No updates on this topic. It is still not possible to use TLS ES with Operate.

Feel free to open one of the listed issues above :)

**Comment by Zelldon** [comment]
Hey @sebascarra with the up coming operate release (0.25.0) this should be possible.

Greets
Chris

**Comment by sebascarra** [comment]
Thanks @Zelldon.
