### ISSUE TITLE
move QA tests to profile

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#559]
since I cannot build locally (neither mvn nor ide), it might be a good idea to move the QA tests to a separate profile so they can run on jenkins and I can switch them of. 

See #557 , #558

**Comment by menski** [comment]
In general I prefer a stable test suite, but I see your point in the current situation.

**Comment by jangalinski** [comment]
Don’t get me wrong, the way profile will be active by default, so nothing changes, but you have the option to skip during dev

**Comment by menski** [comment]
I added a property to skip the tests in `qa/integration-tests` you can use it by specifying `-Dskip-qa`, i.e. `mvn clean test -Dskip-qa`. Is a profile also needed or is a property enough?

**Comment by jangalinski** [comment]
A profile is not needed as we’ll, as it would be an alternative solution 

I‘d prefer a profile because it’s much easier to deactivate when running maven from the ide but property is fine for now

**Comment by menski** [comment]
okay I didn't thought about the IDE, I will migrate the property to a profile later

**Comment by jangalinski** [comment]
What I did locallly: remove module qa from root Pom and add it to a profile in parent

**Comment by menski** [comment]
that would not even compile the QA code or? I would like to keep the impact of skipping qa as minimal as possible

**Comment by jangalinski** [comment]
Good point

**Comment by menski** [comment]
I removed the property `skip-qa` and added a profile `skip-unstable-tests`. This profile will exclude all tests which are marked with `@Category(io.zeebe.UnstableTest.class)` (see https://github.com/zeebe-io/zb-util/commit/a70f7f0faad641b166b9baa45030e14f5332c81b and https://github.com/zeebe-io/zeebe/commit/cd3c6835f9e467716c449912c07c3b501c5d1b03). This way most of the tests are still executed and a developer can mark and skip unstable tests during development. I prefer this approach over excluding the whole QA test suite as the impact is minimal and test are marked explicitly as unstable. What do you think?

**Comment by jangalinski** [comment]
That sounds like a truly great pattern to address this. Lets see how it works out. Thanks! Close?

**Comment by menski** [comment]
Thanks for the feedback. Please report if you find other tests which are unstable locally. :+1:
