### ISSUE TITLE
Removal of ZbLogger

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5592]
**Description**

As we can now change the log level dynamically, is `ZbLogger` still necessary? As far as I can tell, it does mostly what the Log4J logger does already, so from my point of view we could just remove ZbLogger, unless someone knows why we should not. We can keep `ContextLogger` for now - though this would be superseded once SLF4J 2.0 is released (with the new structure API).

**Comment by aivinog1** [comment]
@npepinpe Hi! I would like to take this one.

**Comment by npepinpe** [comment]
Go for it! A few notes:

1. Places using directly `ZbLogger` should now just use `org.slf4j.Logger`
1. Places using `ContextualLogger` can keep using it - just make sure it now implements `org.slf4j.Logger` and doesn't extend `ZbLogger` anymore.
1. Make sure is to test with `StackdriverLayout` (you can do that by setting `ZEEBE_LOG_APPENDER=Stackdriver` when running the official distribution), that it contains the right source location, even after removing `ZbLogger`. When using `StackdriverLayout`, you will get JSON records, so a good thing to try it out is to run something like `ZEEBE_LOG_APPENDER=Stackdriver ZEEBE_LOG_SERVICE_NAME=zeebe-broker bin/broker | jq -R 'fromjson?'`, which will output in nicely formatted JSON. A log statement is expected to be something like:

```json
{
  "severity": "INFO",
  "logging.googleapis.com/sourceLocation": {
    "function": "logStarting",
    "file": "StartupInfoLogger.java",
    "line": 55
  },
  "message": "Starting StandaloneBroker v0.25.0-SNAPSHOT on com-camunda-npt470 with PID 1404601 (/home/nicolas/work/src/github.com/zeebe-io/zeebe/dist/target/zeebe-broker/lib/zeebe-distribution-0.25.0-SNAPSHOT.jar started by nicolas in /home/nicolas/work/src/github.com/zeebe-io/zeebe/dist/target/zeebe-broker)",
  "serviceContext": {
    "service": "zeebe",
    "version": "development"
  },
  "context": {
    "threadId": 1,
    "threadPriority": 5,
    "loggerName": "io.zeebe.broker.StandaloneBroker",
    "threadName": "main"
  },
  "timestampSeconds": 1604060255,
  "timestampNanos": 152207000,
  "logger": "io.zeebe.broker.StandaloneBroker",
  "thread": "main"
}
```

The important part to test is that the `logging.googleapis.com/sourceLocation` is correct :slightly_smiling_face:
