### ISSUE TITLE
TopicSubscriptionTest#shouldCloseSubscriptionOnTransportChannelClose is flaky

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#560]
`TopicSubscriptionTest.shouldCloseSubscriptionOnTransportChannelClose` of the `zeebe-broker-core` test suite fails occasionally on my Windows dev machine (~50% of times).

**Comment by Zelldon** [comment]
@ThorbenLindhauer is this still the case?

**Comment by ThorbenLindhauer** [comment]
Looks fine now. I removed the unstable annotation.
