### ISSUE TITLE
Partition request does not return extra partitions

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#562]
Topic creation as a retry mechanism which can lead to the situation where a requested topic with x partitions is created with more than x partitions. In this case, the partition request implemented in #530 returns only x partitions. Similar behavior occurs in the case of deployments, i.e. a deployment is only distributed to x partitions.

Reason: Both endpoints rely on collecting all the created partitions. This currently only respects the first x partition CREATED events on the system log.

**Comment by menski** [comment]
This means if we deploy a workflow on a topic which has retry partitions the deployment is successful but the workflow does not exist on all partition of the topic? So the client will fail to start workflow instances while doing round robin as the topology also contains retry partitions? Is that correct?

**Comment by ThorbenLindhauer** [comment]
Yes, correct.

**Comment by menski** [comment]
Okay thanks for confirmation then I think we should address that in the near future after finishing our current topics.

**Comment by ThorbenLindhauer** [comment]
Here's a test for the partition request: https://github.com/zeebe-io/zeebe/commit/e6196912cf9f2f52433de3919e48a1c183a20b84#diff-7bb9375e8ef161a823e4fe842066351dR123
