### ISSUE TITLE
Incident stream processor does not close zb map

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#563]
related to #469

**Comment by ThorbenLindhauer** [comment]
I added some logging for easier debugging of zbmap memory leaks. Set the log level to TRACE to get the stacktrace context of each ZbMap that is created.

**Comment by Zelldon** [comment]
What do you think about printing the log msg in the finalize? So we only see this if it was not closed and also in combination with the not closed stmt. I did this for test on the https://github.com/zeebe-io/zb-util/tree/allocatorInCharge branch a couple of month ago. Problem is that we have to store the stacktrace.

**Comment by ThorbenLindhauer** [comment]
> Problem is that we have to store the stacktrace.

That's why I decided against it. In my opinion, it is ok to log this for all maps with trace logging enabled. But I'm generally fine with both solutions, just make sure you record the stacktrace only when trace logging is enabled.
