### ISSUE TITLE
Elasticsearch exporter: List urls for connection 

### ISSUE THREAD

**Issue by jooble** [zeebe-io/zeebe#5635]
I want to use list urls for configure es exporter, because i have es with some nodes

As in es`s docs - https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started-initialization.html

**Comment by saig0** [comment]
@jooble thank you for raising this up :+1: 
Please describe the concrete use case a bit more that this issue should solve.

**Comment by jooble** [comment]
Hi, i have some reasons for that: 
 1. It allows to use load balancing across all nodes. I`m not sure if it can update cluster in runtime. (I didn`t find in docs)
 2. If node cluster is down, broker won`t export logs
 3. I have 3 ES nodes ES and 3 broker nodes, and I don`t know how I will distribute the es nodes to the broker nodes, its hard for me, i just want put all the es nodes

**Comment by cmrenus** [comment]
Second to this. Even if you don't build in load balancing to the nodes, having an alternate node if one goes down is helpful.
