### ISSUE TITLE
extract api modules for broker and client

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#564]
I am currently working on integrating the zeebe rules available in zeebe-test-template-java into zeebe/zeebe-test

so you can use the rules and test-tools without c&p the template.

The new module will be depending on broker-core and client-java, so it will not be possible to use the zeebe-test itself for tests inside one of those modules (circular dependencies).

BUT: if we extract the core api classes into broker-api and client-api, the test-lib would only have to depend on those, meaning it could be used in the broker-core/client-java themselves.

The module tree would be

broker-api/client-java-api - no deps

zeebe-test - dep to broker-api&client-java-api

broker-core - dep to broker-api and zeebe-test

client-java - dep to client-java-api and zeebe-test

this would mean, that having "integration" tests for zeebe-test inside zeebe-test would not be possible, cause this would require again a circle. But this a) just affects a few classes and b) could be solved by putting the rule tests into some qa/zeebe-test module.

WDYT?

**Comment by menski** [comment]
Hi @jangalinski,

thanks for bringing up the topic. But at the moment we think that this is a to major change for the only benefit of not duplicating a couple test helpers. Also we don't see any other reason to decouple API and Implementation of Zeebe at the moment. Therefore I would close this ticket and hope you didn't wasted to much time already.

Cheers,
Sebastian
