### ISSUE TITLE
Fix warnings in LGTM

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5647]
**Description**

Now there are some warnings in [LGTM](https://lgtm.com/projects/g/zeebe-io/zeebe/alerts/?mode=list). They should be fixed.

**Comment by Zelldon** [comment]
https://lgtm.com/projects/g/zeebe-io/zeebe/snapshot/8bfe3db3e96c8052c0fd81758f7381f292310c98/files/engine/src/main/java/io/zeebe/engine/processing/deployment/transform/DeploymentTransformer.java?sort=name&dir=ASC&mode=heatmap#xfeaf97ecc52bcde:1

Cant be easily fixed without breaking backwards compatibility or in other words. If we change here the algorithm then on new deploy of the same file it will be redeployed. @npepinpe needs to decide if we want to change the algorith.


https://lgtm.com/projects/g/zeebe-io/zeebe/snapshot/8bfe3db3e96c8052c0fd81758f7381f292310c98/files/util/src/main/java/io/zeebe/util/sched/ActorThread.java#x5c8b1d58efc9782c:1

Not sure of adding the synchronize word for the start. Actually it should not break any thing but the complete implementation is written in a way to avoid locks so I feel not comfortable to add this here.

**Comment by npepinpe** [comment]
We use md5 not for security but simply to fingerprint the file to see if we already have it or not. I don't really see any point changing it, I fail to see how this could be a vector of attack. I would mark it as a false positive - is this possible with LGTM? Like `@SuppressWarnings`?

**Comment by Zelldon** [comment]
I think it is not only about security. It is proven that MD5 is not collision resistant which a hash function should provide. This means in our case you could have two completely different deployment with the same hash.

**Comment by npepinpe** [comment]
What's the probability however? Isn't something ridiculous low? I mean, maybe we wanted to identify duplicates for all files that ever existed, but in this case we'd only care about a small number of deployed files right? It doesn't seem like much of an issue to me at the moment :thinking:

**Comment by Zelldon** [comment]
We can disable it via // lgtm [java/weak-cryptographic-algorithm at the end of the line
