### ISSUE TITLE
Java Client: A subscription is reopened on Broker leader change

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#565]
Related to #142.

**Comment by ThorbenLindhauer** [comment]
Here are my findings for the Java client:

* Reopening the subscription (task or topic) works already when the corresponding broker becomes unavailable. In this case, the connection is lost and the client reopens the subscription accordingly.
* Reopening does not work yet when there is a regular leader change. There is no event that the client could react to in this case.

Solution possibilities:

1. Close connection on leader change and thus handle both cases in the same way on client side.
1. Poll topology on client side and reopen subscription as soon as the leader has changed
1. Send dedicated close event on the subscribed channel from broker to client.

Option 1 is not so great because the broker may still be leader for other partitions. Any clients subscribed to those would be affected.

Option 2 is not so great because the topology response is not guaranteed to be consistent. This may lead to odd behavior on client side, e.g. a subscription could be reopened although the leader has not changed, etc.

I'll try option 3 for now. In order to avoid an extra message type in the protocol, the subscription end message will be a `SubscribedEvent` at position 0. This is debatable, though.

**Comment by ThorbenLindhauer** [comment]
I'm postponing this issue for now. There are too many obstacles on the way to implement a proper solution in a timely manner and while it is related to our goal of topic-wide subscriptions, it is not essential to it. 

In particular, the following issues influence this:

* https://github.com/zeebe-io/zeebe/issues/575: Zeebe cluster becomes generally unresponsive when a broker is shut down, so a subscription won't reopen. Hotfix here: https://github.com/zeebe-io/zb-transport/commit/5fee70e7036a0f955fb06ff0cb47dfc619d12a69
* https://github.com/zeebe-io/zeebe/issues/578: This leads to client timeouts or broker crashes when a reopen request is made. Couldn't think of a useable hotfix.
* https://github.com/zeebe-io/zeebe/issues/200: This is only an issue for the tests that can be worked around

See the linked commits for my work in progress.

**Comment by menski** [comment]
Topic subscriptions are no longer supported. Job workers are now polling
