### ISSUE TITLE
Zeebe diagnostics runbook

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5650]
**Description**

As part of the October 16th gameday, we saw need for a runbook to diagnose zeebe during incident resolution.

It should contain:
* a reminder of the goal of incident resolution: no need to immediately fix the bug but do resolve the problem
* links to interesting pages like dashboard and logs
* common questions to answer like is zeebe able to compact, etc
* how to check for number of files in runtime/snapshot/pending
* refer to cluster plan limitations

It should be easily available to the Zeebe Dev working on the incident.

**Comment by korthout** [comment]
Gameday incident report: https://docs.google.com/document/d/1zbp7DD_BZxzasWouDIXJ_-VK2lk2DdJMsMMLuvrYLWo

**Comment by korthout** [comment]
Link to cluster plans: https://console.cloud.camunda.io/admin/cluster-plan

**Comment by npepinpe** [comment]
I would propose we first start it in the same repo as the runbook, and see how it evolves - if it's too specific to our setup or not, and see what we make public afterwards.

**Comment by korthout** [comment]
@npepinpe I guess we can close this for https://github.com/camunda-cloud/runbook/blob/master/zeebe/troubleshooting-guide.md

**Comment by npepinpe** [comment]
Thanks :smile:
