### ISSUE TITLE
Workflow stuck with job timed out but no incident raised

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/zeebe#5655]
versions
```
Zeebe Broker & Gateway version camunda/zeebe:0.24.4

    <dependency>
      <groupId>io.zeebe</groupId>
      <artifactId>zeebe-client-java</artifactId>
      <version>0.24.2</version>
    </dependency>
    <dependency>
        <groupId>io.zeebe.spring</groupId>
        <artifactId>spring-zeebe-starter</artifactId>
        <version>0.23.0</version>
    </dependency>

```
I seem to have a workflow stuck. 

The zeebe simple monitor shows that a task has activated, and timed out, however an incident hasn't been raised.

I have a bug in our job implementation that caused the job to never complete and never call  `jobClient.newCompleteCommand`   I can reproduce in dev by putting a breakpoint in the job implementation and waiting until the timeout period has passed.

The job is declared in code as :

```
@ZeebeWorker(type = CHECK_AVAILABILITY_TASK_TYPE, timeout = 1000 * 60 * 10)
public void checkAvailability(final JobClient jobClient, final ActivatedJob job) {

  // business logic that never completes

    jobClient
      .newCompleteCommand(job.getKey())
      .variables(OffersAvailVars.builder()
        .offersAvailable(avail ? 1 : 0)
        .build())
      .send()
    .join();
  }
```

The audit log tab :

![image](https://user-images.githubusercontent.com/672405/96822871-d0fefb80-1476-11eb-92a8-71066a0ca263.png)

The Jobs tab :

![image](https://user-images.githubusercontent.com/672405/96822908-e542f880-1476-11eb-8e40-a4d6b9e4fb27.png)

The incidents tab :

![image](https://user-images.githubusercontent.com/672405/96822935-f12eba80-1476-11eb-983e-a34305f8bcc0.png)

Zeebe broker logs since the WORKFLOW_INSTANCE_CREATION record was exported :

[logs-from-zeebe-broker-in-zeebe-zeebe-broker-0 (1).txt](https://github.com/zeebe-io/zeebe/files/5419977/logs-from-zeebe-broker-in-zeebe-zeebe-broker-0.1.txt)

**Comment by cameronbraid** [comment]
FYI I upgraded zeebe-client-java to latest but made no difference

```
    <dependency>
      <groupId>io.zeebe</groupId>
      <artifactId>zeebe-client-java</artifactId>
      <version>0.24.3</version>
    </dependency>
```

**Comment by Zelldon** [comment]
This is not a bug, it is intended behavior that no incident is raised. 

Incidents are only raised if the job fails multiple times and has no retries left. You can fail a job via a command (FailCommand) to show an execution error. You are able to configure a retry count, which make sense to your application and domain. 

Jobs are timed out after some period of time, depending on your configuration, but these are not seen as execution errors where an incident would make sense. We don't know whether your handler was wrongly configured, bad designed, takes too long to complete or there were some network issues between client and broker. Other workers should be able to pick up the job after one worker was not able to complete the job in time.

Please take a look at the docs:

 * [Job Worker](https://docs.zeebe.io/basics/job-workers.html?highlight=job,worker#job-workers)
 * [Incidents](https://docs.zeebe.io/reference/incidents.html?highlight=incidents#incidents)

Or a similar discussion to that:

 https://forum.zeebe.io/t/how-to-deal-with-transient-failures-without-manual-intervention/1695

**Comment by cameronbraid** [comment]
The issue is that it just sits there and never tries again.

If there are retries left, it should try executing the job abain but it is not.
If there are no retries left, it should raise an incident.

Neither of these two are happening.  And after hours of sitting there.

**Comment by cameronbraid** [comment]
After some though I realised that it must be that the spring @ZeebeWorker only creates a single thread to execute the worker and since this thread is blocked in the job, there are no other workers to take over.

**Comment by bugbugmaker** [comment]
> ZeebeWorke



> After some though I realised that it must be that the spring @ZeebeWorker only creates a single thread to execute the worker and since this thread is blocked in the job, there are no other worker threads to take over.

May I ask how you solved this problem? I also encountered this problem
