### ISSUE TITLE
source code incomplete

### ISSUE THREAD

**Issue by scgillian** [zeebe-io/zeebe#5673]
**Description**
class ValueType and class ExecuteCommandRequestDecoder can not be found in package io.zeebe.protocol.record

**Comment by Zelldon** [comment]
You need to build the project - these files are generated during compile time of the project..

**Comment by scgillian** [comment]
> You need to build the project - these files are generated during compile time of the project..

Any tutorial to build  project to generate  class ValueType etc.?

**Comment by Zelldon** [comment]
Please see the contributing guide https://www.github.com/zeebe-io/zeebe/tree/develop/CONTRIBUTING.md

:)
