### ISSUE TITLE
Using github.com/zeebe-io/zeebe/clients/go v0.25 provokes linter issues

### ISSUE THREAD

**Issue by osangenis** [zeebe-io/zeebe#5675]
**Description**

We use https://github.com/golangci/golangci-lint and after upgrading the zeebe go client to 0.25, the following warnings appeared (maybe something worth checking): 

`copylocks: func passes lock by value: github.com/zeebe-io/zeebe/clients/go/pkg/entities.Job contains github.com/zeebe-io/zeebe/clients/go/pkg/pb.ActivatedJob contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`

Looks like the root cause is the definition of the handler:

`type JobHandler func(client JobClient, job entities.Job)`

as it is not a reference but a value copy

**Comment by npepinpe** [comment]
Hey @MiguelPires, can you assess severity here? I understand doing this may sometimes lead to deadlocks, for example - what is the worse case scenario for us?

**Comment by MiguelPires** [comment]
I don't think this can hurt us much or at least I don't see how. That mutex is a put in MessageState specifically to make govet flag this to prevent people from copying the struct. I also need to look into why golangci went quiet, I don't remember how it worked but we can use github actions https://github.com/golangci/golangci-lint-action
