### ISSUE TITLE
Verify that log.trace does reduce performance if higher log value is used

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#568]
While talking about logging in Zeebe we discussed the option to use the `TRACE` log level for development debug statements, i.e. even in event processing. The requirement for this is that `log.trace` statements will not reduce the performance in a production setup with a higher log level. Therefore we have to validate that this is the case by taking a closer look into how log statements are handled by the JVM.

**Comment by ThorbenLindhauer** [comment]
Note that varargs logging produces garbage in the form of arrays (see also corresponding method javadocs in slf4j). Not sure if there's a convenient way around that.

**Comment by menski** [comment]
I create a minimal example to see the overhead of a disabled log statement: https://github.com/zeebe-io/logger-overhead

It seems that the overhead is around 4 times slower as without the log statement on my local machine. Which would mean we should not add any log statements in the hotpath of Zeebe. If we still want to have log statements in the hotpath we have to build our own guarding system, which allows the JIT to remove the unused branch, something like this https://github.com/zeebe-io/logger-overhead/blob/5511e3dc3b9f97bba472340a096b5143d8f51efb/Benchmark.java#L66.

**Comment by menski** [comment]
I rewrote the benchmark using JMH to ensure that the benchmark is solid. Nevertheless the outcome is still an overhead of around 4 times slower with trace statement.

**Comment by ThorbenLindhauer** [comment]
We will go with guarding log statements in the hot path like so:

```
private static final boolean TRACE_ENABLED = ...;

if (TRACE_ENABLED)
{
  log.trace(..);
}
```
