### ISSUE TITLE
Upgrade mocktio to latest version

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#569]
We want to use the latest versions of mockito 2 and junit 5 in our test suites. A first step is to check if there is a bigger migration required for the existing test cases.

**Comment by menski** [comment]
I upgraded mocktio to 2.13.0 in the parent and used the parent SNAPSHOT version in all projects which use mocktio. As next step I will release a new version of zb-parent and use it in all projects. The biggest change during migration was the [ZeebeMockitoAnnotationEngine](https://github.com/zeebe-io/zb-util/blob/6857dc30df5f1617eb190f54f9fd6e176fb01fdd/test-util/src/main/java/io/zeebe/test/util/ZeebeMockitoAnnotationEngine.java). As the method `createMockFor` is now private and not be overriden I basically copied the code of the `InjectingAnnotationEngine` and added our `FluentMock` there. There is probably a better way to do that.

**Comment by menski** [comment]
I will postpone the upgrade to jUnit 5 as they changed a lot and also got rid of TestRules and replaced them with an [extension model](http://junit.org/junit5/docs/current/user-guide/#extensions). There is kind of support to [still run test rules](https://github.com/junit-team/junit5/tree/master/junit-jupiter-migrationsupport). But I would prefer a clean migration which should be possible.

**Comment by menski** [comment]
I created a separate ticket for JUnit5 migration (#687) as it's a bigger change to migrate.

**Comment by menski** [comment]
@saig0 could you please review this change https://github.com/zeebe-io/zb-util/commit/6857dc30df5f1617eb190f54f9fd6e176fb01fdd#diff-4423c4eb3e9ce86c6a2121639b278de4. Everything else is just updating versions and adjusting to new APIs. Thanks

**Comment by saig0** [comment]
@menski , I think that we don't need the `@FluentMock` anymore. It is used in only one test case which doesn't use the mocks. Anyway, there is also a standard way to deal with fluent APIs: https://tuhrig.de/everytime-a-mock-returns-a-mock-a-fairy-dies/

If we need this feature then we can write:
```java
@Mock(answer = Answers.RETURNS_DEEP_STUBS)  // or Answers.RETURNS_SELF
private Builder mockBuilder;
```

**Comment by menski** [comment]
@saig0 so I will just delete the `ZeebeMockitoAnnotationEngine.java` class? And remove or migrate the fluent mocks?

**Comment by saig0** [comment]
@menski , you can just delete both of them.
