### ISSUE TITLE
SerialGC is used for StandaloneGateway deployment

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5700]
**Description**

I don't know whether it is related to https://github.com/zeebe-io/zeebe/issues/5699 that we are not setting limits, but currently it seems that the JVM doesn't detect correctly how many CPU's the Gateway has available and uses as default GC the serial GC.
This causes high GC pause times (stop the world) ~8 sec. This happens at least on my last test, see here https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-days/2020-10-27

Related https://stackoverflow.com/questions/52474162/why-is-serialgc-chosen-over-g1gc

**Comment by npepinpe** [comment]
How was the standalone gateway deployed? Helm chart?

**Comment by Zelldon** [comment]
Yes :sweat_smile:

**Comment by npepinpe** [comment]
Should this be opened on the Helm repo side? This sounds like a deployment issue and not a Zeebe specific issue.

**Comment by Zelldon** [comment]
We set the Java options right? So I'm not sure if I agree on here.

**Comment by Zelldon** [comment]
Resource limits is also a thing which we should do when deploying the helm chart.

**Comment by npepinpe** [comment]
afaik we don't set any Java options in the Docker image, and the ones we set in the `bin/broker` scripts are `-Xms128m --illegal-access=deny`. I don't expect we'll ever set GC options (at least not in the near future), so I would propose to move this and the resource limit issue (do we have an issue for it in this repo?) to the Helm chart repo. I can do it if you're fine with this.

**Comment by Zelldon** [comment]
We setting java options here: https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/setup/default/zeebe-values.yaml#L43-L49 

You can set the resource limits in the helm charts already. But is is not set in our benchmarks. I have the feeling we talking here about different things. I'm talking about our setup and benchmarks where we never set the limts for gateways nor the correct GC.

**Comment by npepinpe** [comment]
Ah, sorry, I misunderstood. Yes, let's set resources in our benchmark set up, sorry :see_no_evil:

**Comment by npepinpe** [comment]
Blocked by https://github.com/zeebe-io/zeebe/issues/5699 - let's assign resources first, and see if it fixes this.
