### ISSUE TITLE
Java client: Should refresh topology if transport cannot establish connection

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#571]
Currently, we have a topology-refresh mechanism in case a partition leader cannot be found. We should also refresh the topology, if a leader is known but cannot be connected to (e.g. if a broker has been shut down).

**Comment by Zelldon** [comment]
I think this is outdated. We now have client to gateway communication over GRPC and the gateway has always an up to date topology via atomix.
