### ISSUE TITLE
Use MAPPED storage level by default

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5711]
**Is your feature request related to a problem? Please describe.**
Now that the stability of Zeebe has improved, many users have complained about the performance. Using the new memory mapped storage level should improve this; however, this is disabled by default as it isn't as battle tested as the DISK level. For the future, it makes sense for us to concentrate our efforts on a single type, so we should switch the default to MAPPED.

**Describe the solution you'd like**
Set `zeebe.broker.data.useMmap=true` by default, and roll this out at least to INT. This will allow us to start testing this more extensively and get a better idea of how it behaves. It will also allow us to eventually dropped the other storage levels, allowing us to reduce the code base and focus our efforts on a single implementation. We can discuss if we want to roll this out to PROD before 0.26 as part of the kickoff.

**Describe alternatives you've considered**
Keep the status quo

**Comment by korthout** [comment]
@npepinpe I feel like we should first roll out `zeebe.broker.data.useMmap=true` on cloud, before changing Zeebe's default.

**Comment by npepinpe** [comment]
Changing the default means 0.26 would have it - we wouldn't release this as a patch release or anything. I'm unsure about rolling this out to prod yet, but I think rolling it out to INT/DEV would be good. We could do this already - however, having our tests (including the testbench and chaos) all run with mmap would greatly improve coverage, no?

**Comment by korthout** [comment]
@npepinpe If we aim this for 0.26 I definitely agree we should start using this in all our tests asap. The longer we test with it the better. Benchmarks throughput will likely be affected so it might be difficult to for comparisons in the beginning. WDYT @Zelldon, can we just apply this to our benchmarks setup?

**Comment by Zelldon** [comment]
Change it a soon as possible

**Comment by npepinpe** [comment]
One thing that came up with a discussion with Daniel, was we need to make sure we unmap segments as soon as possible (to avoid memory trashing and generally loading too many pages). We already do so for readers, but we keep the writers always open - do we have an issue to close writes once a segment isn't being written to anymore? With the changes @korthout did it will be easier to do so now I think. This would also help keep memory usage a bit more down - this plus a few other issues I've already created to remove unnecessary long living readers.

**Comment by korthout** [comment]
I haven't looked into this, so I think we don't have an issue for this. 

I was also wondering whether it makes sense to change `SegmentedJournal.createSegment(JournalSegmentDescriptor)` to use `IoUtil.mapNewFile` instead of the RandomAccessFile filechannel that is currently used to write the segment descriptor. Perhaps touching the file completely reduces page faults later.

**Comment by npepinpe** [comment]
So when mapping the same file twice, they initially share pages - all dirty pages (every write) will become private, and become "clean" again once they've been written back to disk. So I don't think it would reduce page faults so much, as I imagine most of the time pages will be shared anyway. My current guess for the amount of page faults is due to our records not being aligned to the page size, but that's just an hypothesis - could be that you're right, to be honest.

**Comment by korthout** [comment]
I think it makes sense to let the OS do its thing here. Informing the OS of our intentions by mapping the file during creation might give it the additional data it needs for optimisations that we don't know about. But honestly, I have no clue about it. In the end the description needs to be written to disk before the readers/writer start using it (or is that not true?), so if we map we need to flush and unmap directly.

**Comment by npepinpe** [comment]
I think we're not talking about the same thing :) We can gladly discuss this over Zoom :+1:
