### ISSUE TITLE
More complex data mapping

### ISSUE THREAD

**Issue by cmrenus** [zeebe-io/zeebe#5737]
**Description**

A clear and concise description of what this issue is about.

Is there any plan to add more complex data transformation? such as converting a json object to an array or something? For example I have a json object of addresses
addresses: { address1: {}, address2: {} } , and be able to convert this to addresses: [{}, {}], in order to use a looped service? 

There are some other scenarios I feel that could valuable like appending a constant to a value, but it doesnt seem like it is possible.

source: 'Bearer ' + =token , target: header

**Comment by Zelldon** [comment]
I think you can do it with a feel expression, e.g. append see https://camunda.github.io/feel-scala/develop/feel-built-in-functions for more information.

**Comment by cmrenus** [comment]
Yea actually I figured out I could use get value and like statically create the array which was fine for this scenario. Didn’t realize before that was possible with feel
