### ISSUE TITLE
Remove usage BrokerContactPoint in benchmarks.

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5741]
**Description**

This is a part of #2973 that I intentionally missed in the #5373. Needs to replace usage of `io.zeebe.client.ZeebeClientBuilder#brokerContactPoint` to `io.zeebe.client.ZeebeClientBuilder#gatewayAddress` and `io.zeebe.client.ClientProperties#BROKER_CONTACTPOINT` to `io.zeebe.client.ClientProperties#GATEWAY_ADDRESS` in the benchmarks since it depends on the current version of Java client.

P.S. There are some usages in tests, we should replace this too.

**Comment by aivinog1** [comment]
@npepinpe Hi! I would like to take this one since I've created this :)

**Comment by npepinpe** [comment]
It's all yours :slightly_smiling_face:
