### ISSUE TITLE
Error when a large JSON object is passed as a variable

### ISSUE THREAD

**Issue by pedrompc** [zeebe-io/zeebe#5746]
Hello, I've found that if one passes a large JSON object as a variable upon job completion, a somewhat cryptic error occurs. It was suggested in the zeebe forum that I open this issue, so that the error message can be improved.
In my tests, I used v0.24.1 and v0.25.0, and the JSON object had around 57MB.

Here's the link to the issue i opened in the zeebe forum: https://forum.zeebe.io/t/persistent-error-upon-completing-job/1731

**Comment by saig0** [comment]
Duplicated issues. Closing this issue in favor of #4928.
