### ISSUE TITLE
Cluster performance degrades greatly when shutting a broker down

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#575]
Scenario:

1. Start 3 brokers `a`, `b`, `c`
1. Shutdown broker `c`
1. Create a task on partition at broker `a`

Current behavior: Creating the task times out

Expected behavior: Creating the task takes the same time as before step 2.

Explanation:

* The task is processed so slowly, because committing an event takes extremely long (=> five or more seconds according to logs)
* Broker `c` is still a member of the raft group, so `a` and `b` still try to send append requests to it
* in `b`'s send buffer, the following constellation of messages appears: `[append(=>a), append(=>c), append(=>a), append(=>c), ...]`
* with every append request for `c`, transport tries to establish a connection to `c` which times out after a couple hundred milliseconds accordingly, requests to `a` are delayed and pile up in the send buffer

Solution possibilities: 

* Not sure I get the big picture yet; as a quick fix to validate my understanding, I introduced a timeout in transport to attempt a connection at most every 5 seconds. All messages that are encountered during that time are discarded immediately. This improves performance a bit again.

**Comment by menski** [comment]
It seems two tests are failing on Jenkins https://hq2.camunda.com/jenkins/zeebe/job/zb-transport-DISTRO-maven-deploy/lastBuild/testReport/
