### ISSUE TITLE
Deployment Reprocessing Inconsistency with DeploymentCache

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5753]
After looking into `DeploymentCreateProcessor` and `WorkflowPersistenceCache`, we can say that the processor is definitely a problem for the reprocessing detection. Depending on the in-memory state of the cache, the `CREATE` command is accepted or rejected. So, it depends on which records the processor has processed before (independently from the actual records on the log stream). 

On reprocessing, if the processor reads more or less `CREATE` commands as the processor that wrote the follow-up event (`CREATED` / rejection) then it produces a different follow-up event and it is detected as reprocessing issue.

_Originally posted by @saig0 in https://github.com/zeebe-io/zeebe/issues/5688#issuecomment-721021464_

**Comment by Zelldon** [comment]
> The cache is used in the `DeploymentCreateProcessor` to verify that the deployment is new and to add it to the state. If this deployment with the same key already exists (in-memory) then the processor rejects the `CREATE` command.
> Now we can have situations which might be problematic. Say we have two of the `CREATE` commands on normal processing, this can happen when the first partition re-distributes the deployment. When the first one is processed we create a follow event (`CREATED`), on the second `CREATE` we will write a rejection, since it is already in-memory. If a leader change happens, then it is crucial where the snapshot was taken. If the snapshot position is **AFTER** the first `CREATE` this means that we will handle the second `CREATE` as the first one, which means we will generate on reprocessing a `CREATE` but on the log is a rejection written. This is because the in-memory state doesn't reflect the real state.
> 
> **Side note:** We talking here about Partition three, which gets deployments from partition one distributed.

https://github.com/zeebe-io/zeebe/issues/5688#issuecomment-721092741

**Comment by npepinpe** [comment]
There's little gain from writing a rejection if something already exists, as we don't distinguish between either case. So let's just write that's been created, as:

1. In memory caches don't play well with our retry/abort mechanism of rolling back the state
1. We don't handle the rejection at all, and returning success on an operation that was previously done/cached is fine
1. It creates an additional event, however let's not focus on this for now until our new processing concept is done - we can take care of that later once we know how this will look like

**Comment by npepinpe** [comment]
Downgrading priority in favor of https://github.com/zeebe-io/zeebe/issues/5759
