### ISSUE TITLE
java.lang.IllegalStateException: Failed to execute CommandLineRunner - Shutdown in progress

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5755]
**Describe the bug**
A Zeebe broker was unable to start during the camunda cloud E2E test. 

[Error](https://console.cloud.google.com/errors/CJrb-4TCw7vXdA?service=zeebe&time=P1D&refresh=auto&project=camunda-cloud-240911&authuser=1)

**Log/Stacktrace**

[Log in google console](https://console.cloud.google.com/logs/query;pinnedLogId=2020-11-02T23:03:55.024185Z%2Fg3dzmzfegmpk7;query=error_group%2528%22CJrb-4TCw7vXdA%22%2529%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22excitingdev%22%0Aresource.labels.namespace_name%3D%2259b9075e-7aa0-4642-91ed-323752403309-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-11-02T22:34:25.024Z%2F2020-11-02T23:34:25.024Z?project=camunda-cloud-240911)

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner (SpringApplication.java:798)
at org.springframework.boot.SpringApplication.callRunners (SpringApplication.java:779)
at org.springframework.boot.SpringApplication.run (SpringApplication.java:322)
at org.springframework.boot.SpringApplication.run (SpringApplication.java:1237)
at org.springframework.boot.SpringApplication.run (SpringApplication.java:1226)
at io.zeebe.broker.StandaloneBroker.main (StandaloneBroker.java:52)
Caused by: java.lang.IllegalStateException: Shutdown in progress
at java.lang.ApplicationShutdownHooks.add (Unknown Source)
at java.lang.Runtime.addShutdownHook (Unknown Source)
at io.zeebe.broker.StandaloneBroker.run (StandaloneBroker.java:67)
at org.springframework.boot.SpringApplication.callRunner (SpringApplication.java:795)
```

**Environment:**
Camunda Cloud / `excitingdev` / `0.25.0`

**Comment by korthout** [comment]
@npepinpe Its unclear to me whether this occurred due to the way the E2E is setup or due to some issue in Zeebe

**Comment by ultraschuppi** [comment]
> @npepinpe Its unclear to me whether this occurred due to the way the E2E is setup or due to some issue in Zeebe

na... this test does flap sometimes, but not most of times. so either this is something special in 0.25 or it _just happens_ ;-)

**Comment by korthout** [comment]
@ultraschuppi It occurred yesterday evening AND this morning. These were the only times in at least 30 days.

**Comment by npepinpe** [comment]
Some questions will probably clarify if this is something we should look into or not:

1. What do the logs beforehand tell us about the state of the broker? Had it started? Had it gotten past the Spring Boot part? What's the last startup step it performed?
1. If you look at the Spring Boot code, why would this exception be thrown?

From these, what would be a fair conclusion? Should we investigate this further or not?

**Comment by korthout** [comment]
@npepinpe I've taken a further look into this:

1. The broker had fully started (all 14 steps), event filters for exporters had just been set and then Spring info logs:
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2. The javadoc for `java.lang.Runtime.addShutdownHook` states:

> ```
> @throws  IllegalStateException
>      *          If the virtual machine is already in the process
>      *          of shutting down
> ```

However, the logs don't show any info about a shutdown prior to the exception

<img width="1474" alt="Screenshot 2020-11-04 at 13 56 23" src="https://user-images.githubusercontent.com/3511026/98114424-88e3ce00-1ea5-11eb-9101-9118dee01f87.png">

Looking at the E2E tests code it shows that it audits deleting the cluster and that happens relatively quickly.
<img width="1687" alt="screenshot_2020-11-03_at_15 27 30" src="https://user-images.githubusercontent.com/3511026/98133516-fb60a800-1ebd-11eb-8ed4-9548ae747ca3.png">

**Comment by npepinpe** [comment]
So what's your recommendation for dealing with this issue? Should we close it? If we wanted to work on it, what's the expected outcome?

**Comment by korthout** [comment]
I have no good recommendation. I think the issue is caused by the test itself, but I don't know how to validate it.

**Comment by korthout** [comment]
I see no reason for this to be a Zeebe issue. The contract is clear about the situation. The JVM is shutting down.

**Comment by npepinpe** [comment]
Then please close the issue - thanks for looking into it :slightly_smiling_face:

**Comment by korthout** [comment]
@npepinpe I've been thinking about this a bit more, and we actually still try to shutdown gracefully when we can't add the shutdown hook because of already shutting down. https://github.com/zeebe-io/zeebe/blob/6956b2c4b84740892a27f2265dcb43571ed2e9e3/dist/src/main/java/io/zeebe/broker/StandaloneBroker.java#L59
Something like:
```java
  try {
    getRuntime()
        .addShutdownHook(
            new Thread("Broker close Thread") {
              @Override
              public void run() {
                tryGracefulShutdown();
              }
            });
  } catch (IllegalStateException e) {
    // jvm already shutting down
    tryGracefulShutdown();
  } 
```
WDYT? Would this be useful?
