### ISSUE TITLE
StandaloneBroker performs better then distro

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#580]
It seems that the StandaloneBroker performs better then the distro in the performance tests. 

It seems that the problem lies in the configuration file.

**Comment by Zelldon** [comment]
The old perfs:

![old-test-create-task-throughput](https://user-images.githubusercontent.com/2758593/33433280-43ea1766-d5db-11e7-9022-02344dc9e0fd.png)
![old-test-start-wf-instance-throughput](https://user-images.githubusercontent.com/2758593/33433281-441c6950-d5db-11e7-86bc-6df86929841f.png)

The new:

![new-test-create-task-throughput](https://user-images.githubusercontent.com/2758593/33433278-43a11b24-d5db-11e7-9869-4c21050d0521.png)
![new-test-start-wf-instance-throughput](https://user-images.githubusercontent.com/2758593/33433279-43c414f8-d5db-11e7-96b9-ea8f26eef4aa.png)

Made a huge difference, we should keep the configs up to date.

**Comment by menski** [comment]
@saig0 I will take over this issue as I want to look a little bit deeper in the behavior of the broker on the server

**Comment by menski** [comment]
I reverted the changes to the `numberOfThreads` and `maxIdleTimeMs` options. We should not limit the threads in the distribution per default to 2. The issue we see in the performance tests is that we run the actor scheduler with 11 threads (12cores - 1). This leads to the case that most threads are just idling, which uses the `BackoffIdleStrategy` and therefore limits the throughput. 

If we use the `BusySpinIdleStrategy` instead on the server we reach similar or even higher throughput in the performance tests.

![test-create-task-throughput](https://user-images.githubusercontent.com/516296/33611126-9f9a1714-d9cd-11e7-8f50-9c50a9e58058.png)

![test-start-wf-instance-throughput](https://user-images.githubusercontent.com/516296/33611134-a47306c4-d9cd-11e7-88bd-258f56ef4424.png)

**Comment by menski** [comment]
To recap the actual issue we see on the server is that the performance test does not create enough load on the broker to keep 11 threads busy. And therefor the threads end up in the idle strategy sleep period which leads to a lower throughput. To address this I did the following changes (https://github.com/zeebe-io/zeebe/commit/854017104fdfc886b78ce02be3dee423b98c430a):
- increase the `BackoffIdleStrategy` `maxSpins` and `maxYields` values to 10.000 from 1.000 resp. 100 before, this should create a larger time period before the idle strategy starts to sleep
- increase the warm up request rate to 30.000req/s from 1.000req/s, this should prevent the broker from being idle in the sleep phase after the warm up periode

This leads to better numbers in the performance tests and should not dramatically increase the idle load of the broker in production systems.
