### ISSUE TITLE
RocksDB Log file seems to grow unlimited

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5810]
**Describe the bug**

[Reported by an user in slack](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1605086440397500?thread_ts=1603343832.203000&cid=C6WGNHV2A):

> Abhishek Oct 22nd at 07:17
> Hi Team,
> I am using zeebe 0.24.2 helm chart (standlone gateway and 1 broker configuration) setup
> PVC Disk size = 10 gb , Current Disk usage ~ 80%
> Is it ok delete old snapshots manually from PVC disk, will it corrupt the data from disk ?
>  2.  Or is there any configuration/lifecycle policy available to  manage lifecycle of old snapshots, I dont have to keep on monitoring disk usage for zeebe ?

> zell:house_with_garden:  20 days ago
> Several questions regarding this.
> How many partition do you have?
> Which old snapshots do you mean? There should only one snapshot per partition. Zeebe will take care of cleaning up, you should not do that.
> In general how does you configuration look like?
> You can decrease the snapshot interval to trigger compacting more often.
> Why is the disk so small?
> Why not using the latest patch release?

> Abhishek  20 days ago
> Following are the configuration values (satndalone gateway and 1 broker and 2 exporters enabled - hazelcast and elasticsearch)
> ```
> clusterSize: "1"
> partitionCount: "1"
> replicationFactor: "1"
> cpuThreadCount: "2"
> ioThreadCount: "2"
> resources: 
>   requests:
>     cpu: 500m
>     memory: 2Gi
>   limits:
>     cpu: 1000m
>     memory: 4Gi
> ```
> By old snapshots I meant the .sst files in this location /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/7820099-10-1603353704805  I thought that maybe these snapshots are using up my disk space
> So to check actual usage I ran ncdu /  command and my zeebe broker container exited as it went Outof memory while proccessing this command, and when the new container started again on kubernetes it was using only ~5% disk space but all my deployed workflows were intact.
> as you can see in the attached screenshot the usage dropped from 78% to 5% after the container restart
> So wanted to ask whether zeebe was saving some temp data on PVC disk which was growing day by day like logs ?
![image (2)](https://user-images.githubusercontent.com/2758593/98800598-ebdae500-2410-11eb-91ef-bcf7037523dc.png)

> zell:house_with_garden:  19 days ago
> @Abhishek please never delete these .sst files, these are part of our internal state (RocksDB). If you would delete one of them it would probably cause an inconsistent state.
> So to check actual usage I ran ncdu /  command and my zeebe broker container exited as it went Outof memory while proccessing this command, and when the new container started again on kubernetes it was using only ~5% disk space but all my deployed workflows were intact.
> That sounds weird. But you don't know what else used much space there? Is another pod/container using this PVC?
>  So wanted to ask whether zeebe was saving some temp data on PVC disk which was growing day by day like logs ?
> No. (edited) 
> 
> Abhishek  19 days ago
> That sounds weird. But you don't know what else used much space there? Is another pod/container using this PVC?
> Yes even I was shocked that how it could delete so much data just on a container restart and still have all workflows intact afterwards.
> No other pod/container is using that PVC. Also could not figure out what was using this much space...will keep monitoring from now onwards and let you know if I get any insights.
> Thanks @zell
> 
> zell:house_with_garden:  19 days ago
> Thanks @Abhishek :+1:

> Abhishek  1 hour ago
> From the time we had our last conversation ie. within 19 days ...the PVC disk usage by zeebe broker (total size -10gb) has grown from 5% to 97%
> (Refer screenshot 6)
> Also this time I was able to find out which directory/file  is using so much space
> When I executed
> cd /usr/local/zeebe/data
> ncdu /raft-partition
> I got to know that this directory is occupying 9 Gb of my disk space
> And as per our previous conversation I had shared one observation that after container restart this much space gets free....So I know I can easily restart the container to gain the free space again ...but can you please tell me how important is this(refer screenshot 4) LOG which is almost 8.7 GB and can it be deleted to free disk space
> Scrrenshot (1-4) : Showing space occupied by directories and files in raft-partition directory
> Screenshot 5 : Zeebe Disk usage for last 12 hours
> Screenshot 6 : Zeebe Disk usage for last 15 days
![zee1pvc](https://user-images.githubusercontent.com/2758593/98800690-07de8680-2411-11eb-8f80-e24c2ac36d89.png)
![zee2pvc](https://user-images.githubusercontent.com/2758593/98800692-08771d00-2411-11eb-8071-b9761dbeb78a.png)
![zee3pvc](https://user-images.githubusercontent.com/2758593/98800695-08771d00-2411-11eb-96b0-366af7fb6f9b.png)
![zee4pvc](https://user-images.githubusercontent.com/2758593/98800696-08771d00-2411-11eb-9c29-b32319e035b2.png)
![image](https://user-images.githubusercontent.com/2758593/98800709-0ca33a80-2411-11eb-8d3a-7d62297ae117.png)
![image (1)](https://user-images.githubusercontent.com/2758593/98800712-0ca33a80-2411-11eb-9d6e-d6bae65f8970.png)

**To Reproduce**
Run brokers not on preemtable nodes.

**Expected behavior**
Rolling log file.

**Environment:**
 - OS: k8
 - Zeebe Version: 0.24.2
 - Configuration: helm

**Comment by npepinpe** [comment]
iirc this is a simple setting in RocksDB to configure the log file size and the rolling behaviour. What I'm not sure of is how we would even test this, but the fix itself I think is quite simple.

**Comment by npepinpe** [comment]
Expected settings to fix this:

```java
DBOptions options = new DBOptions();
// keep 1 hour of logs - completely arbitrary. we should keep what we think would be a good balance 
// between useful for performance and small for replication
options.setLogFileTimeToRoll(Duration.ofMinutes(30).toSeconds()).setKeepLogFileNum(2);
```

**Comment by Zelldon** [comment]
Do we need this log file at all in production? Currently we not really consume it only for development afaik. But might be interesting on incidents idk :shrug:
