### ISSUE TITLE
zeebe Log time

### ISSUE THREAD

**Issue by molilanxi** [zeebe-io/zeebe#5815]
zeebe log time is UTC，I want to change to CST

**Comment by Zelldon** [comment]
Please elaborate on this. Why do you want this what is the use case? What are the alternatives and why they are not working for you? About which log we talking about ? The log where the data (records) is stored? Or the log where we write log statements via log4j (debug, warning and error logs)?

**Comment by Zelldon** [comment]
Closed due to inactivity
