### ISSUE TITLE
BufferedLogStreamReader#ensureRemainingBufferCapacity closes buffer to early and does not update reference

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#584]
The method should ensure that the direct buffer has enough capacity to read the next logged event.

Problem:

1. If a new direct buffer is allocated the old one is closed before the copying happens, which means the OS claims the memory and writes new stuff into the location -> We copy from the already freed memory location and this means we copy wrong data. Next time we read the fragmentlength it can happen that the length is negative or really large for example 2 million. In that case the code tries to allocate a buffer, which can store 2 million bytes, an out of memory exception will be thrown.

2. The pointer to the current logged event wraps an unsafe buffer which wrap's the `ioBuffer`. If we allocate a new direct byte buffer the ioBuffer is overwriten, but the unsafe buffer wrap's still the old buffer. This means the current logged event uses wrong data. Like on point 1 it can happen that the fragmentLength is negative or really large!

We have to fix this AND should write better and more unit tests to avoid such bug's.

**Comment by menski** [comment]
should be fixed with refactoring from #592
