### ISSUE TITLE
Fix editorconfig

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5842]
The `.editorconfig` file contains a declaration that is syntactically incorrect:

`[*.dsl,*.groovy,Jenkinsfile*]`

It is not possible to enumerate globs like this.

Either there is a different way to enumerate them, or this section needs to be split up in three sections.

The more delicate part is then in applying the new formatting.

VS Code was the most pleasant tool to do that, because when indenting the top level element it will also adjust indentation for child elements at the same time. This is probably done best while there are no open PRs for the Jenkinsfile

**Comment by npepinpe** [comment]
This was actually done in another PR, though I was unaware of this issue. The fix was to enumerate as `[{*.dsl,*.groovy,Jenkinsfile*}]`
