### ISSUE TITLE
The following error occurred while running and all handlers are unavailable

### ISSUE THREAD

**Issue by power522** [zeebe-io/zeebe#5859]
![image](https://user-images.githubusercontent.com/38269154/99339728-a4959e00-28c1-11eb-88e6-545eb1088624.png)

**Comment by pihme** [comment]
@power522 Could you please provide details on:
Which version of Zeebe?
What was your setup (how many brokers, partitions, replication facotr?, did you use a standalone gateway?)

**Comment by power522** [comment]
> @power522 Could you please provide details on:
> Which version of Zeebe?
> What was your setup (how many brokers, partitions, replication facotr?, did you use a standalone gateway?)

Zeebe version is 0.23.4,3 Broker, attached to the configuration file, is there any problem with my configuration?
The start command is “nohup sh bin/broker &”

```
zeebe:
  broker:
    gateway:
      enable: true
    network:
      host: 10.70.7.27
    cluster:
      nodeId: 0
      partitionsCount: 3
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [10.70.7.28:26502,10.70.7.29:26502]
    threads:
      cpuThreadCount: 10
      ioThreadCount: 10
    exporters:
      elasticsearch:
      # Elasticsearch Exporter ----------
      # An example configuration for the elasticsearch exporter:
      #
      # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_..."
      #
      
        className: io.zeebe.exporter.ElasticsearchExporter
     
        args:
          url: http://10.70.7.27:9200
     
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
     
          # authentication:
          # username: elastic
          # password: changeme
     
          index:
            prefix: zeebe-record
            createTemplate: true
     
            command: false
            event: true
            rejection: false
     
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: false
            messageSubscription: false
            variable: false
            variableDocument: false
            workflowInstance: false
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
     
            ignoreVariablesAbove: 32677
```

**Comment by power522** [comment]
> > @power522 Could you please provide details on:
> > Which version of Zeebe?
> > What was your setup (how many brokers, partitions, replication facotr?, did you use a standalone gateway?)
> 
> Zeebe version is 0.23.4,3 Broker, attached to the configuration file, is there any problem with my configuration?
> The start command is “nohup sh bin/broker &”
> 
> ```
> zeebe:
>   broker:
>     gateway:
>       enable: true
>     network:
>       host: 10.70.7.27
>     cluster:
>       nodeId: 0
>       partitionsCount: 3
>       replicationFactor: 3
>       clusterSize: 3
>       initialContactPoints: [10.70.7.28:26502,10.70.7.29:26502]
>     threads:
>       cpuThreadCount: 10
>       ioThreadCount: 10
>     exporters:
>       elasticsearch:
>       # Elasticsearch Exporter ----------
>       # An example configuration for the elasticsearch exporter:
>       #
>       # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_..."
>       #
>       
>         className: io.zeebe.exporter.ElasticsearchExporter
>      
>         args:
>           url: http://10.70.7.27:9200
>      
>           bulk:
>             delay: 5
>             size: 1000
>             memoryLimit: 10485760
>      
>           # authentication:
>           # username: elastic
>           # password: changeme
>      
>           index:
>             prefix: zeebe-record
>             createTemplate: true
>      
>             command: false
>             event: true
>             rejection: false
>      
>             deployment: true
>             error: true
>             incident: true
>             job: true
>             jobBatch: false
>             message: false
>             messageSubscription: false
>             variable: false
>             variableDocument: false
>             workflowInstance: false
>             workflowInstanceCreation: false
>             workflowInstanceSubscription: false
>      
>             ignoreVariablesAbove: 32677
> ```

**Comment by Zelldon** [comment]
Hey @power522 thanks for raising this. This exception is logged if the client goes away, e.g. if he was shutdown while it has an long polling connection. We have fixed that for example with https://github.com/zeebe-io/zeebe/pull/5524. Please update to a newer version of zeebe. I will close this for now.
