### ISSUE TITLE
ResetState: No case for Member type BOOTSTRAP

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5860]
**Describe the bug**
Found in error logs on production

https://console.cloud.google.com/errors/CK6E2NXBnJHVzgE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Log/Stacktrace**
Report location resetState (RaftMemberContext.java:86)  

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.23.6 
 - Configuration: Camunda Cloud

**Comment by pihme** [comment]
Probably related to old BOOTSTRAP Raft thingy

**Comment by npepinpe** [comment]
You can ignore this, this is related to the update test we were doing and I was doing evil things in the cluster (e.g. deleting files). I should have mentioned this might happened, sorry :see_no_evil:
