### ISSUE TITLE
Could we support an observe request

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5867]
Not sure whether it is a feature request or just a question, but in the morning I had an idea I want to explain here.

**Is your feature request related to a problem? Please describe.**

We currently have the issue that Zeebe is kind of a black box you put things in, which might trigger specific other things but what actually is happening you don't know. To get knowledge about that you need to deploy an exporter, which needs to be done on zeebe deployment. This is kind of meh since it doesn't allow ad-hoc listing for specific things. Furthermore we only support **officially** only the elastic exporter. For some use cases the hazelcast exporter is quite interesting, to trigger other stuffs on incidents or errors for example.

**Describe the solution you'd like**

I would like to have a supported ad-hoc solution, like an observe request for an workflow instance.

**Possible solution:**
The StreamProcessor sends always in the processing all records via side effects to a specific topic per partition. _This could also be done by an specific exporter by the way._ The gateway subscribes to all topics and buffers the last `X` incoming records.

The idea is that the client sends for example a create workflow instance and observe request, similar to `withResult`

```java
  client.observeNewWorkflowInstance()....
```
Or he can send a single observe request for a specific workflow instance.

```java
  client.observeExistingWorkflowInstance(key)
```

We then use the streaming techniques of grpc to stream the records to the client. The gateway will stream then all records which are related to the workflow instance to the client. 

The buffer in the gateway makes it possible that we can also send the observe request a bit later and that leader changes are not that problematic. Restarts of gateway might lose some data, but I would not say that we search for a total reliable solutions as first. For that we could use the exporters.

**Describe alternatives you've considered**

 * We could support officially the hazelcast exporter
 * We could make it possible to hot deploy exporters

**Additional context**

Happy to discuss this and hear your thoughts.

**Comment by npepinpe** [comment]
My main concern would be the overhead of maintaining connections, serializing the records, and sending them back across the wire, and how that would impact leader processing.

So ideally we are exporting hopefully to only one place, and from there this is fanned out to multiple consumers. With Elastic 8 (or 9?), for example, you can stream data out over multiple indices. But I agree that Elastic is maybe too heavy...Honestly I would like to explore the idea of exporting to file, and having exporters pick it up from there. So you can use inotify or something to watch for new files and ingest them, you can extend it to export to GCS or S3 and use cloud events/kinesis/sqs/lambda to ingest them, etc. That's lightweight, hopefully simple, and very portable, and multiple consumers can just read from it.

I guess my point is, I want to reduce how much Zeebe is doing, not add more things it needs to do/manage :sweat_smile:  I think that was one of the goals of zeeqs? 

Ideally, Zeebe should be hyperfocused on the engine and processing the records, so we should have as few exporters as possible. For example, we could decouple the data storage from the engine, and then both the engine and the exporter would be consumers of that (with the engine also being a producer). The data storage service could then be optimized to handle multiple consumers efficiently (with a QoS probably), and Zeebe itself can focus on optimizing processing. But that's probably out of scope here :sweat_smile:

**Comment by Zelldon** [comment]
Yeah I have the feeling the current solution is just not ideal, especially with camunda cloud. We have no access to elastic nor we show enough details in operate, which makes the life unnecessary hard.

**Comment by npepinpe** [comment]
This was brought up in a stakeholder meeting, and product is aware this is a popular feature request, but our focus just isn't on it now. 

If that's alright with you, I'll close this for now. I'd be happy to consider a proposal for a more lightweight embedded exporter to help us and exporter authors test more easily though, something that could be used like RecordingExporter but with an external instance. It probably makes more sense in another issue however, and I doubt it would ever go in Cloud, so here the gain would be for testability.

**Comment by npepinpe** [comment]
I thought about it yesterday, and I think we can just flip it around - add a gRPC exporter where the external system is the server, and the clients are the exporter instances. 

Protocol could be like:

```protobuf
message UniqueId {
  uint32 partitionId = 1;
  uint64 position = 2;
}

message JsonRecord {
  UniqueId id = 1;
  bytes jsonRecord = 2;
}

message Ack {
  UniqueId id = 1;
}

service Importer {
  rpc Exporter(stream JsonRecord) returns (stream Ack);
}
```

Each instance can keep a bidi stream which exports records to a server, and the server responds with acks. We have to deal with the stream possibly dying (i.e. very low load), which adds some complexity, so maybe we could start with batching I guess, which is probably simpler.

Example:

- On open create a stub for the endpoint.
- On export, if there is no ongoing stream, create a stream
- Send record via the stream and add it to an unacknowledged queue
- On ack, update the controller based on this and remove records with IDs lower than the ack
- On any error, propagate the error and recreate the stream (and retry unacknowledged records)

This means it's really easy to put in front of any ingestion service, whether you want to pipe it to redis or just put it in an in-memory queue or even just output it.

You can also use the IPC transport if you're in the same transport, or you can use Unix domain socket as transport - so if you run it with a container, you can just mount a file over which the server/client should communicate and avoid having to deal with ports.

**Comment by Zelldon** [comment]
The last part I'm not sure whether I get, but in general I like the idea of the grpc exporting and having a server, so we could also resource our protobuf protocol right? https://github.com/zeebe-io/zeebe-exporter-protobuf

**Comment by npepinpe** [comment]
The last part is to make it easier to use with something like TestContainers. If you start the server locally, you need to somehow tell your container it can access it - it's a little more complicated if you use IPs as you either need to pick the right network driver, or you need to know the IP of your localhost for the Docker specific virtual interface as seen by the container.

But if you use Unix domain sockets, you can just mount a file to your container, and tell the client to use that for transport (you use an `EpollDomainSocketChannel` instead of an `EpollSocketChannel`), and on your server the same, and they talk over that. No need to fiddle with ports or IPs.

Regarding the protocol, we could, but we'd still need to add either the service definition to it, or have an additional proto which defines the service and just reuses the protocol's messages.
