### ISSUE TITLE
Increase SBE varDataEncoding length type to uint32

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#587]
At the moment we use `uint16` as type for the length filed of the SBE `varDataEncoding` type. This limits the maximal payload of all command to ~65kB. With regard to workflow deployments this limit is often reached by more complex processes e.g. a simple process with 40 tasks and input output mappings is already 53kB. Furthermore it is possible that a deployment command contains multiple workflow definition resources.

To allow bigger deployments we will switch to `uint32` for the `varDataEncoding` in all SBE definitions.

TODO: check also other protocol layers if there are any length types which limit the size of commands to uint16.

**Comment by StephenOTT** [comment]
👍🏻
