### ISSUE TITLE
Split update-tests from integration-tests to a different Jenkins agent in the CI pipeline

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5873]
**Description**

Both the update tests and the integration tests modules make heavy use of resources and ad hoc containers. To avoid port collisions and resource usage contention, we should split them up as we did for the integration tests from the rest of the pipeline in this PR https://github.com/zeebe-io/zeebe/pull/5735.

The assumption is that this will reduce the flakiness of our tests as well.

**Comment by cmur2** [comment]
@npepinpe it might be worth basing your work on https://github.com/zeebe-io/zeebe/pull/5876 to profit from refactorings early :)
