### ISSUE TITLE
typo in grpc_status_invalid_argument

### ISSUE THREAD

**Issue by vtexier** [zeebe-io/zeebe#5875]
**Description**

https://docs.zeebe.io/reference/grpc.html#grpc_status_invalid_argument

```
Returned if:
    ...
    amount is less than 1
```
should be:
```
Returned if:
    ...
    maxJobsToActivate is less than 1
```

**Comment by haardikdharma10** [comment]
Can I take up this? :)

**Comment by Zelldon** [comment]
@haardikdharma10 go for it :)

**Comment by npepinpe** [comment]
This has moved repositories, though the issue remains. I'll reopen it in the other repo.
