### ISSUE TITLE
Broker should purge stale subscriptions

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#588]
There should be a global timeout for subscriptions after which a broker terminates a subscription if there was no interaction. Similar to what a database does with a connection.

Why is this useful?

* It may happen that a client opens a subscription but does not manage to close it (e.g. the close request fails). It should not be the client's responsibility to ensure an eventually clean broker state.

**Comment by menski** [comment]
Topic subscriptions are no longer supported
