### ISSUE TITLE
MetricsExporter leaks memory

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5882]
**Describe the bug**

Looks like the map that records the workflow instances and its time is not cleared once the workflow instance is completed. 

Heap dump from a broker with MetricsExporter enabled: 

![image](https://user-images.githubusercontent.com/1997478/99775023-e8c9ae00-2b0e-11eb-936e-3c4d82c70237.png)

![image](https://user-images.githubusercontent.com/1997478/99775301-5c6bbb00-2b0f-11eb-8132-8fda40cfc090.png)
![image](https://user-images.githubusercontent.com/1997478/99775339-6beb0400-2b0f-11eb-9ac6-f1ffc630a882.png)

**Comment by deepthidevaki** [comment]
Broker with MetricsExporter enabled:

![image](https://user-images.githubusercontent.com/1997478/99776595-5971ca00-2b11-11eb-88c0-acdbb8441701.png)


Broker with out MetricsExporter

![image](https://user-images.githubusercontent.com/1997478/99776494-36dfb100-2b11-11eb-93a6-6a1235b6f621.png)

**Comment by npepinpe** [comment]
Good catch

**Comment by Zelldon** [comment]
Weird we have a clean up job which should do this https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/exporter/metrics/MetricsExporter.java#L119-L128

**Comment by npepinpe** [comment]
I think schedule task is not reoccurring - it seems we never reschedule the task?

**Comment by Zelldon** [comment]
lol

**Comment by npepinpe** [comment]
As we're running this in production, and we've upgraded all clusters now to versions which support it, we should fix and patch it as it will definitely end up affecting heavy users.

**Comment by Zelldon** [comment]
I will fix it

**Comment by Zelldon** [comment]
Thanks @deepthidevaki for finding it :+1:
