### ISSUE TITLE
Zeebe on Kubernetes deployment is based on Helm v2 which is end-of-life

### ISSUE THREAD

**Issue by daghb** [zeebe-io/zeebe#5883]
Official deployment docs tell us to use Helm, but the Helm scripts are v2, which is EOL. Please update Helm projects to v3.

**Comment by npepinpe** [comment]
Hi @daghb! The Zeebe docs recommend that you deploy Zeebe using Kubernetes, and we provide examples to do so which include Helm charts. As our docs say,

> There are many ways that you can provision and configure a Kubernetes cluster. And there are a number of architectural choices you need to make: will your workers run in the Kubernetes cluster or external to it?
> You will need to configure your Kubernetes cluster and modify this to suit the architecture you are building.

So Helm is one way of deploying it. If you're using the [Helm charts](https://github.com/zeebe-io/zeebe-cluster-helm), then I would recommend opening an issue on that repository - it's a community project maintained by the Zeebe community (with contributions from the core team), but it isn't part of the official project.

**Comment by npepinpe** [comment]
I see you opened an issue on the Helm repo - if that's alright with you, then I'll close this one here :slightly_smiling_face:
