### ISSUE TITLE
I can create a filtered topic subscription

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#589]
When a client creates a topic subscription, it can supply an event filter to restrict the types of events it subscribes to. This reduces client-side complexity of event handling and the amount of data transferred.

Use cases:

* a task list may only require TASK events
* a subscriber may not care for commands but only for the corresponding effects (i.e. filter out CREATE but keep CREATED) - via @zambrovski

**Comment by menski** [comment]
Topic subscriptions are no longer supported
