### ISSUE TITLE
Reactive client for a Zeebe

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5892]
**Is your feature request related to a problem? Please describe.**
As discussed in the https://github.com/zeebe-io/spring-zeebe/issues/99#issuecomment-727597543 @salaboy proposed to create a reactive client for Zeebe. 

**Describe the solution you'd like**
I think that this should be at least another interface with reactive implementations of the Zeebe client. I think that a new Maven module will suit better.

**Describe alternatives you've considered**
I think, that we could try to reuse the current client as much as possible. For example, converting from `ZeebeClientFutureImpl` to the `Mono`, `Flux`.

**Comment by npepinpe** [comment]
Hi @aivinog1, this sounds like a nice project, but not something we would want to maintain in the near future - as you can imagine from our back log, we're already quite busy :slightly_smiling_face: 

I would propose you create a new community project for this (maybe ask the community as well if they want to chip in)

**Comment by aivinog1** [comment]
@npepinpe Sounds good to me, but I have a question about licensing - can I reuse `io.zeebe:zeebe-gateway-protocol` in such a community project?

**Comment by npepinpe** [comment]
You cannot include the gateway protocol in your project, but any code you derive from it is fine. You can read more in our readme - https://github.com/zeebe-io/zeebe#clarification-on-grpc-code-generation

> The Zeebe Gateway Protocol (API) as published in the gateway-protocol is licensed under the Zeebe Community License 1.0. Using gRPC tooling to generate stubs for the protocol does not constitute creating a derivative work under the Zeebe Community License 1.0 and no licensing restrictions are imposed on the resulting stub code by the Zeebe Community License 1.0.
