### ISSUE TITLE
Subscription cannot be opened for a short time after broker restart without snapshot

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#590]
With #566, opening a subscription involves asking the system partition for the partitions of the desired topic. This request is answered based on the state of a stream processor. When there are no snapshots, it may happen that this stream processor is still in reprocessing and therefore the response does not contain the latest data, in particular it may not contain all topics. Opening the subscription can then fail. This is unexpected from the user's perspective, as they topic was already created before the broker shut down.

**Comment by ThorbenLindhauer** [comment]
Follow-up of #566 where I saw this in `BrokerRecoveryTest` where we immediately after restarting the broker open a subscription. Temporarily solved by retries.

**Comment by menski** [comment]
Topic subscriptions are no longer supported. Job workers are now polling
