### ISSUE TITLE
Java client: Test and handle subscription replenishment failure

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#591]
Subscriptions regularly send replenishment requests to the broker (ACKs or credits) so that the broker provides more events/tasks. This request can fail.

Current behavior:

* Untested
* As far as I can see: Client retries sending the request indefinitely

Expected behavior:

* Treat the exception gracefully, e.g. log it instead of bubbling it up to the actor runner
* Close subscriber immediately or after a couple of repeated failures.

**Comment by menski** [comment]
Topic subscriptions are no longer supported. Job workers are now polling
