### ISSUE TITLE
change the nodepool from the preemptible to the non-preemptible one

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5935]
**Description**

This was discussed, but not yet implemented as part of #5923 

> After discussing with @npepinpe about pipeline stability we realized that the QA stage will take some longer time making this a long-running job so it might be useful to change the nodepool from the preemptible to the non-preemptible one agents-n1-standard-32-netssd-stable (which is a good practice for release jobs and long-running jobs).

> I added a similar feature in #5932 - it boils down to altering the podspec before launching the agent to include different annotations. Not totally sure how to do it with parameters (params.RUN_QA) but I guess they could/should be available when templating the podspec already...

**Comment by npepinpe** [comment]
Let's do it immediately after #5932, as I imagine we'll run into this as soon as we start using it. The longer our builds run, the more likely they are to be aborted, so if we know a build is going to take > 30 minutes we should probably already put them on stable nodes.
