### ISSUE TITLE
Cant cancel workflow instance if child has blacklisted

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5936]
**Describe the bug**

Happened in our release process. One of our call activity instance has been blacklisted, but we can't cancel the root, since the child can't be canceled. Another child can be canceled. Before we were  able to make progress in a parallel call activity btw.

**Root process:**

![root](https://user-images.githubusercontent.com/2758593/100467679-31670580-30d3-11eb-9a30-2aeb8542d6cf.png)

**Blacklisted process:**

![blacklisted](https://user-images.githubusercontent.com/2758593/100467703-3b890400-30d3-11eb-8be3-ccec8fc6f1b7.png)

**Parallel is canceled**

![parallel](https://user-images.githubusercontent.com/2758593/100467741-4d6aa700-30d3-11eb-9b44-97b2b43df014.png)

**To Reproduce**

Have a root process where the child gets blacklisted.

**Expected behavior**

I can cancel all process instances. Or they are automatically deleted.

**Environment:**
 - OS: k8
 - Zeebe Version: 0.25.0
 - Configuration: production s

**Comment by npepinpe** [comment]
Let's close this in favour of https://github.com/zeebe-io/zeebe/issues/5121
