### ISSUE TITLE
Refine/refactor StreamProcessIntegration/Controller tests

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#594]
Currently the tests are hard to read and to understand. It should be possible to refactor them so it is easier to understand what is happening and also that it is easier to change them, if something in the implementation has changed. 

We should also try to remove most of the mocking, so the real implementation is tested and we do not create new bugs with mocking implementations (like MockLogStreamReader).

**Comment by menski** [comment]
@Zelldon did we improved here in the latest test refactoring or is that still the case?

**Comment by Zelldon** [comment]
Yeah I think is ok
