### ISSUE TITLE
Potential race condition between processing starts and stream processor is paused

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5941]
**Description**

If processing already paused before a StreamProcessor is started, there is a small window in which processing can still happen.

This is how StreamProcessor is paused during it is started.
```
 openFuture.onComplete(
        (nothing, err) -> {
          if (err == null) {
            context.setStreamProcessor(streamProcessor);

            if (!context.shouldProcess()) {
              streamProcessor.pauseProcessing();
            }
```

A solution will be to pass the `pause state` in the constructor of StreamProcessor as we did for the exporter in this PR https://github.com/zeebe-io/zeebe/pull/5903 . However, it still should complete reprocessing before it is actually sets its phase to paused.

**Comment by npepinpe** [comment]
Would this be a blocker for automating the roll outs?

**Comment by deepthidevaki** [comment]
Ya. I think so.
