### ISSUE TITLE
Format to json using JSONPB in all zbctl commands

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5975]
**Description**

https://github.com/zeebe-io/zeebe/pull/5943 introduced the --output parameter to the `zbctl status` command, so that output formatting could be switched between `human` (i.e. human readable; default) and `json`. 

This json formatting required the use of JSONPB to format the json due to issues with protobuf (read the original PR for more info). It was chosen not to do this for all existing commands because JSONPB marshals int64 as Go string making this a breaking change. 

This library should be used for json formatting in all other commands.

**Comment by npepinpe** [comment]
Low priority as it doesn't align with our current goal - we needed JSON output for the status for our testbench, but I'm not aware of other commands. However, if you are blocked and need other commands, please tell me and we can review the prio here.

**Comment by korthout** [comment]
@npepinpe Just to add to that, this would resolve issues like https://github.com/zeebe-io/zeebe/issues/5888

**Comment by aivinog1** [comment]
Hi @npepinpe! I think I can take it. But I can't say anything about when I will do this, since Cyberpunk 2077 is out 😅
