### ISSUE TITLE
Re: Broker has stuck during cluster services start phase

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#6001]
**Describe the bug**
This issue has resurfaced again in `0.25.1` (earlier happened as #5307). After a restart, a broker has stuck in `Bootstrap Broker-2 [6/13]: cluster services` phase. It has been stuck there for more than 18 hours, with no signs of getting started.

**To Reproduce**
Not sure. One of the broker just got restarted, and it is not able to come up.

**Expected behavior**
The broker nodes should come up properly, whenever a restart happens.

**Log/Stacktrace**
Attached stacktrace of broker 2, which is stuck in the start phase.

<details><summary>Full Stacktrace</summary>
 <p>

```
2020-12-09 23:57:55.829 [] [main] [36mDEBUG[m io.zeebe.broker.system - Bootstrap Broker-2 [2/13]: membership and replication protocol started in 297 ms
2020-12-09 23:57:55.830 [] [main] [32mINFO [m io.zeebe.broker.system - Bootstrap Broker-2 [3/13]: command api transport
2020-12-09 23:57:56.236 [] [main] [36mDEBUG[m io.zeebe.broker.system - Bound command API to alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26501 
2020-12-09 23:57:56.249 [] [main] [36mDEBUG[m io.zeebe.broker.system - Bootstrap Broker-2 [3/13]: command api transport started in 419 ms
2020-12-09 23:57:56.249 [] [main] [32mINFO [m io.zeebe.broker.system - Bootstrap Broker-2 [4/13]: command api handler
2020-12-09 23:57:56.330 [] [main] [36mDEBUG[m io.zeebe.broker.system - Bootstrap Broker-2 [4/13]: command api handler started in 80 ms
2020-12-09 23:57:56.330 [] [main] [32mINFO [m io.zeebe.broker.system - Bootstrap Broker-2 [5/13]: subscription api
2020-12-09 23:57:56.364 [] [main] [36mDEBUG[m io.zeebe.broker.system - Bootstrap Broker-2 [5/13]: subscription api started in 33 ms
2020-12-09 23:57:56.364 [] [main] [32mINFO [m io.zeebe.broker.system - Bootstrap Broker-2 [6/13]: cluster services
2020-12-09 23:58:47.729 [] [http-nio-0.0.0.0-9600-exec-1] [32mINFO [m org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-12-09 23:58:47.729 [] [http-nio-0.0.0.0-9600-exec-1] [32mINFO [m org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
2020-12-09 23:58:47.738 [] [http-nio-0.0.0.0-9600-exec-1] [32mINFO [m org.springframework.web.servlet.DispatcherServlet - Completed initialization in 9 ms
```

</p>
</details>

**Environment:**
- Zeebe Version: `0.25.1`
- 3 brokers (3 partitions) + 2 standalone gateways

<details><summary>Configuration</summary>
 <p>

```
Starting broker 2 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local",
      "advertisedPort" : 26501,
      "advertisedAddress" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26501",
      "address" : "0.0.0.0:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local",
      "advertisedPort" : 26502,
      "advertisedAddress" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26502",
      "address" : "0.0.0.0:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local",
      "advertisedPort" : 9600,
      "advertisedAddress" : "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:9600",
      "address" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "alpha-zeebe-zeebe-broker-0.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26502", "alpha-zeebe-zeebe-broker-1.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26502", "alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 2,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT2S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "rocksdb" : {
      "columnFamilyOptions" : { }
    },
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK",
    "freeDiskSpaceCommandWatermark" : 790654280,
    "freeDiskSpaceReplicationWatermark" : 263551427
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "***",
        "bulk" : {
          "delay" : 15,
          "size" : 1000
        },
        "authentication" : {
          "username" : "***",
          "password" : "***"
        },
        "index" : {
          "prefix" : "zeebe-alpha",
          "createTemplate" : true,
          "command" : false,
          "event" : true,
          "rejection" : false,
          "deployment" : true,
          "error" : true,
          "incident" : true,
          "job" : true,
          "jobBatch" : false,
          "message" : true,
          "messageSubscription" : true,
          "variable" : true,
          "variableDocument" : true,
          "workflowInstance" : false,
          "workflowInstanceCreation" : true,
          "workflowInstanceSubscription" : true,
          "ignoreVariablesAbove" : 16384
        }
      },
      "external" : false
    },
    "hazelcast" : {
      "jarPath" : "/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar",
      "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args" : {
        "port" : 5701,
        "remoteAddress" : "stg-zeebe-hazelcast.hazelcast.svc.cluster.local:5701",
        "enabledValueTypes" : "DEPLOYMENT,JOB,WORKFLOW_INSTANCE,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION",
        "enabledRecordTypes" : "EVENT",
        "name" : "zeebe-alpha",
        "capacity" : 10000,
        "timeToLiveInSeconds" : 300,
        "format" : "protobuf"
      },
      "external" : true
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT2S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "detectReprocessingInconsistency" : false,
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
```

</p>
</details>

**Additional Info:**
- [Data](https://drive.google.com/file/d/1Gd8DbPFiKTRsUFDRBotPG8dXJchFp63X/view?usp=sharing) from all brokers
<details><summary>Broker 2 data section: du -ch data/</summary>
 <p>

```
16K	data/lost+found
30M	data/raft-partition/partitions/1/snapshots/30500699-99-1606562691563-36331637-36326444
30M	data/raft-partition/partitions/1/snapshots
4.0K	data/raft-partition/partitions/1/pending
30M	data/raft-partition/partitions/1/runtime
314M	data/raft-partition/partitions/1
31M	data/raft-partition/partitions/3/snapshots/50451999-426-1607464366074-83734075-57881626
31M	data/raft-partition/partitions/3/snapshots
4.0K	data/raft-partition/partitions/3/pending
32M	data/raft-partition/partitions/3/runtime
8.0G	data/raft-partition/partitions/3
30M	data/raft-partition/partitions/2/snapshots/46082799-372-1607464485384-82296656-52892952
30M	data/raft-partition/partitions/2/snapshots
4.0K	data/raft-partition/partitions/2/pending
124M	data/raft-partition/partitions/2/runtime
7.1G	data/raft-partition/partitions/2
16G	data/raft-partition/partitions
16G	data/raft-partition
16G	data/
16G	total
```

</p>
</details>

Related issues: #5135, #5307, #5425

**Comment by npepinpe** [comment]
Strange that partition 2 and 3 have such a bigger log size. Do you have logs from your brokers saying that no snapshot will be taken because the position hasn't changed?

Though even with 8gb per partition I wouldn't expect it to take 18 hours.

**Comment by deepthidevaki** [comment]
If the node is still stuck on the start phase, could you please set the log level of `io.atomix` to "debug"? More detailed log would helps us to investigate it. You can change it dynamically https://docs.zeebe.io/operations/configuration.html#change-log-level-dynamically.

**Comment by strawhat5** [comment]
>Do you have logs from your brokers saying that no snapshot will be taken because the position hasn't changed?

@npepinpe AFAICS from the logs, snapshots are happening regularly.
```
2020-12-11 09:10:51.006 [Broker-1-DeletionService-3] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 56122699
2020-12-11 09:10:51.006 [Broker-1-SnapshotDirector-3] [Broker-1-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - New snapshot 56122699-642-1607677849309-91074968-63959410 was persisted. Start replicating.
2020-12-11 09:10:53.273 [Broker-1-SnapshotDirector-3] [Broker-1-zb-fs-workers-0] DEBUG io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore - Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/56122699-642-1607677849309-91074968-63959410, metadata=FileBasedSnapshotMetadata{index=56122699, term=642, timestamp=2020-12-11 09:10:49,309, processedPosition=91074968, exporterPosition=63959410}}
2020-12-11 09:10:53.274 [Broker-1-SnapshotDirector-3] [Broker-1-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Current commit position 91074995 is greater than 91074995, snapshot 56122699-642-1607677849309-91074968-63959410 is valid and has been persisted.
```

>could you please set the log level of io.atomix to "debug"?

@deepthidevaki the curl command returns `404`. I have tried both POST and GET request for loggers. I can change it through the logger config and restart the broker, but the broker might start successfully and we may miss this issue.
```
# curl 'http://localhost:9600/actuator/loggers/io.atomix' -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel":"debug"}'
HTTP/1.1 404 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Disposition: inline;filename=f.txt
Content-Type: application/json
Transfer-Encoding: chunked
Date: Fri, 11 Dec 2020 09:07:03 GMT

{"timestamp":"2020-12-11T09:07:03.775+00:00","status":404,"error":"Not Found","message":"","path":"/actuator/loggers/io.atomix"}
```

**Comment by deepthidevaki** [comment]
@strawhat5 Probably the endpoints are not enabled. Are you able to access `curl http://localhost:9600/actuator`? Does it show the logger endpoint? Note that you have to provide the url of the broker.

This is what I get with default config: `curl http://localhost:9600/actuator | json_pp`
```
{
   "_links" : {
      "health" : {
         "href" : "http://localhost:9600/actuator/health",
         "templated" : false
      },
      "health-path" : {
         "href" : "http://localhost:9600/actuator/health/{*path}",
         "templated" : true
      },
      "loggers" : {
         "href" : "http://localhost:9600/actuator/loggers",
         "templated" : false
      },
      "loggers-name" : {
         "href" : "http://localhost:9600/actuator/loggers/{name}",
         "templated" : true
      },
      "partitions" : {
         "href" : "http://localhost:9600/actuator/partitions",
         "templated" : false
      },
      "partitions-operation" : {
         "href" : "http://localhost:9600/actuator/partitions/{operation}",
         "templated" : true
      },
      "prometheus" : {
         "href" : "http://localhost:9600/actuator/prometheus",
         "templated" : false
      },
      "self" : {
         "href" : "http://localhost:9600/actuator",
         "templated" : false
      }
   }

```

**Comment by strawhat5** [comment]
Yes the `loggers` endpoint is not enabled. As per [actuator docs](https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#overview-endpoint-urls), all endpoints below `/actuator` should be enabled by default. Weird that it is not enabled. Any way to enable it without restarting the broker?

```
# curl http://localhost:9600/actuator          
{
	"_links": {
		"self": {
			"href": "http://localhost:9600/actuator",
			"templated": false
		},
		"health": {
			"href": "http://localhost:9600/actuator/health",
			"templated": false
		},
		"health-path": {
			"href": "http://localhost:9600/actuator/health/{*path}",
			"templated": true
		},
		"info": {
			"href": "http://localhost:9600/actuator/info",
			"templated": false
		}
	}
}
```

**Comment by strawhat5** [comment]
Attaching the logs below. Atomix logs are present in `zbLog2.txt` (which is also the stuck broker).
[zbLog0.txt](https://github.com/zeebe-io/zeebe/files/5684248/zbLog0.txt)
[zbLog1.txt](https://github.com/zeebe-io/zeebe/files/5684249/zbLog1.txt)
[zbLog2.txt](https://github.com/zeebe-io/zeebe/files/5684250/zbLog2.txt)

**Comment by deepthidevaki** [comment]
Thanks @strawhat5.
I don't know how to enable the endpoints without restarting the application. To enabled the loggers endpoint you have to set `management.endpoint.loggers.enabled=true`. It is by default enabled on 0.25.x. But I don't know why it is not available in your deployment. 
How did you change the log level, at the end?

--
I checked the logs of broker-2.

The following logs indicate that partition-1 has started and joined the cluster successfully. 
```
2020-12-13 05:35:56.871 [] [raft-server-2-raft-partition-partition-1] [36mDEBUG[m io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
2020-12-13 05:35:56.871 [] [raft-server-2-raft-partition-partition-1] [32mINFO [m io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 10707ms
...
020-12-13 05:38:55.118 [] [raft-server-2-raft-partition-partition-1] [36mDEBUG[m io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received AppendRequest{term=611, leader=1, prevLogIndex=30508655, prevLogTerm=611, entries=0, commitIndex=30508655}
2020-12-13 05:38:55.119 [] [raft-server-2-raft-partition-partition-1] [36mDEBUG[m io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Sending AppendResponse{status=OK, term=611, succeeded=true, lastLogIndex=30508655, lastSnapshotIndex=30500699}
```
Partition-1 is also replicating the log, and is up-to-date with the leader.

However partition-2 has not started succesfully, because the leader of partition-2 is not able to communicate with broker 2. The following log indicates that this node has not received any messages from the leader.
```
2020-12-13 05:38:55.450 [] [raft-server-2-raft-partition-partition-2] [32mINFO [m io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-2}{role=FOLLOWER} - No heartbeat from null in the last PT2.568S (calculated from last 2568 ms), sending poll requests
2020-12-13 05:38:55.450 [] [raft-server-2-raft-partition-partition-2] [36mDEBUG[m io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Polling members [DefaultRaftMember{id=0, type=ACTIVE, updated=2020-09-02T05:35:04.028Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-09-02T05:35:04.028Z}]
```
The leader of partition-2 is broker 0. But we don't see any related information in broker 0 logs. Could you please increase the log of broker-0 as well? 
My hypothesis is that it is something to do with the leader having a wrong IP of broker-2. We have seen a similar bug before #5116, but it is already fixed. If it is a similar bug, restarting broker-0 would resolve the issue. However, if you can collect the logs from broker-0, it would help us to root cause this issue.

**Comment by strawhat5** [comment]
>How did you change the log level, at the end?

By updating the configmap and restarting the broker. :)

>Could you please increase the log of broker-0 as well?

It is not possible now, as the broker-2 restarted again few hours back, and this time all broker startup steps completed successfully. But as per your hypothesis, it should have worked only if we restarted broker-0, right?

Also, since #5116 has already been fixed in `0.25.0`, it should not have happened in `0.25.1`. Is it something else?

Attaching logs of all brokers around the time broker-2 was restarted. Search for logs around `2020-12-14 05:04:4` timestamp.
[ZbLogs.zip](https://github.com/zeebe-io/zeebe/files/5688583/ZbLogs.zip)

**Comment by deepthidevaki** [comment]
> > How did you change the log level, at the end?
> 
> By updating the configmap and restarting the broker. I figured there wouldn't be any other way. :)
> 
:slightly_smiling_face: 
If you haven't already enabled the logging actuator, I would recommend you to enable it. It would be easier to debug transient bugs like this in future.

> > Could you please increase the log of broker-0 as well?
> 
> It is not possible now, as the broker-2 restarted again few hours back, and this time all broker startup steps completed successfully. But as per your hypothesis, it should have worked only if we restarted broker-0, right?
> 
> Also, since #5116 has already been fixed in `0.25.0`, it should not have happened in `0.25.1`. Is it something else?
> 

That bug is fixed in 0.25.0. But the symptoms looks very similar. It is possible that there is some other bug that causes the connection to not reset when the target node is restarted.
It is possible that restarting broker-2 again caused the other nodes to reset their connection so that it can talk to the new pod.

> Attaching logs of all brokers around the time broker-2 was restarted. Search for logs around `2020-12-14 05:04:4` timestamp.
> [ZbLogs.zip](https://github.com/zeebe-io/zeebe/files/5688583/ZbLogs.zip)

From the logs, there was leader change for partition-2 and partition-3 at around 3:22. Broker-1 became leader for parition-2 and broker-0 became leader for partition-3. It also seems that from that point, broker-2 is receiving communication from leaders of all partition. There is no log from broker-2 at that time. But during the restart of broker-2, you see the following logs
```
2020-12-14 04:54:37.406 [] [raft-server-0-raft-partition-partition-3] [33mWARN [m io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-3} - AppendRequest{term=649, leader=0, prevLogIndex=89869645, prevLogTerm=649, entries=0, commitIndex=89869645} to 2 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-append timed out in 5000 milliseconds
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-append timed out in 5000 milliseconds
...
2020-12-14 04:54:37.318 [] [raft-server-1-raft-partition-partition-2] [33mWARN [m io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - AppendRequest{term=564, leader=1, prevLogIndex=89199536, prevLogTerm=564, entries=0, commitIndex=89199536} to 2 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-append timed out in 5000 milliseconds
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-append timed out in 5000 milliseconds
```
This indicates that both leaders were sending messages to broker-2 until its restart. This would mean that broker-2 should have been able to complete its startup after the leader change at 3:22. But I don't have logs from broker-2 after 3:22, so I can't say what really happened.
However my guess is that the leader change that happened in between helped to resolve or hide the bug that caused broker-0 to stuck in start phase.

--
This is a transient bug which is very difficult to debug. If you see this again, I would recommend to increase the log levels using the logging actuators on all brokers (also the healthy ones) and post the log here.

**Comment by strawhat5** [comment]
>This would mean that broker-2 should have been able to complete its startup after the leader change at 3:22. But I don't have logs from broker-2 after 3:22, so I can't say what really happened.

Yeah since broker-2 got restarted around `04:54`, we don't have its logs prior to it.

>This is a transient bug which is very difficult to debug. If you see this again, I would recommend to increase the log levels using the logging actuators on all brokers (also the healthy ones) and post the log here.

Yes I understand, thanks for your help here @deepthidevaki ! 🙂 

>If you haven't already enabled the logging actuator, I would recommend you to enable it. It would be easier to debug transient bugs like this in future.

How do I pass this `management.endpoint.loggers.enabled=true`? I don't see any logger related config in [broker.yaml](https://github.com/zeebe-io/zeebe/blob/0.25.1/dist/src/main/config/broker.standalone.yaml.template). Can I just add it there in yaml format?
```
management:
  endpoint:
    loggers:
      enabled: true
```

**Comment by deepthidevaki** [comment]
> How do I pass this `management.endpoint.loggers.enabled=true`? I don't see any logger related config in [broker.yaml](https://github.com/zeebe-io/zeebe/blob/0.25.1/dist/src/main/config/broker.standalone.yaml.template). Can I just add it there in yaml format?
> 
> ```
> management:
>   endpoint:
>     loggers:
>       enabled: true
> ```

Usually that would be enough. Since but since it was not enabled by default not in your case, you may also have to expose the web endpoint. See https://github.com/zeebe-io/zeebe/blob/10d006c469f8e97b25c390620cc2386e7ad3de53/dist/src/main/resources/application.properties#L4
You can add them in broker.yaml in yaml format.

**Comment by strawhat5** [comment]
Cool thanks! :)

**Comment by deepthidevaki** [comment]
@strawhat5 Can we close this issue? You can reopen when it happens again with the logs.

**Comment by strawhat5** [comment]
Hey yes, we can close it.

**Comment by strawhat5** [comment]
@deepthidevaki I have configured the actuator configs through env variables, still the actuator endpoints does not have `loggers` configured. It didn't work by default nor is it working after explicit configuration. Anything else that I am missing?

```
# curl http://localhost:9600/actuator
{
	"_links": {
		"self": {
			"href": "http://localhost:9600/actuator",
			"templated": false
		},
		"health": {
			"href": "http://localhost:9600/actuator/health",
			"templated": false
		},
		"health-path": {
			"href": "http://localhost:9600/actuator/health/{*path}",
			"templated": true
		},
		"info": {
			"href": "http://localhost:9600/actuator/info",
			"templated": false
		}
	}
}
```

```
env:
  - name: management.endpoint.loggers.enabled
    value: 'true'
  - name: management.endpoints.web.exposure.include
    value: 'health,prometheus,loggers,partitions'
```

**Comment by deepthidevaki** [comment]
The environment variables for these configs are:
MANAGAMENT_ENDPOINT_LOGGERS_ENABLED
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
See [Spring Docs](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding-from-environment-variables)

**Comment by strawhat5** [comment]
Ah yes, my bad. It worked after using the Spring Boot env binding convention. Thanks! :)
