### ISSUE TITLE
Why Zeebe is not production supported on Windows? 

### ISSUE THREAD

**Issue by hatzhang** [zeebe-io/zeebe#6014]
**Description**
As [Install](https://docs.zeebe.io/introduction/install.html) described, on windows either docker or distribution version is not supported for production. Can anyone explain the Why behind this?   Is a linux on Windows Hyper-V or WSL2 good enough for Zeebe production?

**Comment by npepinpe** [comment]
Hi @hatzhang,

Zeebe is officially supported and tested on Kubernetes - meaning with the official Docker image. It may work on Windows (though I/O is usually slower, which is a problem for data intensive applications like Zeebe), but we don't actively test it and therefore can't recommend you run it on production.

The main reason is to reduce the scope of the project - there is already a lot of work, so adding more platforms would only increase our workload. Furthermore, you can run Kubernetes on Windows hosts (see https://azure.microsoft.com/en-us/services/kubernetes-service/), so targeting Kubernetes has the official deployment environment also helps us reduce our workload when it comes to supporting multiple platforms.

Hope this answers your question! I'll leave this open for a week, and close it after unless you have any further questions.

**Comment by hatzhang** [comment]
@npepinpe  Thanks, that really helps!

Let's say if we set up a Zeebe cluster on Windows (whether WSL2 or Hyper-V Linux or Kubernetes on Windows), is there some convenient loadtesting tool recommened to verify  its performance or limits, is there a tool come up with the project designed for this purpose?

**Comment by npepinpe** [comment]
There isn't an official tool exactly, but two devs wrote [a blog post that dives into performance evaluation/tuning of Zeebe](https://zeebe.io/blog/2020/11/zeebe-performance-tool/) which includes a link to the tool they used. It's pretty recent, so you could probably reuse that.

**Comment by hatzhang** [comment]
Thanks. We are going to use Kubernetes for Zeebe.
