### ISSUE TITLE
Add partition id to the log context

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#6015]
When parsing the logs for debugging issues, I often have to filter logs for specific partitions. Currently there is no easy way to filter them. Instead we have to filter for several terms like "partition-1", "StreamProcessor-1", "SnapshotDirector-1" etc. It would be easier if we can filter all logs by just "partition-1" or context.partition=1.

**Comment by Zelldon** [comment]
This is the reason why I introduced once the actorname with node id and partition id etc.

You can use that in the log viewer. 

Click on **view options** on the right side:

![viewoptions](https://user-images.githubusercontent.com/2758593/102191851-448f1900-3eba-11eb-9bd6-b57b50ec425b.png)

Reference the `jsonPayload.context.actor-name`
![viewoptions-actorname](https://user-images.githubusercontent.com/2758593/102191892-52dd3500-3eba-11eb-9e40-e19b0af2a441.png)
Make sure that the limit is unticked.

It looks like this:

![viewoptions-actorname-details](https://user-images.githubusercontent.com/2758593/102191973-6e484000-3eba-11eb-8ff2-515892256f58.png)

Makes it debugging much easier.

You can even filter for the partitions or actor etc.

**Comment by npepinpe** [comment]
Focus on the Actor model - i.e. add partition ID into the context. Maybe add a log context property to actors? To be discussed when we pick this up.

**Comment by Zelldon** [comment]
https://github.com/zeebe-io/zeebe/pull/3634

**Comment by deepthidevaki** [comment]
How do you filter logs from a specific partition?

**Comment by Zelldon** [comment]
For example: 
```
jsonPayload.context."actor-name":"-3"
```

![viewoptions-actorname-partition-3](https://user-images.githubusercontent.com/2758593/102194910-288d7680-3ebe-11eb-86d2-92c2b12c98ac.png)

**Comment by deepthidevaki** [comment]
Cool! But this will also matches with Broker-3*

**Comment by Zelldon** [comment]
Yes but you can exclude it with `resource.labels.pod_name:"zell-kw-47-benchmark-zeebe-0"` for example.

**Comment by Zelldon** [comment]
I just found out you can use regex via 
```
jsonPayload.context."actor-name"=~"-3$"
```

https://cloud.google.com/logging/docs/view/advanced-queries

**Comment by deepthidevaki** [comment]
What if I want to include logs from partition-3 from all nodes - including leaders, followers, old leaders? I don't want to exclude or include any specific brokers. 
Pattern matching actor-name might work with a regular expression.

**Comment by Zelldon** [comment]
Yes see above with `=~3$` it will work.

**Comment by deepthidevaki** [comment]
:+1: I can work with that now. 
Note that there are also partition specific logs from non-actors. Eg:- StateReplication, Raft threads etc.

**Comment by Zelldon** [comment]
You can combine them with `OR` raft logs contains the partition id and StateReplication thread name contains also the partition id :slightly_smiling_face:
