### ISSUE TITLE
Handle INACTIVE partition role in gateway

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#6053]
**Describe the bug**
When a partition fails to recover or goes unhealthy the partition switches to the role `INACTIVE`. The gateway cannot handle the `INACTIVE` role and fails to decode it and show it correctly in the topology.

**To Reproduce**

Break a partition or corrupt a snapshot so the partition cannot recover.

**Expected behavior**

The gateway can handle `INACTIVE` partitions.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
{
  "insertId": "nprv5kyjydx40a283",
  "jsonPayload": {
    "serviceContext": {
      "service": "zeebe",
      "version": "0.25.3"
    },
    "context": {
      "threadName": "Broker-0-zb-actors-0",
      "threadId": 28,
      "loggerName": "io.zeebe.protocol",
      "actor-name": "GatewayTopologyManager",
      "threadPriority": 5
    },
    "message": "Failed to decode broker info, found unknown partition role: INACTIVE",
    "logger": "io.zeebe.protocol",
    "thread": "Broker-0-zb-actors-0"
  },
  "timestamp": "2021-01-04T08:46:45.794372Z",
  "severity": "WARNING",
  "logName": "projects/camunda-cloud-240911/logs/stdout",
  "sourceLocation": {
    "file": "BrokerInfo.java",
    "line": "443",
    "function": "lambda$consumePartitions$1"
  },
  "receiveTimestamp": "2021-01-04T08:46:49.049897806Z"
}
<p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Are there any side effects, or it just logs a warning but nothing else happens? Assumption here is once a new leader is up it would effectively be identified, so it's just that the old leader might not be removed "fast".

**Comment by menski** [comment]
Until now we only saw it in single node clusters, where the SNAPSHOT could not be read on recovery. So I don't know if there are effects as the system is already broken. But the warnings are constantly printed which should be fixed and just handled nicely.

**Comment by denissabramovs** [comment]
This is still not fixed in 1.0.0-alpha2

**Comment by Zelldon** [comment]
Can you elaborate on that @denissabramovs
