### ISSUE TITLE
Can't delete pending snapshot because a *.sst file doesn't exist

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#6060]
**Describe the bug**

A broker failed to write snapshot chunks, because it was already out of disk space. The broker aborted the snapshot replication.
During abort we want to delete the pending snapshot, but this failed because an expected `*.sst` file was not found.

```
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/75111799-932-1609829316698-124358328-124358298-5/064488.sst
at io.zeebe.util.FileUtil.deleteFolder (FileUtil.java:54)
at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.purgePendingSnapshot (FileBasedSnapshotStore.java:314)
at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.purgePendingSnapshots (FileBasedSnapshotStore.java:112)
at io.atomix.raft.roles.PassiveRole.abortPendingSnapshots (PassiveRole.java:418)
at io.atomix.raft.roles.PassiveRole.onInstall (PassiveRole.java:252)
at io.atomix.raft.roles.FollowerRole.onInstall (FollowerRole.java:86)
at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$2 (RaftContext.java:203)
at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19 (RaftContext.java:219)
at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run (SingleThreadContext.java:188)

```

_Error group:_

https://console.cloud.google.com/errors/CJy8u-OqoMDhHA?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

It seems that the file was deleted already by another thread. In the log we can see that raft snapshot replication and normal snapshot replication is ongoing and failed at the same time. [They also try to delete there directory in the same time in different threads. ](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-01-05T06:51:10.576194000Z&dateRangeStart=2021-01-05T05:51:16.729Z&dateRangeEnd=2021-01-05T07:51:16.729Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2213f3c38b-6734-410c-8589-d5f0bdcc38c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22zeebe-2%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-01-05T06:50:46.690746000Z&pinnedLogId=p7q2m0p4p9g025hgd&pinnedLogTimestamp=2021-01-05T06:50:46.729587Z)

Thread `Broker-2-StateReplication-1` fails on `75111799-932-1609829316698-124358328-124358298` 
and deletes `DELETE dir /usr/local/zeebe/data/raft-partition/partitions/1/pending/75111799-932-1609829316698-124358328-124358298-5`

Thread `"raft-server-2-raft-partition-partition-1"` fails on ` Failed to write pending snapshot chunk FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/75110499-917-1609823695212-124356069-124356034-6` and deletes `DELETE dir /usr/local/zeebe/data/raft-partition/partitions/1/pending/75110499-917-1609823695212-124356069-124356034-6`.

Thread `"raft-server-2-raft-partition-partition-1"` reports error on deletion for 
`java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/75111799-932-1609829316698-124358328-124358298-5/064488.sst`, which is weird because it is the other directory. There is some weird concurrency issue.
The problem here is that we have after that an left over snapshot.

**To Reproduce**

Have both replication at the same time and fail them via out of disk.

**Expected behavior**
No concurrency issue.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.25.3
 - Configuration: PROD M

**Comment by npepinpe** [comment]
Wasn't that the reason why we had two folders before? At any rate, should be safe now to just skip `NoSuchFileException` when deleting - I mean, if it doesn't exist, the job is...done?

**Comment by Zelldon** [comment]
I was wondering why it happens in the first place, since we use unique directory and each thread should care about there own snapshot dir. We need to investigate whether we have concurrent access,

**Comment by deepthidevaki** [comment]
This should be fixed by https://github.com/zeebe-io/zeebe/pull/6283
Please reopen if occured again.

**Comment by falko** [comment]
My current customer is seeing the following warnings in 1.0.0-alpha3:
```
[zeebe_broker0 |[0m       io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/7/pending/248571-1-345312-9223372036854775807, snapshotStore=io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore@99dd4f7, metadata=FileBasedSnapshotMetadata{index=248571, term=1, processedPosition=345312, exporterPosition=9223372036854775807}}
[zeebe_broker0 |[0m java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/7/pending/248571-1-345312-9223372036854775807
```

**Comment by deepthidevaki** [comment]
@falko It is probably this issue https://github.com/camunda-cloud/zeebe/issues/6445
