### ISSUE TITLE
Why is the docs/ directory in master, but not develop?

### ISSUE THREAD

**Issue by StevenDas-Tomo** [zeebe-io/zeebe#6069]
**Description**

Hi all,

A potentially silly newcomer question:

I noticed that the `docs/` root-level directory appears to exist in the `master` branch, but not in the `develop` branch:

![image](https://user-images.githubusercontent.com/76065524/103836744-c815d300-503e-11eb-9f70-fe80dafe1ac8.png)

![image](https://user-images.githubusercontent.com/76065524/103836764-d95edf80-503e-11eb-9d6b-e4f23fd4cb2a.png)

How are we suppose to contribute documentation improvements and fixes if `develop` doesn't appear to contain these files?

Thank you in advance for your help!

**Comment by saig0** [comment]
Hi @StevenDas-Tomo,

we're restructuring the docs and moving them to a new repository. 
We will publish the new docs very soon. Stay tuned :rocket:

**Comment by StevenDas-Tomo** [comment]
Thanks for the fast reply, @saig0!
