### ISSUE TITLE
Cancel Instance

### ISSUE THREAD

**Issue by Shifuddin** [zeebe-io/zeebe#607]
I tried to cancel an instance from zeebe sample monitor. But came with the error ..
Error: Command for event with key 8590064784 was rejected by broker (CANCEL_WORKFLOW_INSTANCE_REJECTED)

My question is how can I delete a deployed workflow instance under a topic?

**Comment by menski** [comment]
Did you clicked the button twice? I think the simple monitor will still show the canceled instance on the workflow instance tab. You could check the logs tab if there was a successful `WORKFLOW_INSTANCE_CANCELED` event before the rejected event. Also the state of the workflow instance in the instance tab should be `Ended`.

**Comment by Shifuddin** [comment]
State of the instance is ended. I clicked the button once. But in the log I found two entries. I attached the screen here. 
![workflowinstance](https://user-images.githubusercontent.com/17300321/34667555-cdcd7674-f469-11e7-932d-dff22c614b7b.png)

Also after reloading the instance page I found that instance in the left panel. Shouldn't it be deleted from there?

**Comment by menski** [comment]
The simple monitor is a community project which is in a early stage. At the moment the instance is not removed from the instance view. If the instance state is ended I would assume there is also `WORKFLOW_INSTANCE_CANCELED` event before the events in your screenshot otherwise it should still be running.

**Comment by Shifuddin** [comment]
I didn't found WORKFLOW_INSTANCE_CANCELED event for my workflow instance with key 8590214648.

**Comment by menski** [comment]
Was the instance still running when you canceled it? Or did it completed before? If it was still running could you provide all the workflow instance events from the instance of the log tab?

**Comment by Shifuddin** [comment]
For example, I tried to cancel the instance **21475183288**. The state of the workflow instance was **Ended** when I attempted to cancel this instance. 

Before canceling the instance...
![before_cancellation](https://user-images.githubusercontent.com/17300321/34710550-156964b8-f51c-11e7-94a9-88c9b0b1ca93.png)

After canceling the instance..
![after_cancellation](https://user-images.githubusercontent.com/17300321/34710564-296b07fa-f51c-11e7-8ea6-196546ef9be9.png)

Screen shot from log tab...
![log_screen](https://user-images.githubusercontent.com/17300321/34710595-45cf03ce-f51c-11e7-8b90-5b318fd29de4.png)

**Comment by menski** [comment]
> The state of the workflow instance was Ended when I attempted to cancel this instance.

If the instance is already ended you cannot cancel it. You can only cancel running instances. The UI doesn't hide the cancel button for ended instances at the moment. But it is not a valid action. As you can see in you log tab the instance with key 21475183288 was already completed with the event at position 21475198096. After that a cancel instance is not valid and will be rejected.

**Comment by Shifuddin** [comment]
Thanks for the clarification...

**Comment by menski** [comment]
Thanks for your feedback. I created a ticket to improve the UI https://github.com/zeebe-io/zeebe-simple-monitor/issues/16.

**Comment by DrissiReda** [comment]
Anyway you can cancel an instance through the Go client?
