### ISSUE TITLE
Exclude util and impl packages from Java client public API

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#6087]
**Description**

At the moment, we use clirr to ensure we don't break ABI backwards compatibility of our Java client. However, this checks the whole module, including implementation classes. This adds considerable overhead when working in the client and having to ignore multiple changes when changing implementation classes that aren't meant to be consumed. It also builds a false send of security for users who would be using the implementation classes, when they should rely entirely on the interfaces/API.

I would propose to make it explicit that only the API and root interfaces are public, and `util` and `impl` packages are not, and ignore those packages in our clirr configuration.

To make it clearer what is public and what isn't, please also move `util` under `impl`.

NOTE: this can be achieved by configuring clirr as:

```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>clirr-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>io/zeebe/client/util/**</exclude>
            <exclude>io/zeebe/client/impl/**</exclude>
          </excludes>
        </configuration>
      </plugin>
```

**Comment by aivinog1** [comment]
Hi @npepinpe! I want to take this :)

**Comment by npepinpe** [comment]
Let's add one more things: please move util under the impl package, so we have a clearer separation of what is "public" and what isn't.

I'll create a separate issue to document this.

**Comment by aivinog1** [comment]
@npepinpe I'll start working on it today :)
