### ISSUE TITLE
Improve Gossip tests

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#611]
Currently, the tests of the gossip module require some internal knowledge of the implementation. They have to be refactored to make it easier to understand.

**Comment by Zelldon** [comment]
### Unit tests
  * single components should also tested with unit tests like BufferedEventIterator etc.
  * The past (quite often) has shown that most bug's and problems are located in the iteration and data structure classes.
   We should test them better. -> I wrote tests for the ReusableObjectlist,  this should be done at creation time. Perhaps we need more test for this collection?

### Ping Req and forward Ack
 * With intellij code coverage it seems that some branches are not tested in the AwaitAckState.

### ManualActorScheduler
 * Is it possible that we use the existing scheduler? Why we have to call it sometimes twice?

### Naming

 * Perhaps we can rename the gossip rules. For example gossip1 to ownGossip, this makes
easier to understand. I had some problems and overlooked sometimes the numbers at the end.

**Comment by menski** [comment]
We will replace the gossip module
