### ISSUE TITLE
Update Go version in clients/go

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#6135]
**Description**

Inspired by #6034. So, after Go 1.16 will be released we should update the Go version in the project.

**Comment by npepinpe** [comment]
So you mean the version of Go? I imagine this is a prerequisite for #6034. @MiguelPires do you see any potential blockers to updating our Go version? I vaguely remember we had some issues with updating versions in the past.

Also, if any of you knows, what's the release data for 1.16?

**Comment by aivinog1** [comment]
Yes, I mean the version of Go. As I can see from the milestone: https://github.com/golang/go/milestone/145 due date is 1 February :)

**Comment by MiguelPires** [comment]
I don't see any problems with updating our Go version. Also, I don't think this is documented anywhere but I think our policy was to use the oldest supported version of Go (this is based on my memory of a conversation, so take it with a grain of salt). Right now that's 1.14, so we can already bump our current version. If we keep following the same policy, we would only be updating to 1.16 in August or September.

**Comment by npepinpe** [comment]
Where can I find the supported versions of Go, and for how long they're supported? The release page just lists all of them, and it seems consensus is to try to always use the latest version?

**Comment by MiguelPires** [comment]
Yes, #3881 made sense a year ago but we never got around to it. It should be quick though, so I can do it (update to 1.15) tomorrow

**Comment by aivinog1** [comment]
I'm closing it because https://github.com/zeebe-io/zeebe/pull/6153 is merged.
