### ISSUE TITLE
zeebe-label-action failed.

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#6136]
**Description**

I was notified that Github action: "Add default labels to new issues" was failed on my task: #6135: https://github.com/zeebe-io/zeebe/runs/1727660967?check_suite_focus=true

**Comment by npepinpe** [comment]
Seems to have been a transient error, since it worked for this one ;)

To be honest I'm thinking of removing this label anyway, it's not particularly useful at the moment.
