### ISSUE TITLE
Provide Server Test Suite

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#614]
- [x] There exists an Ansible playbook which installs Zeebe on a server
- [x] There exists an Ansible playbook which starts Zeebe on a server
- [x] There exists an Ansible playbook which stops Zeebe on a server
- [x] There exists a Java test suite which will execute tests from the HQ docker swarm on the Zeebe servers (no embedded broker)
- [x] There exists a Jenkins job for the performance test suite and the long running test suite

**Comment by menski** [comment]
Idea: We can also use this infrastructure to run a Go client IT test suite

**Comment by menski** [comment]
We have to limit the jobs which concurrently use the testbed in Jenkins. A solution could be https://plugins.jenkins.io/throttle-concurrents with a global category which is limited to a single concurrent job.

**Comment by menski** [comment]
@Zelldon for review do not look at all the commits. But I would like to have some feedback on the test suite in https://github.com/zeebe-io/zeebe-cluster-tests as you also worked heavily on the old test suites. If I should explain you some stuff, e.g. related to ansible, just approach me. I'm happy to explain that in more detail and improve it.

**Comment by Zelldon** [comment]
Looks really cool. I like the writing of the tests and the readme in each folder etc. 

One Question: Why it is named `zeebe-clustered-test` and not with `zb-*`? :)

**Comment by menski** [comment]
> One Question: Why it is named zeebe-clustered-test and not with zb-*? :)

Not sure, I think I choose zeebe as its not a library of Zeebe like zb-logstream but a thing which uses zeebe like zeebe-simple-monitor :thinking: 

We can rename it if you want

**Comment by Zelldon** [comment]
No was only asking out of interest, when to use zb or zeebe. Make sense what you wrote for me it is ok. :)
I will close this issue. But I think we need to check why they are not running after the scheduler change.
