### ISSUE TITLE
Decide on Zeebe Chaos pipeline

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#6156]
**Description**

The Zeebe Chaos pipeline is currently failing, because of the service account change we did last week. It needs to use the newest SA token in order to be able to run again. The question is whether we still need it. We now also have chaos experiments against all cluster plans via the test bench. Only benefit I see here is that it is a long running cluster instead of a short living. 

So question would be: Do we want to fix it or should we remove it completely?

**Comment by npepinpe** [comment]
What is the advantage of the long running cluster? Do you mean it's the same cluster even across runs? Are we updating it every time?

**Comment by Zelldon** [comment]
Yes to both, correct we updating it on a newer version.

**Comment by npepinpe** [comment]
Let's kill it - we should test these things properly, which we will do eventually, but long running is not a case which is vital for GA at the moment. So from my pov the advantages are tangential, and while nice, don't fit our current priorities. wdyt?

**Comment by Zelldon** [comment]
Ok I will create a PR to remove it thanks
