### ISSUE TITLE
Apply event-sourcing to the variable processors

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#6175]
**Description**

* apply the event-sourcing concept to the variable processors
* including restructure the variable state to extract the variable propagation from setting a variable  

Reference:
* [ZEP: Service Task](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#the-stream-processor#service-task)

**Comment by npepinpe** [comment]
The current plan is to:

1. Extract the document indexing logic out of the variable state.
2. Expose getting the parent scope key of a variable scope key through `VariableState`.
3. Create a new variable document merging behaviour, which will be used by I/O mappings and by the `UpdateVariableDocumentProcessor`.
4. Apply event-sourcing to variable/variable document: remove variable listeners, create a `VariableApplier` (only one is needed for either updated/created), update the behaviour created in step 3 to use an immutable state and not update variables but use the `StateWriter`.

**Comment by Zelldon** [comment]
I did nothing @npepinpe :sweat_smile:

**Comment by npepinpe** [comment]
Seems like the automation still closes issues just due to the branch name. Maybe this isn't code tree... :thinking:

**Comment by npepinpe** [comment]
I like that it's someone different every once in a while :smile:
