### ISSUE TITLE
Apply event-sourcing to the message processors

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#6178]
**Description**

* apply the event-sourcing concept to the message processors

Open question:
* Rename the intent of messages from Delete/Deleted to Expire/Expired to be more intuitive?
* Omit writing a message event with intent Published if the TTL = 0 to avoid additional logic when replay this event (e.g. don't store the message in state)?

Reference:
* [ZEP: Message Events](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#message-intermediate-catch-event)

**Comment by Zelldon** [comment]
:man_shrugging: @MiguelPires @npepinpe @saig0 would be nice when we can get this under control :sweat_smile:

**Comment by npepinpe** [comment]
The issue was closed when the branch 6178-message-expire was merged, so I imagine it's something related to this. Why it uses Miguel's credentials, I have no idea...

**Comment by npepinpe** [comment]
![Screenshot from 2021-02-16 19-57-40](https://user-images.githubusercontent.com/43373/108108694-3ebbdc80-7091-11eb-8418-791a70a1d8b1.png)
