### ISSUE TITLE
Apply event-sourcing to the BPMN parallel gateway processor

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#6190]
**Description**

* apply the event-sourcing concept to the BPMN parallel gateway processor

Open question:
* ~How to restore which incoming sequence flow is triggered?~ - moved to #6450

Reference:
* [ZEP](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#bpmn-processing)

**Comment by korthout** [comment]
Part of this issue is removing the processing of SEQUENCE_FLOW_TAKEN records and removing the dirty hack from `ReprocessingStateMachine` (see todo in that class with marker for this issue).
