### ISSUE TITLE
Verify that replay restores the state correctly

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#6203]
**Description**

We need to verify that the stream processor restores the state on replay. It must restore exactly the same state as before on processing. 

* create a basic setup for writing these test cases
  * generate random workflows (with limited elements)
  * able to compare the content in the RocksDB state   

Reference:
* [ZEP: Testing](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#testing)
* [Collected ideas about Workflow Engine Tests](https://docs.google.com/document/d/1JFzlx-xJ-wLMPKCOcUn7G6nn4JwaJdJD93TkVPitwHM/edit?usp=sharing)
* [Workflow Generator Spike](https://github.com/zeebe-io/zeebe-workflow-generator/tree/random-process-generator)

**Comment by pihme** [comment]
Not done yet
