### ISSUE TITLE
Question - does zeebe support automatic retry logic once some task or broker fails at some stage?

### ISSUE THREAD

**Issue by deuther** [zeebe-io/zeebe#621]
Haven't looked at the code yet, hence quick question ;-)

**Comment by menski** [comment]
Hi @deuther,

I'm not sure if I understood your question correctly but if you want to know if a failed task will be retried then the answer is yes. A task can specify how often it will be retried. If then a worker fails to complete a task the broker will send the task to another worker. Does this answer your question?

PS: For questions like this you can also use our [slack channel](https://zeebe-slackin.herokuapp.com/) or https://forum.zeebe.io. GitHub is mainly used to track and discuss code issues.

**Comment by deuther** [comment]
Hi @menski 

Thanks for prompt answer. Yes, you answered my question to some extent.
Let me also express myself this way:

**given:** "there is a broker runing within k8s"
**and:** "the  'validate' -> 'fetch pkg from ftp' -> 'extract & validate pkg' -> 'parse content' workflow is deployed"
**and:** "workflow instance XYZ is active"
**when:** "workflow instance XYZ enters 'fetch pkg from ftp' step"
**and:** "broker fails"
**and:** "broker is restarted"
**then:** "workflow instance XYZ should be reinitialized automatically"
**and:** "workflow instance XYZ should continue from step 'fetch pkg from ftp'"

p.s. next time I will use channels you provided for this kind of questions. Thanks!

**Comment by menski** [comment]
If a broker restarts or crashes it recovers automatically the last state which is always persisted to disk and continues all running instances.

**Comment by deuther** [comment]
Great to know. Thanks! Will let zeebe a chance then ;-)

**Comment by menski** [comment]
We are always happy to answer any questions if you give it a try
