### ISSUE TITLE
GossipEventListener calling and spread behavior

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#625]
On reviewing #343 I found a problem which is described here #624. 
As first I thought join requests and Membership Events are not spread at all and only send to one node.
I had a problem to find the place where the dissemination of the events happens.
After a bit of debugging and reading I found the key parts, but perhaps we can improve on that.

The following is a short description how the process of calling the listeners on a new gossip event goes.

 * The GossipEventFactory is used by the Controller's to create a GossipEvent. On creation time (inside the Factory) the main listeners are added. For example EventLogger, MemberListUpdater and Dissemination component.
 * This Gossip Event is reused by the calling Controllers. 
 * MembershipEvents and CustomEvents are send and received on ping requests/responses
 * The Request can contain more than one custom and membership events.
 * In the GossipRequestHandler, on a request, the request buffer is wrapped from the GossipEvent.
 * Inside the wrap method, the listeners for membership events and custom events are called.
 * For the membership event, for example, as first the log listener, the membershipUpdateListener
and if the membership was updated the DisseminationComponent, which spread the event again, are called.
 * After all listeners for custom and membership events are called the wrap method will finish and the gossip event listeners are called. 

I would say that calling the listeners in the wrap method is the wrong place and some way of hide something. Besides that it was not clear if the events are spread after the listeners are called.

I would like to discuss this.

**Comment by menski** [comment]
We will replace the gossip module
