### ISSUE TITLE
Incorrect representation of string process variable

### ISSUE THREAD

**Issue by illpillow** [zeebe-io/zeebe#6287]
**Describe the bug**
When defining a single string value as a variable, e.g. `str`, zeebe incorrectly returns this variable with quotes around the actual value, e.g. `"str"`. I believe this is due to the representation of variables as JSON. When exporting such a variable record, the quotes are exported as well possibly breaking an application reading that exported record.

**To Reproduce**
This is quite simple to reproduce: Fire up a standalone broker and the simple monitor, start a process and add a variable (either via command-line or via web UI, doesn't matter). When refreshing the web UI it now displays the variable using quotes.

**Expected behavior**
While I can understand that it makes sense displaying variables as JSON, I would expect a primitive object like a string to returned as such, i.e. without quotes.

**Log/Stacktrace**
There is no stacktrace or error log since it's not an error to zeebe itself, but the consuming applications.

**Environment:**
 - OS: Windows/Linux
 - Zeebe Version: 0.26.0
 - Configuration: https://github.com/zeebe-io/zeebe-docker-compose/blob/master/simple-monitor/application.yaml

**Comment by saig0** [comment]
@illpillow thank you for raising this up. 

You're right that the variable record contains the variable value as a JSON string. This is documented in the [Java docs](https://github.com/zeebe-io/zeebe/blob/develop/protocol/src/main/java/io/zeebe/protocol/record/value/VariableRecordValue.java#L31-L32).
It is basically the structure as the variables are persistent on the stream. There is no distinction between "primitive" values and more complex objects. The uniform format makes it easy to consume the stream without knowing the type of the value.

Please explain more about your use case. 
Which problems do you see?
How does it block you?

**Comment by illpillow** [comment]
Hi @saig0,

thank you for quick reply and sorry for my late response...

In our current use case we store a variable representing a custom business key as used in the classic Camunda workflow engine. To access the history of a process we have created an exporter that writes all outputs from zeebe to a database. To correlate the outputs we first go from the variables by searching our custom business key. Due to the representation of the variable as a JSON string it does not match anymore because of the quotes, i.e. expected key `ABC`, exported key `"ABC"`.

For now we have worked around this by extending the given key with quotes to find the correct workflow instance key and afterwards removing them again to match the saved key.

I can clearly see the advantage of having a uniform representation of variables regardless of their type. Since you already provided a link to the Java doc stating this kind of behavior I guess this is functionality is expected. Would have been good if we had read that before rising this issue... However, a hint in the official docs about variables would probably be useful as well. From my side this issue is resolved and we are going to implement the conversion to JSON before comparing the keys.

**Comment by saig0** [comment]
Thank you for sharing the insides :+1:

**Comment by bulivlad** [comment]
@saig0 came across this one as well when trying to migrate a running process from an older version to a newer one.
As there in no straight forward way of migrating running processes from a version to another in camunda 8 what I'm trying sounds like:
1. Retrieve all variables from the running process using operate rest api
2. Create and start a new process using the latest version as described [here](https://docs.camunda.io/docs/components/concepts/process-instance-creation/)
3. Adding variables retrieved at point 1 to the new process

Also here's a code snippet of what I'm trying
```
zeebeClient.newCreateInstanceCommand()
        .bpmnProcessId(processInstanceDTO.getBpmnProcessId())
        .version(processInstanceDTO.getVersion())
        .variables(processInstanceDTO.getVariables())
        .startBeforeElement(processInstanceDTO.getStartBeforeElement())
        .send()
        .join()
        .getProcessInstanceKey();

```
