### ISSUE TITLE
Improve clustering integration tests

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#632]

**Comment by menski** [comment]
We need helper methods which give us the following synchronization points.

- `startCluster`
  - waits that a leader + at least 2 followers for the `internal-system` topic partition `0` exist
- `createTopic`
  - waits for the successful execution of the client create topic command
  - waits for replication of all partitions of the topic, i.e. for every partition we see a leader + at least 2 followers
  - the java client can see the topic, maybe topics request?
- `stopBroker`
  - determine all partitions the broker is leader for
  - close the broker
  - wait till we see a new leader for the partitions the broker was leader for
- `restartBroker` (not sure if we need this)
  - starts broker again
  - wait till the broker appears again in the topology

**Comment by menski** [comment]
On jenkins it seems that the clustering tests are not really stable at the moment. There is normally one or two tests failing.

**Comment by menski** [comment]
locally I often see following tests fail:

```
[ERROR] Failures:                                                                                                                                                                                                                                                               
[ERROR]   BrokerLeaderChangeTest.shouldChangeLeaderAfterLeaderDies:88 Failed to wait for task completion                                                                                                                                                                        
[ERROR]   CreateTopicClusteredTest.shouldRequestTopicsAfterTopicCreation:81 expected:<[tru]e> but was:<[fals]e>                                                                                                                                                                 
[ERROR]   DeploymentClusteredTest.shouldDeployOnRemainingBrokers expected:<[tru]e> but was:<[fals]e>                                                                                                                                                                            
[ERROR]   GossipClusteringTest.shouldReAddToCluster:133 
```

**Comment by ThorbenLindhauer** [comment]
I rewrote `ClusteringRule` a little bit on the branch https://github.com/zeebe-io/zeebe/compare/575. I'll push that with the changes for #575.

**Comment by Zelldon** [comment]
@ThorbenLindhauer really cool thanks :) 

@menski I think I fixed the problems. On my machine the tests are now green. I have to wait until the jenkins runs again.

**Comment by ThorbenLindhauer** [comment]
Another thing: Surefire doesn't pick up `VerifyDirectMemory` as it does not match the default test class naming patterns (see https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html).
