### ISSUE TITLE
Race condition on ReplayStatePropertyTest

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#6321]
**Description**

ReplayStatePropertyTest failed after running it locally.

![fail](https://user-images.githubusercontent.com/2758593/107642259-e93c9580-6c74-11eb-86c0-420558ddab70.png)
I was not able to copy the test seeds, thats why a screenshot.

Assert failure:
```
org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
[The state column 'DEFAULT' has different entries after replay] 
Expecting map:
  {"[0, 0, 0, 24, 76, 65, 83, 84, 95, 80, 82, 79, 67, 69, 83, 83, 69, 68, 95, 69, 86, 69, 78, 84, 95, 75, 69, 89]"="{"lastProcessPosition":48}"}
to contain only:
  [[0, 0, 0, 24, 76, 65, 83, 84, 95, 80, 82, 79, 67, 69, 83, 83, 69, 68, 95, 69, 86, 69, 78, 84, 95, 75, 69, 89]={"lastProcessPosition":49}]
map entries not found:
  [MapEntry[key="[0, 0, 0, 24, 76, 65, 83, 84, 95, 80, 82, 79, 67, 69, 83, 83, 69, 68, 95, 69, 86, 69, 78, 84, 95, 75, 69, 89]", value="{"lastProcessPosition":49}"]]
and map entries not expected:
  [MapEntry[key="[0, 0, 0, 24, 76, 65, 83, 84, 95, 80, 82, 79, 67, 69, 83, 83, 69, 68, 95, 69, 86, 69, 78, 84, 95, 75, 69, 89]", value="{"lastProcessPosition":48}"]]
```

There is a race condition, on taking the first snapshot we do: https://github.com/zeebe-io/zeebe/blob/develop/engine/src/test/java/io/zeebe/engine/processing/streamprocessor/ReplayStatePropertyTest.java#L139-L144

So we wait until last process is equal to last written. After restart we only wait until the stream processor switch his phase to PROCESSING, which is a weaker assumption.

In our failure case we had the following log:
```
  ...     46            47          48       49
[..., JOB_CREATE, JOB_CREATE, JOB_CREATED, JOB_CREATED]
```

The first JOB CREATED (pos 48) will not cause an follow up event. This means on reprocessing we will find 47 as the last record until we do the reprocessing and switch to processing again. This means we process 48 normal again, when we are now fast enough in our test and take a snapshot of our state we will have a different last processed position.

The issue here is we currently can't use the same technique to wait until write and last processed is same, since after reprocessing last written is minus one. We need to set the last written to the last position in the log in order  to fix the race condition.

Easily reproducible if you put a sleep after updating the PROCESSING state.

![reproduce](https://user-images.githubusercontent.com/2758593/107653064-87365d00-6c81-11eb-817f-2d90ec947eb3.png)

**Comment by Zelldon** [comment]
Might have a fix. Need to refine it

**Comment by pihme** [comment]
I think you are right. But it won't be enough to just use the same condition. We also need to stop the engine from advancing past the point where we took the snapshot before the restart.

**Comment by saig0** [comment]
I suggest to exclude the `lastProcessPosition` column from the check. While migrating the processors, we will skip the commands and don't reprocess them. If we skip the command then the `lastProcessPosition` is not updated. 

Sidenote: we can access the last written position directly from the stream. We don't need to ask the stream processor of his last written position.

**Comment by Zelldon** [comment]
Would be happy if you can create a PR for that I have currently no time for that.

**Comment by saig0** [comment]
Sure :+1: I'll create the PR. Please approach me if something is unclear.
