### ISSUE TITLE
Topology response contains all raft members

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#633]
The topology should contain a list of all brokers of the cluster. And for every broker a list of all partitions it is responsible for (including the raft state). Similar to:

```json
{
    "brokers" : [
        {
            "host": "server1",
            "port": 51015,
            "partitions": [
                {
                    "topicName": "internal-system",
                    "partitionId": 0,
                    "state": "LEADER"
                },
                {
                    "topicName": "foo",
                    "partitionId": 1,
                    "state": "FOLLOWER"
                },
                {
                    "topicName": "foo",
                    "partitionId": 2,
                    "state": "LEADER"
                }
            ]
        },
        {
            "host": "server2",
            "port": 51015,
            "partitions": [
                {
                    "topicName": "internal-system",
                    "partitionId": 0,
                    "state": "FOLLOWER"
                },
                {
                    "topicName": "foo",
                    "partitionId": 1,
                    "state": "LEADER"
                },
                {
                    "topicName": "foo",
                    "partitionId": 2,
                    "state": "FOLLOWER"
                }
            ]
        }
    ]
}
```

This additional information allows us to better synchronize on the replication state in the integration tests suite. Also this information can be useful for the user to understand which server is responsible for which partition.

**Comment by menski** [comment]
As much as I love logging we should take care to not commit log statements which we added during debugging like: https://github.com/zeebe-io/zb-raft/commit/2f89a7f163448ff2a74dc2c06dd83a9259c308c6#diff-753bf9bc4b70a2fa73b219baaac5dbe0R151

If we want to keep the log statement it should have a useful message and give enough context.

**Comment by Zelldon** [comment]
Yeah right, was by mistake :see_no_evil: Sorry :)

**Comment by menski** [comment]
we also have to adjust https://github.com/zeebe-io/zeebe-test

**Comment by Zelldon** [comment]
never seen this before :sweat_smile:

**Comment by menski** [comment]
I refactor the determination if a partition is in leader state as the constant `LEADER` was spread throughout the code (see https://github.com/zeebe-io/zeebe/commit/973a5785715d15aba392347c4718e174e0f8ccbc and https://github.com/zeebe-io/zeebe-test/commit/69fb9058e051256469a3fb33924adbc7c9305550)
