### ISSUE TITLE
LogStorageAppender should use the LeaderRole from correct term

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#6346]
When LogStorageAppender appends a new record, it gets the current LeaderRole object for each append. Since the role transition in raft and zeebe happens asynchronously, when the role on raft has stepdown to follower, LogStorageAppender may be still running. Then the raft role can become a leader again at a newer term. This means that after a step down (and then again becoming a leader), the appender may try to append with a LeaderRole object at a newer term, while the LogStorageAppender is from a previous term. 
https://github.com/zeebe-io/zeebe/blob/e76d9256080e4e3331cfdd786210780e9b00ea35/logstreams/src/main/java/io/zeebe/logstreams/storage/atomix/AtomixLogStorage.java#L49

If it was using the old LeaderRole object to append, it would not be able to append because the role is already closed. It would be better to get the LeaderRole object once, immediately after the role transition to leader. It would prevent inconsistencies as observed in 
Ref: https://github.com/zeebe-io/zeebe/issues/6316#issuecomment-779276368_

**Comment by npepinpe** [comment]
Generally I would like to separate the appender part from the leader role itself - if it helps here then we should do that first.

**Comment by Zelldon** [comment]
@deepthidevaki do you have time tomorrow to discuss this?

**Comment by deepthidevaki** [comment]
Yes.
