### ISSUE TITLE
I cannot create more than 128 partitions

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#636]
Create more than 128 partitions in a row. This queue overflows: https://github.com/zeebe-io/zeebe/blob/0.6.0/broker-core/src/main/java/io/zeebe/broker/system/deployment/handler/WorkflowRequestMessageHandler.java#L41

Why? A new command is added with every new log stream and the queue is only processed when a workflow request arrives, which is not the case here.

**Comment by meyerdan** [comment]
Done via zeebe-io/zeebe#679f1608fa81ca85b0e02b53476364a802638e4c
