### ISSUE TITLE
Raft join request loop

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#638]
A node can end in a loop, in which it sends many join requests in a millisecond.

## Scenario:

 * Node 1 starts.
 * Node 2 starts and sends join to Node 1. 
 * Join requests times out.
 * Node 2 sends new join request, goes into await join response state.
 * Request is done, but rejected by node 1. 
 * Fail transition ends in send join request state. Starts again in Point 3.

We have now a loop, which ends if Node 1 commits and the join will be accepted.
We need to wait between the join requests.

I think some of the failing IT cluster tests are related to this loop.

**Comment by menski** [comment]
Good catch, this where a lot of request :see_no_evil:

**Comment by Zelldon** [comment]
Yeah :D 

Perhaps we can add a transition from `AwaitJoinResponseState` to `SendJoinRequestState`, which is take if the Request times out. In this case I would say we don't need to wait again.
