### ISSUE TITLE
Test broker restart without index savepoints

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#64]
Write tests where the last log entries are API requests that no follow-up events point to (e.g. task locked events that are not completed yet) and where these events have not been indexed yet, such that the recovery logic processes them again.
Fix problems if any.

Should be both, integration and unit tested.

**Comment by menski** [comment]
@saig0 does the broker restart tests cover this issue?

**Comment by saig0** [comment]
@menski  yes, they do.
