### ISSUE TITLE
Opening a task subscription can fail unexpectedly on leader change

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#640]
Scenario:

* Leader change takes place
* Client is aware of new leader
* Client makes request to create a new task subscription
* Broker request handler tries to add the subscription to the stream processor that locks tasks
* The last step can fail in a leader-change situation because the handler is notified asynchronously of log streams

Current behavior:

* The request fails with error code `REQUEST_PROCESSING_FAILURE`
* The client fails the request accordingly (no retries)

Expected behavior:

* The request fails with error code `PARTITION_NOT_FOUND`
* The client retries the request accordingly

**Comment by menski** [comment]
Probably caused by this bug #641. The issue seems to be that the leader is already propagated in the topology but the logstream service is not started yet, which leads to the situation that the logstream is not yet known by the client API message handler and therefor rejects the request.

**Comment by menski** [comment]
As discussed this is issue still needs a fix in the request handler as there logstreams are registered asynchronous when the service is started.

**Comment by menski** [comment]
Job workers are not a subscription anymore, but instead regularly poll for new jobs, which should handle leader changes gracefully
