### ISSUE TITLE
Deployment on topic with 15 partions causes weird behavior

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#644]
On jenkins and locally with maven I had sometimes that deploying a deployment on a topic with 15 partitions causes an out of direct memory. Also this causes problems on closing the broker and executed other tests afterwards.

**Comment by Zelldon** [comment]
If the ignored test is executed (the test is green if executed). Then all tests after wards are behave really weird. We should take a look into this.

**Comment by menski** [comment]
After the latest cluster orchestration refactoring this test works. It was nevertheless removed as it takes about 30s without testing a specific issue. We can think about adding such a test to the long running test suite.
