### ISSUE TITLE
Add cluster it tests, on which broker is force stopped

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#646]
Pre:

* We need in the cluster rule a new method to kill the broker, without saying good bye
See https://github.com/zeebe-io/zeebe/issues/647

Tests:

 * leader change
 * task completion after leader change
 * deployment and workflow instance start
 * topic creation and leader change for the partitions

**Comment by menski** [comment]
we will instead investigate chaos testing strategies for Zeebe
