### ISSUE TITLE
Additional storage options

### ISSUE THREAD

**Issue by LLLLimbo** [zeebe-io/zeebe#6492]
I hope Zeebe can support relational database storage, because some distributed relational database like [TIDB](https://github.com/pingcap/tidb), already has the ability to scale horizontally , and its underlying storage engine is RocksDB too.

In addition, I believe that there is a fatal problem with the way Zeebe handles data storage, which results in unusually high disk usage during writes. I believe this is the culprit for Zeebe's poor standalone performance.

**Comment by npepinpe** [comment]
Hi @LLLLimbo - having multiple storage options is definitely a nice goals if we want to support various environments and use cases, but it's too early in the project for this at the moment considering the resources (time-wise) we have. At any rate, relational databases are unlikely to help here - Zeebe is built around event sourcing and stream processing, and most of these databases simply aren't built for that. They can be used to store your projection (aka the state), which is what we use RocksDB for, but one of the big advantage with RocksDB is it's embedded into the application (as opposed to a database that is a separate process, possibly located on a different node).

That said, it's still a nice goal in the future to support pluggable state and log storage modules, of course, and it makes sense in the long run, but we just don't have the resources for this at the moment.

Regarding your TIDB example, you're right that Zeebe has similarities with TIDB - both use Raft for consensus/replication, and both use RocksDB though differently: Zeebe uses RocksDB for the engine (in Raft lingo, the replicated state machine), and for its Raft log a simple segmented journal implementation. TIDB uses RocksDB for the Raft log itself. However, keep in mind that you can't really compare the performance of TIDB and Zeebe, has Zeebe has to perform all the work of the database, and on top of that has to run the workflow engine (i.e. the application), whereas TIDB is just the database.

Hope this helps!

**Comment by LLLLimbo** [comment]
@npepinpe Thank you for your patience and the efforts of the Zeebe team! Overall, I am very positive about the future of Zeebe, once the performance issues are resolved.

**Comment by LLLLimbo** [comment]
@npepinpe Thank you for your patience and the efforts of the Zeebe team! Overall, I am very positive about the future of Zeebe, once the performance issues are resolved.
