### ISSUE TITLE
GossipDifferentNodeJoinTest.shouldReAddToCluster fails occasionally

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#651]

**Comment by Zelldon** [comment]
During https://github.com/zeebe-io/zeebe/issues/740 and https://github.com/zeebe-io/zeebe/issues/747 and we also improved the ClusteringRule so it should give the warranty that all brokers have the same state and return the same topology. That is why I reverted for now this fix and will close this issue.
