### ISSUE TITLE
Redesign how cluster membership is propagted to stream processors

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#652]
The current implementation is based on shared, mutable state, therefore not thread-safe. Follow-up of #610. We should tackle this once the actor concept is rewritten.

**Comment by menski** [comment]
idea sync access using actor.call

**Comment by menski** [comment]
With the rewrite of the clustering layer the topology manager only exposes a query API and a DTO which should prevent shared state.

https://github.com/zeebe-io/zeebe/blob/8aab324aa86841a553b74b6b2fdb287a24bb882d/broker-core/src/main/java/io/zeebe/broker/clustering/base/topology/TopologyManager.java#L39-L41
