### ISSUE TITLE
Decided which host should be default in distribution

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#654]
We saw issues on Windows that the default host set in the distribution configuration `0.0.0.0` is not working as expected. Also setting it to `0.0.0.0` on a Linux server make the Client API accessible by anyone, which might be a security concern. Setting it to `127.0.0.1` should work on Linux and Windows but requires changes for cluster setups.

**Comment by meyerdan** [comment]
Might  be worthwhile to have a very quick look at how systems like Cassandra or Kafka are handling this

**Comment by npepinpe** [comment]
Considering we explicitly support containers/k8s, I wouldn't spend more effort here. Feel free to reopen and challenge.
