### ISSUE TITLE
Distribution broker cannot be killed by CTRL-C on Windows

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#655]
It seems that a distribution broker cannot be killed with CTRL-C on Windows.

**Comment by Zelldon** [comment]
There a lot of questions around CTRL-C on cmd (on windows). 
The most suggest to use CTRL-BREAK, if CTRL-C does not work. 

https://docs.microsoft.com/en-us/windows/console/ctrl-c-and-ctrl-break-signals
https://superuser.com/questions/1237833/how-do-i-interrupt-a-program-run-from-cmd/1237838#1237838
https://stackoverflow.com/questions/800521/linuxlike-ctrl-c-keyboardinterrupt-for-the-windows-cmd-line


BTW this seems a MS issue.

https://github.com/PowerShell/Win32-OpenSSH/issues/914
https://github.com/Microsoft/vscode/issues/9347
https://github.com/Microsoft/vscode/issues/25195

**Comment by menski** [comment]
I think we were looking at a good old MinGW terminal at the moment.

**Comment by Zelldon** [comment]
i think this is fixed with https://github.com/zeebe-io/zeebe/pull/1493
