### ISSUE TITLE
Scheduler: #await should not allow another job to be executed before callback

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#669]
`ActorControl#await` blocks the actor until the future is completed. If a job is submitted in the meantime, it is not executed. However, as soon as the future completes the intermittent job is executed before the future callback. This is an odd guarantee that await makes.

**Comment by meyerdan** [comment]
I have given this some thought: I think we should completely remove the blocking feature since I do not think we need it.

**Comment by meyerdan** [comment]
@ThorbenLindhauer I pushed a commit to a branch. In this commit I deprecate await and delegate to the new methods. In addition, I do cleanup and remove the code related to the blocking feature. This removes all the special treatment of futures and the while "blocked" state for the actor.

**Comment by menski** [comment]
await was removed
