### ISSUE TITLE
extract ZeebeObjectMapper

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#672]
zeebe client uses a jackson ObjectMapper that has to be configured with addiitional injection of msgpack.
It is created and configured via "new" inside the ZeebeClientImpl constructor.

In the camel-zeebe extension I needed an object mapper to test json mapping, but it is not possible without creating a ZeebeClient first. (see https://github.com/holunda-io/camel-zeebe/blob/master/test/src/main/java/io/zeebe/camel/test/json/ZeebeObjectMapper.java)

Idea: provide a ZeebeObjectMapper that uses the required configuration and refer to that instance in the ZeebeClientImpl.

**Comment by menski** [comment]
Are you interested to provide a pull request for this? As you are in a better position to check if it meets your requirements.

**Comment by jangalinski** [comment]
already on it
