### ISSUE TITLE
Scheduler: I can schedule asynchronous callbacks in `onActorClosing`

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#677]
I would like to call `#runOnCompletion` in the `#onActorClosing` callback. The scheduler should ensure that the callback is run before the actor task terminates. 

At the same time, it should not be possible to submit any further jobs from the outside anymore.

Use case:
I have a subscription manager in the Java client that should close all current subscriptions when it is closed. Closing a subscription is a transport request (=> asynchronous). The subscription manager (and thus Zeebe client) should not close before all subscribers are confirmed to be closed.

Workaround:
Do not close actor immediately but only do that after subscriptions have been closed. Requires some state management on top of the actor to avoid opening new subscriptions while the subscription manager already closes.

**Comment by ThorbenLindhauer** [comment]
@meyerdan: Any thoughts if this should be built into the scheduler or instead be built into the actor implementation like sketched in the workaround?

**Comment by menski** [comment]
closed cause we got lifecycles
