### ISSUE TITLE
Rename task to work item

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#694]
Open for discussion:

Let's avoid the clash with the BPMN term *task* (as in service task, etc.). This gets confused sometimes in the Camunda BPM context (forum) and it also makes our docs less clear in some places (https://docs.zeebe.io/bpmn-workflows/activities.html#service-tasks).

TaskSubscription => WorkItemSubscription or WorkSubscription
TaskHandler => WorkItemHandler
TasksClient => WorkItemsClient
TaskEvent => WorkItemEvent

**Comment by menski** [comment]
The team agrees that task maybe be not the perfect fit. We should decide in the near future which term we want to use. If no one has a better item then Work Item we will stick to it.

**Comment by ThorbenLindhauer** [comment]
We noticed that `workItem` is dangerously close to `workflow` when it comes to things like code completion and grasping code at a quick glance. We will have to weigh this against the clarity of the term and potential alternatives.

**Comment by o314** [comment]
Semantically, a workflow is a compound, a work item an atom.
So the difference lies in the cognitive and psychographics side.
A still relevant remark, there is so much hard letter in those words.
Hard pipe glyph everywhere that leads to hard to articulate, bind, spell, and memo symbol.

IHMO there is only one serious alternative to the stem `WorkItem` : `Job` 
That drives to

| Before            | After (alt 1)          | After (alt 2)    |
|-------------------|------------------------|------------------|
| TaskSubscription  | WorkItemSubscription   | JobSubscription  |
| TaskHandler       | WorkItemHandler        | JobHandler       |
| TasksClient       | WorkItemsClient        | JobsClient       |
| TaskEvent         | WorkItemEvent          | JobEvent         |

Works more smoothly

Job was already commons in eclipse background job, printing job...

It scale way betters in direction to business analysis and business people too,
still working greatly with techie folks.

My 2 cts

**Comment by berndruecker** [comment]
I do also like the term Job. I think it could be a bit more overloaded / pose more misunderstandings though. On the other hand Job Scheduler are kind of known and probably even good to relate to marketing wise. 

It also does interfere with the Camunda BPM 7 concept of Job, but I personally do not consider this a real show stopper for the term - even if it might complicate things for people migrating.

**Comment by o314** [comment]
Agree with your remarks.



> the job naming is more overloaded in the tech landscape.

true but more with legacy eg. 'job scheduler'
Or go with the flow / too much of a promise solutions.

even with megaproject in the kind of docker, kubernetes, mesos i am not sure at all if there is a clear and formal def of scheduler today.
even less for the next decade.

and there bpmn2 is a clear winner. its promise has be realized, but i think we are in the good timeframe (and the good place).



> the job naming is more overloaded in the business landscape.

true but due to the lack of a clear solution in the tech land.
a good tech / product, and people will follow.


> confusion with camunda

i can answer there.
even if i don't think i see any show stopper in the bpmn2 spec of in what i know from your products

**Comment by meyerdan** [comment]
Big Problem with Workitem is that it looks exactly like Workflow.

Workflow
Workitem

client.getWorkflowClient()
client.getWorkitemClient()

terrible

**Comment by berndruecker** [comment]
I see what you mean. So probably prefer "Job"?

**Comment by meyerdan** [comment]
@ThorbenLindhauer  we decided on "Job". Should this be closed?

**Comment by ThorbenLindhauer** [comment]
Sure, the work to be done is covered by other tickets.
