### ISSUE TITLE
Subsequent calls actor run should guarantee ordering of invocations 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#700]
If code call run in order it should also be executed in this order. Currently the ordering of run calls seems to be not guaranteed.

**Comment by menski** [comment]
Example, this test:  
```
schedulerRule.submitActor(new ZbActor()
{
    @Override
    protected void onActorStarted()
    {
        actor.run(() -> System.out.println("foo"));
        actor.run(() -> System.out.println("bar"));
        actor.run(() -> System.out.println("lol"));
        actor.run(() -> System.out.println("why"));
    }
});
```

will output 
```
foo
why
lol
bar
```

which is probably not what the developer intended to achieve.

**Comment by menski** [comment]
@meyerdan am I right that we decided against this? So we can close this issue?

**Comment by meyerdan** [comment]
yes, lets close
