### ISSUE TITLE
Implement Error-Handling in the ActorScheduler

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#703]
Currently we have no error handling. If an exception is thrown it is simply printed via `printStacktrace` and
 the next job or task is executed.

**Comment by Zelldon** [comment]
I'm really unsure how error handling should look like here, but might be nice to have at least proper logging.

**Comment by npepinpe** [comment]
I think this is still the case? Correct me if I'm wrong.

**Comment by Zelldon** [comment]
Still true

**Comment by npepinpe** [comment]
It is now logged via a Logger :tada: ! But yeah, still not real error handling. Like all things actor scheduler, I would avoid doing anything but critical refactoring/fixing and rather invest time in investigating alternatives (e.g. Akka). I'm closing, but I'd like to hear some opinions if we think this is indeed critical and we should reopen. My reasoning here is that this isn't a trivial issue, so the time it takes to have a solid concept, validate and implement it, we might want to invest in into migrating to a different framework which has the features we need out of the box.

Let me know what you think
