### ISSUE TITLE
Scheduler: Actor callback onActorCloseRequested

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#710]
Add a callback for when closing of an actor is requested. The callback signals to the actor that things like timers, channels, etc. will no longer be considered. The actor can react to that, e.g. by cleaning things up.

Use cases:

1. Transport's `ClientRequestRetryController` repeatedly reschedules requests via `#runDelayed`. This method is only applicable in state `STARTED`. To prevent the controller from rescheduling after closing is initiated, it must keep a flag if it is closing. This flag can be set in the new callback.
1. Transport's `ClientRequestRetryController` waits for requests to finish (`#runOnCompletion`) and also schedules a timer for timeout. If the request is never resolved and the closing is initiated, then the controller can never be closed. The request future blocks the controller from closing and the timeout does not trigger anymore (as state `STARTED` has been left). In the new callback, we could cancel the request.

**Comment by Zelldon** [comment]
@ThorbenLindhauer Do we still need the callback, after impl https://github.com/zeebe-io/zeebe/issues/704 ?

**Comment by ThorbenLindhauer** [comment]
I believe the remaining implementations of that method are either not needed anymore or can be moved elsewhere.

**Comment by Zelldon** [comment]
Ok thanks. I will remove this in #704 or do you want to do this? :)

**Comment by ThorbenLindhauer** [comment]
I created https://github.com/zeebe-io/zeebe/issues/759 and can do it. If you need it done soon, I can give you some pointers how to refactor the remaining implementations.

**Comment by Zelldon** [comment]
I will close this issue then
