### ISSUE TITLE
Gossip configuration cannot be read from toml file

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#720]
During the actor scheduler refactoring the gossip configuration [changed values from long to `Duration`](https://github.com/zeebe-io/zb-gossip/blob/a42337fe7b91a5319aa5211066f2fb3c8e3e8787/src/main/java/io/zeebe/gossip/GossipConfiguration.java#L24). Our configuration parsing cannot convert numbers to duration automatically. Adjust configuration to be parseable from toml files.

**Comment by meyerdan** [comment]
Closed by #815
