### ISSUE TITLE
Replace task-related stream processor mocked tests with integration tests 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#725]
Remove as much mock tests as possible and write integration tests.

**Comment by ThorbenLindhauer** [comment]
Tests to port:

* `TaskLockExpirationStreamProcessorTest` 
* `TaskInstanceStreamProcessorTest`
* `IncidentStreamProcessorTest`
* `LockTaskStreamProcessorTest`

**Comment by ThorbenLindhauer** [comment]
This is the issue for incident-related tests: https://github.com/zeebe-io/zeebe/issues/772
