### ISSUE TITLE
Remove actor lifecycle phase checks

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#729]
At the moment specific actor operations (i.e. creating timers) are not allow in phases like starting and closing. As the actor itself is not always aware of its current phase the ensuring exceptions are misleading. Remove them and document allowed operations in lifecycle call backs.

**Comment by meyerdan** [comment]
Wrongly referenced issue  in commit, sorry.

Commit is https://github.com/zeebe-io/zb-util/commit/91a9d740f8080b52a7e8bcce88a708e43608593e
