### ISSUE TITLE
Improve implementation of actor future get for non actor threads

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#733]
Currently we use busy spin which could be improved by using monitors etc.

- [x] fix implementation
- [x] add stress test in util
- [x] add stress tests in transport validating scalability of blocking requests when increasing thread count

**Comment by Zelldon** [comment]
I think it works not as expected. The following test never ends.

```java
@Test
    public void shouldTimeoutActorFuture() throws Exception
    {
        // given
        final CompletableActorFuture<Void> future = new CompletableActorFuture<>();

        // when
        future.get(5, TimeUnit.MILLISECONDS);

        // then

    }
```

Also the logstream and raft builds are failed because of a timeout.

**Comment by Zelldon** [comment]
As the `Thread#wait` documentation says it can happen that the wait returns, before the time is done and even if the thread was not notified. That is why we should use a while loop.

```java
     [...]
     * A thread can also wake up without being notified, interrupted, or
     * timing out, a so-called <i>spurious wakeup</i>.  While this will rarely
     * occur in practice, applications must guard against it by testing for
     * the condition that should have caused the thread to be awakened, and
     * continuing to wait if the condition is not satisfied.  In other words,
     * waits should always occur in loops, like this one:
     * <pre>
     *     synchronized (obj) {
     *         while (&lt;condition does not hold&gt;)
     *             obj.wait(timeout);
     *         ... // Perform action appropriate to condition
     *     }
     * </pre>
    [...]
```

Besides that I had to remove some code, to fix this issue mentioned [above](https://github.com/zeebe-io/zeebe/issues/733#issuecomment-374128594). Maybe we can rethink about the improvement.
