### ISSUE TITLE
Investigate and fix PollableTopicSubscriptionTest

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#738]
Currently the test succeeds but has an unexpected timing.

**Comment by ThorbenLindhauer** [comment]
Analysis: The test creates the situation where a subscriber is reopened but that request is going to time out (15 seconds). At the end of the test, the client is closed. Closing works such that it does not close a subscriber group while a subscriber is opening. Instead we wait for the opening request to resolve and may then close the subscriber again. So the client does not close before the open request is resolved which is 15 seconds in our test suite. 

I consider this behavior good (makes it least likely that subscribers remain open, although not impossible), so I decided to extend the test such that it makes the request time out immediately by manipulating the clock.
