### ISSUE TITLE
Increase test coverage for actor scheduler

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#739]
The actor scheduler is a main component and should be well tested.

- [x] actor lifecycle tests https://github.com/zeebe-io/zb-util/commit/91a9d740f8080b52a7e8bcce88a708e43608593e
- [x] order of execution of actions https://github.com/zeebe-io/zb-util/commit/9a320b2d91a116a2682b5c48eaa037c9e1345675
- [x] move stress tests to JMH testsuite https://github.com/zeebe-io/zb-util/commit/51afad608bbaa3fffb998bd454da8e63af808903
- [x] add missing functional unit tests https://github.com/zeebe-io/zb-util/commit/4065391a60a67aae1e2ee2a8d7836c7b29df3554

**Comment by meyerdan** [comment]
@menski  I am closing this now. As a follow up, we should discuss running the stress tests in Jenkins: #744
