### ISSUE TITLE
Stabilize transport test suite

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#741]
Currently we see the test case `io.zeebe.transport.ControllableClientTransportTest.shouldNotOpenRequestWhenSendBufferIsSaturated` repeatedly fail on Jenkins.

**Comment by ThorbenLindhauer** [comment]
Had these three locally:

```
[ERROR] Failures:
[ERROR]   ClientTransportTest.shouldReopenChannelAfterReactivation:535 expected:<[tru]e> but was:<[fals]e>
[ERROR]   ControllableClientTransportTest.shouldNotOpenRequestWhenSendBufferIsSaturated:100 expected:<null> but was:<io.zeebe.transport.impl.ClientRequestImpl@1a6c1270>
[ERROR]   ControllableClientTransportTest.shouldRejectMessageWhenSendBufferIsSaturated:123 expected:<[fals]e> but was:<[tru]e>
```

The first one fails only very rarely. They run fine from within Eclipse.

**Comment by ThorbenLindhauer** [comment]
Can't reproduce the failure of `ClientTransportTest.shouldReopenChannelAfterReactivation`, so I'll ignore it for the time being.
