### ISSUE TITLE
Run actor scheduler stress tests

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#744]
There is a new testsuite for actor scheduler stress tests, created in #739.
These tests use JMH and tests that features like futures, channels, consumers, etc.. can be run millions of times and also concurrently. We need to run this testsuite in CI.

**Comment by meyerdan** [comment]
Also interesting https://github.com/jzillmann/jmh-visualizer

**Comment by menski** [comment]
Looks good for me https://hq2.camunda.com/jenkins/zeebe/job/zb-util-DISTRO-maven-deploy/jmh-report/
