### ISSUE TITLE
TaskSubscription seem to fetch only the given taskFetchSize

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#752]
In the integration tests it seems that the TaskSubscription fetch only the given taskFetchSize, after completing them no new tasks are fetched.

**Comment by saig0** [comment]
@ThorbenLindhauer , do you know why it's important to buffer task increase credit requests which couldn't be handled? Currently, incoming requests aren't handled until the buffered requests are handled.

**Comment by ThorbenLindhauer** [comment]
@saig0 I believe this is a leftover of trying to be garbage-free and can be greatly simplified if this is not required.

**Comment by Zelldon** [comment]
Hey @saig0 did we simplified/removed the buffering or what is the current state?

**Comment by saig0** [comment]
No, it's still there. Currently, I don't see a need to improve the behavior. If we remove the buffering then it could be that we lose credit requests (and maybe also the credits if the client doesn't send new requests).

**Comment by menski** [comment]
Not sure if related but the problem described in the initial post could have been triggered by this bug https://github.com/zeebe-io/zeebe/issues/770

**Comment by Zelldon** [comment]
Sorry @saig0 but I have another question, https://github.com/zeebe-io/zeebe/commit/0a4bd5f89e9f8777483c9a25074a59bc98c44da0 removes the commented out TaskSubscriptionManagerTest, which had extensive use of mocks. Do we have an alternative ?
