### ISSUE TITLE
Can't access ActorClock in #runBlocking

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#753]
During the removing of the `ClockUtil` (#751 ) I observed some problems with the `ActorClock`.

The `ActorClock` is only available in an ActorThread. If we call `ActorClock#currentTimeMillis` `ActorThread.current` is called, which returns null if the current Thread can't be casted to `ActorThread`. If null is returned `ActorClock#currentTimeMillis` throws an exception, that it can only be accessed in an `ActorThread`.  This makes sense, but if we running in an Actor and for example call `actor.runBlocking`
this will be execute from `ThreadPoolExecutor`. This executor uses `BlockingTasksThreadFactory`, which simply creates new Threads for an runnable.

This means if an runnable is executed from the `ThreadPoolExecutor`, which happens on `#runBlocking`, then we have no access to the `ActorClock`.

---

We have this for example in the `ClusterManagerService`.
In the `Service#start` method there is a action submitted to the `ServiceStartContext`.

```java

  @Override
    public void start(ServiceStartContext startContext)
    {
        startContext.run(() ->
        {
            final ClusterManagerContext context = clusterManagementContextInjector.getValue();
            clusterManager = new ClusterManager(context, serviceContainer, config);

            actorSchedulerInjector.getValue().submitActor(clusterManager);
        });

    }
```

In the service controller this action will be executed via `runBlocking` see this [line](https://github.com/zeebe-io/zb-service-container/blob/master/src/main/java/io/zeebe/servicecontainer/impl/ServiceController.java#L170).
This means we can't access the ActorClock or the ActorThread.current.

Is this what we expect?

**Comment by meyerdan** [comment]
I think that we should implement this in a way that it works for the threads executing blocking actions as well.

**Comment by Zelldon** [comment]
I think this is fixed with https://github.com/zeebe-io/zeebe/issues/849
