### ISSUE TITLE
Raft replication: throughput vs. deadline

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#758]
Investigate how raft can maximize throughput while meeting the heartbeat deadline

**Comment by meyerdan** [comment]
I am now able to replicate 5M events in a 3 node cluster in 39sec on my machine, that is 128K events/s  at around 32MB/s cluster write throughput

**Comment by menski** [comment]
Raft credit idea acking with the consumed buffer size

**Comment by meyerdan** [comment]
Initial implementation is available. I would leave it at this for now
