### ISSUE TITLE
Allow client.complete(taskId)

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#765]
We should allow to complete as task (WorkItem) by its id. Currently you need the full event to do that.

**Comment by berndruecker** [comment]
Currently I need this workaround: https://github.com/flowing/flowing-retail/blob/zeebe/kafka/java/order-zeebe/src/main/java/io/flowing/retail/kafka/order/adapter/ZeebeWorkarounds.java

**Comment by menski** [comment]
At the moment we do not plan to implement this. The new Client API will provide a simple way to (de)serialize an event from/to JSON which can be used to store the event for later completion.
