### ISSUE TITLE
Client credit update is not thread safe

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#769]
The client checks if the credits should be updated after a event was processed. It then triggers a condition which will execute the update async. Before this update is executed more events could be processed triggering the condition again. When the update handler is executed it will reset the events processed since last update. If then the update handler is invoked again by one of the remaining condition triggers it will try to update the credits to 0 since the last processed events were reset to 0 in the mean time which is invalid and kills the subscription.

**Comment by ThorbenLindhauer** [comment]
Is there an exception occurring and do you have a stacktrace?

**Comment by menski** [comment]
There is no stacktrace. The broker just rejects credit requests with <= 0 credits. And as the client will close the subscription on an error we should prevent this one way or the other.

https://github.com/zeebe-io/zeebe/blob/e39ea27b3e5363e99c3274cb571c29d8744d3855/broker-core/src/main/java/io/zeebe/broker/transport/controlmessage/IncreaseTaskSubscriptionCreditsHandler.java#L57-L60

**Comment by ThorbenLindhauer** [comment]
Ah, okay. I'll see if I can fix this later.
