### ISSUE TITLE
Stream Processor Snapshot is not written under high load

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#771]
Current behavior:
* the controller tries to write a snapshot at a fixed rate
* before it writes a snapshot, it checks that the last written event is committed
* if not, no snapshot is written
* as result, the controller may write no snapshots if it constantly writes new events  

AT:
* snapshots are written eventually

Hint:
* the previous implementation stopped the processing of new events until the snapshot was written
* alternative: if the check fails then retry the check after a short period

**Comment by menski** [comment]
We have to decided how to handle snapshots under load (see also #499). If we value performance more then recovery speed we probably should limit snapshot creation under load.

**Comment by saig0** [comment]
The behavior has changed. Now, snapshots are always created, even if it contains not yet committed changes.
