### ISSUE TITLE
Service container shutdown can time out

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#775]
The way the service container shuts down the services on `ServiceContainer#close` is not robust. It happens sometimes in the broker test suite that `#close` times out after ten seconds although all services are already removed.

* The service container and each service controller are individual actors
* The service container iterates all currently installed (not yet removed) controllers and asks them to close via `actor.call`
* This call submits a future to the service controller that is completed when the service is removed
* It can happen that the container still sees a service controller that is already closing. The `#call` invocation will then do nothing and the remove future is never completed
* Service container waits until timeout for this future to complete

**Comment by Zelldon** [comment]
I think this is now fixed due to closing only root services which then closes it dependencies etc - never saw this exception again
