### ISSUE TITLE
Composite service container operations

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#782]
When using service container, there are situations where we want to install multiple services as one operation.

There are many examples where an event in the broker like the creation of a new partition needs multiple services to be installed as one groop.

In these situations, we want to be able to
- wait until all these services were successfully installed
- if installation of one of the services fails, we want the whole operation to be rolled back (ie. the other services should be stopped again)

This will now get more important as we rewrite the clustering layer in the broker

**Comment by meyerdan** [comment]
Implementation is done and pushed to branch, waiting for release

**Comment by saig0** [comment]
I merged the changes. @meyerdan can you please create an issue to introduce an install timeout? Thank you.

**Comment by meyerdan** [comment]
@saig0  Thanks! 788
