### ISSUE TITLE
Use service container to track dependencies in logstreams

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#783]
In the logstreams module we have rather complex dependencies between the different actors.

Problems with current implementation:
- Currently we have a lot of error-prone code using futures for managing these dependencies
- When using the module in the broker, it is not possibile to crate dependencies on components like the storage only

Out solution to managing statefule components with lifecycle & dependencies is service container, we should use it.

This will get more important as we rewrite the clustring layer in the broker

**Comment by saig0** [comment]
@meyerdan , I applied the review hints. Somehow, the LogBlockIndexWritterTests are kind of unstable. I guess that the update commit position is not triggered / handled correctly after service restart.
