### ISSUE TITLE
Create clustering base layer

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#784]
The Cluster Manager has grown over time and, for obvious reasons, has never received a lot of love.

Now, as we start to implement replication factors and more sophisticated orchestration, we need to structure this in a more robust way.

Goals:
- separate clustering base layer from orchestration layer
- prepare for orchestrator
- make different aspects more composable (break apart monolithic ClusterManager)
- do state management correctly
- use the service container to clearly track and manage dependencies between components

**Comment by meyerdan** [comment]
Remaining:

- [] Raft stability
- [] Ignore tests which need orchestration layer (Cluster tests)
- [] Adjust all configurations

Follow up issues
- [] I can provide replication factor when creating topic
- [] In standalone mode I can provide default topic in configuration
- [] Separate start scripts and configurations for standalone vs. clustered broker
- [] Tests for cluster bootstrap
- [] Orchestration layer

**Comment by menski** [comment]
@meyerdan can this be reviewed or this there more things to do?
