### ISSUE TITLE
A raft node can leave the group

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#787]
Raft provides a leave method which will trigger that the node tries to leave the current raft group. The leave method is **not** invoked by closing raft. The leave is attempted endlessly. The initiated leave does not change anything about the replication algorithm, meaning events are still replicated during leave.

At the moment calling leave on a leader will throw an exception. Making a leader leave requires more preparations.

Chapter 4 - Cluster membership changes of the [Raft Paper](https://github.com/ongardie/dissertation/blob/master/book.pdf?raw=true) describes the desired behavior.

**Comment by Zelldon** [comment]
For avoiding disruptive servers and disabling election timeout on leave, we will improve the Voting process.
This is described in the RAFT dissertation section 4.2.3 Disruptive servers.

> 
> Raft’s solution uses heartbeats to determine when a valid leader exists. In Raft, a leader is
> considered active if it is able to maintain heartbeats to its followers (otherwise, another server will
> start an election). Thus, servers should not be able to disrupt a leader whose cluster is receiving
> heartbeats. We modify the RequestVote RPC to achieve this: if a server receives a RequestVote
> request within the minimum election timeout of hearing from a current leader, it does not update its
> term or grant its vote. It can either drop the request, reply with a vote denial, or delay the request;
> the result is essentially the same. This does not affect normal elections, where each server waits at
> least a minimum election timeout before starting an election. However, it helps avoid disruptions
> from servers not in Cnew: while a leader is able to get heartbeats to its cluster, it will not be deposed
> by larger term numbers.
>
> This change conflicts with the leadership transfer mechanism as described in Chapter 3, in which
> a server legitimately starts an election without waiting an election timeout. In that case, RequestVote
> messages should be processed by other servers even when they believe a current cluster leader exists.
> Those RequestVote requests can include a special flag to indicate this behavior (“I have permission
> to disrupt the leader—it told me to!”).

This means we will store the last heartbeat time and on a vote request each raft node will check if he will as well do an election, because he got no heart beat from the leader as well.

**Comment by ThorbenLindhauer** [comment]
Review:

- There's a race condition between https://github.com/zeebe-io/zb-raft/blob/cf7c6c9/src/main/java/io/zeebe/raft/controller/RaftJoinService.java#L108 and https://github.com/zeebe-io/zb-raft/blob/cf7c6c9/src/main/java/io/zeebe/raft/controller/RaftJoinService.java#L122, which can lead to an exception if we complete the future a second time. We can prevent this by a guard.

This does not block the release.

**Comment by Zelldon** [comment]
Seems that this additional timer was added in https://github.com/zeebe-io/zeebe/issues/784 - but yeah will add the guard.
