### ISSUE TITLE
StreamProcessorControllerTest crashes

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#791]
JVM crashes occasionally. It looks like memory is being used after it is released, e.g. a claim on a closed dispatcher.

[hs_err_pid2760.log](https://github.com/zeebe-io/zeebe/files/1883967/hs_err_pid2760.log)
[hs_err_pid6528.log](https://github.com/zeebe-io/zeebe/files/1883968/hs_err_pid6528.log)
[hs_err_pid9880.log](https://github.com/zeebe-io/zeebe/files/1883969/hs_err_pid9880.log)

**Comment by saig0** [comment]
This issue is maybe fixed by #783.
@ThorbenLindhauer does the JVM crash still happen?
