### ISSUE TITLE
Broker: Distinguish events, commands, command rejection

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#794]
These aspects should become part of the event header (BrokerEventMetadata)

**Comment by menski** [comment]
may solve https://github.com/zeebe-io/zeebe/issues/367

**Comment by ThorbenLindhauer** [comment]
Also name everything consistently:

* record (instead of log entry, etc)
* job (instead of task)

**Comment by ThorbenLindhauer** [comment]
Protocol changes:

* SBE Layer:
  * See the diff here: https://github.com/zeebe-io/zb-protocol/compare/78ca0acb034e31ea72a8f6c76771546cca6fc4b7...a27fde4a7167bd05f0cbe2f2cea5dd2cdce7050c#diff-aa3cfd0b2c72db625cc18431127e4ab4
  * For the meaningful values of the `intent` field, see the `*Intent` enums that the diff includes
* Command/Event value layer (message pack): 
  * all the `state` properties are removed (replaced by `intent` in SBE layer)
  * Records of type `INCIDENT`:
    * Property `taskKey` is now `jobKey`
