### ISSUE TITLE
Separate workflow and flow node instance events

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#799]
In the client, workflow and activity (flow node) instance events are both represented by `WorkflowInstanceEvent`. This is problematic for the following reasons:

* The name `WorkflowInstanceEvent` does not suggest that this can represent a flow node instance
* In order to separate workflow instance events from flow node instance events, users have to interpret the workflow instance state enum correctly
* Certain event properties do not apply to both types of events and are therefore confusing. Example: Start a workflow instance, an instance of `WorkflowInstanceEvent` is returned. This class has a method called `#getActivityId` which makes no sense here. So users have to know when which property is valid, which is not obviouis.
* `FlowNodeInstanceEvent` is maybe not the term people who have never read the BPMN spec (aka most people) could relate to

**Comment by menski** [comment]
Let's talk about that again after we discussed how to further implement BPMN.

**Comment by menski** [comment]
@ThorbenLindhauer do you think this still makes sense?

**Comment by ThorbenLindhauer** [comment]
No, a common value type looks better, as these elements share a common lifecycle. I have created https://github.com/zeebe-io/zeebe/issues/1528 as a follow-up.
