### ISSUE TITLE
Add cluster orchestration layer

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#806]
Responsibilities

- ensure replication factor is met (enough replicas of each partition exist)
- ensure balancing of partitions between nodes

**Comment by menski** [comment]
@meyerdan there a still some TODOs left, i.e. limit listener invocations to the topic name. And some tests are failing, but I you want you can already the general approach.

**Comment by menski** [comment]
I created the follow up issues #860 and #861
