### ISSUE TITLE
Improve lifecycle in raft

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#814]
- [x] use service container to fomally track states in raft (leader vs. follower vs. candidate)
- [x] this should stabilize raft and make it possible to depend on states (leader vs. follower) in the broker (ie. stream processor needs to depend on leader state)
- [ ] review replication (should only send non-blocking after follower has acknowledged first event to make sure follower is not flooded with messages before they can be appended)

**Comment by menski** [comment]
@meyerdan can this be reviewed or this there more things to do?
