### ISSUE TITLE
Review & Simplify Configuration

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#815]
- Ensure all parameters make sense
- Remove non used parameters
- Document remaining parameters
- introduce simplified folder layout for partitions
- expose all raft and gossip options
- simplify configuration through top-level POJO class "BrokerCfg"
- make  it possible to configure byte values  using things like "16M" or "32K" ...
- fix resolution of configuration file relative to installation directory #803

**Comment by hawky-4s-** [comment]
@meyerdan: [This file](https://github.com/zeebe-io/zeebe/blob/master/docker/utils/zeebe.cfg.toml) should also be adjusted to the new config I guess.

**Comment by meyerdan** [comment]
No

**Comment by Zelldon** [comment]
I did the review. Should I directly change the things I found or do you want (have time) to do it ? Then we need a f2f meeting. 

Related question to the review:
Do we plan to write the documentation for the raft and gossip section?

**Comment by meyerdan** [comment]
Hi Chris,

Thanks!

It is best if you directly change what you want to change.

@menski  and I decided that we currently do not want to document the raft and gossip config settings since it is not a priority right now and we believe that users will hopefully not need to change them right now.

**Comment by Zelldon** [comment]
Alright thanks :)
