### ISSUE TITLE
Rename locking jobs to activating jobs

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#819]
Rename job locking to activating jobs which are assigned to a work with a deadline.

Client Job Worker Builder
- [ ] `lockOwner` becomes `name`
- [ ] `lockTime` becomes `timeout`

Msgpack Job Record
- [ ] `lockOwner` becomes `worker`
- [ ] `lockTime` becomes `deadline`

Broker Job Intent
- [ ] `LOCK_TASK` becomes `ACTIVATE`
- [ ] `TASK_LOCKED` becomes `ACTIVATED`
- [ ] `EXPIRE_LOCK` becomes `TIMEOUT`
- [ ] `LOCK_EXPIRED` becomes `TIMED_OUT`

<hr>
Original issue description:   

We should discuss the term locking an job. It indicates that it can only be changed/updated by the lock owner, which is not true ( the locking is more an assignment of an job). 

@ThorbenLindhauer first thoughts https://github.com/zeebe-io/zeebe/issues/802#issuecomment-382567666:
>The "locking" concept has three concerns. 1) assignment to a worker 2) exclusiveness 3) expiration. Ideally, I would like to have a term that conveys all three. "locking" covers 2, "assignment" covers 1 and (somewhat) 2.

**Comment by o314** [comment]
`Pinning` may convey those meaning. 
It seems to be more and more used nowaday.

**Comment by ThorbenLindhauer** [comment]
@o314 Do you know if *pinning* is used in any other software system for this concept? I have never heard of it in that context and it sounds a little counter-intuitive to me (makes me think pinning a note to a whiteboard)

**Comment by o314** [comment]
Pinning can be used in the context of dynamic placement of process too.


- cpu pinning
    - [openstack](https://docs.openstack.org/nova/pike/admin/cpu-topologies.html)
    - [ovirt](https://www.ovirt.org/documentation/sla/cpu-pinning/)
    - [kubernetes](https://insights.ubuntu.com/2017/03/27/job-concurrency-in-kubernetes-lxd-cpu-pinning-to-the-rescue)
- hpc pinning
    - [co-scheduling of hpc applications](https://books.google.fr/books?id=fgP0DQAAQBAJ&printsec=frontcover&=en&sa=X&ved=0ahUKEwio6d2xsdDaAhVLZFAKHebEAKUQ6AEIKDAA#v=onepage&q=pinning&f=false)
    - [case study on co-scheduling for hpc applications](https://www.computer.org/csdl/proceedings/icppw/2015/7589/00/7589a277.pdf)
    - [learning-based dynamic pinning of parallelized applications in many-core systems](https://www.semanticscholar.org/paper/Learning-based-Dynamic-Pinning-of-Parallelized-in-Chasparis-Janjic/f95ff14f0b28e9ea7799e9b3745e6dc68015b0f5)
- thread pinning
    - [performance evaluation and analysis of thread pinning strategies on multi-core platforms](https://ieeexplore.ieee.org/document/5999834/)
- process pinning
    - [efficient dynamic pinning of parallelized applications by distributed reinforcement learning](https://www.researchgate.net/publication/304505761_Efficient_Dynamic_Pinning_of_Parallelized_Applications_by_Distributed_Reinforcement_Learning)
- task pinning TBD
- job pinning TBD



The van der aalst box explains it well in my opinion
![the three dimensions of workflow](https://user-images.githubusercontent.com/4026002/39126835-b3e71af2-4703-11e8-88ec-84352a6d65da.png)

You pin into one or multiple dimension of the process context.

I found lock is more associated with database. Mutex lock too.
But that does not reflect as well the distributed and multidimensional duty of orchestration.

**Comment by Zelldon** [comment]
> I found lock is more associated with database. Mutex lock too.

Yeah I agree with that. 

Personally for me the biggest problem is, that lock indicates it can only be changed/updated by the lock owner. Currently retries etc. can be updated even if you are not the lock owner. I think this is confusing.

**Comment by menski** [comment]
What about lease. It implies an exclusive access to a entity, in our case the job completion. And also normally has a timeout which could be activitly extended.

Pinning for me has the notion to be an one time operation like thread pinning. And will normally not timeout nor change. Locking could be understood as exclusive write which is not true in case of update retries. Where it's common that a lease can be revoked based on changes of the system.

**Comment by berndruecker** [comment]
My personal opinion: `Lease` (or `pin`) will always make people think what this is about. `Lock` is very intuitive - so I would still prefer it. We could clearly document the scope of the lock to avoid confusion.

**Comment by o314** [comment]
It the policy is to not be uniquely and definitively assignable, lease could be better than pin.

Leasing is quite common i believe - think car leasing, a rental without explicit renewal.
i knew it from .net remoting, the former framework of microsoft before .net framework windows communication foundation (wcf). For me it was one a good modeled part of the fx.

**Comment by menski** [comment]
Decision: A task is active when it is assigned to a job worker.

Builder Naming:
lockOwner -> name
lockTime -> timeout

Task Event:
lockTime -> deadline
lockOwner -> worker

Task State:
LOCK_TASK -> ACTIVATE
TASK_LOCKED -> ACTIVATED
EXPIRE_LOCK -> TIMEOUT
LOCK_EXPIRED -> TIMED_OUT

**Comment by menski** [comment]
I updated the issue title and description to reflect our decision
