### ISSUE TITLE
Subscriptions stall

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#822]
Occasionally, task and topic subscriptions no longer receive events.

Conditions for this behavior:

* Version 0.8.0 (haven't checked later versions)
* Create more tasks than subscription capacity (in my case 125 workflow instances with capacity 32; may have to be repeated a couple of times to reproduce)
* Run broker with more than one cpu-bound thread (5 in my case due to autodetection; we have 1 in our CI)

After some testing, the third points seems crucial, so I suspect there's a race condition somewhere. Wasn't able to reproduce it in an integration test yet.

Maybe required conditions to reproduce:

* A workflow with two tasks of different types
* Active task subscriptions for both types (I only saw the subscription for the type of the second task stall)

**Comment by menski** [comment]
Topic subscriptions are no longer supported. Job worker are not a subscription anymore.
