### ISSUE TITLE
CI: Run broker with more than one cpu-bound thread

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#823]
Makes it more likely that we detect race conditions. Followup of #822.

**Comment by ThorbenLindhauer** [comment]
Also, the broker config option `numberOfThreads` is `cpu-bound + io-bound` where io-bound threads are always 2. E.g. when I put in 2, I receive 1 cpu-bound and 2 io-bound threads. This is not intuitive. If io-bound is always statically 2, then `numberOfThreads` should configure the number of cpu-bound threads.

**Comment by menski** [comment]
Regarding the comment by @ThorbenLindhauer this behavior was removed and now the scheduler uses the configured values without magic, see https://github.com/zeebe-io/zeebe/blob/61f768f70dd02f32795b9321c57d23f0a5b6446c/broker-core/src/main/java/io/zeebe/broker/system/SystemContext.java#L123-L134

**Comment by menski** [comment]
@ThorbenLindhauer I assume that we should change the whole test suite to more the one cpu thread? Or should it be only for specific tests?

**Comment by ThorbenLindhauer** [comment]
I'd say the default in the test suite should be more than one thread.

**Comment by menski** [comment]
I changed the default value of cpu threads to 2 as it was already the default for the distribution I didn't thinks it should be a problem. Commit is https://github.com/zeebe-io/zeebe/commit/2917a9075978200f2de4248856f3c9d40a3916ea. I adjusted all tests I found locally which had problems with multiple threads. If we discover more we will fix them afterwards.
