### ISSUE TITLE
Improve Job worker section

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#840]
https://stage.docs.zeebe.io/bpmn-workflows/data-flow.html

"Tight coupling" often has negative connotations, so users may want to avoid it instinctively. It is valid and sometimes better usage, though. Let's try to find better terms to distinguish the use cases.

**Comment by saig0** [comment]
Current wording:

Payload is the link between workflow instance context and workers and therefore a form of coupling. We distinguish two cases:

1. **Tightly coupled job workers**: Job workers work with the exact JSON structure that the workflow instance payload has. This approach is applicable when workers are used only in a single workflow and the payload format can be agreed upon. It is convenient when building both, workflow and job workers, from scratch.
1. **Loosely coupled job workers**: Job workers work with a different JSON structure than the workflow instance payload. This is often the case when job workers are reused for many workflows or when workers are developed independently of the workflow.

Without additional configuration, Zeebe assumes *tightly* coupled workers.
