### ISSUE TITLE
Clustering test taking wrong assumptions

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#844]
Most of the clustering test are written before rewriting the clustering layer (which is now the base and orchestration layer). In the past it was possible to stop a broker and work with the remaining ones after a new leader was chosen. This is no longer fully true. If the replication is undershot, the leader partition service will be removed and this means task creation or topic requests are no longer possible. 

This means we should have two kinds of tests:

 1. Starting three brokers and stopping one, then nothing should be possible anymore
 2. Starting four brokers and stopping one, the replication service should invite the fourth broker, which means the replication factor is satisfied. Then the task creation etc should work again.

With this kind of tests we ensure that the replication factor service work as expected and that nothing bad happens if the replication factor is undershot.

**Comment by menski** [comment]
What changed is that a broker who is shutdown now leaves the raft group. Before it would stay member and therefore the replication factor was not changed. So for the old tests we need a way to either prevent a graceful shutdown or to isolate the broker from transport.

Tests which will check that the broker rejects commands or reinvites members are new tests in my opinion.

**Comment by Zelldon** [comment]
> What changed is that a broker who is shutdown now leaves the raft group. Before it would stay member and therefore the replication factor was not changed. So for the old tests we need a way to either prevent a graceful shutdown or to isolate the broker from transport.
Yeah, missed to mention that, thanks. Again we have the problem that we don't know how to isolate them or 'prevent a graceful shutdown'.

> Tests which will check that the broker rejects commands or reinvites members are new tests in my opinion. 
True. I added some already.

**Comment by menski** [comment]
> Nevertheless I think we should also have tests which ensures that the replication service works as expected.

Yeah of course we need here more tests. My comment was only about the already existing tests. I think they are still valid and we need to find a way to recreate the expected scenario of the test.

**Comment by Zelldon** [comment]
Ok agree

**Comment by Zelldon** [comment]
we migrated to atomix and test are now valid and enabled again
