### ISSUE TITLE
In StreamProcessor, I can process an Event Asychronously

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#848]
General use case:
- in the processEvent() Method I want to do an async action like sending a request

Our immediate usecase: #843

**Comment by meyerdan** [comment]
Also see https://github.com/zeebe-io/zb-logstreams/commit/baf33e4ce135d1b1f4b719e8cb23df3a257bacfb

**Comment by meyerdan** [comment]
@npepinpe I assigned you here to do a review. We can use it as an opportunity to look into how we do reviews.

**Comment by npepinpe** [comment]
Looks good, as discussed I refactored out AsyncContext from EventLifecycleContext (see above commits).
