### ISSUE TITLE
Add timestamp property to every record in the logstream

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#849]
Add timestamp prtoperty to every record in the logstream, as the time it was written at, using ActorClock. This is primarily to help users visualize a timeline of all events that occurred up to a certain point.

**Comment by npepinpe** [comment]
After discussing it, we decided to add a LogStreamWriterClock which would wrap around the ActorClock to typically provide access to the current ActorClock's time, but in the case where a call is made outside of an actor thread (as far as I can tell only in testing), it would fallback to the system time.

Although, @meyerdan, maybe that's something that could be conflated into the ActorClock in general, instead of throwing an UnsupportedOperationException? I mean, most things are scheduled through actors anyway, is the guard clause here extremely important?

**Comment by meyerdan** [comment]
I see the problem. Personally I would for now just add some if statements in the writer checking whether we are actor or not and then, when we have the full extend of the feature come back and focus on it and find a good solution.

**Comment by npepinpe** [comment]
A few notes:

1. Calling ActorClock.current now returns null outside of an ActorThread (maybe use Optional? Though that doesn't seem too used in the codebase atm) vs throwing UnsupportedOperationException. There was only one other usage outside of ActorClock which was done in an Actor, and wasn't checking for the exception anyway.
2. Calling ActorClock.currentTimeMillis will now fallback to System.currentTimeMillis when called outside an ActorThread.
3. Testing specifically for timestamp values in LogStreamWriter/LogStreamBatchWriter is done by using a ControlledActorScheduler, which is a little verbose I guess, the option being to inject an optional clock into the writer (e.g. use ActorClock.currentTimeMillis or the injected clock). I have no strong preference to be honest, so if whoever reviews does, feel free to insist on one.

**Comment by meyerdan** [comment]
@npepinpe I reviewed it, looks good! I did a minor edit: https://github.com/zeebe-io/zb-logstreams/commit/a03cae560d1c64dd5a49bacb7a70ff4f0e9c937c
