### ISSUE TITLE
Add timestamp property to record interface in the Java client

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#851]
Related to #850 

Client should read and make available to the user the timestamp property of each record (whether a command response or from a subscription).

**Comment by ThorbenLindhauer** [comment]
Review:

* Test that events obtained from command responses contain the correct timestamp value
* `RecordMetadata#getTimestamp` can return an instance of `java.time.Instant` instead of a `long`. This would be consistent with e.g. `JobRecord#getLockExpirationTime`
