### ISSUE TITLE
Cluster: Node topology may not return all cluster nodes

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#854]
Scenario:

* Start a cluster of four broker nodes
* One bootstrapping node (i.e. system partition has one replica)

Current behavior:

* Client requests topology during a request. It can happen that a cluster node permanently returns an incomplete topology response. It seems that the bootstrapping node (=> system partition leader) is missing, so the client can no longer deploy workflows, etc.

@felix-mueller is able to reproduce this.

**Comment by Zelldon** [comment]
I'm currently not able to reproduce this. How the configuration files look like? Do they have all the same initial contact point? Bootstrap is set to 1 right?

I tested it with 3 and 4 brokers. The fourth broker also had a different contact point. How do you request the topology? Via zbctl or the java client? I used for the test the zbctl (0.9.0) and the clustering rule in integration tests.

@felix-mueller do you have more insights on this?

**Comment by Zelldon** [comment]
Outdated. Please reopen if you think this issue still exist.
