### ISSUE TITLE
Reiterate sending of requests in transport

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#858]
## Current drawbacks

There are 2 problems with the way sending of requests in transport is implemented:

* Handling of multiple remotes (brokers): in the case the transport needs to send messages to multiple brokers, the current behavior has the following drawbacks:
    * Poor batching: when consuming from the ringbuffer, we can only send a consecutive block of memory as a batch. If many small messages for different remotes are present on the buffer, batching goes away
    * No async sending to different brokers concurrently: since messages are consumed from the ringbuffer in blocks, one block blocks the next block :) we always need to fully send a given block to it's remote, until we can proceed to the next block. Or in other words, while we are getting backpressure from one broker, we cannot concurrently send to another broker on a different channel.

* Blocking behavior of requests: Currently, we can send requests asynchronously up to a configurable number. Once this number is reached, the user must await and *close()*! the first request future. This is a problem since users need to write somewhat awkward handling logic of async requests. [See example](https://github.com/zeebe-io/zeebe-cluster-tests/blob/master/java/src/main/java/io/zeebe/BenchmarkRunner.java#L70-L124). It would be better if receiving of responses would make it possible to send new requests again, instead of having to close() the responses.

## New solution

This issue provides a new implementation which achieves these two goals.

First, the ring buffer in the sender is removed, and now, a queue of request batches is managed per channel and the sender can write to these channels concurrently. This means that:
* backpressure from one broker does not influence ability to send data to other brokers anymore
* batching of requests is implemented on a per-remote basis.

Second, the transport now maintains a pool of memory available to new requests. When a response is received (or a request timeout occurs), the memory is reclaimed. This means that when the client reaches the capacity of this pool, it will only block until the next response is received, the user does not have to close() the response.

## Benchmark

![image](https://user-images.githubusercontent.com/488063/40014483-ff1b0e76-57b0-11e8-9299-3c9dae65e052.png)

## Progress

- [x] implementation pushed to master
- [x] gossip, raft and broker adjusted
- [x] client adjusted (talk to @ThorbenLindhauer )
- [x] cleanup & remove dead code
- [x] client topology currently blocks on memory backpressure which we do not want.

**Comment by meyerdan** [comment]
Jenkins agrees: 

![image](https://user-images.githubusercontent.com/488063/40015557-07dcf2f6-57b4-11e8-9747-e62b9abdb2ab.png)

Messages are not slower (a little bit faster even)

![image](https://user-images.githubusercontent.com/488063/40015582-1f7a07e6-57b4-11e8-84f5-e4e28281a7d3.png)

**Comment by ThorbenLindhauer** [comment]
We added a fix to make `ClientResponse#getRemoteAddress` work, see https://github.com/zeebe-io/zb-transport/commit/b38cd54fda800a0d289a2d262989334148627fd5. I suggest we add a test case for that.

**Comment by meyerdan** [comment]
@ThorbenLindhauer  there is the remaining challenge with the fact that the topology request in the client should not fail / be delayed on memory backpressure. We need to add the possiblity when sending a request to control whether it allocates a buffer from the limited pool or not. Should be straight forward, I will look into it while finalizing this issue, just wanted to let you know that this is still open.

**Comment by ThorbenLindhauer** [comment]
Got an `EXCEPTION_ACCESS_VIOLATION` JVM error running the integration tests that seems related to the changes made here. See error report below.

[hs_err_pid4852.log](https://github.com/zeebe-io/zeebe/files/2008372/hs_err_pid4852.log)

**Comment by meyerdan** [comment]
Foollow up issue #904

**Comment by menski** [comment]
I changed the default send buffer size of the client to 2 megabytes. This could prevent some user confusion as it might prevent client timeouts at the current situation. We should reevaluate this value after we tackled the backpressure topic (#904).
