### ISSUE TITLE
Raft configuration may contain wrong initial member on receiving multiple invitation requests

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#867]
If a node receives a invitation request for a partition it reads the initial member from the request
https://github.com/zeebe-io/zeebe/blob/6f11674f98f9d96425b0b6c68bec4901fb17724e/broker-core/src/main/java/io/zeebe/broker/clustering/api/ManagementApiRequestHandler.java#L128

After that this list is used to create the raft configuration _asynchronously_
https://github.com/zeebe-io/zeebe/blob/6f11674f98f9d96425b0b6c68bec4901fb17724e/broker-core/src/main/java/io/zeebe/broker/clustering/api/ManagementApiRequestHandler.java#L144

If another invitation request is received before the configuration is written the list of initial members is overwritten with the other request content
https://github.com/zeebe-io/zeebe/blob/6f11674f98f9d96425b0b6c68bec4901fb17724e/broker-core/src/main/java/io/zeebe/broker/clustering/api/InvitationRequest.java#L177-L194

**Comment by npepinpe** [comment]
The test case you added passes when I revert the changes in ManagementApiRequestHandler and increase the test timeout (although it only times out from time to time without increasing).

I don't have a good solution on how to make this more controlled, except perhaps with a functional test (there's a ManagementApiRequestHandlerTest class now so it would be a little easier to add tests there).
