### ISSUE TITLE
Move broker and client benchmarks to jmh test folder

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#868]
Currently we have benchmarks in the main source folder of the broker and client. 

Do we need them? Do we execute them regularly? They can not be compiled. Every time I do an `mvn clean install` my Intellij complains that there a compilation errors. Every time after the `mvn clean install` I have to exclude them from the module. 

Perhaps we can move them into an own jmh test suite like the other benchmarks or we simply remove them.

**Comment by menski** [comment]
We will try to move them to a JMH test folder similar to other repos

**Comment by menski** [comment]
It seems the JMH report plugin for jenkins only supports a single report file. So we execute the benchmarks on Jenkins but don't have the report integration enabled for now.

**Comment by Zelldon** [comment]
Thank you :tada:

**Comment by Zelldon** [comment]
Nice :tada:
