### ISSUE TITLE
Stream processor state contains last position which changed state of statemachine

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#870]
Every stream processor which handles commands saves the position of the last record which changed its state. A command has to reference the position of the record which changed the state as `sourcePosition`. The stream processor validates if the `sourcePosition` is equal to the last changing record position, otherwise the command is rejected. If the state is changed by the command (e.g. it is accepted), the last position in the state of the stream processor is updated.

**Comment by ThorbenLindhauer** [comment]
We should also check how this can work with *cancel workflow instance* commands. This command creates events of multiple state machines (workflow instance and activity instances). With our envisioned mechanism we could detect a concurrent update on the workflow instance, but maybe not on the activity instances. We may have to improve our approach to concurrent update detection or change how cancellation works.

**Comment by Zelldon** [comment]
With help of the the source pointers (https://github.com/zeebe-io/zeebe/issues/869) I was able to visualize the state machines, perhaps this makes it easier for us to discuss this topic tomorrow. 

I also added some questions to the slides. 
[RejectCommands.pdf](https://github.com/zeebe-io/zeebe/files/2045490/RejectCommands.pdf)

**Comment by menski** [comment]
We reworked the workflow instance stream processing and this is not needed anymore
