### ISSUE TITLE
Java Client backwards/forwards compatiblity

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#874]
Ticket to collect requirements and things that may impact backwards/forwards compatibility of the client (i.e. client in Vesion Y can work with brokers in versions X and Z where X < Y < Z).

* JSON (De-)Serialization: Broker Z may publish records of value types that the client Y does not know; client should be able to serialize this to JSON; This JSON can be deserialized with client Z
* JSON (De-)Serialization: Broker Z may send a record property that client Y does not know; client should include this property in serialized JSON and on deserialization and command creation send it back to the broker (in order to not drop property values)
* JSON (De-)Serialization: Client Z can deserialize JSON generated by Client Y. This may require including the client/protocol version in the JSON.

**Comment by npepinpe** [comment]
This is somewhat outdated since we switched to Protobuf for the client. However, we still the issue with the broker clients where this is poorly implemented. I would propose we open a new issue however as all this shares is the name, since the requirements are not the same any more.
