### ISSUE TITLE
Provide management API endpoint to query list of snapshots per partition

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#876]
Management API exposes an endpoint which returns, for a given partition if it is the leader, the list of current snapshots, where each element is a triple as:

* snapshot name
* length in bytes
* checksum

**Comment by npepinpe** [comment]
Note: there's currently only unit/functional tests, since there's no consumer for this endpoint yet (see #877). So tracking of leader partitions is not tested at the moment.

**Comment by menski** [comment]
Please make sure that we exclude the log block index from the list of snapshots as it cannot be replicated as it depends on the physical addresses of the logstream.

**Comment by meyerdan** [comment]
Closed with minor edits in b5d2921
