### ISSUE TITLE
Drop custom framing in favor of SBE 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#892]
Currently our client protocol is a layer of custom framing, i.e. DataFrameHeader, TransportHeader, optional RequestResponseHeader, and then SBE messages. Also there are some interesting features in the data frame which applies alignment of the message size. This framing was applied to work correctly with the dispatcher implementation. It also exposes internal information to the client which is not required for the protocol. As there is the chance that we will remove the Dispatcher completely from the code base. It might also be worth the effort the remove the custom framing in favor of only having a SBE schema for all client interaction. This might ease the development of new clients as there are different language generators for SBE already. 

Base on first discussions we think it should be possible to add all values required from the custom framing to the SBE protocol. This has to be checked before making a decision.

We should decide this before the 1.0 release. Personally I'm in favor in dropping all custom framing and only use SBE.

**Comment by npepinpe** [comment]
Can you elaborate on this? Our transport was largely rewritten - do you mean the data frame in the dispatcher? If so I guess we still use it - this could be part of #3856 then.

**Comment by menski** [comment]
We replaced our custom transport with atomix so this is not relevant anymore.
