### ISSUE TITLE
An user can subscribe to all deployment events

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#901]
### Scenario 

An application wants to present all workflows deployed to Zeebe. Currently this requires to regularly poll the workflow repository API to fetch all workflows. This is suboptimal as it can lead to unneeded overhead on client and broker side as it always fetches all workflows again and again. Also if the number of deployed workflows exceeds the maximum size of a response message the behavior is unclear.

### Idea

Add the possibility create a deployment subscription which will receive all deployed workflows. This would require the possibility to create a subscription on the internal system topic which is currently not possible.

**Comment by menski** [comment]
@saig0 if you have any further thoughts on this please add it to this ticket. thanks.

**Comment by menski** [comment]
We plan to also push topic events over this subscription so a user can subscribe also to topic creation to get notified about new topics.

**Comment by saig0** [comment]
**Protocol change** 
* on Msgpack layer: 
  * event of type 'deployment': add property 'resourceName' under 'deployedWorkflows'

**Comment by menski** [comment]
I accidentally already implemented that protocol change in zbc-go
https://github.com/zeebe-io/zbc-go/blob/555e3cb10d828299c500a4aaf6a71bec1a798e62/zbc/models/zbmsgpack/workflow.go#L20

**Comment by ThorbenLindhauer** [comment]
Review:

* merge `DeployedWorkflow` and `Workflow` interfaces in client to make it easier for people to understand and use
* may require some changes in broker
