### ISSUE TITLE
Change default behavior of output mapping to merge

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#907]
If no output mapping is given the default will be a flat top level merge with override. Which means all top level properties of the source payload are merged into the target payload with overriding of already existing properties with the same name. Which means there will be no nested merged for nested objects. If both source and target payload contain a `foo` property object, the result will have the `foo` property object from the source payload overriding the `foo` from the target payload. All none overridden properties from target are kept.

**Comment by Zelldon** [comment]
Changed the default output mapping behavior to top-level merge.
If no mapping is given to the mapping processor he will simply do the top-level merge.
The overwrite is still possible via root level mapping (`$` -> `$`), which will simply overwrite the target document. The top-level merge is also possible via mappings but is ten times slower, see the results of the new merge jmh benchmark:

```java
# Run complete. Total time: 00:03:14

Benchmark                                    (keyCount)   Mode  Cnt      Score     Error  Units
MergeBenchmark.overwriteDocument                    100  thrpt    5  39106.498 ± 419.154  ops/s
MergeBenchmark.overwriteDocument                   1000  thrpt    5   3632.108 ±  35.467  ops/s
MergeBenchmark.overwriteDocument                  10000  thrpt    5    339.547 ±   4.440  ops/s
MergeBenchmark.topLevelMergeDefaultBehavior         100  thrpt    5  13344.668 ± 413.637  ops/s
MergeBenchmark.topLevelMergeDefaultBehavior        1000  thrpt    5   1161.495 ±  35.421  ops/s
MergeBenchmark.topLevelMergeDefaultBehavior       10000  thrpt    5     92.912 ±   1.188  ops/s
MergeBenchmark.topLevelMergeViaMappings             100  thrpt    5    949.264 ±  44.458  ops/s
MergeBenchmark.topLevelMergeViaMappings            1000  thrpt    5     10.319 ±   0.210  ops/s
MergeBenchmark.topLevelMergeViaMappings           10000  thrpt    5      0.090 ±   0.012  ops/s
```

The old msgpack benchmarks should also be ported to jmh and they should be executed on jenkins as well. I created an issue for this https://github.com/zeebe-io/zeebe/issues/921 .

**Comment by menski** [comment]
@Zelldon I didn't find a commit or an issue about updating the documentation to the new default behavior?

**Comment by Zelldon** [comment]
Because there is none 😅sorry
