### ISSUE TITLE
Add custom XML attribute to configure override behavior of output mapping 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#908]
I can set a custom Zeebe BPMN XML attribute to indicate that the payload should be overridden by a output mapping. In this case the resulting payload is the one provided by the job completed event.

Decide if we support override + output mappings. If not supported throw an validation error. Otherwise if supported the behavior should be that the output mappings are executed with an empty target payload instead of the original target payload of the workflow instance.

**Comment by saig0** [comment]
When we kown how it will look like then we should create an issue for the zeebe-monitor.

**Comment by menski** [comment]
@saig0 why Monitor? Or do you mean Modeler?

**Comment by ThorbenLindhauer** [comment]
Can we also have a flag for *do not change workflow instance payload* and then remove the completion-without-payload API? Then, the payload merging logic is entirely described by the workflow model and the client API is clearer in my opinion.

**Comment by menski** [comment]
What does the `withoutPayload` API actually means? I never really understood this.

**Comment by ThorbenLindhauer** [comment]
> I never really understood this.

Exactly the reason I'd like to remove it :)

See https://stage.docs.zeebe.io/reference/json-payload-mapping.html#semantics. You can use it to leave the workflow instance payload unchanged (in contrast to providing a payload, which would overwrite the workflow instance payload).

**Comment by menski** [comment]
> You can use it to leave the workflow instance payload unchanged (in contrast to providing a payload, which would overwrite the workflow instance payload).

But with the new default behavior the payload would not be overridden anymore, if you provide a payload or not. Do we then still need the feature to *do not change workflow instance payload*?

**Comment by ThorbenLindhauer** [comment]
I think the use case would be workers that need a mapped input payload but do not produce output. For example:

* worker receives a job with payload that was created via input mappings
* worker completes job, leaving payload as is
* now output mapping is applied. Merge would not be desired (the new default). Replacing the workflow instance payload with the job payload (the new flag) would also not be desired.

**Comment by ThorbenLindhauer** [comment]
With the current implementation, you need to know both Java code and XML to understand how the workflow payload changes in this case. I think it's easier to use if the workflow definition is the single point of truth.

**Comment by menski** [comment]
Fair point. I created an issue for this feature #911.

**Comment by Zelldon** [comment]
Question how do you guys think it should look like:

### Option A: As task attribute
```xml

    <bpmn:serviceTask id="ServiceTask_1bdglb9" name="TaskOne" overwritePayload=true>
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="test" retries="3" />
        <zeebe:ioMapping>
          <zeebe:input source="sourceValue" target="targetValaue" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>SequenceFlow_1fswtdm</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_02v8vv2</bpmn:outgoing>
    </bpmn:serviceTask>
```
### Option B: As ioMapping attribute
```xml
    <bpmn:serviceTask id="ServiceTask_1bdglb9" name="TaskOne">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="test" retries="3" />
        <zeebe:ioMapping outputOverwrites=true>
          <zeebe:input source="sourceValue" target="targetValaue" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>SequenceFlow_1fswtdm</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_02v8vv2</bpmn:outgoing>
    </bpmn:serviceTask>
```
### Option C: As output attribute
```xml
    <bpmn:serviceTask id="ServiceTask_1bdglb9" name="TaskOne">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="test" retries="3" />
        <zeebe:ioMapping outputOverwrites=true>
          <zeebe:input source="sourceValue" target="targetValaue" />
          <zeebe:output overwrite=true />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>SequenceFlow_1fswtdm</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_02v8vv2</bpmn:outgoing>
    </bpmn:serviceTask>
```

Personally I would prefer option B I think.

**Comment by ThorbenLindhauer** [comment]
How about `<zeebe:ioMapping defaultOutput="overwrite">` where other options could be `none` (for https://github.com/zeebe-io/zeebe/issues/911) and `merge` (which would also be the default). Could then be easy to map to a dropdown in the modeler.

**Comment by Zelldon** [comment]
Yep like the idea. What do you think @menski ?

**Comment by menski** [comment]
I would add it as attribute to `zeebe:ioMapping`, and as Thorben suggested make it a String. I wouldn't call it `defaultOutput` as it might be useful to use in combination with output mappings. So I would suggest something like `outputBehavior` or `outputType` or similar.

**Comment by Zelldon** [comment]
Hm I'm not quite sure about the second point. On `outputBehavior=merge` and given output mappings, it will merge OK and on overwrite it could be like described above. But how should this look like if you have `outputBehavior=none` and an output mapping? Would it not be inconsistent if we have THEN a validation error?

**Comment by menski** [comment]
Yes `outputBehavior=none` + output Mappings does not make much sense. So either validation error or warning.

**Comment by Zelldon** [comment]
@saig0 I created for yaml an extra issue #930

**Comment by saig0** [comment]
Review Hints:
* BPMN Model API:
  * validation of JSON path/el in transform: list all errors in same validation format (line number + acitivity id)
  * write test cases in BpmnBuilderTest and BpmnParserTest
* WorkflowInstanceStreamProcessor/ActivityCompletingEventProcessor: don't need to get the payload from cache if the output behavior is 'overwrite'
