### ISSUE TITLE
I can deserialize the payload of a JobRecord as a Java Class

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#910]
The client provides a method `<T> T JobRecord#payloadAsClass(Class<T> clazz)`. It uses the default ObjectMapper inside the client to attempt a deserializing of the Job payload. If the user wants to use a different deserializer the JSON String can still be used for custom implementations.

Corresponding it is possible to provide a Java Class Instance to set the payload of a `CompleteJobCommand`.

**Comment by ThorbenLindhauer** [comment]
I propose to use a separate zero-configuration `ObjectMapper` for this to avoid coupling this API to the configuration for record (de-)serialization. Then the behavior is also very clear to document and understandable by users.

**Comment by menski** [comment]
Makes sense, we can discuss this in more detail when we address this issue. But thanks for the feedback.
