### ISSUE TITLE
I can mark tests in all projects as unstable

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#923]

**Comment by ThorbenLindhauer** [comment]
Building all projects via the `build` module and profile `skip-unstable-tests` fails because not all modules have `zb-test-util` as dependency and the surefire-plugin tries to eagerly load the category class.

**Comment by ThorbenLindhauer** [comment]
Decided to go with the profile-per-module approach.

**Comment by menski** [comment]
This is now possible with 9a276fcae2b99e9be6227cc200183d80b846532c

The UnstableTest class is now inside the zb-build-tools module which is now part of the mono repository. Also the zb-build-tools are now a test dependency for every project, which allows us to mark any test in the zeebe repository as unstable.
