### ISSUE TITLE
Regular processing can interfere with reprocessing

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#926]
The fix for https://github.com/zeebe-io/zeebe/issues/905 introduced a regression such that a stream processor may start regular stream processing while it is still reprocessing. Here is how:

* a stream processor can be resumed from the outside via `StreamProcessorContext#resumeController`
* This will always submit the `#readNextEvent` runnable to the stream processor's actor, which triggers regular stream processing
* it is possible that the stream processor controller is still reprocessing at that point
* so then regular processing and reprocessing run concurrently and mess up shared datastructures, most notably the log stream reader and current event

Impact: It looks like we only use the resume API for `ActivateJobStreamProcessor`, so I think only job workers are affected.

This was introduced by #905 because before reprocessing was a single actor job that could not be interrupted.

This is the root cause for the exception in #925.

**Comment by menski** [comment]
@saig0  please review this issue today as I should be part of the patch release. Thanks
