### ISSUE TITLE
Job activating stream processor consumes credits without pushing jobs on reprocessing

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#928]
Scenario:

* Create a job subscriber
* This starts a new stream processor that activates jobs of the given type (`ActivateJobStreamProcessor`)
* This stream processor does reprocessing first
* In `#processRecord`, it selects a random subscriber
* In `#updateState` it decrements that subscriber's credits
* In consequence, credits are consumed for records that are never published

This should not happen. In fact, reprocessing does not make sense for `ActivateJobStreamProcessor` because it keeps no index state anyway.

**Comment by menski** [comment]
job subscriptions are removed
