### ISSUE TITLE
Payload is always a document

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#933]
In order to handle the payload uniform, the payload must be always a document (instead of NIL). 

AT:
* create a workflow instance / job with an empty document as payload if no payload is provided
* reject the creation if the payload is not a document

**Comment by Zelldon** [comment]
Notes for myself:

Affected functionality are:

 - [ ] update payload (wf and activity)
 - [ ] complete job
 - [ ] create workflow instance

Should have test for:

 - [ ] create workflow instance
   - [ X ] empty payload ("null")
   - [ X ] invalid payload
   - [ X ] no payload
   - [ X ] zero length payload
 - [ ] complete job
   - [ ] empty payload ("null")
   - [ ] invalid payload
   - [ ] no payload
   - [ ] zero length payload
 - [ ] update payload (wf and activity)   
   - [X ] empty payload ("null")
   - [ X ] invalid payload
   - [ X ] zero length payload

**Comment by Zelldon** [comment]
Sorry :sweat_smile:
