### ISSUE TITLE
Workflow execution may stop on system partition leader change

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#954]
Noticed this reading the code in `WorkflowCache`, it seems this line should use `!equals`: https://github.com/zeebe-io/zeebe/blob/0.10.1/broker-core/src/main/java/io/zeebe/broker/workflow/map/WorkflowCache.java#L229

**Comment by Zelldon** [comment]
closes by removing workflow fetching #1165
