### ISSUE TITLE
Connection to broker fails on Windows 7 with Docker Toolbox

### ISSUE THREAD

**Issue by fjakop** [zeebe-io/zeebe#971]
I'm trying to use zeebe as docker container on Windows 7 and ` docker run --name zeebe -p 51015:51015 camunda/zeebe` starts up fine. 
Since Windows 7 runs a separate Linux VM (virtualbox) I forwarded `localhost:51015 --> IPofLinuxVM:51015`. (this kind of forwarding works fine when it comes to http connections to different REST exposing apps which also run in docker containers)
Now when I try to connect like this
```
final Properties clientProperties = new Properties();
clientProperties.put(ClientProperties.BROKER_CONTACTPOINT, "localhost:51015");

final ZeebeClient client = ZeebeClient.newClientBuilder()
        .withProperties(clientProperties)
        .build();

client.topicClient("default-topic").workflowClient()
        .newResourceRequest().bpmnProcessId("order-process").latestVersion()
        .send()
        .join();
```
the connection times out after 15s and yields 
`io.zeebe.client.cmd.ClientException: Request timed out (PT15S). Request was: [ target topic = null, target partition = 0, type = GET_WORKFLOW]`

Are there other ports to be considered forwarding? I also tried to add 51016 and 51017 with no luck.

**Comment by fjakop** [comment]
Well thanks, but no change when I start with `docker run --name zeebe -p 51015:51015 -e ZEEBE_HOST=0.0.0.0 camunda/zeebe`

**Comment by jwulf** [comment]
See here: https://github.com/docker/for-win/issues/204#issuecomment-303461340

**Comment by Zelldon** [comment]
I will close this due to inactivity, feel free to reopen this
