### ISSUE TITLE
Dangerous usage of service container dependencies with follower partition service

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#974]
I tracked down the issue of installing the follower partition service on raft state changes (or lack of) due to a limitation (? not sure if even to call it that) of the service container.

In this particular case, we have 2 services, the raft follower service (Rn, e.g. R0 for term 0, R1 for term 1, etc.), whose service name is based on the `topicName-partitionId.term` and the partition follower service (P), whose service name is based on `topicName-partitionId`, where P is dependent on Rn.

Rn is installed/removed by Raft on transition changes, which occur when changing raft state, or changing raft term.

P is installed on raft state changes through `RaftStateListener#onStateChange`. This is triggered on state change or term change, after Rn has been installed. P is dependent on Rn, so when Rn is removed, P is removed. 

The issue is that installing/removing, and raft state changes, all happen asynchronously. So the following sequence can happen:

1. Install R0, notify state listeners.
1. Since P is not installed yet, schedule P to be installed, with a dependency on R0.
1. Raft state changes (e.g. term change).
1. Before P is installed and marked as a dependent of R0, R0 is removed.
1. P is installed and waits for dependencies.
1. R1 is installed, notify state listeners.
1. P is already installed (though waiting for dependencies), so don't install it.
1. P eventually gets DEPENDENCIES_UNAVAILABLE and is removed.

P is never installed again until another raft state change.

I don't think this is really a bug, as I don't think it's up to the service container to handle this kind of scheduling. I don't actually have a good solution on how to make sure we avoid these kind of mistakes. If anyone does, please go for it, it's the kind of thing that is easy to miss in a review, and leads to unstable tests (as it can work most of the time). This can also happen with other services that have these kind of dependencies, and I imagine is more likely to happen the longer the dependency chain.

Related to #953

**Comment by Zelldon** [comment]
Maybe also the term in the partition service name would solve the problem?

**Comment by npepinpe** [comment]
It would, but it means remove/installing more often for potentially no reason, since the term by itself has no effect on the partition itself. I'm not 100% sure which is the best solution to be honest.

**Comment by Zelldon** [comment]
I see what you mean but I think it is better than no partition at all installed :grin:

**Comment by npepinpe** [comment]
So I'll close this unless anyone has an objection.

**Comment by Zelldon** [comment]
Hm ? I thought we need to use the term inside the name as well?

**Comment by Zelldon** [comment]
So it can happen that we have a follower without the partition installed?
