### ISSUE TITLE
Improve on the job stealing algorithm

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#998]
Currently the executors steal from the ActorTaskQueue one job at a time it could be better to steal more, like half of the queue. We should investigate on this, also maybe do some benchmarking.

**Comment by Zelldon** [comment]
Currently not easy possible since we it is a linked list and we don't know how many entries we have. We also saw no evidence that we need to improve here we have other bottle necks as far as I know.

**Comment by npepinpe** [comment]
Then I would propose to close this for now.
